In [2]:
import os
print(os.system("python -V"))

Python 3.12.3
0

In [9]:
import os

# Check environment variables
print(os.environ.get('ILOG_LICENSE_FILE'))
print(os.environ.get('CPLEX_STUDIO_DIR'))

# Print all CPLEX/ILOG related environment variables
for key, value in os.environ.items():
    if 'cplex' in key.lower() or 'ilog' in key.lower() or 'ibm' in key.lower():
        print(f"{key}={value}")

None
None

In [10]:
import cplex
c = cplex.Cplex()
print(c.get_version())

# Some installations store info here
import os
print(os.path.dirname(cplex.__file__))

22.1.1.0
/opt/env/modelseed_cplex/lib/python3.10/site-packages/cplex-22.1.1.0-py3.10.egg/cplex

In [12]:
import subprocess

# Search within the virtual environment
result = subprocess.run(['find', '/opt/env/modelseed_cplex', '-name', 'access.ilm'], capture_output=True, text=True)
print(result.stdout)

# Also check for any .ilm files
result = subprocess.run(['find', '/opt/env/modelseed_cplex', '-name', '*.ilm'], capture_output=True, text=True)
print(result.stdout)

In [ ]:
import subprocess

result = subprocess.run(['find', '/opt', '-name', 'access.ilm'], capture_output=True, text=True, timeout=120)
print(result.stdout)

# create models from ASVset genome objects

In [1]:
from load_genomes_to_modelseedpy import GenomeLoader
from cobra.io import write_sbml_model
# from glob import glob
from tqdm import tqdm
import os

loader = GenomeLoader()
# genome_ids = loader.list_available_genomes()#[:10]

def write_model(gID):
    model = loader.build_model(gID, printing=False)
    write_sbml_model(model, f'models/{gID}.xml')

# for genome_id in tqdm(genome_ids):
#     model_path = f'models/{genome_id}.xml'
#     if os.path.exists(model_path):  continue
#     try:
#         model = loader.build_model(genome_id, printing=False)
#         write_sbml_model(model, model_path)
#         # print(f"✓ {genome_id}") 
#     except Exception as e:
#         print(f"✗ {genome_id}: {e}")


# parallelize the effort
args = [gID for gID in loader.list_available_genomes() if not os.path.exists(f'models/{gID}.xml')]#[:2]
print(len(args), "will be processed")
parallelize = False
if parallelize:
    from multiprocess import Pool
    from os import cpu_count
    
    cpus = int(cpu_count()/8)
    print(f"{cpus} cores are being used.  The first argument is {args[0]}")
    pool = Pool(cpus)
    outputs = pool.map(write_model, args)
    
    print(f"missing iterativeIDs", missing_iterativeIDs)
    print(f"missing IDs", missing_IDs)
else:
    for arg in args:
        # print(arg)
        write_model(arg)

100%|██████████| 1698/1698 [1:21:00<00:00,  2.86s/it]

## Gapfill the models in minimal media

### ATP Correction

In [1]:
from cobra.io import read_sbml_model
from glob import glob

member_models = {}
num_models = 5
for model in glob('models/*.xml')[:num_models]:
    ID = model.split("/")[0].split(".")[0]
    member_models[ID] = read_sbml_model(model)

'' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070
Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

'' is not a valid SBML 'SId'.
'' is not a valid SBML 'SId'.
'' is not a valid SBML 'SId'.
'' is not a valid SBML 'SId'.

In [2]:
# from modelseedpy.core.msatpcorrection import load_default_medias
from modelseedpy.core.mstemplate import MSTemplateBuilder
from modelseedpy import MSATPCorrection
from json import load

with open('../ModelSEEDpy/modelseedpy/data/templates/template_core.json') as fh:
    template_core = MSTemplateBuilder.from_dict(load(fh)).build()
    
ATPcorrection_tests = {}
for ID, model in member_models.items():
    atp_correction = MSATPCorrection(model, #.util.model,
                                     template_core, #default_medias,
                                     compartment='c0', atp_hydrolysis_id='ATPM_c0',
                                     load_default_medias=True)

    print("correction done")
    media_eval = atp_correction.evaluate_growth_media()
    print("evaluation done")
    atp_correction.determine_growth_media()
    print("growth media done")
    atp_correction.apply_growth_media_gapfilling()
    print("applying growth media done")
    atp_correction.expand_model_to_genome_scale()
    print("expanding model done")
    ATPcorrection_tests[ID] = atp_correction.build_tests()

modelseedpy 0.3.3
Neither carbon consumption nor oxygen consumption are defined in
c0
correction done
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Ac.O2

No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Pyr.O2

No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Akg.O2

No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Dlac.O2

No gapfilling solution found before filtering for Ac activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Ac

No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Pyr

No gapfilling solution found before filtering for Succ activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Succ

No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Dlac

No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media mal-L

No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media For.NO3

No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Pyr.NO2

No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Pyr.NO

No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Ac.NO3

No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Pyr.DMSO

No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Pyr.SO4

No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media H2.CO2

No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media For.SO4.H2

No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media For.SO4

No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media H2.SO4

No gapfilling solution found before filtering for Light activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Light

No gapfilling solution found before filtering for Methane activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Methane

No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Methanol.H2

No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Removing ungapfillable media Dimethylamine.H2
Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705900266110>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

No gapfilling solution found for Etho.O2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05581_c0': '<', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn00935_c0': '<', 'rxn14422_c0': '>', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x70590191f460>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x70590191f640>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn09269_c0': '>', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908037d00>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908037880>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

No gapfilling solution found for For.O2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908037100>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

No gapfilling solution found for Etho activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn05581_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908036920>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908036770>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

No gapfilling solution found for Akg activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908036140>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

No gapfilling solution found for For activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for For.NO2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for For.NO activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for Pyr.NO3 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for Ac.NO2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for Ac.NO activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908034400>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908034190>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

No gapfilling solution found for Pyr.TMAO activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for Pyr.SO3 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for H2.Ac activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908004ee0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x705908005390>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

No gapfilling solution found for empty activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for ANME activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for Methanol activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for Methanamine.H2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

No gapfilling solution found for Trimethylamine.H2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

FileNotFoundError: [Errno 2] No such file or directory: 'datacache/solutions.json'

In [3]:
%run util.py
from json import load
from numpy import mean

# microbiome_path = "/Users/andrewfreiburger/Documents/Research/MicrobiomeNotebooks/digestor"
microbiome_path = "../MicrobiomeNotebooks"
metabolites = load(open(f"{microbiome_path}/digestor/metabolites.json", 'r'))
metaboliteIDs = list(metabolites.keys())

media_nar = 207617
metabolites = util.msrecon.get_media(f"{media_nar}/Wolfe").mediacompounds
auxo_media = util.msrecon.get_media(f"{media_nar}/AuxoMedia")
anaerobicPyruvate = util.msrecon.get_media(f"{media_nar}/PyruateMinimalAnaerobic")
# metabolites
metaboliteIDs = [cpd['id'] for cpd in metabolites] + ["cpd00011", "cpd11640", "cpd01024"]  # experimental media + CO2,H2,CH4

#TODO:  Why is growth only performed for the non-base media and uptake/excretion only performed for the base media?
uptake_phenoset = util.create_phenotypeset_from_compounds(
    metaboliteIDs, base_media=auxo_media, base_uptake=0, base_excretion=1000, global_atom_limits={}, type="uptake")
excretion_phenoset = util.create_phenotypeset_from_compounds(
    metaboliteIDs, base_media=auxo_media, base_uptake=0, base_excretion=1000, global_atom_limits={}, type="excretion")
agrowth_phenoset = util.create_phenotypeset_from_compounds(
    metaboliteIDs, base_media=anaerobicPyruvate, base_uptake=0, base_excretion=1000, global_atom_limits={}, type="agrowth")
# growth_phenoset = util.create_phenotypeset_from_compounds(
#     metabolites, base_media=gmm_base_media, base_uptake=0, base_excretion=1000, global_atom_limits={}, type="growth")
phenotypes = {"uptake": uptake_phenoset, "excretion": excretion_phenoset, "agrowth": agrowth_phenoset}

python version 3.10.19

['/home/afreiburger/repos/cobrakbase',
 '/home/afreiburger/repos/KBBaseModules',
 '/home/afreiburger/repos/chenry_utility_module/lib',
 '/home/afreiburger/repos/cb_annotation_ontology_api/lib',
 '/home/afreiburger/repos/KB-ModelSEEDReconstruction/lib',
 '/home/afreiburger/repos/MergeMetabolicAnnotations/lib',
 '/home/afreiburger/repos/codiffusion_bioreactor',
 '/home/afreiburger/.local/share/uv/python/cpython-3.10.19-linux-x86_64-gnu/lib/python310.zip',
 '/home/afreiburger/.local/share/uv/python/cpython-3.10.19-linux-x86_64-gnu/lib/python3.10',
 '/home/afreiburger/.local/share/uv/python/cpython-3.10.19-linux-x86_64-gnu/lib/python3.10/lib-dynload',
 '',
 '/home/afreiburger/repos/.venv2/lib/python3.10/site-packages',
 '/home/afreiburger/repos/.venv2/lib/python3.10/site-packages/cplex-22.1.1.0-py3.10.egg',
 '/home/afreiburger/repos/.venv2/lib/python3.10/site-packages/libsbml',
 '/home/afreiburger/repos']

KBBaseModules 0.0.1
cobrakbase 0.3.1
Output files printed to:/home/afreiburger/repos/codiffusion_bioreactor/Sludge/nboutput when using KBDevUtils.output_dir

In [ ]:
from modelseedpy.core.msmodel import get_reaction_constraints_from_direction
from cobra.io import write_sbml_model
from modelseedpy import MSBuilder
from modelseedpy import MSGapfill
from modelseedpy.core.mspredict import MSPredict

def _integrate_solution(template, model, gap_fill_solution):
    added_reactions = []
    for rxn_id, (lb, ub) in gap_fill_solution.items():
        template_reaction = template.reactions.get_by_id(rxn_id)
        model_reaction = template_reaction.to_reaction(model)
        model_reaction.lower_bound = lb
        model_reaction.upper_bound = ub
        _str = model_reaction.build_reaction_string(True)
        #print(f'{model.id} add {model_reaction.id}: {_str}')
        added_reactions.append(model_reaction)
    model.add_reactions(added_reactions)
    add_exchanges = MSBuilder.add_exchanges_to_model(model)

    return added_reactions, add_exchanges

with open('~/repos/ModelSEEDpy/modelseedpy/data/templates/template_gram_neg.json') as fh:
    template_gramneg = MSTemplateBuilder.from_dict(json.load(fh)).build()
    
for ID, model in member_models:
    predict = MSPredict()
    genome_klass = predict.predict(genome)
    
    gapfill = MSGapfill(model, default_gapfill_templates=[template_gramneg],
                        test_conditions=ATPcorrection_tests[ID],
                        default_target='bio1')

    for media in [auxo_media, anaerobicPyruvate]:
        gapfill_res = gapfill.run_gapfilling(auxo_media)
        gap_sol = {}
        for rxn_id, d in gapfill_res['new'].items():
            if rxn_id[:-1] in template_gramneg.reactions:
                gap_sol[rxn_id[:-1]] = get_reaction_constraints_from_direction(d)
        print(gap_sol)
        _integrate_solution(template_gramneg, model, gap_sol)

    write_sbml_model(model, f'models/{gID}.xml')

In [14]:
# Cell 1: Imports and setup                                                                                                                
                                                                                                                                         
import os, json                                                                                                                            
                                                                                                                                         
from glob import glob                                                                                                                      
from tqdm import tqdm                                                                                                                      
from collections import Counter                                                                                                            
from modelseedpy.core.msgenome import MSGenome, MSFeature                                                                                  
                                                                                                                                         
from modelseedpy.core.mspredict import MSPredict                                                                                           
                                                                                                                                         
from gapfill_models import (                                                                                                               
get_template_for_genome_class, create_auxo_media,                                                                                          
create_pyruvate_minimal_anaerobic, gapfill_model, list_models                                                                              
)                                                                                                                                          
                                                                                                                                         
                                                                                                                                         
models_dir = "models"                                                                                                                      
genome_objects_dir = "genome_objects"                                                                                                      
output_dir = "gapfilled_models2"                                                                                                           
                                                                                                                                         
# Initialize MSPredict classifier                                                                                                          
predictor = MSPredict()                                                                                                                    
def load_genome_from_genome_object(genome_id):                                                                                             
  """Load MSGenome with RAST annotations from genome_objects JSON."""                                                                    
  obj_path = os.path.join(genome_objects_dir, f"{genome_id}.json")                                                                       
  if not os.path.exists(obj_path):                                                                                                       
      return None                                                                                                                        
                                                                                                                                         
  genome = MSGenome()                                                                                                                    
  with open(obj_path) as f:                                                                                                              
      data = json.load(f)                                                                                                                
  genome.id = data.get('id', genome_id)                                                                                                  
  features = data.get('features', [])                                                                                                    
  for feat in features:                                                                                                                  
      if not isinstance(feat, dict):                                                                                                     
          continue                                                                                                                       
                                                                                                                                         
      # Check for CDS type and has functions or ontology_terms                                                                           
      if feat.get('type') == 'CDS':
          feat_id = feat.get('id', '')                                                                                                   
          ms_feat = MSFeature(feat_id, "")                                                                                               
          # Use ontology_terms if available, otherwise use functions                                                                     
          ontology = feat.get('ontology_terms', {})                                                                                      
          if 'RAST' in ontology and ontology['RAST']:                                                                                    
              for term in ontology['RAST']:                                                                                              
                  ms_feat.add_ontology_term('RAST', term)                                                                                
              genome.features.append(ms_feat)                                                                                            
          elif feat.get('functions'):                                                                                                    
              for func in feat['functions']:                                                                                             
                  ms_feat.add_ontology_term('RAST', func)                                                                                
              genome.features.append(ms_feat)                                                                                            
  return genome                                                                                                                          
                                                                                                                                         
# Get genome IDs from genome_objects directory                                                                                             
genome_ids = [os.path.splitext(os.path.basename(f))[0] for f in glob(f"{genome_objects_dir}/*.json")]                                      
genome_classifications = {}
print("classifying the genomes")                                                                                                           
for gid in tqdm(genome_ids):                                                                                                               
  genome = load_genome_from_genome_object(gid)                                                                                           
  if genome and len(genome.features) > 0:
      try:                                                                                                                               
          genome_classifications[gid] = predictor.predict(genome).value                                                                  
      except Exception as e:
          print(f"Could not classify {gid}: {e}")                                                                                        
                                                                                                                                         
json.dump(genome_classifications, open("member_classifications.json", 'w'), indent=3)                                                      
counts = Counter(list(genome_classifications.values())).most_common()                                                                      
print(f"Classified {len(genome_classifications)} genomes: {counts}")

/home/afreiburger/repos/.venv2/lib/python3.10/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator KNeighborsClassifier from version 1.2.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

classifying the genomes

100%|██████████| 1698/1698 [08:15<00:00,  3.43it/s]

Classified 1698 genomes: [('Gram Negative', 890), ('Gram Positive', 736), ('Archaea', 64), ('Cyano', 8)]

In [19]:
list(genome_classifications.items())[:2]

[('Angelakisella.1', 'Gram Positive'), ('midas_g_399.4', 'Gram Positive')]

In [22]:
# Build model -> genome mapping   
genome_classifications = json.load(open("member_classifications.json", 'r'))
# ASVgIDs = {json.load(open("model_inputs/ASV_genomeIDs.json", 'r'))

# iterativeIDs = json.load(open("model_inputs/iterativeIDs.json", 'r'))

print("ID mapping")
model_genome_mapping = {}                                                                                                                  
for model_path in tqdm(list_models(models_dir)):
    model_id = os.path.splitext(os.path.basename(model_path))[0]
    # print(model_path, model_id)
    if model_id in genome_classifications:                                                                                                 
        model_genome_mapping[model_id] = model_id
        # print("here")
    else:                                                                                                                                  
        base_id = '.'.join(model_id.split('.')[:2])                                                                                        
        if base_id in genome_classifications:                                                                                              
            model_genome_mapping[model_id] = base_id    
        # print("here2")
    # break
    
print(f"Mapped {len(model_genome_mapping)} models to genomes")

ID mapping

100%|██████████| 1698/1698 [00:00<00:00, 311859.18it/s]

Mapped 1698 models to genomes

In [ ]:
print("Gapfilling")                                                                                   
from cobra.io import read_sbml_model, write_sbml_model                                                                                     
from modelseedpy.core.msatpcorrection import MSATPCorrection                                                                               
from modelseedpy.core.mspredict import MSGenomeClass                                                                                       
                                                                                                                                         
media_list = [create_auxo_media(), create_pyruvate_minimal_anaerobic()]                                                                    
atp_correction_tests = {}                                                                                                                  
results = {}                                                                                                                               
                                                                                                                                         
# Map string values back to MSGenomeClass enum                                                                                             
genome_class_map = {                                                                                                                       
  "Gram Positive": MSGenomeClass.P,                                                                                                      
  "Gram Negative": MSGenomeClass.N,                                                                                                      
  "Cyano": MSGenomeClass.C,                                                                                                              
  "Archaea": MSGenomeClass.A,                                                                                                            
}                                                                                                                                          
                                                                                                                                         
def gapfilling(model_path):                                                                                                                
  model_id = os.path.splitext(os.path.basename(model_path))[0]                                                                           
  genome_id = model_genome_mapping.get(model_id)                                                                                         
  genome_class_str = genome_classifications.get(genome_id) if genome_id else None                                                        
                                                                                                                                         
  # Convert string to MSGenomeClass enum                                                                                                 
  genome_class = genome_class_map.get(genome_class_str) if genome_class_str else None                                                    
                                                                                                                                         
  # Get template using MSPredict classification                                                                                          
  core_template = None                                                                                                                   
  genome_template = None                                                                                                                 
  if genome_class:                                                                                                                       
      core_template, genome_template = predictor.auto_select_template(genome_class)                                                      
                                                                                                                                         
  output_path = gapfill_model(                                                                                                           
      model_path=model_path,                                                                                                             
      media_list=media_list,                                                                                                             
      output_dir=output_dir,                                                                                                             
      gapfilling_mode="Sequential",                                                                                                      
      atp_safe=True,                                                                                                                     
      genome_class=genome_class                                                                                                          
  )                                                                                                                                      
                                                                                                                                         
  result = None                                                                                                                          
  if output_path:                                                                                                                        
      # Load gapfilled model for ATP correction                                                                                          
      model = read_sbml_model(output_path)                                                                                               
                                                                                                                                         
      # ATP Correction                                                                                                                   
      if core_template:                                                                                                                  
          atp_correction = MSATPCorrection(                                                                                              
              model,                                                                                                                     
              core_template,  # Fixed: was core_tmpl                                                                                     
              compartment='c0',                                                                                                          
              atp_hydrolysis_id='ATPM_c0',                                                                                               
              load_default_medias=True                                                                                                   
          )                                                                                                                              
          atp_correction.evaluate_growth_media()                                                                                         
          atp_correction.determine_growth_media()                                                                                        
          atp_correction.apply_growth_media_gapfilling()                                                                                 
          atp_correction.expand_model_to_genome_scale()                                                                                  
          tests = atp_correction.build_tests()                                                                                           
                                                                                                                                         
          # Save corrected model                                                                                                         
          write_sbml_model(model, output_path)                                                                                           
          result = (model_id, output_path, tests)                                                                                        
      else:                                                                                                                              
          result = (model_id, output_path, None)                                                                                         
      print(f"Completed: {model_id}")                                                                                                    
  else:                                                                                                                                  
      result = (model_id, None, None)                                                                                                    
                                                                                                                                         
  return result                                                                                                                          
                                                                                                                                         
                                                                                                                                         
# parallelize the effort                                                                                                                   
args = list_models(models_dir)
print(len(args), "will be processed")
parallelize = True
if parallelize:
    from multiprocess import Pool
    from os import cpu_count
    
    cpus = min(len(args), int(cpu_count()/8))
    print(f"{cpus} cores are being used.  The first argument is {args[0]}")
    pool = Pool(cpus)
    outputs = pool.map(gapfilling, args)                                                                                                   
    pool.close()                                                                                                                           
    pool.join()                                                                                                                            
                                                                                                                                         
    # Collect results from parallel execution                                                                                              
    for model_id, output_path, tests in outputs:                                                                                           
      results[model_id] = output_path                                                                                                    
      if tests:                                                                                                                          
          atp_correction_tests[model_id] = tests                                                                                         
else:                                                                                                                                      
  for arg in args:                                                                                                                       
      model_id, output_path, tests = gapfilling(arg)  # Fixed: was create_comm                                                           
      results[model_id] = output_path                                                                                                    
      if tests:                                                                                                                          
          atp_correction_tests[model_id] = tests

                                                                                                                                         
print(f"Completed: {sum(1 for v in results.values() if v)}/{len(results)} successful")

Gapfilling
1698 will be processed
42 cores are being used.  The first argument is models/AAP99.1.xml

2026-01-13 19:31:51,403 - INFO - Loading model: Comamonadaceae.19
2026-01-13 19:31:51,404 - INFO - Loading model: Clostridia.7
2026-01-13 19:31:51,433 - INFO - Loading model: Desulfobacca.1
2026-01-13 19:31:51,434 - INFO - Loading model: Christensenellaceae_R-7_group.36
2026-01-13 19:31:51,434 - INFO - Loading model: DMER64.1
2026-01-13 19:31:51,435 - INFO - Loading model: Bacillus.2
2026-01-13 19:31:51,437 - INFO - Loading model: Clostridium_sensu_stricto_1.2
2026-01-13 19:31:51,437 - INFO - Loading model: AAP99.1
2026-01-13 19:31:51,437 - INFO - Loading model: Eoetvoesia.1
2026-01-13 19:31:51,443 - INFO - Loading model: Dehalobacter.1
2026-01-13 19:31:51,444 - INFO - Loading model: Christensenellaceae_R-7_group.57
2026-01-13 19:31:51,445 - INFO - Loading model: Erysipelothrix.8
2026-01-13 19:31:51,445 - INFO - Loading model: Desulfovibrio.3
2026-01-13 19:31:51,448 - INFO - Loading model: Ca_Alysiosphaera.2
2026-01-13 19:31:51,450 - INFO - Loading model: Ca_Competibacter.1
2026-01-13 19:31:51,454 - INFO - Loading model: Clostridium_sensu_stricto_13.3
2026-01-13 19:31:51,459 - INFO - Loading model: Christensenellaceae_R-7_group.11
2026-01-13 19:31:51,459 - INFO - Loading model: Colidextribacter.5
2026-01-13 19:31:51,441 - INFO - Loading model: EBM-39.5
2026-01-13 19:31:51,492 - INFO - Loading model: Comamonas.5
2026-01-13 19:31:51,517 - INFO - Loading model: Fastidiosipila.1
2026-01-13 19:31:51,521 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,522 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070
Set parameter TSPort to value 27070

2026-01-13 19:31:51,537 - INFO - Set parameter TSPort to value 27070
2026-01-13 19:31:51,538 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,539 - INFO - Set parameter TSPort to value 27070
2026-01-13 19:31:51,540 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,541 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,551 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,552 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,593 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,596 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,608 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,609 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,611 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,612 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,615 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,615 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,617 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,621 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,624 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,624 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,629 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070
Set parameter TSPort to value 27070

2026-01-13 19:31:51,630 - INFO - Set parameter TSPort to value 27070
2026-01-13 19:31:51,630 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
Set parameter TSPort to value 27070
Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,632 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,632 - INFO - Set parameter TSPort to value 27070
2026-01-13 19:31:51,632 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,634 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,634 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,636 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,637 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070
Set parameter TSPort to value 27070

2026-01-13 19:31:51,638 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,639 - INFO - Set parameter TSPort to value 27070
2026-01-13 19:31:51,639 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,641 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,641 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,640 - INFO - Loading model: Dethiobacter.9
2026-01-13 19:31:51,643 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,644 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,646 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,649 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,650 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,653 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,653 - INFO - Loading model: Acholeplasma.3
2026-01-13 19:31:51,654 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,659 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,660 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,661 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,661 - INFO - Loading model: Actinobacteria.1
2026-01-13 19:31:51,669 - INFO - Loading model: Brevundimonas.3
2026-01-13 19:31:51,671 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,673 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,674 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,677 - INFO - Loading model: Aquamicrobium.7
2026-01-13 19:31:51,678 - INFO - Loading model: Alphaproteobacteria.2

Set parameter TSPort to value 27070

2026-01-13 19:31:51,684 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,686 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,685 - INFO - Loading model: Ca_Phosphoribacter.1
2026-01-13 19:31:51,684 - INFO - Loading model: Aeromonas.1
2026-01-13 19:31:51,686 - INFO - Loading model: Bacilli.3
2026-01-13 19:31:51,695 - INFO - Loading model: Caldicoprobacteraceae.1
2026-01-13 19:31:51,696 - INFO - Loading model: Azoarcus.4
2026-01-13 19:31:51,697 - INFO - Loading model: Bauldia.2
2026-01-13 19:31:51,697 - INFO - Loading model: Alcaligenes.14
2026-01-13 19:31:51,699 - INFO - Loading model: Christensenellaceae_R-7_group.76
2026-01-13 19:31:51,699 - INFO - Loading model: Anaeromyxobacteraceae.2
2026-01-13 19:31:51,683 - INFO - Loading model: Devosia.9
2026-01-13 19:31:51,708 - INFO - Loading model: Blvii28_wastewater-sludge_group.3
2026-01-13 19:31:51,711 - INFO - Loading model: Anaerovorax.4
2026-01-13 19:31:51,713 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,728 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,730 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,729 - INFO - Loading model: Chelatococcus.1
2026-01-13 19:31:51,730 - INFO -   Loading template...
2026-01-13 19:31:51,755 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,761 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,773 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,775 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,777 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,779 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,778 - INFO -   Loading template...
2026-01-13 19:31:51,788 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,797 - INFO -   Loading template...
2026-01-13 19:31:51,803 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,805 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,816 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,821 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,831 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,832 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,832 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,837 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,838 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,841 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,842 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,847 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,849 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,853 - INFO - Loading model: Chryseobacterium.1
2026-01-13 19:31:51,855 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,857 - INFO - Set parameter TSPort to value 27070

Set parameter TSPort to value 27070
Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,859 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,859 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,861 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,870 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,872 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,895 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,908 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,910 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,912 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,922 - INFO -   Loading template...
2026-01-13 19:31:51,921 - INFO - Loading model: Aminivibrio.8
2026-01-13 19:31:51,923 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,925 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,926 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,926 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,934 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070
Set parameter TSPort to value 27070

2026-01-13 19:31:51,941 - INFO - Set parameter TSPort to value 27070
2026-01-13 19:31:51,942 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,943 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,944 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,944 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,948 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,950 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,958 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,960 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,960 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,961 - INFO -   Loading template...
2026-01-13 19:31:51,964 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:51,966 - INFO -   Loading template...
2026-01-13 19:31:51,972 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:51,976 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,978 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,979 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,981 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

Set parameter TSPort to value 27070

2026-01-13 19:31:51,987 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:51,989 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:51,995 - INFO -   Loading template...
2026-01-13 19:31:52,000 - INFO -   Loading template...
2026-01-13 19:31:52,002 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:52,017 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:52,019 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:52,030 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:52,031 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:52,032 - INFO -   Loading template...
2026-01-13 19:31:52,002 - INFO -   Loading template...
2026-01-13 19:31:52,037 - INFO -   Loading template...
2026-01-13 19:31:52,039 - INFO -   Loading template...
2026-01-13 19:31:52,033 - INFO -   Loading template...

Set parameter TSPort to value 27070

2026-01-13 19:31:52,047 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
Set parameter TSPort to value 27070

2026-01-13 19:31:52,050 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:52,050 - INFO - Set parameter TSPort to value 27070
2026-01-13 19:31:52,051 - INFO -   Loading template...

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:52,053 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:52,053 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:52,068 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:52,070 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:52,073 - ERROR - '' is not a valid SBML 'SId'.

Set parameter TSPort to value 27070

2026-01-13 19:31:52,088 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:52,089 - INFO -   Loading template...
2026-01-13 19:31:52,090 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:52,091 - INFO -   Loading template...
2026-01-13 19:31:52,154 - INFO -   Loading template...
2026-01-13 19:31:52,167 - INFO -   Loading template...
2026-01-13 19:31:52,173 - INFO -   Loading template...
2026-01-13 19:31:52,175 - INFO -   Loading template...
2026-01-13 19:31:52,180 - INFO -   Loading template...
2026-01-13 19:31:52,198 - INFO -   Loading template...
2026-01-13 19:31:52,280 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:31:52,286 - INFO -   Loading template...

Set parameter TSPort to value 27070

2026-01-13 19:31:52,296 - INFO - Set parameter TSPort to value 27070

Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

2026-01-13 19:31:52,298 - INFO - Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"
2026-01-13 19:31:52,349 - INFO -   Loading template...
2026-01-13 19:31:52,382 - INFO -   Loading template...
2026-01-13 19:31:52,387 - INFO -   Loading template...
2026-01-13 19:31:52,389 - INFO -   Loading template...
2026-01-13 19:31:52,407 - INFO -   Loading template...
2026-01-13 19:31:52,415 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,428 - INFO -   Loading template...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:52,450 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:52,477 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,480 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,489 - INFO -   Loading template...
2026-01-13 19:31:52,498 - INFO -   Loading template...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:52,509 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:52,514 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:52,529 - INFO -   Loading template...
2026-01-13 19:31:52,542 - INFO -   Loading template...
2026-01-13 19:31:52,553 - INFO -   Loading template...
2026-01-13 19:31:52,596 - INFO -   Loading template...
2026-01-13 19:31:52,605 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,614 - INFO -   Loading template...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:52,640 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:52,670 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,675 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,690 - INFO -   Loading template...
2026-01-13 19:31:52,701 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,702 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,721 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:52,732 - INFO -   Using template: GramNegative.modeltemplate

2026-01-13 19:31:52,734 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:52,740 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:52,768 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:52,793 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,804 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,824 - INFO -   Loading template...
2026-01-13 19:31:52,827 - INFO -   Loading template...
2026-01-13 19:31:52,837 - INFO -   Loading template...
2026-01-13 19:31:52,840 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,873 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:52,879 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:52,903 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:52,910 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,925 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:52,933 - INFO -   Loading template...
2026-01-13 19:31:52,934 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:52,965 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:52,976 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:53,003 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,007 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,026 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,038 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,038 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,059 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,073 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,074 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,094 - INFO -   Loading template...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,102 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,107 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:53,115 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,152 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,156 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,175 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,184 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:53,208 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,239 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,244 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,274 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,278 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,297 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,351 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,374 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,384 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,427 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,462 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,475 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,510 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,543 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,549 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,570 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:53,598 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:53,600 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,603 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,629 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,632 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,633 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,660 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,682 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,718 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,720 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,759 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,795 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,830 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,911 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:53,917 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,944 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:53,949 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:53,984 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 19:31:54,016 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:54,020 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:54,051 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:54,223 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:54,258 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 19:31:54,332 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:31:54,368 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:19,256 - INFO - Objective with gapfill database:137.21706849317312; min objective:0.01
2026-01-13 19:32:20,096 - INFO - Objective with gapfill database:137.21706849317223; min objective:0.01
2026-01-13 19:32:20,942 - INFO - Objective with gapfill database:137.2170684931731; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:21,879 - INFO - Objective with gapfill database:137.21706849317312; min objective:0.01
2026-01-13 19:32:22,020 - INFO - Objective with gapfill database:137.21706849317516; min objective:0.01
2026-01-13 19:32:22,553 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00054_e0': '<', 'EX_cpd00039_e0': '<', 'EX_cpd00215_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00218_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00035_e0': '<', 'EX_cpd00132_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00107_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00322_e0': '<', 'EX_cpd00156_e0': '<', 'EX_cpd10515_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn12666_c0': '>', 'rxn00530_c0': '>', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn00060_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn09427_c0': '>', 'rxn01997_c0': '>', 'rxn00171_c0': '>', 'rxn03918_c0': '>', 'rxn05243_c0': '>', 'rxn05335_c0': '<', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn01644_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn01505_c0': '>', 'rxn00849_c0': '<', 'rxn01629_c0': '<', 'rxn00777_c0': '<', 'rxn01740_c0': '<', 'rxn05573_c0': '>', 'rxn05244_c0': '>', 'rxn00503_c0': '<', 'rxn00790_c0': '<', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn01484_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05307_c0': '>', 'rxn00904_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn05496_c0': '>', 'rxn03537_c0': '>', 'rxn00173_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05508_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn00606_c0': '<', 'rxn09113_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn00069_c0': '>', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn02895_c0': '>', 'rxn03917_c0': '>', 'rxn00124_c0': '>', 'rxn00440_c0': '>', 'rxn03893_c0': '>', 'rxn00410_c0': '>', 'rxn01333_c0': '<', 'rxn03150_c0': '>', 'rxn01302_c0': '>', 'rxn02285_c0': '<', 'rxn02303_c0': '>', 'rxn03087_c0': '<', 'rxn00227_c0': '>', 'rxn05663_c0': '>', 'rxn03907_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn01361_c0': '>', 'rxn05618_c0': '>', 'rxn00461_c0': '>', 'rxn03136_c0': '>', 'rxn02937_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn02213_c0': '>', 'rxn05226_c0': '>', 'rxn00615_c0': '>', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn05154_c0': '>', 'rxn11702_c0': '>', 'rxn01332_c0': '>', 'rxn03084_c0': '>', 'rxn00558_c0': '>', 'rxn00346_c0': '>', 'rxn01790_c0': '<', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn06076_c0': '<', 'rxn05301_c0': '>', 'rxn01602_c0': '<', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn00520_c0': '<', 'rxn02373_c0': '<', 'rxn01466_c0': '>', 'rxn05310_c0': '>', 'rxn00605_c0': '<', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05669_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00929_c0': '<', 'rxn00138_c0': '>', 'rxn00347_c0': '<', 'rxn03031_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05177_c0': '>', 'rxn05306_c0': '>', 'rxn02929_c0': '<', 'rxn05305_c0': '<', 'rxn00686_c0': '<', 'rxn06075_c0': '<', 'rxn00117_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn09390_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:22,556 - INFO - integrating rxn: EX_cpd00054_e0
2026-01-13 19:32:22,558 - INFO - integrating rxn: EX_cpd00039_e0
2026-01-13 19:32:22,559 - INFO - integrating rxn: EX_cpd00215_e0
2026-01-13 19:32:22,561 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:22,562 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 19:32:22,563 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:22,564 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:22,566 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:22,567 - INFO - integrating rxn: EX_cpd00218_e0
2026-01-13 19:32:22,568 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:22,569 - INFO - integrating rxn: EX_cpd00035_e0
2026-01-13 19:32:22,571 - INFO - integrating rxn: EX_cpd00132_e0
2026-01-13 19:32:22,572 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:22,573 - INFO - integrating rxn: EX_cpd00084_e0
2026-01-13 19:32:22,574 - INFO - integrating rxn: EX_cpd00107_e0
2026-01-13 19:32:22,576 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:22,577 - INFO - integrating rxn: EX_cpd00161_e0
2026-01-13 19:32:22,578 - INFO - integrating rxn: EX_cpd00027_e0
2026-01-13 19:32:22,579 - INFO - integrating rxn: EX_cpd00060_e0
2026-01-13 19:32:22,580 - INFO - integrating rxn: EX_cpd00069_e0
2026-01-13 19:32:22,581 - INFO - integrating rxn: EX_cpd00322_e0
2026-01-13 19:32:22,582 - INFO - integrating rxn: EX_cpd00156_e0
2026-01-13 19:32:22,583 - INFO - integrating rxn: EX_cpd10515_e0
2026-01-13 19:32:22,584 - INFO - integrating rxn: EX_cpd00051_e0
2026-01-13 19:32:22,585 - INFO - integrating rxn: EX_cpd00066_e0
2026-01-13 19:32:22,586 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:32:22,588 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:22,589 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:22,591 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:32:22,592 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:22,593 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:22,595 - INFO - integrating rxn: rxn12666_c0
2026-01-13 19:32:22,596 - INFO - integrating rxn: rxn00530_c0
2026-01-13 19:32:22,597 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:32:22,598 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:22,600 - INFO - integrating rxn: rxn05300_c0
2026-01-13 19:32:22,601 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:22,602 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:22,604 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:22,605 - INFO - integrating rxn: rxn00060_c0
2026-01-13 19:32:22,607 - INFO - integrating rxn: rxn00100_c0
2026-01-13 19:32:22,608 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:22,609 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:22,611 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:22,612 - INFO - integrating rxn: rxn09427_c0
2026-01-13 19:32:22,613 - INFO - integrating rxn: rxn01997_c0
2026-01-13 19:32:22,615 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:32:22,616 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:22,617 - INFO - integrating rxn: rxn05243_c0
2026-01-13 19:32:22,619 - INFO - integrating rxn: rxn05335_c0
2026-01-13 19:32:22,620 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:22,621 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:22,623 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:22,624 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:22,625 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:22,626 - INFO - integrating rxn: rxn01644_c0
2026-01-13 19:32:22,628 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:22,629 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:22,630 - INFO - integrating rxn: rxn05219_c0
2026-01-13 19:32:22,631 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:22,633 - INFO - integrating rxn: rxn00029_c0
2026-01-13 19:32:22,634 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:22,635 - INFO - integrating rxn: rxn01675_c0
2026-01-13 19:32:22,637 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:22,638 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:22,639 - INFO - integrating rxn: rxn00849_c0
2026-01-13 19:32:22,640 - INFO - integrating rxn: rxn01629_c0
2026-01-13 19:32:22,641 - INFO - integrating rxn: rxn00777_c0
2026-01-13 19:32:22,642 - INFO - integrating rxn: rxn01740_c0
2026-01-13 19:32:22,644 - INFO - integrating rxn: rxn05573_c0
2026-01-13 19:32:22,645 - INFO - integrating rxn: rxn05244_c0
2026-01-13 19:32:22,646 - INFO - integrating rxn: rxn00503_c0
2026-01-13 19:32:22,647 - INFO - integrating rxn: rxn00790_c0
2026-01-13 19:32:22,648 - INFO - integrating rxn: rxn00237_c0
2026-01-13 19:32:22,650 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:22,651 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:22,652 - INFO - integrating rxn: rxn01484_c0
2026-01-13 19:32:22,653 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:22,655 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:22,656 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:22,657 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:22,658 - INFO - integrating rxn: rxn05307_c0
2026-01-13 19:32:22,659 - INFO - integrating rxn: rxn00904_c0
2026-01-13 19:32:22,661 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:22,662 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:22,663 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:22,665 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:22,666 - INFO - integrating rxn: rxn05496_c0
2026-01-13 19:32:22,667 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:22,668 - INFO - integrating rxn: rxn00173_c0
2026-01-13 19:32:22,669 - INFO - integrating rxn: rxn08528_c0
2026-01-13 19:32:22,671 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:22,672 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:22,673 - INFO - integrating rxn: rxn05508_c0
2026-01-13 19:32:22,674 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:22,676 - INFO - integrating rxn: rxn05237_c0
2026-01-13 19:32:22,677 - INFO - integrating rxn: rxn00606_c0
2026-01-13 19:32:22,678 - INFO - integrating rxn: rxn09113_c0
2026-01-13 19:32:22,680 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:22,681 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:22,682 - INFO - integrating rxn: rxn06023_c0
2026-01-13 19:32:22,683 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:22,684 - INFO - integrating rxn: rxn00970_c0
2026-01-13 19:32:22,686 - INFO - integrating rxn: rxn00069_c0
2026-01-13 19:32:22,687 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:22,688 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:22,689 - INFO - integrating rxn: rxn02895_c0
2026-01-13 19:32:22,691 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:22,692 - INFO - integrating rxn: rxn00124_c0
2026-01-13 19:32:22,693 - INFO - integrating rxn: rxn00440_c0
2026-01-13 19:32:22,694 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:22,696 - INFO - integrating rxn: rxn00410_c0
2026-01-13 19:32:22,697 - INFO - integrating rxn: rxn01333_c0
2026-01-13 19:32:22,698 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:22,699 - INFO - integrating rxn: rxn01302_c0
2026-01-13 19:32:22,701 - INFO - integrating rxn: rxn02285_c0
2026-01-13 19:32:22,702 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:22,704 - INFO - integrating rxn: rxn03087_c0
2026-01-13 19:32:22,705 - INFO - integrating rxn: rxn00227_c0
2026-01-13 19:32:22,706 - INFO - integrating rxn: rxn05663_c0
2026-01-13 19:32:22,707 - INFO - integrating rxn: rxn03907_c0
2026-01-13 19:32:22,708 - INFO - integrating rxn: rxn03538_c0
2026-01-13 19:32:22,710 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:22,711 - INFO - integrating rxn: rxn02304_c0
2026-01-13 19:32:22,712 - INFO - integrating rxn: rxn01361_c0
2026-01-13 19:32:22,713 - INFO - integrating rxn: rxn05618_c0
2026-01-13 19:32:22,715 - INFO - integrating rxn: rxn00461_c0
2026-01-13 19:32:22,716 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:22,717 - INFO - integrating rxn: rxn02937_c0
2026-01-13 19:32:22,718 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:22,719 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:22,721 - INFO - integrating rxn: rxn00533_c0
2026-01-13 19:32:22,722 - INFO - integrating rxn: rxn01512_c0
2026-01-13 19:32:22,723 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:22,725 - INFO - integrating rxn: rxn02213_c0
2026-01-13 19:32:22,726 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:32:22,727 - INFO - integrating rxn: rxn00615_c0
2026-01-13 19:32:22,728 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:22,729 - INFO - integrating rxn: rxn00704_c0
2026-01-13 19:32:22,731 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:32:22,732 - INFO - integrating rxn: rxn05154_c0
2026-01-13 19:32:22,734 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:22,735 - INFO - integrating rxn: rxn01332_c0
2026-01-13 19:32:22,736 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:22,737 - INFO - integrating rxn: rxn00558_c0
2026-01-13 19:32:22,739 - INFO - integrating rxn: rxn00346_c0
2026-01-13 19:32:22,740 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:22,741 - INFO - integrating rxn: rxn02897_c0
2026-01-13 19:32:22,742 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:22,744 - INFO - integrating rxn: rxn00134_c0
2026-01-13 19:32:22,745 - INFO - integrating rxn: rxn02003_c0
2026-01-13 19:32:22,746 - INFO - integrating rxn: rxn00130_c0
2026-01-13 19:32:22,747 - INFO - integrating rxn: rxn00912_c0
2026-01-13 19:32:22,748 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:22,750 - INFO - integrating rxn: rxn06076_c0
2026-01-13 19:32:22,751 - INFO - integrating rxn: rxn05301_c0
2026-01-13 19:32:22,751 - INFO - Objective with gapfill database:137.21706849317223; min objective:0.01
2026-01-13 19:32:22,752 - INFO - integrating rxn: rxn01602_c0
2026-01-13 19:32:22,753 - INFO - integrating rxn: rxn05223_c0
2026-01-13 19:32:22,755 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:22,756 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:22,757 - INFO - integrating rxn: rxn00520_c0
2026-01-13 19:32:22,759 - INFO - integrating rxn: rxn02373_c0
2026-01-13 19:32:22,760 - INFO - integrating rxn: rxn01466_c0
2026-01-13 19:32:22,761 - INFO - integrating rxn: rxn05310_c0
2026-01-13 19:32:22,762 - INFO - integrating rxn: rxn00605_c0
2026-01-13 19:32:22,763 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:22,764 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:22,766 - INFO - integrating rxn: rxn00409_c0
2026-01-13 19:32:22,767 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:22,768 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:22,769 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:22,770 - INFO - integrating rxn: rxn05669_c0
2026-01-13 19:32:22,772 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:22,773 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:22,774 - INFO - integrating rxn: rxn00929_c0
2026-01-13 19:32:22,775 - INFO - integrating rxn: rxn00138_c0
2026-01-13 19:32:22,776 - INFO - integrating rxn: rxn00347_c0
2026-01-13 19:32:22,778 - INFO - integrating rxn: rxn03031_c0
2026-01-13 19:32:22,779 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:22,780 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:22,781 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:22,782 - INFO - integrating rxn: rxn06591_c0
2026-01-13 19:32:22,783 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:22,785 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:22,786 - INFO - integrating rxn: rxn05177_c0
2026-01-13 19:32:22,787 - INFO - integrating rxn: rxn05306_c0
2026-01-13 19:32:22,788 - INFO - integrating rxn: rxn02929_c0
2026-01-13 19:32:22,790 - INFO - integrating rxn: rxn05305_c0
2026-01-13 19:32:22,791 - INFO - integrating rxn: rxn00686_c0
2026-01-13 19:32:22,792 - INFO - integrating rxn: rxn06075_c0
2026-01-13 19:32:22,793 - INFO - integrating rxn: rxn00117_c0
2026-01-13 19:32:22,794 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:22,796 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:22,797 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:22,798 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:22,800 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:22,801 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:22,802 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:22,804 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:32:22,805 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:22,806 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:22,807 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:22,809 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:22,810 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:22,811 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:32:22,812 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:32:22,814 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:22,815 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:22,816 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:22,817 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:32:22,818 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:22,820 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:22,821 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:22,823 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:32:22,824 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:22,825 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:22,826 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:22,828 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:22,829 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:22,830 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:22,831 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:22,833 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:32:22,834 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:22,835 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:22,836 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:22,838 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:22,839 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:22,840 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:22,841 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:32:22,842 - INFO - integrating rxn: rxn09390_c0

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00054_e0': '<', 'EX_cpd00039_e0': '<', 'EX_cpd00215_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00218_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00035_e0': '<', 'EX_cpd00132_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00107_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00322_e0': '<', 'EX_cpd00156_e0': '<', 'EX_cpd10515_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn12666_c0': '>', 'rxn00530_c0': '>', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn00060_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn09427_c0': '>', 'rxn01997_c0': '>', 'rxn00171_c0': '>', 'rxn03918_c0': '>', 'rxn05243_c0': '>', 'rxn05335_c0': '<', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn01644_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn01505_c0': '>', 'rxn00849_c0': '<', 'rxn01629_c0': '<', 'rxn00777_c0': '<', 'rxn01740_c0': '<', 'rxn05573_c0': '>', 'rxn05244_c0': '>', 'rxn00503_c0': '<', 'rxn00790_c0': '<', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn01484_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05307_c0': '>', 'rxn00904_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn05496_c0': '>', 'rxn03537_c0': '>', 'rxn00173_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05508_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn00606_c0': '<', 'rxn09113_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn00069_c0': '>', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn02895_c0': '>', 'rxn03917_c0': '>', 'rxn00124_c0': '>', 'rxn00440_c0': '>', 'rxn03893_c0': '>', 'rxn00410_c0': '>', 'rxn01333_c0': '<', 'rxn03150_c0': '>', 'rxn01302_c0': '>', 'rxn02285_c0': '<', 'rxn02303_c0': '>', 'rxn03087_c0': '<', 'rxn00227_c0': '>', 'rxn05663_c0': '>', 'rxn03907_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn01361_c0': '>', 'rxn05618_c0': '>', 'rxn00461_c0': '>', 'rxn03136_c0': '>', 'rxn02937_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn02213_c0': '>', 'rxn05226_c0': '>', 'rxn00615_c0': '>', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn05154_c0': '>', 'rxn11702_c0': '>', 'rxn01332_c0': '>', 'rxn03084_c0': '>', 'rxn00558_c0': '>', 'rxn00346_c0': '>', 'rxn01790_c0': '<', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn06076_c0': '<', 'rxn05301_c0': '>', 'rxn01602_c0': '<', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn00520_c0': '<', 'rxn02373_c0': '<', 'rxn01466_c0': '>', 'rxn05310_c0': '>', 'rxn00605_c0': '<', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05669_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00929_c0': '<', 'rxn00138_c0': '>', 'rxn00347_c0': '<', 'rxn03031_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05177_c0': '>', 'rxn05306_c0': '>', 'rxn02929_c0': '<', 'rxn05305_c0': '<', 'rxn00686_c0': '<', 'rxn06075_c0': '<', 'rxn00117_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn09390_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:23,199 - INFO - Cumulative: [['EX_cpd00039_e0', '<', 'new'], ['EX_cpd00215_e0', '<', 'new'], ['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00218_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00035_e0', '<', 'new'], ['EX_cpd00132_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00107_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00161_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00069_e0', '<', 'new'], ['EX_cpd00322_e0', '<', 'new'], ['EX_cpd00156_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['EX_cpd00066_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12666_c0', '>', 'new'], ['rxn00530_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn05300_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn09427_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn00171_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn05243_c0', '>', 'new'], ['rxn05335_c0', '<', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn01644_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00849_c0', '<', 'new'], ['rxn01629_c0', '<', 'new'], ['rxn01740_c0', '<', 'new'], ['rxn05573_c0', '>', 'new'], ['rxn05244_c0', '>', 'new'], ['rxn00790_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn01484_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn00904_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn05496_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05508_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn00606_c0', '<', 'new'], ['rxn09113_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00970_c0', '<', 'new'], ['rxn00069_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn02895_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00124_c0', '>', 'new'], ['rxn00440_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn00410_c0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01302_c0', '>', 'new'], ['rxn02285_c0', '<', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn00227_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn01361_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn00461_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02937_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn02213_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn05154_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn00558_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05301_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn00520_c0', '<', 'new'], ['rxn02373_c0', '<', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn05310_c0', '>', 'new'], ['rxn00605_c0', '<', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05669_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00929_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn00347_c0', '<', 'new'], ['rxn03031_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn06591_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05177_c0', '>', 'new'], ['rxn05306_c0', '>', 'new'], ['rxn02929_c0', '<', 'new'], ['rxn05305_c0', '<', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new']]
2026-01-13 19:32:23,200 - INFO -     Added 215 reactions
2026-01-13 19:32:23,201 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:23,407 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00034_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00051_e0': '<', 'rxn08709_c0': '>', 'rxn02000_c0': '>', 'rxn05457_c0': '<', 'rxn03086_c0': '<', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn04996_c0': '<', 'rxn03030_c0': '>', 'rxn02988_c0': '<', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn01739_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn03918_c0': '>', 'rxn08551_c0': '>', 'rxn08708_c0': '>', 'rxn05348_c0': '>', 'rxn00907_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn05345_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn05744_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn08688_c0': '>', 'rxn01505_c0': '>', 'rxn01256_c0': '>', 'rxn05327_c0': '<', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn00285_c0': '>', 'rxn14184_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn10954_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn05347_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn05342_c0': '<', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn02303_c0': '>', 'rxn05315_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn03136_c0': '>', 'rxn08088_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn09422_c0': '>', 'rxn00533_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00834_c0': '>', 'rxn00599_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn05117_c0': '>', 'rxn05355_c0': '<', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00347_c0': '<', 'rxn00467_c0': '<', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn00686_c0': '<', 'rxn06075_c0': '<', 'rxn00117_c0': '>', 'rxn05343_c0': '>', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn11285_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn47875_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08989_c0': '>', 'rxn14423_c0': '>', 'rxn10120_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:23,410 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:23,412 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 19:32:23,413 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:23,415 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:23,416 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:23,418 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:23,419 - INFO - integrating rxn: EX_cpd00034_e0
2026-01-13 19:32:23,421 - INFO - integrating rxn: EX_cpd00149_e0
2026-01-13 19:32:23,422 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:23,423 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:23,425 - INFO - integrating rxn: EX_cpd00051_e0
2026-01-13 19:32:23,426 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:23,428 - INFO - integrating rxn: rxn02000_c0
2026-01-13 19:32:23,429 - INFO - integrating rxn: rxn05457_c0
2026-01-13 19:32:23,431 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:32:23,433 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:23,434 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:32:23,436 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:23,437 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:23,439 - INFO - integrating rxn: rxn04996_c0
2026-01-13 19:32:23,440 - INFO - integrating rxn: rxn03030_c0
2026-01-13 19:32:23,442 - INFO - integrating rxn: rxn02988_c0
2026-01-13 19:32:23,443 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:23,444 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:32:23,446 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:23,447 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:23,449 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:23,450 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:23,452 - INFO - integrating rxn: rxn01739_c0
2026-01-13 19:32:23,453 - INFO - integrating rxn: rxn00060_c0
2026-01-13 19:32:23,455 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:23,456 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:23,458 - INFO - integrating rxn: rxn09202_c0
2026-01-13 19:32:23,459 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:23,461 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:23,462 - INFO - integrating rxn: rxn01997_c0
2026-01-13 19:32:23,464 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:23,465 - INFO - integrating rxn: rxn08551_c0
2026-01-13 19:32:23,467 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:23,469 - INFO - integrating rxn: rxn05348_c0
2026-01-13 19:32:23,470 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:23,471 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:23,473 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:23,474 - INFO - integrating rxn: rxn05345_c0
2026-01-13 19:32:23,475 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:23,477 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:23,478 - INFO - integrating rxn: rxn00029_c0
2026-01-13 19:32:23,480 - INFO - integrating rxn: rxn05744_c0
2026-01-13 19:32:23,482 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:23,483 - INFO - integrating rxn: rxn01675_c0
2026-01-13 19:32:23,485 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:23,486 - INFO - integrating rxn: rxn08688_c0
2026-01-13 19:32:23,487 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:23,488 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:32:23,490 - INFO - integrating rxn: rxn05327_c0
2026-01-13 19:32:23,490 - INFO - Objective with gapfill database:137.2170684931731; min objective:0.01
2026-01-13 19:32:23,491 - INFO - integrating rxn: rxn00237_c0
2026-01-13 19:32:23,493 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:23,494 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:23,496 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:32:23,497 - INFO - integrating rxn: rxn14184_c0
2026-01-13 19:32:23,499 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:23,500 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:23,502 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:23,503 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:23,504 - INFO - integrating rxn: rxn05303_c0
2026-01-13 19:32:23,506 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:23,507 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:32:23,509 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:23,511 - INFO - integrating rxn: rxn01972_c0
2026-01-13 19:32:23,512 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:23,513 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:23,515 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:23,516 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:23,517 - INFO - integrating rxn: rxn08528_c0
2026-01-13 19:32:23,519 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:23,520 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:23,522 - INFO - integrating rxn: rxn10954_c0
2026-01-13 19:32:23,523 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:23,524 - INFO - integrating rxn: rxn02402_c0
2026-01-13 19:32:23,525 - INFO - integrating rxn: rxn05347_c0
2026-01-13 19:32:23,527 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:23,528 - INFO - integrating rxn: rxn06023_c0
2026-01-13 19:32:23,529 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:23,531 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:23,532 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:23,534 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:23,535 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:23,536 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:23,537 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:23,539 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:23,540 - INFO - integrating rxn: rxn05342_c0
2026-01-13 19:32:23,541 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:23,543 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:23,544 - INFO - integrating rxn: rxn05029_c0
2026-01-13 19:32:23,546 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:23,547 - INFO - integrating rxn: rxn05315_c0
2026-01-13 19:32:23,549 - INFO - integrating rxn: rxn05663_c0
2026-01-13 19:32:23,550 - INFO - integrating rxn: rxn03538_c0
2026-01-13 19:32:23,551 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:23,553 - INFO - integrating rxn: rxn02304_c0
2026-01-13 19:32:23,554 - INFO - integrating rxn: rxn05618_c0
2026-01-13 19:32:23,556 - INFO - integrating rxn: rxn08241_c0
2026-01-13 19:32:23,557 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:23,558 - INFO - integrating rxn: rxn08088_c0
2026-01-13 19:32:23,560 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:23,561 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:23,563 - INFO - integrating rxn: rxn09422_c0
2026-01-13 19:32:23,564 - INFO - integrating rxn: rxn00533_c0
2026-01-13 19:32:23,565 - INFO - integrating rxn: rxn01512_c0
2026-01-13 19:32:23,567 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:23,568 - INFO - integrating rxn: rxn04113_c0
2026-01-13 19:32:23,570 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:23,571 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:23,572 - INFO - integrating rxn: rxn00704_c0
2026-01-13 19:32:23,574 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:32:23,575 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:23,577 - INFO - integrating rxn: rxn05117_c0
2026-01-13 19:32:23,578 - INFO - integrating rxn: rxn05355_c0
2026-01-13 19:32:23,580 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:23,582 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:23,583 - INFO - integrating rxn: rxn00346_c0
2026-01-13 19:32:23,584 - INFO - integrating rxn: rxn02897_c0
2026-01-13 19:32:23,586 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:23,587 - INFO - integrating rxn: rxn00134_c0
2026-01-13 19:32:23,588 - INFO - integrating rxn: rxn02003_c0
2026-01-13 19:32:23,590 - INFO - integrating rxn: rxn00130_c0
2026-01-13 19:32:23,591 - INFO - integrating rxn: rxn00912_c0
2026-01-13 19:32:23,593 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:23,594 - INFO - integrating rxn: rxn01602_c0
2026-01-13 19:32:23,596 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:23,597 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:23,599 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:23,600 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:23,601 - INFO - integrating rxn: rxn00409_c0
2026-01-13 19:32:23,603 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:23,604 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:23,606 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:23,607 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:23,608 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:23,609 - INFO - integrating rxn: rxn00347_c0
2026-01-13 19:32:23,611 - INFO - integrating rxn: rxn00467_c0
2026-01-13 19:32:23,612 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:23,614 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:23,615 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:23,616 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:23,618 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:23,619 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:23,620 - INFO - integrating rxn: rxn00686_c0
2026-01-13 19:32:23,622 - INFO - integrating rxn: rxn06075_c0

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00034_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00051_e0': '<', 'rxn08709_c0': '>', 'rxn02000_c0': '>', 'rxn05457_c0': '<', 'rxn03086_c0': '<', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn04996_c0': '<', 'rxn03030_c0': '>', 'rxn02988_c0': '<', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn01739_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn03918_c0': '>', 'rxn08551_c0': '>', 'rxn08708_c0': '>', 'rxn05348_c0': '>', 'rxn00907_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn05345_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn05744_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn08688_c0': '>', 'rxn01505_c0': '>', 'rxn01256_c0': '>', 'rxn05327_c0': '<', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn00285_c0': '>', 'rxn14184_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn10954_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn05347_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn05342_c0': '<', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn02303_c0': '>', 'rxn05315_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn03136_c0': '>', 'rxn08088_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn09422_c0': '>', 'rxn00533_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00834_c0': '>', 'rxn00599_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn05117_c0': '>', 'rxn05355_c0': '<', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00347_c0': '<', 'rxn00467_c0': '<', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn00686_c0': '<', 'rxn06075_c0': '<', 'rxn00117_c0': '>', 'rxn05343_c0': '>', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn11285_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn47875_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08989_c0': '>', 'rxn14423_c0': '>', 'rxn10120_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:24,002 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00034_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn05457_c0', '<', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn04996_c0', '<', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08551_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn05348_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn05345_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn05744_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08688_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn05327_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn00285_c0', '>', 'new'], ['rxn14184_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn05303_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn05347_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn05342_c0', '<', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn05315_c0', '<', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn09422_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn05355_c0', '<', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00347_c0', '<', 'new'], ['rxn00467_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn06075_c0', '<', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn05343_c0', '>', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn00154_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn47875_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10120_c0', '>', 'new']]
2026-01-13 19:32:24,003 - INFO -     Added 187 reactions
2026-01-13 19:32:24,004 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:24,110 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00205_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd10515_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn03408_c0': '>', 'rxn02000_c0': '>', 'rxn03086_c0': '<', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn02988_c0': '<', 'rxn01117_c0': '<', 'rxn00710_c0': '>', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn01974_c0': '>', 'rxn00762_c0': '>', 'rxn00060_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn01362_c0': '<', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn01465_c0': '<', 'rxn10204_c0': '>', 'rxn01637_c0': '<', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn00656_c0': '>', 'rxn01629_c0': '<', 'rxn00503_c0': '<', 'rxn00790_c0': '<', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn01300_c0': '>', 'rxn11676_c0': '>', 'rxn06848_c0': '<', 'rxn00527_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05119_c0': '>', 'rxn01917_c0': '>', 'rxn02011_c0': '>', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05237_c0': '>', 'rxn03147_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn02895_c0': '>', 'rxn00420_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn00283_c0': '>', 'rxn01018_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn01069_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn02285_c0': '<', 'rxn02303_c0': '>', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn01361_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn00260_c0': '<', 'rxn00461_c0': '>', 'rxn03136_c0': '>', 'rxn00502_c0': '<', 'rxn02937_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn00834_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn00693_c0': '<', 'rxn01101_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn01790_c0': '<', 'rxn00077_c0': '>', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00851_c0': '>', 'rxn00141_c0': '>', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn05596_c0': '<', 'rxn03904_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn10199_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03164_c0': '>', 'rxn00929_c0': '<', 'rxn03004_c0': '>', 'rxn00347_c0': '<', 'rxn02465_c0': '<', 'rxn03130_c0': '>', 'rxn00542_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05305_c0': '<', 'rxn02914_c0': '<', 'rxn00117_c0': '>', 'rxn02246_c0': '<', 'rxn00493_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn11285_c0': '>', 'rxn13339_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40040_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:24,113 - INFO - integrating rxn: EX_cpd00039_e0
2026-01-13 19:32:24,114 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:24,116 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 19:32:24,117 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:24,119 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:24,120 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:24,121 - INFO - integrating rxn: EX_cpd00205_e0
2026-01-13 19:32:24,122 - INFO - integrating rxn: EX_cpd00084_e0
2026-01-13 19:32:24,123 - INFO - integrating rxn: EX_cpd00149_e0
2026-01-13 19:32:24,125 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:24,126 - INFO - integrating rxn: EX_cpd00161_e0
2026-01-13 19:32:24,127 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:24,128 - INFO - integrating rxn: EX_cpd10515_e0
2026-01-13 19:32:24,129 - INFO - integrating rxn: EX_cpd00051_e0
2026-01-13 19:32:24,131 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:32:24,132 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:24,133 - INFO - integrating rxn: rxn03408_c0
2026-01-13 19:32:24,135 - INFO - integrating rxn: rxn02000_c0
2026-01-13 19:32:24,136 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:32:24,138 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:24,139 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:24,140 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:24,141 - INFO - integrating rxn: rxn03030_c0
2026-01-13 19:32:24,143 - INFO - integrating rxn: rxn02988_c0
2026-01-13 19:32:24,144 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:24,145 - INFO - integrating rxn: rxn00710_c0
2026-01-13 19:32:24,147 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:32:24,148 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:24,149 - INFO - integrating rxn: rxn05300_c0
2026-01-13 19:32:24,151 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:24,152 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:24,153 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:24,155 - INFO - integrating rxn: rxn01974_c0
2026-01-13 19:32:24,156 - INFO - integrating rxn: rxn00762_c0
2026-01-13 19:32:24,157 - INFO - integrating rxn: rxn00060_c0
2026-01-13 19:32:24,159 - INFO - integrating rxn: rxn00100_c0
2026-01-13 19:32:24,160 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:24,161 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:24,162 - INFO - integrating rxn: rxn09202_c0
2026-01-13 19:32:24,164 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:24,165 - INFO - integrating rxn: rxn01362_c0
2026-01-13 19:32:24,167 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:24,168 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:24,169 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:24,171 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:24,173 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:24,174 - INFO - integrating rxn: rxn01465_c0
2026-01-13 19:32:24,175 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:24,176 - INFO - integrating rxn: rxn01637_c0
2026-01-13 19:32:24,178 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:24,179 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:24,181 - INFO - integrating rxn: rxn00029_c0
2026-01-13 19:32:24,182 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:24,183 - INFO - integrating rxn: rxn01675_c0
2026-01-13 19:32:24,185 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:24,187 - INFO - integrating rxn: rxn00656_c0
2026-01-13 19:32:24,188 - INFO - integrating rxn: rxn01629_c0
2026-01-13 19:32:24,190 - INFO - integrating rxn: rxn00503_c0
2026-01-13 19:32:24,192 - INFO - integrating rxn: rxn00790_c0
2026-01-13 19:32:24,193 - INFO - integrating rxn: rxn00237_c0
2026-01-13 19:32:24,195 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:24,196 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:24,198 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:24,199 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:24,201 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:24,202 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:24,204 - INFO - integrating rxn: rxn05303_c0
2026-01-13 19:32:24,205 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:24,207 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:24,208 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:24,210 - INFO - integrating rxn: rxn01300_c0
2026-01-13 19:32:24,211 - INFO - integrating rxn: rxn11676_c0
2026-01-13 19:32:24,213 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:24,214 - INFO - integrating rxn: rxn00527_c0
2026-01-13 19:32:24,215 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:24,217 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:24,219 - INFO - integrating rxn: rxn05119_c0
2026-01-13 19:32:24,220 - INFO - integrating rxn: rxn01917_c0
2026-01-13 19:32:24,222 - INFO - integrating rxn: rxn02011_c0
2026-01-13 19:32:24,223 - INFO - integrating rxn: rxn08528_c0
2026-01-13 19:32:24,225 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:24,226 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:24,228 - INFO - integrating rxn: rxn05237_c0
2026-01-13 19:32:24,229 - INFO - integrating rxn: rxn03147_c0
2026-01-13 19:32:24,230 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:24,232 - INFO - integrating rxn: rxn02402_c0
2026-01-13 19:32:24,233 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:24,234 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:24,236 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:24,238 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:24,239 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:24,240 - INFO - integrating rxn: rxn02895_c0
2026-01-13 19:32:24,242 - INFO - integrating rxn: rxn00420_c0
2026-01-13 19:32:24,243 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:24,245 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:24,246 - INFO - integrating rxn: rxn00283_c0
2026-01-13 19:32:24,247 - INFO - integrating rxn: rxn01018_c0
2026-01-13 19:32:24,248 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:24,250 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:24,251 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:24,252 - INFO - integrating rxn: rxn01069_c0
2026-01-13 19:32:24,254 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:24,255 - INFO - integrating rxn: rxn05029_c0
2026-01-13 19:32:24,257 - INFO - integrating rxn: rxn02285_c0
2026-01-13 19:32:24,259 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:24,260 - INFO - integrating rxn: rxn05663_c0
2026-01-13 19:32:24,261 - INFO - integrating rxn: rxn03538_c0
2026-01-13 19:32:24,263 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:24,264 - INFO - integrating rxn: rxn02304_c0
2026-01-13 19:32:24,265 - INFO - integrating rxn: rxn01361_c0
2026-01-13 19:32:24,267 - INFO - integrating rxn: rxn05618_c0
2026-01-13 19:32:24,268 - INFO - integrating rxn: rxn08241_c0
2026-01-13 19:32:24,270 - INFO - integrating rxn: rxn00260_c0
2026-01-13 19:32:24,272 - INFO - integrating rxn: rxn00461_c0
2026-01-13 19:32:24,273 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:24,274 - INFO - integrating rxn: rxn00502_c0
2026-01-13 19:32:24,276 - INFO - integrating rxn: rxn02937_c0
2026-01-13 19:32:24,277 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:24,278 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:24,280 - INFO - integrating rxn: rxn01512_c0
2026-01-13 19:32:24,281 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:24,283 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:24,284 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:32:24,285 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:24,287 - INFO - integrating rxn: rxn00693_c0
2026-01-13 19:32:24,288 - INFO - integrating rxn: rxn01101_c0
2026-01-13 19:32:24,290 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:24,291 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:24,293 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:24,294 - INFO - integrating rxn: rxn00077_c0
2026-01-13 19:32:24,296 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:24,297 - INFO - integrating rxn: rxn02897_c0
2026-01-13 19:32:24,298 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:24,300 - INFO - integrating rxn: rxn00851_c0
2026-01-13 19:32:24,301 - INFO - integrating rxn: rxn00141_c0
2026-01-13 19:32:24,303 - INFO - integrating rxn: rxn02003_c0
2026-01-13 19:32:24,304 - INFO - integrating rxn: rxn00130_c0
2026-01-13 19:32:24,305 - INFO - integrating rxn: rxn00912_c0
2026-01-13 19:32:24,307 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:24,308 - INFO - integrating rxn: rxn05223_c0
2026-01-13 19:32:24,309 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:24,311 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:24,312 - INFO - integrating rxn: rxn05596_c0
2026-01-13 19:32:24,313 - INFO - integrating rxn: rxn03904_c0
2026-01-13 19:32:24,315 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:24,316 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:24,317 - INFO - integrating rxn: rxn10199_c0
2026-01-13 19:32:24,319 - INFO - integrating rxn: rxn00409_c0
2026-01-13 19:32:24,320 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:24,322 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:24,323 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:24,324 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:24,325 - INFO - integrating rxn: rxn02832_c0

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00205_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd10515_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn03408_c0': '>', 'rxn02000_c0': '>', 'rxn03086_c0': '<', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn02988_c0': '<', 'rxn01117_c0': '<', 'rxn00710_c0': '>', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn01974_c0': '>', 'rxn00762_c0': '>', 'rxn00060_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn01362_c0': '<', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn01465_c0': '<', 'rxn10204_c0': '>', 'rxn01637_c0': '<', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn00656_c0': '>', 'rxn01629_c0': '<', 'rxn00503_c0': '<', 'rxn00790_c0': '<', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn01300_c0': '>', 'rxn11676_c0': '>', 'rxn06848_c0': '<', 'rxn00527_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05119_c0': '>', 'rxn01917_c0': '>', 'rxn02011_c0': '>', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05237_c0': '>', 'rxn03147_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn02895_c0': '>', 'rxn00420_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn00283_c0': '>', 'rxn01018_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn01069_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn02285_c0': '<', 'rxn02303_c0': '>', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn01361_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn00260_c0': '<', 'rxn00461_c0': '>', 'rxn03136_c0': '>', 'rxn00502_c0': '<', 'rxn02937_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn00834_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn00693_c0': '<', 'rxn01101_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn01790_c0': '<', 'rxn00077_c0': '>', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00851_c0': '>', 'rxn00141_c0': '>', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn05596_c0': '<', 'rxn03904_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn10199_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03164_c0': '>', 'rxn00929_c0': '<', 'rxn03004_c0': '>', 'rxn00347_c0': '<', 'rxn02465_c0': '<', 'rxn03130_c0': '>', 'rxn00542_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05305_c0': '<', 'rxn02914_c0': '<', 'rxn00117_c0': '>', 'rxn02246_c0': '<', 'rxn00493_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn11285_c0': '>', 'rxn13339_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40040_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:24,821 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00205_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00161_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03408_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00710_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn05300_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01974_c0', '>', 'new'], ['rxn00762_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn01362_c0', '<', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn01465_c0', '<', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn01637_c0', '<', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn00656_c0', '>', 'new'], ['rxn01629_c0', '<', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn00790_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn05303_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn11676_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn00527_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn01917_c0', '>', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn03147_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn02895_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00283_c0', '>', 'new'], ['rxn01018_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01069_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn02285_c0', '<', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn01361_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn00260_c0', '<', 'new'], ['rxn00461_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00502_c0', '<', 'new'], ['rxn02937_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00693_c0', '<', 'new'], ['rxn01101_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn00077_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00851_c0', '>', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn05596_c0', '<', 'new'], ['rxn03904_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn10199_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03164_c0', '>', 'new'], ['rxn00929_c0', '<', 'new'], ['rxn03004_c0', '>', 'new'], ['rxn02465_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn00542_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn06591_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn02914_c0', '<', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn02246_c0', '<', 'new'], ['rxn00493_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:32:24,822 - INFO -     Added 202 reactions
2026-01-13 19:32:24,822 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:25,334 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00132_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00129_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'rxn08709_c0': '>', 'rxn00364_c0': '>', 'rxn03408_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01117_c0': '<', 'rxn00001_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn03181_c0': '>', 'rxn01048_c0': '<', 'rxn02331_c0': '<', 'rxn00796_c0': '<', 'rxn01930_c0': '>', 'rxn01729_c0': '>', 'rxn12512_c0': '>', 'rxn01739_c0': '>', 'rxn00762_c0': '<', 'rxn08583_c0': '>', 'rxn01355_c0': '>', 'rxn00383_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn02933_c0': '>', 'rxn02268_c0': '>', 'rxn00612_c0': '<', 'rxn01438_c0': '>', 'rxn08551_c0': '>', 'rxn08708_c0': '>', 'rxn11946_c0': '>', 'rxn00907_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn00747_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn11943_c0': '>', 'rxn02774_c0': '>', 'rxn04464_c0': '>', 'rxn01505_c0': '>', 'rxn05573_c0': '>', 'rxn03919_c0': '>', 'rxn10124_c0': '<', 'rxn09210_c0': '>', 'rxn01484_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn04704_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn08224_c0': '<', 'rxn00252_c0': '>', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn02011_c0': '>', 'rxn00173_c0': '<', 'rxn03916_c0': '>', 'rxn01669_c0': '<', 'rxn10954_c0': '>', 'rxn05508_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn01927_c0': '>', 'rxn00606_c0': '<', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn01730_c0': '>', 'rxn00069_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn00283_c0': '>', 'rxn03108_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn05342_c0': '<', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn01631_c0': '>', 'rxn01537_c0': '>', 'rxn02285_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02085_c0': '<', 'rxn02304_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn00461_c0': '>', 'rxn03136_c0': '>', 'rxn08088_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn01437_c0': '>', 'rxn00121_c0': '<', 'rxn05226_c0': '>', 'rxn00599_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn05154_c0': '>', 'rxn11702_c0': '>', 'rxn00320_c0': '>', 'rxn00693_c0': '<', 'rxn03439_c0': '>', 'rxn00558_c0': '>', 'rxn01790_c0': '<', 'rxn02056_c0': '<', 'rxn03075_c0': '>', 'rxn00134_c0': '>', 'rxn00851_c0': '>', 'rxn02003_c0': '<', 'rxn05301_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn00605_c0': '<', 'rxn02008_c0': '>', 'rxn03904_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn10199_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03901_c0': '>', 'rxn02832_c0': '<', 'rxn03164_c0': '>', 'rxn00347_c0': '<', 'rxn03130_c0': '>', 'rxn08231_c0': '<', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00478_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05306_c0': '>', 'rxn05638_c0': '>', 'rxn00686_c0': '<', 'rxn00293_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn17731_c0': '>', 'rxn42530_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn15166_c0': '>', 'rxn19346_c0': '>', 'rxn15091_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn14109_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn41988_c0': '>', 'rxn15776_c0': '>', 'rxn14050_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:25,338 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:25,340 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 19:32:25,342 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:25,343 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:25,345 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:25,346 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:25,347 - INFO - integrating rxn: EX_cpd00132_e0
2026-01-13 19:32:25,349 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:25,350 - INFO - integrating rxn: EX_cpd00129_e0
2026-01-13 19:32:25,351 - INFO - integrating rxn: EX_cpd00084_e0
2026-01-13 19:32:25,352 - INFO - integrating rxn: EX_cpd00149_e0
2026-01-13 19:32:25,353 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:25,355 - INFO - integrating rxn: EX_cpd00161_e0
2026-01-13 19:32:25,356 - INFO - integrating rxn: EX_cpd00027_e0
2026-01-13 19:32:25,357 - INFO - integrating rxn: EX_cpd00060_e0
2026-01-13 19:32:25,358 - INFO - integrating rxn: EX_cpd00069_e0
2026-01-13 19:32:25,359 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:25,360 - INFO - integrating rxn: EX_cpd00051_e0
2026-01-13 19:32:25,362 - INFO - integrating rxn: EX_cpd00066_e0
2026-01-13 19:32:25,363 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:25,364 - INFO - integrating rxn: rxn00364_c0
2026-01-13 19:32:25,366 - INFO - integrating rxn: rxn03408_c0
2026-01-13 19:32:25,367 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:32:25,368 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:25,370 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:25,371 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:32:25,372 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:25,373 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:25,375 - INFO - integrating rxn: rxn03030_c0
2026-01-13 19:32:25,376 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:25,377 - INFO - integrating rxn: rxn00001_c0
2026-01-13 19:32:25,379 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:25,380 - INFO - integrating rxn: rxn05300_c0
2026-01-13 19:32:25,381 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:25,383 - INFO - integrating rxn: rxn01048_c0
2026-01-13 19:32:25,384 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:25,386 - INFO - integrating rxn: rxn00796_c0
2026-01-13 19:32:25,387 - INFO - integrating rxn: rxn01930_c0
2026-01-13 19:32:25,389 - INFO - integrating rxn: rxn01729_c0
2026-01-13 19:32:25,391 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:25,392 - INFO - integrating rxn: rxn01739_c0
2026-01-13 19:32:25,393 - INFO - integrating rxn: rxn00762_c0
2026-01-13 19:32:25,395 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:25,396 - INFO - integrating rxn: rxn01355_c0
2026-01-13 19:32:25,397 - INFO - integrating rxn: rxn00383_c0
2026-01-13 19:32:25,399 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:25,400 - INFO - integrating rxn: rxn09202_c0
2026-01-13 19:32:25,401 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:25,403 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:25,404 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:25,405 - INFO - integrating rxn: rxn02933_c0
2026-01-13 19:32:25,407 - INFO - integrating rxn: rxn02268_c0
2026-01-13 19:32:25,408 - INFO - integrating rxn: rxn00612_c0
2026-01-13 19:32:25,409 - INFO - integrating rxn: rxn01438_c0
2026-01-13 19:32:25,411 - INFO - integrating rxn: rxn08551_c0
2026-01-13 19:32:25,412 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:25,413 - INFO - integrating rxn: rxn11946_c0
2026-01-13 19:32:25,415 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:25,416 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:25,417 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:25,418 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:25,419 - INFO - integrating rxn: rxn00747_c0
2026-01-13 19:32:25,421 - INFO - integrating rxn: rxn05219_c0
2026-01-13 19:32:25,422 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:25,424 - INFO - integrating rxn: rxn11943_c0
2026-01-13 19:32:25,425 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:25,426 - INFO - integrating rxn: rxn04464_c0
2026-01-13 19:32:25,428 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:25,429 - INFO - integrating rxn: rxn05573_c0
2026-01-13 19:32:25,430 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:25,431 - INFO - integrating rxn: rxn10124_c0
2026-01-13 19:32:25,433 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:25,434 - INFO - integrating rxn: rxn01484_c0
2026-01-13 19:32:25,435 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:25,436 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:25,438 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:25,439 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:25,440 - INFO - integrating rxn: rxn04704_c0
2026-01-13 19:32:25,442 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:25,443 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:25,444 - INFO - integrating rxn: rxn01972_c0
2026-01-13 19:32:25,446 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:25,447 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:25,448 - INFO - integrating rxn: rxn08224_c0
2026-01-13 19:32:25,449 - INFO - integrating rxn: rxn00252_c0
2026-01-13 19:32:25,451 - INFO - integrating rxn: rxn03537_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:25,452 - INFO - integrating rxn: rxn00966_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:25,454 - INFO - integrating rxn: rxn02011_c0
2026-01-13 19:32:25,456 - INFO - integrating rxn: rxn00173_c0
2026-01-13 19:32:25,458 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:25,459 - INFO - integrating rxn: rxn01669_c0
2026-01-13 19:32:25,460 - INFO - integrating rxn: rxn10954_c0
2026-01-13 19:32:25,461 - INFO - integrating rxn: rxn05508_c0
2026-01-13 19:32:25,463 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:25,464 - INFO - integrating rxn: rxn05237_c0
2026-01-13 19:32:25,465 - INFO - integrating rxn: rxn01927_c0
2026-01-13 19:32:25,467 - INFO - integrating rxn: rxn00606_c0
2026-01-13 19:32:25,468 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:25,469 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:32:25,470 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:25,472 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:25,473 - INFO - integrating rxn: rxn01730_c0
2026-01-13 19:32:25,475 - INFO - integrating rxn: rxn00069_c0
2026-01-13 19:32:25,476 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:25,477 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:25,479 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:25,480 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:25,481 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:25,482 - INFO - integrating rxn: rxn00283_c0
2026-01-13 19:32:25,484 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:32:25,485 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:25,486 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:25,487 - INFO - integrating rxn: rxn05342_c0
2026-01-13 19:32:25,489 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:25,490 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:25,491 - INFO - integrating rxn: rxn01631_c0
2026-01-13 19:32:25,493 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:32:25,494 - INFO - integrating rxn: rxn02285_c0
2026-01-13 19:32:25,495 - INFO - integrating rxn: rxn05663_c0
2026-01-13 19:32:25,496 - INFO - integrating rxn: rxn03538_c0
2026-01-13 19:32:25,498 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:25,499 - INFO - integrating rxn: rxn02085_c0
2026-01-13 19:32:25,500 - INFO - integrating rxn: rxn02304_c0
2026-01-13 19:32:25,501 - INFO - integrating rxn: rxn05618_c0
2026-01-13 19:32:25,503 - INFO - integrating rxn: rxn08241_c0
2026-01-13 19:32:25,504 - INFO - integrating rxn: rxn00461_c0
2026-01-13 19:32:25,505 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:25,506 - INFO - integrating rxn: rxn08088_c0
2026-01-13 19:32:25,507 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:25,508 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:25,510 - INFO - integrating rxn: rxn01437_c0
2026-01-13 19:32:25,511 - INFO - integrating rxn: rxn00121_c0
2026-01-13 19:32:25,512 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:32:25,514 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:25,515 - INFO - integrating rxn: rxn00704_c0
2026-01-13 19:32:25,516 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:32:25,517 - INFO - integrating rxn: rxn05154_c0
2026-01-13 19:32:25,519 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:25,520 - INFO - integrating rxn: rxn00320_c0
2026-01-13 19:32:25,521 - INFO - integrating rxn: rxn00693_c0
2026-01-13 19:32:25,524 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:25,525 - INFO - integrating rxn: rxn00558_c0
2026-01-13 19:32:25,526 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:25,527 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:25,528 - INFO - integrating rxn: rxn03075_c0
2026-01-13 19:32:25,530 - INFO - integrating rxn: rxn00134_c0
2026-01-13 19:32:25,531 - INFO - integrating rxn: rxn00851_c0
2026-01-13 19:32:25,532 - INFO - integrating rxn: rxn02003_c0
2026-01-13 19:32:25,533 - INFO - integrating rxn: rxn05301_c0
2026-01-13 19:32:25,535 - INFO - integrating rxn: rxn01602_c0
2026-01-13 19:32:25,536 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:25,537 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:25,539 - INFO - integrating rxn: rxn01466_c0
2026-01-13 19:32:25,540 - INFO - integrating rxn: rxn00605_c0
2026-01-13 19:32:25,541 - INFO - integrating rxn: rxn02008_c0
2026-01-13 19:32:25,543 - INFO - integrating rxn: rxn03904_c0
2026-01-13 19:32:25,544 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:25,545 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:25,547 - INFO - integrating rxn: rxn10199_c0
2026-01-13 19:32:25,548 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:25,549 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:25,551 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:25,552 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:25,553 - INFO - integrating rxn: rxn03901_c0
2026-01-13 19:32:25,554 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:25,556 - INFO - integrating rxn: rxn03164_c0
2026-01-13 19:32:25,557 - INFO - integrating rxn: rxn00347_c0
2026-01-13 19:32:25,558 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:25,559 - INFO - integrating rxn: rxn08231_c0
2026-01-13 19:32:25,560 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:25,561 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:25,563 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:25,564 - INFO - integrating rxn: rxn00478_c0
2026-01-13 19:32:25,565 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:25,566 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:25,567 - INFO - integrating rxn: rxn05306_c0
2026-01-13 19:32:25,569 - INFO - integrating rxn: rxn05638_c0
2026-01-13 19:32:25,570 - INFO - integrating rxn: rxn00686_c0
2026-01-13 19:32:25,571 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:25,572 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:25,574 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:25,575 - INFO - integrating rxn: rxn17731_c0
2026-01-13 19:32:25,576 - INFO - integrating rxn: rxn42530_c0
2026-01-13 19:32:25,578 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:25,579 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:25,581 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:25,582 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:32:25,584 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:25,585 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:25,586 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:25,588 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:25,589 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:25,590 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:32:25,591 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:32:25,593 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:25,594 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:32:25,595 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:32:25,596 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:25,598 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:25,599 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:25,600 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:32:25,602 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:32:25,603 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:32:25,604 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:25,605 - INFO - integrating rxn: rxn15091_c0
2026-01-13 19:32:25,607 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:32:25,608 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:32:25,610 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:32:25,611 - INFO - integrating rxn: rxn14109_c0
2026-01-13 19:32:25,612 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:32:25,613 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:32:25,615 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:25,616 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:25,617 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:25,619 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:32:25,620 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:25,622 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:25,623 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:25,625 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:25,626 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:25,627 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:25,629 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:32:25,630 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:25,631 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:25,632 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:25,633 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:32:25,635 - INFO - integrating rxn: rxn41988_c0
2026-01-13 19:32:25,636 - INFO - integrating rxn: rxn15776_c0
2026-01-13 19:32:25,638 - INFO - integrating rxn: rxn14050_c0
2026-01-13 19:32:25,639 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:25,640 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:25,641 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00132_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00129_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00161_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00069_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['EX_cpd00066_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00364_c0', '>', 'new'], ['rxn03408_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00001_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn05300_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn01048_c0', '<', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn00796_c0', '<', 'new'], ['rxn01930_c0', '>', 'new'], ['rxn01729_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn00762_c0', '<', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn01355_c0', '>', 'new'], ['rxn00383_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn02933_c0', '>', 'new'], ['rxn02268_c0', '>', 'new'], ['rxn00612_c0', '<', 'new'], ['rxn01438_c0', '>', 'new'], ['rxn08551_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn11946_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00747_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn11943_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn04464_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn05573_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn01484_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn08224_c0', '<', 'new'], ['rxn00252_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn00173_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn01669_c0', '<', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05508_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn01927_c0', '>', 'new'], ['rxn00606_c0', '<', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01730_c0', '>', 'new'], ['rxn00069_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00283_c0', '>', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn05342_c0', '<', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01631_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02285_c0', '<', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02085_c0', '<', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn00461_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01437_c0', '>', 'new'], ['rxn00121_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn05154_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00320_c0', '>', 'new'], ['rxn00693_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00558_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00851_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn05301_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn00605_c0', '<', 'new'], ['rxn02008_c0', '>', 'new'], ['rxn03904_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn10199_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03901_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03164_c0', '>', 'new'], ['rxn00347_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn08231_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00478_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05306_c0', '>', 'new'], ['rxn05638_c0', '>', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn17731_c0', '>', 'new'], ['rxn42530_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn15091_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn14109_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn41988_c0', '>', 'new'], ['rxn15776_c0', '>', 'new'], ['rxn14050_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:25,652 - INFO - cpd00263 not found in model!
2026-01-13 19:32:25,652 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:25,653 - INFO - cpd00215 not found in model!
2026-01-13 19:32:25,654 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:25,670 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,672 - INFO - AuxoMedia/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,673 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:25,676 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,678 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,680 - INFO - EX_cpd00065_e0< not needed:1.8014265849902131
2026-01-13 19:32:25,682 - INFO - AuxoMedia/bio1:EX_cpd00132_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,684 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,685 - INFO - EX_cpd00129_e0< not needed:1.7883789198355904
2026-01-13 19:32:25,687 - INFO - EX_cpd00084_e0< not needed:1.7866081192943066
2026-01-13 19:32:25,690 - INFO - AuxoMedia/bio1:EX_cpd00149_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,691 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,693 - INFO - AuxoMedia/bio1:EX_cpd00161_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,695 - INFO - AuxoMedia/bio1:EX_cpd00027_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,697 - INFO - AuxoMedia/bio1:EX_cpd00060_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,700 - INFO - EX_cpd00069_e0< not needed:1.7675413385533858
2026-01-13 19:32:25,703 - INFO - AuxoMedia/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,705 - INFO - EX_cpd00051_e0< not needed:1.7425252682941543
2026-01-13 19:32:25,707 - INFO - EX_cpd00066_e0< not needed:1.719013093984337
2026-01-13 19:32:25,709 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,711 - INFO - AuxoMedia/bio1:rxn00364_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,712 - INFO - AuxoMedia/bio1:rxn03408_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,714 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,715 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,716 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,718 - INFO - AuxoMedia/bio1:rxn00179_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,719 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,720 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,723 - INFO - AuxoMedia/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,724 - INFO - AuxoMedia/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,726 - INFO - rxn00001_c0> not needed:1.7190130939843418
2026-01-13 19:32:25,729 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,730 - INFO - Objective with gapfill database:137.21706849317334; min objective:0.01
2026-01-13 19:32:25,731 - INFO - AuxoMedia/bio1:rxn05300_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,733 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,734 - INFO - AuxoMedia/bio1:rxn01048_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,736 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,737 - INFO - AuxoMedia/bio1:rxn00796_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,739 - INFO - rxn01930_c0> not needed:1.719013093984337
2026-01-13 19:32:25,742 - INFO - AuxoMedia/bio1:rxn01729_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,743 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,745 - INFO - AuxoMedia/bio1:rxn01739_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,746 - INFO - AuxoMedia/bio1:rxn00762_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,748 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,749 - INFO - rxn01355_c0> not needed:1.7163486393515124
2026-01-13 19:32:25,752 - INFO - AuxoMedia/bio1:rxn00383_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,754 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,755 - INFO - AuxoMedia/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,756 - INFO - AuxoMedia/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,757 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,759 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,760 - INFO - rxn02933_c0> not needed:1.7163486393515104
2026-01-13 19:32:25,762 - INFO - rxn02268_c0> not needed:1.7163486393515064
2026-01-13 19:32:25,764 - INFO - AuxoMedia/bio1:rxn00612_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,767 - INFO - rxn01438_c0> not needed:1.7163486393515102
2026-01-13 19:32:25,770 - INFO - AuxoMedia/bio1:rxn08551_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,771 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,773 - INFO - AuxoMedia/bio1:rxn11946_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,775 - INFO - rxn00907_c0> not needed:1.702992021201243
2026-01-13 19:32:25,778 - INFO - AuxoMedia/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,780 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,781 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,783 - INFO - AuxoMedia/bio1:rxn00747_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,784 - INFO - AuxoMedia/bio1:rxn05219_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,786 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,787 - INFO - AuxoMedia/bio1:rxn11943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,789 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,790 - INFO - AuxoMedia/bio1:rxn04464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,791 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,793 - INFO - AuxoMedia/bio1:rxn05573_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,794 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,795 - INFO - AuxoMedia/bio1:rxn10124_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,797 - INFO - AuxoMedia/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,798 - INFO - AuxoMedia/bio1:rxn01484_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,799 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,800 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,802 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,803 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,804 - INFO - AuxoMedia/bio1:rxn04704_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,805 - INFO - AuxoMedia/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,807 - INFO - AuxoMedia/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,808 - INFO - AuxoMedia/bio1:rxn01972_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,809 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,811 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,812 - INFO - AuxoMedia/bio1:rxn08224_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,813 - INFO - AuxoMedia/bio1:rxn00252_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,815 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,816 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,817 - INFO - AuxoMedia/bio1:rxn02011_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,819 - INFO - AuxoMedia/bio1:rxn00173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,821 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,822 - INFO - AuxoMedia/bio1:rxn01669_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,824 - INFO - AuxoMedia/bio1:rxn10954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,825 - INFO - AuxoMedia/bio1:rxn05508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,826 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,828 - INFO - rxn05237_c0> not needed:1.7029920212012415
2026-01-13 19:32:25,829 - INFO - rxn01927_c0> not needed:1.702992021201241
2026-01-13 19:32:25,832 - INFO - AuxoMedia/bio1:rxn00606_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,833 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,835 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,836 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,837 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,839 - INFO - AuxoMedia/bio1:rxn01730_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,840 - INFO - AuxoMedia/bio1:rxn00069_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,841 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,843 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,844 - INFO - AuxoMedia/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,845 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,847 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,848 - INFO - AuxoMedia/bio1:rxn00283_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,849 - INFO - AuxoMedia/bio1:rxn03108_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,851 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,852 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,853 - INFO - AuxoMedia/bio1:rxn05342_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,854 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,856 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,857 - INFO - AuxoMedia/bio1:rxn01631_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,858 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,860 - INFO - AuxoMedia/bio1:rxn02285_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,861 - INFO - rxn05663_c0> not needed:1.7029920212012464
2026-01-13 19:32:25,864 - INFO - AuxoMedia/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,866 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,867 - INFO - AuxoMedia/bio1:rxn02085_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,869 - INFO - AuxoMedia/bio1:rxn02304_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,870 - INFO - AuxoMedia/bio1:rxn05618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,871 - INFO - AuxoMedia/bio1:rxn08241_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,872 - INFO - AuxoMedia/bio1:rxn00461_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,873 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,875 - INFO - AuxoMedia/bio1:rxn08088_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,876 - INFO - AuxoMedia/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,877 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,879 - INFO - rxn01437_c0> not needed:1.7029920212012473
2026-01-13 19:32:25,882 - INFO - AuxoMedia/bio1:rxn00121_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,884 - INFO - AuxoMedia/bio1:rxn05226_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,885 - INFO - AuxoMedia/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,887 - INFO - AuxoMedia/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,888 - INFO - AuxoMedia/bio1:rxn08130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,889 - INFO - rxn05154_c0> not needed:1.7029920212012495
2026-01-13 19:32:25,893 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,894 - INFO - AuxoMedia/bio1:rxn00320_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,895 - INFO - AuxoMedia/bio1:rxn00693_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,897 - INFO - AuxoMedia/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,898 - INFO - AuxoMedia/bio1:rxn00558_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,900 - INFO - AuxoMedia/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,901 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,903 - INFO - AuxoMedia/bio1:rxn03075_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,904 - INFO - AuxoMedia/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,905 - INFO - AuxoMedia/bio1:rxn00851_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,906 - INFO - AuxoMedia/bio1:rxn02003_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,908 - INFO - rxn05301_c0> not needed:1.7029920212012468
2026-01-13 19:32:25,911 - INFO - AuxoMedia/bio1:rxn01602_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,912 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,913 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,915 - INFO - AuxoMedia/bio1:rxn01466_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,916 - INFO - AuxoMedia/bio1:rxn00605_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,917 - INFO - AuxoMedia/bio1:rxn02008_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,918 - INFO - AuxoMedia/bio1:rxn03904_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,920 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,921 - INFO - AuxoMedia/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,922 - INFO - AuxoMedia/bio1:rxn10199_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,923 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,925 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,926 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,927 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,928 - INFO - AuxoMedia/bio1:rxn03901_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,930 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,931 - INFO - AuxoMedia/bio1:rxn03164_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,932 - INFO - AuxoMedia/bio1:rxn00347_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,934 - INFO - AuxoMedia/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,935 - INFO - AuxoMedia/bio1:rxn08231_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,936 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,938 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,939 - INFO - AuxoMedia/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,940 - INFO - rxn00478_c0> not needed:1.7029920212012417
2026-01-13 19:32:25,943 - INFO - AuxoMedia/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,945 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,946 - INFO - rxn05306_c0> not needed:1.702992021201249
2026-01-13 19:32:25,947 - INFO - rxn05638_c0> not needed:1.7029920212012437
2026-01-13 19:32:25,950 - INFO - AuxoMedia/bio1:rxn00686_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:25,951 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,953 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,955 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,956 - INFO - AuxoMedia/bio1:rxn17731_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,957 - INFO - rxn42530_c0> not needed:1.7029920212012457
2026-01-13 19:32:25,960 - INFO - AuxoMedia/bio1:rxn14424_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,962 - INFO - rxn11274_c0> not needed:1.7029920212012426
2026-01-13 19:32:25,964 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,966 - INFO - AuxoMedia/bio1:rxn12932_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,967 - INFO - AuxoMedia/bio1:rxn12940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,968 - INFO - AuxoMedia/bio1:rxn12939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,970 - INFO - AuxoMedia/bio1:rxn12929_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,971 - INFO - AuxoMedia/bio1:rxn25637_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,973 - INFO - AuxoMedia/bio1:rxn18935_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,974 - INFO - AuxoMedia/bio1:rxn25743_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,975 - INFO - AuxoMedia/bio1:rxn12928_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,977 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,978 - INFO - AuxoMedia/bio1:rxn12942_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,979 - INFO - AuxoMedia/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,980 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,982 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,983 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,984 - INFO - AuxoMedia/bio1:rxn11251_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,986 - INFO - AuxoMedia/bio1:rxn15167_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,987 - INFO - rxn15166_c0> not needed:1.7029920212012395

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:25,989 - INFO - AuxoMedia/bio1:rxn19346_c0> needed:0.0 with min obj:0.01

2026-01-13 19:32:25,991 - INFO - AuxoMedia/bio1:rxn15091_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,993 - INFO - AuxoMedia/bio1:rxn25042_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,994 - INFO - AuxoMedia/bio1:rxn19766_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,996 - INFO - AuxoMedia/bio1:rxn19764_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:25,997 - INFO - rxn14109_c0> not needed:1.7029920212012477
2026-01-13 19:32:25,999 - INFO - AuxoMedia/bio1:rxn19728_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,000 - INFO - AuxoMedia/bio1:rxn20235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,003 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,004 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,005 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,007 - INFO - AuxoMedia/bio1:rxn16114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,008 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,009 - INFO - AuxoMedia/bio1:rxn15060_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,011 - INFO - AuxoMedia/bio1:rxn29919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,012 - INFO - rxn10095_c0> not needed:1.7029920212012426
2026-01-13 19:32:26,015 - INFO - AuxoMedia/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,016 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,018 - INFO - AuxoMedia/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,020 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,022 - INFO - rxn08921_c0> not needed:1.7029106871794528
2026-01-13 19:32:26,023 - INFO - rxn29260_c0> not needed:1.702829360926246
2026-01-13 19:32:26,024 - INFO - rxn08473_c0> not needed:1.702829360926245
2026-01-13 19:32:26,025 - INFO - rxn41988_c0> not needed:1.702829360926245
2026-01-13 19:32:26,028 - INFO - AuxoMedia/bio1:rxn15776_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,029 - INFO - AuxoMedia/bio1:rxn14050_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,030 - INFO - AuxoMedia/bio1:rxn14423_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,032 - INFO - AuxoMedia/bio1:rxn10042_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:26,035 - INFO - Unneeded: [['EX_cpd00065_e0', '<', 'new', -10, None], ['EX_cpd00129_e0', '<', 'new', -10, None], ['EX_cpd00084_e0', '<', 'new', -10, None], ['EX_cpd00069_e0', '<', 'new', -10, None], ['EX_cpd00051_e0', '<', 'new', -10, None], ['EX_cpd00066_e0', '<', 'new', -10, None], ['rxn00001_c0', '>', 'new', 100, None], ['rxn01930_c0', '>', 'new', 100, None], ['rxn01355_c0', '>', 'new', 100, None], ['rxn02933_c0', '>', 'new', 100, None], ['rxn02268_c0', '>', 'new', 100, None], ['rxn01438_c0', '>', 'new', 100, None], ['rxn00907_c0', '>', 'new', 100, None], ['rxn05237_c0', '>', 'new', 100, None], ['rxn01927_c0', '>', 'new', 100, None], ['rxn05663_c0', '>', 'new', 100, None], ['rxn01437_c0', '>', 'new', 100, None], ['rxn05154_c0', '>', 'new', 100, None], ['rxn05301_c0', '>', 'new', 100, None], ['rxn00478_c0', '>', 'new', 100, None], ['rxn05306_c0', '>', 'new', 100, None], ['rxn05638_c0', '>', 'new', 100, None], ['rxn42530_c0', '>', 'new', 100, None], ['rxn11274_c0', '>', 'new', 100, None], ['rxn15166_c0', '>', 'new', 100, None], ['rxn14109_c0', '>', 'new', 100, None], ['rxn10095_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn08473_c0', '>', 'new', 100, None], ['rxn41988_c0', '>', 'new', 100, None]]
2026-01-13 19:32:26,040 - INFO - cpd00263 not found in model!
2026-01-13 19:32:26,041 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:26,042 - INFO - cpd00215 not found in model!
2026-01-13 19:32:26,043 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:26,048 - INFO - Growth: 1.8104007774933666 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00132_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00129_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'rxn08709_c0': '>', 'rxn00364_c0': '>', 'rxn03408_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01117_c0': '<', 'rxn00001_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn03181_c0': '>', 'rxn01048_c0': '<', 'rxn02331_c0': '<', 'rxn00796_c0': '<', 'rxn01930_c0': '>', 'rxn01729_c0': '>', 'rxn12512_c0': '>', 'rxn01739_c0': '>', 'rxn00762_c0': '<', 'rxn08583_c0': '>', 'rxn01355_c0': '>', 'rxn00383_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn02933_c0': '>', 'rxn02268_c0': '>', 'rxn00612_c0': '<', 'rxn01438_c0': '>', 'rxn08551_c0': '>', 'rxn08708_c0': '>', 'rxn11946_c0': '>', 'rxn00907_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn00747_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn11943_c0': '>', 'rxn02774_c0': '>', 'rxn04464_c0': '>', 'rxn01505_c0': '>', 'rxn05573_c0': '>', 'rxn03919_c0': '>', 'rxn10124_c0': '<', 'rxn09210_c0': '>', 'rxn01484_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn04704_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn08224_c0': '<', 'rxn00252_c0': '>', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn02011_c0': '>', 'rxn00173_c0': '<', 'rxn03916_c0': '>', 'rxn01669_c0': '<', 'rxn10954_c0': '>', 'rxn05508_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn01927_c0': '>', 'rxn00606_c0': '<', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn01730_c0': '>', 'rxn00069_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn00283_c0': '>', 'rxn03108_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn05342_c0': '<', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn01631_c0': '>', 'rxn01537_c0': '>', 'rxn02285_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02085_c0': '<', 'rxn02304_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn00461_c0': '>', 'rxn03136_c0': '>', 'rxn08088_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn01437_c0': '>', 'rxn00121_c0': '<', 'rxn05226_c0': '>', 'rxn00599_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn05154_c0': '>', 'rxn11702_c0': '>', 'rxn00320_c0': '>', 'rxn00693_c0': '<', 'rxn03439_c0': '>', 'rxn00558_c0': '>', 'rxn01790_c0': '<', 'rxn02056_c0': '<', 'rxn03075_c0': '>', 'rxn00134_c0': '>', 'rxn00851_c0': '>', 'rxn02003_c0': '<', 'rxn05301_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn00605_c0': '<', 'rxn02008_c0': '>', 'rxn03904_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn10199_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03901_c0': '>', 'rxn02832_c0': '<', 'rxn03164_c0': '>', 'rxn00347_c0': '<', 'rxn03130_c0': '>', 'rxn08231_c0': '<', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00478_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05306_c0': '>', 'rxn05638_c0': '>', 'rxn00686_c0': '<', 'rxn00293_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn17731_c0': '>', 'rxn42530_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn15166_c0': '>', 'rxn19346_c0': '>', 'rxn15091_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn14109_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn41988_c0': '>', 'rxn15776_c0': '>', 'rxn14050_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:26,052 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00132_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00161_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00364_c0', '>', 'new'], ['rxn03408_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn05300_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn01048_c0', '<', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn00796_c0', '<', 'new'], ['rxn01729_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn00762_c0', '<', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn00383_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00612_c0', '<', 'new'], ['rxn08551_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn11946_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00747_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn11943_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn04464_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn05573_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn01484_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn08224_c0', '<', 'new'], ['rxn00252_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn00173_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn01669_c0', '<', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05508_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn00606_c0', '<', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01730_c0', '>', 'new'], ['rxn00069_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00283_c0', '>', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn05342_c0', '<', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01631_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02285_c0', '<', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02085_c0', '<', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn00461_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00121_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00320_c0', '>', 'new'], ['rxn00693_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00558_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00851_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn00605_c0', '<', 'new'], ['rxn02008_c0', '>', 'new'], ['rxn03904_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn10199_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03901_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03164_c0', '>', 'new'], ['rxn00347_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn08231_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn17731_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn15091_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn15776_c0', '>', 'new'], ['rxn14050_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:26,053 - INFO -     Added 200 reactions
2026-01-13 19:32:26,054 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:26,289 - INFO - Objective with gapfill database:137.21706849317317; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:26,642 - INFO - Objective with gapfill database:137.21706849317295; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:28,286 - INFO - Objective with gapfill database:137.21706849317337; min objective:0.01
2026-01-13 19:32:28,871 - INFO - Objective with gapfill database:137.21706849317317; min objective:0.01
2026-01-13 19:32:28,972 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00054_e0': '<', 'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00033_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00205_e0': '<', 'EX_cpd00132_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00034_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd10515_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'rxn08709_c0': '>', 'rxn00935_c0': '>', 'rxn02000_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn05582_c0': '>', 'rxn01117_c0': '<', 'rxn00530_c0': '>', 'rxn00710_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn00337_c0': '>', 'rxn12512_c0': '>', 'rxn10484_c0': '>', 'rxn01739_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn02212_c0': '>', 'rxn10481_c0': '>', 'rxn00692_c0': '<', 'rxn01997_c0': '>', 'rxn01362_c0': '<', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00471_c0': '>', 'rxn02404_c0': '>', 'rxn09180_c0': '<', 'rxn10204_c0': '>', 'rxn01301_c0': '>', 'rxn01643_c0': '<', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn04464_c0': '>', 'rxn03536_c0': '>', 'rxn05150_c0': '>', 'rxn01505_c0': '>', 'rxn01629_c0': '<', 'rxn01740_c0': '<', 'rxn03919_c0': '>', 'rxn10124_c0': '<', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn05307_c0': '>', 'rxn00904_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn00786_c0': '>', 'rxn01255_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn08352_c0': '>', 'rxn09106_c0': '>', 'rxn05508_c0': '>', 'rxn05463_c0': '>', 'rxn05237_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00394_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn02895_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn00799_c0': '<', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn08854_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn05663_c0': '>', 'rxn03907_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02085_c0': '<', 'rxn00175_c0': '>', 'rxn01361_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn02476_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn02213_c0': '>', 'rxn00615_c0': '>', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn01332_c0': '>', 'rxn00693_c0': '<', 'rxn03439_c0': '>', 'rxn00558_c0': '>', 'rxn01790_c0': '<', 'rxn05651_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00141_c0': '>', 'rxn02003_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn05301_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn05596_c0': '<', 'rxn01466_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05306_c0': '>', 'rxn02929_c0': '<', 'rxn00686_c0': '<', 'rxn00560_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:28,976 - INFO - integrating rxn: EX_cpd00054_e0
2026-01-13 19:32:28,977 - INFO - integrating rxn: EX_cpd00039_e0
2026-01-13 19:32:28,979 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:28,980 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 19:32:28,982 - INFO - integrating rxn: EX_cpd00033_e0
2026-01-13 19:32:28,983 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:28,984 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:28,986 - INFO - integrating rxn: EX_cpd00048_e0
2026-01-13 19:32:28,987 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:28,988 - INFO - integrating rxn: EX_cpd00205_e0
2026-01-13 19:32:28,989 - INFO - integrating rxn: EX_cpd00132_e0
2026-01-13 19:32:28,990 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:28,991 - INFO - integrating rxn: EX_cpd00084_e0
2026-01-13 19:32:28,993 - INFO - integrating rxn: EX_cpd00034_e0
2026-01-13 19:32:28,994 - INFO - integrating rxn: EX_cpd00149_e0
2026-01-13 19:32:28,995 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:28,996 - INFO - integrating rxn: EX_cpd00161_e0
2026-01-13 19:32:28,997 - INFO - integrating rxn: EX_cpd00060_e0
2026-01-13 19:32:28,998 - INFO - integrating rxn: EX_cpd00069_e0
2026-01-13 19:32:28,999 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:29,001 - INFO - integrating rxn: EX_cpd10515_e0
2026-01-13 19:32:29,002 - INFO - integrating rxn: EX_cpd00051_e0
2026-01-13 19:32:29,003 - INFO - integrating rxn: EX_cpd00066_e0
2026-01-13 19:32:29,004 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:29,006 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:32:29,007 - INFO - integrating rxn: rxn02000_c0
2026-01-13 19:32:29,008 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:29,010 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:29,011 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:29,012 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:29,013 - INFO - integrating rxn: rxn05582_c0
2026-01-13 19:32:29,015 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:29,016 - INFO - integrating rxn: rxn00530_c0
2026-01-13 19:32:29,017 - INFO - integrating rxn: rxn00710_c0
2026-01-13 19:32:29,019 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:29,020 - INFO - integrating rxn: rxn05300_c0
2026-01-13 19:32:29,021 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:29,023 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:29,024 - INFO - integrating rxn: rxn00337_c0
2026-01-13 19:32:29,025 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:29,027 - INFO - integrating rxn: rxn10484_c0
2026-01-13 19:32:29,029 - INFO - integrating rxn: rxn01739_c0
2026-01-13 19:32:29,030 - INFO - integrating rxn: rxn00060_c0
2026-01-13 19:32:29,031 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:29,033 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:29,034 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:29,035 - INFO - integrating rxn: rxn02212_c0
2026-01-13 19:32:29,036 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:29,038 - INFO - integrating rxn: rxn00692_c0
2026-01-13 19:32:29,040 - INFO - integrating rxn: rxn01997_c0
2026-01-13 19:32:29,041 - INFO - integrating rxn: rxn01362_c0
2026-01-13 19:32:29,043 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:29,044 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:29,045 - INFO - integrating rxn: rxn00471_c0
2026-01-13 19:32:29,047 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:29,048 - INFO - integrating rxn: rxn09180_c0
2026-01-13 19:32:29,049 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:29,050 - INFO - integrating rxn: rxn01301_c0
2026-01-13 19:32:29,052 - INFO - integrating rxn: rxn01643_c0
2026-01-13 19:32:29,053 - INFO - integrating rxn: rxn06937_c0
2026-01-13 19:32:29,055 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:29,056 - INFO - integrating rxn: rxn05219_c0
2026-01-13 19:32:29,057 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:29,059 - INFO - integrating rxn: rxn00029_c0
2026-01-13 19:32:29,060 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:29,061 - INFO - integrating rxn: rxn01675_c0
2026-01-13 19:32:29,063 - INFO - integrating rxn: rxn04464_c0
2026-01-13 19:32:29,064 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:29,065 - INFO - integrating rxn: rxn05150_c0
2026-01-13 19:32:29,067 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:29,068 - INFO - integrating rxn: rxn01629_c0
2026-01-13 19:32:29,069 - INFO - integrating rxn: rxn01740_c0
2026-01-13 19:32:29,071 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:29,072 - INFO - integrating rxn: rxn10124_c0
2026-01-13 19:32:29,073 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:29,074 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:29,076 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:29,077 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:29,078 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:29,079 - INFO - integrating rxn: rxn05303_c0
2026-01-13 19:32:29,081 - INFO - integrating rxn: rxn05307_c0
2026-01-13 19:32:29,082 - INFO - integrating rxn: rxn00904_c0
2026-01-13 19:32:29,083 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:29,085 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:29,086 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:29,087 - INFO - integrating rxn: rxn00786_c0
2026-01-13 19:32:29,089 - INFO - integrating rxn: rxn01255_c0
2026-01-13 19:32:29,090 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:29,091 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:29,093 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:29,094 - INFO - integrating rxn: rxn08352_c0
2026-01-13 19:32:29,096 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:29,097 - INFO - integrating rxn: rxn05508_c0
2026-01-13 19:32:29,098 - INFO - integrating rxn: rxn05463_c0
2026-01-13 19:32:29,099 - INFO - integrating rxn: rxn05237_c0
2026-01-13 19:32:29,101 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:29,102 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:29,103 - INFO - integrating rxn: rxn00394_c0
2026-01-13 19:32:29,104 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:29,106 - INFO - integrating rxn: rxn00970_c0
2026-01-13 19:32:29,107 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:29,109 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:29,110 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:29,111 - INFO - integrating rxn: rxn02895_c0
2026-01-13 19:32:29,113 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:29,114 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:29,115 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:29,117 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:29,118 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:32:29,119 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:29,121 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:29,122 - INFO - integrating rxn: rxn08854_c0
2026-01-13 19:32:29,123 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:32:29,125 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:29,126 - INFO - integrating rxn: rxn05663_c0
2026-01-13 19:32:29,127 - INFO - integrating rxn: rxn03907_c0
2026-01-13 19:32:29,129 - INFO - integrating rxn: rxn03538_c0
2026-01-13 19:32:29,130 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:29,131 - INFO - integrating rxn: rxn02085_c0
2026-01-13 19:32:29,133 - INFO - integrating rxn: rxn00175_c0
2026-01-13 19:32:29,134 - INFO - integrating rxn: rxn01361_c0
2026-01-13 19:32:29,135 - INFO - integrating rxn: rxn05618_c0
2026-01-13 19:32:29,136 - INFO - integrating rxn: rxn08241_c0
2026-01-13 19:32:29,137 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:29,139 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:29,140 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:29,141 - INFO - integrating rxn: rxn00533_c0
2026-01-13 19:32:29,143 - INFO - integrating rxn: rxn02476_c0
2026-01-13 19:32:29,144 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:29,146 - INFO - integrating rxn: rxn04113_c0
2026-01-13 19:32:29,147 - INFO - integrating rxn: rxn02213_c0
2026-01-13 19:32:29,148 - INFO - integrating rxn: rxn00615_c0
2026-01-13 19:32:29,149 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:29,151 - INFO - integrating rxn: rxn00704_c0
2026-01-13 19:32:29,153 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:32:29,154 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:29,155 - INFO - integrating rxn: rxn01332_c0
2026-01-13 19:32:29,157 - INFO - integrating rxn: rxn00693_c0
2026-01-13 19:32:29,158 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:29,159 - INFO - integrating rxn: rxn00558_c0
2026-01-13 19:32:29,161 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:29,162 - INFO - integrating rxn: rxn05651_c0
2026-01-13 19:32:29,163 - INFO - integrating rxn: rxn02897_c0
2026-01-13 19:32:29,164 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:29,166 - INFO - integrating rxn: rxn00141_c0
2026-01-13 19:32:29,167 - INFO - integrating rxn: rxn02003_c0
2026-01-13 19:32:29,168 - INFO - integrating rxn: rxn00912_c0
2026-01-13 19:32:29,169 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:29,171 - INFO - integrating rxn: rxn05301_c0
2026-01-13 19:32:29,172 - INFO - integrating rxn: rxn01602_c0
2026-01-13 19:32:29,173 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:29,175 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:29,176 - INFO - integrating rxn: rxn05596_c0
2026-01-13 19:32:29,178 - INFO - integrating rxn: rxn01466_c0
2026-01-13 19:32:29,179 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:29,181 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:29,182 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:29,184 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:29,185 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:29,186 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:29,187 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:29,188 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:29,190 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:29,191 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:29,192 - INFO - integrating rxn: rxn06591_c0
2026-01-13 19:32:29,194 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:29,195 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:29,196 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:29,197 - INFO - integrating rxn: rxn05306_c0
2026-01-13 19:32:29,199 - INFO - integrating rxn: rxn02929_c0
2026-01-13 19:32:29,200 - INFO - integrating rxn: rxn00686_c0
2026-01-13 19:32:29,202 - INFO - integrating rxn: rxn00560_c0
2026-01-13 19:32:29,203 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:29,205 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:29,206 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:29,207 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:29,209 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:29,210 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:29,212 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:29,213 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:29,214 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:29,216 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:29,217 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:29,219 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:29,220 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:29,221 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:32:29,222 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:32:29,224 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:29,225 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:29,226 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:29,226 - INFO - Objective with gapfill database:137.21706849317295; min objective:0.01
2026-01-13 19:32:29,227 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:32:29,229 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:29,230 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:29,232 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:29,233 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:32:29,234 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:32:29,236 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:29,237 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:32:29,238 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:32:29,240 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:29,241 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:29,242 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:29,243 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:32:29,245 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:29,246 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:29,247 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:29,248 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:29,250 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:29,251 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:29,252 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:29,254 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:29,255 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:32:29,256 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:29,257 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:29,259 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:29,260 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:29,261 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:32:29,262 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:29,264 - INFO - integrating rxn: rxn10042_c0

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00054_e0': '<', 'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00033_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00205_e0': '<', 'EX_cpd00132_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00034_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd10515_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'rxn08709_c0': '>', 'rxn00935_c0': '>', 'rxn02000_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn05582_c0': '>', 'rxn01117_c0': '<', 'rxn00530_c0': '>', 'rxn00710_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn00337_c0': '>', 'rxn12512_c0': '>', 'rxn10484_c0': '>', 'rxn01739_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn02212_c0': '>', 'rxn10481_c0': '>', 'rxn00692_c0': '<', 'rxn01997_c0': '>', 'rxn01362_c0': '<', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00471_c0': '>', 'rxn02404_c0': '>', 'rxn09180_c0': '<', 'rxn10204_c0': '>', 'rxn01301_c0': '>', 'rxn01643_c0': '<', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn04464_c0': '>', 'rxn03536_c0': '>', 'rxn05150_c0': '>', 'rxn01505_c0': '>', 'rxn01629_c0': '<', 'rxn01740_c0': '<', 'rxn03919_c0': '>', 'rxn10124_c0': '<', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn05307_c0': '>', 'rxn00904_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn00786_c0': '>', 'rxn01255_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn08352_c0': '>', 'rxn09106_c0': '>', 'rxn05508_c0': '>', 'rxn05463_c0': '>', 'rxn05237_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00394_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn02895_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn00799_c0': '<', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn08854_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn05663_c0': '>', 'rxn03907_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02085_c0': '<', 'rxn00175_c0': '>', 'rxn01361_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn02476_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn02213_c0': '>', 'rxn00615_c0': '>', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn01332_c0': '>', 'rxn00693_c0': '<', 'rxn03439_c0': '>', 'rxn00558_c0': '>', 'rxn01790_c0': '<', 'rxn05651_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00141_c0': '>', 'rxn02003_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn05301_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn05596_c0': '<', 'rxn01466_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05306_c0': '>', 'rxn02929_c0': '<', 'rxn00686_c0': '<', 'rxn00560_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:29,644 - INFO - Cumulative: [['EX_cpd00054_e0', '<', 'new'], ['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00033_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00205_e0', '<', 'new'], ['EX_cpd00132_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00034_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00069_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['EX_cpd00066_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00935_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn05582_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00530_c0', '>', 'new'], ['rxn00710_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn00337_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn10484_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn02212_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn01362_c0', '<', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00471_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn09180_c0', '<', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn01301_c0', '>', 'new'], ['rxn01643_c0', '<', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn04464_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn05150_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01629_c0', '<', 'new'], ['rxn01740_c0', '<', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn05303_c0', '>', 'new'], ['rxn05307_c0', '>', 'new'], ['rxn00904_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01255_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn08352_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05508_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00394_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00970_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn02895_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02085_c0', '<', 'new'], ['rxn01361_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn02476_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn02213_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn00693_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00558_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05301_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn05596_c0', '<', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn06591_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05306_c0', '>', 'new'], ['rxn02929_c0', '<', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00560_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:29,645 - INFO -     Added 195 reactions
2026-01-13 19:32:29,645 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:29,821 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00033_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00107_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00322_e0': '<', 'EX_cpd00156_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn00530_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn12512_c0': '>', 'rxn00060_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn09427_c0': '>', 'rxn03918_c0': '>', 'rxn05243_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn04464_c0': '<', 'rxn01505_c0': '>', 'rxn00213_c0': '>', 'rxn01629_c0': '<', 'rxn01740_c0': '<', 'rxn05244_c0': '>', 'rxn03919_c0': '>', 'rxn01484_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn09113_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn08661_c0': '>', 'rxn00420_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn05231_c0': '>', 'rxn00283_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn03150_c0': '>', 'rxn08854_c0': '>', 'rxn00101_c0': '>', 'rxn02303_c0': '>', 'rxn03087_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn02213_c0': '>', 'rxn05226_c0': '>', 'rxn00615_c0': '>', 'rxn00834_c0': '>', 'rxn11702_c0': '>', 'rxn01332_c0': '>', 'rxn01790_c0': '<', 'rxn05651_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn06076_c0': '<', 'rxn05301_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn01304_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05669_c0': '>', 'rxn05255_c0': '>', 'rxn00778_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05306_c0': '>', 'rxn06075_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn15395_c0': '>', 'rxn14178_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn15270_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:29,825 - INFO - integrating rxn: EX_cpd00039_e0
2026-01-13 19:32:29,826 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:29,828 - INFO - integrating rxn: EX_cpd00033_e0
2026-01-13 19:32:29,829 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:29,830 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:29,831 - INFO - integrating rxn: EX_cpd00048_e0
2026-01-13 19:32:29,833 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:29,834 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:29,835 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:29,836 - INFO - integrating rxn: EX_cpd00084_e0
2026-01-13 19:32:29,837 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00205_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00129_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00107_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00322_e0': '<', 'EX_cpd00156_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00364_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn05161_c0': '>', 'rxn08708_c0': '>', 'rxn00272_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01454_c0': '<', 'rxn01501_c0': '<', 'rxn05244_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn02229_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn05299_c0': '>', 'rxn09657_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn03087_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn05165_c0': '>', 'rxn05618_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn06865_c0': '<', 'rxn05226_c0': '>', 'rxn00615_c0': '>', 'rxn01265_c0': '<', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn00122_c0': '>', 'rxn05301_c0': '>', 'rxn01602_c0': '<', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn05596_c0': '<', 'rxn00338_c0': '>', 'rxn02287_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn01538_c0': '>', 'rxn05669_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn05306_c0': '>', 'rxn05305_c0': '<', 'rxn00686_c0': '<', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn08233_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn46249_c0': '>', 'rxn40040_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn09390_c0': '>', 'rxn10120_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:29,838 - INFO - integrating rxn: EX_cpd00107_e0
2026-01-13 19:32:29,839 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:29,840 - INFO - integrating rxn: EX_cpd00161_e0
2026-01-13 19:32:29,840 - INFO - integrating rxn: EX_cpd00039_e0
2026-01-13 19:32:29,842 - INFO - integrating rxn: EX_cpd00027_e0
2026-01-13 19:32:29,842 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:29,843 - INFO - integrating rxn: EX_cpd00069_e0
2026-01-13 19:32:29,844 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 19:32:29,844 - INFO - integrating rxn: EX_cpd00322_e0
2026-01-13 19:32:29,845 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:29,846 - INFO - integrating rxn: EX_cpd00156_e0
2026-01-13 19:32:29,847 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:29,847 - INFO - integrating rxn: EX_cpd00051_e0
2026-01-13 19:32:29,848 - INFO - integrating rxn: EX_cpd00066_e0
2026-01-13 19:32:29,849 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:29,850 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:32:29,850 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:29,851 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:29,852 - INFO - integrating rxn: EX_cpd00205_e0
2026-01-13 19:32:29,853 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:29,853 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:29,854 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:29,854 - INFO - integrating rxn: EX_cpd00129_e0
2026-01-13 19:32:29,856 - INFO - integrating rxn: EX_cpd00084_e0
2026-01-13 19:32:29,856 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:29,857 - INFO - integrating rxn: EX_cpd00107_e0
2026-01-13 19:32:29,858 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:29,858 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:29,859 - INFO - integrating rxn: rxn00530_c0
2026-01-13 19:32:29,860 - INFO - integrating rxn: EX_cpd00027_e0
2026-01-13 19:32:29,861 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:29,861 - INFO - integrating rxn: EX_cpd00060_e0
2026-01-13 19:32:29,863 - INFO - integrating rxn: EX_cpd00069_e0
2026-01-13 19:32:29,862 - INFO - integrating rxn: rxn05300_c0
2026-01-13 19:32:29,864 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:29,864 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:29,865 - INFO - integrating rxn: EX_cpd00322_e0
2026-01-13 19:32:29,866 - INFO - integrating rxn: rxn00060_c0
2026-01-13 19:32:29,867 - INFO - integrating rxn: EX_cpd00156_e0
2026-01-13 19:32:29,867 - INFO - integrating rxn: rxn00100_c0
2026-01-13 19:32:29,868 - INFO - integrating rxn: EX_cpd00051_e0
2026-01-13 19:32:29,869 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:29,870 - INFO - integrating rxn: EX_cpd00066_e0
2026-01-13 19:32:29,870 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:29,871 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:32:29,872 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:29,873 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:29,873 - INFO - integrating rxn: rxn09427_c0
2026-01-13 19:32:29,874 - INFO - integrating rxn: rxn00364_c0
2026-01-13 19:32:29,875 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:29,875 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:29,876 - INFO - integrating rxn: rxn05243_c0
2026-01-13 19:32:29,877 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:29,877 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:29,878 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:29,879 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:29,879 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:29,880 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:29,881 - INFO - integrating rxn: rxn01636_c0
2026-01-13 19:32:29,881 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:29,882 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:29,882 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:29,883 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:29,884 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:29,885 - INFO - integrating rxn: rxn00100_c0
2026-01-13 19:32:29,885 - INFO - integrating rxn: rxn00029_c0
2026-01-13 19:32:29,886 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:29,887 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:29,887 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:29,888 - INFO - integrating rxn: rxn04464_c0
2026-01-13 19:32:29,888 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:29,889 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:29,890 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:29,890 - INFO - integrating rxn: rxn00213_c0
2026-01-13 19:32:29,891 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:29,892 - INFO - integrating rxn: rxn01629_c0
2026-01-13 19:32:29,892 - INFO - integrating rxn: rxn05161_c0
2026-01-13 19:32:29,893 - INFO - integrating rxn: rxn01740_c0
2026-01-13 19:32:29,894 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:29,894 - INFO - integrating rxn: rxn05244_c0
2026-01-13 19:32:29,896 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:29,896 - INFO - integrating rxn: rxn00272_c0
2026-01-13 19:32:29,897 - INFO - integrating rxn: rxn01484_c0
2026-01-13 19:32:29,897 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:29,898 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:29,899 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:29,900 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:29,900 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:29,901 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:29,902 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:29,902 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:29,903 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:29,904 - INFO - integrating rxn: rxn05303_c0
2026-01-13 19:32:29,904 - INFO - integrating rxn: rxn00830_c0
2026-01-13 19:32:29,905 - INFO - integrating rxn: rxn11703_c0

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00205_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00129_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00107_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00322_e0': '<', 'EX_cpd00156_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00364_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn05161_c0': '>', 'rxn08708_c0': '>', 'rxn00272_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01454_c0': '<', 'rxn01501_c0': '<', 'rxn05244_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn02229_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn05299_c0': '>', 'rxn09657_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn03087_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn05165_c0': '>', 'rxn05618_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn06865_c0': '<', 'rxn05226_c0': '>', 'rxn00615_c0': '>', 'rxn01265_c0': '<', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn00122_c0': '>', 'rxn05301_c0': '>', 'rxn01602_c0': '<', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn05596_c0': '<', 'rxn00338_c0': '>', 'rxn02287_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn01538_c0': '>', 'rxn05669_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn05306_c0': '>', 'rxn05305_c0': '<', 'rxn00686_c0': '<', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn08233_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn46249_c0': '>', 'rxn40040_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn09390_c0': '>', 'rxn10120_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:30,374 - INFO - AuxoMedia/bio1:rxn20508_c0> needed:0.0 with min obj:0.01

2026-01-13 19:32:30,376 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00205_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00129_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00322_e0', '<', 'new'], ['EX_cpd00156_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00364_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00272_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01454_c0', '<', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn05244_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn02229_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05165_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn05596_c0', '<', 'new'], ['rxn00338_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05669_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:30,376 - INFO -     Added 136 reactions
2026-01-13 19:32:30,377 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:30,377 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:30,379 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:30,381 - INFO - AuxoMedia/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:30,382 - INFO - AuxoMedia/bio1:rxn41492_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:30,384 - INFO - AuxoMedia/bio1:rxn44493_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:30,385 - INFO - AuxoMedia/bio1:rxn42332_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:30,387 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:30,388 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:30,390 - INFO - rxn29260_c0> not needed:3.111837576380544
2026-01-13 19:32:30,391 - INFO - rxn14423_c0> not needed:3.111837576380544
2026-01-13 19:32:30,392 - INFO - Objective with gapfill database:137.21706849317238; min objective:0.01
2026-01-13 19:32:30,394 - INFO - Unneeded: [['EX_cpd00039_e0', '<', 'new', -10, None], ['EX_cpd00033_e0', '<', 'new', -10, None], ['EX_cpd00161_e0', '<', 'new', -10, None], ['rxn05300_c0', '>', 'new', 100, None], ['rxn08661_c0', '>', 'new', 100, None], ['rxn08854_c0', '>', 'new', 100, None], ['rxn00778_c0', '>', 'new', 100, None], ['rxn06075_c0', '<', 'new', -100, None], ['rxn14424_c0', '>', 'new', 100, None], ['rxn14178_c0', '>', 'new', 100, None], ['rxn16114_c0', '>', 'new', 100, None], ['rxn08233_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn14423_c0', '>', 'new', 100, None]]
2026-01-13 19:32:30,400 - INFO - cpd00263 not found in model!
2026-01-13 19:32:30,400 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:30,401 - INFO - cpd00215 not found in model!
2026-01-13 19:32:30,402 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:30,404 - INFO - Growth: 4.607989371644357 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00033_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00107_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00322_e0': '<', 'EX_cpd00156_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn00530_c0': '>', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn12512_c0': '>', 'rxn00060_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn09427_c0': '>', 'rxn03918_c0': '>', 'rxn05243_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn04464_c0': '<', 'rxn01505_c0': '>', 'rxn00213_c0': '>', 'rxn01629_c0': '<', 'rxn01740_c0': '<', 'rxn05244_c0': '>', 'rxn03919_c0': '>', 'rxn01484_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn05303_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn09113_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn08661_c0': '>', 'rxn00420_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn05231_c0': '>', 'rxn00283_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn03150_c0': '>', 'rxn08854_c0': '>', 'rxn00101_c0': '>', 'rxn02303_c0': '>', 'rxn03087_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn02213_c0': '>', 'rxn05226_c0': '>', 'rxn00615_c0': '>', 'rxn00834_c0': '>', 'rxn11702_c0': '>', 'rxn01332_c0': '>', 'rxn01790_c0': '<', 'rxn05651_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn06076_c0': '<', 'rxn05301_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn01304_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05669_c0': '>', 'rxn05255_c0': '>', 'rxn00778_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05306_c0': '>', 'rxn06075_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn15395_c0': '>', 'rxn14178_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn15270_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:30,407 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00107_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00069_e0', '<', 'new'], ['EX_cpd00322_e0', '<', 'new'], ['EX_cpd00156_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['EX_cpd00066_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn00530_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn09427_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn05243_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn04464_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00213_c0', '>', 'new'], ['rxn01629_c0', '<', 'new'], ['rxn01740_c0', '<', 'new'], ['rxn05244_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn01484_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn05303_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn09113_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00970_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn05231_c0', '>', 'new'], ['rxn00283_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn00101_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn02213_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn06076_c0', '<', 'new'], ['rxn05301_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn01304_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05669_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn06591_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05306_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn15395_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:32:30,408 - INFO -     Added 161 reactions
2026-01-13 19:32:30,408 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:32,457 - INFO - Objective with gapfill database:137.21706849317326; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:32,906 - INFO - Objective with gapfill database:137.21706849317238; min objective:0.01
2026-01-13 19:32:33,284 - INFO - Objective with gapfill database:137.2170684931733; min objective:0.01
2026-01-13 19:32:33,467 - INFO - Objective with gapfill database:137.21706849317164; min objective:0.01
2026-01-13 19:32:33,551 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00034_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00099_e0': '<', 'rxn08709_c0': '>', 'rxn00359_c0': '<', 'rxn02000_c0': '>', 'rxn03086_c0': '<', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn04996_c0': '<', 'rxn03030_c0': '>', 'rxn01636_c0': '>', 'rxn02988_c0': '<', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn00579_c0': '<', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01256_c0': '>', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn10124_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn13647_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00611_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn02285_c0': '<', 'rxn02303_c0': '>', 'rxn05315_c0': '<', 'rxn03907_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00599_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn05117_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn01790_c0': '<', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn03130_c0': '>', 'rxn00623_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn01513_c0': '>', 'rxn00117_c0': '>', 'rxn01520_c0': '>', 'rxn00399_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14428_c0': '>', 'rxn14423_c0': '>', 'rxn10120_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:33,554 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:33,555 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:33,557 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:33,559 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:33,560 - INFO - integrating rxn: EX_cpd00034_e0
2026-01-13 19:32:33,562 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:33,563 - INFO - integrating rxn: EX_cpd00060_e0
2026-01-13 19:32:33,565 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:33,566 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:33,568 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:32:33,569 - INFO - integrating rxn: rxn02000_c0
2026-01-13 19:32:33,571 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:32:33,573 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:33,574 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:32:33,575 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:33,577 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:33,578 - INFO - integrating rxn: rxn04996_c0
2026-01-13 19:32:33,580 - INFO - integrating rxn: rxn03030_c0
2026-01-13 19:32:33,581 - INFO - integrating rxn: rxn01636_c0
2026-01-13 19:32:33,583 - INFO - integrating rxn: rxn02988_c0
2026-01-13 19:32:33,584 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:33,586 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:33,588 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:33,589 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:33,591 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:33,593 - INFO - integrating rxn: rxn00060_c0
2026-01-13 19:32:33,594 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:33,595 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:33,597 - INFO - integrating rxn: rxn09202_c0
2026-01-13 19:32:33,598 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:33,600 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:33,601 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:33,603 - INFO - integrating rxn: rxn00579_c0
2026-01-13 19:32:33,604 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:33,605 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:33,607 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:33,608 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:33,610 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:33,611 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:33,612 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:33,614 - INFO - integrating rxn: rxn05219_c0
2026-01-13 19:32:33,615 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:33,616 - INFO - integrating rxn: rxn00029_c0
2026-01-13 19:32:33,618 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:33,619 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:33,621 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:32:33,622 - INFO - integrating rxn: rxn00237_c0
2026-01-13 19:32:33,624 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:33,625 - INFO - integrating rxn: rxn10124_c0
2026-01-13 19:32:33,626 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:33,628 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:33,629 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:33,631 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:33,633 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:33,634 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:32:33,636 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:33,637 - INFO - integrating rxn: rxn01972_c0
2026-01-13 19:32:33,638 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:33,640 - INFO - integrating rxn: rxn13647_c0
2026-01-13 19:32:33,641 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:33,643 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:33,644 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:33,645 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:33,647 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:33,648 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:33,649 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:33,651 - INFO - integrating rxn: rxn02402_c0
2026-01-13 19:32:33,652 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:33,653 - INFO - integrating rxn: rxn06023_c0
2026-01-13 19:32:33,655 - INFO - integrating rxn: rxn00611_c0
2026-01-13 19:32:33,657 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:33,658 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:33,659 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:33,660 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:33,662 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:33,663 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:33,665 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:33,666 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:33,668 - INFO - integrating rxn: rxn05029_c0
2026-01-13 19:32:33,669 - INFO - integrating rxn: rxn02285_c0
2026-01-13 19:32:33,671 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:33,672 - INFO - integrating rxn: rxn05315_c0
2026-01-13 19:32:33,674 - INFO - integrating rxn: rxn03907_c0
2026-01-13 19:32:33,675 - INFO - integrating rxn: rxn03538_c0
2026-01-13 19:32:33,676 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:33,678 - INFO - integrating rxn: rxn02304_c0
2026-01-13 19:32:33,679 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:33,680 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:33,682 - INFO - integrating rxn: rxn01512_c0
2026-01-13 19:32:33,683 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:33,685 - INFO - integrating rxn: rxn04113_c0
2026-01-13 19:32:33,687 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:33,688 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:32:33,689 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:33,691 - INFO - integrating rxn: rxn05117_c0
2026-01-13 19:32:33,692 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:33,694 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:33,695 - INFO - integrating rxn: rxn00346_c0
2026-01-13 19:32:33,697 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:33,698 - INFO - integrating rxn: rxn02897_c0
2026-01-13 19:32:33,700 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:33,701 - INFO - integrating rxn: rxn02003_c0
2026-01-13 19:32:33,702 - INFO - integrating rxn: rxn00130_c0
2026-01-13 19:32:33,704 - INFO - integrating rxn: rxn00912_c0
2026-01-13 19:32:33,705 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:33,706 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:33,708 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:33,709 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:33,711 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:33,712 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:33,713 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:33,715 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:33,716 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:33,717 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:33,719 - INFO - integrating rxn: rxn00138_c0
2026-01-13 19:32:33,720 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:33,721 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:32:33,723 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:33,724 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:33,725 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:33,727 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:33,728 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:33,729 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:33,731 - INFO - integrating rxn: rxn01513_c0
2026-01-13 19:32:33,732 - INFO - integrating rxn: rxn00117_c0
2026-01-13 19:32:33,733 - INFO - integrating rxn: rxn01520_c0
2026-01-13 19:32:33,735 - INFO - integrating rxn: rxn00399_c0
2026-01-13 19:32:33,735 - INFO - Objective with gapfill database:137.21706849317363; min objective:0.01
2026-01-13 19:32:33,737 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:33,738 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:33,740 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:33,741 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:33,743 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:33,745 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:33,746 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:32:33,748 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:33,749 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:33,750 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:33,752 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:32:33,753 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:32:33,755 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:32:33,756 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:32:33,757 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:33,759 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:33,760 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:33,761 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:32:33,763 - INFO - integrating rxn: rxn00154_c0
2026-01-13 19:32:33,764 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:33,765 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:33,767 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:33,768 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:32:33,770 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:32:33,771 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:32:33,773 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:32:33,775 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:32:33,776 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:32:33,778 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:33,779 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:33,781 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:33,782 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:32:33,783 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:33,785 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:33,786 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:32:33,787 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:32:33,789 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:33,790 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:33,792 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:33,793 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:33,794 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:32:33,796 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:32:33,797 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:32:33,799 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:33,800 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:33,801 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:33,803 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:33,804 - INFO - integrating rxn: rxn14428_c0
2026-01-13 19:32:33,806 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:33,808 - INFO - integrating rxn: rxn10120_c0
2026-01-13 19:32:33,809 - INFO - integrating rxn: rxn10042_c0

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00034_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00099_e0': '<', 'rxn08709_c0': '>', 'rxn00359_c0': '<', 'rxn02000_c0': '>', 'rxn03086_c0': '<', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn04996_c0': '<', 'rxn03030_c0': '>', 'rxn01636_c0': '>', 'rxn02988_c0': '<', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn00579_c0': '<', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01256_c0': '>', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn10124_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn13647_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00611_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn02285_c0': '<', 'rxn02303_c0': '>', 'rxn05315_c0': '<', 'rxn03907_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00599_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn05117_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn01790_c0': '<', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn03130_c0': '>', 'rxn00623_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn01513_c0': '>', 'rxn00117_c0': '>', 'rxn01520_c0': '>', 'rxn00399_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14428_c0': '>', 'rxn14423_c0': '>', 'rxn10120_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:34,164 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00034_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00359_c0', '<', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn04996_c0', '<', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00579_c0', '<', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn13647_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00611_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn02285_c0', '<', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn05315_c0', '<', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01513_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00399_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn00154_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14428_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:32:34,165 - INFO -     Added 152 reactions
2026-01-13 19:32:34,166 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:34,493 - INFO - Objective with gapfill database:143.8231579611122; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:35,003 - INFO - Objective with gapfill database:137.21706849317326; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:35,584 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn00179_c0': '>', 'rxn10336_c0': '>', 'rxn05235_c0': '>', 'rxn02988_c0': '<', 'rxn01117_c0': '<', 'rxn00530_c0': '>', 'rxn00710_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn01739_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn02212_c0': '>', 'rxn03918_c0': '>', 'rxn00340_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn02404_c0': '>', 'rxn01465_c0': '<', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn05744_c0': '>', 'rxn06777_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn01740_c0': '<', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn00126_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn01255_c0': '>', 'rxn06848_c0': '<', 'rxn13850_c0': '<', 'rxn03537_c0': '>', 'rxn02011_c0': '>', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn10954_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn03843_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn05347_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn00931_c0': '<', 'rxn03244_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn13846_c0': '<', 'rxn08020_c0': '>', 'rxn03917_c0': '>', 'rxn05231_c0': '>', 'rxn01018_c0': '>', 'rxn00440_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn05349_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn05663_c0': '>', 'rxn01213_c0': '>', 'rxn01361_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn00461_c0': '>', 'rxn03136_c0': '>', 'rxn08088_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn03249_c0': '<', 'rxn02213_c0': '>', 'rxn01265_c0': '<', 'rxn01332_c0': '>', 'rxn05117_c0': '>', 'rxn03909_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00558_c0': '>', 'rxn01790_c0': '<', 'rxn05651_c0': '>', 'rxn02056_c0': '<', 'rxn03242_c0': '<', 'rxn00541_c0': '>', 'rxn01434_c0': '>', 'rxn12147_c0': '>', 'rxn00122_c0': '>', 'rxn05301_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03901_c0': '>', 'rxn00138_c0': '>', 'rxn06729_c0': '>', 'rxn00239_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn03246_c0': '<', 'rxn05306_c0': '>', 'rxn06075_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn25474_c0': '>', 'rxn19346_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:35,587 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 19:32:35,588 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:35,590 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:35,591 - INFO - integrating rxn: EX_cpd00048_e0
2026-01-13 19:32:35,593 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:35,594 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:35,596 - INFO - integrating rxn: EX_cpd00084_e0
2026-01-13 19:32:35,597 - INFO - integrating rxn: EX_cpd00149_e0
2026-01-13 19:32:35,598 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:35,600 - INFO - integrating rxn: EX_cpd00060_e0
2026-01-13 19:32:35,601 - INFO - integrating rxn: EX_cpd00069_e0
2026-01-13 19:32:35,602 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:35,604 - INFO - integrating rxn: EX_cpd00066_e0
2026-01-13 19:32:35,605 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:32:35,607 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:35,608 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:35,610 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:32:35,611 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:32:35,613 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:35,614 - INFO - integrating rxn: rxn05235_c0
2026-01-13 19:32:35,616 - INFO - integrating rxn: rxn02988_c0
2026-01-13 19:32:35,617 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:35,619 - INFO - integrating rxn: rxn00530_c0
2026-01-13 19:32:35,620 - INFO - integrating rxn: rxn00710_c0
2026-01-13 19:32:35,622 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:35,623 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:35,625 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:35,626 - INFO - integrating rxn: rxn01739_c0
2026-01-13 19:32:35,628 - INFO - integrating rxn: rxn00060_c0
2026-01-13 19:32:35,629 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:35,631 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:35,632 - INFO - integrating rxn: rxn09202_c0
2026-01-13 19:32:35,633 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:35,635 - INFO - integrating rxn: rxn02212_c0
2026-01-13 19:32:35,636 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:35,638 - INFO - integrating rxn: rxn00340_c0
2026-01-13 19:32:35,639 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:35,641 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:35,642 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:35,644 - INFO - integrating rxn: rxn01465_c0
2026-01-13 19:32:35,645 - INFO - integrating rxn: rxn06937_c0
2026-01-13 19:32:35,647 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:35,648 - INFO - integrating rxn: rxn05219_c0
2026-01-13 19:32:35,650 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:35,652 - INFO - integrating rxn: rxn05744_c0
2026-01-13 19:32:35,653 - INFO - integrating rxn: rxn06777_c0
2026-01-13 19:32:35,654 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:35,656 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:35,657 - INFO - integrating rxn: rxn01740_c0
2026-01-13 19:32:35,659 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:35,660 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:35,662 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:35,663 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:35,665 - INFO - integrating rxn: rxn00126_c0
2026-01-13 19:32:35,666 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:35,668 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:35,669 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:35,671 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:35,672 - INFO - integrating rxn: rxn01255_c0
2026-01-13 19:32:35,674 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:35,675 - INFO - integrating rxn: rxn13850_c0
2026-01-13 19:32:35,677 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:35,678 - INFO - integrating rxn: rxn02011_c0
2026-01-13 19:32:35,679 - INFO - integrating rxn: rxn08528_c0
2026-01-13 19:32:35,681 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:35,682 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:35,684 - INFO - integrating rxn: rxn10954_c0
2026-01-13 19:32:35,685 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:35,687 - INFO - integrating rxn: rxn05237_c0
2026-01-13 19:32:35,688 - INFO - integrating rxn: rxn03843_c0
2026-01-13 19:32:35,690 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:35,691 - INFO - integrating rxn: rxn02402_c0
2026-01-13 19:32:35,692 - INFO - integrating rxn: rxn05347_c0
2026-01-13 19:32:35,694 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:32:35,695 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:35,696 - INFO - integrating rxn: rxn06023_c0
2026-01-13 19:32:35,698 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:35,699 - INFO - integrating rxn: rxn00970_c0
2026-01-13 19:32:35,701 - INFO - integrating rxn: rxn00931_c0
2026-01-13 19:32:35,702 - INFO - integrating rxn: rxn03244_c0
2026-01-13 19:32:35,704 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:35,705 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:35,707 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:35,708 - INFO - integrating rxn: rxn13846_c0
2026-01-13 19:32:35,709 - INFO - integrating rxn: rxn08020_c0
2026-01-13 19:32:35,711 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:35,712 - INFO - integrating rxn: rxn05231_c0
2026-01-13 19:32:35,713 - INFO - integrating rxn: rxn01018_c0
2026-01-13 19:32:35,715 - INFO - integrating rxn: rxn00440_c0
2026-01-13 19:32:35,716 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:35,718 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:35,719 - INFO - integrating rxn: rxn05349_c0
2026-01-13 19:32:35,721 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:35,722 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:35,724 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:35,725 - INFO - integrating rxn: rxn05663_c0
2026-01-13 19:32:35,726 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:35,728 - INFO - integrating rxn: rxn01361_c0
2026-01-13 19:32:35,730 - INFO - integrating rxn: rxn05618_c0
2026-01-13 19:32:35,731 - INFO - integrating rxn: rxn08241_c0
2026-01-13 19:32:35,733 - INFO - integrating rxn: rxn00461_c0
2026-01-13 19:32:35,734 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:35,736 - INFO - integrating rxn: rxn08088_c0
2026-01-13 19:32:35,737 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:35,738 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:35,740 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:35,741 - INFO - integrating rxn: rxn03249_c0
2026-01-13 19:32:35,743 - INFO - integrating rxn: rxn02213_c0
2026-01-13 19:32:35,742 - INFO - Objective with gapfill database:137.2170684931733; min objective:0.01
2026-01-13 19:32:35,744 - INFO - integrating rxn: rxn01265_c0
2026-01-13 19:32:35,745 - INFO - integrating rxn: rxn01332_c0
2026-01-13 19:32:35,747 - INFO - integrating rxn: rxn05117_c0
2026-01-13 19:32:35,748 - INFO - integrating rxn: rxn03909_c0
2026-01-13 19:32:35,750 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:35,751 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:35,753 - INFO - integrating rxn: rxn00558_c0
2026-01-13 19:32:35,754 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:35,755 - INFO - integrating rxn: rxn05651_c0
2026-01-13 19:32:35,757 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:35,758 - INFO - integrating rxn: rxn03242_c0
2026-01-13 19:32:35,759 - INFO - integrating rxn: rxn00541_c0
2026-01-13 19:32:35,761 - INFO - integrating rxn: rxn01434_c0
2026-01-13 19:32:35,762 - INFO - integrating rxn: rxn12147_c0
2026-01-13 19:32:35,763 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:35,765 - INFO - integrating rxn: rxn05301_c0
2026-01-13 19:32:35,766 - INFO - integrating rxn: rxn05223_c0
2026-01-13 19:32:35,768 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:35,770 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:35,772 - INFO - integrating rxn: rxn01466_c0
2026-01-13 19:32:35,773 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:35,774 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:35,776 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:35,777 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:35,778 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:35,780 - INFO - integrating rxn: rxn03901_c0
2026-01-13 19:32:35,781 - INFO - integrating rxn: rxn00138_c0
2026-01-13 19:32:35,783 - INFO - integrating rxn: rxn06729_c0
2026-01-13 19:32:35,784 - INFO - integrating rxn: rxn00239_c0
2026-01-13 19:32:35,786 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:35,787 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:35,788 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:35,790 - INFO - integrating rxn: rxn06591_c0
2026-01-13 19:32:35,791 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:35,792 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:35,794 - INFO - integrating rxn: rxn03246_c0
2026-01-13 19:32:35,795 - INFO - integrating rxn: rxn05306_c0
2026-01-13 19:32:35,797 - INFO - integrating rxn: rxn06075_c0
2026-01-13 19:32:35,798 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:35,799 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:35,801 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:35,802 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:35,804 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:35,805 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:35,807 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:35,809 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:35,811 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:35,812 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:35,814 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:35,815 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:35,817 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:35,818 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:35,820 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:35,821 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:35,822 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:35,824 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:35,825 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:35,827 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:35,828 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:35,830 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:32:35,831 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:35,832 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:35,834 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:35,835 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:35,837 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:35,838 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:35,839 - INFO - Full solution: [['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00069_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00066_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00530_c0', '>', 'new'], ['rxn00710_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn02212_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00340_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn01465_c0', '<', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn05744_c0', '>', 'new'], ['rxn06777_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01740_c0', '<', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn00126_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01255_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn13850_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn03843_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn05347_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00970_c0', '<', 'new'], ['rxn00931_c0', '<', 'new'], ['rxn03244_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn13846_c0', '<', 'new'], ['rxn08020_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn05231_c0', '>', 'new'], ['rxn01018_c0', '>', 'new'], ['rxn00440_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn05349_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn01361_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn00461_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn03249_c0', '<', 'new'], ['rxn02213_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03909_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00558_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03242_c0', '<', 'new'], ['rxn00541_c0', '>', 'new'], ['rxn01434_c0', '>', 'new'], ['rxn12147_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05301_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03901_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn06729_c0', '>', 'new'], ['rxn00239_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn06591_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn03246_c0', '<', 'new'], ['rxn05306_c0', '>', 'new'], ['rxn06075_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:35,871 - INFO - AuxoMedia/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:35,873 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn00179_c0': '>', 'rxn10336_c0': '>', 'rxn05235_c0': '>', 'rxn02988_c0': '<', 'rxn01117_c0': '<', 'rxn00530_c0': '>', 'rxn00710_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn01739_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn02212_c0': '>', 'rxn03918_c0': '>', 'rxn00340_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn02404_c0': '>', 'rxn01465_c0': '<', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn05744_c0': '>', 'rxn06777_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn01740_c0': '<', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn00126_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn01255_c0': '>', 'rxn06848_c0': '<', 'rxn13850_c0': '<', 'rxn03537_c0': '>', 'rxn02011_c0': '>', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn10954_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn03843_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn05347_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn00931_c0': '<', 'rxn03244_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn13846_c0': '<', 'rxn08020_c0': '>', 'rxn03917_c0': '>', 'rxn05231_c0': '>', 'rxn01018_c0': '>', 'rxn00440_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn05349_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn05663_c0': '>', 'rxn01213_c0': '>', 'rxn01361_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn00461_c0': '>', 'rxn03136_c0': '>', 'rxn08088_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn03249_c0': '<', 'rxn02213_c0': '>', 'rxn01265_c0': '<', 'rxn01332_c0': '>', 'rxn05117_c0': '>', 'rxn03909_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00558_c0': '>', 'rxn01790_c0': '<', 'rxn05651_c0': '>', 'rxn02056_c0': '<', 'rxn03242_c0': '<', 'rxn00541_c0': '>', 'rxn01434_c0': '>', 'rxn12147_c0': '>', 'rxn00122_c0': '>', 'rxn05301_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03901_c0': '>', 'rxn00138_c0': '>', 'rxn06729_c0': '>', 'rxn00239_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn06591_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn03246_c0': '<', 'rxn05306_c0': '>', 'rxn06075_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn25474_c0': '>', 'rxn19346_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:36,145 - INFO - Cumulative: [['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00530_c0', '>', 'new'], ['rxn00710_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn02212_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00340_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn01465_c0', '<', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn05744_c0', '>', 'new'], ['rxn06777_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01740_c0', '<', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn00126_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01255_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn13850_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn03843_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn05347_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00970_c0', '<', 'new'], ['rxn00931_c0', '<', 'new'], ['rxn03244_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn13846_c0', '<', 'new'], ['rxn08020_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn05231_c0', '>', 'new'], ['rxn01018_c0', '>', 'new'], ['rxn00440_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn05349_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn01361_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn00461_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn03249_c0', '<', 'new'], ['rxn02213_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03909_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00558_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03242_c0', '<', 'new'], ['rxn00541_c0', '>', 'new'], ['rxn01434_c0', '>', 'new'], ['rxn12147_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03901_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn06729_c0', '>', 'new'], ['rxn00239_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn06591_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn03246_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:32:36,145 - INFO -     Added 158 reactions
2026-01-13 19:32:36,146 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:36,259 - INFO - Objective with gapfill database:137.21706849317363; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:36,341 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'rxn08709_c0': '>', 'rxn02000_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn04996_c0': '<', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn01256_c0': '>', 'rxn00503_c0': '<', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn04704_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05463_c0': '>', 'rxn01345_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00834_c0': '>', 'rxn00599_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn05117_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn00141_c0': '>', 'rxn02003_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn00686_c0': '<', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn21859_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn10095_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn45223_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn10120_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:36,344 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:36,347 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:36,348 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:36,350 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:36,351 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:36,353 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:36,354 - INFO - integrating rxn: rxn02000_c0
2026-01-13 19:32:36,356 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:36,357 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:36,359 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:36,360 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:36,362 - INFO - integrating rxn: rxn04996_c0
2026-01-13 19:32:36,363 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:36,364 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:32:36,366 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:36,368 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:36,369 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:36,371 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:36,372 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:36,374 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:36,375 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:36,376 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:36,378 - INFO - integrating rxn: rxn01997_c0
2026-01-13 19:32:36,379 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:36,381 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:36,382 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:36,384 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:36,385 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:36,387 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:36,388 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:36,389 - INFO - integrating rxn: rxn06937_c0
2026-01-13 19:32:36,391 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:36,393 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:36,394 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:36,395 - INFO - integrating rxn: rxn01675_c0
2026-01-13 19:32:36,397 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:36,398 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:32:36,400 - INFO - integrating rxn: rxn00503_c0
2026-01-13 19:32:36,401 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:36,403 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:36,404 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:36,406 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:36,407 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:36,409 - INFO - integrating rxn: rxn04704_c0
2026-01-13 19:32:36,411 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:36,412 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:32:36,414 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:36,415 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:36,417 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:36,418 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:36,420 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:36,421 - INFO - integrating rxn: rxn08528_c0
2026-01-13 19:32:36,423 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:36,424 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:36,426 - INFO - integrating rxn: rxn05463_c0
2026-01-13 19:32:36,427 - INFO - integrating rxn: rxn01345_c0
2026-01-13 19:32:36,429 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:36,430 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:36,431 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:36,433 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:32:36,435 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:36,436 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:36,437 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:36,439 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:36,440 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:36,441 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:36,443 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:36,444 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:36,445 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:36,447 - INFO - integrating rxn: rxn02304_c0
2026-01-13 19:32:36,448 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:36,449 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:36,451 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:36,453 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:36,454 - INFO - integrating rxn: rxn04113_c0
2026-01-13 19:32:36,455 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:36,457 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:36,458 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:32:36,460 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:36,461 - INFO - integrating rxn: rxn05117_c0
2026-01-13 19:32:36,463 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:36,464 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:36,466 - INFO - integrating rxn: rxn00346_c0
2026-01-13 19:32:36,467 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:36,468 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:36,470 - INFO - integrating rxn: rxn00134_c0
2026-01-13 19:32:36,471 - INFO - integrating rxn: rxn00141_c0
2026-01-13 19:32:36,472 - INFO - integrating rxn: rxn02003_c0
2026-01-13 19:32:36,474 - INFO - integrating rxn: rxn00912_c0
2026-01-13 19:32:36,475 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:36,477 - INFO - integrating rxn: rxn01602_c0
2026-01-13 19:32:36,478 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:36,479 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:36,481 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:36,482 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:36,483 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:36,485 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:36,486 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:36,487 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:36,488 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:36,490 - INFO - integrating rxn: rxn00138_c0
2026-01-13 19:32:36,491 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:36,492 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:36,494 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:36,495 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:36,496 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:36,498 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:36,499 - INFO - integrating rxn: rxn00686_c0
2026-01-13 19:32:36,501 - INFO - integrating rxn: rxn01520_c0
2026-01-13 19:32:36,502 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:36,503 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:36,506 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:36,507 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:32:36,509 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:36,510 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:36,511 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:36,513 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:36,515 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:36,516 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:36,517 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:32:36,519 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:36,520 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:36,521 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:36,523 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:32:36,524 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:32:36,526 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:32:36,527 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:32:36,528 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:36,530 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:36,531 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:36,533 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:32:36,534 - INFO - integrating rxn: rxn00154_c0
2026-01-13 19:32:36,535 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:32:36,536 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:36,537 - INFO - Objective with gapfill database:137.2170684931728; min objective:0.01
2026-01-13 19:32:36,538 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:32:36,540 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:36,542 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:36,543 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:32:36,545 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:32:36,546 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:36,548 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:36,549 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:36,551 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:36,552 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:36,554 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:36,555 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:32:36,556 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:36,556 - INFO - Objective with gapfill database:137.2170684931731; min objective:0.01
2026-01-13 19:32:36,557 - INFO - integrating rxn: rxn08154_c0
2026-01-13 19:32:36,559 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:36,560 - INFO - integrating rxn: rxn45223_c0
2026-01-13 19:32:36,562 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:36,563 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:36,564 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:36,566 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:36,567 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:36,568 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:36,570 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:36,571 - INFO - integrating rxn: rxn10120_c0
2026-01-13 19:32:36,573 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:36,573 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn04996_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn01345_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn21859_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn00154_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08154_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn45223_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10120_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:36,608 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:36,610 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:36,612 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:36,613 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:36,614 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:36,616 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,617 - INFO - AuxoMedia/bio1:rxn02000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,619 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,620 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,622 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,623 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,625 - INFO - AuxoMedia/bio1:rxn04996_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:36,627 - INFO - AuxoMedia/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:36,628 - INFO - AuxoMedia/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,630 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,631 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,633 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:36,634 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,636 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:36,637 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01

Adding gapfilling

2026-01-13 19:32:36,895 - INFO - integrating rxn: rxn03978_c0

 {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'rxn08709_c0': '>', 'rxn02000_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn04996_c0': '<', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn01256_c0': '>', 'rxn00503_c0': '<', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn04704_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05463_c0': '>', 'rxn01345_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00834_c0': '>', 'rxn00599_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn05117_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn00141_c0': '>', 'rxn02003_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn00686_c0': '<', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn21859_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn10095_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn45223_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn10120_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:36,896 - INFO - integrating rxn: rxn02405_c0

2026-01-13 19:32:36,898 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:36,898 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn04996_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn01345_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10120_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:36,899 - INFO -     Added 135 reactions
2026-01-13 19:32:36,899 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:36,900 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:36,901 - INFO - integrating rxn: rxn05663_c0
2026-01-13 19:32:36,903 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:36,904 - INFO - integrating rxn: rxn05618_c0
2026-01-13 19:32:36,906 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:36,907 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:36,908 - INFO - integrating rxn: rxn01512_c0
2026-01-13 19:32:36,910 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:36,911 - INFO - integrating rxn: rxn04113_c0
2026-01-13 19:32:36,912 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:36,914 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:36,915 - INFO - integrating rxn: rxn05117_c0
2026-01-13 19:32:36,917 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:36,918 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:36,920 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:36,921 - INFO - integrating rxn: rxn00912_c0
2026-01-13 19:32:36,922 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:36,924 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:36,925 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:36,926 - INFO - integrating rxn: rxn00567_c0
2026-01-13 19:32:36,928 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:36,929 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:36,930 - INFO - integrating rxn: rxn00409_c0
2026-01-13 19:32:36,932 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:36,933 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:36,934 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:36,936 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:36,937 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:36,938 - INFO - integrating rxn: rxn00138_c0
2026-01-13 19:32:36,940 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:36,941 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:36,942 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:36,943 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:36,945 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:36,946 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:36,947 - INFO - integrating rxn: rxn00117_c0
2026-01-13 19:32:36,949 - INFO - integrating rxn: rxn00399_c0
2026-01-13 19:32:36,950 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:36,952 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:36,953 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:32:36,955 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:36,956 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:36,958 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:36,957 - INFO - Objective with gapfill database:143.8231579611122; min objective:0.01
2026-01-13 19:32:36,959 - INFO - integrating rxn: rxn39982_c0
2026-01-13 19:32:36,961 - INFO - integrating rxn: rxn13195_c0
2026-01-13 19:32:36,963 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:36,964 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:36,966 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:36,967 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:32:36,968 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:36,970 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:36,971 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:32:36,972 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:32:36,974 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:32:36,975 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:36,977 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:32:36,978 - INFO - integrating rxn: rxn00154_c0
2026-01-13 19:32:36,978 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00033_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00107_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00322_e0': '<', 'EX_cpd00156_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn10336_c0': '>', 'rxn01483_c0': '>', 'rxn00530_c0': '>', 'rxn00710_c0': '>', 'rxn00910_c0': '<', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn08583_c0': '>', 'rxn05514_c0': '<', 'rxn09427_c0': '>', 'rxn01362_c0': '<', 'rxn03918_c0': '>', 'rxn05243_c0': '>', 'rxn10030_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '<', 'rxn10213_c0': '>', 'rxn01301_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01505_c0': '>', 'rxn00213_c0': '>', 'rxn05573_c0': '>', 'rxn05244_c0': '>', 'rxn03919_c0': '>', 'rxn01484_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn09113_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn08661_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn03150_c0': '>', 'rxn00101_c0': '>', 'rxn02303_c0': '>', 'rxn03087_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn08241_c0': '<', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00371_c0': '>', 'rxn00615_c0': '>', 'rxn01265_c0': '<', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn05154_c0': '>', 'rxn01332_c0': '>', 'rxn03084_c0': '>', 'rxn01790_c0': '<', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn05301_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn02276_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05669_c0': '>', 'rxn05255_c0': '>', 'rxn00929_c0': '<', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn01513_c0': '>', 'rxn05306_c0': '>', 'rxn05305_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn39982_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn29260_c0': '>', 'rxn40324_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:36,979 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:36,981 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:32:36,983 - INFO - integrating rxn: EX_cpd00039_e0
2026-01-13 19:32:36,983 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:36,984 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:36,985 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:36,985 - INFO - integrating rxn: EX_cpd00033_e0
2026-01-13 19:32:36,986 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:32:36,987 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:36,988 - INFO - integrating rxn: rxn30633_c0
2026-01-13 19:32:36,988 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:36,989 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:36,990 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:36,991 - INFO - integrating rxn: rxn40142_c0
2026-01-13 19:32:36,991 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:36,992 - INFO - integrating rxn: rxn15395_c0
2026-01-13 19:32:36,993 - INFO - integrating rxn: EX_cpd00084_e0
2026-01-13 19:32:36,993 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:32:36,994 - INFO - integrating rxn: EX_cpd00149_e0
2026-01-13 19:32:36,995 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:32:36,995 - INFO - integrating rxn: EX_cpd00107_e0
2026-01-13 19:32:36,996 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:32:36,997 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:36,998 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:32:36,998 - INFO - integrating rxn: EX_cpd00161_e0
2026-01-13 19:32:36,999 - INFO - integrating rxn: rxn16141_c0
2026-01-13 19:32:37,000 - INFO - integrating rxn: EX_cpd00027_e0
2026-01-13 19:32:37,001 - INFO - integrating rxn: EX_cpd00060_e0
2026-01-13 19:32:37,001 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:37,002 - INFO - integrating rxn: EX_cpd00069_e0
2026-01-13 19:32:37,002 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:37,003 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:37,004 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:37,005 - INFO - integrating rxn: EX_cpd00322_e0
2026-01-13 19:32:37,006 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:37,006 - INFO - integrating rxn: EX_cpd00156_e0
2026-01-13 19:32:37,007 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:32:37,007 - INFO - integrating rxn: EX_cpd00051_e0
2026-01-13 19:32:37,008 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:37,009 - INFO - integrating rxn: EX_cpd00066_e0
2026-01-13 19:32:37,009 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:37,010 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:32:37,011 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:37,011 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:37,012 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:37,013 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:37,014 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:37,014 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:32:37,015 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:32:37,016 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:37,016 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:32:37,017 - INFO - integrating rxn: rxn01483_c0
2026-01-13 19:32:37,018 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:32:37,018 - INFO - integrating rxn: rxn00530_c0
2026-01-13 19:32:37,019 - INFO - integrating rxn: rxn47875_c0
2026-01-13 19:32:37,020 - INFO - integrating rxn: rxn00710_c0
2026-01-13 19:32:37,020 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:37,021 - INFO - integrating rxn: rxn00910_c0
2026-01-13 19:32:37,022 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:37,023 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:37,023 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:37,024 - INFO - integrating rxn: rxn05300_c0
2026-01-13 19:32:37,025 - INFO - integrating rxn: rxn41399_c0
2026-01-13 19:32:37,025 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:37,026 - INFO - integrating rxn: rxn41401_c0
2026-01-13 19:32:37,027 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:37,027 - INFO - integrating rxn: rxn15776_c0
2026-01-13 19:32:37,028 - INFO - integrating rxn: rxn09427_c0
2026-01-13 19:32:37,029 - INFO - integrating rxn: rxn14428_c0
2026-01-13 19:32:37,029 - INFO - integrating rxn: rxn01362_c0
2026-01-13 19:32:37,030 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:37,031 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:37,031 - INFO - integrating rxn: rxn10120_c0
2026-01-13 19:32:37,032 - INFO - integrating rxn: rxn05243_c0
2026-01-13 19:32:37,033 - INFO - integrating rxn: rxn10042_c0

Adding gapfilling

2026-01-13 19:32:37,409 - INFO - AuxoMedia/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,409 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:37,409 - INFO - integrating rxn: rxn05645_c0

 {'reversed': {}, 'new': {'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00094_e0': '>', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn04996_c0': '<', 'rxn03030_c0': '>', 'rxn02988_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn00060_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn00383_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01740_c0': '<', 'rxn00237_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn10094_c0': '>', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn00440_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn01333_c0': '<', 'rxn03978_c0': '<', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn05663_c0': '>', 'rxn01213_c0': '>', 'rxn05618_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00599_c0': '>', 'rxn11702_c0': '>', 'rxn05117_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn02056_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn00567_c0': '<', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn00117_c0': '>', 'rxn00399_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn21859_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn39982_c0': '>', 'rxn13195_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn30633_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn15395_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn16141_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn11285_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn16341_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn47875_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>', 'rxn14428_c0': '>', 'rxn14423_c0': '>', 'rxn10120_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:37,411 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:37,411 - INFO - AuxoMedia/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,411 - INFO - integrating rxn: rxn05237_c0

2026-01-13 19:32:37,412 - INFO - integrating rxn: rxn17394_c0
2026-01-13 19:32:37,413 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:37,412 - INFO - Cumulative: [['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn04996_c0', '<', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn00383_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01740_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn00440_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn00567_c0', '<', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn39982_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn00154_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn47875_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn41399_c0', '>', 'new'], ['rxn41401_c0', '>', 'new'], ['rxn15776_c0', '>', 'new'], ['rxn14428_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:32:37,413 - INFO - AuxoMedia/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,413 - INFO -     Added 143 reactions
2026-01-13 19:32:37,414 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:37,414 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:37,414 - INFO - integrating rxn: rxn16671_c0
2026-01-13 19:32:37,414 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,416 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:32:37,416 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:37,416 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,417 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:37,417 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:37,418 - INFO - AuxoMedia/bio1:rxn05301_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,418 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:37,419 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:32:37,420 - INFO - integrating rxn: rxn05325_c0
2026-01-13 19:32:37,420 - INFO - AuxoMedia/bio1:rxn05223_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,420 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:37,421 - INFO - integrating rxn: rxn01508_c0
2026-01-13 19:32:37,421 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,421 - INFO - integrating rxn: rxn44043_c0
2026-01-13 19:32:37,423 - INFO - integrating rxn: rxn00420_c0
2026-01-13 19:32:37,423 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:37,424 - INFO - AuxoMedia/bio1:rxn02276_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,424 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:37,425 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:37,425 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,426 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:37,426 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:37,427 - INFO - AuxoMedia/bio1:rxn01466_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,427 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:32:37,428 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:32:37,428 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,428 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:37,429 - INFO - integrating rxn: rxn46249_c0
2026-01-13 19:32:37,430 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,430 - INFO - integrating rxn: rxn01361_c0
2026-01-13 19:32:37,431 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:32:37,431 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,431 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:37,432 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:32:37,433 - INFO - integrating rxn: rxn08088_c0
2026-01-13 19:32:37,433 - INFO - AuxoMedia/bio1:rxn05669_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,433 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:32:37,434 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:37,434 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,435 - INFO - integrating rxn: rxn20472_c0
2026-01-13 19:32:37,435 - INFO - integrating rxn: rxn00533_c0
2026-01-13 19:32:37,436 - INFO - AuxoMedia/bio1:rxn00929_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,436 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:37,437 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:37,437 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,437 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:37,438 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:32:37,439 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,439 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:37,439 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:37,440 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,440 - INFO - integrating rxn: rxn14428_c0
2026-01-13 19:32:37,441 - INFO - integrating rxn: rxn00693_c0
2026-01-13 19:32:37,442 - INFO - AuxoMedia/bio1:rxn01513_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,442 - INFO - integrating rxn: rxn10121_c0
2026-01-13 19:32:37,442 - INFO - integrating rxn: rxn05651_c0
2026-01-13 19:32:37,443 - INFO - AuxoMedia/bio1:rxn05306_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,444 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:37,444 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:37,444 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00646_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn00105_c0', '>', 'new'], ['rxn01302_c0', '<', 'new'], ['rxn00559_c0', '<', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00541_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn03904_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03164_c0', '>', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn05232_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn16671_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn44043_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn14428_c0', '>', 'new'], ['rxn10121_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:37,445 - INFO - rxn05305_c0< not needed:4.345470795123579
2026-01-13 19:32:37,445 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:37,447 - INFO - integrating rxn: rxn00541_c0
2026-01-13 19:32:37,447 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,448 - INFO - integrating rxn: rxn00134_c0
2026-01-13 19:32:37,449 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,449 - INFO - integrating rxn: rxn00912_c0
2026-01-13 19:32:37,450 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,451 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:37,451 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,452 - INFO - integrating rxn: rxn01011_c0
2026-01-13 19:32:37,454 - INFO - integrating rxn: rxn01602_c0
2026-01-13 19:32:37,454 - INFO - AuxoMedia/bio1:rxn39982_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,455 - INFO - integrating rxn: rxn05223_c0
2026-01-13 19:32:37,456 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,456 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:37,458 - INFO - AuxoMedia/bio1:rxn12932_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,457 - INFO - cpd00263 not found in model!
2026-01-13 19:32:37,458 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:37,459 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:37,459 - INFO - AuxoMedia/bio1:rxn12940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,460 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:37,460 - INFO - cpd00215 not found in model!
2026-01-13 19:32:37,460 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:37,461 - INFO - AuxoMedia/bio1:rxn12939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,461 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:37,462 - INFO - AuxoMedia/bio1:rxn12929_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,463 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:37,464 - INFO - AuxoMedia/bio1:rxn12938_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,464 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:37,465 - INFO - AuxoMedia/bio1:rxn12927_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,465 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:37,466 - INFO - AuxoMedia/bio1:rxn12921_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,467 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:37,468 - INFO - integrating rxn: rxn00778_c0
2026-01-13 19:32:37,468 - INFO - AuxoMedia/bio1:rxn12928_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,469 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:37,470 - INFO - rxn12944_c0> not needed:4.345470795123587
2026-01-13 19:32:37,470 - INFO - integrating rxn: rxn05326_c0
2026-01-13 19:32:37,472 - INFO - rxn12994_c0> not needed:4.345470795123589
2026-01-13 19:32:37,472 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:32:37,473 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,473 - INFO - integrating rxn: rxn03004_c0
2026-01-13 19:32:37,475 - INFO - integrating rxn: rxn00138_c0
2026-01-13 19:32:37,475 - INFO - AuxoMedia/bio1:rxn12942_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,476 - INFO - integrating rxn: rxn00347_c0
2026-01-13 19:32:37,476 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,477 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:32:37,478 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,479 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:37,479 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,480 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:37,481 - INFO - rxn11251_c0> not needed:4.345130410962136
2026-01-13 19:32:37,481 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:37,483 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:37,483 - INFO - AuxoMedia/bio1:rxn19346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,483 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,484 - INFO - integrating rxn: rxn02914_c0
2026-01-13 19:32:37,485 - INFO - AuxoMedia/bio1:rxn19728_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,485 - INFO - AuxoMedia/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,485 - INFO - integrating rxn: rxn00686_c0
2026-01-13 19:32:37,487 - INFO - AuxoMedia/bio1:rxn20235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,487 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,487 - INFO - integrating rxn: rxn06075_c0
2026-01-13 19:32:37,488 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,488 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:37,489 - INFO - EX_cpd00119_e0< not needed:3.1180872255319367
2026-01-13 19:32:37,490 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,490 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:37,491 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,492 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:32:37,493 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,493 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:37,494 - INFO - rxn16114_c0> not needed:4.345130410962134
2026-01-13 19:32:37,495 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:37,495 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,495 - INFO - rxn15064_c0> not needed:4.3451304109621285
2026-01-13 19:32:37,496 - INFO - AuxoMedia/bio1:EX_cpd00149_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,496 - INFO - rxn15270_c0> not needed:4.3451304109621285
2026-01-13 19:32:37,496 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:37,498 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,498 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:37,498 - INFO - AuxoMedia/bio1:rxn11285_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,499 - INFO - AuxoMedia/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,499 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:37,500 - INFO - AuxoMedia/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,500 - INFO - AuxoMedia/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,501 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:37,502 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01

Adding gapfilling

2026-01-13 19:32:37,533 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01

2026-01-13 19:32:37,534 - INFO - integrating rxn: rxn27266_c0

{'reversed': {}, 'new': {'EX_cpd00039_e0': '<', 'EX_cpd00305_e0': '<', 'EX_cpd00033_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00107_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00161_e0': '<', 'EX_cpd00027_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00069_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00322_e0': '<', 'EX_cpd00156_e0': '<', 'EX_cpd00051_e0': '<', 'EX_cpd00066_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn10336_c0': '>', 'rxn01483_c0': '>', 'rxn00530_c0': '>', 'rxn00710_c0': '>', 'rxn00910_c0': '<', 'rxn08710_c0': '>', 'rxn05300_c0': '>', 'rxn08583_c0': '>', 'rxn05514_c0': '<', 'rxn09427_c0': '>', 'rxn01362_c0': '<', 'rxn03918_c0': '>', 'rxn05243_c0': '>', 'rxn10030_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '<', 'rxn10213_c0': '>', 'rxn01301_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01505_c0': '>', 'rxn00213_c0': '>', 'rxn05573_c0': '>', 'rxn05244_c0': '>', 'rxn03919_c0': '>', 'rxn01484_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn09113_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00970_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn08661_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn03150_c0': '>', 'rxn00101_c0': '>', 'rxn02303_c0': '>', 'rxn03087_c0': '<', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn08241_c0': '<', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00371_c0': '>', 'rxn00615_c0': '>', 'rxn01265_c0': '<', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn05154_c0': '>', 'rxn01332_c0': '>', 'rxn03084_c0': '>', 'rxn01790_c0': '<', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn05301_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn02276_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05669_c0': '>', 'rxn05255_c0': '>', 'rxn00929_c0': '<', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn01513_c0': '>', 'rxn05306_c0': '>', 'rxn05305_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn39982_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn29260_c0': '>', 'rxn40324_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:37,535 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,536 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:37,536 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00033_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00107_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00069_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00322_e0', '<', 'new'], ['EX_cpd00156_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['EX_cpd00066_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01483_c0', '>', 'new'], ['rxn00530_c0', '>', 'new'], ['rxn00710_c0', '>', 'new'], ['rxn00910_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn01362_c0', '<', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn05243_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn01301_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00213_c0', '>', 'new'], ['rxn05573_c0', '>', 'new'], ['rxn05244_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn09113_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00970_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn08661_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn00101_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn05154_c0', '>', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05301_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn02276_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05669_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00929_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01513_c0', '>', 'new'], ['rxn05306_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn39982_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:32:37,537 - INFO -     Added 142 reactions
2026-01-13 19:32:37,537 - INFO - AuxoMedia/bio1:rxn01675_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,537 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:37,537 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:37,538 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,539 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:37,540 - INFO - AuxoMedia/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,540 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:32:37,541 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,541 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:37,542 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05324_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn05744_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn05327_c0', '<', 'new'], ['rxn00422_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn05325_c0', '<', 'new'], ['rxn01508_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn01361_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00693_c0', '>', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00541_c0', '>', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01011_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00778_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05326_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn03004_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn00347_c0', '<', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn02914_c0', '<', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn06075_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn21859_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn13339_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn27266_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:37,543 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,544 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,546 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,547 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,548 - INFO - AuxoMedia/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,550 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,550 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn10484_c0': '>', 'rxn03436_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01454_c0': '<', 'rxn01501_c0': '<', 'rxn01505_c0': '>', 'rxn01256_c0': '>', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn08352_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn00410_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn02476_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn00834_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn01790_c0': '<', 'rxn02056_c0': '<', 'rxn00141_c0': '>', 'rxn02185_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn01513_c0': '>', 'rxn00117_c0': '>', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn15167_c0': '>', 'rxn30633_c0': '>', 'rxn11162_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:37,551 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,553 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,553 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:37,554 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,555 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:37,556 - INFO - AuxoMedia/bio1:rxn02011_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,556 - INFO - cpd00263 not found in model!
2026-01-13 19:32:37,556 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:37,557 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:37,557 - INFO - AuxoMedia/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,557 - INFO - cpd00215 not found in model!
2026-01-13 19:32:37,557 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:37,558 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:37,559 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,559 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:37,560 - INFO - AuxoMedia/bio1:rxn02402_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,560 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:37,562 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,562 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:37,563 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,564 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:37,565 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,565 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:37,567 - INFO - integrating rxn: rxn01636_c0
2026-01-13 19:32:37,568 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:37,568 - INFO - rxn05299_c0> not needed:3.1180872255319296
2026-01-13 19:32:37,570 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:37,571 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:37,573 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:37,574 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,574 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:37,575 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,576 - INFO - integrating rxn: rxn10484_c0
2026-01-13 19:32:37,577 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,577 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:32:37,579 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:37,579 - INFO - AuxoMedia/bio1:rxn01333_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,580 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:37,581 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,581 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,581 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:37,582 - INFO - AuxoMedia/bio1:rxn00105_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,583 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:37,584 - INFO - AuxoMedia/bio1:rxn01302_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,584 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,585 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:37,586 - INFO - AuxoMedia/bio1:rxn00559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,586 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,586 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:37,587 - INFO - AuxoMedia/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,587 - INFO - AuxoMedia/bio1:EX_cpd00048_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,588 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:37,589 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,589 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,589 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:37,590 - INFO - AuxoMedia/bio1:rxn05618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,591 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:37,590 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,592 - INFO - AuxoMedia/bio1:rxn08241_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,592 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:37,592 - INFO - AuxoMedia/bio1:EX_cpd00084_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,593 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:1.0097293131778145e-13 with min obj:0.01
2026-01-13 19:32:37,594 - INFO - AuxoMedia/bio1:EX_cpd00060_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,594 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:37,595 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,595 - INFO - AuxoMedia/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,596 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:37,597 - INFO - AuxoMedia/bio1:rxn01265_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,597 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,597 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:37,599 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,599 - INFO - AuxoMedia/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,599 - INFO - integrating rxn: rxn01454_c0
2026-01-13 19:32:37,600 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,601 - INFO - AuxoMedia/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,601 - INFO - integrating rxn: rxn01501_c0
2026-01-13 19:32:37,602 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,602 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,602 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:37,603 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,603 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:32:37,604 - INFO - AuxoMedia/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,605 - INFO - integrating rxn: rxn00237_c0

Adding gapfilling

2026-01-13 19:32:37,751 - INFO - integrating rxn: rxn47659_c0

 {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00646_c0': '>', 'rxn02000_c0': '>', 'rxn00800_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn05235_c0': '>', 'rxn00470_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn01256_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn01000_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn02011_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn02402_c0': '<', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn05299_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03893_c0': '>', 'rxn01333_c0': '<', 'rxn03150_c0': '>', 'rxn00105_c0': '>', 'rxn01302_c0': '<', 'rxn00559_c0': '<', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn01265_c0': '<', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00541_c0': '<', 'rxn00134_c0': '>', 'rxn02003_c0': '<', 'rxn00122_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn03904_c0': '>', 'rxn02287_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03164_c0': '>', 'rxn00623_c0': '<', 'rxn02341_c0': '>', 'rxn05232_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn28338_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn16671_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn10095_c0': '>', 'rxn44043_c0': '>', 'rxn08233_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn46249_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14428_c0': '>', 'rxn10121_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:37,752 - INFO - AuxoMedia/bio1:rxn00138_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,753 - INFO - integrating rxn: rxn43798_c0

2026-01-13 19:32:37,754 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00646_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn00105_c0', '>', 'new'], ['rxn01302_c0', '<', 'new'], ['rxn00559_c0', '<', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00541_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn03904_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03164_c0', '>', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn05232_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:32:37,754 - INFO - AuxoMedia/bio1:rxn00347_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,754 - INFO -     Added 123 reactions
2026-01-13 19:32:37,754 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:32:37,755 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:37,756 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:32:37,756 - INFO - rxn00623_c0< not needed:1.9635977470848487
2026-01-13 19:32:37,757 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:32:37,759 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:37,761 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:37,761 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,762 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:37,763 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,763 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:37,764 - INFO - AuxoMedia/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,765 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:37,766 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,766 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:32:37,767 - INFO - AuxoMedia/bio1:rxn02914_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,767 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:32:37,769 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:37,769 - INFO - AuxoMedia/bio1:rxn00686_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,770 - INFO - integrating rxn: rxn13741_c0
2026-01-13 19:32:37,771 - INFO - rxn06075_c0< not needed:1.9635977470848414
2026-01-13 19:32:37,771 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:37,773 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:37,773 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,774 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,775 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:37,776 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:37,776 - INFO - rxn21859_c0> not needed:1.9635977470848411
2026-01-13 19:32:37,777 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:37,778 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,779 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:37,779 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,780 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:37,781 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:37,782 - INFO - rxn11274_c0> not needed:1.9635977470848458
2026-01-13 19:32:37,783 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:37,784 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:32:37,786 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,786 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:32:37,788 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:32:37,789 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:32:37,790 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn10484_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01454_c0', '<', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn08352_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn00410_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn02476_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn00409_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01513_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn00154_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn11162_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn13741_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:37,791 - INFO - rxn12940_c0> not needed:1.9635977470848451
2026-01-13 19:32:37,792 - INFO - rxn12939_c0> not needed:1.9635977470848487
2026-01-13 19:32:37,793 - INFO - rxn12929_c0> not needed:1.9635977470848487
2026-01-13 19:32:37,797 - INFO - AuxoMedia/bio1:rxn25637_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,800 - INFO - AuxoMedia/bio1:rxn18935_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,801 - INFO - AuxoMedia/bio1:rxn25743_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,805 - INFO - rxn12928_c0> not needed:1.963597747084845
2026-01-13 19:32:37,809 - INFO - AuxoMedia/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,811 - INFO - rxn46124_c0> not needed:1.963597747084847
2026-01-13 19:32:37,815 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,817 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,818 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,820 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,821 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,823 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,824 - INFO - rxn15060_c0> not needed:1.7830580745409963
2026-01-13 19:32:37,826 - INFO - rxn29919_c0> not needed:1.7830580745409914
2026-01-13 19:32:37,826 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,827 - INFO - rxn15064_c0> not needed:1.7830580745409914
2026-01-13 19:32:37,828 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,828 - INFO - rxn10095_c0> not needed:1.7830580745409965
2026-01-13 19:32:37,829 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,830 - INFO - rxn13339_c0> not needed:1.7830580745409967
2026-01-13 19:32:37,831 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,831 - INFO - rxn20508_c0> not needed:1.7830580745409927
2026-01-13 19:32:37,832 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,834 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,835 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,836 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,837 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,838 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,839 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,840 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,841 - INFO - AuxoMedia/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,842 - INFO - rxn27266_c0> not needed:1.783058074540997
2026-01-13 19:32:37,842 - INFO - AuxoMedia/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,844 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,844 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,845 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,845 - INFO - rxn08921_c0> not needed:1.7830580745409956
2026-01-13 19:32:37,847 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,847 - INFO - rxn29260_c0> not needed:1.7830580745409939
2026-01-13 19:32:37,849 - INFO - rxn09390_c0> not needed:1.7830580745409914
2026-01-13 19:32:37,849 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,850 - INFO - AuxoMedia/bio1:rxn10484_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,852 - INFO - AuxoMedia/bio1:rxn03436_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,853 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,854 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,856 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,857 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,858 - INFO - rxn10042_c0> not needed:1.7830580745409896
2026-01-13 19:32:37,859 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,860 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,861 - INFO - Unneeded: [['rxn00179_c0', '>', 'new', 100, None], ['rxn00422_c0', '<', 'new', -100, None], ['rxn00134_c0', '>', 'new', 100, None], ['rxn01011_c0', '>', 'new', 100, None], ['rxn00623_c0', '<', 'new', -100, None], ['rxn06075_c0', '<', 'new', -100, None], ['rxn21859_c0', '>', 'new', 100, None], ['rxn11274_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12939_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn12928_c0', '>', 'new', 100, None], ['rxn46124_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn10095_c0', '>', 'new', 100, None], ['rxn13339_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn27266_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn09390_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None]]
2026-01-13 19:32:37,862 - INFO - AuxoMedia/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,864 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,865 - INFO - AuxoMedia/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,867 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,867 - INFO - cpd00263 not found in model!
2026-01-13 19:32:37,868 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,868 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:37,869 - INFO - cpd00215 not found in model!
2026-01-13 19:32:37,870 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,870 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:37,871 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,873 - INFO - AuxoMedia/bio1:rxn01454_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,873 - INFO - Growth: 1.9672089302832003 AuxoMedia

Adding gapfilling

2026-01-13 19:32:37,874 - INFO - AuxoMedia/bio1:rxn01501_c0< needed:0.0 with min obj:0.01

{'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00084_e0': '<', 'EX_cpd00060_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn00179_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01636_c0': '>', 'rxn05235_c0': '>', 'rxn00470_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05324_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn05229_c0': '>', 'rxn00392_c0': '>', 'rxn05219_c0': '>', 'rxn09225_c0': '>', 'rxn05744_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn01256_c0': '>', 'rxn05327_c0': '<', 'rxn00422_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn04704_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn01300_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn10954_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn05325_c0': '<', 'rxn01508_c0': '>', 'rxn00420_c0': '>', 'rxn09657_c0': '>', 'rxn03893_c0': '>', 'rxn01537_c0': '>', 'rxn01213_c0': '>', 'rxn01361_c0': '>', 'rxn03136_c0': '>', 'rxn08088_c0': '>', 'rxn00350_c0': '<', 'rxn00533_c0': '>', 'rxn00834_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn00693_c0': '>', 'rxn05651_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00541_c0': '>', 'rxn00134_c0': '>', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn01011_c0': '>', 'rxn01602_c0': '<', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn00778_c0': '>', 'rxn02832_c0': '<', 'rxn05326_c0': '<', 'rxn00256_c0': '<', 'rxn03004_c0': '>', 'rxn00138_c0': '>', 'rxn00347_c0': '<', 'rxn00623_c0': '<', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn02914_c0': '<', 'rxn00686_c0': '<', 'rxn06075_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn21859_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn02485_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn13339_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn27266_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn09390_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:37,876 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,876 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05324_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn05744_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn05327_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn05325_c0', '<', 'new'], ['rxn01508_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn01361_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00693_c0', '>', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00541_c0', '>', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00778_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05326_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn03004_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn00347_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn02914_c0', '<', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:32:37,877 - INFO -     Added 125 reactions
2026-01-13 19:32:37,877 - INFO - AuxoMedia/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,878 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:37,879 - INFO - AuxoMedia/bio1:rxn00237_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,881 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,882 - INFO - AuxoMedia/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,883 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,885 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,886 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,888 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,889 - INFO - AuxoMedia/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,891 - INFO - AuxoMedia/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,892 - INFO - AuxoMedia/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,894 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,895 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,897 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,899 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,900 - INFO - AuxoMedia/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,901 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,903 - INFO - AuxoMedia/bio1:rxn08352_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,905 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,906 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,907 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,909 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:-9.80519982353072e-13 with min obj:0.01
2026-01-13 19:32:37,915 - INFO - AuxoMedia/bio1:rxn01539_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,918 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,919 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,920 - INFO - AuxoMedia/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,922 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,924 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,925 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,927 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,928 - INFO - AuxoMedia/bio1:rxn00410_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,930 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,931 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,933 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,934 - INFO - AuxoMedia/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,936 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,937 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,939 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,941 - INFO - AuxoMedia/bio1:rxn02476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,942 - INFO - AuxoMedia/bio1:rxn01512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,944 - INFO - AuxoMedia/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,945 - INFO - AuxoMedia/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,947 - INFO - AuxoMedia/bio1:rxn08130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,948 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,950 - INFO - AuxoMedia/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,951 - INFO - AuxoMedia/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,953 - INFO - AuxoMedia/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,954 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,956 - INFO - AuxoMedia/bio1:rxn00141_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,957 - INFO - AuxoMedia/bio1:rxn02185_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,959 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,960 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,961 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,963 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,964 - INFO - AuxoMedia/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,967 - INFO - rxn00409_c0> not needed:4.211909387578111
2026-01-13 19:32:37,970 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,972 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,973 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,975 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,976 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:37,978 - INFO - AuxoMedia/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,979 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,981 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,982 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,984 - INFO - AuxoMedia/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,985 - INFO - AuxoMedia/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,986 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,988 - INFO - AuxoMedia/bio1:rxn01513_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,991 - INFO - AuxoMedia/bio1:rxn00117_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,994 - INFO - AuxoMedia/bio1:rxn01520_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,995 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:37,998 - INFO - rxn16218_c0> not needed:4.211909387578112
2026-01-13 19:32:38,001 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,005 - INFO - rxn16217_c0> not needed:4.211909387578069
2026-01-13 19:32:38,008 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,011 - INFO - AuxoMedia/bio1:rxn14424_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,016 - INFO - AuxoMedia/bio1:rxn11274_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,018 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,023 - INFO - rxn12932_c0> not needed:4.0919119691286205
2026-01-13 19:32:38,026 - INFO - rxn12940_c0> not needed:4.091911969128595
2026-01-13 19:32:38,028 - INFO - rxn12939_c0> not needed:3.9719145506790827
2026-01-13 19:32:38,029 - INFO - rxn12929_c0> not needed:3.971914550679088
2026-01-13 19:32:38,030 - INFO - rxn12938_c0> not needed:3.971914550679088
2026-01-13 19:32:38,031 - INFO - rxn12927_c0> not needed:3.971914550679088
2026-01-13 19:32:38,032 - INFO - rxn12921_c0> not needed:3.971914550679088
2026-01-13 19:32:38,034 - INFO - rxn12928_c0> not needed:3.971914550679088
2026-01-13 19:32:38,035 - INFO - rxn12944_c0> not needed:3.8519171322295636
2026-01-13 19:32:38,037 - INFO - rxn12994_c0> not needed:3.8519171322295542
2026-01-13 19:32:38,039 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,043 - INFO - rxn12942_c0> not needed:3.8519171322295356
2026-01-13 19:32:38,044 - INFO - rxn00154_c0> not needed:3.8519171322295356
2026-01-13 19:32:38,049 - INFO - AuxoMedia/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,051 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,053 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,054 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,056 - INFO - AuxoMedia/bio1:rxn15167_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,058 - INFO - AuxoMedia/bio1:rxn30633_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,061 - INFO - rxn11162_c0> not needed:3.851917132229482
2026-01-13 19:32:38,063 - INFO - AuxoMedia/bio1:rxn45899_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,065 - INFO - AuxoMedia/bio1:rxn47659_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,066 - INFO - AuxoMedia/bio1:rxn43798_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,070 - INFO - AuxoMedia/bio1:rxn25042_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,072 - INFO - AuxoMedia/bio1:rxn19766_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,073 - INFO - AuxoMedia/bio1:rxn19764_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,076 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,077 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,079 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,080 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,083 - INFO - rxn15064_c0> not needed:3.8519171322295587
2026-01-13 19:32:38,084 - INFO - rxn15270_c0> not needed:3.8519171322295525
2026-01-13 19:32:38,086 - INFO - AuxoMedia/bio1:rxn11285_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,090 - INFO - AuxoMedia/bio1:rxn10095_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,093 - INFO - rxn13741_c0> not needed:3.8519171322295453
2026-01-13 19:32:38,097 - INFO - rxn20508_c0> not needed:3.8519171322295547
2026-01-13 19:32:38,099 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,102 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,103 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,105 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,107 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,109 - INFO - rxn08921_c0> not needed:3.6119222953304995
2026-01-13 19:32:38,111 - INFO - rxn29260_c0> not needed:3.611861518120291
2026-01-13 19:32:38,114 - INFO - AuxoMedia/bio1:rxn14423_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,115 - INFO - AuxoMedia/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,117 - INFO - AuxoMedia/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,118 - INFO - AuxoMedia/bio1:rxn41263_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,120 - INFO - AuxoMedia/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:38,123 - INFO - Unneeded: [['rxn00409_c0', '>', 'new', 100, None], ['rxn16218_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn12932_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12939_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn12938_c0', '>', 'new', 100, None], ['rxn12927_c0', '>', 'new', 100, None], ['rxn12921_c0', '>', 'new', 100, None], ['rxn12928_c0', '>', 'new', 100, None], ['rxn12944_c0', '>', 'new', 100, None], ['rxn12994_c0', '>', 'new', 100, None], ['rxn12942_c0', '>', 'new', 100, None], ['rxn00154_c0', '>', 'new', 100, None], ['rxn11162_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn15270_c0', '>', 'new', 100, None], ['rxn13741_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None]]
2026-01-13 19:32:38,134 - INFO - Growth: 4.216297245016913 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn10484_c0': '>', 'rxn03436_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01454_c0': '<', 'rxn01501_c0': '<', 'rxn01505_c0': '>', 'rxn01256_c0': '>', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn08352_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn00410_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn02476_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn00834_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn01790_c0': '<', 'rxn02056_c0': '<', 'rxn00141_c0': '>', 'rxn02185_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn01513_c0': '>', 'rxn00117_c0': '>', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn15167_c0': '>', 'rxn30633_c0': '>', 'rxn11162_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:38,138 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn10484_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01454_c0', '<', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn08352_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn00410_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn02476_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01513_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:38,139 - INFO -     Added 138 reactions
2026-01-13 19:32:38,140 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:39,336 - INFO - Objective with gapfill database:137.21706849317366; min objective:0.01
2026-01-13 19:32:39,825 - INFO - Objective with gapfill database:137.21706849317334; min objective:0.01
2026-01-13 19:32:39,825 - INFO - Objective with gapfill database:137.2170684931731; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:41,112 - INFO - Objective with gapfill database:137.21706849317286; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:41,847 - INFO - Objective with gapfill database:137.21706849317366; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:42,309 - INFO - Objective with gapfill database:137.21706849317334; min objective:0.01
2026-01-13 19:32:42,367 - INFO - Objective with gapfill database:137.2170684931731; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:42,503 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn02000_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn03436_c0': '>', 'rxn08583_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn03918_c0': '>', 'rxn10030_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn01454_c0': '<', 'rxn01501_c0': '<', 'rxn00927_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn00606_c0': '<', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn00420_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03150_c0': '>', 'rxn01302_c0': '<', 'rxn01537_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00991_c0': '<', 'rxn03075_c0': '>', 'rxn02003_c0': '<', 'rxn02185_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:42,507 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:42,509 - INFO - integrating rxn: EX_cpd00393_e0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:42,510 - INFO - integrating rxn: EX_cpd00119_e0

2026-01-13 19:32:42,512 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:42,514 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:42,515 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:42,517 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:42,519 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:32:42,520 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:42,522 - INFO - integrating rxn: rxn02000_c0
2026-01-13 19:32:42,524 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:42,525 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:42,527 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:42,528 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:42,530 - INFO - integrating rxn: rxn01636_c0
2026-01-13 19:32:42,531 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:42,533 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:42,534 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:32:42,536 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:42,537 - INFO - integrating rxn: rxn09202_c0
2026-01-13 19:32:42,539 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:42,540 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:42,542 - INFO - integrating rxn: rxn01997_c0
2026-01-13 19:32:42,543 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:42,545 - INFO - integrating rxn: rxn10030_c0
2026-01-13 19:32:42,547 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:42,548 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:42,549 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:42,551 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:42,552 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:42,554 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:42,555 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:42,557 - INFO - integrating rxn: rxn01675_c0
2026-01-13 19:32:42,558 - INFO - integrating rxn: rxn01454_c0
2026-01-13 19:32:42,560 - INFO - integrating rxn: rxn01501_c0
2026-01-13 19:32:42,561 - INFO - integrating rxn: rxn00927_c0
2026-01-13 19:32:42,562 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:42,564 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:42,565 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:42,567 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:42,568 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:42,569 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:42,571 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:42,572 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:42,574 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:42,575 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:42,576 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:42,578 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:42,579 - INFO - integrating rxn: rxn05463_c0
2026-01-13 19:32:42,581 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:42,582 - INFO - integrating rxn: rxn00606_c0
2026-01-13 19:32:42,583 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:32:42,585 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:42,586 - INFO - integrating rxn: rxn10094_c0
2026-01-13 19:32:42,588 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:42,590 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:42,591 - INFO - integrating rxn: rxn00420_c0
2026-01-13 19:32:42,593 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:42,594 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:42,595 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:42,597 - INFO - integrating rxn: rxn01302_c0
2026-01-13 19:32:42,598 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:32:42,599 - INFO - integrating rxn: rxn03087_c0
2026-01-13 19:32:42,601 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:42,602 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:42,603 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:42,604 - INFO - integrating rxn: rxn00704_c0
2026-01-13 19:32:42,606 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:42,607 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:42,609 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:42,610 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:42,612 - INFO - integrating rxn: rxn00991_c0
2026-01-13 19:32:42,613 - INFO - integrating rxn: rxn03075_c0
2026-01-13 19:32:42,614 - INFO - integrating rxn: rxn02003_c0
2026-01-13 19:32:42,616 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:32:42,617 - INFO - integrating rxn: rxn00912_c0
2026-01-13 19:32:42,618 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:42,620 - INFO - integrating rxn: rxn05223_c0
2026-01-13 19:32:42,622 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:42,623 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:42,624 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:42,626 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:42,628 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:42,629 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:42,630 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:42,631 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:42,633 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:42,634 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:42,636 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:42,637 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:42,639 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:42,640 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:42,642 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:42,643 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:42,644 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:32:42,646 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:42,647 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:42,649 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:32:42,650 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:32:42,652 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:32:42,653 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:42,655 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:32:42,656 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:32:42,657 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:42,659 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:42,660 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:42,662 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:32:42,663 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:42,665 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:32:42,666 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:32:42,667 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:32:42,669 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:42,670 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:42,672 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:32:42,673 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:42,674 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:32:42,676 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:42,677 - INFO - integrating rxn: rxn13741_c0
2026-01-13 19:32:42,679 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:42,680 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:42,681 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:42,683 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:42,684 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:32:42,686 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:42,687 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:42,688 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:42,690 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:42,691 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:32:42,693 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:32:42,695 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:32:42,696 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:32:42,697 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn01454_c0', '<', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn00927_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn00606_c0', '<', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01302_c0', '<', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00991_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn13741_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:42,737 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,741 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,744 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,748 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,750 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,752 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,753 - INFO - AuxoMedia/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,754 - INFO - AuxoMedia/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,756 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,758 - INFO - AuxoMedia/bio1:rxn02000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,759 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,761 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,762 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,764 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,766 - INFO - AuxoMedia/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,767 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,769 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,770 - INFO - AuxoMedia/bio1:rxn03436_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,772 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,774 - INFO - AuxoMedia/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,775 - INFO - AuxoMedia/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,777 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,778 - INFO - AuxoMedia/bio1:rxn01997_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,780 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,781 - INFO - AuxoMedia/bio1:rxn10030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,783 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,785 - INFO - AuxoMedia/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,786 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,788 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,789 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,791 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,792 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,794 - INFO - AuxoMedia/bio1:rxn01675_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,796 - INFO - rxn01454_c0< not needed:0.9852724437518576
2026-01-13 19:32:42,800 - INFO - AuxoMedia/bio1:rxn01501_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,807 - INFO - rxn00927_c0> not needed:0.9852724437518551
2026-01-13 19:32:42,812 - INFO - AuxoMedia/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,813 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,815 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,817 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,818 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,820 - INFO - AuxoMedia/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,821 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,823 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,825 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,826 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,828 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,829 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,832 - INFO - rxn05463_c0> not needed:0.9852724437518583
2026-01-13 19:32:42,836 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,841 - INFO - rxn00606_c0< not needed:0.985272443751856
2026-01-13 19:32:42,844 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,845 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,847 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,849 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,851 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,853 - INFO - AuxoMedia/bio1:rxn00420_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,856 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,858 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,860 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,863 - INFO - rxn01302_c0< not needed:0.8698442256803004
2026-01-13 19:32:42,865 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,867 - INFO - AuxoMedia/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,868 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,870 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,872 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,874 - INFO - AuxoMedia/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,875 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,877 - INFO - AuxoMedia/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,879 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,880 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,882 - INFO - AuxoMedia/bio1:rxn00991_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,883 - INFO - AuxoMedia/bio1:rxn03075_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,885 - INFO - AuxoMedia/bio1:rxn02003_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:42,886 - INFO - AuxoMedia/bio1:rxn02185_c0< needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:42,952 - INFO - integrating rxn: rxn08618_c0

2026-01-13 19:32:42,953 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:32:42,954 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,955 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:42,956 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:42,956 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,958 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:42,959 - INFO - rxn16114_c0> not needed:0.8698442256803005
2026-01-13 19:32:42,959 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:42,960 - INFO - rxn15064_c0> not needed:0.8698442256803005
2026-01-13 19:32:42,961 - INFO - integrating rxn: rxn08528_c0
2026-01-13 19:32:42,961 - INFO - rxn15270_c0> not needed:0.8698442256803005
2026-01-13 19:32:42,962 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:42,963 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:42,965 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:42,965 - INFO - rxn10095_c0> not needed:0.8698442256803004
2026-01-13 19:32:42,966 - INFO - integrating rxn: rxn02402_c0
2026-01-13 19:32:42,967 - INFO - rxn13741_c0> not needed:0.8698442256803004
2026-01-13 19:32:42,967 - INFO - integrating rxn: rxn06023_c0
2026-01-13 19:32:42,969 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:42,970 - INFO - AuxoMedia/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,970 - INFO - integrating rxn: rxn02760_c0
2026-01-13 19:32:42,972 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:42,973 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:42,975 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:42,976 - INFO - integrating rxn: rxn00105_c0
2026-01-13 19:32:42,976 - INFO - rxn20508_c0> not needed:0.8698442256803015
2026-01-13 19:32:42,978 - INFO - integrating rxn: rxn05315_c0
2026-01-13 19:32:42,978 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,979 - INFO - integrating rxn: rxn03538_c0
2026-01-13 19:32:42,980 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:42,981 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,982 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:42,983 - INFO - integrating rxn: rxn00502_c0
2026-01-13 19:32:42,983 - INFO - AuxoMedia/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,985 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:42,985 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,986 - INFO - integrating rxn: rxn01512_c0
2026-01-13 19:32:42,987 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:42,987 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:42,989 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:32:42,990 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:42,991 - INFO - Objective with gapfill database:137.21706849317303; min objective:0.01
2026-01-13 19:32:42,992 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:42,994 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:42,995 - INFO - rxn08921_c0> not needed:0.8698442256803005
2026-01-13 19:32:42,995 - INFO - integrating rxn: rxn02897_c0
2026-01-13 19:32:42,997 - INFO - rxn29260_c0> not needed:0.8698442256803006
2026-01-13 19:32:42,997 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:42,998 - INFO - integrating rxn: rxn00134_c0
2026-01-13 19:32:43,000 - INFO - integrating rxn: rxn05223_c0
2026-01-13 19:32:43,001 - INFO - AuxoMedia/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,001 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:43,002 - INFO - AuxoMedia/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,003 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:43,004 - INFO - AuxoMedia/bio1:rxn41263_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,004 - INFO - integrating rxn: rxn00338_c0
2026-01-13 19:32:43,005 - INFO - AuxoMedia/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,006 - INFO - integrating rxn: rxn00119_c0
2026-01-13 19:32:43,007 - INFO - integrating rxn: rxn00409_c0
2026-01-13 19:32:43,009 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:43,009 - INFO - Unneeded: [['rxn01454_c0', '<', 'new', -100, None], ['rxn00927_c0', '>', 'new', 100, None], ['rxn05463_c0', '>', 'new', 100, None], ['rxn00606_c0', '<', 'new', -100, None], ['rxn01302_c0', '<', 'new', -100, None], ['rxn12932_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn12938_c0', '>', 'new', 100, None], ['rxn12927_c0', '>', 'new', 100, None], ['rxn12921_c0', '>', 'new', 100, None], ['rxn12942_c0', '>', 'new', 100, None], ['rxn02485_c0', '>', 'new', 100, None], ['rxn11251_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn45899_c0', '>', 'new', 100, None], ['rxn47659_c0', '>', 'new', 100, None], ['rxn43798_c0', '>', 'new', 100, None], ['rxn16114_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn15270_c0', '>', 'new', 100, None], ['rxn10095_c0', '>', 'new', 100, None], ['rxn13741_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None]]
2026-01-13 19:32:43,010 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:43,011 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:43,013 - INFO - integrating rxn: rxn01538_c0
2026-01-13 19:32:43,014 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:43,015 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:43,017 - INFO - integrating rxn: rxn00239_c0
2026-01-13 19:32:43,018 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:43,018 - INFO - Growth: 1.0488029400798549 AuxoMedia

Adding gapfilling

2026-01-13 19:32:43,019 - INFO - integrating rxn: rxn02341_c0

 {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn02000_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn03436_c0': '>', 'rxn08583_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn03918_c0': '>', 'rxn10030_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn01454_c0': '<', 'rxn01501_c0': '<', 'rxn00927_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn00606_c0': '<', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn00420_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03150_c0': '>', 'rxn01302_c0': '<', 'rxn01537_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00991_c0': '<', 'rxn03075_c0': '>', 'rxn02003_c0': '<', 'rxn02185_c0': '<', 'rxn00912_c0': '>', 'rxn00122_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:43,021 - INFO - integrating rxn: rxn03511_c0

2026-01-13 19:32:43,022 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00991_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:43,023 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:43,023 - INFO -     Added 105 reactions
2026-01-13 19:32:43,024 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:43,024 - INFO - integrating rxn: rxn01019_c0
2026-01-13 19:32:43,026 - INFO - integrating rxn: rxn00117_c0
2026-01-13 19:32:43,027 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:43,028 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:43,030 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:43,032 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:43,033 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:43,034 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:43,036 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:43,038 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:43,039 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:43,041 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:43,042 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:43,044 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:43,045 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:43,047 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:32:43,048 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:43,050 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:43,051 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:43,052 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:43,054 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:43,056 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:43,057 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:32:43,059 - INFO - integrating rxn: rxn28338_c0
2026-01-13 19:32:43,060 - INFO - integrating rxn: rxn01736_c0
2026-01-13 19:32:43,062 - INFO - integrating rxn: rxn00644_c0
2026-01-13 19:32:43,063 - INFO - integrating rxn: rxn15091_c0
2026-01-13 19:32:43,065 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:32:43,066 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:32:43,068 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:43,069 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:43,071 - INFO - integrating rxn: rxn17394_c0
2026-01-13 19:32:43,072 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:32:43,073 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:43,075 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:43,076 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:43,078 - INFO - integrating rxn: rxn18575_c0
2026-01-13 19:32:43,079 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:43,080 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:43,082 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:43,083 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:43,085 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:43,086 - INFO - integrating rxn: rxn46249_c0
2026-01-13 19:32:43,088 - INFO - integrating rxn: rxn20472_c0
2026-01-13 19:32:43,089 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:43,090 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:43,092 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:43,093 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:32:43,094 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:43,096 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:43,097 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00034_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn01673_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn00416_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn01637_c0', '<', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn02760_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn00105_c0', '>', 'new'], ['rxn05315_c0', '<', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00502_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn00338_c0', '>', 'new'], ['rxn00119_c0', '>', 'new'], ['rxn00409_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00239_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01019_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn15091_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn18575_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:43,112 - INFO - cpd00263 not found in model!
2026-01-13 19:32:43,113 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:43,113 - INFO - cpd00215 not found in model!
2026-01-13 19:32:43,114 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:43,137 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,139 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,140 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,142 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,143 - INFO - AuxoMedia/bio1:EX_cpd00034_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,145 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,146 - INFO - AuxoMedia/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,148 - INFO - AuxoMedia/bio1:EX_cpd10515_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,149 - INFO - AuxoMedia/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,151 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,152 - INFO - AuxoMedia/bio1:rxn01673_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,154 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,156 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,157 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,159 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,161 - INFO - AuxoMedia/bio1:rxn02988_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,162 - INFO - AuxoMedia/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,164 - INFO - AuxoMedia/bio1:rxn00416_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,166 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,167 - INFO - AuxoMedia/bio1:rxn01739_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,169 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,171 - INFO - AuxoMedia/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,172 - INFO - AuxoMedia/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,174 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,175 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,177 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,178 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,180 - INFO - AuxoMedia/bio1:rxn01637_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,182 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,183 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,185 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,186 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,188 - INFO - AuxoMedia/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,190 - INFO - AuxoMedia/bio1:rxn00503_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,191 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'rxn08709_c0': '>', 'rxn00423_c0': '>', 'rxn05457_c0': '<', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn05235_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn12933_c0': '<', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn00097_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn00774_c0': '>', 'rxn03918_c0': '>', 'rxn00340_c0': '>', 'rxn10030_c0': '>', 'rxn05957_c0': '>', 'rxn08708_c0': '>', 'rxn02404_c0': '>', 'rxn05345_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn05744_c0': '>', 'rxn02175_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01501_c0': '<', 'rxn00237_c0': '>', 'rxn08311_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn03843_c0': '>', 'rxn08711_c0': '>', 'rxn05465_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03244_c0': '<', 'rxn04139_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn00410_c0': '>', 'rxn05342_c0': '<', 'rxn03150_c0': '>', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn02937_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn03249_c0': '<', 'rxn00834_c0': '>', 'rxn11702_c0': '>', 'rxn03439_c0': '>', 'rxn00558_c0': '<', 'rxn00077_c0': '>', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00991_c0': '<', 'rxn03242_c0': '<', 'rxn00134_c0': '>', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00122_c0': '>', 'rxn00114_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn00119_c0': '>', 'rxn01466_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03004_c0': '>', 'rxn06729_c0': '>', 'rxn03031_c0': '>', 'rxn00239_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn05232_c0': '>', 'rxn08619_c0': '>', 'rxn03246_c0': '<', 'rxn06075_c0': '<', 'rxn09149_c0': '<', 'rxn00117_c0': '>', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn25474_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn16341_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>', 'rxn11382_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:43,191 - INFO - AuxoMedia/bio1:rxn00237_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,193 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,195 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:43,195 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,196 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:43,197 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,198 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:43,199 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,200 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:43,201 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,201 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:43,202 - INFO - AuxoMedia/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,202 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:43,204 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,204 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:43,205 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,206 - INFO - integrating rxn: rxn00423_c0
2026-01-13 19:32:43,207 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,207 - INFO - integrating rxn: rxn05457_c0
2026-01-13 19:32:43,208 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,209 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:43,211 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:43,211 - INFO - AuxoMedia/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,212 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:43,212 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,213 - INFO - integrating rxn: rxn05235_c0
2026-01-13 19:32:43,214 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,215 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:43,216 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,217 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:43,217 - INFO - AuxoMedia/bio1:rxn02402_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,218 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:43,219 - INFO - AuxoMedia/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,220 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:43,220 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,221 - INFO - integrating rxn: rxn12933_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:43,371 - INFO - integrating rxn: rxn01520_c0
2026-01-13 19:32:43,372 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01

2026-01-13 19:32:43,373 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:43,374 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,374 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:43,375 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,376 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:43,377 - INFO - AuxoMedia/bio1:rxn46249_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,378 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:43,379 - INFO - AuxoMedia/bio1:rxn20472_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,379 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:43,380 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,381 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:43,382 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:43,384 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:32:43,385 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:32:43,385 - INFO - rxn08921_c0> not needed:1.3771672469342653
2026-01-13 19:32:43,387 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:43,387 - INFO - rxn29260_c0> not needed:1.3771672469342637
2026-01-13 19:32:43,388 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:43,389 - INFO - AuxoMedia/bio1:rxn08473_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,389 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:43,391 - INFO - rxn14423_c0> not needed:1.3771672469342637
2026-01-13 19:32:43,391 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:43,393 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:43,394 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:43,395 - INFO - rxn10042_c0> not needed:1.3771672469342646
2026-01-13 19:32:43,395 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:43,397 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:43,398 - INFO - Unneeded: [['rxn16218_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn14424_c0', '>', 'new', 100, None], ['rxn11274_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn25637_c0', '>', 'new', 100, None], ['rxn18935_c0', '>', 'new', 100, None], ['rxn25743_c0', '>', 'new', 100, None], ['rxn12944_c0', '>', 'new', 100, None], ['rxn12994_c0', '>', 'new', 100, None], ['rxn15091_c0', '>', 'new', 100, None], ['rxn19728_c0', '>', 'new', 100, None], ['rxn20235_c0', '>', 'new', 100, None], ['rxn16114_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn14423_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None]]
2026-01-13 19:32:43,398 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:43,400 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:32:43,401 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:32:43,403 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:43,404 - INFO - cpd00263 not found in model!
2026-01-13 19:32:43,404 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:43,404 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:43,405 - INFO - cpd00215 not found in model!
2026-01-13 19:32:43,406 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:43,406 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:43,407 - INFO - integrating rxn: rxn41399_c0
2026-01-13 19:32:43,409 - INFO - integrating rxn: rxn41401_c0
2026-01-13 19:32:43,410 - INFO - Growth: 3.8694145854971773 AuxoMedia
2026-01-13 19:32:43,411 - INFO - integrating rxn: rxn15776_c0

Adding gapfilling

2026-01-13 19:32:43,412 - INFO - integrating rxn: rxn11382_c0

{'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00034_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd10515_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn01673_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn02988_c0': '<', 'rxn00470_c0': '>', 'rxn00416_c0': '>', 'rxn12512_c0': '>', 'rxn01739_c0': '>', 'rxn08583_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn01637_c0': '<', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01256_c0': '>', 'rxn00503_c0': '<', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn01000_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn02760_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03150_c0': '>', 'rxn00105_c0': '>', 'rxn05315_c0': '<', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00502_c0': '<', 'rxn03137_c0': '>', 'rxn01512_c0': '>', 'rxn00834_c0': '>', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn00338_c0': '>', 'rxn00119_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00239_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn01019_c0': '>', 'rxn00117_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn15166_c0': '>', 'rxn28338_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn15091_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn18575_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn46249_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:43,413 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:43,414 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00034_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn01673_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn00416_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn01637_c0', '<', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn02760_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn00105_c0', '>', 'new'], ['rxn05315_c0', '<', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00502_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn00338_c0', '>', 'new'], ['rxn00119_c0', '>', 'new'], ['rxn00409_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00239_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01019_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn18575_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08473_c0', '>', 'new']]
2026-01-13 19:32:43,415 - INFO -     Added 117 reactions
2026-01-13 19:32:43,415 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:32:43,415 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:43,417 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:32:43,418 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:32:43,419 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:32:43,420 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00423_c0', '>', 'new'], ['rxn05457_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn12933_c0', '<', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn00097_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn00774_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00340_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn05957_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn05345_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn05744_c0', '>', 'new'], ['rxn02175_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn08311_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn03843_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn05465_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03244_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00410_c0', '>', 'new'], ['rxn05342_c0', '<', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02937_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn03249_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00558_c0', '<', 'new'], ['rxn00077_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00991_c0', '<', 'new'], ['rxn03242_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn00114_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn00119_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn00409_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03004_c0', '>', 'new'], ['rxn06729_c0', '>', 'new'], ['rxn03031_c0', '>', 'new'], ['rxn00239_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn05232_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn03246_c0', '<', 'new'], ['rxn06075_c0', '<', 'new'], ['rxn09149_c0', '<', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn41399_c0', '>', 'new'], ['rxn41401_c0', '>', 'new'], ['rxn15776_c0', '>', 'new'], ['rxn11382_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:43,436 - INFO - cpd00263 not found in model!
2026-01-13 19:32:43,436 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:43,438 - INFO - cpd00215 not found in model!
2026-01-13 19:32:43,439 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:43,461 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,462 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,464 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,465 - INFO - AuxoMedia/bio1:EX_cpd00065_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,467 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,468 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,469 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,471 - INFO - AuxoMedia/bio1:rxn00423_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,473 - INFO - AuxoMedia/bio1:rxn05457_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,474 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,476 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,477 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,479 - INFO - AuxoMedia/bio1:rxn05235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,480 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,481 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,483 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,484 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,486 - INFO - AuxoMedia/bio1:rxn12933_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,487 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,489 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,491 - INFO - AuxoMedia/bio1:rxn00097_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,493 - INFO - AuxoMedia/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,495 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,496 - INFO - AuxoMedia/bio1:rxn00774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,498 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,499 - INFO - AuxoMedia/bio1:rxn00340_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,501 - INFO - AuxoMedia/bio1:rxn10030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,502 - INFO - AuxoMedia/bio1:rxn05957_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,504 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,505 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,507 - INFO - AuxoMedia/bio1:rxn05345_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,508 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,510 - INFO - AuxoMedia/bio1:rxn00830_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,511 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,513 - INFO - AuxoMedia/bio1:rxn00029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,515 - INFO - AuxoMedia/bio1:rxn05744_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,516 - INFO - AuxoMedia/bio1:rxn02175_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,518 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,519 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,521 - INFO - AuxoMedia/bio1:rxn01501_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,522 - INFO - AuxoMedia/bio1:rxn00237_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,524 - INFO - AuxoMedia/bio1:rxn08311_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,525 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,527 - INFO - AuxoMedia/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,528 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,530 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,531 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,532 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,534 - INFO - AuxoMedia/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,536 - INFO - AuxoMedia/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,537 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,539 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,541 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,542 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,544 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,545 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,547 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,548 - INFO - AuxoMedia/bio1:rxn03843_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,550 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,552 - INFO - AuxoMedia/bio1:rxn05465_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,553 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,555 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,556 - INFO - AuxoMedia/bio1:rxn03244_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,558 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,559 - INFO - AuxoMedia/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,561 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,562 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,564 - INFO - AuxoMedia/bio1:rxn00410_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,565 - INFO - AuxoMedia/bio1:rxn05342_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,566 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,568 - INFO - AuxoMedia/bio1:rxn05663_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,569 - INFO - AuxoMedia/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,571 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,572 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,574 - INFO - AuxoMedia/bio1:rxn02937_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,575 - INFO - AuxoMedia/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,577 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,578 - INFO - AuxoMedia/bio1:rxn01512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,580 - INFO - AuxoMedia/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,581 - INFO - AuxoMedia/bio1:rxn03249_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,582 - INFO - AuxoMedia/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,584 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,585 - INFO - AuxoMedia/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,587 - INFO - AuxoMedia/bio1:rxn00558_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,588 - INFO - AuxoMedia/bio1:rxn00077_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,590 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,591 - INFO - AuxoMedia/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,593 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,594 - INFO - AuxoMedia/bio1:rxn00991_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,596 - INFO - AuxoMedia/bio1:rxn03242_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,597 - INFO - AuxoMedia/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,599 - INFO - AuxoMedia/bio1:rxn02003_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,600 - INFO - AuxoMedia/bio1:rxn00130_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,602 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,603 - INFO - AuxoMedia/bio1:rxn00114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,605 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,606 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,607 - INFO - AuxoMedia/bio1:rxn00119_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,609 - INFO - AuxoMedia/bio1:rxn01466_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,611 - INFO - AuxoMedia/bio1:rxn00409_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,612 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,614 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,615 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,618 - INFO - AuxoMedia/bio1:rxn01538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,620 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,622 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,625 - INFO - AuxoMedia/bio1:rxn03004_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,627 - INFO - AuxoMedia/bio1:rxn06729_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,629 - INFO - AuxoMedia/bio1:rxn03031_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,631 - INFO - AuxoMedia/bio1:rxn00239_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,633 - INFO - AuxoMedia/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,635 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,637 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,638 - INFO - AuxoMedia/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,640 - INFO - AuxoMedia/bio1:rxn05232_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,641 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,643 - INFO - AuxoMedia/bio1:rxn03246_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:43,644 - INFO - AuxoMedia/bio1:rxn06075_c0< needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:43,646 - INFO - AuxoMedia/bio1:rxn09149_c0< needed:0.0 with min obj:0.01

2026-01-13 19:32:43,648 - INFO - AuxoMedia/bio1:rxn00117_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,649 - INFO - AuxoMedia/bio1:rxn01520_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,651 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,652 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,654 - INFO - AuxoMedia/bio1:rxn16218_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,656 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,657 - INFO - AuxoMedia/bio1:rxn16217_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,658 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,660 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,664 - INFO - AuxoMedia/bio1:rxn19728_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,666 - INFO - AuxoMedia/bio1:rxn20235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,667 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,669 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,670 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,675 - INFO - rxn15060_c0> not needed:3.969256722780275
2026-01-13 19:32:43,676 - INFO - rxn29919_c0> not needed:3.969256722780276
2026-01-13 19:32:43,678 - INFO - rxn15064_c0> not needed:3.969256722780276
2026-01-13 19:32:43,679 - INFO - rxn20508_c0> not needed:3.969256722780276
2026-01-13 19:32:43,681 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,689 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,691 - INFO - AuxoMedia/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,696 - INFO - rxn16341_c0> not needed:3.969256722780252
2026-01-13 19:32:43,698 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,700 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,702 - INFO - rxn08921_c0> not needed:3.969256722780253
2026-01-13 19:32:43,703 - INFO - rxn41399_c0> not needed:3.969256722780343
2026-01-13 19:32:43,705 - INFO - rxn41401_c0> not needed:3.969256722780343
2026-01-13 19:32:43,706 - INFO - rxn15776_c0> not needed:3.969256722780343
2026-01-13 19:32:43,707 - INFO - rxn11382_c0> not needed:3.969256722780343
2026-01-13 19:32:43,708 - INFO - rxn10042_c0> not needed:3.969256722780343
2026-01-13 19:32:43,710 - INFO - AuxoMedia/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,712 - INFO - AuxoMedia/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,713 - INFO - AuxoMedia/bio1:rxn41263_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,715 - INFO - AuxoMedia/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:43,717 - INFO - Unneeded: [['rxn15060_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn16341_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn41399_c0', '>', 'new', 100, None], ['rxn41401_c0', '>', 'new', 100, None], ['rxn15776_c0', '>', 'new', 100, None], ['rxn11382_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None]]
2026-01-13 19:32:43,724 - INFO - cpd00263 not found in model!
2026-01-13 19:32:43,724 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:43,725 - INFO - cpd00215 not found in model!
2026-01-13 19:32:43,726 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:43,729 - INFO - Growth: 3.969256722780261 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00065_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'rxn08709_c0': '>', 'rxn00423_c0': '>', 'rxn05457_c0': '<', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn05235_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn12933_c0': '<', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn00097_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn00774_c0': '>', 'rxn03918_c0': '>', 'rxn00340_c0': '>', 'rxn10030_c0': '>', 'rxn05957_c0': '>', 'rxn08708_c0': '>', 'rxn02404_c0': '>', 'rxn05345_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn05744_c0': '>', 'rxn02175_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01501_c0': '<', 'rxn00237_c0': '>', 'rxn08311_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn03843_c0': '>', 'rxn08711_c0': '>', 'rxn05465_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03244_c0': '<', 'rxn04139_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn00410_c0': '>', 'rxn05342_c0': '<', 'rxn03150_c0': '>', 'rxn05663_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn02937_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn03249_c0': '<', 'rxn00834_c0': '>', 'rxn11702_c0': '>', 'rxn03439_c0': '>', 'rxn00558_c0': '<', 'rxn00077_c0': '>', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00991_c0': '<', 'rxn03242_c0': '<', 'rxn00134_c0': '>', 'rxn02003_c0': '<', 'rxn00130_c0': '<', 'rxn00122_c0': '>', 'rxn00114_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn00119_c0': '>', 'rxn01466_c0': '>', 'rxn00409_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03004_c0': '>', 'rxn06729_c0': '>', 'rxn03031_c0': '>', 'rxn00239_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn05232_c0': '>', 'rxn08619_c0': '>', 'rxn03246_c0': '<', 'rxn06075_c0': '<', 'rxn09149_c0': '<', 'rxn00117_c0': '>', 'rxn01520_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn25474_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn16341_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>', 'rxn11382_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:43,733 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00423_c0', '>', 'new'], ['rxn05457_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn12933_c0', '<', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn00097_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn00774_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00340_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn05957_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn05345_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn05744_c0', '>', 'new'], ['rxn02175_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn08311_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn03843_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn05465_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03244_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00410_c0', '>', 'new'], ['rxn05342_c0', '<', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02937_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn03249_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00558_c0', '<', 'new'], ['rxn00077_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00991_c0', '<', 'new'], ['rxn03242_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn00114_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn00119_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn00409_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03004_c0', '>', 'new'], ['rxn06729_c0', '>', 'new'], ['rxn03031_c0', '>', 'new'], ['rxn00239_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn05232_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn03246_c0', '<', 'new'], ['rxn06075_c0', '<', 'new'], ['rxn09149_c0', '<', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:43,733 - INFO -     Added 142 reactions
2026-01-13 19:32:43,734 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:43,899 - INFO - Objective with gapfill database:137.21706849317286; min objective:0.01
2026-01-13 19:32:44,110 - INFO - Objective with gapfill database:137.21706849317312; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:44,541 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01636_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01256_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn01972_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn01967_c0': '<', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn05029_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn03907_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn05117_c0': '>', 'rxn03439_c0': '>', 'rxn03638_c0': '>', 'rxn01541_c0': '<', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15167_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:44,544 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:44,546 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:44,547 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:44,549 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:44,550 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:44,552 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:44,553 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:32:44,555 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:44,556 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:44,558 - INFO - integrating rxn: rxn03030_c0
2026-01-13 19:32:44,559 - INFO - integrating rxn: rxn01636_c0
2026-01-13 19:32:44,560 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:44,562 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:44,564 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:44,566 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:44,567 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:44,569 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:44,570 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:44,572 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:44,573 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:44,575 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:44,577 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:44,578 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:44,580 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:44,581 - INFO - integrating rxn: rxn06937_c0
2026-01-13 19:32:44,583 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:44,584 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:44,586 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:44,587 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:32:44,589 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:44,590 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:44,592 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:44,593 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:44,594 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:44,596 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:44,597 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:32:44,599 - INFO - integrating rxn: rxn01972_c0
2026-01-13 19:32:44,600 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:44,601 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:44,603 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:44,604 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:44,606 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:44,607 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:44,608 - INFO - integrating rxn: rxn01967_c0
2026-01-13 19:32:44,609 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:44,611 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:32:44,612 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:44,613 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:44,615 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:32:44,616 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:44,618 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:44,619 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:44,620 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:44,622 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:44,623 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:44,624 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:44,626 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:44,627 - INFO - integrating rxn: rxn05029_c0
2026-01-13 19:32:44,628 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:32:44,630 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:44,631 - INFO - integrating rxn: rxn03907_c0
2026-01-13 19:32:44,633 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:44,634 - INFO - integrating rxn: rxn02304_c0
2026-01-13 19:32:44,635 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:44,637 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:44,638 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:44,639 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:44,641 - INFO - integrating rxn: rxn04113_c0
2026-01-13 19:32:44,642 - INFO - integrating rxn: rxn05117_c0
2026-01-13 19:32:44,644 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:44,645 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:44,647 - INFO - integrating rxn: rxn01541_c0
2026-01-13 19:32:44,648 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:44,649 - INFO - integrating rxn: rxn00134_c0
2026-01-13 19:32:44,651 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:44,652 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:44,654 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:44,655 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:44,656 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:44,658 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:44,659 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:44,660 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:44,661 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:44,663 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:44,664 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:44,665 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:44,667 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:44,668 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:44,669 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:44,671 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:44,672 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:44,673 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:44,675 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:44,677 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:44,678 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:44,679 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:44,681 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:44,682 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:44,683 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:32:44,685 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:44,686 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:32:44,687 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:44,688 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:32:44,690 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:44,691 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:44,693 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:32:44,694 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:32:44,695 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:32:44,697 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:32:44,698 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:32:44,700 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:32:44,701 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:44,703 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:44,704 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:44,705 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:44,707 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:44,708 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:44,709 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:32:44,710 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:44,712 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:44,713 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:44,714 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:44,716 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:44,717 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:44,718 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:44,720 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:44,721 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:44,722 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn01967_c0', '<', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn01541_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:44,739 - INFO - cpd00263 not found in model!
2026-01-13 19:32:44,740 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:44,740 - INFO - cpd00215 not found in model!
2026-01-13 19:32:44,741 - INFO - Media compound: cpd00215 not found in model.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:44,764 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,766 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,767 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,768 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,770 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,771 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,773 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,775 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,776 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,778 - INFO - AuxoMedia/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,779 - INFO - AuxoMedia/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,780 - INFO - AuxoMedia/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,782 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,783 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,785 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,786 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,788 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,789 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,791 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,792 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,793 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,795 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,796 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,798 - INFO - AuxoMedia/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,799 - INFO - AuxoMedia/bio1:rxn06937_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,801 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,802 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,803 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,805 - INFO - AuxoMedia/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,806 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,808 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,809 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,811 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,812 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,813 - INFO - AuxoMedia/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,815 - INFO - AuxoMedia/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,816 - INFO - AuxoMedia/bio1:rxn01972_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,817 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,819 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,820 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,822 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,823 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,825 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,826 - INFO - AuxoMedia/bio1:rxn01967_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,828 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,829 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,830 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,832 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,835 - INFO - AuxoMedia/bio1:rxn01539_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,838 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,839 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,840 - INFO - AuxoMedia/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,842 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,844 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,845 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,846 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,848 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,849 - INFO - AuxoMedia/bio1:rxn05029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,851 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:2.1176627283809436e-13 with min obj:0.01
2026-01-13 19:32:44,853 - INFO - AuxoMedia/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,854 - INFO - AuxoMedia/bio1:rxn03907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,856 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,857 - INFO - AuxoMedia/bio1:rxn02304_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,859 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:-2.1544466290797503e-13 with min obj:0.01
2026-01-13 19:32:44,860 - INFO - AuxoMedia/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,862 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,863 - INFO - AuxoMedia/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,864 - INFO - AuxoMedia/bio1:rxn04113_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,866 - INFO - AuxoMedia/bio1:rxn05117_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,867 - INFO - AuxoMedia/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,869 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,870 - INFO - AuxoMedia/bio1:rxn01541_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,873 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:44,874 - INFO - AuxoMedia/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,875 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,877 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,878 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,880 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,881 - INFO - AuxoMedia/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,882 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,884 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,885 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,887 - INFO - AuxoMedia/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,888 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,890 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,891 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,893 - INFO - AuxoMedia/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,894 - INFO - AuxoMedia/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,895 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,897 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,900 - INFO - rxn16218_c0> not needed:3.5865109548160476
2026-01-13 19:32:44,902 - INFO - rxn16217_c0> not needed:3.586510954816036
2026-01-13 19:32:44,905 - INFO - AuxoMedia/bio1:rxn14424_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,906 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,911 - INFO - rxn12940_c0> not needed:3.586510954816028
2026-01-13 19:32:44,912 - INFO - rxn12929_c0> not needed:3.586510954816023
2026-01-13 19:32:44,914 - INFO - rxn25637_c0> not needed:3.586510954816044
2026-01-13 19:32:44,915 - INFO - rxn18935_c0> not needed:3.586510954816034
2026-01-13 19:32:44,916 - INFO - rxn25638_c0> not needed:3.586510954816034
2026-01-13 19:32:44,919 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,923 - INFO - AuxoMedia/bio1:rxn02485_c0> needed:1.3215331873456273e-13 with min obj:0.01
2026-01-13 19:32:44,924 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,929 - INFO - rxn46124_c0> not needed:3.58651095481603
2026-01-13 19:32:44,931 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,933 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,935 - INFO - rxn47267_c0> not needed:3.586510954816033
2026-01-13 19:32:44,936 - INFO - rxn41387_c0> not needed:3.5865109548160246
2026-01-13 19:32:44,939 - INFO - rxn15167_c0> not needed:3.584136234248257
2026-01-13 19:32:44,940 - INFO - rxn25042_c0> not needed:3.5841362342482523
2026-01-13 19:32:44,941 - INFO - rxn19766_c0> not needed:3.5841362342482523
2026-01-13 19:32:44,942 - INFO - rxn19764_c0> not needed:3.5841362342482523
2026-01-13 19:32:44,945 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,946 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,948 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,949 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,952 - INFO - rxn29919_c0> not needed:3.5841362342482315
2026-01-13 19:32:44,953 - INFO - rxn15064_c0> not needed:3.584136234248249
2026-01-13 19:32:44,954 - INFO - rxn11285_c0> not needed:3.584136234248249
2026-01-13 19:32:44,957 - INFO - AuxoMedia/bio1:rxn10095_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,961 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,962 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,964 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,965 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,970 - INFO - rxn08921_c0> not needed:3.136119204967227
2026-01-13 19:32:44,971 - INFO - rxn29260_c0> not needed:3.136104428042237
2026-01-13 19:32:44,975 - INFO - AuxoMedia/bio1:rxn14423_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:44,980 - INFO - rxn10042_c0> not needed:3.136104428042226
2026-01-13 19:32:44,983 - INFO - Unneeded: [['rxn16218_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn25637_c0', '>', 'new', 100, None], ['rxn18935_c0', '>', 'new', 100, None], ['rxn25638_c0', '>', 'new', 100, None], ['rxn46124_c0', '>', 'new', 100, None], ['rxn47267_c0', '>', 'new', 100, None], ['rxn41387_c0', '>', 'new', 100, None], ['rxn15167_c0', '>', 'new', 100, None], ['rxn25042_c0', '>', 'new', 100, None], ['rxn19766_c0', '>', 'new', 100, None], ['rxn19764_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn11285_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None]]
2026-01-13 19:32:44,990 - INFO - cpd00263 not found in model!
2026-01-13 19:32:44,990 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:44,991 - INFO - cpd00215 not found in model!
2026-01-13 19:32:44,991 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:44,994 - INFO - Growth: 3.5865109548160286 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01636_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01256_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn01972_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn01967_c0': '<', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn05029_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn03907_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn05117_c0': '>', 'rxn03439_c0': '>', 'rxn03638_c0': '>', 'rxn01541_c0': '<', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15167_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:44,998 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn01967_c0', '<', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn01541_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:32:44,998 - INFO -     Added 107 reactions
2026-01-13 19:32:44,999 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:45,488 - INFO - Objective with gapfill database:137.21706849317303; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:46,110 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd10515_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn02988_c0': '<', 'rxn00470_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01256_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn01000_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05119_c0': '>', 'rxn02011_c0': '>', 'rxn05645_c0': '>', 'rxn02402_c0': '<', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn05299_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03150_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn00834_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn28338_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn04551_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn46249_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:46,114 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:46,116 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:46,118 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:46,119 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:46,121 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:46,123 - INFO - integrating rxn: EX_cpd10515_e0
2026-01-13 19:32:46,124 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:32:46,126 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:46,128 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:46,130 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:46,132 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:46,133 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:46,135 - INFO - integrating rxn: rxn01636_c0
2026-01-13 19:32:46,137 - INFO - integrating rxn: rxn02988_c0
2026-01-13 19:32:46,138 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:32:46,140 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:46,141 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:46,143 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:46,144 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:46,146 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:46,147 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:46,149 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:46,150 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:46,152 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:46,153 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:46,155 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:46,157 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:46,158 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:32:46,160 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:46,161 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:46,162 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:46,164 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:46,165 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:32:46,167 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:46,168 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:46,170 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:46,171 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:46,172 - INFO - integrating rxn: rxn05119_c0
2026-01-13 19:32:46,174 - INFO - integrating rxn: rxn02011_c0
2026-01-13 19:32:46,175 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:46,177 - INFO - integrating rxn: rxn02402_c0
2026-01-13 19:32:46,179 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:46,180 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:46,182 - INFO - integrating rxn: rxn10094_c0
2026-01-13 19:32:46,184 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:46,186 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:46,187 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:46,189 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:46,191 - INFO - integrating rxn: rxn03538_c0
2026-01-13 19:32:46,193 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:46,194 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:46,196 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:46,198 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:46,199 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:46,201 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:46,203 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:46,205 - INFO - integrating rxn: rxn02897_c0
2026-01-13 19:32:46,206 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:46,208 - INFO - integrating rxn: rxn00134_c0
2026-01-13 19:32:46,210 - INFO - integrating rxn: rxn05223_c0
2026-01-13 19:32:46,211 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:46,213 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:46,214 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:46,216 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:46,218 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:46,219 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:46,221 - INFO - integrating rxn: rxn01538_c0
2026-01-13 19:32:46,222 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:46,224 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:46,225 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:46,227 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:46,228 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:46,230 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:46,232 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:46,233 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:46,235 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:46,237 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:46,238 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:46,240 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:46,242 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:46,243 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:46,245 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:46,246 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:46,248 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:32:46,249 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:32:46,251 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:46,252 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:46,254 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:46,255 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:46,257 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:46,258 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:46,260 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:46,261 - INFO - integrating rxn: rxn28338_c0
2026-01-13 19:32:46,263 - INFO - integrating rxn: rxn01736_c0
2026-01-13 19:32:46,264 - INFO - integrating rxn: rxn00644_c0
2026-01-13 19:32:46,266 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:32:46,267 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:46,269 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:46,270 - INFO - integrating rxn: rxn17394_c0
2026-01-13 19:32:46,272 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:46,274 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:46,275 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:46,276 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:46,278 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:46,280 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:46,281 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:46,283 - INFO - integrating rxn: rxn46249_c0
2026-01-13 19:32:46,285 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:32:46,286 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:32:46,288 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:32:46,289 - INFO - integrating rxn: rxn20472_c0
2026-01-13 19:32:46,291 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:46,292 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:46,294 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:32:46,295 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:46,296 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:32:46,333 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,336 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,338 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,340 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,341 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,344 - INFO - AuxoMedia/bio1:EX_cpd10515_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,345 - INFO - AuxoMedia/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,347 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,349 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,351 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,353 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,355 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,356 - INFO - AuxoMedia/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,359 - INFO - AuxoMedia/bio1:rxn02988_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,361 - INFO - AuxoMedia/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,363 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,364 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,366 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,368 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,369 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,372 - INFO - AuxoMedia/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,373 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,375 - INFO - AuxoMedia/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,377 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,379 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,380 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,382 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,384 - INFO - AuxoMedia/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,385 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,387 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,389 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,391 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,392 - INFO - AuxoMedia/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,394 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,396 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,397 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,399 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,401 - INFO - AuxoMedia/bio1:rxn05119_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,403 - INFO - AuxoMedia/bio1:rxn02011_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,404 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,406 - INFO - AuxoMedia/bio1:rxn02402_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,408 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,410 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,412 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,413 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,415 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,417 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,419 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,420 - INFO - AuxoMedia/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,422 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,424 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,426 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,427 - INFO - AuxoMedia/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,429 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,431 - INFO - AuxoMedia/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,432 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,434 - INFO - AuxoMedia/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,436 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,437 - INFO - AuxoMedia/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,439 - INFO - AuxoMedia/bio1:rxn05223_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,441 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,442 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,444 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,446 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,448 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,450 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,452 - INFO - AuxoMedia/bio1:rxn01538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,453 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,455 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:46,457 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,459 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,461 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,462 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,464 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:46,466 - INFO - rxn16218_c0> not needed:4.26644561286423
2026-01-13 19:32:46,468 - INFO - rxn16217_c0> not needed:4.266445612864213
2026-01-13 19:32:46,470 - INFO - rxn14424_c0> not needed:4.26644561286423

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd10515_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn02988_c0': '<', 'rxn00470_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01256_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn01000_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05119_c0': '>', 'rxn02011_c0': '>', 'rxn05645_c0': '>', 'rxn02402_c0': '<', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn05299_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03150_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn00834_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn28338_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn04551_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn46249_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:46,570 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08473_c0', '>', 'new']]
2026-01-13 19:32:46,571 - INFO -     Added 96 reactions
2026-01-13 19:32:46,572 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:46,817 - INFO - Objective with gapfill database:137.21706849317093; min objective:0.01
2026-01-13 19:32:47,149 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00084_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01636_c0': '>', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn02212_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn04464_c0': '>', 'rxn01256_c0': '>', 'rxn03910_c0': '>', 'rxn03919_c0': '>', 'rxn13840_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn04704_c0': '>', 'rxn01000_c0': '>', 'rxn10663_c0': '<', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn01300_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn04413_c0': '>', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn00420_c0': '>', 'rxn03893_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn03907_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn00952_c0': '>', 'rxn00533_c0': '>', 'rxn10667_c0': '>', 'rxn01265_c0': '<', 'rxn00834_c0': '>', 'rxn11702_c0': '>', 'rxn00346_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00623_c0': '<', 'rxn02341_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05177_c0': '>', 'rxn02914_c0': '<', 'rxn00686_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn39982_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12939_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn27266_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:47,154 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:47,156 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:47,156 - INFO - Objective with gapfill database:137.21706849317292; min objective:0.01
2026-01-13 19:32:47,157 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:47,159 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:47,160 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:47,162 - INFO - integrating rxn: EX_cpd00084_e0
2026-01-13 19:32:47,164 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:47,166 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:32:47,167 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:47,169 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:47,170 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:32:47,172 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:47,173 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:47,175 - INFO - integrating rxn: rxn03030_c0
2026-01-13 19:32:47,177 - INFO - integrating rxn: rxn01636_c0
2026-01-13 19:32:47,178 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:32:47,179 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:47,181 - INFO - integrating rxn: rxn00100_c0
2026-01-13 19:32:47,182 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:47,183 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:47,185 - INFO - integrating rxn: rxn02212_c0
2026-01-13 19:32:47,186 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:47,188 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:47,189 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:47,190 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:47,192 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:47,194 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:47,195 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:47,197 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:47,199 - INFO - integrating rxn: rxn04464_c0
2026-01-13 19:32:47,200 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:32:47,201 - INFO - integrating rxn: rxn03910_c0
2026-01-13 19:32:47,202 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:47,204 - INFO - integrating rxn: rxn13840_c0
2026-01-13 19:32:47,205 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:47,207 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:47,209 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:47,210 - INFO - integrating rxn: rxn04704_c0
2026-01-13 19:32:47,212 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:32:47,214 - INFO - integrating rxn: rxn10663_c0
2026-01-13 19:32:47,215 - INFO - integrating rxn: rxn01972_c0
2026-01-13 19:32:47,217 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:47,218 - INFO - integrating rxn: rxn01300_c0
2026-01-13 19:32:47,220 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:47,221 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:47,223 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:47,224 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:47,226 - INFO - integrating rxn: rxn05463_c0
2026-01-13 19:32:47,227 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:47,228 - INFO - integrating rxn: rxn05237_c0
2026-01-13 19:32:47,230 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:32:47,231 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:32:47,233 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:47,234 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:47,236 - INFO - integrating rxn: rxn00420_c0
2026-01-13 19:32:47,238 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:47,239 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:47,240 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:32:47,242 - INFO - integrating rxn: rxn03907_c0
2026-01-13 19:32:47,243 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:47,245 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:47,246 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:47,248 - INFO - integrating rxn: rxn00952_c0
2026-01-13 19:32:47,249 - INFO - integrating rxn: rxn00533_c0
2026-01-13 19:32:47,251 - INFO - integrating rxn: rxn10667_c0
2026-01-13 19:32:47,252 - INFO - integrating rxn: rxn01265_c0
2026-01-13 19:32:47,253 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:47,255 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:47,257 - INFO - integrating rxn: rxn00346_c0
2026-01-13 19:32:47,258 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:47,260 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:47,261 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:47,263 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:47,265 - INFO - integrating rxn: rxn01602_c0
2026-01-13 19:32:47,266 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:47,268 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:47,269 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:47,270 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:47,272 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:47,273 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:47,275 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:47,276 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:47,277 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:47,279 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:32:47,280 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:47,281 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:47,283 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:47,284 - INFO - integrating rxn: rxn05177_c0
2026-01-13 19:32:47,286 - INFO - integrating rxn: rxn02914_c0
2026-01-13 19:32:47,287 - INFO - integrating rxn: rxn00686_c0
2026-01-13 19:32:47,288 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:47,290 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:47,291 - INFO - integrating rxn: rxn39982_c0
2026-01-13 19:32:47,293 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:47,295 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:32:47,296 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:47,297 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:32:47,299 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:47,300 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:47,302 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:47,303 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:32:47,305 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:32:47,306 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:47,307 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:47,309 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:47,311 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:32:47,312 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:32:47,314 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:47,315 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:32:47,317 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:47,318 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:47,320 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:32:47,321 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:32:47,323 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:47,324 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:47,326 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:47,327 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:47,329 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:47,330 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:47,331 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:47,333 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:47,334 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:47,335 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:47,337 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:47,338 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:47,340 - INFO - integrating rxn: rxn27266_c0
2026-01-13 19:32:47,341 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:47,342 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:47,344 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:47,345 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:47,347 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:47,347 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn02212_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn04464_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03910_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn13840_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn10663_c0', '<', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn00952_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn10667_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05177_c0', '>', 'new'], ['rxn02914_c0', '<', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn39982_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn27266_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:47,365 - INFO - cpd00263 not found in model!
2026-01-13 19:32:47,366 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:47,368 - INFO - cpd00215 not found in model!
2026-01-13 19:32:47,368 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:47,397 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:47,399 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:47,400 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:47,402 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:47,404 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:47,407 - INFO - EX_cpd00084_e0< not needed:8.87519528037982
2026-01-13 19:32:47,411 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:47,412 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:47,414 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:47,416 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:47,417 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:-3.064308384128817e-12 with min obj:0.01
2026-01-13 19:32:47,419 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:47,421 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:47,423 - INFO - AuxoMedia/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:47,425 - INFO - AuxoMedia/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:47,427 - INFO - AuxoMedia/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:47,428 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:47,430 - INFO - AuxoMedia/bio1:rxn00100_c0> needed:0.0 with min obj:0.01

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00084_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01636_c0': '>', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn02212_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn04464_c0': '>', 'rxn01256_c0': '>', 'rxn03910_c0': '>', 'rxn03919_c0': '>', 'rxn13840_c0': '<', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn04704_c0': '>', 'rxn01000_c0': '>', 'rxn10663_c0': '<', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn01300_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn05237_c0': '>', 'rxn04413_c0': '>', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn00420_c0': '>', 'rxn03893_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn03907_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn00952_c0': '>', 'rxn00533_c0': '>', 'rxn10667_c0': '>', 'rxn01265_c0': '<', 'rxn00834_c0': '>', 'rxn11702_c0': '>', 'rxn00346_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn01602_c0': '<', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00623_c0': '<', 'rxn02341_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05177_c0': '>', 'rxn02914_c0': '<', 'rxn00686_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn39982_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12939_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn27266_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:47,703 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn02212_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn04464_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03910_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn00952_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn10667_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05177_c0', '>', 'new'], ['rxn02914_c0', '<', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn39982_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:32:47,703 - INFO -     Added 102 reactions
2026-01-13 19:32:47,704 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:49,210 - INFO - Objective with gapfill database:137.21706849317093; min objective:0.01
2026-01-13 19:32:49,405 - INFO - Objective with gapfill database:114.73871061823121; min objective:0.01
2026-01-13 19:32:49,429 - INFO - Objective with gapfill database:137.21706849317317; min objective:0.01
2026-01-13 19:32:49,604 - INFO - Objective with gapfill database:137.21706849317292; min objective:0.01
2026-01-13 19:32:49,899 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd10515_e0': '<', 'rxn08709_c0': '>', 'rxn02000_c0': '>', 'rxn01358_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn02988_c0': '<', 'rxn08710_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn03918_c0': '>', 'rxn00727_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn00927_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05119_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn10094_c0': '>', 'rxn05299_c0': '>', 'rxn03917_c0': '>', 'rxn03150_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn11702_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn02003_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn39982_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn15395_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn08474_c0': '>', 'rxn08473_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:49,902 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:49,904 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:49,905 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:49,907 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:49,909 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:49,910 - INFO - integrating rxn: EX_cpd10515_e0
2026-01-13 19:32:49,912 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:49,914 - INFO - integrating rxn: rxn02000_c0
2026-01-13 19:32:49,915 - INFO - integrating rxn: rxn01358_c0
2026-01-13 19:32:49,917 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:49,918 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:49,920 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:32:49,922 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:49,923 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:49,925 - INFO - integrating rxn: rxn02988_c0
2026-01-13 19:32:49,927 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:49,929 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:49,930 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:49,932 - INFO - integrating rxn: rxn01997_c0
2026-01-13 19:32:49,933 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:49,935 - INFO - integrating rxn: rxn00727_c0
2026-01-13 19:32:49,937 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:49,938 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:49,940 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:49,941 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:49,942 - INFO - integrating rxn: rxn00830_c0
2026-01-13 19:32:49,944 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:49,945 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:49,947 - INFO - integrating rxn: rxn01675_c0
2026-01-13 19:32:49,948 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:49,950 - INFO - integrating rxn: rxn00927_c0
2026-01-13 19:32:49,951 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:49,953 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:49,954 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:49,956 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:49,957 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:49,958 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:49,960 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:49,961 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:49,963 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:49,964 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:49,966 - INFO - integrating rxn: rxn05119_c0
2026-01-13 19:32:49,966 - INFO - Objective with gapfill database:137.2170684931731; min objective:0.01
2026-01-13 19:32:49,968 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:49,969 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:49,971 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:49,972 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:49,973 - INFO - integrating rxn: rxn02402_c0
2026-01-13 19:32:49,975 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:49,976 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:32:49,978 - INFO - integrating rxn: rxn10094_c0
2026-01-13 19:32:49,979 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:49,980 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:49,982 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:49,983 - INFO - integrating rxn: rxn03087_c0
2026-01-13 19:32:49,984 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:49,986 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:49,987 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:49,988 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:49,990 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:49,991 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:49,993 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:49,994 - INFO - integrating rxn: rxn02003_c0
2026-01-13 19:32:49,996 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:49,997 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:49,999 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:50,001 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:50,002 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:50,004 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:50,005 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:50,006 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:50,008 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:50,009 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:50,011 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:50,012 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:50,013 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:50,015 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:50,016 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:50,018 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:50,019 - INFO - integrating rxn: rxn39982_c0
2026-01-13 19:32:50,021 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:50,023 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:50,024 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:50,025 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:50,027 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:50,028 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:32:50,030 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:50,031 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:50,033 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:50,034 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:32:50,036 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:50,037 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:50,039 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:50,040 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:50,042 - INFO - integrating rxn: rxn15395_c0
2026-01-13 19:32:50,043 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:50,045 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:50,046 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:50,048 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:50,049 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:50,050 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:50,052 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:32:50,053 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:50,055 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:50,056 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:50,058 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:50,059 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:32:50,061 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:32:50,062 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:32:50,063 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:50,065 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:50,066 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:50,067 - INFO - integrating rxn: rxn08474_c0
2026-01-13 19:32:50,069 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:32:50,068 - INFO - Objective with gapfill database:114.73871061823094; min objective:0.01
2026-01-13 19:32:50,070 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:50,072 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:32:50,074 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:32:50,076 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:32:50,077 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:32:50,078 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn01358_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00727_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn00927_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn39982_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn15395_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn08474_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:50,125 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,130 - INFO - EX_cpd00119_e0< not needed:4.595331605891667
2026-01-13 19:32:50,132 - INFO - Objective with gapfill database:137.21706849317314; min objective:0.01
2026-01-13 19:32:50,133 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,135 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,137 - INFO - AuxoMedia/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,138 - INFO - AuxoMedia/bio1:EX_cpd10515_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,140 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,142 - INFO - AuxoMedia/bio1:rxn02000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,146 - INFO - rxn01358_c0> not needed:4.595331605891687
2026-01-13 19:32:50,149 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,151 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,153 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,154 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,156 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,158 - INFO - AuxoMedia/bio1:rxn02988_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,159 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,161 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,162 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,164 - INFO - AuxoMedia/bio1:rxn01997_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,165 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,167 - INFO - AuxoMedia/bio1:rxn00727_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,169 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,171 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,173 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,174 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,176 - INFO - AuxoMedia/bio1:rxn00830_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,178 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,179 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,181 - INFO - AuxoMedia/bio1:rxn01675_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,185 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00099_e0': '<', 'EX_cpd10515_e0': '<', 'rxn08709_c0': '>', 'rxn02000_c0': '>', 'rxn01358_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn02988_c0': '<', 'rxn08710_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn03918_c0': '>', 'rxn00727_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01675_c0': '>', 'rxn03536_c0': '>', 'rxn00927_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05119_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn02402_c0': '<', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn10094_c0': '>', 'rxn05299_c0': '>', 'rxn03917_c0': '>', 'rxn03150_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn11702_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn02003_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn39982_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn15395_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn08474_c0': '>', 'rxn08473_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:50,418 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00727_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn00927_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:50,419 - INFO -     Added 93 reactions
2026-01-13 19:32:50,420 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:50,455 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,457 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,460 - INFO - EX_cpd00119_e0< not needed:7.695331300597288
2026-01-13 19:32:50,464 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,465 - INFO - AuxoMedia/bio1:EX_cpd10515_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,467 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,469 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,471 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,473 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,475 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,476 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,478 - INFO - AuxoMedia/bio1:rxn05235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,479 - INFO - AuxoMedia/bio1:rxn00100_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,481 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,483 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,485 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,487 - INFO - AuxoMedia/bio1:rxn00340_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,488 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,490 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,492 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,493 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,495 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,497 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,499 - INFO - rxn01454_c0< not needed:7.695331300597318
2026-01-13 19:32:50,501 - INFO - rxn01501_c0< not needed:7.695331300597318
2026-01-13 19:32:50,504 - INFO - AuxoMedia/bio1:rxn03910_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,505 - INFO - AuxoMedia/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,507 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,509 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,510 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,512 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,514 - INFO - AuxoMedia/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,516 - INFO - AuxoMedia/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,517 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,519 - INFO - AuxoMedia/bio1:rxn00838_c0> needed:1.429075182040615e-13 with min obj:0.01
2026-01-13 19:32:50,521 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,523 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,524 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,526 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,528 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,529 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,531 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,533 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,535 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,540 - INFO - AuxoMedia/bio1:rxn01539_c0< needed:-6.083283924666589e-13 with min obj:0.01
2026-01-13 19:32:50,542 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,545 - INFO - rxn05299_c0> not needed:7.695331300597331
2026-01-13 19:32:50,548 - INFO - AuxoMedia/bio1:rxn01508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,550 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,553 - INFO - rxn05236_c0> not needed:7.694737344131112
2026-01-13 19:32:50,556 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,557 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn04996_c0': '<', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn00213_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09429_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn03907_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12939_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn06090_c0': '>', 'rxn07254_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15166_c0': '>', 'rxn30633_c0': '>', 'rxn19346_c0': '>', 'rxn00644_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn09390_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:50,560 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:50,561 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:50,562 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,563 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:50,564 - INFO - AuxoMedia/bio1:rxn03907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,565 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:50,566 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:32:50,566 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,568 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:50,568 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:3.2712681562407207e-13 with min obj:0.01
2026-01-13 19:32:50,570 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:50,570 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,571 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:50,572 - INFO - AuxoMedia/bio1:rxn01265_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,573 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:50,574 - INFO - AuxoMedia/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,575 - INFO - integrating rxn: rxn04996_c0
2026-01-13 19:32:50,576 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,576 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:50,578 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,578 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:50,579 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,580 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:50,581 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,581 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:50,582 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,583 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:50,584 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,585 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:50,586 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,586 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:50,587 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,588 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:50,589 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,590 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:50,591 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,591 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:50,592 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,593 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:50,594 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,595 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:50,596 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,596 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:50,598 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,598 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:50,599 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,600 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:50,601 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,602 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:50,603 - INFO - integrating rxn: rxn00213_c0
2026-01-13 19:32:50,604 - INFO - rxn16218_c0> not needed:7.694737344131089
2026-01-13 19:32:50,604 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:50,606 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:50,607 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,608 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:50,609 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:50,610 - INFO - rxn16217_c0> not needed:7.694737344131136
2026-01-13 19:32:50,611 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:50,612 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:50,612 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,614 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:50,614 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,615 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:50,617 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:50,617 - INFO - rxn12932_c0> not needed:7.5742560704756015
2026-01-13 19:32:50,619 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:50,620 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:50,621 - INFO - rxn12940_c0> not needed:7.574256070475593
2026-01-13 19:32:50,622 - INFO - integrating rxn: rxn09429_c0
2026-01-13 19:32:50,623 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:50,624 - INFO - rxn12939_c0> not needed:7.453774796820134
2026-01-13 19:32:50,625 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:50,625 - INFO - rxn12929_c0> not needed:7.4537747968201
2026-01-13 19:32:50,626 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:32:50,627 - INFO - rxn25637_c0> not needed:7.4537747968201
2026-01-13 19:32:50,628 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:50,628 - INFO - rxn18935_c0> not needed:7.4537747968201
2026-01-13 19:32:50,629 - INFO - integrating rxn: rxn06023_c0
2026-01-13 19:32:50,629 - INFO - rxn25743_c0> not needed:7.4537747968201
2026-01-13 19:32:50,630 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:50,631 - INFO - rxn12928_c0> not needed:7.4537747968201
2026-01-13 19:32:50,632 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:50,634 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:50,634 - INFO - rxn12944_c0> not needed:7.333293523164659
2026-01-13 19:32:50,635 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:50,636 - INFO - rxn12994_c0> not needed:7.333293523164616
2026-01-13 19:32:50,637 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:50,638 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:50,638 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,640 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:50,641 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:50,642 - INFO - rxn12942_c0> not needed:7.333293523164597
2026-01-13 19:32:50,643 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:50,644 - INFO - integrating rxn: rxn03907_c0
2026-01-13 19:32:50,646 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:50,647 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:50,647 - INFO - AuxoMedia/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,648 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:50,649 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,650 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:50,651 - INFO - integrating rxn: rxn04113_c0
2026-01-13 19:32:50,651 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,653 - INFO - integrating rxn: rxn00704_c0
2026-01-13 19:32:50,653 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,654 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:50,656 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:50,657 - INFO - rxn11251_c0> not needed:7.33307262729097
2026-01-13 19:32:50,657 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:50,658 - INFO - rxn47267_c0> not needed:7.333072627290961
2026-01-13 19:32:50,659 - INFO - integrating rxn: rxn00346_c0
2026-01-13 19:32:50,660 - INFO - rxn41387_c0> not needed:7.333072627290961
2026-01-13 19:32:50,660 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:50,661 - INFO - integrating rxn: rxn00134_c0
2026-01-13 19:32:50,662 - INFO - AuxoMedia/bio1:rxn15166_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,663 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:50,664 - INFO - AuxoMedia/bio1:rxn28338_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,664 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:50,666 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:50,666 - INFO - AuxoMedia/bio1:rxn25042_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,667 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:50,668 - INFO - AuxoMedia/bio1:rxn19766_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,669 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:50,670 - INFO - AuxoMedia/bio1:rxn19764_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,670 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:50,672 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:50,672 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,673 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:50,674 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,674 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:50,676 - INFO - integrating rxn: rxn00138_c0
2026-01-13 19:32:50,676 - INFO - rxn16114_c0> not needed:7.333072627290958
2026-01-13 19:32:50,677 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:50,679 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:50,679 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,680 - INFO - integrating rxn: rxn02341_c0

Adding gapfilling

2026-01-13 19:32:50,741 - INFO - integrating rxn: rxn20508_c0

{'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd10515_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn05235_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn03918_c0': '>', 'rxn00340_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01454_c0': '<', 'rxn01501_c0': '<', 'rxn03910_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn00838_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn01539_c0': '<', 'rxn10094_c0': '>', 'rxn05299_c0': '>', 'rxn01508_c0': '>', 'rxn09657_c0': '>', 'rxn05236_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn03907_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn01265_c0': '<', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15166_c0': '>', 'rxn28338_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn20567_c0': '>', 'rxn23676_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:50,743 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:50,743 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00340_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03910_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn00838_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn01508_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new']]
2026-01-13 19:32:50,744 - INFO -     Added 91 reactions
2026-01-13 19:32:50,745 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:50,745 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:50,746 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:50,748 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:32:50,749 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:50,751 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:50,752 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:32:50,754 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:32:50,755 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:50,756 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn04996_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00213_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09429_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn06090_c0', '>', 'new'], ['rxn07254_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:32:50,774 - INFO - cpd00263 not found in model!
2026-01-13 19:32:50,775 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:50,776 - INFO - cpd00215 not found in model!
2026-01-13 19:32:50,776 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:50,806 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,808 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,810 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,812 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,815 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,817 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,819 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,821 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,823 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,825 - INFO - AuxoMedia/bio1:rxn04996_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,827 - INFO - AuxoMedia/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,829 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,830 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,832 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,834 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,836 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,837 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,839 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,841 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,842 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,844 - INFO - AuxoMedia/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,846 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,848 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,849 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,851 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,852 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,854 - INFO - AuxoMedia/bio1:rxn00213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,856 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,858 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,859 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,861 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,863 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,864 - INFO - AuxoMedia/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,866 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,868 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,869 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,871 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,873 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,875 - INFO - AuxoMedia/bio1:rxn09429_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,877 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,878 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,880 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,882 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,883 - INFO - AuxoMedia/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,885 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,887 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,889 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,890 - INFO - AuxoMedia/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,892 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,894 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,895 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,897 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,898 - INFO - AuxoMedia/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,900 - INFO - AuxoMedia/bio1:rxn03907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,902 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,904 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,906 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,908 - INFO - AuxoMedia/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,909 - INFO - AuxoMedia/bio1:rxn04113_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,911 - INFO - AuxoMedia/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,913 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,915 - INFO - AuxoMedia/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,916 - INFO - AuxoMedia/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,918 - INFO - AuxoMedia/bio1:rxn00346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,920 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,924 - INFO - rxn00134_c0> not needed:6.847161809635421
2026-01-13 19:32:50,929 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,931 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,933 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,934 - INFO - AuxoMedia/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,936 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,938 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,940 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,941 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,943 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:50,945 - INFO - AuxoMedia/bio1:rxn00138_c0> needed:3.16484998891156e-13 with min obj:0.01
2026-01-13 19:32:50,946 - INFO - AuxoMedia/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,950 - INFO - rxn05464_c0> not needed:6.847161809635408
2026-01-13 19:32:50,954 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,956 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,957 - INFO - AuxoMedia/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,959 - INFO - AuxoMedia/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,961 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,963 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,967 - INFO - rxn16218_c0> not needed:6.847161809635347
2026-01-13 19:32:50,970 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,972 - INFO - rxn16217_c0> not needed:6.847161809635384
2026-01-13 19:32:50,975 - INFO - AuxoMedia/bio1:rxn14424_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,977 - INFO - AuxoMedia/bio1:rxn11274_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,980 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,985 - INFO - rxn12932_c0> not needed:6.847161809635431
2026-01-13 19:32:50,987 - INFO - rxn12939_c0> not needed:6.847161809635431
2026-01-13 19:32:50,989 - INFO - rxn12938_c0> not needed:6.847161809635431
2026-01-13 19:32:50,990 - INFO - rxn12927_c0> not needed:6.847161809635431
2026-01-13 19:32:50,991 - INFO - rxn12921_c0> not needed:6.847161809635431
2026-01-13 19:32:50,993 - INFO - rxn12928_c0> not needed:6.847161809635431
2026-01-13 19:32:50,995 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:50,998 - INFO - rxn12942_c0> not needed:6.847161809635484
2026-01-13 19:32:51,002 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,003 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,008 - INFO - rxn06090_c0> not needed:6.847161809635517
2026-01-13 19:32:51,009 - INFO - rxn07254_c0> not needed:6.8471618096354785
2026-01-13 19:32:51,014 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,020 - INFO - rxn11251_c0> not needed:6.84716180963545
2026-01-13 19:32:51,021 - INFO - rxn47267_c0> not needed:6.847161809635386
2026-01-13 19:32:51,022 - INFO - rxn41387_c0> not needed:6.847161809635386
2026-01-13 19:32:51,024 - INFO - rxn15166_c0> not needed:6.847161809635386
2026-01-13 19:32:51,025 - INFO - rxn30633_c0> not needed:6.847161809635386
2026-01-13 19:32:51,026 - INFO - rxn19346_c0> not needed:6.847161809635386
2026-01-13 19:32:51,028 - INFO - rxn00644_c0> not needed:6.633329528082605
2026-01-13 19:32:51,031 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,033 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,035 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,037 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,042 - INFO - rxn15060_c0> not needed:6.633329528082634
2026-01-13 19:32:51,044 - INFO - rxn29919_c0> not needed:6.633329528082634
2026-01-13 19:32:51,045 - INFO - rxn15064_c0> not needed:6.633329528082634
2026-01-13 19:32:51,046 - INFO - rxn10095_c0> not needed:6.633329528082634
2026-01-13 19:32:51,049 - INFO - AuxoMedia/bio1:rxn20508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,051 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,053 - INFO - rxn15940_c0> not needed:6.633329528082667
2026-01-13 19:32:51,057 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,059 - INFO - AuxoMedia/bio1:rxn15939_c0> needed:8.780048539474804e-13 with min obj:0.01
2026-01-13 19:32:51,061 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,063 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,067 - INFO - rxn09390_c0> not needed:6.6333295280826094
2026-01-13 19:32:51,070 - INFO - AuxoMedia/bio1:rxn14423_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:51,075 - INFO - rxn10042_c0> not needed:6.633329528082681
2026-01-13 19:32:51,079 - INFO - Unneeded: [['rxn00134_c0', '>', 'new', 100, None], ['rxn05464_c0', '>', 'new', 100, None], ['rxn16218_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn12932_c0', '>', 'new', 100, None], ['rxn12939_c0', '>', 'new', 100, None], ['rxn12938_c0', '>', 'new', 100, None], ['rxn12927_c0', '>', 'new', 100, None], ['rxn12921_c0', '>', 'new', 100, None], ['rxn12928_c0', '>', 'new', 100, None], ['rxn12942_c0', '>', 'new', 100, None], ['rxn06090_c0', '>', 'new', 100, None], ['rxn07254_c0', '>', 'new', 100, None], ['rxn11251_c0', '>', 'new', 100, None], ['rxn47267_c0', '>', 'new', 100, None], ['rxn41387_c0', '>', 'new', 100, None], ['rxn15166_c0', '>', 'new', 100, None], ['rxn30633_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn00644_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn10095_c0', '>', 'new', 100, None], ['rxn15940_c0', '>', 'new', 100, None], ['rxn09390_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None]]
2026-01-13 19:32:51,089 - INFO - cpd00263 not found in model!
2026-01-13 19:32:51,090 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:51,091 - INFO - cpd00215 not found in model!

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn04996_c0': '<', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn00213_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09429_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn03907_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12939_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn06090_c0': '>', 'rxn07254_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15166_c0': '>', 'rxn30633_c0': '>', 'rxn19346_c0': '>', 'rxn00644_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn09390_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:51,099 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn04996_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00213_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09429_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:32:51,100 - INFO -     Added 101 reactions
2026-01-13 19:32:51,101 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:51,106 - INFO - Objective with gapfill database:137.21706849317326; min objective:0.01
2026-01-13 19:32:51,848 - INFO - Objective with gapfill database:137.21706849317317; min objective:0.01
2026-01-13 19:32:51,903 - INFO - Objective with gapfill database:114.73871061823121; min objective:0.01
2026-01-13 19:32:52,180 - INFO - Objective with gapfill database:137.21706849317414; min objective:0.01
2026-01-13 19:32:52,429 - INFO - Objective with gapfill database:137.21706849317295; min objective:0.01
2026-01-13 19:32:52,437 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00099_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn00599_c0': '>', 'rxn11702_c0': '>', 'rxn03439_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn39982_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn15166_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16671_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn18575_c0': '>', 'rxn08233_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn19006_c0': '>', 'rxn19007_c0': '>', 'rxn14423_c0': '>', 'rxn10154_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:52,440 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:52,442 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:52,444 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:52,445 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:52,447 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:32:52,449 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:52,450 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:52,452 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:52,454 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:52,455 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:52,457 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:52,459 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:52,459 - INFO - Initial solution: {'reversed': {'rxn00777_c0': '>', 'rxn01302_c0': '<', 'rxn00558_c0': '<', 'rxn00347_c0': '>'}, 'new': {'EX_cpd00013_e0': '<', 'EX_cpd00020_e0': '<', 'rxn00359_c0': '<', 'rxn00800_c0': '>', 'rxn02320_c0': '<', 'rxn02504_c0': '>', 'rxn00544_c0': '>', 'rxn00898_c0': '>', 'rxn02988_c0': '<', 'rxn02305_c0': '>', 'rxn00337_c0': '>', 'rxn00902_c0': '<', 'rxn01306_c0': '<', 'rxn05469_c0': '>', 'rxn00789_c0': '<', 'rxn03436_c0': '>', 'rxn13022_c0': '>', 'rxn00802_c0': '>', 'rxn02160_c0': '>', 'rxn00727_c0': '>', 'rxn00957_c0': '>', 'rxn02159_c0': '>', 'rxn05466_c0': '>', 'rxn00300_c0': '>', 'rxn02380_c0': '<', 'rxn01643_c0': '<', 'rxn02835_c0': '>', 'rxn01575_c0': '<', 'rxn03435_c0': '<', 'rxn01256_c0': '>', 'rxn03175_c0': '>', 'rxn00306_c0': '>', 'rxn00527_c0': '<', 'rxn05119_c0': '>', 'rxn12868_c0': '>', 'rxn01345_c0': '>', 'rxn01967_c0': '<', 'rxn00863_c0': '>', 'rxn01270_c0': '<', 'rxn02402_c0': '<', 'rxn01303_c0': '>', 'rxn03437_c0': '>', 'rxn02508_c0': '>', 'rxn00420_c0': '>', 'rxn00048_c0': '>', 'rxn03108_c0': '>', 'rxn05035_c0': '>', 'rxn00791_c0': '<', 'rxn00490_c0': '>', 'rxn00691_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn00952_c0': '>', 'rxn03841_c0': '>', 'rxn12239_c0': '>', 'rxn01257_c0': '>', 'rxn00903_c0': '<', 'rxn00806_c0': '<', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn02473_c0': '>', 'rxn01434_c0': '>', 'rxn08094_c0': '<', 'rxn00623_c0': '<', 'rxn02507_c0': '>', 'rxn01964_c0': '>', 'rxn02186_c0': '>', 'rxn01019_c0': '>', 'rxn01603_c0': '>', 'rxn03194_c0': '>', 'rxn21857_c0': '>', 'rxn16573_c0': '>', 'rxn21635_c0': '>', 'rxn11279_c0': '>', 'rxn21859_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn21861_c0': '>', 'rxn40439_c0': '>', 'rxn21860_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn11251_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn16048_c0': '>', 'rxn16114_c0': '>', 'rxn29919_c0': '>', 'rxn37372_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn15939_c0': '>', 'rxn47493_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:52,460 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:52,462 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:32:52,462 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:52,464 - INFO - integrating rxn: EX_cpd00020_e0
2026-01-13 19:32:52,464 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:52,466 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:32:52,466 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:52,467 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:52,468 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:52,469 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:32:52,470 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:52,470 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:32:52,471 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:52,472 - INFO - integrating rxn: rxn00544_c0
2026-01-13 19:32:52,473 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:52,473 - INFO - integrating rxn: rxn00898_c0
2026-01-13 19:32:52,474 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:52,475 - INFO - integrating rxn: rxn02988_c0
2026-01-13 19:32:52,476 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:52,476 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:32:52,478 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:52,478 - INFO - integrating rxn: rxn00337_c0
2026-01-13 19:32:52,480 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:52,480 - INFO - integrating rxn: rxn00902_c0
2026-01-13 19:32:52,481 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:52,482 - INFO - integrating rxn: rxn01306_c0
2026-01-13 19:32:52,483 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:52,483 - INFO - integrating rxn: rxn05469_c0
2026-01-13 19:32:52,485 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:52,485 - INFO - integrating rxn: rxn00789_c0
2026-01-13 19:32:52,486 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:52,487 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:32:52,488 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:52,488 - INFO - integrating rxn: rxn13022_c0
2026-01-13 19:32:52,489 - INFO - integrating rxn: rxn00802_c0
2026-01-13 19:32:52,490 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:52,491 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:32:52,491 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:52,492 - INFO - integrating rxn: rxn00727_c0
2026-01-13 19:32:52,493 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:52,494 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:32:52,495 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:52,495 - INFO - integrating rxn: rxn02159_c0
2026-01-13 19:32:52,496 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:52,497 - INFO - integrating rxn: rxn05466_c0
2026-01-13 19:32:52,498 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:52,498 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:32:52,500 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:52,500 - INFO - integrating rxn: rxn02380_c0
2026-01-13 19:32:52,501 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:52,501 - INFO - integrating rxn: rxn01643_c0
2026-01-13 19:32:52,502 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:52,503 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:32:52,504 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:52,504 - INFO - integrating rxn: rxn01575_c0
2026-01-13 19:32:52,505 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:52,506 - INFO - integrating rxn: rxn03435_c0
2026-01-13 19:32:52,507 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:32:52,507 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:52,508 - INFO - integrating rxn: rxn03175_c0
2026-01-13 19:32:52,509 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:52,510 - INFO - integrating rxn: rxn00306_c0
2026-01-13 19:32:52,510 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:52,511 - INFO - integrating rxn: rxn00527_c0
2026-01-13 19:32:52,512 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:52,512 - INFO - integrating rxn: rxn05119_c0
2026-01-13 19:32:52,513 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:52,514 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:32:52,515 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:52,515 - INFO - integrating rxn: rxn01345_c0
2026-01-13 19:32:52,516 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:52,516 - INFO - integrating rxn: rxn01967_c0
2026-01-13 19:32:52,518 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:52,518 - INFO - integrating rxn: rxn00863_c0
2026-01-13 19:32:52,519 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:52,520 - INFO - integrating rxn: rxn01270_c0
2026-01-13 19:32:52,520 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:52,521 - INFO - integrating rxn: rxn02402_c0
2026-01-13 19:32:52,522 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:52,523 - INFO - integrating rxn: rxn01303_c0
2026-01-13 19:32:52,523 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:52,524 - INFO - integrating rxn: rxn03437_c0
2026-01-13 19:32:52,525 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:52,525 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:32:52,526 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:52,527 - INFO - integrating rxn: rxn00420_c0
2026-01-13 19:32:52,528 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:52,529 - INFO - integrating rxn: rxn00048_c0
2026-01-13 19:32:52,529 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:52,530 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:32:52,531 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:32:52,532 - INFO - integrating rxn: rxn05035_c0
2026-01-13 19:32:52,532 - INFO - Objective with gapfill database:137.21706849317314; min objective:0.01
2026-01-13 19:32:52,532 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:52,533 - INFO - integrating rxn: rxn00791_c0
2026-01-13 19:32:52,534 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:52,535 - INFO - integrating rxn: rxn00490_c0
2026-01-13 19:32:52,536 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:52,536 - INFO - integrating rxn: rxn00691_c0
2026-01-13 19:32:52,538 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:52,538 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:32:52,539 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:52,539 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:32:52,541 - INFO - integrating rxn: rxn00952_c0
2026-01-13 19:32:52,541 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:52,542 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:32:52,543 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:52,544 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:32:52,544 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:52,545 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:32:52,546 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:52,547 - INFO - integrating rxn: rxn00903_c0
2026-01-13 19:32:52,547 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:52,548 - INFO - integrating rxn: rxn00806_c0
2026-01-13 19:32:52,549 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:52,550 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:32:52,550 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:52,552 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:32:52,552 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:52,553 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:32:52,553 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:52,555 - INFO - integrating rxn: rxn02473_c0
2026-01-13 19:32:52,555 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:52,556 - INFO - integrating rxn: rxn01434_c0
2026-01-13 19:32:52,556 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:52,558 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:32:52,558 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:52,559 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:32:52,560 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:52,561 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:32:52,562 - INFO - integrating rxn: rxn01964_c0
2026-01-13 19:32:52,562 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:52,563 - INFO - integrating rxn: rxn02186_c0
2026-01-13 19:32:52,564 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:52,565 - INFO - integrating rxn: rxn01019_c0
2026-01-13 19:32:52,566 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:52,566 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:32:52,567 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:52,568 - INFO - integrating rxn: rxn03194_c0
2026-01-13 19:32:52,569 - INFO - integrating rxn: rxn39982_c0
2026-01-13 19:32:52,569 - INFO - integrating rxn: rxn21857_c0
2026-01-13 19:32:52,570 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:32:52,571 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:32:52,572 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:52,572 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:52,574 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:32:52,574 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:52,575 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:32:52,575 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:52,577 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:32:52,577 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:52,578 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:32:52,579 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:52,579 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:32:52,580 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:52,581 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:32:52,582 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:52,582 - INFO - integrating rxn: rxn21861_c0
2026-01-13 19:32:52,583 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:32:52,584 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:32:52,585 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:52,585 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:32:52,586 - INFO - integrating rxn: rxn40142_c0
2026-01-13 19:32:52,587 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:32:52,587 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:32:52,588 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:32:52,589 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:32:52,589 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:32:52,591 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:32:52,591 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:32:52,592 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:32:52,593 - INFO - integrating rxn: rxn19764_c0

c0

2026-01-13 19:32:52,889 - INFO - rxn04551_c0> not needed:4.607630780262862
2026-01-13 19:32:52,895 - INFO - AuxoMedia/bio1:rxn25042_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,897 - INFO - AuxoMedia/bio1:rxn19766_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,899 - INFO - AuxoMedia/bio1:rxn19764_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,901 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,903 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,904 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,910 - INFO - rxn16671_c0> not needed:4.60763078026285
2026-01-13 19:32:52,913 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,918 - INFO - rxn15060_c0> not needed:4.607630780262854
2026-01-13 19:32:52,920 - INFO - rxn29919_c0> not needed:4.607630780262854
2026-01-13 19:32:52,921 - INFO - rxn15064_c0> not needed:4.607630780262854
2026-01-13 19:32:52,923 - INFO - rxn10095_c0> not needed:3.9126200415698054
2026-01-13 19:32:52,927 - INFO - AuxoMedia/bio1:rxn18575_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,929 - INFO - AuxoMedia/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,934 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,936 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,938 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,940 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:52,944 - INFO - rxn08921_c0> not needed:3.9126200415698102
2026-01-13 19:32:52,946 - INFO - rxn29260_c0> not needed:3.9126200415698102
2026-01-13 19:32:52,947 - INFO - rxn19006_c0> not needed:3.9126200415698102
2026-01-13 19:32:52,948 - INFO - rxn19007_c0> not needed:3.9126200415698102
2026-01-13 19:32:52,950 - INFO - rxn14423_c0> not needed:3.9126200415698102
2026-01-13 19:32:52,951 - INFO - rxn10154_c0> not needed:3.9126200415698102
2026-01-13 19:32:52,953 - INFO - rxn10042_c0> not needed:3.9126200415698102
2026-01-13 19:32:52,956 - INFO - Unneeded: [['rxn21635_c0', '>', 'new', 100, None], ['rxn16218_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn39982_c0', '>', 'new', 100, None], ['rxn14424_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn15166_c0', '>', 'new', 100, None], ['rxn04551_c0', '>', 'new', 100, None], ['rxn16671_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn10095_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn19006_c0', '>', 'new', 100, None], ['rxn19007_c0', '>', 'new', 100, None], ['rxn14423_c0', '>', 'new', 100, None], ['rxn10154_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None]]
2026-01-13 19:32:52,965 - INFO - cpd00263 not found in model!
2026-01-13 19:32:52,965 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:52,967 - INFO - cpd00215 not found in model!
2026-01-13 19:32:52,967 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:52,970 - INFO - Growth: 4.642292975115159 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00099_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn00599_c0': '>', 'rxn11702_c0': '>', 'rxn03439_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn39982_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn15166_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16671_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn18575_c0': '>', 'rxn08233_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn19006_c0': '>', 'rxn19007_c0': '>', 'rxn14423_c0': '>', 'rxn10154_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:52,973 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn18575_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:32:52,974 - INFO -     Added 96 reactions
2026-01-13 19:32:52,974 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:53,182 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00065_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn08710_c0': '>', 'rxn01739_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn04704_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn09657_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn05663_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn00599_c0': '>', 'rxn03084_c0': '>', 'rxn00346_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn00623_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn15395_c0': '>', 'rxn00644_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16671_c0': '>', 'rxn14070_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn27266_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn11382_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:53,185 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:53,187 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:53,188 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:53,190 - INFO - integrating rxn: EX_cpd00065_e0
2026-01-13 19:32:53,192 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:53,194 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:32:53,195 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:53,197 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:32:53,198 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:53,199 - INFO - integrating rxn: rxn03030_c0
2026-01-13 19:32:53,201 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:53,203 - INFO - integrating rxn: rxn01739_c0
2026-01-13 19:32:53,203 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00048_e0': '<', 'EX_cpd15378_e0': '>', 'rxn00359_c0': '<', 'rxn02504_c0': '>', 'rxn00544_c0': '>', 'rxn00898_c0': '>', 'rxn02305_c0': '>', 'rxn00902_c0': '<', 'rxn03436_c0': '>', 'rxn13022_c0': '>', 'rxn00802_c0': '>', 'rxn00300_c0': '>', 'rxn01280_c0': '<', 'rxn00324_c0': '>', 'rxn03435_c0': '<', 'rxn00010_c0': '>', 'rxn12376_c0': '<', 'rxn01539_c0': '<', 'rxn03437_c0': '>', 'rxn02508_c0': '>', 'rxn00048_c0': '>', 'rxn00726_c0': '>', 'rxn03108_c0': '>', 'rxn02200_c0': '>', 'rxn00791_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn03841_c0': '>', 'rxn01257_c0': '>', 'rxn05651_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn01434_c0': '>', 'rxn00623_c0': '<', 'rxn02507_c0': '>', 'rxn01964_c0': '>', 'rxn02186_c0': '>', 'rxn01019_c0': '>', 'rxn01603_c0': '>', 'rxn03194_c0': '>', 'rxn21857_c0': '>', 'rxn16573_c0': '>', 'rxn21863_c0': '>', 'rxn22816_c0': '>', 'rxn21862_c0': '>', 'rxn11279_c0': '>', 'rxn21859_c0': '>', 'rxn10504_c0': '>', 'rxn47768_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn21858_c0': '>', 'rxn20834_c0': '>', 'rxn21861_c0': '>', 'rxn40439_c0': '>', 'rxn17731_c0': '>', 'rxn21860_c0': '>', 'rxn15395_c0': '>', 'rxn15091_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn16114_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn42332_c0': '>', 'rxn47493_c0': '>', 'rxn10121_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:53,204 - INFO - integrating rxn: rxn00060_c0
2026-01-13 19:32:53,206 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:53,206 - INFO - integrating rxn: EX_cpd00048_e0
2026-01-13 19:32:53,207 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:53,208 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:32:53,209 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:53,210 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:32:53,211 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:53,212 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:32:53,212 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:32:53,213 - INFO - integrating rxn: rxn00544_c0
2026-01-13 19:32:53,214 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:53,215 - INFO - integrating rxn: rxn00898_c0
2026-01-13 19:32:53,216 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:53,216 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:32:53,217 - INFO - integrating rxn: rxn00029_c0
2026-01-13 19:32:53,218 - INFO - integrating rxn: rxn00902_c0
2026-01-13 19:32:53,219 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:53,220 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:32:53,221 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:53,221 - INFO - integrating rxn: rxn13022_c0
2026-01-13 19:32:53,223 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:53,223 - INFO - integrating rxn: rxn00802_c0
2026-01-13 19:32:53,224 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:53,224 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:32:53,225 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:53,226 - INFO - integrating rxn: rxn01280_c0
2026-01-13 19:32:53,226 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd10515_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn00649_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn00625_c0': '>', 'rxn10030_c0': '>', 'rxn05957_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01501_c0': '<', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03917_c0': '>', 'rxn00440_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn00782_c0': '<', 'rxn11702_c0': '>', 'rxn00551_c0': '>', 'rxn03439_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn11162_c0': '>', 'rxn15395_c0': '>', 'rxn15091_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn45106_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn16341_c0': '>', 'rxn46249_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn13301_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn09390_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:53,227 - INFO - integrating rxn: rxn04704_c0
2026-01-13 19:32:53,227 - INFO - integrating rxn: rxn00324_c0
2026-01-13 19:32:53,228 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:53,229 - INFO - integrating rxn: rxn03435_c0
2026-01-13 19:32:53,230 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:53,230 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:53,230 - INFO - integrating rxn: rxn00010_c0
2026-01-13 19:32:53,232 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:53,232 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:32:53,232 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:53,233 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:53,234 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:32:53,234 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:53,235 - INFO - integrating rxn: rxn08528_c0
2026-01-13 19:32:53,235 - INFO - integrating rxn: rxn03437_c0
2026-01-13 19:32:53,236 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:53,236 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:53,237 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:32:53,237 - INFO - integrating rxn: EX_cpd10515_e0
2026-01-13 19:32:53,238 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:53,238 - INFO - integrating rxn: rxn00048_c0
2026-01-13 19:32:53,239 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:53,240 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:32:53,240 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:53,241 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:53,242 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:32:53,242 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:32:53,243 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:53,243 - INFO - integrating rxn: rxn02200_c0
2026-01-13 19:32:53,244 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:32:53,245 - INFO - integrating rxn: rxn00791_c0
2026-01-13 19:32:53,245 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:32:53,246 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:53,247 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:32:53,247 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:53,247 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:53,248 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:32:53,248 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:53,249 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:53,250 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:32:53,250 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:32:53,251 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:53,251 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:32:53,252 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:53,252 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:53,253 - INFO - integrating rxn: rxn05651_c0
2026-01-13 19:32:53,254 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:53,254 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:53,255 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:32:53,255 - INFO - integrating rxn: rxn00649_c0
2026-01-13 19:32:53,256 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:53,256 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:32:53,257 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:53,257 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:32:53,258 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:32:53,258 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:53,259 - INFO - integrating rxn: rxn05663_c0
2026-01-13 19:32:53,259 - INFO - integrating rxn: rxn01434_c0
2026-01-13 19:32:53,260 - INFO - integrating rxn: rxn09202_c0
2026-01-13 19:32:53,260 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:53,261 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:32:53,261 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:53,262 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:53,263 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:32:53,263 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:53,264 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:53,264 - INFO - integrating rxn: rxn01964_c0
2026-01-13 19:32:53,265 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:53,265 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:53,265 - INFO - integrating rxn: rxn02186_c0
2026-01-13 19:32:53,266 - INFO - integrating rxn: rxn00625_c0
2026-01-13 19:32:53,267 - INFO - integrating rxn: rxn01019_c0
2026-01-13 19:32:53,267 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:53,268 - INFO - integrating rxn: rxn10030_c0
2026-01-13 19:32:53,268 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:32:53,269 - INFO - integrating rxn: rxn00346_c0
2026-01-13 19:32:53,269 - INFO - integrating rxn: rxn05957_c0
2026-01-13 19:32:53,270 - INFO - integrating rxn: rxn03194_c0
2026-01-13 19:32:53,271 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:53,271 - INFO - integrating rxn: rxn21857_c0
2026-01-13 19:32:53,272 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:53,272 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:53,273 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:53,273 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:32:53,274 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:53,275 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:53,275 - INFO - integrating rxn: rxn21863_c0
2026-01-13 19:32:53,276 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:53,276 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:53,276 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:32:53,277 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:53,277 - INFO - integrating rxn: rxn00830_c0
2026-01-13 19:32:53,278 - INFO - integrating rxn: rxn21862_c0
2026-01-13 19:32:53,278 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:53,279 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:53,279 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:32:53,280 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:53,281 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:53,281 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:32:53,282 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:53,282 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:53,283 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:32:53,283 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:53,284 - INFO - integrating rxn: rxn01501_c0
2026-01-13 19:32:53,284 - INFO - integrating rxn: rxn47768_c0
2026-01-13 19:32:53,284 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:53,285 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:53,285 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:32:53,286 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:32:53,287 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:53,287 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:32:53,287 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:53,288 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:32:53,289 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:53,289 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:53,290 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:32:53,290 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:53,291 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:32:53,291 - INFO - integrating rxn: rxn21858_c0
2026-01-13 19:32:53,292 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:53,292 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:53,292 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:32:53,293 - INFO - integrating rxn: rxn08618_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:53,421 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:32:53,422 - INFO - integrating rxn: rxn03511_c0

2026-01-13 19:32:53,422 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,423 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,423 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:32:53,424 - INFO - PyruateMinimalAnaerobic/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,424 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:53,425 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,425 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:53,425 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:32:53,425 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,426 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,427 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:32:53,427 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:53,427 - INFO - PyruateMinimalAnaerobic/bio1:rxn10954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,428 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,429 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,429 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:32:53,429 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:53,429 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,430 - INFO - PyruateMinimalAnaerobic/bio1:rxn02402_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,430 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:32:53,431 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:32:53,431 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn00649_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00625_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn05957_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00440_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00782_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00551_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn11162_c0', '>', 'new'], ['rxn15395_c0', '>', 'new'], ['rxn15091_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn45106_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn13301_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:53,431 - INFO - PyruateMinimalAnaerobic/bio1:rxn05347_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,431 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,432 - INFO - integrating rxn: rxn45276_c0
2026-01-13 19:32:53,433 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,433 - INFO - AuxoMedia/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,434 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:53,434 - INFO - PyruateMinimalAnaerobic/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,435 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,435 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,435 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:32:53,436 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,437 - INFO - AuxoMedia/bio1:rxn01739_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,437 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:53,437 - INFO - PyruateMinimalAnaerobic/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,438 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:32:53,438 - INFO - PyruateMinimalAnaerobic/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,438 - INFO - AuxoMedia/bio1:rxn00060_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,440 - INFO - PyruateMinimalAnaerobic/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,440 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:53,440 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,441 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,442 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:53,442 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,442 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,443 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,443 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:53,444 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,444 - INFO - PyruateMinimalAnaerobic/bio1:rxn05342_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,445 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:53,445 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,445 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,446 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:53,446 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,448 - INFO - PyruateMinimalAnaerobic/bio1:rxn05029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,448 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:32:53,448 - INFO - AuxoMedia/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,449 - INFO - PyruateMinimalAnaerobic/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,449 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:32:53,450 - INFO - PyruateMinimalAnaerobic/bio1:rxn05315_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,450 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,451 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:53,451 - INFO - PyruateMinimalAnaerobic/bio1:rxn05663_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,452 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,452 - INFO - PyruateMinimalAnaerobic/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,452 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:53,453 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,453 - INFO - AuxoMedia/bio1:rxn00029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,454 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:53,454 - INFO - PyruateMinimalAnaerobic/bio1:rxn02304_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,455 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,455 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:32:53,455 - INFO - PyruateMinimalAnaerobic/bio1:rxn05618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,457 - INFO - PyruateMinimalAnaerobic/bio1:rxn08241_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,457 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,457 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:32:53,458 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,458 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:53,459 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,459 - INFO - PyruateMinimalAnaerobic/bio1:rxn08088_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,460 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,460 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,460 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:53,461 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,462 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:53,462 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,463 - INFO - PyruateMinimalAnaerobic/bio1:rxn09422_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,464 - INFO - AuxoMedia/bio1:rxn04704_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,464 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:32:53,464 - INFO - PyruateMinimalAnaerobic/bio1:rxn00533_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,465 - INFO - PyruateMinimalAnaerobic/bio1:rxn01512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,465 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:32:53,465 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,466 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,467 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:32:53,467 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,468 - INFO - PyruateMinimalAnaerobic/bio1:rxn04113_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,468 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:53,469 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,469 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,470 - INFO - integrating rxn: rxn28338_c0
2026-01-13 19:32:53,470 - INFO - PyruateMinimalAnaerobic/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,470 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,471 - INFO - PyruateMinimalAnaerobic/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,472 - INFO - integrating rxn: rxn01736_c0
2026-01-13 19:32:53,472 - INFO - AuxoMedia/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,472 - INFO - PyruateMinimalAnaerobic/bio1:rxn08130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,473 - INFO - integrating rxn: rxn00644_c0
2026-01-13 19:32:53,473 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,474 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,475 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:32:53,475 - INFO - PyruateMinimalAnaerobic/bio1:rxn05117_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,476 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,476 - INFO - PyruateMinimalAnaerobic/bio1:rxn05355_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,476 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:32:53,476 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,477 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,477 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,478 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:53,478 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,478 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,479 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,479 - INFO - PyruateMinimalAnaerobic/bio1:rxn00346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,479 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:53,480 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,481 - INFO - PyruateMinimalAnaerobic/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,481 - INFO - integrating rxn: rxn17394_c0
2026-01-13 19:32:53,481 - INFO - AuxoMedia/bio1:rxn01539_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,482 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,482 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,483 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:53,483 - INFO - PyruateMinimalAnaerobic/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,483 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,484 - INFO - AuxoMedia/bio1:EX_cpd10515_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,484 - INFO - integrating rxn: rxn45106_c0
2026-01-13 19:32:53,484 - INFO - PyruateMinimalAnaerobic/bio1:rxn02003_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,485 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,485 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,486 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:53,486 - INFO - PyruateMinimalAnaerobic/bio1:rxn00130_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,487 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,487 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,487 - INFO - PyruateMinimalAnaerobic/bio1:rxn00912_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,487 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:53,488 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,489 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,489 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,489 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:53,490 - INFO - PyruateMinimalAnaerobic/bio1:rxn01602_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,490 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,491 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,491 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:32:53,491 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,492 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,492 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:53,492 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,493 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,494 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,494 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,494 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:32:53,494 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,495 - INFO - PyruateMinimalAnaerobic/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,495 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,495 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:53,496 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,496 - INFO - AuxoMedia/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,497 - INFO - AuxoMedia/bio1:rxn05663_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,497 - INFO - integrating rxn: rxn46249_c0
2026-01-13 19:32:53,497 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,498 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,499 - INFO - integrating rxn: rxn20472_c0
2026-01-13 19:32:53,499 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,499 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,500 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,500 - INFO - PyruateMinimalAnaerobic/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,500 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:53,501 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,501 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,502 - INFO - integrating rxn: rxn08989_c0
2026-01-13 19:32:53,502 - INFO - PyruateMinimalAnaerobic/bio1:rxn00347_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,502 - INFO - AuxoMedia/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,503 - INFO - rxn00649_c0> not needed:6.520367007191229
2026-01-13 19:32:53,503 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:32:53,504 - INFO - PyruateMinimalAnaerobic/bio1:rxn00467_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,504 - INFO - AuxoMedia/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,505 - INFO - PyruateMinimalAnaerobic/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,505 - INFO - integrating rxn: rxn20567_c0

c0

2026-01-13 19:32:53,561 - INFO - rxn12940_c0> not needed:1.4762102558566803

2026-01-13 19:32:53,562 - INFO - rxn12929_c0> not needed:1.4762102558566803
2026-01-13 19:32:53,563 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,564 - INFO - rxn12938_c0> not needed:1.4762102558566803
2026-01-13 19:32:53,565 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,565 - INFO - rxn12927_c0> not needed:1.4762102558566803
2026-01-13 19:32:53,566 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,566 - INFO - rxn12921_c0> not needed:1.4762102558566803
2026-01-13 19:32:53,568 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,570 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,571 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,571 - INFO - AuxoMedia/bio1:rxn00440_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,573 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,575 - INFO - rxn12942_c0> not needed:1.4762102558566785
2026-01-13 19:32:53,575 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,576 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,577 - INFO - AuxoMedia/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,578 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,578 - INFO - AuxoMedia/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,579 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,579 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,580 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,581 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,581 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,582 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,582 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,583 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,583 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,584 - INFO - AuxoMedia/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,585 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,586 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,588 - INFO - rxn00782_c0< not needed:6.520367007191231
2026-01-13 19:32:53,588 - INFO - rxn11251_c0> not needed:1.4762102558566623
2026-01-13 19:32:53,588 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,589 - INFO - rxn15167_c0> not needed:1.4762102558566632
2026-01-13 19:32:53,590 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,590 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,591 - INFO - AuxoMedia/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,592 - INFO - AuxoMedia/bio1:rxn00551_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,593 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,594 - INFO - AuxoMedia/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,595 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,596 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,597 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,597 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,598 - INFO - AuxoMedia/bio1:rxn19346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,598 - INFO - AuxoMedia/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,599 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,600 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,601 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,602 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,602 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,603 - INFO - AuxoMedia/bio1:rxn00340_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,604 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,604 - INFO - AuxoMedia/bio1:rxn40142_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,605 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,605 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,607 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,607 - INFO - rxn15395_c0> not needed:1.476210255856668
2026-01-13 19:32:53,607 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,608 - INFO - rxn00644_c0> not needed:1.476210255856682
2026-01-13 19:32:53,609 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:2.4755294822836146e-12 with min obj:0.01
2026-01-13 19:32:53,609 - INFO - AuxoMedia/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,609 - INFO - rxn25042_c0> not needed:1.476210255856682
2026-01-13 19:32:53,610 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,611 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,611 - INFO - rxn19766_c0> not needed:1.476210255856682
2026-01-13 19:32:53,612 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,612 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,613 - INFO - rxn19764_c0> not needed:1.476210255856682
2026-01-13 19:32:53,614 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,614 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,615 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,615 - INFO - AuxoMedia/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,616 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,616 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,617 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,618 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,618 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,618 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,619 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,620 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,621 - INFO - rxn16671_c0> not needed:1.4762102558566748
2026-01-13 19:32:53,621 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,623 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,624 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,624 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,626 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,628 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,629 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,630 - INFO - AuxoMedia/bio1:rxn11285_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,631 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,632 - INFO - AuxoMedia/bio1:rxn20508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,633 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,633 - INFO - rxn11274_c0> not needed:6.520367007191165
2026-01-13 19:32:53,634 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,635 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,636 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,636 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,637 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,638 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,639 - INFO - rxn12932_c0> not needed:6.5203670071912425
2026-01-13 19:32:53,639 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,640 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,642 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,642 - INFO - rxn12940_c0> not needed:6.520367007191175
2026-01-13 19:32:53,643 - INFO - rxn27266_c0> not needed:1.4762102558566745
2026-01-13 19:32:53,643 - INFO - AuxoMedia/bio1:rxn01313_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,644 - INFO - rxn12939_c0> not needed:6.5203670071912345
2026-01-13 19:32:53,645 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,645 - INFO - rxn12929_c0> not needed:6.520367007191175
2026-01-13 19:32:53,646 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,647 - INFO - AuxoMedia/bio1:rxn05029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,647 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,648 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,648 - INFO - rxn12938_c0> not needed:6.520367007191191
2026-01-13 19:32:53,650 - INFO - rxn12927_c0> not needed:6.520367007191207
2026-01-13 19:32:53,650 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,651 - INFO - rxn08921_c0> not needed:1.4762102558566723
2026-01-13 19:32:53,651 - INFO - rxn12921_c0> not needed:6.520367007191207
2026-01-13 19:32:53,652 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,652 - INFO - rxn12928_c0> not needed:6.520367007191207
2026-01-13 19:32:53,653 - INFO - rxn29260_c0> not needed:1.476210255856678
2026-01-13 19:32:53,654 - INFO - rxn12944_c0> not needed:6.520367007191207
2026-01-13 19:32:53,654 - INFO - rxn14423_c0> not needed:1.476210255856667
2026-01-13 19:32:53,654 - INFO - AuxoMedia/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,655 - INFO - rxn12994_c0> not needed:6.520367007191207
2026-01-13 19:32:53,655 - INFO - rxn11382_c0> not needed:1.476210255856667
2026-01-13 19:32:53,656 - INFO - AuxoMedia/bio1:rxn00362_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,658 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,658 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,660 - INFO - AuxoMedia/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,662 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,663 - INFO - rxn12942_c0> not needed:6.5203670071912345
2026-01-13 19:32:53,664 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:53,666 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,666 - INFO - AuxoMedia/bio1:rxn03075_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,667 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,667 - INFO - rxn10042_c0> not needed:1.4762102558566712
2026-01-13 19:32:53,668 - INFO - AuxoMedia/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,669 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,670 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,671 - INFO - AuxoMedia/bio1:rxn19346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,671 - INFO - Unneeded: [['rxn00623_c0', '<', 'new', -100, None], ['rxn14424_c0', '>', 'new', 100, None], ['rxn11274_c0', '>', 'new', 100, None], ['rxn12932_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn12938_c0', '>', 'new', 100, None], ['rxn12927_c0', '>', 'new', 100, None], ['rxn12921_c0', '>', 'new', 100, None], ['rxn12942_c0', '>', 'new', 100, None], ['rxn11251_c0', '>', 'new', 100, None], ['rxn15167_c0', '>', 'new', 100, None], ['rxn15395_c0', '>', 'new', 100, None], ['rxn00644_c0', '>', 'new', 100, None], ['rxn25042_c0', '>', 'new', 100, None], ['rxn19766_c0', '>', 'new', 100, None], ['rxn19764_c0', '>', 'new', 100, None], ['rxn16671_c0', '>', 'new', 100, None], ['rxn27266_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn14423_c0', '>', 'new', 100, None], ['rxn11382_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None]]
2026-01-13 19:32:53,672 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,673 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,675 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,675 - INFO - rxn11162_c0> not needed:6.520367007191203
2026-01-13 19:32:53,677 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,678 - INFO - rxn15395_c0> not needed:3.317343549807467
2026-01-13 19:32:53,678 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,680 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,680 - INFO - AuxoMedia/bio1:rxn15091_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,681 - INFO - Growth: 1.482347395089395 AuxoMedia

Adding gapfilling

2026-01-13 19:32:53,682 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01

 {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00065_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn08710_c0': '>', 'rxn01739_c0': '>', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn04704_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn09657_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn05663_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn00599_c0': '>', 'rxn03084_c0': '>', 'rxn00346_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn00623_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn15395_c0': '>', 'rxn00644_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16671_c0': '>', 'rxn14070_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn27266_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn11382_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:53,684 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01

2026-01-13 19:32:53,685 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:32:53,685 - INFO -     Added 88 reactions
2026-01-13 19:32:53,685 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,686 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:53,688 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,689 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,691 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,693 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,693 - INFO - rxn25042_c0> not needed:1.7632605306715456
2026-01-13 19:32:53,695 - INFO - rxn19766_c0> not needed:1.7632605306715456
2026-01-13 19:32:53,696 - INFO - rxn19764_c0> not needed:1.7632605306715456
2026-01-13 19:32:53,698 - INFO - rxn16218_c0> not needed:6.951448261645768
2026-01-13 19:32:53,700 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,701 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,701 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:53,703 - INFO - AuxoMedia/bio1:rxn17394_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,705 - INFO - rxn45276_c0> not needed:6.951448261645777
2026-01-13 19:32:53,705 - INFO - rxn45106_c0> not needed:1.7632605306714562
2026-01-13 19:32:53,706 - INFO - rxn16217_c0> not needed:6.951448261645732
2026-01-13 19:32:53,708 - INFO - AuxoMedia/bio1:rxn11285_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,709 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,711 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,712 - INFO - rxn10095_c0> not needed:1.7632605306713074
2026-01-13 19:32:53,714 - INFO - rxn08233_c0> not needed:1.7632605306716609
2026-01-13 19:32:53,715 - INFO - rxn20508_c0> not needed:1.7632605306716609
2026-01-13 19:32:53,715 - INFO - rxn12932_c0> not needed:6.951448261645783
2026-01-13 19:32:53,718 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,719 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,721 - INFO - rxn12940_c0> not needed:6.951448261645717
2026-01-13 19:32:53,721 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,722 - INFO - rxn12939_c0> not needed:6.951448261645645
2026-01-13 19:32:53,723 - INFO - AuxoMedia/bio1:rxn16341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,724 - INFO - rxn12929_c0> not needed:6.951448261645645
2026-01-13 19:32:53,724 - INFO - AuxoMedia/bio1:rxn46249_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,725 - INFO - rxn25637_c0> not needed:6.951448261645645
2026-01-13 19:32:53,726 - INFO - AuxoMedia/bio1:rxn20472_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,727 - INFO - rxn18935_c0> not needed:6.951448261645645
2026-01-13 19:32:53,728 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,728 - INFO - rxn25743_c0> not needed:6.951448261645645
2026-01-13 19:32:53,729 - INFO - rxn12928_c0> not needed:6.951448261645645
2026-01-13 19:32:53,729 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,731 - INFO - rxn12944_c0> not needed:6.951448261645645
2026-01-13 19:32:53,732 - INFO - rxn12994_c0> not needed:6.951448261645645
2026-01-13 19:32:53,736 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,740 - INFO - rxn12942_c0> not needed:6.951448261645799
2026-01-13 19:32:53,742 - INFO - rxn13301_c0> not needed:1.763260530671526
2026-01-13 19:32:53,742 - INFO - rxn02485_c0> not needed:6.951448261645806
2026-01-13 19:32:53,744 - INFO - rxn29260_c0> not needed:1.7632605306714169
2026-01-13 19:32:53,745 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,747 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,748 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,749 - INFO - AuxoMedia/bio1:rxn08473_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,751 - INFO - rxn09390_c0> not needed:1.7632605306715374
2026-01-13 19:32:53,751 - INFO - rxn47267_c0> not needed:6.951448261645821
2026-01-13 19:32:53,752 - INFO - rxn41387_c0> not needed:6.951448261645827
2026-01-13 19:32:53,753 - INFO - AuxoMedia/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,754 - INFO - rxn15166_c0> not needed:6.951448261645827
2026-01-13 19:32:53,754 - INFO - AuxoMedia/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,756 - INFO - rxn19346_c0> not needed:6.820201921997263
2026-01-13 19:32:53,756 - INFO - AuxoMedia/bio1:rxn41263_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,758 - INFO - rxn28338_c0> not needed:6.820201921997279
2026-01-13 19:32:53,758 - INFO - AuxoMedia/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,760 - INFO - AuxoMedia/bio1:rxn01736_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,762 - INFO - AuxoMedia/bio1:rxn00644_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,766 - INFO - rxn19728_c0> not needed:6.8202019219972465
2026-01-13 19:32:53,768 - INFO - rxn20235_c0> not needed:6.820201921997262
2026-01-13 19:32:53,770 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,770 - INFO - Unneeded: [['rxn00649_c0', '>', 'new', 100, None], ['rxn05463_c0', '>', 'new', 100, None], ['rxn00782_c0', '<', 'new', -100, None], ['rxn11274_c0', '>', 'new', 100, None], ['rxn12932_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12939_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn12938_c0', '>', 'new', 100, None], ['rxn12927_c0', '>', 'new', 100, None], ['rxn12921_c0', '>', 'new', 100, None], ['rxn12928_c0', '>', 'new', 100, None], ['rxn12944_c0', '>', 'new', 100, None], ['rxn12994_c0', '>', 'new', 100, None], ['rxn12942_c0', '>', 'new', 100, None], ['rxn11162_c0', '>', 'new', 100, None], ['rxn15395_c0', '>', 'new', 100, None], ['rxn25042_c0', '>', 'new', 100, None], ['rxn19766_c0', '>', 'new', 100, None], ['rxn19764_c0', '>', 'new', 100, None], ['rxn45106_c0', '>', 'new', 100, None], ['rxn10095_c0', '>', 'new', 100, None], ['rxn08233_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn13301_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn09390_c0', '>', 'new', 100, None]]
2026-01-13 19:32:53,772 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,774 - INFO - AuxoMedia/bio1:rxn17394_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,776 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,781 - INFO - rxn45106_c0> not needed:6.820201921997228
2026-01-13 19:32:53,782 - INFO - rxn15060_c0> not needed:6.820201921997228
2026-01-13 19:32:53,784 - INFO - rxn29919_c0> not needed:6.820201921997228
2026-01-13 19:32:53,784 - INFO - Growth: 6.520367007191223 AuxoMedia
2026-01-13 19:32:53,785 - INFO - rxn10095_c0> not needed:6.820201921997228

Adding gapfilling

2026-01-13 19:32:53,786 - INFO - rxn20508_c0> not needed:6.820201921997228

{'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd10515_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn00649_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn00625_c0': '>', 'rxn10030_c0': '>', 'rxn05957_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01501_c0': '<', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03917_c0': '>', 'rxn00440_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn00782_c0': '<', 'rxn11702_c0': '>', 'rxn00551_c0': '>', 'rxn03439_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn11162_c0': '>', 'rxn15395_c0': '>', 'rxn15091_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn45106_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn16341_c0': '>', 'rxn46249_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn13301_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn09390_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:53,788 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00625_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn05957_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00440_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00551_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn15091_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:53,789 - INFO -     Added 100 reactions
2026-01-13 19:32:53,789 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:53,790 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,797 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,799 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,801 - INFO - AuxoMedia/bio1:rxn46249_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,803 - INFO - AuxoMedia/bio1:rxn20472_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,804 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:53,808 - INFO - rxn08989_c0> not needed:6.820201921997272
2026-01-13 19:32:53,810 - INFO - rxn09390_c0> not needed:6.8202019219972545
2026-01-13 19:32:53,812 - INFO - rxn20567_c0> not needed:6.8202019219972545
2026-01-13 19:32:53,813 - INFO - rxn23676_c0> not needed:6.8202019219972545
2026-01-13 19:32:53,814 - INFO - rxn10042_c0> not needed:6.8202019219972545
2026-01-13 19:32:53,816 - INFO - rxn43975_c0> not needed:6.8202019219972545
2026-01-13 19:32:53,817 - INFO - rxn42732_c0> not needed:6.8202019219972545
2026-01-13 19:32:53,818 - INFO - rxn41263_c0> not needed:6.8202019219972545
2026-01-13 19:32:53,820 - INFO - rxn20839_c0> not needed:6.8202019219972545
2026-01-13 19:32:53,824 - INFO - Unneeded: [['rxn16218_c0', '>', 'new', 100, None], ['rxn45276_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn12932_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12939_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn25637_c0', '>', 'new', 100, None], ['rxn18935_c0', '>', 'new', 100, None], ['rxn25743_c0', '>', 'new', 100, None], ['rxn12928_c0', '>', 'new', 100, None], ['rxn12944_c0', '>', 'new', 100, None], ['rxn12994_c0', '>', 'new', 100, None], ['rxn12942_c0', '>', 'new', 100, None], ['rxn02485_c0', '>', 'new', 100, None], ['rxn47267_c0', '>', 'new', 100, None], ['rxn41387_c0', '>', 'new', 100, None], ['rxn15166_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn28338_c0', '>', 'new', 100, None], ['rxn19728_c0', '>', 'new', 100, None], ['rxn20235_c0', '>', 'new', 100, None], ['rxn45106_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn10095_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn08989_c0', '>', 'new', 100, None], ['rxn09390_c0', '>', 'new', 100, None], ['rxn20567_c0', '>', 'new', 100, None], ['rxn23676_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None], ['rxn43975_c0', '>', 'new', 100, None], ['rxn42732_c0', '>', 'new', 100, None], ['rxn41263_c0', '>', 'new', 100, None], ['rxn20839_c0', '>', 'new', 100, None]]
2026-01-13 19:32:53,835 - INFO - Growth: 6.951448261645767 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn00340_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn01313_c0': '>', 'rxn03917_c0': '>', 'rxn05029_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn00834_c0': '>', 'rxn00362_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn03075_c0': '>', 'rxn00134_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn45276_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15166_c0': '>', 'rxn19346_c0': '>', 'rxn28338_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn14070_c0': '>', 'rxn45106_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn10095_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn46249_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn08989_c0': '>', 'rxn09390_c0': '>', 'rxn20567_c0': '>', 'rxn23676_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:53,838 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00340_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn01313_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00362_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:32:53,839 - INFO -     Added 86 reactions
2026-01-13 19:32:53,839 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:54,123 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd10515_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01501_c0': '<', 'rxn01505_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03150_c0': '>', 'rxn04784_c0': '>', 'rxn01537_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn01790_c0': '<', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn12930_c0': '>', 'rxn12939_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn45106_c0': '>', 'rxn16622_c0': '>', 'rxn15060_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn13301_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn20567_c0': '>', 'rxn23676_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:54,127 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:32:54,129 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:54,131 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:54,132 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:54,134 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:54,135 - INFO - integrating rxn: EX_cpd10515_e0
2026-01-13 19:32:54,137 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:54,139 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:54,141 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:54,142 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:32:54,144 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:54,145 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:54,147 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:54,149 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:54,150 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:54,151 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:54,153 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:54,155 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:54,156 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:54,158 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:54,159 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:54,161 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:54,162 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:54,164 - INFO - integrating rxn: rxn00830_c0
2026-01-13 19:32:54,165 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:54,167 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:54,169 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:54,171 - INFO - integrating rxn: rxn01501_c0
2026-01-13 19:32:54,172 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:54,174 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:54,175 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:54,177 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:54,178 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:54,179 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:54,181 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:32:54,182 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:54,184 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:54,185 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:54,187 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:54,188 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:54,190 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:54,191 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:54,193 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:54,194 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:54,196 - INFO - integrating rxn: rxn10094_c0
2026-01-13 19:32:54,197 - INFO - integrating rxn: rxn09657_c0
2026-01-13 19:32:54,199 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:54,200 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:32:54,202 - INFO - integrating rxn: rxn04784_c0
2026-01-13 19:32:54,203 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:32:54,204 - INFO - integrating rxn: rxn03087_c0
2026-01-13 19:32:54,206 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:54,207 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:54,208 - INFO - integrating rxn: rxn00704_c0
2026-01-13 19:32:54,210 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:32:54,211 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:32:54,213 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:54,214 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:54,216 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:54,217 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:54,219 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:32:54,220 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:54,222 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:54,223 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:54,224 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:32:54,226 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:54,227 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:32:54,229 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:54,230 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:54,231 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:54,233 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:54,235 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:54,237 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:32:54,239 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:32:54,240 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:32:54,242 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:32:54,243 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:32:54,245 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:54,246 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:54,248 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:54,249 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:32:54,250 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:54,252 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:54,253 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:54,255 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:32:54,257 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:54,259 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:32:54,260 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:32:54,262 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:32:54,263 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:54,265 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:54,266 - INFO - integrating rxn: rxn45106_c0
2026-01-13 19:32:54,268 - INFO - integrating rxn: rxn16622_c0
2026-01-13 19:32:54,269 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:54,271 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:32:54,272 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:54,274 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:32:54,275 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:54,277 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:54,278 - INFO - integrating rxn: rxn13301_c0
2026-01-13 19:32:54,279 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:54,281 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:32:54,283 - INFO - integrating rxn: rxn20567_c0
2026-01-13 19:32:54,284 - INFO - integrating rxn: rxn23676_c0
2026-01-13 19:32:54,286 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:32:54,287 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:32:54,289 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:32:54,290 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:32:54,292 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:32:54,293 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn04784_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn45106_c0', '>', 'new'], ['rxn16622_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn13301_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn20567_c0', '>', 'new'], ['rxn23676_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:54,348 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,350 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,352 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,354 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,356 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,358 - INFO - AuxoMedia/bio1:EX_cpd10515_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,360 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,363 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,365 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,367 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,369 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,371 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,372 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,374 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,376 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,377 - INFO - AuxoMedia/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,379 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,381 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,382 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,384 - INFO - AuxoMedia/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,386 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,388 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,390 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,391 - INFO - AuxoMedia/bio1:rxn00830_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,393 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,395 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,396 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,398 - INFO - AuxoMedia/bio1:rxn01501_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,400 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,401 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,403 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,405 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,407 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,408 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,410 - INFO - AuxoMedia/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,412 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,413 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,415 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,417 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,418 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,420 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,422 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,423 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,425 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,426 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,428 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,430 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,431 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,433 - INFO - AuxoMedia/bio1:rxn04784_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,435 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,436 - INFO - AuxoMedia/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:54,438 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,440 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:54,442 - INFO - AuxoMedia/bio1:rxn00704_c0< needed:0.0 with min obj:0.01

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd10515_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn00830_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01501_c0': '<', 'rxn01505_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03150_c0': '>', 'rxn04784_c0': '>', 'rxn01537_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn01790_c0': '<', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn12930_c0': '>', 'rxn12939_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn45106_c0': '>', 'rxn16622_c0': '>', 'rxn15060_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn13301_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn20567_c0': '>', 'rxn23676_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:54,610 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn04784_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:54,611 - INFO -     Added 88 reactions
2026-01-13 19:32:54,612 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:54,614 - INFO - Objective with gapfill database:137.21706849317414; min objective:0.01
2026-01-13 19:32:54,831 - INFO - Objective with gapfill database:137.21706849317295; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:55,245 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn02331_c0': '<', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn00834_c0': '>', 'rxn00599_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn00605_c0': '<', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn00138_c0': '>', 'rxn05464_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:55,249 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:55,251 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:55,253 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:55,255 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:55,257 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:32:55,258 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:55,260 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:55,262 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:55,264 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:55,266 - INFO - integrating rxn: rxn00060_c0
2026-01-13 19:32:55,268 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:55,270 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:55,271 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:55,273 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:55,275 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:55,277 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:55,278 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:55,280 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:55,281 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:55,283 - INFO - integrating rxn: rxn00029_c0
2026-01-13 19:32:55,285 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:55,287 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:55,289 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:55,291 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:55,292 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:55,294 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:55,296 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:55,298 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:55,299 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:55,301 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:55,302 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:55,304 - INFO - integrating rxn: rxn08528_c0
2026-01-13 19:32:55,306 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:55,307 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:55,309 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:32:55,310 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:32:55,312 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:55,313 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:55,315 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:55,317 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:55,318 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:55,319 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:55,321 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:55,323 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:55,324 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:32:55,326 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:55,327 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:55,329 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:55,330 - INFO - integrating rxn: rxn00834_c0
2026-01-13 19:32:55,332 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:55,334 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:32:55,336 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:55,337 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:32:55,339 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:55,340 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:55,342 - INFO - integrating rxn: rxn00605_c0
2026-01-13 19:32:55,343 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:55,345 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:32:55,346 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:55,347 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:32:55,349 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:55,351 - INFO - integrating rxn: rxn00138_c0
2026-01-13 19:32:55,352 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:55,353 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:32:55,355 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:32:55,356 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:32:55,358 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:32:55,359 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:32:55,361 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:32:55,362 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:32:55,364 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:32:55,366 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:32:55,367 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:32:55,369 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:32:55,370 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:32:55,371 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:32:55,373 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:32:55,374 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:32:55,377 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:32:55,378 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:32:55,379 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:32:55,381 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:32:55,383 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:32:55,385 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:32:55,386 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:32:55,388 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:32:55,389 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:32:55,391 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:32:55,392 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:32:55,394 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:32:55,395 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:32:55,397 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:32:55,398 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:32:55,399 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:32:55,401 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:32:55,402 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:32:55,404 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:32:55,405 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn00605_c0', '<', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new']]
2026-01-13 19:32:55,424 - INFO - cpd00263 not found in model!
2026-01-13 19:32:55,424 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:55,425 - INFO - cpd00215 not found in model!
2026-01-13 19:32:55,426 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:55,459 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,460 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,462 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,464 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,466 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,468 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,470 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,472 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,474 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,475 - INFO - AuxoMedia/bio1:rxn00060_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,477 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,479 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,481 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,482 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,487 - INFO - AuxoMedia/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,489 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,490 - INFO - AuxoMedia/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,492 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,493 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,495 - INFO - AuxoMedia/bio1:rxn00029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,496 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,496 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03917_c0': '>', 'rxn01213_c0': '>', 'rxn00858_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn14070_c0': '>', 'rxn45106_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn46249_c0': '>', 'rxn40040_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn29260_c0': '>', 'rxn19672_c0': '>', 'rxn08508_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:55,498 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,500 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,500 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:55,501 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,502 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:55,503 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,504 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:55,505 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,506 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:55,506 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,507 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:55,508 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,509 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:32:55,510 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,511 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:32:55,512 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,513 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:32:55,513 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,514 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:55,515 - INFO - AuxoMedia/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,516 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:55,517 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,518 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:55,519 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,520 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:55,521 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,522 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:55,522 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,523 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:32:55,524 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,525 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:55,526 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,527 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:55,528 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,529 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:55,529 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,530 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:55,531 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,532 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:55,533 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,534 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:55,535 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,535 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:55,537 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,537 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:55,539 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:55,540 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:55,542 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:55,542 - INFO - rxn02303_c0> not needed:5.606730787715915
2026-01-13 19:32:55,543 - INFO - integrating rxn: rxn05463_c0
2026-01-13 19:32:55,545 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:55,547 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:32:55,547 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,548 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:32:55,550 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,550 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:55,551 - INFO - integrating rxn: rxn10094_c0
2026-01-13 19:32:55,552 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,553 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:32:55,553 - INFO - AuxoMedia/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,554 - INFO - integrating rxn: rxn01213_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:55,661 - INFO - integrating rxn: rxn20839_c0

2026-01-13 19:32:55,661 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn00858_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn45106_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn08154_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn19672_c0', '>', 'new'], ['rxn08508_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:32:55,663 - INFO - rxn15060_c0> not needed:5.606730787715903
2026-01-13 19:32:55,664 - INFO - rxn29919_c0> not needed:5.606730787715887
2026-01-13 19:32:55,667 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,669 - INFO - AuxoMedia/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,670 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,672 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,674 - INFO - rxn08921_c0> not needed:5.606730787715903
2026-01-13 19:32:55,676 - INFO - rxn29260_c0> not needed:5.6067307877158665
2026-01-13 19:32:55,680 - INFO - Unneeded: [['rxn02303_c0', '>', 'new', 100, None], ['rxn16218_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn12938_c0', '>', 'new', 100, None], ['rxn12927_c0', '>', 'new', 100, None], ['rxn12921_c0', '>', 'new', 100, None], ['rxn25042_c0', '>', 'new', 100, None], ['rxn19766_c0', '>', 'new', 100, None], ['rxn19764_c0', '>', 'new', 100, None], ['rxn16114_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None]]
2026-01-13 19:32:55,689 - INFO - cpd00263 not found in model!
2026-01-13 19:32:55,689 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:32:55,690 - INFO - cpd00215 not found in model!
2026-01-13 19:32:55,691 - INFO - Media compound: cpd00215 not found in model.
2026-01-13 19:32:55,693 - INFO - Growth: 5.617122148157008 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn02331_c0': '<', 'rxn00060_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn00834_c0': '>', 'rxn00599_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn00605_c0': '<', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn00138_c0': '>', 'rxn05464_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:55,697 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn00605_c0', '<', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:32:55,697 - INFO -     Added 81 reactions
2026-01-13 19:32:55,698 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:55,715 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,717 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,719 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,721 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,723 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,725 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,727 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,728 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,730 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,732 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,734 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,735 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,737 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,739 - INFO - AuxoMedia/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,741 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,742 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,744 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,746 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,748 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,750 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,751 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,753 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,755 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,757 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,758 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,760 - INFO - AuxoMedia/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,762 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,764 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,765 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,767 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,769 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,770 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,772 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,774 - INFO - AuxoMedia/bio1:rxn00858_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,776 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,778 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,779 - INFO - AuxoMedia/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,781 - INFO - AuxoMedia/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,783 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,785 - INFO - AuxoMedia/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,787 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,788 - INFO - AuxoMedia/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,790 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,793 - INFO - AuxoMedia/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,795 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,796 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,798 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,801 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,802 - INFO - AuxoMedia/bio1:rxn01538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,804 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,806 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:32:55,808 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,810 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,812 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,814 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,819 - INFO - rxn16218_c0> not needed:12.59564777836632
2026-01-13 19:32:55,820 - INFO - rxn16217_c0> not needed:12.595647778366331
2026-01-13 19:32:55,823 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,827 - INFO - rxn12940_c0> not needed:12.5956477783664
2026-01-13 19:32:55,829 - INFO - rxn12939_c0> not needed:12.595647778366533
2026-01-13 19:32:55,831 - INFO - rxn12929_c0> not needed:12.595647778366411
2026-01-13 19:32:55,836 - INFO - rxn25637_c0> not needed:12.595647778366223
2026-01-13 19:32:55,837 - INFO - rxn18935_c0> not needed:12.59564777836644
2026-01-13 19:32:55,839 - INFO - rxn25638_c0> not needed:12.59564777836644
2026-01-13 19:32:55,840 - INFO - rxn12928_c0> not needed:12.59564777836644
2026-01-13 19:32:55,844 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,846 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,848 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,850 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,854 - INFO - rxn11251_c0> not needed:12.595647778366413
2026-01-13 19:32:55,857 - INFO - rxn15167_c0> not needed:12.363564253151091
2026-01-13 19:32:55,858 - INFO - rxn19346_c0> not needed:12.363564253151061
2026-01-13 19:32:55,863 - INFO - AuxoMedia/bio1:rxn01736_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,865 - INFO - AuxoMedia/bio1:rxn00644_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,867 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,869 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,870 - INFO - AuxoMedia/bio1:rxn17394_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,873 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,877 - INFO - rxn45106_c0> not needed:12.363564253151024
2026-01-13 19:32:55,879 - INFO - rxn29919_c0> not needed:12.363564253151152
2026-01-13 19:32:55,880 - INFO - rxn15064_c0> not needed:12.363564253151152
2026-01-13 19:32:55,883 - INFO - rxn08154_c0> not needed:12.363564253151061
2026-01-13 19:32:55,885 - INFO - rxn20508_c0> not needed:12.363564253151106
2026-01-13 19:32:55,887 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,892 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,894 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,896 - INFO - AuxoMedia/bio1:rxn46249_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,902 - INFO - rxn40040_c0> not needed:12.36356425315118
2026-01-13 19:32:55,907 - INFO - AuxoMedia/bio1:rxn20472_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,909 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:32:55,914 - INFO - rxn29260_c0> not needed:12.363564253151218
2026-01-13 19:32:55,916 - INFO - rxn19672_c0> not needed:12.363564253151123
2026-01-13 19:32:55,918 - INFO - rxn08508_c0> not needed:12.363564253151123
2026-01-13 19:32:55,919 - INFO - rxn10042_c0> not needed:12.363564253151123
2026-01-13 19:32:55,921 - INFO - rxn43975_c0> not needed:12.091897929755042
2026-01-13 19:32:55,922 - INFO - rxn42732_c0> not needed:12.091897929755156
2026-01-13 19:32:55,924 - INFO - rxn41263_c0> not needed:12.091897929755156
2026-01-13 19:32:55,925 - INFO - rxn20839_c0> not needed:12.091897929755156
2026-01-13 19:32:55,929 - INFO - Unneeded: [['rxn16218_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12939_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn25637_c0', '>', 'new', 100, None], ['rxn18935_c0', '>', 'new', 100, None], ['rxn25638_c0', '>', 'new', 100, None], ['rxn12928_c0', '>', 'new', 100, None], ['rxn11251_c0', '>', 'new', 100, None], ['rxn15167_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn45106_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn08154_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn40040_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn19672_c0', '>', 'new', 100, None], ['rxn08508_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None], ['rxn43975_c0', '>', 'new', 100, None], ['rxn42732_c0', '>', 'new', 100, None], ['rxn41263_c0', '>', 'new', 100, None], ['rxn20839_c0', '>', 'new', 100, None]]
2026-01-13 19:32:55,941 - INFO - Growth: 12.595647778366418 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn09177_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn04413_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03917_c0': '>', 'rxn01213_c0': '>', 'rxn00858_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03638_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn17394_c0': '>', 'rxn14070_c0': '>', 'rxn45106_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn46249_c0': '>', 'rxn40040_c0': '>', 'rxn20472_c0': '>', 'rxn40674_c0': '>', 'rxn29260_c0': '>', 'rxn19672_c0': '>', 'rxn08508_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:32:55,945 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn00858_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:32:55,946 - INFO -     Added 72 reactions
2026-01-13 19:32:55,947 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:32:56,036 - INFO - Objective with gapfill database:107.9893746995116; min objective:0.01
2026-01-13 19:32:56,742 - INFO - Objective with gapfill database:137.21706849317235; min objective:0.01
2026-01-13 19:32:58,591 - INFO - Objective with gapfill database:137.21706849317323; min objective:0.01
2026-01-13 19:32:58,632 - INFO - Objective with gapfill database:107.9893746995116; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:59,155 - INFO - Objective with gapfill database:137.21706849317235; min objective:0.01
2026-01-13 19:32:59,230 - INFO - Initial solution: {'reversed': {'rxn00693_c0': '>'}, 'new': {'EX_cpd00013_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd15378_e0': '>', 'rxn00973_c0': '>', 'rxn02320_c0': '<', 'rxn02504_c0': '>', 'rxn00898_c0': '>', 'rxn02305_c0': '>', 'rxn00796_c0': '>', 'rxn05733_c0': '>', 'rxn00902_c0': '<', 'rxn01306_c0': '<', 'rxn00789_c0': '<', 'rxn03436_c0': '>', 'rxn13022_c0': '>', 'rxn00802_c0': '>', 'rxn02160_c0': '>', 'rxn02159_c0': '>', 'rxn05466_c0': '>', 'rxn00300_c0': '>', 'rxn00272_c0': '<', 'rxn00336_c0': '<', 'rxn01301_c0': '<', 'rxn02835_c0': '>', 'rxn03435_c0': '<', 'rxn03175_c0': '>', 'rxn00285_c0': '>', 'rxn00863_c0': '>', 'rxn12376_c0': '<', 'rxn01303_c0': '>', 'rxn00069_c0': '>', 'rxn01539_c0': '<', 'rxn03437_c0': '>', 'rxn00505_c0': '>', 'rxn02508_c0': '>', 'rxn00048_c0': '>', 'rxn00265_c0': '<', 'rxn00726_c0': '>', 'rxn03108_c0': '>', 'rxn02200_c0': '>', 'rxn00791_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn00952_c0': '>', 'rxn03841_c0': '>', 'rxn04954_c0': '<', 'rxn05909_c0': '>', 'rxn01257_c0': '>', 'rxn00599_c0': '>', 'rxn03909_c0': '>', 'rxn05651_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn02473_c0': '>', 'rxn01434_c0': '>', 'rxn00623_c0': '<', 'rxn02507_c0': '>', 'rxn02186_c0': '>', 'rxn01019_c0': '>', 'rxn01603_c0': '>', 'rxn03194_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn16048_c0': '>', 'rxn16671_c0': '>', 'rxn15064_c0': '>', 'rxn37372_c0': '>', 'rxn10095_c0': '>', 'rxn16341_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn47493_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:59,234 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:32:59,235 - INFO - integrating rxn: EX_cpd00048_e0
2026-01-13 19:32:59,237 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:32:59,239 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:32:59,240 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:32:59,242 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:32:59,244 - INFO - integrating rxn: rxn00898_c0
2026-01-13 19:32:59,245 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:32:59,247 - INFO - integrating rxn: rxn00796_c0
2026-01-13 19:32:59,248 - INFO - integrating rxn: rxn05733_c0
2026-01-13 19:32:59,250 - INFO - integrating rxn: rxn00902_c0
2026-01-13 19:32:59,251 - INFO - integrating rxn: rxn01306_c0
2026-01-13 19:32:59,253 - INFO - integrating rxn: rxn00789_c0
2026-01-13 19:32:59,254 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:32:59,255 - INFO - integrating rxn: rxn13022_c0
2026-01-13 19:32:59,257 - INFO - integrating rxn: rxn00802_c0
2026-01-13 19:32:59,258 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:32:59,260 - INFO - integrating rxn: rxn02159_c0
2026-01-13 19:32:59,261 - INFO - integrating rxn: rxn05466_c0
2026-01-13 19:32:59,262 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:32:59,263 - INFO - integrating rxn: rxn00272_c0
2026-01-13 19:32:59,265 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:32:59,266 - INFO - integrating rxn: rxn01301_c0
2026-01-13 19:32:59,267 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:32:59,269 - INFO - integrating rxn: rxn03435_c0
2026-01-13 19:32:59,270 - INFO - integrating rxn: rxn03175_c0
2026-01-13 19:32:59,271 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:32:59,273 - INFO - integrating rxn: rxn00863_c0
2026-01-13 19:32:59,274 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:32:59,276 - INFO - integrating rxn: rxn01303_c0
2026-01-13 19:32:59,277 - INFO - integrating rxn: rxn00069_c0
2026-01-13 19:32:59,278 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:32:59,279 - INFO - integrating rxn: rxn03437_c0
2026-01-13 19:32:59,280 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:32:59,282 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:32:59,283 - INFO - integrating rxn: rxn00048_c0
2026-01-13 19:32:59,284 - INFO - integrating rxn: rxn00265_c0
2026-01-13 19:32:59,286 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:32:59,287 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:32:59,289 - INFO - integrating rxn: rxn02200_c0
2026-01-13 19:32:59,290 - INFO - integrating rxn: rxn00791_c0
2026-01-13 19:32:59,292 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:32:59,294 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:32:59,295 - INFO - integrating rxn: rxn00952_c0
2026-01-13 19:32:59,296 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:32:59,297 - INFO - integrating rxn: rxn04954_c0
2026-01-13 19:32:59,299 - INFO - integrating rxn: rxn05909_c0
2026-01-13 19:32:59,300 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:32:59,302 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:59,303 - INFO - integrating rxn: rxn03909_c0
2026-01-13 19:32:59,304 - INFO - integrating rxn: rxn05651_c0
2026-01-13 19:32:59,306 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:32:59,307 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:32:59,309 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:32:59,310 - INFO - integrating rxn: rxn02473_c0
2026-01-13 19:32:59,311 - INFO - integrating rxn: rxn01434_c0
2026-01-13 19:32:59,313 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:32:59,314 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:32:59,315 - INFO - integrating rxn: rxn02186_c0
2026-01-13 19:32:59,316 - INFO - integrating rxn: rxn01019_c0
2026-01-13 19:32:59,318 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:32:59,319 - INFO - integrating rxn: rxn03194_c0
2026-01-13 19:32:59,320 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:32:59,322 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:32:59,323 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:32:59,325 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:32:59,326 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:32:59,327 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:32:59,329 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:32:59,330 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:32:59,331 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:32:59,332 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:32:59,334 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:32:59,335 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:32:59,336 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:32:59,338 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:32:59,339 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:32:59,340 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:32:59,341 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:32:59,343 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:32:59,344 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:32:59,346 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:32:59,348 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:32:59,349 - INFO - integrating rxn: rxn16048_c0
2026-01-13 19:32:59,350 - INFO - integrating rxn: rxn16671_c0
2026-01-13 19:32:59,352 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:32:59,353 - INFO - integrating rxn: rxn37372_c0
2026-01-13 19:32:59,354 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:32:59,356 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:32:59,357 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:32:59,358 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:32:59,360 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:32:59,361 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:32:59,362 - INFO - integrating rxn: rxn00693_c0
2026-01-13 19:32:59,363 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00205_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00161_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03408_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00710_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn05300_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01974_c0', '>', 'new'], ['rxn00762_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn01362_c0', '<', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn01465_c0', '<', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn01637_c0', '<', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn00656_c0', '>', 'new'], ['rxn01629_c0', '<', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn00790_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn05303_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn11676_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn00527_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn01917_c0', '>', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn03147_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn02895_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00283_c0', '>', 'new'], ['rxn01018_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01069_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn02285_c0', '<', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn01361_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn00260_c0', '<', 'new'], ['rxn00461_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00502_c0', '<', 'new'], ['rxn02937_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00693_c0', '<', 'new'], ['rxn01101_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn00077_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00851_c0', '>', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn05596_c0', '<', 'new'], ['rxn03904_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn10199_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03164_c0', '>', 'new'], ['rxn00929_c0', '<', 'new'], ['rxn03004_c0', '>', 'new'], ['rxn02465_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn00542_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn06591_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn02914_c0', '<', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn02246_c0', '<', 'new'], ['rxn00493_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00030_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00065_e0', 'EX_cpd00205_e0', 'EX_cpd00084_e0', 'EX_cpd00149_e0', 'EX_cpd00063_e0', 'EX_cpd00161_e0', 'EX_cpd00099_e0', 'EX_cpd10515_e0', 'EX_cpd00051_e0', 'EX_cpd00104_e0', 'rxn08709_c0', 'rxn03408_c0', 'rxn02000_c0', 'rxn03086_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn03030_c0', 'rxn02988_c0', 'rxn01117_c0', 'rxn00710_c0', 'rxn00470_c0', 'rxn08710_c0', 'rxn05300_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn01974_c0', 'rxn00762_c0', 'rxn00060_c0', 'rxn00100_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn09202_c0', 'rxn05514_c0', 'rxn01362_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn05229_c0', 'rxn02404_c0', 'rxn01465_c0', 'rxn10204_c0', 'rxn01637_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn00029_c0', 'rxn02774_c0', 'rxn01675_c0', 'rxn03536_c0', 'rxn00656_c0', 'rxn01629_c0', 'rxn00503_c0', 'rxn00790_c0', 'rxn00237_c0', 'rxn03919_c0', 'rxn09210_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn05303_c0', 'rxn03159_c0', 'rxn03397_c0', 'rxn11703_c0', 'rxn01300_c0', 'rxn11676_c0', 'rxn06848_c0', 'rxn00527_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn05119_c0', 'rxn01917_c0', 'rxn02011_c0', 'rxn08528_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05237_c0', 'rxn03147_c0', 'rxn08711_c0', 'rxn02402_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn02895_c0', 'rxn00420_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn00283_c0', 'rxn01018_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn01069_c0', 'rxn03150_c0', 'rxn05029_c0', 'rxn02285_c0', 'rxn02303_c0', 'rxn05663_c0', 'rxn03538_c0', 'rxn01213_c0', 'rxn02304_c0', 'rxn01361_c0', 'rxn05618_c0', 'rxn08241_c0', 'rxn00260_c0', 'rxn00461_c0', 'rxn03136_c0', 'rxn00502_c0', 'rxn02937_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn01512_c0', 'rxn06865_c0', 'rxn00834_c0', 'rxn08130_c0', 'rxn11702_c0', 'rxn00693_c0', 'rxn01101_c0', 'rxn03084_c0', 'rxn03439_c0', 'rxn01790_c0', 'rxn00077_c0', 'rxn03638_c0', 'rxn02897_c0', 'rxn02056_c0', 'rxn00851_c0', 'rxn00141_c0', 'rxn02003_c0', 'rxn00130_c0', 'rxn00912_c0', 'rxn00122_c0', 'rxn05223_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn05596_c0', 'rxn03904_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn10199_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn03164_c0', 'rxn00929_c0', 'rxn03004_c0', 'rxn02465_c0', 'rxn03130_c0', 'rxn00542_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn06591_c0', 'rxn03182_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn02914_c0', 'rxn00117_c0', 'rxn02246_c0', 'rxn00493_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn16218_c0', 'rxn15949_c0', 'rxn16217_c0', 'rxn15947_c0', 'rxn14424_c0', 'rxn11274_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn11251_c0', 'rxn47267_c0', 'rxn41387_c0', 'rxn15167_c0', 'rxn19346_c0', 'rxn40142_c0', 'rxn01736_c0', 'rxn00644_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn11285_c0', 'rxn08233_c0', 'rxn20508_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40040_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn08473_c0', 'rxn14423_c0', ['EX_cpd00013_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd15378_e0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn02320_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn00898_c0', '>', 'new'], ['rxn02305_c0', '>', 'new'], ['rxn00796_c0', '>', 'new'], ['rxn05733_c0', '>', 'new'], ['rxn00902_c0', '<', 'new'], ['rxn01306_c0', '<', 'new'], ['rxn00789_c0', '<', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn13022_c0', '>', 'new'], ['rxn00802_c0', '>', 'new'], ['rxn02160_c0', '>', 'new'], ['rxn02159_c0', '>', 'new'], ['rxn05466_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn00272_c0', '<', 'new'], ['rxn00336_c0', '<', 'new'], ['rxn01301_c0', '<', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn03435_c0', '<', 'new'], ['rxn03175_c0', '>', 'new'], ['rxn00285_c0', '>', 'new'], ['rxn00863_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn01303_c0', '>', 'new'], ['rxn00069_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn03437_c0', '>', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn00048_c0', '>', 'new'], ['rxn00265_c0', '<', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn02200_c0', '>', 'new'], ['rxn00791_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn00952_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn04954_c0', '<', 'new'], ['rxn05909_c0', '>', 'new'], ['rxn01257_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn03909_c0', '>', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn02473_c0', '>', 'new'], ['rxn01434_c0', '>', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn02507_c0', '>', 'new'], ['rxn02186_c0', '>', 'new'], ['rxn01019_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn03194_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn16048_c0', '>', 'new'], ['rxn16671_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn37372_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn00693_c0', '>', 'reversed']]
2026-01-13 19:32:59,368 - INFO - cpd11640 not found in model!
2026-01-13 19:32:59,368 - INFO - Media compound: cpd11640 not found in model.

c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:32:59,861 - INFO - Objective with gapfill database:86.03859232922565; min objective:0.01
2026-01-13 19:32:59,884 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01505_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn02011_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn01213_c0': '>', 'rxn05618_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn00599_c0': '>', 'rxn03439_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn24212_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15550_c0': '>', 'rxn14070_c0': '>', 'rxn15072_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn10095_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:32:59,888 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 19:32:59,890 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:32:59,891 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:32:59,893 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:32:59,894 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:32:59,896 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:32:59,898 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:32:59,899 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:32:59,901 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:32:59,903 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:32:59,904 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:32:59,906 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:32:59,908 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:32:59,910 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:32:59,912 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:32:59,914 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:32:59,915 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:32:59,917 - INFO - integrating rxn: rxn09202_c0
2026-01-13 19:32:59,918 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:32:59,920 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:32:59,922 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:32:59,923 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:32:59,925 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:32:59,926 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:32:59,928 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:32:59,930 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:32:59,931 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:32:59,933 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:32:59,935 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:32:59,936 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:32:59,938 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:32:59,939 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:32:59,941 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:32:59,943 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:32:59,944 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:32:59,946 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:32:59,948 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:32:59,949 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:32:59,951 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:32:59,952 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:32:59,953 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:32:59,955 - INFO - integrating rxn: rxn02011_c0
2026-01-13 19:32:59,956 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:32:59,958 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:32:59,959 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:32:59,961 - INFO - integrating rxn: rxn06023_c0
2026-01-13 19:32:59,962 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:32:59,964 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:32:59,966 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:32:59,967 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:32:59,969 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:32:59,970 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:32:59,972 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:32:59,973 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:32:59,975 - INFO - integrating rxn: rxn05618_c0
2026-01-13 19:32:59,976 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:32:59,977 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:32:59,979 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:32:59,980 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:32:59,982 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:32:59,984 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:32:59,985 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:32:59,987 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:32:59,988 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:32:59,990 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:32:59,991 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:32:59,993 - INFO - integrating rxn: rxn01538_c0
2026-01-13 19:32:59,994 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:32:59,996 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:32:59,997 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:32:59,998 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:00,000 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:33:00,001 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:33:00,002 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:33:00,004 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:33:00,005 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:33:00,007 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:33:00,009 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:33:00,011 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:33:00,012 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:33:00,014 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:00,015 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:00,017 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:33:00,018 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:33:00,020 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:33:00,022 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:00,023 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:00,025 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:00,026 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:33:00,028 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:33:00,029 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:33:00,031 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:00,032 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:00,033 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:00,035 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:00,037 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:00,038 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:00,040 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:33:00,041 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:33:00,043 - INFO - integrating rxn: rxn24212_c0
2026-01-13 19:33:00,045 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:00,046 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:00,047 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:00,049 - INFO - integrating rxn: rxn15550_c0
2026-01-13 19:33:00,051 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:33:00,052 - INFO - integrating rxn: rxn15072_c0
2026-01-13 19:33:00,054 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:00,055 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:33:00,057 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:33:00,058 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:00,060 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:00,061 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:00,063 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:33:00,064 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:00,065 - INFO - Full solution: [['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn24212_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn15550_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15072_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new']]
2026-01-13 19:33:00,118 - INFO - AuxoMedia/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,120 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,122 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,123 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,125 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,127 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,129 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,131 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:-3.1319518052837157e-13 with min obj:0.01
2026-01-13 19:33:00,132 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,134 - INFO - AuxoMedia/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,136 - INFO - AuxoMedia/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,138 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,140 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,141 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,143 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,145 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,147 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,149 - INFO - AuxoMedia/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,151 - INFO - AuxoMedia/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,152 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,154 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,156 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,158 - INFO - AuxoMedia/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,160 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,162 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,163 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,165 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,167 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,168 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,170 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,172 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,174 - INFO - AuxoMedia/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,175 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,177 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,179 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,180 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,182 - INFO - AuxoMedia/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,184 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,185 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,187 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,189 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,190 - INFO - AuxoMedia/bio1:rxn02011_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,192 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,194 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,196 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,198 - INFO - AuxoMedia/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,199 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,201 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,203 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,204 - INFO - AuxoMedia/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,206 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,208 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,209 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,211 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,213 - INFO - AuxoMedia/bio1:rxn05618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,215 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,216 - INFO - AuxoMedia/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,218 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,220 - INFO - AuxoMedia/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:00,221 - INFO - AuxoMedia/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,223 - INFO - AuxoMedia/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,225 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,226 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,228 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,230 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,231 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,233 - INFO - AuxoMedia/bio1:rxn01538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,235 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,236 - INFO - AuxoMedia/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,238 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,240 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,242 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,243 - INFO - AuxoMedia/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,245 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,247 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:00,252 - INFO - rxn21635_c0> not needed:9.035536847302833

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01505_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn02011_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn01213_c0': '>', 'rxn05618_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn00599_c0': '>', 'rxn03439_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01538_c0': '>', 'rxn05255_c0': '>', 'rxn03130_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn24212_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15550_c0': '>', 'rxn14070_c0': '>', 'rxn15072_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn10095_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:00,386 - INFO - Cumulative: [['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:33:00,388 - INFO -     Added 90 reactions
2026-01-13 19:33:00,388 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:33:00,965 - INFO - Objective with gapfill database:137.21706849317323; min objective:0.01
2026-01-13 19:33:01,345 - INFO - Objective with gapfill database:137.21706849317363; min objective:0.01
2026-01-13 19:33:01,346 - INFO - Objective with gapfill database:86.04689764726749; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:01,513 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn05229_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn00137_c0': '>', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn11702_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn00138_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn04551_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn15354_c0': '>', 'rxn10095_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn25160_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn09390_c0': '>', 'rxn19006_c0': '>', 'rxn19007_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:01,516 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:33:01,518 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:33:01,520 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:33:01,522 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:33:01,523 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:33:01,525 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:33:01,527 - INFO - integrating rxn: rxn03030_c0
2026-01-13 19:33:01,529 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:33:01,530 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:33:01,532 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:33:01,533 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:33:01,535 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:33:01,537 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:33:01,538 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:33:01,540 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:33:01,541 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:33:01,543 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:33:01,545 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:33:01,546 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:33:01,548 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:33:01,549 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:33:01,551 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:33:01,552 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:33:01,553 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:33:01,555 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:33:01,556 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:33:01,557 - INFO - integrating rxn: rxn08528_c0
2026-01-13 19:33:01,559 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:33:01,560 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:33:01,562 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:33:01,563 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:01,565 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:33:01,566 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:33:01,567 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:33:01,569 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:33:01,570 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:33:01,572 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:33:01,573 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:33:01,575 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:33:01,576 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:33:01,577 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:33:01,579 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:33:01,580 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:33:01,582 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:33:01,583 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:33:01,585 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:33:01,586 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:33:01,587 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:33:01,589 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:33:01,590 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:33:01,592 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:33:01,594 - INFO - integrating rxn: rxn00138_c0
2026-01-13 19:33:01,596 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:33:01,598 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:01,600 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:33:01,601 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:33:01,603 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:33:01,605 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:33:01,607 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:01,609 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:01,610 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:01,612 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:01,614 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:01,615 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:33:01,616 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:01,618 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:01,620 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:01,622 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:01,623 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:33:01,625 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:33:01,627 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:01,628 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:01,630 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:33:01,631 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:33:01,633 - INFO - integrating rxn: rxn15354_c0
2026-01-13 19:33:01,634 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:33:01,636 - INFO - integrating rxn: rxn08154_c0
2026-01-13 19:33:01,638 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:33:01,639 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:33:01,640 - INFO - integrating rxn: rxn25160_c0
2026-01-13 19:33:01,642 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:33:01,644 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:01,645 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:01,647 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:33:01,648 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:01,649 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:33:01,651 - INFO - integrating rxn: rxn19006_c0
2026-01-13 19:33:01,653 - INFO - integrating rxn: rxn19007_c0
2026-01-13 19:33:01,654 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:33:01,656 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:33:01,656 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15354_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08154_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn25160_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn19006_c0', '>', 'new'], ['rxn19007_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:33:01,714 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:01,716 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:01,718 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,721 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:01,723 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:1.740844033251401e-13 with min obj:0.01
2026-01-13 19:33:01,725 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,726 - INFO - AuxoMedia/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,728 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,730 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,732 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,733 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,735 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,737 - INFO - AuxoMedia/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,739 - INFO - AuxoMedia/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,741 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,742 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,744 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,746 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,747 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,749 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,751 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,753 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,754 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,756 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,758 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:01,760 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:01,764 - INFO - AuxoMedia/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,766 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,768 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,769 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,775 - INFO - AuxoMedia/bio1:rxn01539_c0< needed:-2.486123300725281e-13 with min obj:0.01
2026-01-13 19:33:01,777 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,779 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,781 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,783 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,785 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,787 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,789 - INFO - AuxoMedia/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,790 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,792 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,794 - INFO - AuxoMedia/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:01,796 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,798 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:01,799 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,801 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,803 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,804 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,806 - INFO - AuxoMedia/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,808 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,810 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,812 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,814 - INFO - AuxoMedia/bio1:rxn00138_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,815 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,817 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,819 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,821 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,827 - INFO - rxn14424_c0> not needed:13.668928817051071
2026-01-13 19:33:01,828 - INFO - rxn11274_c0> not needed:13.668928817051071
2026-01-13 19:33:01,831 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,836 - INFO - rxn25637_c0> not needed:13.668928817051118
2026-01-13 19:33:01,837 - INFO - rxn18935_c0> not needed:13.668928817051068
2026-01-13 19:33:01,839 - INFO - rxn25638_c0> not needed:13.668928817051068
2026-01-13 19:33:01,842 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,846 - INFO - AuxoMedia/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,847 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,849 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,851 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,857 - INFO - rxn11251_c0> not needed:13.668928817051071
2026-01-13 19:33:01,859 - INFO - rxn04551_c0> not needed:13.668928817050997
2026-01-13 19:33:01,864 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,866 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,867 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,869 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,875 - INFO - rxn15064_c0> not needed:13.668928817051073
2026-01-13 19:33:01,876 - INFO - rxn15354_c0> not needed:13.668928817051011
2026-01-13 19:33:01,877 - INFO - rxn10095_c0> not needed:13.668928817051011
2026-01-13 19:33:01,879 - INFO - rxn08154_c0> not needed:13.668928817051011
2026-01-13 19:33:01,881 - INFO - rxn20508_c0> not needed:13.64807350937871
2026-01-13 19:33:01,885 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,890 - INFO - rxn25160_c0> not needed:13.648073509378579
2026-01-13 19:33:01,895 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,896 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,898 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,900 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:01,912 - INFO - rxn08921_c0> not needed:13.64807350937859
2026-01-13 19:33:01,914 - INFO - rxn09390_c0> not needed:13.64807350937859
2026-01-13 19:33:01,915 - INFO - rxn19006_c0> not needed:13.64807350937859
2026-01-13 19:33:01,916 - INFO - rxn19007_c0> not needed:13.64807350937859
2026-01-13 19:33:01,918 - INFO - rxn14423_c0> not needed:13.64807350937859
2026-01-13 19:33:01,921 - INFO - rxn10042_c0> not needed:12.773197002367034
2026-01-13 19:33:01,924 - INFO - Unneeded: [['rxn14424_c0', '>', 'new', 100, None], ['rxn11274_c0', '>', 'new', 100, None], ['rxn25637_c0', '>', 'new', 100, None], ['rxn18935_c0', '>', 'new', 100, None], ['rxn25638_c0', '>', 'new', 100, None], ['rxn11251_c0', '>', 'new', 100, None], ['rxn04551_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn15354_c0', '>', 'new', 100, None], ['rxn10095_c0', '>', 'new', 100, None], ['rxn08154_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn25160_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn09390_c0', '>', 'new', 100, None], ['rxn19006_c0', '>', 'new', 100, None], ['rxn19007_c0', '>', 'new', 100, None], ['rxn14423_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None]]
2026-01-13 19:33:01,936 - INFO - Growth: 13.668928817051052 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn05229_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn00137_c0': '>', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn11702_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn00138_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn04551_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn15354_c0': '>', 'rxn10095_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn25160_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn09390_c0': '>', 'rxn19006_c0': '>', 'rxn19007_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:01,939 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:33:01,940 - INFO -     Added 71 reactions
2026-01-13 19:33:01,941 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:33:02,631 - INFO - Objective with gapfill database:137.2170684931733; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:02,717 - INFO - Objective with gapfill database:86.03859232922565; min objective:0.01
2026-01-13 19:33:03,623 - INFO - Initial solution: {'reversed': {'rxn00693_c0': '>', 'rxn00558_c0': '<'}, 'new': {'EX_cpd00013_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd00421_e0': '>', 'rxn00359_c0': '<', 'rxn02504_c0': '>', 'rxn03436_c0': '>', 'rxn02160_c0': '>', 'rxn00340_c0': '>', 'rxn00957_c0': '>', 'rxn05466_c0': '>', 'rxn00300_c0': '>', 'rxn09180_c0': '>', 'rxn02835_c0': '>', 'rxn00213_c0': '>', 'rxn01300_c0': '>', 'rxn00010_c0': '>', 'rxn01303_c0': '>', 'rxn01106_c0': '>', 'rxn01539_c0': '<', 'rxn00333_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn05717_c0': '<', 'rxn03841_c0': '>', 'rxn12239_c0': '>', 'rxn01257_c0': '>', 'rxn05651_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn00430_c0': '<', 'rxn00288_c0': '<', 'rxn02185_c0': '<', 'rxn00623_c0': '<', 'rxn01603_c0': '>', 'rxn21857_c0': '>', 'rxn16573_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn21862_c0': '>', 'rxn11279_c0': '>', 'rxn21859_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn21858_c0': '>', 'rxn20834_c0': '>', 'rxn21861_c0': '>', 'rxn40439_c0': '>', 'rxn21860_c0': '>', 'rxn20216_c0': '>', 'rxn25638_c0': '>', 'rxn28338_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn30685_c0': '>', 'rxn20508_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn27266_c0': '>', 'rxn42332_c0': '>', 'rxn24606_c0': '>', 'rxn24607_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:03,626 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:33:03,629 - INFO - integrating rxn: EX_cpd00048_e0
2026-01-13 19:33:03,630 - INFO - integrating rxn: EX_cpd00421_e0
2026-01-13 19:33:03,632 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:33:03,634 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:03,635 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:03,637 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:33:03,639 - INFO - integrating rxn: rxn00340_c0
2026-01-13 19:33:03,641 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:33:03,643 - INFO - integrating rxn: rxn05466_c0
2026-01-13 19:33:03,644 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:03,646 - INFO - integrating rxn: rxn09180_c0
2026-01-13 19:33:03,648 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:33:03,649 - INFO - integrating rxn: rxn00213_c0
2026-01-13 19:33:03,651 - INFO - integrating rxn: rxn01300_c0
2026-01-13 19:33:03,652 - INFO - integrating rxn: rxn00010_c0
2026-01-13 19:33:03,654 - INFO - integrating rxn: rxn01303_c0
2026-01-13 19:33:03,656 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:33:03,658 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:03,659 - INFO - integrating rxn: rxn00333_c0
2026-01-13 19:33:03,662 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:03,663 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:03,665 - INFO - integrating rxn: rxn05717_c0
2026-01-13 19:33:03,666 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:03,668 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:03,670 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:03,671 - INFO - integrating rxn: rxn05651_c0
2026-01-13 19:33:03,673 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:03,675 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:03,676 - INFO - integrating rxn: rxn00430_c0
2026-01-13 19:33:03,678 - INFO - integrating rxn: rxn00288_c0
2026-01-13 19:33:03,680 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:03,682 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:33:03,683 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:03,685 - INFO - integrating rxn: rxn21857_c0
2026-01-13 19:33:03,687 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:03,689 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:33:03,690 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:03,690 - INFO - Objective with gapfill database:137.21706849317363; min objective:0.01
2026-01-13 19:33:03,692 - INFO - integrating rxn: rxn21862_c0
2026-01-13 19:33:03,694 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:03,695 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:33:03,697 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:03,698 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:03,700 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:03,701 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:03,703 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:03,704 - INFO - integrating rxn: rxn21858_c0
2026-01-13 19:33:03,706 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:03,707 - INFO - integrating rxn: rxn21861_c0
2026-01-13 19:33:03,708 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:03,710 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:03,711 - INFO - integrating rxn: rxn20216_c0
2026-01-13 19:33:03,713 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:03,714 - INFO - integrating rxn: rxn28338_c0
2026-01-13 19:33:03,716 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:33:03,717 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:33:03,718 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:33:03,720 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:03,721 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:33:03,723 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:33:03,724 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:33:03,725 - INFO - integrating rxn: rxn27266_c0
2026-01-13 19:33:03,727 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:33:03,728 - INFO - integrating rxn: rxn24606_c0
2026-01-13 19:33:03,730 - INFO - integrating rxn: rxn24607_c0
2026-01-13 19:33:03,730 - INFO - integrating rxn: rxn00693_c0
2026-01-13 19:33:03,731 - INFO - integrating rxn: rxn00558_c0
2026-01-13 19:33:03,732 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00132_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00161_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00364_c0', '>', 'new'], ['rxn03408_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn05300_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn01048_c0', '<', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn00796_c0', '<', 'new'], ['rxn01729_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn00762_c0', '<', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn00383_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00612_c0', '<', 'new'], ['rxn08551_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn11946_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00747_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn11943_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn04464_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn05573_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn01484_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn08224_c0', '<', 'new'], ['rxn00252_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn00173_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn01669_c0', '<', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05508_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn00606_c0', '<', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01730_c0', '>', 'new'], ['rxn00069_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00283_c0', '>', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn05342_c0', '<', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01631_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02285_c0', '<', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02085_c0', '<', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn00461_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00121_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00320_c0', '>', 'new'], ['rxn00693_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00558_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00851_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn00605_c0', '<', 'new'], ['rxn02008_c0', '>', 'new'], ['rxn03904_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn10199_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03901_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03164_c0', '>', 'new'], ['rxn00347_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn08231_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn17731_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn15091_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn15776_c0', '>', 'new'], ['rxn14050_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00030_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00132_e0', 'EX_cpd00058_e0', 'EX_cpd00149_e0', 'EX_cpd00063_e0', 'EX_cpd00161_e0', 'EX_cpd00027_e0', 'EX_cpd00060_e0', 'EX_cpd00099_e0', 'rxn08709_c0', 'rxn00364_c0', 'rxn03408_c0', 'rxn03086_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn00179_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn03030_c0', 'rxn01117_c0', 'rxn08710_c0', 'rxn05300_c0', 'rxn03181_c0', 'rxn01048_c0', 'rxn02331_c0', 'rxn00796_c0', 'rxn01729_c0', 'rxn12512_c0', 'rxn01739_c0', 'rxn00762_c0', 'rxn08583_c0', 'rxn00383_c0', 'rxn02264_c0', 'rxn09202_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn00612_c0', 'rxn08551_c0', 'rxn08708_c0', 'rxn11946_c0', 'rxn05229_c0', 'rxn02404_c0', 'rxn00392_c0', 'rxn00747_c0', 'rxn05219_c0', 'rxn09225_c0', 'rxn11943_c0', 'rxn02774_c0', 'rxn04464_c0', 'rxn01505_c0', 'rxn05573_c0', 'rxn03919_c0', 'rxn10124_c0', 'rxn09210_c0', 'rxn01484_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn04704_c0', 'rxn03159_c0', 'rxn03397_c0', 'rxn01972_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn08224_c0', 'rxn00252_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn02011_c0', 'rxn00173_c0', 'rxn03916_c0', 'rxn01669_c0', 'rxn10954_c0', 'rxn05508_c0', 'rxn05645_c0', 'rxn00606_c0', 'rxn08711_c0', 'rxn04413_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn01730_c0', 'rxn00069_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn00283_c0', 'rxn03108_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn05342_c0', 'rxn02405_c0', 'rxn03150_c0', 'rxn01631_c0', 'rxn01537_c0', 'rxn02285_c0', 'rxn03538_c0', 'rxn01213_c0', 'rxn02085_c0', 'rxn02304_c0', 'rxn05618_c0', 'rxn08241_c0', 'rxn00461_c0', 'rxn03136_c0', 'rxn08088_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn00121_c0', 'rxn05226_c0', 'rxn00599_c0', 'rxn00704_c0', 'rxn08130_c0', 'rxn11702_c0', 'rxn00320_c0', 'rxn00693_c0', 'rxn03439_c0', 'rxn00558_c0', 'rxn01790_c0', 'rxn02056_c0', 'rxn03075_c0', 'rxn00134_c0', 'rxn00851_c0', 'rxn02003_c0', 'rxn01602_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn01466_c0', 'rxn00605_c0', 'rxn02008_c0', 'rxn03904_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn10199_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn03901_c0', 'rxn02832_c0', 'rxn03164_c0', 'rxn00347_c0', 'rxn03130_c0', 'rxn08231_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn00686_c0', 'rxn00293_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn17731_c0', 'rxn14424_c0', 'rxn12930_c0', 'rxn12932_c0', 'rxn12940_c0', 'rxn12939_c0', 'rxn12929_c0', 'rxn25637_c0', 'rxn18935_c0', 'rxn25743_c0', 'rxn12928_c0', 'rxn12943_c0', 'rxn12942_c0', 'rxn02485_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn11251_c0', 'rxn15167_c0', 'rxn19346_c0', 'rxn15091_c0', 'rxn25042_c0', 'rxn19766_c0', 'rxn19764_c0', 'rxn19728_c0', 'rxn20235_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn16114_c0', 'rxn14070_c0', 'rxn15060_c0', 'rxn29919_c0', 'rxn08233_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn09037_c0', 'rxn15776_c0', 'rxn14050_c0', 'rxn14423_c0', 'rxn10042_c0', ['EX_cpd00013_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00421_e0', '>', 'new'], ['rxn00359_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn02160_c0', '>', 'new'], ['rxn00340_c0', '>', 'new'], ['rxn00957_c0', '>', 'new'], ['rxn05466_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn09180_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn00213_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn00010_c0', '>', 'new'], ['rxn01303_c0', '>', 'new'], ['rxn01106_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn00333_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn05717_c0', '<', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn01257_c0', '>', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn00430_c0', '<', 'new'], ['rxn00288_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn21857_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn21862_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn21859_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn21858_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn21861_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn20216_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn27266_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn24606_c0', '>', 'new'], ['rxn24607_c0', '>', 'new'], ['rxn00693_c0', '>', 'reversed'], ['rxn00558_c0', '<', 'reversed']]
2026-01-13 19:33:03,738 - INFO - cpd11640 not found in model!
2026-01-13 19:33:03,738 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:03,746 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,748 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,749 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,751 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,753 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,754 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00132_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,755 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,756 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00149_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,758 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,759 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00161_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,760 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00027_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,761 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00060_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,762 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,764 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,765 - INFO - PyruateMinimalAnaerobic/bio1:rxn00364_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,766 - INFO - PyruateMinimalAnaerobic/bio1:rxn03408_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,767 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,769 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,770 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,771 - INFO - PyruateMinimalAnaerobic/bio1:rxn00179_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,772 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,773 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,774 - INFO - PyruateMinimalAnaerobic/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,775 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:03,777 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,778 - INFO - PyruateMinimalAnaerobic/bio1:rxn05300_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,779 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:03,780 - INFO - PyruateMinimalAnaerobic/bio1:rxn01048_c0< needed:0.0 with min obj:0.01

c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:04,287 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn10336_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn00599_c0': '>', 'rxn11702_c0': '>', 'rxn01332_c0': '>', 'rxn03439_c0': '>', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn16622_c0': '>', 'rxn15060_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn16341_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn13301_c0': '>', 'rxn29260_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:04,291 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:33:04,293 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:33:04,295 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:33:04,297 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:33:04,299 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:33:04,300 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:33:04,302 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:33:04,304 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:33:04,306 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:33:04,307 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:33:04,309 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:33:04,311 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:33:04,313 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:33:04,314 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:33:04,316 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:33:04,318 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:33:04,319 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:33:04,321 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:33:04,323 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:33:04,324 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:33:04,326 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:33:04,327 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:33:04,330 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:33:04,331 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:33:04,333 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:33:04,335 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:33:04,336 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:33:04,337 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:33:04,339 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:33:04,341 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:33:04,342 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:33:04,344 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:33:04,345 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:33:04,347 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:33:04,348 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:33:04,350 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:33:04,351 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:33:04,352 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:33:04,354 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:33:04,356 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:33:04,357 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:33:04,359 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:33:04,360 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:33:04,361 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:33:04,363 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:33:04,365 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:33:04,366 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:33:04,368 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:33:04,369 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:33:04,371 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:33:04,372 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:33:04,374 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:33:04,375 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:33:04,377 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:33:04,378 - INFO - integrating rxn: rxn01332_c0
2026-01-13 19:33:04,380 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:33:04,381 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:33:04,383 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:33:04,384 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:33:04,386 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:33:04,387 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:33:04,389 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:33:04,390 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:33:04,392 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:04,393 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:33:04,394 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:33:04,396 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:33:04,397 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:33:04,399 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:04,401 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:04,402 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:33:04,404 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:33:04,405 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:04,407 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:04,409 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:04,411 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:04,412 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:04,414 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:04,415 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:04,417 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:04,419 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:04,421 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:33:04,422 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:33:04,423 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:33:04,424 - INFO - Initial solution: {'reversed': {'rxn09180_c0': '>', 'rxn01301_c0': '<', 'rxn00786_c0': '<', 'rxn00693_c0': '>', 'rxn00558_c0': '<'}, 'new': {'EX_cpd00013_e0': '<', 'rxn00359_c0': '<', 'rxn00179_c0': '>', 'rxn02320_c0': '<', 'rxn00544_c0': '>', 'rxn00958_c0': '>', 'rxn00470_c0': '>', 'rxn00902_c0': '<', 'rxn01268_c0': '>', 'rxn01306_c0': '<', 'rxn00789_c0': '<', 'rxn03436_c0': '>', 'rxn00802_c0': '>', 'rxn02160_c0': '>', 'rxn00340_c0': '>', 'rxn02159_c0': '>', 'rxn05466_c0': '>', 'rxn00300_c0': '>', 'rxn02835_c0': '>', 'rxn01575_c0': '<', 'rxn03435_c0': '<', 'rxn01256_c0': '>', 'rxn00777_c0': '>', 'rxn00503_c0': '<', 'rxn03175_c0': '>', 'rxn01000_c0': '>', 'rxn01300_c0': '>', 'rxn12868_c0': '>', 'rxn02811_c0': '<', 'rxn03062_c0': '>', 'rxn00863_c0': '>', 'rxn01303_c0': '>', 'rxn01539_c0': '<', 'rxn02508_c0': '>', 'rxn00420_c0': '>', 'rxn06710_c0': '<', 'rxn00048_c0': '>', 'rxn00726_c0': '>', 'rxn02789_c0': '>', 'rxn01069_c0': '>', 'rxn00791_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn00952_c0': '>', 'rxn03841_c0': '>', 'rxn04954_c0': '<', 'rxn12239_c0': '>', 'rxn01257_c0': '>', 'rxn00903_c0': '<', 'rxn00652_c0': '<', 'rxn00806_c0': '<', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn00288_c0': '<', 'rxn02185_c0': '<', 'rxn02473_c0': '>', 'rxn01434_c0': '>', 'rxn08094_c0': '<', 'rxn02373_c0': '<', 'rxn01304_c0': '>', 'rxn00929_c0': '<', 'rxn00467_c0': '<', 'rxn00623_c0': '<', 'rxn02507_c0': '>', 'rxn01964_c0': '>', 'rxn02186_c0': '>', 'rxn02914_c0': '<', 'rxn01603_c0': '>', 'rxn03194_c0': '>', 'rxn16573_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn21859_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn21860_c0': '>', 'rxn12932_c0': '>', 'rxn25743_c0': '>', 'rxn12942_c0': '>', 'rxn46124_c0': '>', 'rxn30633_c0': '>', 'rxn15395_c0': '>', 'rxn15091_c0': '>', 'rxn16048_c0': '>', 'rxn15064_c0': '>', 'rxn37372_c0': '>', 'rxn15940_c0': '>', 'rxn47493_c0': '>', 'rxn16687_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:04,425 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:33:04,427 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:33:04,428 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:33:04,429 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:33:04,430 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:33:04,431 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:33:04,432 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:33:04,432 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:04,433 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:33:04,434 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:04,435 - INFO - integrating rxn: rxn00544_c0
2026-01-13 19:33:04,435 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:33:04,436 - INFO - integrating rxn: rxn00958_c0
2026-01-13 19:33:04,437 - INFO - integrating rxn: rxn16622_c0
2026-01-13 19:33:04,438 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:33:04,438 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:04,440 - INFO - integrating rxn: rxn00902_c0
2026-01-13 19:33:04,440 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:33:04,441 - INFO - integrating rxn: rxn01268_c0
2026-01-13 19:33:04,442 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:33:04,443 - INFO - integrating rxn: rxn01306_c0
2026-01-13 19:33:04,444 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:33:04,444 - INFO - integrating rxn: rxn00789_c0
2026-01-13 19:33:04,445 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:04,445 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:04,447 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:33:04,447 - INFO - integrating rxn: rxn00802_c0
2026-01-13 19:33:04,448 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:04,448 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:33:04,449 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:33:04,450 - INFO - integrating rxn: rxn00340_c0
2026-01-13 19:33:04,451 - INFO - integrating rxn: rxn13301_c0
2026-01-13 19:33:04,451 - INFO - integrating rxn: rxn02159_c0
2026-01-13 19:33:04,452 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:33:04,452 - INFO - integrating rxn: rxn05466_c0
2026-01-13 19:33:04,454 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:04,454 - INFO - integrating rxn: rxn41399_c0
2026-01-13 19:33:04,455 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:33:04,456 - INFO - integrating rxn: rxn41401_c0
2026-01-13 19:33:04,457 - INFO - integrating rxn: rxn01575_c0
2026-01-13 19:33:04,457 - INFO - integrating rxn: rxn15776_c0
2026-01-13 19:33:04,458 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn16622_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn13301_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn41399_c0', '>', 'new'], ['rxn41401_c0', '>', 'new'], ['rxn15776_c0', '>', 'new']]
2026-01-13 19:33:04,458 - INFO - integrating rxn: rxn03435_c0
2026-01-13 19:33:04,459 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:33:04,460 - INFO - integrating rxn: rxn00777_c0
2026-01-13 19:33:04,462 - INFO - integrating rxn: rxn00503_c0
2026-01-13 19:33:04,463 - INFO - integrating rxn: rxn03175_c0
2026-01-13 19:33:04,465 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:33:04,466 - INFO - integrating rxn: rxn01300_c0
2026-01-13 19:33:04,468 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:33:04,469 - INFO - integrating rxn: rxn02811_c0
2026-01-13 19:33:04,471 - INFO - integrating rxn: rxn03062_c0
2026-01-13 19:33:04,472 - INFO - integrating rxn: rxn00863_c0
2026-01-13 19:33:04,473 - INFO - integrating rxn: rxn01303_c0
2026-01-13 19:33:04,475 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:04,476 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:33:04,477 - INFO - integrating rxn: rxn00420_c0
2026-01-13 19:33:04,477 - INFO - cpd00263 not found in model!
2026-01-13 19:33:04,478 - INFO - Media compound: cpd00263 not found in model.
2026-01-13 19:33:04,479 - INFO - integrating rxn: rxn06710_c0
2026-01-13 19:33:04,480 - INFO - integrating rxn: rxn00048_c0
2026-01-13 19:33:04,482 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:33:04,483 - INFO - integrating rxn: rxn02789_c0
2026-01-13 19:33:04,485 - INFO - integrating rxn: rxn01069_c0
2026-01-13 19:33:04,486 - INFO - integrating rxn: rxn00791_c0
2026-01-13 19:33:04,488 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:04,489 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:04,491 - INFO - integrating rxn: rxn00952_c0
2026-01-13 19:33:04,492 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:04,493 - INFO - integrating rxn: rxn04954_c0
2026-01-13 19:33:04,495 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:04,496 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:04,497 - INFO - integrating rxn: rxn00903_c0
2026-01-13 19:33:04,499 - INFO - integrating rxn: rxn00652_c0
2026-01-13 19:33:04,500 - INFO - integrating rxn: rxn00806_c0
2026-01-13 19:33:04,502 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:04,503 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:04,505 - INFO - integrating rxn: rxn00288_c0
2026-01-13 19:33:04,506 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:04,507 - INFO - integrating rxn: rxn02473_c0
2026-01-13 19:33:04,509 - INFO - integrating rxn: rxn01434_c0
2026-01-13 19:33:04,510 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:33:04,512 - INFO - integrating rxn: rxn02373_c0
2026-01-13 19:33:04,513 - INFO - integrating rxn: rxn01304_c0
2026-01-13 19:33:04,515 - INFO - integrating rxn: rxn00929_c0
2026-01-13 19:33:04,516 - INFO - integrating rxn: rxn00467_c0
2026-01-13 19:33:04,517 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:33:04,519 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:33:04,519 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:04,520 - INFO - integrating rxn: rxn01964_c0
2026-01-13 19:33:04,522 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:04,522 - INFO - integrating rxn: rxn02186_c0
2026-01-13 19:33:04,523 - INFO - integrating rxn: rxn02914_c0
2026-01-13 19:33:04,523 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:04,524 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:04,525 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:04,526 - INFO - integrating rxn: rxn03194_c0
2026-01-13 19:33:04,527 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,527 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:04,529 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,529 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:33:04,530 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:04,530 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,532 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:04,532 - INFO - AuxoMedia/bio1:rxn00179_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,533 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:33:04,534 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,535 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:04,536 - INFO - AuxoMedia/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:04,536 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:04,537 - INFO - integrating rxn: rxn41452_c0

Adding gapfilling

2026-01-13 19:33:04,799 - INFO - PyruateMinimalAnaerobic/bio1:rxn15167_c0> needed:0.0 with min obj:0.01

2026-01-13 19:33:04,800 - INFO - PyruateMinimalAnaerobic/bio1:rxn19346_c0> needed:0.0 with min obj:0.01

{'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn00179_c0': '>', 'rxn10336_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn00599_c0': '>', 'rxn11702_c0': '>', 'rxn01332_c0': '>', 'rxn03439_c0': '>', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn16622_c0': '>', 'rxn15060_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn16341_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn13301_c0': '>', 'rxn29260_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:04,801 - INFO - PyruateMinimalAnaerobic/bio1:rxn19728_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,801 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:33:04,802 - INFO -     Added 81 reactions
2026-01-13 19:33:04,802 - INFO - PyruateMinimalAnaerobic/bio1:rxn20235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,803 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:33:04,804 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,805 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,806 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,807 - INFO - PyruateMinimalAnaerobic/bio1:rxn16114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,808 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,809 - INFO - PyruateMinimalAnaerobic/bio1:rxn15060_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,811 - INFO - PyruateMinimalAnaerobic/bio1:rxn29919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,812 - INFO - PyruateMinimalAnaerobic/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,813 - INFO - PyruateMinimalAnaerobic/bio1:rxn20508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,814 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,816 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,817 - INFO - PyruateMinimalAnaerobic/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,818 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,820 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,821 - INFO - PyruateMinimalAnaerobic/bio1:rxn08473_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,822 - INFO - PyruateMinimalAnaerobic/bio1:rxn14423_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,828 - INFO - PyruateMinimalAnaerobic/bio1:rxn10042_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:04,828 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:33:04,829 - INFO -   Running ATP safety check...

c0

2026-01-13 19:33:04,953 - INFO - Objective with gapfill database:137.2170684931733; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:05,536 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn10030_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01501_c0': '<', 'rxn01505_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05645_c0': '>', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn03907_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn11702_c0': '>', 'rxn02056_c0': '<', 'rxn03075_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn08154_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn16341_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn13301_c0': '>', 'rxn08921_c0': '>', 'rxn20567_c0': '>', 'rxn23676_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>', 'rxn14423_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:05,540 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:33:05,542 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:33:05,544 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:33:05,546 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:33:05,548 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:33:05,550 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:33:05,551 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:33:05,553 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:33:05,555 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:33:05,556 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:33:05,558 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:33:05,560 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:33:05,561 - INFO - integrating rxn: rxn10030_c0
2026-01-13 19:33:05,563 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:33:05,564 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:33:05,566 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:33:05,567 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:33:05,569 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:33:05,571 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:33:05,572 - INFO - integrating rxn: rxn01501_c0
2026-01-13 19:33:05,574 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:33:05,575 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:33:05,577 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:33:05,578 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:33:05,579 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:33:05,581 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:33:05,583 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:33:05,584 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:33:05,586 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:33:05,588 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:33:05,589 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:33:05,591 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:33:05,592 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:33:05,594 - INFO - integrating rxn: rxn10094_c0
2026-01-13 19:33:05,595 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:33:05,596 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:33:05,598 - INFO - integrating rxn: rxn03907_c0
2026-01-13 19:33:05,599 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:33:05,601 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:33:05,602 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:33:05,603 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:33:05,605 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:33:05,606 - INFO - integrating rxn: rxn03075_c0
2026-01-13 19:33:05,608 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:33:05,609 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:33:05,611 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:33:05,612 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:33:05,614 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:33:05,615 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:33:05,616 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:33:05,618 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:33:05,619 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:33:05,621 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:05,622 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:33:05,623 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:33:05,625 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:33:05,627 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:33:05,629 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:33:05,630 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:33:05,632 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:33:05,633 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:33:05,635 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:05,636 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:33:05,638 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:33:05,639 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:05,641 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:05,642 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:05,644 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:33:05,645 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:33:05,647 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:05,648 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:33:05,649 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:05,651 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:05,652 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:05,654 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:33:05,655 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:33:05,657 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:33:05,658 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:33:05,660 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:33:05,661 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:05,663 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:05,664 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:33:05,666 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:05,667 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:33:05,668 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:33:05,670 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:33:05,671 - INFO - integrating rxn: rxn08154_c0
2026-01-13 19:33:05,672 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:33:05,674 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:05,676 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:05,677 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:33:05,679 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:33:05,680 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:33:05,682 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:33:05,683 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:05,685 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:33:05,686 - INFO - integrating rxn: rxn13301_c0
2026-01-13 19:33:05,687 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:05,689 - INFO - integrating rxn: rxn20567_c0
2026-01-13 19:33:05,690 - INFO - integrating rxn: rxn23676_c0
2026-01-13 19:33:05,692 - INFO - integrating rxn: rxn41399_c0
2026-01-13 19:33:05,694 - INFO - integrating rxn: rxn41401_c0
2026-01-13 19:33:05,695 - INFO - integrating rxn: rxn15776_c0
2026-01-13 19:33:05,697 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:33:05,699 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:33:05,701 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:33:05,703 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:33:05,705 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:33:05,706 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08154_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn13301_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn20567_c0', '>', 'new'], ['rxn23676_c0', '>', 'new'], ['rxn41399_c0', '>', 'new'], ['rxn41401_c0', '>', 'new'], ['rxn15776_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:33:05,764 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:05,766 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:05,768 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:05,770 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,772 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,774 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,776 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,778 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,780 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,782 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,783 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,785 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,789 - INFO - AuxoMedia/bio1:rxn10030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,790 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,792 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,794 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,796 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,798 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,800 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,806 - INFO - rxn01501_c0< not needed:14.485564370929323
2026-01-13 19:33:05,810 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,812 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,814 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,816 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,817 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,819 - INFO - AuxoMedia/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,821 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,823 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:05,824 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,826 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:05,828 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,830 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,833 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:-1.7825167884581364e-13 with min obj:0.01
2026-01-13 19:33:05,835 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,836 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,842 - INFO - rxn02303_c0> not needed:14.453823838122185
2026-01-13 19:33:05,846 - INFO - AuxoMedia/bio1:rxn03907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,848 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,850 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,854 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,856 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,857 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:05,859 - INFO - AuxoMedia/bio1:rxn03075_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,861 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,862 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,864 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,866 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,868 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,869 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,871 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,873 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:05,879 - INFO - rxn05464_c0> not needed:14.45382383812212
2026-01-13 19:33:05,883 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,884 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,886 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,888 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,894 - INFO - rxn16218_c0> not needed:14.453823838122224
2026-01-13 19:33:05,898 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,902 - INFO - rxn16217_c0> not needed:14.453823838122162
2026-01-13 19:33:05,906 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,911 - INFO - rxn14424_c0> not needed:14.45382383812216
2026-01-13 19:33:05,916 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,921 - INFO - rxn12940_c0> not needed:14.453823838122197
2026-01-13 19:33:05,922 - INFO - rxn12929_c0> not needed:14.453823838122206
2026-01-13 19:33:05,924 - INFO - rxn25637_c0> not needed:14.453823838122206
2026-01-13 19:33:05,925 - INFO - rxn18935_c0> not needed:14.453823838122206
2026-01-13 19:33:05,926 - INFO - rxn25638_c0> not needed:14.453823838122206
2026-01-13 19:33:05,928 - INFO - rxn12944_c0> not needed:14.453823838122206
2026-01-13 19:33:05,929 - INFO - rxn12994_c0> not needed:14.453823838122206
2026-01-13 19:33:05,932 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,936 - INFO - rxn02485_c0> not needed:14.450657433592704
2026-01-13 19:33:05,938 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,940 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,942 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,945 - INFO - rxn19346_c0> not needed:14.216208930106193
2026-01-13 19:33:05,946 - INFO - rxn04551_c0> not needed:14.21620893010615
2026-01-13 19:33:05,948 - INFO - rxn19728_c0> not needed:14.21620893010615
2026-01-13 19:33:05,949 - INFO - rxn20235_c0> not needed:14.21620893010615
2026-01-13 19:33:05,952 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,954 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,956 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,957 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:05,964 - INFO - rxn15060_c0> not needed:14.216208930106266
2026-01-13 19:33:05,966 - INFO - rxn29919_c0> not needed:14.216208930106266
2026-01-13 19:33:05,967 - INFO - rxn15064_c0> not needed:14.216208930106266
2026-01-13 19:33:05,968 - INFO - rxn10095_c0> not needed:14.216208930106266
2026-01-13 19:33:05,970 - INFO - rxn08154_c0> not needed:14.216208930106266
2026-01-13 19:33:05,971 - INFO - rxn20627_c0> not needed:14.216208930106266
2026-01-13 19:33:05,975 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn10030_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01501_c0': '<', 'rxn01505_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05645_c0': '>', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03150_c0': '>', 'rxn02303_c0': '>', 'rxn03907_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn11702_c0': '>', 'rxn02056_c0': '<', 'rxn03075_c0': '>', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn10095_c0': '>', 'rxn08154_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn16341_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn13301_c0': '>', 'rxn08921_c0': '>', 'rxn20567_c0': '>', 'rxn23676_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>', 'rxn14423_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:06,030 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:33:06,031 - INFO -     Added 68 reactions
2026-01-13 19:33:06,032 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:07,234 - INFO - Objective with gapfill database:137.21706849317312; min objective:0.01
2026-01-13 19:33:08,455 - INFO - Objective with gapfill database:114.73871061823165; min objective:0.01
2026-01-13 19:33:09,386 - INFO - Objective with gapfill database:114.73871061823233; min objective:0.01
2026-01-13 19:33:09,529 - INFO - Objective with gapfill database:137.21706849317312; min objective:0.01
2026-01-13 19:33:10,088 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn06848_c0': '<', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn03917_c0': '>', 'rxn03893_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn13741_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:10,091 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:33:10,093 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:33:10,095 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:33:10,097 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:33:10,099 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:33:10,100 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:33:10,102 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:33:10,104 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:33:10,106 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:33:10,107 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:33:10,109 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:33:10,111 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:33:10,112 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:33:10,114 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:33:10,116 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:33:10,117 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:33:10,119 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:33:10,120 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:33:10,122 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:33:10,123 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:33:10,125 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:33:10,127 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:33:10,128 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:33:10,130 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:33:10,131 - INFO - integrating rxn: rxn05463_c0
2026-01-13 19:33:10,133 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:33:10,134 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:33:10,136 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:33:10,137 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:33:10,139 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:33:10,140 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:33:10,142 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:33:10,143 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:33:10,145 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:33:10,146 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:33:10,148 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:33:10,149 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:33:10,151 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:33:10,152 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:33:10,154 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:33:10,155 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:33:10,156 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:33:10,158 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:10,160 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:33:10,161 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:33:10,162 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:33:10,164 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:33:10,166 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:33:10,167 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:33:10,169 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:10,171 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:33:10,172 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:33:10,174 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:10,175 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:10,177 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:10,178 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:10,180 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:33:10,181 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:10,183 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:10,184 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:10,186 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:10,188 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:33:10,189 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:33:10,191 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:33:10,192 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:33:10,194 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:33:10,195 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:10,197 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:10,198 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:10,200 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:33:10,201 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:33:10,203 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:33:10,204 - INFO - integrating rxn: rxn13741_c0
2026-01-13 19:33:10,206 - INFO - integrating rxn: rxn08154_c0
2026-01-13 19:33:10,207 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:33:10,210 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:10,211 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:10,213 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:33:10,214 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:33:10,216 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:33:10,218 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:10,219 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:10,221 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:33:10,222 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:33:10,224 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:33:10,226 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:33:10,228 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:33:10,229 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn13741_c0', '>', 'new'], ['rxn08154_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:33:10,290 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:10,293 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:10,294 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:10,296 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:10,299 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,301 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,303 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,305 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,307 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,309 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,311 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,313 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,315 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,317 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,318 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,320 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,322 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,324 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,326 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,328 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,330 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,331 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:10,334 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:10,335 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,337 - INFO - AuxoMedia/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,339 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,341 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,345 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:10,346 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,348 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,350 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,352 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,354 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,356 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,357 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,359 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:10,361 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,363 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,365 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,366 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,368 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,370 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,372 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,374 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,376 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,378 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,380 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,381 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,389 - INFO - rxn11274_c0> not needed:6.9445117915306085
2026-01-13 19:33:10,393 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,400 - INFO - rxn12940_c0> not needed:6.944511791530561
2026-01-13 19:33:10,402 - INFO - rxn12929_c0> not needed:6.944511791530561
2026-01-13 19:33:10,403 - INFO - rxn25637_c0> not needed:6.944511791530561
2026-01-13 19:33:10,405 - INFO - rxn18935_c0> not needed:6.944511791530561
2026-01-13 19:33:10,406 - INFO - rxn25638_c0> not needed:6.944511791530561
2026-01-13 19:33:10,410 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,417 - INFO - rxn02485_c0> not needed:6.943223893871134
2026-01-13 19:33:10,421 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,423 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,425 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,429 - INFO - rxn11251_c0> not needed:6.943223893871138
2026-01-13 19:33:10,430 - INFO - rxn47267_c0> not needed:6.9432238938711395
2026-01-13 19:33:10,432 - INFO - rxn41387_c0> not needed:6.9432238938711395
2026-01-13 19:33:10,433 - INFO - rxn19346_c0> not needed:6.9432238938711395
2026-01-13 19:33:10,435 - INFO - rxn04551_c0> not needed:6.9432238938711395
2026-01-13 19:33:10,438 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,440 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,441 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,448 - INFO - rxn15060_c0> not needed:6.943223893871106
2026-01-13 19:33:10,449 - INFO - rxn15064_c0> not needed:6.943223893871136
2026-01-13 19:33:10,451 - INFO - rxn15270_c0> not needed:6.943223893871136
2026-01-13 19:33:10,452 - INFO - rxn11285_c0> not needed:6.943223893871136
2026-01-13 19:33:10,453 - INFO - rxn13741_c0> not needed:6.943223893871136
2026-01-13 19:33:10,455 - INFO - rxn08154_c0> not needed:6.943223893871136
2026-01-13 19:33:10,456 - INFO - rxn20508_c0> not needed:6.943223893871136
2026-01-13 19:33:10,461 - INFO - rxn30917_c0> not needed:6.943223893871151
2026-01-13 19:33:10,462 - INFO - rxn15939_c0> not needed:6.943223893871122
2026-01-13 19:33:10,464 - INFO - rxn41492_c0> not needed:6.943223893871122
2026-01-13 19:33:10,465 - INFO - rxn44493_c0> not needed:6.943223893871122
2026-01-13 19:33:10,467 - INFO - rxn42332_c0> not needed:6.943223893871122
2026-01-13 19:33:10,470 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,474 - INFO - rxn08921_c0> not needed:6.943223893871127
2026-01-13 19:33:10,476 - INFO - rxn10042_c0> not needed:6.943223893871136
2026-01-13 19:33:10,479 - INFO - AuxoMedia/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,481 - INFO - AuxoMedia/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,483 - INFO - AuxoMedia/bio1:rxn41263_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,484 - INFO - AuxoMedia/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:10,485 - INFO - Objective with gapfill database:137.2170684931735; min objective:0.01
2026-01-13 19:33:10,488 - INFO - Unneeded: [['rxn11274_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn25637_c0', '>', 'new', 100, None], ['rxn18935_c0', '>', 'new', 100, None], ['rxn25638_c0', '>', 'new', 100, None], ['rxn02485_c0', '>', 'new', 100, None], ['rxn11251_c0', '>', 'new', 100, None], ['rxn47267_c0', '>', 'new', 100, None], ['rxn41387_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn04551_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn15270_c0', '>', 'new', 100, None], ['rxn11285_c0', '>', 'new', 100, None], ['rxn13741_c0', '>', 'new', 100, None], ['rxn08154_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn30917_c0', '>', 'new', 100, None], ['rxn15939_c0', '>', 'new', 100, None], ['rxn41492_c0', '>', 'new', 100, None], ['rxn44493_c0', '>', 'new', 100, None], ['rxn42332_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn10042_c0', '>', 'new', 100, None]]

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:10,503 - INFO - Growth: 6.944511791530597 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn06848_c0': '<', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn03917_c0': '>', 'rxn03893_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn13741_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:10,507 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:33:10,508 - INFO -     Added 61 reactions
2026-01-13 19:33:10,509 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:33:10,535 - INFO - Objective with gapfill database:114.73871061823186; min objective:0.01
2026-01-13 19:33:10,925 - INFO - Objective with gapfill database:114.73871061823165; min objective:0.01
2026-01-13 19:33:11,345 - INFO - Objective with gapfill database:143.82315796111237; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:11,614 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00013_e0': '<', 'rxn00179_c0': '>', 'rxn02320_c0': '<', 'rxn02504_c0': '>', 'rxn00544_c0': '>', 'rxn00898_c0': '>', 'rxn00958_c0': '>', 'rxn02305_c0': '>', 'rxn00470_c0': '>', 'rxn00902_c0': '<', 'rxn01306_c0': '<', 'rxn00789_c0': '<', 'rxn03436_c0': '>', 'rxn01355_c0': '>', 'rxn13022_c0': '>', 'rxn00802_c0': '>', 'rxn02159_c0': '>', 'rxn05466_c0': '>', 'rxn00300_c0': '>', 'rxn02835_c0': '>', 'rxn03435_c0': '<', 'rxn01256_c0': '>', 'rxn03175_c0': '>', 'rxn01000_c0': '>', 'rxn00197_c0': '<', 'rxn12868_c0': '>', 'rxn00863_c0': '>', 'rxn03437_c0': '>', 'rxn00726_c0': '>', 'rxn03108_c0': '>', 'rxn00791_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn00952_c0': '>', 'rxn03841_c0': '>', 'rxn12239_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn02473_c0': '>', 'rxn01434_c0': '>', 'rxn02373_c0': '<', 'rxn00623_c0': '<', 'rxn02507_c0': '>', 'rxn01964_c0': '>', 'rxn02186_c0': '>', 'rxn01603_c0': '>', 'rxn03194_c0': '>', 'rxn16573_c0': '>', 'rxn21862_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn21858_c0': '>', 'rxn40439_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn46124_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn30633_c0': '>', 'rxn28338_c0': '>', 'rxn04551_c0': '>', 'rxn16048_c0': '>', 'rxn37372_c0': '>', 'rxn10095_c0': '>', 'rxn15940_c0': '>', 'rxn08921_c0': '>', 'rxn47493_c0': '>', 'rxn09390_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:11,617 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:33:11,619 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:33:11,621 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:33:11,623 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:11,625 - INFO - integrating rxn: rxn00544_c0
2026-01-13 19:33:11,627 - INFO - integrating rxn: rxn00898_c0
2026-01-13 19:33:11,629 - INFO - integrating rxn: rxn00958_c0
2026-01-13 19:33:11,630 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:33:11,632 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:33:11,634 - INFO - integrating rxn: rxn00902_c0
2026-01-13 19:33:11,636 - INFO - integrating rxn: rxn01306_c0
2026-01-13 19:33:11,637 - INFO - integrating rxn: rxn00789_c0
2026-01-13 19:33:11,639 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:11,641 - INFO - integrating rxn: rxn01355_c0
2026-01-13 19:33:11,643 - INFO - integrating rxn: rxn13022_c0
2026-01-13 19:33:11,644 - INFO - integrating rxn: rxn00802_c0
2026-01-13 19:33:11,646 - INFO - integrating rxn: rxn02159_c0
2026-01-13 19:33:11,647 - INFO - integrating rxn: rxn05466_c0
2026-01-13 19:33:11,649 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:11,651 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:33:11,653 - INFO - integrating rxn: rxn03435_c0
2026-01-13 19:33:11,654 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:33:11,655 - INFO - integrating rxn: rxn03175_c0
2026-01-13 19:33:11,657 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:33:11,659 - INFO - integrating rxn: rxn00197_c0
2026-01-13 19:33:11,660 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:33:11,662 - INFO - integrating rxn: rxn00863_c0
2026-01-13 19:33:11,664 - INFO - integrating rxn: rxn03437_c0
2026-01-13 19:33:11,666 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:33:11,667 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:33:11,669 - INFO - integrating rxn: rxn00791_c0
2026-01-13 19:33:11,671 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:11,672 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:11,673 - INFO - integrating rxn: rxn00952_c0
2026-01-13 19:33:11,675 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:11,676 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:11,678 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:11,680 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:11,681 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:11,683 - INFO - integrating rxn: rxn02473_c0
2026-01-13 19:33:11,685 - INFO - integrating rxn: rxn01434_c0
2026-01-13 19:33:11,686 - INFO - integrating rxn: rxn02373_c0
2026-01-13 19:33:11,688 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:33:11,690 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:33:11,692 - INFO - integrating rxn: rxn01964_c0
2026-01-13 19:33:11,693 - INFO - integrating rxn: rxn02186_c0
2026-01-13 19:33:11,695 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:11,696 - INFO - integrating rxn: rxn03194_c0
2026-01-13 19:33:11,698 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:11,699 - INFO - integrating rxn: rxn21862_c0
2026-01-13 19:33:11,701 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:11,702 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:11,703 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:11,705 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:11,706 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:11,708 - INFO - integrating rxn: rxn21858_c0
2026-01-13 19:33:11,709 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:11,710 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:33:11,712 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:33:11,713 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:33:11,714 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:33:11,716 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:11,718 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:33:11,719 - INFO - integrating rxn: rxn30633_c0
2026-01-13 19:33:11,721 - INFO - integrating rxn: rxn28338_c0
2026-01-13 19:33:11,722 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:33:11,724 - INFO - integrating rxn: rxn16048_c0
2026-01-13 19:33:11,726 - INFO - integrating rxn: rxn37372_c0
2026-01-13 19:33:11,727 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:33:11,728 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:33:11,730 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:11,731 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:11,733 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:33:11,734 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00107_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00069_e0', '<', 'new'], ['EX_cpd00322_e0', '<', 'new'], ['EX_cpd00156_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['EX_cpd00066_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn00530_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn09427_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn05243_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn04464_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00213_c0', '>', 'new'], ['rxn01629_c0', '<', 'new'], ['rxn01740_c0', '<', 'new'], ['rxn05244_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn01484_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn05303_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn09113_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00970_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn05231_c0', '>', 'new'], ['rxn00283_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn00101_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn02213_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn06076_c0', '<', 'new'], ['rxn05301_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn01304_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05669_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn06591_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05306_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn15395_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00048_e0', 'EX_cpd00220_e0', 'EX_cpd00065_e0', 'EX_cpd00058_e0', 'EX_cpd00084_e0', 'EX_cpd00107_e0', 'EX_cpd00063_e0', 'EX_cpd00027_e0', 'EX_cpd00069_e0', 'EX_cpd00322_e0', 'EX_cpd00156_e0', 'EX_cpd00051_e0', 'EX_cpd00066_e0', 'EX_cpd00104_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn00530_c0', 'rxn08710_c0', 'rxn12512_c0', 'rxn00060_c0', 'rxn00100_c0', 'rxn08583_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn09427_c0', 'rxn03918_c0', 'rxn05243_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn05229_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn00029_c0', 'rxn02774_c0', 'rxn04464_c0', 'rxn01505_c0', 'rxn00213_c0', 'rxn01629_c0', 'rxn01740_c0', 'rxn05244_c0', 'rxn03919_c0', 'rxn01484_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn05303_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn08528_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn05237_c0', 'rxn09113_c0', 'rxn08711_c0', 'rxn04413_c0', 'rxn06023_c0', 'rxn00832_c0', 'rxn00970_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn00420_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn05231_c0', 'rxn00283_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn03150_c0', 'rxn00101_c0', 'rxn02303_c0', 'rxn03087_c0', 'rxn05663_c0', 'rxn03538_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn00533_c0', 'rxn02213_c0', 'rxn05226_c0', 'rxn00615_c0', 'rxn00834_c0', 'rxn11702_c0', 'rxn01332_c0', 'rxn01790_c0', 'rxn05651_c0', 'rxn02897_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn06076_c0', 'rxn05301_c0', 'rxn05223_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn01466_c0', 'rxn01304_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05669_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn00138_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn06591_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn05306_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn11274_c0', 'rxn12930_c0', 'rxn12932_c0', 'rxn12940_c0', 'rxn12939_c0', 'rxn12929_c0', 'rxn25637_c0', 'rxn18935_c0', 'rxn25743_c0', 'rxn12928_c0', 'rxn12944_c0', 'rxn12994_c0', 'rxn12943_c0', 'rxn12942_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn19346_c0', 'rxn15395_c0', 'rxn19728_c0', 'rxn20235_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn15060_c0', 'rxn15270_c0', 'rxn20508_c0', 'rxn20627_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn41492_c0', 'rxn44493_c0', 'rxn42332_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd00013_e0', '<', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02320_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn00544_c0', '>', 'new'], ['rxn00898_c0', '>', 'new'], ['rxn00958_c0', '>', 'new'], ['rxn02305_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn00902_c0', '<', 'new'], ['rxn01306_c0', '<', 'new'], ['rxn00789_c0', '<', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn01355_c0', '>', 'new'], ['rxn13022_c0', '>', 'new'], ['rxn00802_c0', '>', 'new'], ['rxn02159_c0', '>', 'new'], ['rxn05466_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn03435_c0', '<', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03175_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn00197_c0', '<', 'new'], ['rxn12868_c0', '>', 'new'], ['rxn00863_c0', '>', 'new'], ['rxn03437_c0', '>', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn00791_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn00952_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn02473_c0', '>', 'new'], ['rxn01434_c0', '>', 'new'], ['rxn02373_c0', '<', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn02507_c0', '>', 'new'], ['rxn01964_c0', '>', 'new'], ['rxn02186_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn03194_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn21862_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn21858_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn16048_c0', '>', 'new'], ['rxn37372_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn09390_c0', '>', 'new']]
2026-01-13 19:33:11,751 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,752 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,754 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,755 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00048_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,756 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,758 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00065_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,759 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,760 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00084_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,761 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00107_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,763 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,764 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00027_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,765 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00069_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,766 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00322_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,767 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00156_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,768 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00051_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,770 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00066_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,771 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,772 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,773 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,774 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,775 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,777 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,778 - INFO - PyruateMinimalAnaerobic/bio1:rxn00530_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,779 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,780 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,781 - INFO - PyruateMinimalAnaerobic/bio1:rxn00060_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,782 - INFO - PyruateMinimalAnaerobic/bio1:rxn00100_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,784 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,785 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:11,786 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,787 - INFO - PyruateMinimalAnaerobic/bio1:rxn09427_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,788 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,789 - INFO - PyruateMinimalAnaerobic/bio1:rxn05243_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,791 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,792 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,793 - INFO - PyruateMinimalAnaerobic/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,794 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,795 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,796 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,797 - INFO - PyruateMinimalAnaerobic/bio1:rxn00029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,799 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:11,800 - INFO - PyruateMinimalAnaerobic/bio1:rxn04464_c0< needed:0.0 with min obj:0.01

c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:12,641 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00048_e0': '<', 'EX_cpd00020_e0': '<', 'rxn00359_c0': '<', 'rxn02320_c0': '<', 'rxn02504_c0': '>', 'rxn00796_c0': '>', 'rxn05469_c0': '>', 'rxn03436_c0': '>', 'rxn00957_c0': '>', 'rxn00300_c0': '>', 'rxn00503_c0': '<', 'rxn00690_c0': '>', 'rxn00333_c0': '>', 'rxn09310_c0': '>', 'rxn03841_c0': '>', 'rxn12239_c0': '>', 'rxn00693_c0': '>', 'rxn05651_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn00623_c0': '<', 'rxn01603_c0': '>', 'rxn00157_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn21860_c0': '>', 'rxn14424_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn46124_c0': '>', 'rxn28338_c0': '>', 'rxn30685_c0': '>', 'rxn41185_c0': '>', 'rxn08154_c0': '>', 'rxn20508_c0': '>', 'rxn15939_c0': '>', 'rxn16341_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:12,644 - INFO - integrating rxn: EX_cpd00048_e0
2026-01-13 19:33:12,646 - INFO - integrating rxn: EX_cpd00020_e0
2026-01-13 19:33:12,648 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:33:12,650 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:33:12,652 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:12,654 - INFO - integrating rxn: rxn00796_c0
2026-01-13 19:33:12,656 - INFO - integrating rxn: rxn05469_c0
2026-01-13 19:33:12,657 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:12,659 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:33:12,661 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:12,663 - INFO - integrating rxn: rxn00503_c0
2026-01-13 19:33:12,664 - INFO - integrating rxn: rxn00690_c0
2026-01-13 19:33:12,666 - INFO - integrating rxn: rxn00333_c0
2026-01-13 19:33:12,668 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:12,670 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:12,671 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:12,673 - INFO - integrating rxn: rxn00693_c0
2026-01-13 19:33:12,674 - INFO - integrating rxn: rxn05651_c0
2026-01-13 19:33:12,676 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:12,678 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:12,680 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:33:12,682 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:12,683 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:33:12,684 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:12,686 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:12,688 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:12,690 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:12,691 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:12,693 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:12,694 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:12,695 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:12,697 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:12,699 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:33:12,701 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:33:12,702 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:33:12,704 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:33:12,706 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:33:12,707 - INFO - integrating rxn: rxn28338_c0
2026-01-13 19:33:12,708 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:12,710 - INFO - integrating rxn: rxn41185_c0
2026-01-13 19:33:12,711 - INFO - integrating rxn: rxn08154_c0
2026-01-13 19:33:12,713 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:33:12,714 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:12,716 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:33:12,718 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:33:12,719 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:33:12,720 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:33:12,721 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:33:12,723 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:33:12,724 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00205_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00129_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00322_e0', '<', 'new'], ['EX_cpd00156_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00364_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00272_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01454_c0', '<', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn05244_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn02229_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05165_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn05596_c0', '<', 'new'], ['rxn00338_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05669_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00030_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00205_e0', 'EX_cpd00058_e0', 'EX_cpd00129_e0', 'EX_cpd00084_e0', 'EX_cpd00063_e0', 'EX_cpd00027_e0', 'EX_cpd00060_e0', 'EX_cpd00099_e0', 'EX_cpd00322_e0', 'EX_cpd00156_e0', 'EX_cpd00104_e0', 'rxn08709_c0', 'rxn00364_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn01636_c0', 'rxn08710_c0', 'rxn12512_c0', 'rxn00100_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00272_c0', 'rxn00907_c0', 'rxn10213_c0', 'rxn02404_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn00830_c0', 'rxn05219_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn01454_c0', 'rxn01501_c0', 'rxn05244_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn02229_c0', 'rxn05645_c0', 'rxn05237_c0', 'rxn04413_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn10094_c0', 'rxn05299_c0', 'rxn09657_c0', 'rxn03150_c0', 'rxn05029_c0', 'rxn03087_c0', 'rxn03538_c0', 'rxn01213_c0', 'rxn05165_c0', 'rxn05618_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn00533_c0', 'rxn06865_c0', 'rxn05226_c0', 'rxn00615_c0', 'rxn01265_c0', 'rxn00834_c0', 'rxn00704_c0', 'rxn11702_c0', 'rxn01790_c0', 'rxn03638_c0', 'rxn02897_c0', 'rxn02056_c0', 'rxn00134_c0', 'rxn00122_c0', 'rxn01602_c0', 'rxn05223_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn05596_c0', 'rxn00338_c0', 'rxn02287_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn01538_c0', 'rxn05669_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn00686_c0', 'rxn01520_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn15167_c0', 'rxn19346_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn17394_c0', 'rxn15060_c0', 'rxn29919_c0', 'rxn08233_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn46249_c0', 'rxn40040_c0', 'rxn20472_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn43975_c0', 'rxn42732_c0', 'rxn41263_c0', 'rxn20839_c0', ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00020_e0', '<', 'new'], ['rxn00359_c0', '<', 'new'], ['rxn02320_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn00796_c0', '>', 'new'], ['rxn05469_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00957_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn00690_c0', '>', 'new'], ['rxn00333_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn00693_c0', '>', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn00157_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn41185_c0', '>', 'new'], ['rxn08154_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:33:12,728 - INFO - cpd11640 not found in model!
2026-01-13 19:33:12,729 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:12,737 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,738 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,739 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,741 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,742 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,743 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00205_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,744 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,745 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00129_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,746 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00084_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,747 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,748 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00027_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,749 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00060_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,750 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,751 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00322_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,753 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00156_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,754 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,755 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,756 - INFO - PyruateMinimalAnaerobic/bio1:rxn00364_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,757 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,758 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,759 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,760 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,761 - INFO - PyruateMinimalAnaerobic/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,762 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,763 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,765 - INFO - PyruateMinimalAnaerobic/bio1:rxn00100_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,766 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,767 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,768 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,769 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,770 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,771 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,772 - INFO - PyruateMinimalAnaerobic/bio1:rxn00272_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,773 - INFO - PyruateMinimalAnaerobic/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,774 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,776 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,777 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,778 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,779 - INFO - PyruateMinimalAnaerobic/bio1:rxn00830_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,780 - INFO - PyruateMinimalAnaerobic/bio1:rxn05219_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,781 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,782 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,783 - INFO - PyruateMinimalAnaerobic/bio1:rxn01454_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,784 - INFO - PyruateMinimalAnaerobic/bio1:rxn01501_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,785 - INFO - PyruateMinimalAnaerobic/bio1:rxn05244_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,787 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,788 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,789 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,790 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,791 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,792 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,793 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,794 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,795 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,796 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,797 - INFO - PyruateMinimalAnaerobic/bio1:rxn02229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,798 - INFO - PyruateMinimalAnaerobic/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,800 - INFO - PyruateMinimalAnaerobic/bio1:rxn05237_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,801 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,802 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,803 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,804 - INFO - PyruateMinimalAnaerobic/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,805 - INFO - PyruateMinimalAnaerobic/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,806 - INFO - PyruateMinimalAnaerobic/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,807 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,808 - INFO - PyruateMinimalAnaerobic/bio1:rxn05029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,809 - INFO - PyruateMinimalAnaerobic/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,811 - INFO - PyruateMinimalAnaerobic/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,812 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,813 - INFO - PyruateMinimalAnaerobic/bio1:rxn05165_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,814 - INFO - PyruateMinimalAnaerobic/bio1:rxn05618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,816 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,817 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,818 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,819 - INFO - PyruateMinimalAnaerobic/bio1:rxn00533_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:12,820 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:12,821 - INFO - PyruateMinimalAnaerobic/bio1:rxn05226_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:33:13,121 - INFO - Objective with gapfill database:114.73871061823186; min objective:0.01
2026-01-13 19:33:13,148 - INFO - Objective with gapfill database:114.73871061823313; min objective:0.01
2026-01-13 19:33:13,448 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn09128_c0': '<', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05645_c0': '>', 'rxn00832_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn00644_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn24212_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15081_c0': '>', 'rxn15550_c0': '>', 'rxn14070_c0': '>', 'rxn15072_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40203_c0': '>', 'rxn40292_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn47875_c0': '>', 'rxn40674_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:13,452 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:33:13,454 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:33:13,456 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:33:13,458 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:33:13,460 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:33:13,462 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:33:13,463 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:33:13,465 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:33:13,467 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:33:13,469 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:33:13,471 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:33:13,472 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:33:13,474 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:33:13,476 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:33:13,477 - INFO - integrating rxn: rxn09128_c0
2026-01-13 19:33:13,479 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:33:13,481 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:33:13,483 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:33:13,484 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:33:13,486 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:33:13,487 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:33:13,489 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:33:13,491 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:33:13,492 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:33:13,494 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:33:13,495 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:33:13,497 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:33:13,499 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:33:13,501 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:33:13,502 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:33:13,504 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:33:13,506 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:33:13,508 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:33:13,509 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:33:13,511 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:33:13,513 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:33:13,514 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:13,516 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:33:13,517 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:33:13,519 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:13,521 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:13,523 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:33:13,524 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:33:13,526 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:13,528 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:13,530 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:13,532 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:13,534 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:13,535 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:13,537 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:33:13,539 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:13,540 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:13,542 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:33:13,544 - INFO - integrating rxn: rxn00644_c0
2026-01-13 19:33:13,545 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:33:13,547 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:33:13,549 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:33:13,550 - INFO - integrating rxn: rxn24212_c0
2026-01-13 19:33:13,552 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:33:13,553 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:33:13,555 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:13,557 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:13,559 - INFO - integrating rxn: rxn15081_c0
2026-01-13 19:33:13,560 - INFO - integrating rxn: rxn15550_c0
2026-01-13 19:33:13,562 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:33:13,564 - INFO - integrating rxn: rxn15072_c0
2026-01-13 19:33:13,565 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:13,567 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:33:13,569 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:33:13,570 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:33:13,572 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:13,574 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:13,576 - INFO - integrating rxn: rxn40203_c0
2026-01-13 19:33:13,578 - INFO - integrating rxn: rxn40292_c0
2026-01-13 19:33:13,579 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:33:13,581 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:33:13,583 - INFO - integrating rxn: rxn47875_c0
2026-01-13 19:33:13,584 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:13,586 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:33:13,587 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn09128_c0', '<', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn24212_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn15081_c0', '>', 'new'], ['rxn15550_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15072_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40203_c0', '>', 'new'], ['rxn40292_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn47875_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:33:13,628 - INFO - Objective with gapfill database:137.2170684931733; min objective:0.01
2026-01-13 19:33:13,650 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,653 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,655 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,657 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,659 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,662 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,664 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,666 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,668 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,670 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,672 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,674 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,677 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,679 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,678 - INFO - Objective with gapfill database:143.82315796111237; min objective:0.01
2026-01-13 19:33:13,681 - INFO - AuxoMedia/bio1:rxn09128_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,683 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,684 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,686 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,688 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,691 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,693 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,695 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,697 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,699 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,701 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,702 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,704 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,706 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,708 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,709 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,711 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,713 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,714 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,716 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,718 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,721 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,723 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,725 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,727 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,730 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,738 - INFO - rxn12932_c0> not needed:14.909858436089008
2026-01-13 19:33:13,742 - INFO - rxn12940_c0> not needed:14.909858436088495
2026-01-13 19:33:13,744 - INFO - rxn12929_c0> not needed:14.909858436089166
2026-01-13 19:33:13,745 - INFO - rxn25637_c0> not needed:14.909858436089166
2026-01-13 19:33:13,746 - INFO - rxn18935_c0> not needed:14.909858436089166
2026-01-13 19:33:13,748 - INFO - rxn25638_c0> not needed:14.909858436089166
2026-01-13 19:33:13,753 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,760 - INFO - rxn12942_c0> not needed:14.909858436088676
2026-01-13 19:33:13,765 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,770 - INFO - rxn46124_c0> not needed:14.909858436088692
2026-01-13 19:33:13,774 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,774 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn02504_c0': '>', 'rxn02305_c0': '>', 'rxn01306_c0': '<', 'rxn03436_c0': '>', 'rxn00957_c0': '>', 'rxn00300_c0': '>', 'rxn09180_c0': '>', 'rxn02835_c0': '>', 'rxn01300_c0': '>', 'rxn12868_c0': '>', 'rxn01345_c0': '>', 'rxn01303_c0': '>', 'rxn01539_c0': '<', 'rxn00048_c0': '>', 'rxn03108_c0': '>', 'rxn02200_c0': '>', 'rxn00290_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn03841_c0': '>', 'rxn12239_c0': '>', 'rxn01257_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn21859_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn21860_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn15166_c0': '>', 'rxn30633_c0': '>', 'rxn28338_c0': '>', 'rxn16048_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn37372_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn15939_c0': '>', 'rxn47493_c0': '>', 'rxn10121_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:13,776 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,777 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:13,780 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:33:13,781 - INFO - integrating rxn: rxn01306_c0
2026-01-13 19:33:13,783 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:13,784 - INFO - rxn19346_c0> not needed:14.90985843608841
2026-01-13 19:33:13,784 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:33:13,786 - INFO - rxn00644_c0> not needed:14.90985843608841
2026-01-13 19:33:13,786 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:13,788 - INFO - integrating rxn: rxn09180_c0
2026-01-13 19:33:13,789 - INFO - rxn25042_c0> not needed:14.90985843608867
2026-01-13 19:33:13,789 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:33:13,790 - INFO - rxn19766_c0> not needed:14.90985843608867
2026-01-13 19:33:13,791 - INFO - integrating rxn: rxn01300_c0
2026-01-13 19:33:13,791 - INFO - rxn19764_c0> not needed:14.90985843608867
2026-01-13 19:33:13,793 - INFO - rxn24212_c0> not needed:14.90985843608867
2026-01-13 19:33:13,793 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:33:13,794 - INFO - integrating rxn: rxn01345_c0
2026-01-13 19:33:13,796 - INFO - integrating rxn: rxn01303_c0
2026-01-13 19:33:13,797 - INFO - AuxoMedia/bio1:rxn19728_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,798 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:13,799 - INFO - AuxoMedia/bio1:rxn20235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,799 - INFO - integrating rxn: rxn00048_c0
2026-01-13 19:33:13,801 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:33:13,801 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,802 - INFO - integrating rxn: rxn02200_c0
2026-01-13 19:33:13,803 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,804 - INFO - integrating rxn: rxn00290_c0
2026-01-13 19:33:13,806 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:13,807 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:13,809 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:13,810 - INFO - rxn15081_c0> not needed:14.909858436087864
2026-01-13 19:33:13,811 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:13,812 - INFO - rxn15550_c0> not needed:14.909858436087987
2026-01-13 19:33:13,812 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:13,814 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:13,815 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:13,816 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,817 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:13,818 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:13,820 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:13,821 - INFO - rxn15072_c0> not needed:14.90985843608885
2026-01-13 19:33:13,821 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:13,823 - INFO - rxn15060_c0> not needed:14.90985843608885
2026-01-13 19:33:13,823 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:13,824 - INFO - rxn15064_c0> not needed:14.90985843608885
2026-01-13 19:33:13,825 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:33:13,825 - INFO - rxn11285_c0> not needed:14.90985843608885
2026-01-13 19:33:13,826 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:13,827 - INFO - rxn20508_c0> not needed:14.90985843608885
2026-01-13 19:33:13,828 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:13,829 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:13,831 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:13,831 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:-4.601288276413882e-13 with min obj:0.01
2026-01-13 19:33:13,832 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:13,833 - INFO - AuxoMedia/bio1:rxn15939_c0> needed:7.022046365611548e-13 with min obj:0.01
2026-01-13 19:33:13,834 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:13,835 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:13,836 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:13,838 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:13,839 - INFO - rxn40203_c0> not needed:14.909858436088456
2026-01-13 19:33:13,840 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:13,841 - INFO - rxn40292_c0> not needed:14.909858436088603
2026-01-13 19:33:13,841 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:33:13,842 - INFO - rxn41492_c0> not needed:14.909858436088603
2026-01-13 19:33:13,843 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:33:13,844 - INFO - rxn44493_c0> not needed:14.909858436088603
2026-01-13 19:33:13,844 - INFO - integrating rxn: rxn30633_c0

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn09128_c0': '<', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05645_c0': '>', 'rxn00832_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn00644_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn24212_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15081_c0': '>', 'rxn15550_c0': '>', 'rxn14070_c0': '>', 'rxn15072_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40203_c0': '>', 'rxn40292_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn47875_c0': '>', 'rxn40674_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:13,874 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn09128_c0', '<', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:33:13,874 - INFO -     Added 52 reactions
2026-01-13 19:33:13,875 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:33:13,882 - INFO - EX_cpd00393_e0< not needed:2.711930316964637
2026-01-13 19:33:13,884 - INFO - EX_cpd00119_e0< not needed:2.711930316964637
2026-01-13 19:33:13,886 - INFO - EX_cpd00220_e0< not needed:2.711930316964637
2026-01-13 19:33:13,889 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,891 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00034_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,892 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,894 - INFO - EX_cpd00060_e0< not needed:2.7119303169646343
2026-01-13 19:33:13,898 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,900 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,901 - INFO - PyruateMinimalAnaerobic/bio1:rxn00359_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,903 - INFO - PyruateMinimalAnaerobic/bio1:rxn02000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,905 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,906 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,908 - INFO - PyruateMinimalAnaerobic/bio1:rxn00179_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,909 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,911 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,913 - INFO - PyruateMinimalAnaerobic/bio1:rxn04996_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,915 - INFO - PyruateMinimalAnaerobic/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,916 - INFO - PyruateMinimalAnaerobic/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,918 - INFO - PyruateMinimalAnaerobic/bio1:rxn02988_c0< needed:-1.0290828447587443e-12 with min obj:0.01
2026-01-13 19:33:13,920 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,921 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,922 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,924 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,925 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,927 - INFO - PyruateMinimalAnaerobic/bio1:rxn00060_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,929 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,930 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,932 - INFO - PyruateMinimalAnaerobic/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,933 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,934 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,936 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,937 - INFO - PyruateMinimalAnaerobic/bio1:rxn00579_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,939 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,941 - INFO - PyruateMinimalAnaerobic/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,942 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,944 - INFO - PyruateMinimalAnaerobic/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,945 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,947 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,948 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,951 - INFO - rxn05219_c0> not needed:2.711930316964632
2026-01-13 19:33:13,954 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,956 - INFO - PyruateMinimalAnaerobic/bio1:rxn00029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,958 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,959 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,961 - INFO - PyruateMinimalAnaerobic/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,962 - INFO - PyruateMinimalAnaerobic/bio1:rxn00237_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,964 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,966 - INFO - PyruateMinimalAnaerobic/bio1:rxn10124_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,967 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,968 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,970 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,971 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,973 - INFO - PyruateMinimalAnaerobic/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,974 - INFO - PyruateMinimalAnaerobic/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,976 - INFO - PyruateMinimalAnaerobic/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,977 - INFO - PyruateMinimalAnaerobic/bio1:rxn01972_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,979 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,981 - INFO - PyruateMinimalAnaerobic/bio1:rxn13647_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,982 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:13,984 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,986 - INFO - rxn00966_c0< not needed:2.7119303169646307
2026-01-13 19:33:13,990 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,991 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,994 - INFO - rxn05645_c0> not needed:2.7119303169646436
2026-01-13 19:33:13,996 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:13,998 - INFO - PyruateMinimalAnaerobic/bio1:rxn02402_c0< needed:3.047472162799147e-13 with min obj:0.01
2026-01-13 19:33:13,999 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,001 - INFO - PyruateMinimalAnaerobic/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,003 - INFO - PyruateMinimalAnaerobic/bio1:rxn00611_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,004 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,007 - INFO - rxn05299_c0> not needed:2.7119303169646356
2026-01-13 19:33:14,009 - INFO - PyruateMinimalAnaerobic/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,010 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,012 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,014 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,015 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,017 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,018 - INFO - PyruateMinimalAnaerobic/bio1:rxn05029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,020 - INFO - PyruateMinimalAnaerobic/bio1:rxn02285_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,021 - INFO - PyruateMinimalAnaerobic/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,023 - INFO - PyruateMinimalAnaerobic/bio1:rxn05315_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,024 - INFO - PyruateMinimalAnaerobic/bio1:rxn03907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,026 - INFO - PyruateMinimalAnaerobic/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,028 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,030 - INFO - rxn02304_c0> not needed:2.7119303169646423
2026-01-13 19:33:14,033 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,034 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,036 - INFO - PyruateMinimalAnaerobic/bio1:rxn01512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,038 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,039 - INFO - PyruateMinimalAnaerobic/bio1:rxn04113_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,041 - INFO - PyruateMinimalAnaerobic/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,042 - INFO - PyruateMinimalAnaerobic/bio1:rxn08130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,044 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,046 - INFO - PyruateMinimalAnaerobic/bio1:rxn05117_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,047 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,049 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,050 - INFO - PyruateMinimalAnaerobic/bio1:rxn00346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,052 - INFO - PyruateMinimalAnaerobic/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,053 - INFO - PyruateMinimalAnaerobic/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,055 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,056 - INFO - PyruateMinimalAnaerobic/bio1:rxn02003_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,058 - INFO - PyruateMinimalAnaerobic/bio1:rxn00130_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,059 - INFO - PyruateMinimalAnaerobic/bio1:rxn00912_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,061 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,062 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,064 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,066 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,067 - INFO - PyruateMinimalAnaerobic/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,069 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,070 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,072 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,074 - INFO - rxn05255_c0> not needed:2.711930316964643
2026-01-13 19:33:14,077 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,078 - INFO - PyruateMinimalAnaerobic/bio1:rxn00138_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,080 - INFO - PyruateMinimalAnaerobic/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,082 - INFO - PyruateMinimalAnaerobic/bio1:rxn00623_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,083 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,085 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,087 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,089 - INFO - PyruateMinimalAnaerobic/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,090 - INFO - PyruateMinimalAnaerobic/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,091 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,093 - INFO - PyruateMinimalAnaerobic/bio1:rxn01513_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,095 - INFO - PyruateMinimalAnaerobic/bio1:rxn00117_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,097 - INFO - PyruateMinimalAnaerobic/bio1:rxn01520_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,098 - INFO - PyruateMinimalAnaerobic/bio1:rxn00399_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,100 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,101 - INFO - PyruateMinimalAnaerobic/bio1:rxn16218_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,103 - INFO - PyruateMinimalAnaerobic/bio1:rxn16217_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,106 - INFO - rxn14424_c0> not needed:1.7074929678236979
2026-01-13 19:33:14,108 - INFO - PyruateMinimalAnaerobic/bio1:rxn11274_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,110 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,112 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,116 - INFO - rxn00154_c0> not needed:1.3416016175757663
2026-01-13 19:33:14,120 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,122 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,123 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,125 - INFO - rxn04551_c0> not needed:1.3416016175757568
2026-01-13 19:33:14,129 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,132 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,133 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,135 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,139 - INFO - rxn11285_c0> not needed:1.2890759690244782
2026-01-13 19:33:14,144 - INFO - PyruateMinimalAnaerobic/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,146 - INFO - PyruateMinimalAnaerobic/bio1:rxn20508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,149 - INFO - rxn15940_c0> not needed:1.2890759690244793
2026-01-13 19:33:14,152 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,155 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,156 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,158 - INFO - PyruateMinimalAnaerobic/bio1:rxn14428_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,160 - INFO - rxn14423_c0> not needed:1.2890759690244782
2026-01-13 19:33:14,161 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:33:14,162 - INFO -   Running ATP safety check...

c0

2026-01-13 19:33:14,344 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn08954_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn04413_c0': '>', 'rxn10094_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn16218_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn12930_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn13741_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40040_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn09390_c0': '>', 'rxn40324_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:14,347 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:33:14,349 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:33:14,351 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:33:14,351 - INFO - Objective with gapfill database:137.2170684931731; min objective:0.01
2026-01-13 19:33:14,353 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:33:14,355 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:33:14,357 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:33:14,359 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:33:14,360 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:33:14,362 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:33:14,364 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:33:14,365 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:33:14,367 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:33:14,369 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:33:14,371 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:33:14,372 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:33:14,374 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:33:14,376 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:33:14,377 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:33:14,379 - INFO - integrating rxn: rxn05463_c0
2026-01-13 19:33:14,381 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:33:14,382 - INFO - integrating rxn: rxn10094_c0
2026-01-13 19:33:14,384 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:33:14,386 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:33:14,387 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:33:14,389 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:33:14,390 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:33:14,392 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:33:14,394 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:33:14,395 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:33:14,396 - INFO - Objective with gapfill database:143.82315796111217; min objective:0.01
2026-01-13 19:33:14,397 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:14,398 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:33:14,400 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:14,402 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:33:14,404 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:14,405 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:33:14,407 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:14,408 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:14,410 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:14,412 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:14,414 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:14,415 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:14,417 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:33:14,418 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:33:14,420 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:14,421 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:14,423 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:14,425 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:14,427 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:14,429 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:33:14,430 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:33:14,432 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:33:14,434 - INFO - integrating rxn: rxn40142_c0
2026-01-13 19:33:14,436 - INFO - integrating rxn: rxn01736_c0
2026-01-13 19:33:14,437 - INFO - integrating rxn: rxn00644_c0
2026-01-13 19:33:14,439 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:33:14,441 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:33:14,442 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:33:14,444 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:33:14,446 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:33:14,447 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:14,449 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:14,451 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:33:14,453 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:14,454 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:33:14,456 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:33:14,457 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:14,459 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:33:14,461 - INFO - integrating rxn: rxn13741_c0
2026-01-13 19:33:14,462 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:33:14,464 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:14,466 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:14,467 - INFO - integrating rxn: rxn40040_c0
2026-01-13 19:33:14,469 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:14,471 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:14,472 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:33:14,474 - INFO - integrating rxn: rxn40324_c0
2026-01-13 19:33:14,476 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:33:14,477 - INFO - Full solution: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn13741_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn40324_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:33:14,547 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,550 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,552 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,554 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,557 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,558 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,560 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,562 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,564 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,566 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,568 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,570 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,572 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,575 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,576 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,579 - INFO - AuxoMedia/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,580 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,583 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,585 - INFO - AuxoMedia/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,587 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,588 - INFO - AuxoMedia/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,590 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,593 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,595 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:14,597 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,599 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,601 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,603 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,605 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,607 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,609 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,611 - INFO - AuxoMedia/bio1:rxn01603_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,617 - INFO - rxn21635_c0> not needed:14.725135073581054
2026-01-13 19:33:14,619 - INFO - rxn22816_c0> not needed:14.72513507358136
2026-01-13 19:33:14,621 - INFO - rxn16218_c0> not needed:14.725135073581017
2026-01-13 19:33:14,623 - INFO - rxn22817_c0> not needed:14.725135073581685
2026-01-13 19:33:14,624 - INFO - rxn20834_c0> not needed:14.725135073581685
2026-01-13 19:33:14,628 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,636 - INFO - rxn25637_c0> not needed:14.725135073581706
2026-01-13 19:33:14,638 - INFO - rxn18935_c0> not needed:14.725135073581702
2026-01-13 19:33:14,639 - INFO - rxn25638_c0> not needed:14.725135073581702
2026-01-13 19:33:14,641 - INFO - rxn12944_c0> not needed:14.725135073581907
2026-01-13 19:33:14,643 - INFO - rxn12994_c0> not needed:14.725135073581985
2026-01-13 19:33:14,649 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,651 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,653 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,655 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,663 - INFO - rxn11251_c0> not needed:14.72513507358178
2026-01-13 19:33:14,665 - INFO - rxn47267_c0> not needed:14.725135073581647
2026-01-13 19:33:14,666 - INFO - rxn41387_c0> not needed:14.725135073581647
2026-01-13 19:33:14,670 - INFO - rxn19346_c0> not needed:14.725135073581303
2026-01-13 19:33:14,673 - INFO - rxn40142_c0> not needed:14.725135073581804
2026-01-13 19:33:14,674 - INFO - rxn01736_c0> not needed:14.72513507358115
2026-01-13 19:33:14,676 - INFO - rxn00644_c0> not needed:14.72513507358115
2026-01-13 19:33:14,677 - INFO - rxn25042_c0> not needed:14.72513507358115
2026-01-13 19:33:14,679 - INFO - rxn19766_c0> not needed:14.72513507358115
2026-01-13 19:33:14,680 - INFO - rxn19764_c0> not needed:14.72513507358115
2026-01-13 19:33:14,683 - INFO - AuxoMedia/bio1:rxn19728_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,685 - INFO - AuxoMedia/bio1:rxn20235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,687 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,689 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,695 - INFO - rxn14070_c0> not needed:14.725135073582132
2026-01-13 19:33:14,696 - INFO - rxn15060_c0> not needed:14.725135073581129
2026-01-13 19:33:14,698 - INFO - rxn29919_c0> not needed:14.725135073581129
2026-01-13 19:33:14,699 - INFO - rxn15064_c0> not needed:14.725135073581129
2026-01-13 19:33:14,702 - INFO - AuxoMedia/bio1:rxn30685_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,707 - INFO - rxn11285_c0> not needed:14.725135073581418
2026-01-13 19:33:14,708 - INFO - rxn13741_c0> not needed:14.725135073581148
2026-01-13 19:33:14,710 - INFO - rxn20508_c0> not needed:14.725135073581148
2026-01-13 19:33:14,713 - INFO - rxn30917_c0> not needed:14.725135073581686
2026-01-13 19:33:14,714 - INFO - rxn15939_c0> not needed:14.725135073581686
2026-01-13 19:33:14,716 - INFO - rxn40040_c0> not needed:14.725135073581686
2026-01-13 19:33:14,720 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,725 - INFO - rxn08921_c0> not needed:14.725135073581725
2026-01-13 19:33:14,728 - INFO - rxn09390_c0> not needed:14.72513507358084
2026-01-13 19:33:14,732 - INFO - AuxoMedia/bio1:rxn40324_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,734 - INFO - AuxoMedia/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:14,738 - INFO - Unneeded: [['rxn21635_c0', '>', 'new', 100, None], ['rxn22816_c0', '>', 'new', 100, None], ['rxn16218_c0', '>', 'new', 100, None], ['rxn22817_c0', '>', 'new', 100, None], ['rxn20834_c0', '>', 'new', 100, None], ['rxn25637_c0', '>', 'new', 100, None], ['rxn18935_c0', '>', 'new', 100, None], ['rxn25638_c0', '>', 'new', 100, None], ['rxn12944_c0', '>', 'new', 100, None], ['rxn12994_c0', '>', 'new', 100, None], ['rxn11251_c0', '>', 'new', 100, None], ['rxn47267_c0', '>', 'new', 100, None], ['rxn41387_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn40142_c0', '>', 'new', 100, None], ['rxn01736_c0', '>', 'new', 100, None], ['rxn00644_c0', '>', 'new', 100, None], ['rxn25042_c0', '>', 'new', 100, None], ['rxn19766_c0', '>', 'new', 100, None], ['rxn19764_c0', '>', 'new', 100, None], ['rxn14070_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn11285_c0', '>', 'new', 100, None], ['rxn13741_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn30917_c0', '>', 'new', 100, None], ['rxn15939_c0', '>', 'new', 100, None], ['rxn40040_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn09390_c0', '>', 'new', 100, None]]
2026-01-13 19:33:14,755 - INFO - Growth: 14.725135073581244 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn08954_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn04413_c0': '>', 'rxn10094_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn16218_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn12930_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn13741_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40040_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn09390_c0': '>', 'rxn40324_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:14,760 - INFO - Cumulative: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn40324_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:33:14,760 - INFO -     Added 45 reactions
2026-01-13 19:33:14,761 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:15,315 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,330 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,338 - INFO - cpd00363 not found in model!
2026-01-13 19:33:15,339 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:15,342 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,352 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,361 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,371 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,381 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,392 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,401 - INFO - cpd00159 not found in model!
2026-01-13 19:33:15,403 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:15,406 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,417 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,428 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,438 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,452 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,462 - INFO - cpd00363 not found in model!
2026-01-13 19:33:15,463 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:15,466 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,478 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,488 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,498 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,509 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,519 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,527 - INFO - cpd00159 not found in model!
2026-01-13 19:33:15,528 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:15,531 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,542 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,552 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,561 - INFO - cpd00130 not found in model!
2026-01-13 19:33:15,561 - INFO - Media compound: cpd00130 not found in model.
2026-01-13 19:33:15,565 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,573 - INFO - cpd00075 not found in model!
2026-01-13 19:33:15,574 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:15,577 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,585 - INFO - cpd00209 not found in model!
2026-01-13 19:33:15,586 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:15,588 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,597 - INFO - cpd00418 not found in model!
2026-01-13 19:33:15,597 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:15,600 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,608 - INFO - cpd00075 not found in model!
2026-01-13 19:33:15,609 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:15,612 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,621 - INFO - cpd00209 not found in model!
2026-01-13 19:33:15,622 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:15,625 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,633 - INFO - cpd00418 not found in model!
2026-01-13 19:33:15,634 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:15,637 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,645 - INFO - cpd00075 not found in model!
2026-01-13 19:33:15,646 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:15,648 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,656 - INFO - cpd00209 not found in model!
2026-01-13 19:33:15,657 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:15,659 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,666 - INFO - Objective with gapfill database:114.73871061823313; min objective:0.01
2026-01-13 19:33:15,667 - INFO - cpd00418 not found in model!
2026-01-13 19:33:15,667 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:15,671 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,679 - INFO - cpd08021 not found in model!
2026-01-13 19:33:15,680 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:15,682 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,690 - INFO - cpd00811 not found in model!
2026-01-13 19:33:15,690 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:15,693 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,701 - INFO - cpd08021 not found in model!
2026-01-13 19:33:15,702 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:15,704 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,712 - INFO - cpd00811 not found in model!
2026-01-13 19:33:15,714 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:15,716 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,728 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,738 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,747 - INFO - cpd11640 not found in model!
2026-01-13 19:33:15,748 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:15,751 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,759 - INFO - cpd11640 not found in model!
2026-01-13 19:33:15,760 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:15,763 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,771 - INFO - cpd11640 not found in model!
2026-01-13 19:33:15,772 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:15,775 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,782 - INFO - cpd00159 not found in model!
2026-01-13 19:33:15,783 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:15,784 - INFO - cpd11640 not found in model!
2026-01-13 19:33:15,784 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:15,787 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,797 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,804 - INFO - cpd00159 not found in model!
2026-01-13 19:33:15,805 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:15,808 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,815 - INFO - cpd11640 not found in model!
2026-01-13 19:33:15,816 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:15,819 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,828 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,835 - INFO - cpd11632 not found in model!
2026-01-13 19:33:15,836 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:33:15,839 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,846 - INFO - cpd08701 not found in model!
2026-01-13 19:33:15,847 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:33:15,848 - INFO - cpd01024 not found in model!
2026-01-13 19:33:15,848 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:15,851 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,859 - INFO - cpd01024 not found in model!
2026-01-13 19:33:15,860 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:15,863 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,872 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,880 - INFO - cpd11640 not found in model!
2026-01-13 19:33:15,881 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:15,884 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,891 - INFO - cpd11640 not found in model!
2026-01-13 19:33:15,892 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:15,892 - INFO - cpd00187 not found in model!
2026-01-13 19:33:15,893 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:33:15,896 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,901 - INFO - Objective with gapfill database:137.2170684931733; min objective:0.01
2026-01-13 19:33:15,903 - INFO - cpd11640 not found in model!
2026-01-13 19:33:15,904 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:15,905 - INFO - cpd00425 not found in model!
2026-01-13 19:33:15,906 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:33:15,908 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:15,916 - INFO - cpd11640 not found in model!
2026-01-13 19:33:15,917 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:15,917 - INFO - cpd00441 not found in model!
2026-01-13 19:33:15,918 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:33:15,920 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,126 - INFO - Objective with gapfill database:137.21706849317346; min objective:0.01
2026-01-13 19:33:16,128 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,141 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,149 - INFO - cpd00363 not found in model!
2026-01-13 19:33:16,149 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:16,152 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,161 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,169 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,177 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,186 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,195 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,202 - INFO - cpd00159 not found in model!
2026-01-13 19:33:16,203 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:16,206 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,213 - INFO - cpd00221 not found in model!
2026-01-13 19:33:16,214 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:33:16,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,233 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,248 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,253 - INFO - Initial solution: {'reversed': {'rxn00558_c0': '<'}, 'new': {'EX_cpd15378_e0': '>', 'rxn00359_c0': '<', 'rxn02305_c0': '>', 'rxn00910_c0': '<', 'rxn00789_c0': '<', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn00336_c0': '<', 'rxn01345_c0': '>', 'rxn12376_c0': '<', 'rxn01573_c0': '<', 'rxn00804_c0': '<', 'rxn00505_c0': '>', 'rxn02508_c0': '>', 'rxn00048_c0': '>', 'rxn03108_c0': '>', 'rxn01986_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn00502_c0': '<', 'rxn01257_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn21857_c0': '>', 'rxn16573_c0': '>', 'rxn21863_c0': '>', 'rxn22816_c0': '>', 'rxn21862_c0': '>', 'rxn11279_c0': '>', 'rxn21859_c0': '>', 'rxn10504_c0': '>', 'rxn47768_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn22817_c0': '>', 'rxn21858_c0': '>', 'rxn20834_c0': '>', 'rxn21861_c0': '>', 'rxn21860_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn24212_c0': '>', 'rxn16114_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn15940_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:16,256 - INFO - cpd00363 not found in model!
2026-01-13 19:33:16,256 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:16,257 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:16,258 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:33:16,259 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,260 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:33:16,261 - INFO - integrating rxn: rxn00910_c0
2026-01-13 19:33:16,263 - INFO - integrating rxn: rxn00789_c0
2026-01-13 19:33:16,265 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:16,267 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:16,268 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,268 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:33:16,270 - INFO - integrating rxn: rxn01345_c0
2026-01-13 19:33:16,271 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:16,273 - INFO - integrating rxn: rxn01573_c0
2026-01-13 19:33:16,274 - INFO - integrating rxn: rxn00804_c0
2026-01-13 19:33:16,276 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,276 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:33:16,277 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:33:16,279 - INFO - integrating rxn: rxn00048_c0
2026-01-13 19:33:16,281 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:33:16,282 - INFO - integrating rxn: rxn01986_c0
2026-01-13 19:33:16,284 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:16,284 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,286 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:16,288 - INFO - integrating rxn: rxn00502_c0
2026-01-13 19:33:16,289 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:16,290 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:16,292 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:16,293 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,293 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:16,295 - INFO - integrating rxn: rxn21857_c0
2026-01-13 19:33:16,297 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:16,298 - INFO - integrating rxn: rxn21863_c0
2026-01-13 19:33:16,300 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:16,302 - INFO - integrating rxn: rxn21862_c0
2026-01-13 19:33:16,302 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,303 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:16,305 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:33:16,306 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:16,308 - INFO - integrating rxn: rxn47768_c0
2026-01-13 19:33:16,309 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:16,310 - INFO - cpd00159 not found in model!
2026-01-13 19:33:16,310 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:16,311 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:16,312 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:16,313 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,313 - INFO - integrating rxn: rxn21858_c0
2026-01-13 19:33:16,315 - INFO - integrating rxn: rxn20834_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:16,625 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01

2026-01-13 19:33:16,627 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,630 - INFO - cpd11640 not found in model!
2026-01-13 19:33:16,630 - INFO - rxn15060_c0> not needed:3.3081043606361082
2026-01-13 19:33:16,630 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:16,631 - INFO - cpd00187 not found in model!
2026-01-13 19:33:16,631 - INFO - rxn29919_c0> not needed:3.3081043606360865
2026-01-13 19:33:16,632 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:33:16,634 - INFO - PyruateMinimalAnaerobic/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,635 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,635 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,639 - INFO - Objective with gapfill database:137.2170684931731; min objective:0.01
2026-01-13 19:33:16,642 - INFO - cpd11640 not found in model!
2026-01-13 19:33:16,642 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:16,643 - INFO - cpd00425 not found in model!
2026-01-13 19:33:16,644 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:33:16,645 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:16,647 - INFO - rxn15939_c0> not needed:3.3081043606360447
2026-01-13 19:33:16,650 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,651 - INFO - Objective with gapfill database:143.82315796111217; min objective:0.01
2026-01-13 19:33:16,653 - INFO - cpd11640 not found in model!
2026-01-13 19:33:16,653 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:16,654 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,654 - INFO - cpd00441 not found in model!
2026-01-13 19:33:16,655 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:33:16,655 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:33:16,656 - INFO -   Running ATP safety check...

c0

2026-01-13 19:33:16,657 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:16,684 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn04139_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn19346_c0': '>', 'rxn11162_c0': '>', 'rxn16141_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15550_c0': '>', 'rxn15072_c0': '>', 'rxn16622_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn29260_c0': '>', 'rxn09390_c0': '>', 'rxn14423_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:16,687 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:33:16,689 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:33:16,690 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:16,691 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:33:16,692 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:33:16,692 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:16,694 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:33:16,695 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:16,696 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:33:16,697 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:33:16,699 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:33:16,701 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:33:16,702 - INFO - EX_cpd00104_e0< not needed:15.734222606679895
2026-01-13 19:33:16,703 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:33:16,704 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:33:16,706 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:33:16,707 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,708 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:33:16,709 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:33:16,710 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,711 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:33:16,713 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:33:16,712 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,714 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:33:16,715 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,716 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:33:16,717 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,717 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:33:16,719 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:33:16,719 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,721 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:33:16,721 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,722 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:33:16,723 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,724 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:33:16,725 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,726 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:33:16,727 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,727 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:33:16,729 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:33:16,729 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,731 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:33:16,731 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,732 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:33:16,733 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,734 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:33:16,735 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,735 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:33:16,737 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,737 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:33:16,739 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:33:16,739 - INFO - AuxoMedia/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,740 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:33:16,741 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,741 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:33:16,743 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:33:16,744 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:16,745 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:33:16,746 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,747 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:33:16,748 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,748 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:33:16,749 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:33:16,750 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,751 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:33:16,752 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,752 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:16,754 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:33:16,754 - INFO - AuxoMedia/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,755 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:33:16,756 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:16,757 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:16,759 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:33:16,760 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:33:16,761 - INFO - rxn05223_c0> not needed:15.734222606679893
2026-01-13 19:33:16,762 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:33:16,764 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:16,765 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,766 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:16,767 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,767 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:33:16,769 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,769 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:33:16,771 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:33:16,771 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,772 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:16,773 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,774 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:16,775 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:33:16,775 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,777 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:16,777 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,778 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:16,779 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,780 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:16,782 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:33:16,784 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:33:16,785 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:33:16,785 - INFO - rxn21635_c0> not needed:15.734222606679891
2026-01-13 19:33:16,787 - INFO - integrating rxn: rxn11162_c0
2026-01-13 19:33:16,787 - INFO - rxn16218_c0> not needed:15.734222606679891
2026-01-13 19:33:16,788 - INFO - integrating rxn: rxn16141_c0
2026-01-13 19:33:16,789 - INFO - rxn16217_c0> not needed:15.734222606679891
2026-01-13 19:33:16,790 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:33:16,790 - INFO - rxn40505_c0> not needed:15.734222606679891
2026-01-13 19:33:16,792 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:16,792 - INFO - rxn14424_c0> not needed:15.734222606679891
2026-01-13 19:33:16,793 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:16,793 - INFO - rxn17445_c0> not needed:15.734222606679891
2026-01-13 19:33:16,795 - INFO - integrating rxn: rxn15550_c0
2026-01-13 19:33:16,797 - INFO - integrating rxn: rxn15072_c0
2026-01-13 19:33:16,797 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,798 - INFO - integrating rxn: rxn16622_c0
2026-01-13 19:33:16,800 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:16,801 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:33:16,802 - INFO - rxn12940_c0> not needed:15.734222606679882
2026-01-13 19:33:16,803 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:16,803 - INFO - rxn12939_c0> not needed:15.734222606679891
2026-01-13 19:33:16,804 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:33:16,805 - INFO - rxn12929_c0> not needed:15.734222606679891
2026-01-13 19:33:16,806 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:16,807 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:16,809 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:16,809 - INFO - rxn25637_c0> not needed:15.73422260667988
2026-01-13 19:33:16,811 - INFO - rxn18935_c0> not needed:15.734222606679872
2026-01-13 19:33:16,811 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:33:16,813 - INFO - rxn25638_c0> not needed:15.734222606679872
2026-01-13 19:33:16,813 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:33:16,814 - INFO - rxn12928_c0> not needed:15.734222606679872
2026-01-13 19:33:16,815 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:33:16,817 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:33:16,818 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,819 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:33:16,821 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:33:16,821 - INFO - rxn02485_c0> not needed:15.73113735456537
2026-01-13 19:33:16,823 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:33:16,825 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,825 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:33:16,826 - INFO - Full solution: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn11162_c0', '>', 'new'], ['rxn16141_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn15550_c0', '>', 'new'], ['rxn15072_c0', '>', 'new'], ['rxn16622_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:33:16,827 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,829 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,832 - INFO - rxn47267_c0> not needed:15.731137354565325
2026-01-13 19:33:16,834 - INFO - rxn41387_c0> not needed:15.731137354565284
2026-01-13 19:33:16,836 - INFO - rxn19346_c0> not needed:15.73113735456532
2026-01-13 19:33:16,838 - INFO - rxn01736_c0> not needed:15.731137354565247
2026-01-13 19:33:16,840 - INFO - rxn00644_c0> not needed:15.26732801370395
2026-01-13 19:33:16,841 - INFO - rxn04551_c0> not needed:15.267328013703933
2026-01-13 19:33:16,845 - INFO - rxn25042_c0> not needed:15.267328013703882
2026-01-13 19:33:16,847 - INFO - rxn19766_c0> not needed:15.267328013703969
2026-01-13 19:33:16,848 - INFO - rxn19764_c0> not needed:15.267328013703969
2026-01-13 19:33:16,852 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,854 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,856 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,862 - INFO - rxn45106_c0> not needed:15.267328013703906
2026-01-13 19:33:16,871 - INFO - rxn15060_c0> not needed:15.26732801370401
2026-01-13 19:33:16,873 - INFO - rxn15064_c0> not needed:15.267328013703938
2026-01-13 19:33:16,874 - INFO - rxn15270_c0> not needed:15.267328013703958
2026-01-13 19:33:16,881 - INFO - rxn15940_c0> not needed:15.26732801370397
2026-01-13 19:33:16,882 - INFO - rxn30917_c0> not needed:15.267328013703969
2026-01-13 19:33:16,884 - INFO - rxn16341_c0> not needed:15.267328013703969
2026-01-13 19:33:16,886 - INFO - rxn41492_c0> not needed:15.267328013703969
2026-01-13 19:33:16,887 - INFO - rxn44493_c0> not needed:15.267328013703969
2026-01-13 19:33:16,889 - INFO - rxn27266_c0> not needed:15.267328013703969
2026-01-13 19:33:16,890 - INFO - rxn47875_c0> not needed:15.267328013703969
2026-01-13 19:33:16,891 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:16,893 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,893 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,894 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:16,896 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,898 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,899 - INFO - rxn37059_c0> not needed:15.267328013703924
2026-01-13 19:33:16,900 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,900 - INFO - rxn08921_c0> not needed:15.267328013704006
2026-01-13 19:33:16,902 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,903 - INFO - rxn15754_c0> not needed:15.236982722116275
2026-01-13 19:33:16,904 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,905 - INFO - rxn41399_c0> not needed:15.236982722116254
2026-01-13 19:33:16,905 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,906 - INFO - rxn41401_c0> not needed:15.236982722116254
2026-01-13 19:33:16,907 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,908 - INFO - rxn15776_c0> not needed:15.236982722116254
2026-01-13 19:33:16,909 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,909 - INFO - rxn14423_c0> not needed:15.236982722116254
2026-01-13 19:33:16,911 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,911 - INFO - rxn10154_c0> not needed:15.236982722116254
2026-01-13 19:33:16,913 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,913 - INFO - rxn10042_c0> not needed:15.236982722116254
2026-01-13 19:33:16,915 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,917 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01

Adding gapfilling

2026-01-13 19:33:16,933 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01

 {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn10213_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn03537_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn00832_c0': '<', 'rxn01537_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn03638_c0': '>', 'rxn02056_c0': '<', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn40505_c0': '>', 'rxn14424_c0': '>', 'rxn17445_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn19346_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn45106_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn16341_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn27266_c0': '>', 'rxn47875_c0': '>', 'rxn40674_c0': '>', 'rxn37059_c0': '>', 'rxn08921_c0': '>', 'rxn15754_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>', 'rxn14423_c0': '>', 'rxn10154_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:16,935 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,935 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:33:16,937 - INFO -     Added 44 reactions
2026-01-13 19:33:16,937 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:33:16,937 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,940 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,942 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,943 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,945 - INFO - AuxoMedia/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,947 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,949 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,951 - INFO - AuxoMedia/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:16,953 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:16,955 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,956 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,958 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,960 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,962 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,964 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,966 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,967 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,969 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,971 - INFO - AuxoMedia/bio1:rxn01603_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,976 - INFO - rxn16218_c0> not needed:11.20042515788858
2026-01-13 19:33:16,978 - INFO - rxn16217_c0> not needed:11.200425157888553
2026-01-13 19:33:16,979 - INFO - rxn14424_c0> not needed:11.200425157888553
2026-01-13 19:33:16,984 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:16,988 - INFO - rxn12932_c0> not needed:11.200425157888528
2026-01-13 19:33:16,990 - INFO - rxn12938_c0> not needed:11.200425157888525
2026-01-13 19:33:16,992 - INFO - rxn12927_c0> not needed:11.200425157888525
2026-01-13 19:33:16,993 - INFO - rxn12921_c0> not needed:11.200425157888525
2026-01-13 19:33:16,996 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,000 - INFO - rxn12942_c0> not needed:11.200425157888509
2026-01-13 19:33:17,002 - INFO - rxn02485_c0> not needed:11.198355933361093
2026-01-13 19:33:17,005 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,007 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,009 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,014 - INFO - rxn47267_c0> not needed:11.198355933361139
2026-01-13 19:33:17,016 - INFO - rxn41387_c0> not needed:11.198355933361107
2026-01-13 19:33:17,020 - INFO - rxn19346_c0> not needed:11.136403540277273
2026-01-13 19:33:17,022 - INFO - rxn11162_c0> not needed:11.136403540277259
2026-01-13 19:33:17,023 - INFO - rxn16141_c0> not needed:11.136403540277259
2026-01-13 19:33:17,027 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,029 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,031 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,035 - INFO - rxn15550_c0> not needed:11.136403540277273
2026-01-13 19:33:17,036 - INFO - rxn15072_c0> not needed:11.136403540277236
2026-01-13 19:33:17,038 - INFO - rxn16622_c0> not needed:11.136403540277236
2026-01-13 19:33:17,039 - INFO - rxn15060_c0> not needed:11.136403540277236
2026-01-13 19:33:17,040 - INFO - rxn15064_c0> not needed:11.136403540277236
2026-01-13 19:33:17,043 - INFO - AuxoMedia/bio1:rxn30685_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,055 - INFO - rxn11285_c0> not needed:11.136403540277167

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:17,079 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,081 - INFO - AuxoMedia/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,084 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,086 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:17,095 - INFO - rxn29260_c0> not needed:11.13640354027725
2026-01-13 19:33:17,097 - INFO - rxn09390_c0> not needed:11.136403540277275
2026-01-13 19:33:17,098 - INFO - rxn14423_c0> not needed:11.136403540277275
2026-01-13 19:33:17,100 - INFO - rxn43975_c0> not needed:11.136403540277275
2026-01-13 19:33:17,101 - INFO - rxn42732_c0> not needed:11.136403540277275
2026-01-13 19:33:17,102 - INFO - rxn41263_c0> not needed:11.136403540277275
2026-01-13 19:33:17,104 - INFO - rxn20839_c0> not needed:11.136403540277275
2026-01-13 19:33:17,108 - INFO - Unneeded: [['rxn16218_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn14424_c0', '>', 'new', 100, None], ['rxn12932_c0', '>', 'new', 100, None], ['rxn12938_c0', '>', 'new', 100, None], ['rxn12927_c0', '>', 'new', 100, None], ['rxn12921_c0', '>', 'new', 100, None], ['rxn12942_c0', '>', 'new', 100, None], ['rxn02485_c0', '>', 'new', 100, None], ['rxn47267_c0', '>', 'new', 100, None], ['rxn41387_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn11162_c0', '>', 'new', 100, None], ['rxn16141_c0', '>', 'new', 100, None], ['rxn15550_c0', '>', 'new', 100, None], ['rxn15072_c0', '>', 'new', 100, None], ['rxn16622_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn11285_c0', '>', 'new', 100, None], ['rxn29260_c0', '>', 'new', 100, None], ['rxn09390_c0', '>', 'new', 100, None], ['rxn14423_c0', '>', 'new', 100, None], ['rxn43975_c0', '>', 'new', 100, None], ['rxn42732_c0', '>', 'new', 100, None], ['rxn41263_c0', '>', 'new', 100, None], ['rxn20839_c0', '>', 'new', 100, None]]
2026-01-13 19:33:17,122 - INFO - Growth: 11.200425157888503 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn04139_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn19346_c0': '>', 'rxn11162_c0': '>', 'rxn16141_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15550_c0': '>', 'rxn15072_c0': '>', 'rxn16622_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn29260_c0': '>', 'rxn09390_c0': '>', 'rxn14423_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:17,125 - INFO - Cumulative: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:33:17,126 - INFO -     Added 57 reactions
2026-01-13 19:33:17,127 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:33:17,215 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04139_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03439_c0': '>', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn06090_c0': '>', 'rxn07254_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn24212_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15550_c0': '>', 'rxn15072_c0': '>', 'rxn16622_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn08154_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn47493_c0': '>', 'rxn09390_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:17,218 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:33:17,220 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:33:17,222 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:33:17,224 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:33:17,226 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:33:17,227 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:33:17,228 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00104_e0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn12512_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn00392_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn03084_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn05223_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02341_c0': '>', 'rxn09149_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn11162_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15550_c0': '>', 'rxn14070_c0': '>', 'rxn15072_c0': '>', 'rxn45106_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:17,229 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:33:17,231 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:33:17,232 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:33:17,233 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:33:17,234 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:33:17,235 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:33:17,235 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:33:17,236 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:33:17,237 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:33:17,238 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:33:17,238 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:33:17,239 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:33:17,240 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:33:17,241 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:33:17,242 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:33:17,243 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:33:17,244 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:33:17,245 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:33:17,246 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:33:17,246 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:33:17,247 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:33:17,248 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:33:17,249 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:33:17,250 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:33:17,251 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:33:17,251 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:33:17,253 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:33:17,253 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:33:17,254 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:33:17,255 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:33:17,256 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:33:17,256 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:33:17,258 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:33:17,258 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:33:17,259 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:33:17,260 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:33:17,261 - INFO - integrating rxn: rxn05463_c0
2026-01-13 19:33:17,262 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:33:17,263 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:33:17,263 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:33:17,264 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:33:17,265 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:33:17,266 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:33:17,267 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:33:17,268 - INFO - integrating rxn: rxn10094_c0
2026-01-13 19:33:17,268 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:33:17,269 - INFO - integrating rxn: rxn03087_c0
2026-01-13 19:33:17,270 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:33:17,271 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:33:17,271 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:33:17,273 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:33:17,273 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:33:17,274 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:33:17,275 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:33:17,276 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:33:17,277 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:33:17,278 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:33:17,278 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:33:17,279 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:33:17,280 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:33:17,281 - INFO - integrating rxn: rxn05223_c0
2026-01-13 19:33:17,281 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:17,283 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:33:17,283 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:33:17,284 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:33:17,285 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:33:17,286 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:33:17,286 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:33:17,287 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:33:17,288 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:17,289 - INFO - integrating rxn: rxn09149_c0
2026-01-13 19:33:17,290 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:33:17,291 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:33:17,292 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:33:17,293 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:33:17,293 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:33:17,294 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:33:17,295 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:17,296 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:33:17,297 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:17,298 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:33:17,299 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:17,300 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:33:17,301 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:17,302 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:17,302 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:33:17,304 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:33:17,304 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:17,305 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:33:17,306 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:17,307 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:33:17,307 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:33:17,309 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:33:17,309 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:17,311 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:33:17,311 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:17,312 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:33:17,313 - INFO - integrating rxn: rxn06090_c0
2026-01-13 19:33:17,314 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:33:17,314 - INFO - integrating rxn: rxn07254_c0
2026-01-13 19:33:17,316 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:33:17,316 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:17,317 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:33:17,318 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:17,319 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:17,319 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:33:17,321 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:17,321 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:33:17,322 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:33:17,323 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:33:17,324 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:17,326 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:33:17,326 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:33:17,327 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:33:17,327 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:33:17,329 - INFO - integrating rxn: rxn24212_c0
2026-01-13 19:33:17,329 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:33:17,330 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:17,331 - INFO - integrating rxn: rxn11162_c0
2026-01-13 19:33:17,332 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:17,332 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:33:17,333 - INFO - integrating rxn: rxn15550_c0
2026-01-13 19:33:17,334 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:33:17,335 - INFO - integrating rxn: rxn15072_c0
2026-01-13 19:33:17,336 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:33:17,337 - INFO - integrating rxn: rxn16622_c0
2026-01-13 19:33:17,337 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:33:17,338 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:33:17,339 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:17,340 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:17,340 - INFO - integrating rxn: rxn15550_c0
2026-01-13 19:33:17,341 - INFO - integrating rxn: rxn08154_c0
2026-01-13 19:33:17,342 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:33:17,343 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:17,344 - INFO - integrating rxn: rxn15072_c0
2026-01-13 19:33:17,344 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:17,345 - INFO - integrating rxn: rxn45106_c0
2026-01-13 19:33:17,346 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:17,347 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:17,348 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:33:17,348 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:33:17,349 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:17,350 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:33:17,351 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:33:17,351 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:33:17,352 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:17,353 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:33:17,354 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:33:17,355 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:33:17,355 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:33:17,356 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:33:17,357 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:33:17,358 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:33:17,359 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:33:17,359 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:33:17,360 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:33:17,361 - INFO - Full solution: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn06090_c0', '>', 'new'], ['rxn07254_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn24212_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn15550_c0', '>', 'new'], ['rxn15072_c0', '>', 'new'], ['rxn16622_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn08154_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:33:17,361 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:33:17,363 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:33:17,365 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:33:17,366 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:33:17,368 - INFO - integrating rxn: rxn10042_c0

Adding gapfillingAdding gapfilling  {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00104_e0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn12512_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn00392_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn03397_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn05645_c0': '>', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn10094_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn03084_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn05223_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02341_c0': '>', 'rxn09149_c0': '<', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn11162_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15550_c0': '>', 'rxn14070_c0': '>', 'rxn15072_c0': '>', 'rxn45106_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn11285_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn40674_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}{'reversed': {}, 'new': {'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn08710_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04139_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03439_c0': '>', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn16217_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn06090_c0': '>', 'rxn07254_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn24212_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15550_c0': '>', 'rxn15072_c0': '>', 'rxn16622_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn08154_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn47493_c0': '>', 'rxn09390_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:33:17,698 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn09149_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:33:17,699 - INFO - Cumulative: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:33:17,699 - INFO -     Added 47 reactions
2026-01-13 19:33:17,699 - INFO -     Added 54 reactions
2026-01-13 19:33:17,700 - INFO -   Gapfilling with PyruateMinimalAnaerobic...
2026-01-13 19:33:17,700 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:22,458 - INFO - Objective with gapfill database:86.04689764726665; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:24,444 - INFO - Objective with gapfill database:107.98937469951257; min objective:0.01
2026-01-13 19:33:24,532 - INFO - Objective with gapfill database:114.7387106182322; min objective:0.01
2026-01-13 19:33:24,870 - INFO - Objective with gapfill database:94.56987442287223; min objective:0.01
2026-01-13 19:33:24,953 - INFO - Objective with gapfill database:86.04689764726665; min objective:0.01
2026-01-13 19:33:25,425 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,453 - INFO - cpd00363 not found in model!
2026-01-13 19:33:25,454 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:25,457 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,467 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,477 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,486 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,496 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,505 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,514 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,523 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,532 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,541 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,553 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,556 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00013_e0': '<', 'EX_cpd15378_e0': '>', 'rxn00359_c0': '<', 'rxn02504_c0': '>', 'rxn01306_c0': '<', 'rxn03436_c0': '>', 'rxn05466_c0': '>', 'rxn00300_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn03841_c0': '>', 'rxn01257_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn00623_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn21860_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn15166_c0': '>', 'rxn15395_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn16048_c0': '>', 'rxn16114_c0': '>', 'rxn15060_c0': '>', 'rxn37372_c0': '>', 'rxn15939_c0': '>', 'rxn47493_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:25,560 - INFO - cpd00363 not found in model!
2026-01-13 19:33:25,560 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:33:25,561 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:25,563 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:25,564 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,565 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:33:25,567 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:25,569 - INFO - integrating rxn: rxn01306_c0
2026-01-13 19:33:25,570 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:25,572 - INFO - integrating rxn: rxn05466_c0
2026-01-13 19:33:25,573 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:25,574 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,575 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:25,577 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:25,578 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:25,580 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:25,581 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:25,583 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:25,583 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,585 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:25,586 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:25,588 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:33:25,590 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:25,591 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:25,592 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,593 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:25,595 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:25,597 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:25,598 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:25,600 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:25,601 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:25,603 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:25,603 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,604 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:25,606 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:25,607 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:25,609 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:25,610 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:25,612 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:33:25,613 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,613 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:33:25,615 - INFO - integrating rxn: rxn15395_c0
2026-01-13 19:33:25,617 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:33:25,618 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:33:25,620 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:33:25,621 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:33:25,622 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,623 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:33:25,625 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:33:25,627 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:33:25,628 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:33:25,629 - INFO - integrating rxn: rxn16048_c0
2026-01-13 19:33:25,631 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:25,632 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,632 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:25,635 - INFO - integrating rxn: rxn37372_c0
2026-01-13 19:33:25,636 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:25,638 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:25,639 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn04996_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn01345_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10120_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00058_e0', 'EX_cpd00063_e0', 'rxn08709_c0', 'rxn02000_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn04996_c0', 'rxn01117_c0', 'rxn00470_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn01997_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00907_c0', 'rxn10213_c0', 'rxn05229_c0', 'rxn02404_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn01675_c0', 'rxn03536_c0', 'rxn01256_c0', 'rxn00503_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn04704_c0', 'rxn03159_c0', 'rxn01000_c0', 'rxn03397_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn08528_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05463_c0', 'rxn01345_c0', 'rxn08711_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn01539_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn01213_c0', 'rxn02304_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn06865_c0', 'rxn04113_c0', 'rxn00834_c0', 'rxn00599_c0', 'rxn08130_c0', 'rxn11702_c0', 'rxn05117_c0', 'rxn03084_c0', 'rxn03439_c0', 'rxn00346_c0', 'rxn03638_c0', 'rxn02056_c0', 'rxn00134_c0', 'rxn00141_c0', 'rxn02003_c0', 'rxn00912_c0', 'rxn00122_c0', 'rxn01602_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn00138_c0', 'rxn03130_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn00686_c0', 'rxn01520_c0', 'rxn00293_c0', 'rxn16218_c0', 'rxn15949_c0', 'rxn16217_c0', 'rxn15947_c0', 'rxn14424_c0', 'rxn11274_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn02485_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn15167_c0', 'rxn19346_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn20508_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn14423_c0', 'rxn10120_c0', 'rxn10042_c0', ['EX_cpd00013_e0', '<', 'new'], ['EX_cpd15378_e0', '>', 'new'], ['rxn00359_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn01306_c0', '<', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn05466_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn01257_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn15395_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn16048_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn37372_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn47493_c0', '>', 'new']]
2026-01-13 19:33:25,641 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,645 - INFO - cpd11640 not found in model!
2026-01-13 19:33:25,646 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:25,650 - INFO - cpd00130 not found in model!
2026-01-13 19:33:25,650 - INFO - Media compound: cpd00130 not found in model.
2026-01-13 19:33:25,653 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,656 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:25,658 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:25,659 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:25,660 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:25,661 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:25,663 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,663 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,664 - INFO - PyruateMinimalAnaerobic/bio1:rxn02000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,665 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,667 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,668 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,669 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,670 - INFO - PyruateMinimalAnaerobic/bio1:rxn04996_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:25,671 - INFO - cpd00209 not found in model!
2026-01-13 19:33:25,672 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:25,672 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:25,673 - INFO - PyruateMinimalAnaerobic/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,674 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,675 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,676 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,677 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:25,679 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,680 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,682 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,683 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:25,683 - INFO - cpd00418 not found in model!
2026-01-13 19:33:25,684 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:25,684 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,686 - INFO - PyruateMinimalAnaerobic/bio1:rxn01997_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,687 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,687 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,689 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,690 - INFO - PyruateMinimalAnaerobic/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,692 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,693 - INFO - PyruateMinimalAnaerobic/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,694 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,695 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,696 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:25,697 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,698 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:33:25,845 - INFO - cpd11640 not found in model!
2026-01-13 19:33:25,845 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:25,848 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,856 - INFO - cpd11640 not found in model!
2026-01-13 19:33:25,856 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:25,859 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,868 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,877 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,884 - INFO - cpd11640 not found in model!
2026-01-13 19:33:25,885 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:25,887 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,896 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,904 - INFO - cpd11632 not found in model!
2026-01-13 19:33:25,904 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:33:25,907 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,914 - INFO - cpd08701 not found in model!
2026-01-13 19:33:25,915 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:33:25,915 - INFO - cpd01024 not found in model!
2026-01-13 19:33:25,916 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:25,919 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,926 - INFO - cpd01024 not found in model!
2026-01-13 19:33:25,927 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:25,929 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,939 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,946 - INFO - cpd11640 not found in model!
2026-01-13 19:33:25,947 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:25,949 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,957 - INFO - cpd11640 not found in model!
2026-01-13 19:33:25,957 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:25,958 - INFO - cpd00187 not found in model!
2026-01-13 19:33:25,959 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:33:25,961 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,969 - INFO - cpd11640 not found in model!
2026-01-13 19:33:25,969 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:25,970 - INFO - cpd00425 not found in model!
2026-01-13 19:33:25,971 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:33:25,974 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:25,981 - INFO - cpd11640 not found in model!
2026-01-13 19:33:25,982 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:25,983 - INFO - cpd00441 not found in model!
2026-01-13 19:33:25,983 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:33:25,986 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:26,433 - INFO - Objective with gapfill database:86.04689764726818; min objective:0.01
2026-01-13 19:33:26,809 - INFO - Objective with gapfill database:107.98937469951171; min objective:0.01
2026-01-13 19:33:26,984 - INFO - Objective with gapfill database:107.98937469951257; min objective:0.01
2026-01-13 19:33:26,997 - INFO - Objective with gapfill database:114.7387106182322; min objective:0.01
2026-01-13 19:33:27,314 - INFO - Objective with gapfill database:94.56987442287223; min objective:0.01
2026-01-13 19:33:27,587 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00013_e0': '<', 'EX_cpd00048_e0': '<', 'rxn00359_c0': '<', 'rxn02504_c0': '>', 'rxn00544_c0': '>', 'rxn02305_c0': '>', 'rxn00796_c0': '>', 'rxn03436_c0': '>', 'rxn05293_c0': '>', 'rxn02160_c0': '>', 'rxn00957_c0': '>', 'rxn05466_c0': '>', 'rxn00300_c0': '>', 'rxn00289_c0': '>', 'rxn02835_c0': '>', 'rxn01300_c0': '>', 'rxn05893_c0': '>', 'rxn01539_c0': '<', 'rxn02508_c0': '>', 'rxn00726_c0': '>', 'rxn03108_c0': '>', 'rxn00333_c0': '>', 'rxn02200_c0': '>', 'rxn00791_c0': '<', 'rxn09310_c0': '>', 'rxn03841_c0': '>', 'rxn12239_c0': '>', 'rxn01257_c0': '>', 'rxn05651_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn03061_c0': '<', 'rxn00347_c0': '<', 'rxn00623_c0': '<', 'rxn02507_c0': '>', 'rxn01964_c0': '>', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn21860_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn14178_c0': '>', 'rxn25279_c0': '>', 'rxn25278_c0': '>', 'rxn17392_c0': '>', 'rxn16114_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn30685_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn44043_c0': '>', 'rxn15939_c0': '>', 'rxn42332_c0': '>', 'rxn29260_c0': '>', 'rxn47493_c0': '>', 'rxn08474_c0': '>', 'rxn10121_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:27,590 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:33:27,593 - INFO - integrating rxn: EX_cpd00048_e0
2026-01-13 19:33:27,595 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:33:27,596 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:27,598 - INFO - integrating rxn: rxn00544_c0
2026-01-13 19:33:27,600 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:33:27,602 - INFO - integrating rxn: rxn00796_c0
2026-01-13 19:33:27,603 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:27,604 - INFO - integrating rxn: rxn05293_c0
2026-01-13 19:33:27,606 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:33:27,607 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:33:27,609 - INFO - integrating rxn: rxn05466_c0
2026-01-13 19:33:27,610 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:27,612 - INFO - integrating rxn: rxn00289_c0
2026-01-13 19:33:27,613 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:33:27,614 - INFO - integrating rxn: rxn01300_c0
2026-01-13 19:33:27,616 - INFO - integrating rxn: rxn05893_c0
2026-01-13 19:33:27,617 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:27,619 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:33:27,620 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:33:27,622 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:33:27,623 - INFO - integrating rxn: rxn00333_c0
2026-01-13 19:33:27,626 - INFO - integrating rxn: rxn02200_c0
2026-01-13 19:33:27,627 - INFO - integrating rxn: rxn00791_c0
2026-01-13 19:33:27,629 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:27,630 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:27,632 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:27,633 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:27,634 - INFO - integrating rxn: rxn05651_c0
2026-01-13 19:33:27,636 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:27,638 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:27,639 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:27,640 - INFO - integrating rxn: rxn03061_c0
2026-01-13 19:33:27,642 - INFO - integrating rxn: rxn00347_c0
2026-01-13 19:33:27,643 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:33:27,645 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:33:27,646 - INFO - integrating rxn: rxn01964_c0
2026-01-13 19:33:27,647 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:27,649 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:27,650 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:27,652 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:27,653 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:27,655 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:27,656 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:27,657 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:27,659 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:27,660 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:27,661 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:27,663 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:27,664 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:27,666 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:27,667 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:27,669 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:33:27,670 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:33:27,671 - INFO - integrating rxn: rxn14178_c0
2026-01-13 19:33:27,673 - INFO - integrating rxn: rxn25279_c0
2026-01-13 19:33:27,674 - INFO - integrating rxn: rxn25278_c0
2026-01-13 19:33:27,675 - INFO - integrating rxn: rxn17392_c0
2026-01-13 19:33:27,677 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:27,678 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:27,679 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:33:27,680 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn12376_c0': '<', 'rxn00333_c0': '>', 'rxn09310_c0': '>', 'rxn03841_c0': '>', 'rxn01257_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn16218_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn16217_c0': '>', 'rxn21860_c0': '>', 'rxn11274_c0': '>', 'rxn15166_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn29919_c0': '>', 'rxn30685_c0': '>', 'rxn16341_c0': '>', 'rxn47493_c0': '>', 'rxn08474_c0': '>', 'rxn08473_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:27,681 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:27,682 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:33:27,683 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:27,684 - INFO - integrating rxn: rxn13741_c0
2026-01-13 19:33:27,685 - INFO - integrating rxn: rxn44043_c0
2026-01-13 19:33:27,685 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:27,687 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:27,687 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:27,688 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:33:27,689 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:27,689 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:33:27,690 - INFO - integrating rxn: rxn00333_c0
2026-01-13 19:33:27,691 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:27,692 - INFO - integrating rxn: rxn08474_c0
2026-01-13 19:33:27,692 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:27,694 - INFO - integrating rxn: rxn10121_c0
2026-01-13 19:33:27,694 - INFO - integrating rxn: rxn03841_c0

c0

2026-01-13 19:33:27,901 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01

2026-01-13 19:33:27,902 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:27,903 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,904 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:27,905 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,905 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:27,906 - INFO - rxn01538_c0> not needed:4.3898603189138035
2026-01-13 19:33:27,906 - INFO - integrating rxn: rxn17731_c0
2026-01-13 19:33:27,908 - INFO - rxn05255_c0> not needed:4.389860318913827
2026-01-13 19:33:27,908 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:27,910 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:27,910 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:27,911 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:27,911 - INFO - PyruateMinimalAnaerobic/bio1:rxn03164_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,913 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:33:27,913 - INFO - PyruateMinimalAnaerobic/bio1:rxn00623_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:27,914 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:33:27,915 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,915 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:33:27,916 - INFO - PyruateMinimalAnaerobic/bio1:rxn05232_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,917 - INFO - integrating rxn: rxn15395_c0
2026-01-13 19:33:27,918 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,918 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:27,919 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,919 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:33:27,921 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,921 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:27,922 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,922 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:27,924 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,924 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:27,925 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,925 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:33:27,927 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,927 - INFO - integrating rxn: rxn10120_c0
2026-01-13 19:33:27,928 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:33:27,928 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,929 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn10484_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01454_c0', '<', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn08352_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn00410_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn02476_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01513_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn01636_c0', 'rxn01117_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn10484_c0', 'rxn03436_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn05229_c0', 'rxn02404_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn01454_c0', 'rxn01501_c0', 'rxn01505_c0', 'rxn01256_c0', 'rxn00237_c0', 'rxn03919_c0', 'rxn09210_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03159_c0', 'rxn01000_c0', 'rxn03397_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn08528_c0', 'rxn03916_c0', 'rxn08352_c0', 'rxn09106_c0', 'rxn08711_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn01539_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn00410_c0', 'rxn02405_c0', 'rxn03150_c0', 'rxn01537_c0', 'rxn02303_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn02476_c0', 'rxn01512_c0', 'rxn06865_c0', 'rxn00834_c0', 'rxn08130_c0', 'rxn11702_c0', 'rxn03084_c0', 'rxn03439_c0', 'rxn01790_c0', 'rxn02056_c0', 'rxn00141_c0', 'rxn02185_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn03130_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn01513_c0', 'rxn00117_c0', 'rxn01520_c0', 'rxn00293_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn14424_c0', 'rxn11274_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn02485_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn15167_c0', 'rxn30633_c0', 'rxn45899_c0', 'rxn47659_c0', 'rxn43798_c0', 'rxn25042_c0', 'rxn19766_c0', 'rxn19764_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn11285_c0', 'rxn10095_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn14423_c0', 'rxn43975_c0', 'rxn42732_c0', 'rxn41263_c0', 'rxn20839_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn00359_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn00272_c0', '>', 'new'], ['rxn00336_c0', '<', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn00048_c0', '>', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn00333_c0', '>', 'new'], ['rxn00791_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn00520_c0', '>', 'new'], ['rxn02507_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn17731_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn15395_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn10120_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:33:27,930 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,932 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,933 - INFO - PyruateMinimalAnaerobic/bio1:rxn28338_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,935 - INFO - PyruateMinimalAnaerobic/bio1:rxn01736_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,936 - INFO - cpd11640 not found in model!
2026-01-13 19:33:27,936 - INFO - PyruateMinimalAnaerobic/bio1:rxn00644_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,937 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:27,938 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,940 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,941 - INFO - PyruateMinimalAnaerobic/bio1:rxn17394_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,943 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,944 - INFO - PyruateMinimalAnaerobic/bio1:rxn15064_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,946 - INFO - rxn15270_c0> not needed:4.389860318913827
2026-01-13 19:33:27,948 - INFO - EX_cpd00305_e0< not needed:2.831206565817571
2026-01-13 19:33:27,948 - INFO - PyruateMinimalAnaerobic/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,949 - INFO - EX_cpd00393_e0< not needed:2.831206565817571
2026-01-13 19:33:27,950 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,950 - INFO - EX_cpd00119_e0< not needed:2.831206565817571
2026-01-13 19:33:27,952 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,952 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:27,953 - INFO - PyruateMinimalAnaerobic/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,954 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,955 - INFO - PyruateMinimalAnaerobic/bio1:rxn46249_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,955 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,957 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,958 - INFO - rxn41492_c0> not needed:4.389860318913791
2026-01-13 19:33:27,959 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,959 - INFO - rxn44493_c0> not needed:4.389860318913794
2026-01-13 19:33:27,960 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,960 - INFO - rxn42332_c0> not needed:4.389860318913794
2026-01-13 19:33:27,961 - INFO - PyruateMinimalAnaerobic/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,962 - INFO - PyruateMinimalAnaerobic/bio1:rxn20472_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,963 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:27,964 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,965 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:33:27,964 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,966 - INFO -   Running ATP safety check...
2026-01-13 19:33:27,966 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:33:27,968 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:27,969 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:-6.903321516792167e-13 with min obj:0.01
2026-01-13 19:33:27,971 - INFO - PyruateMinimalAnaerobic/bio1:rxn10484_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,972 - INFO - PyruateMinimalAnaerobic/bio1:rxn03436_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,974 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,975 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,977 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,978 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,980 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,981 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,983 - INFO - PyruateMinimalAnaerobic/bio1:rxn05229_c0> needed:5.681694292987068e-13 with min obj:0.01
2026-01-13 19:33:27,985 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,986 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,988 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,989 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,990 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,992 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,993 - INFO - PyruateMinimalAnaerobic/bio1:rxn01454_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:27,995 - INFO - PyruateMinimalAnaerobic/bio1:rxn01501_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:27,997 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:27,998 - INFO - PyruateMinimalAnaerobic/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,000 - INFO - PyruateMinimalAnaerobic/bio1:rxn00237_c0> needed:6.112918944384169e-13 with min obj:0.01
2026-01-13 19:33:28,002 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,003 - INFO - PyruateMinimalAnaerobic/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,004 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,006 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,008 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,009 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,011 - INFO - PyruateMinimalAnaerobic/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,012 - INFO - PyruateMinimalAnaerobic/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,013 - INFO - PyruateMinimalAnaerobic/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,015 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,017 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,018 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,019 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,021 - INFO - PyruateMinimalAnaerobic/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,022 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,024 - INFO - PyruateMinimalAnaerobic/bio1:rxn08352_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,025 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,027 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,028 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,030 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,034 - INFO - PyruateMinimalAnaerobic/bio1:rxn01539_c0< needed:-2.311809554703622e-13 with min obj:0.01
2026-01-13 19:33:28,037 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,039 - INFO - rxn05299_c0> not needed:2.8312065658175642
2026-01-13 19:33:28,042 - INFO - PyruateMinimalAnaerobic/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,044 - INFO - rxn09657_c0> not needed:2.831206565817584
2026-01-13 19:33:28,047 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,049 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,050 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,052 - INFO - PyruateMinimalAnaerobic/bio1:rxn00410_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,053 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,055 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,060 - INFO - PyruateMinimalAnaerobic/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,062 - INFO - PyruateMinimalAnaerobic/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,063 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,065 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,066 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,068 - INFO - PyruateMinimalAnaerobic/bio1:rxn02476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,070 - INFO - PyruateMinimalAnaerobic/bio1:rxn01512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,071 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,073 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,074 - INFO - PyruateMinimalAnaerobic/bio1:rxn08130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,076 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,078 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,079 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,081 - INFO - PyruateMinimalAnaerobic/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,082 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,084 - INFO - PyruateMinimalAnaerobic/bio1:rxn00141_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,085 - INFO - PyruateMinimalAnaerobic/bio1:rxn02185_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,087 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,088 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,089 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,091 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,092 - INFO - PyruateMinimalAnaerobic/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,094 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,095 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,097 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,099 - INFO - rxn05255_c0> not needed:2.8312065658175762
2026-01-13 19:33:28,102 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,103 - INFO - PyruateMinimalAnaerobic/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,104 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,106 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,108 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,109 - INFO - PyruateMinimalAnaerobic/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,111 - INFO - PyruateMinimalAnaerobic/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,112 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,113 - INFO - PyruateMinimalAnaerobic/bio1:rxn01513_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,116 - INFO - PyruateMinimalAnaerobic/bio1:rxn00117_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,117 - INFO - PyruateMinimalAnaerobic/bio1:rxn01520_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,119 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,120 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,122 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,125 - INFO - PyruateMinimalAnaerobic/bio1:rxn14424_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,130 - INFO - PyruateMinimalAnaerobic/bio1:rxn11274_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,133 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,135 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,138 - INFO - PyruateMinimalAnaerobic/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,140 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,142 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,143 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,147 - INFO - rxn15167_c0> not needed:2.8312065658175833
2026-01-13 19:33:28,148 - INFO - rxn30633_c0> not needed:2.8312065658175767
2026-01-13 19:33:28,151 - INFO - PyruateMinimalAnaerobic/bio1:rxn45899_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,152 - INFO - PyruateMinimalAnaerobic/bio1:rxn47659_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,154 - INFO - PyruateMinimalAnaerobic/bio1:rxn43798_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,157 - INFO - PyruateMinimalAnaerobic/bio1:rxn25042_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,159 - INFO - PyruateMinimalAnaerobic/bio1:rxn19766_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,161 - INFO - PyruateMinimalAnaerobic/bio1:rxn19764_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,164 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,166 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,168 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,169 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,171 - INFO - PyruateMinimalAnaerobic/bio1:rxn11285_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,173 - INFO - PyruateMinimalAnaerobic/bio1:rxn10095_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,175 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,178 - INFO - rxn15940_c0> not needed:2.8312065658175833
2026-01-13 19:33:28,181 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,183 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,184 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,186 - INFO - PyruateMinimalAnaerobic/bio1:rxn14423_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,187 - INFO - PyruateMinimalAnaerobic/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,189 - INFO - PyruateMinimalAnaerobic/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,191 - INFO - PyruateMinimalAnaerobic/bio1:rxn41263_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,192 - INFO - PyruateMinimalAnaerobic/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,193 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:33:28,193 - INFO -   Running ATP safety check...

c0

2026-01-13 19:33:28,235 - INFO - Objective with gapfill database:114.7387106182323; min objective:0.01
2026-01-13 19:33:28,630 - INFO - Objective with gapfill database:114.73871061823196; min objective:0.01
2026-01-13 19:33:28,797 - INFO - Initial solution: {'reversed': {'rxn00907_c0': '>'}, 'new': {'EX_cpd00013_e0': '<', 'EX_cpd00020_e0': '<', 'rxn00359_c0': '<', 'rxn00179_c0': '>', 'rxn02320_c0': '<', 'rxn00898_c0': '>', 'rxn02305_c0': '>', 'rxn00470_c0': '>', 'rxn00902_c0': '<', 'rxn05469_c0': '>', 'rxn00789_c0': '<', 'rxn03436_c0': '>', 'rxn00802_c0': '>', 'rxn02160_c0': '>', 'rxn00957_c0': '>', 'rxn02159_c0': '>', 'rxn05466_c0': '>', 'rxn05957_c0': '>', 'rxn00272_c0': '>', 'rxn02835_c0': '>', 'rxn03435_c0': '<', 'rxn01256_c0': '>', 'rxn03175_c0': '>', 'rxn01000_c0': '>', 'rxn01300_c0': '>', 'rxn12868_c0': '>', 'rxn02811_c0': '<', 'rxn03062_c0': '>', 'rxn00863_c0': '>', 'rxn01539_c0': '<', 'rxn03437_c0': '>', 'rxn02508_c0': '>', 'rxn00420_c0': '>', 'rxn00726_c0': '>', 'rxn03108_c0': '>', 'rxn02789_c0': '>', 'rxn05035_c0': '>', 'rxn00333_c0': '>', 'rxn01069_c0': '>', 'rxn00791_c0': '<', 'rxn01302_c0': '<', 'rxn01537_c0': '>', 'rxn00227_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn12239_c0': '>', 'rxn00693_c0': '>', 'rxn03909_c0': '>', 'rxn02277_c0': '>', 'rxn03075_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn02473_c0': '>', 'rxn01434_c0': '>', 'rxn08094_c0': '<', 'rxn02373_c0': '<', 'rxn01304_c0': '>', 'rxn00623_c0': '<', 'rxn02507_c0': '>', 'rxn01964_c0': '>', 'rxn02186_c0': '>', 'rxn01019_c0': '>', 'rxn01603_c0': '>', 'rxn03194_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn21862_c0': '>', 'rxn11279_c0': '>', 'rxn16218_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn21858_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn16217_c0': '>', 'rxn21860_c0': '>', 'rxn11274_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn02485_c0': '>', 'rxn46124_c0': '>', 'rxn30633_c0': '>', 'rxn15395_c0': '>', 'rxn15060_c0': '>', 'rxn30685_c0': '>', 'rxn10095_c0': '>', 'rxn44043_c0': '>', 'rxn13339_c0': '>', 'rxn13321_c0': '>', 'rxn15940_c0': '>', 'rxn08921_c0': '>', 'rxn47493_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:28,801 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:33:28,803 - INFO - integrating rxn: EX_cpd00020_e0
2026-01-13 19:33:28,805 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:33:28,807 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:33:28,809 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:33:28,811 - INFO - integrating rxn: rxn00898_c0
2026-01-13 19:33:28,813 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:33:28,814 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:33:28,816 - INFO - integrating rxn: rxn00902_c0
2026-01-13 19:33:28,818 - INFO - integrating rxn: rxn05469_c0
2026-01-13 19:33:28,820 - INFO - integrating rxn: rxn00789_c0
2026-01-13 19:33:28,821 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:28,822 - INFO - integrating rxn: rxn00802_c0
2026-01-13 19:33:28,824 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:33:28,826 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:33:28,827 - INFO - integrating rxn: rxn02159_c0
2026-01-13 19:33:28,828 - INFO - integrating rxn: rxn05466_c0
2026-01-13 19:33:28,830 - INFO - integrating rxn: rxn05957_c0
2026-01-13 19:33:28,831 - INFO - integrating rxn: rxn00272_c0
2026-01-13 19:33:28,833 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:33:28,834 - INFO - integrating rxn: rxn03435_c0
2026-01-13 19:33:28,835 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:33:28,837 - INFO - integrating rxn: rxn03175_c0
2026-01-13 19:33:28,838 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:33:28,840 - INFO - integrating rxn: rxn01300_c0
2026-01-13 19:33:28,841 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:33:28,843 - INFO - integrating rxn: rxn02811_c0
2026-01-13 19:33:28,844 - INFO - integrating rxn: rxn03062_c0
2026-01-13 19:33:28,846 - INFO - integrating rxn: rxn00863_c0
2026-01-13 19:33:28,847 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:28,848 - INFO - integrating rxn: rxn03437_c0
2026-01-13 19:33:28,850 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:33:28,851 - INFO - integrating rxn: rxn00420_c0
2026-01-13 19:33:28,853 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:33:28,854 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:33:28,855 - INFO - integrating rxn: rxn02789_c0
2026-01-13 19:33:28,857 - INFO - integrating rxn: rxn05035_c0
2026-01-13 19:33:28,858 - INFO - integrating rxn: rxn00333_c0
2026-01-13 19:33:28,859 - INFO - integrating rxn: rxn01069_c0
2026-01-13 19:33:28,861 - INFO - integrating rxn: rxn00791_c0
2026-01-13 19:33:28,862 - INFO - integrating rxn: rxn01302_c0
2026-01-13 19:33:28,864 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:33:28,865 - INFO - integrating rxn: rxn00227_c0
2026-01-13 19:33:28,867 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:28,868 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:28,870 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:28,872 - INFO - integrating rxn: rxn00693_c0
2026-01-13 19:33:28,873 - INFO - integrating rxn: rxn03909_c0
2026-01-13 19:33:28,875 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:28,876 - INFO - integrating rxn: rxn03075_c0
2026-01-13 19:33:28,878 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:28,880 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:28,881 - INFO - integrating rxn: rxn02473_c0
2026-01-13 19:33:28,883 - INFO - integrating rxn: rxn01434_c0
2026-01-13 19:33:28,885 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:33:28,886 - INFO - integrating rxn: rxn02373_c0
2026-01-13 19:33:28,887 - INFO - integrating rxn: rxn01304_c0
2026-01-13 19:33:28,889 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:33:28,891 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:33:28,892 - INFO - integrating rxn: rxn01964_c0
2026-01-13 19:33:28,893 - INFO - integrating rxn: rxn02186_c0
2026-01-13 19:33:28,895 - INFO - integrating rxn: rxn01019_c0
2026-01-13 19:33:28,897 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:28,898 - INFO - integrating rxn: rxn03194_c0
2026-01-13 19:33:28,899 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:28,901 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:28,902 - INFO - integrating rxn: rxn21862_c0
2026-01-13 19:33:28,904 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:28,905 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:33:28,907 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:28,908 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:28,909 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:28,911 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:28,912 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:28,913 - INFO - integrating rxn: rxn21858_c0
2026-01-13 19:33:28,915 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:28,916 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:28,917 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:33:28,918 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:28,920 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:33:28,921 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:28,923 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:28,924 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:28,925 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:33:28,927 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:33:28,928 - INFO - integrating rxn: rxn30633_c0
2026-01-13 19:33:28,929 - INFO - integrating rxn: rxn15395_c0
2026-01-13 19:33:28,931 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:33:28,932 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:28,933 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:33:28,934 - INFO - integrating rxn: rxn44043_c0
2026-01-13 19:33:28,936 - INFO - integrating rxn: rxn13339_c0
2026-01-13 19:33:28,937 - INFO - integrating rxn: rxn13321_c0
2026-01-13 19:33:28,938 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:33:28,940 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:28,941 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:28,942 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:33:28,944 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:33:28,945 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:33:28,946 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:33:28,946 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00033_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00107_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00069_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00322_e0', '<', 'new'], ['EX_cpd00156_e0', '<', 'new'], ['EX_cpd00051_e0', '<', 'new'], ['EX_cpd00066_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01483_c0', '>', 'new'], ['rxn00530_c0', '>', 'new'], ['rxn00710_c0', '>', 'new'], ['rxn00910_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn01362_c0', '<', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn05243_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn01301_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00213_c0', '>', 'new'], ['rxn05573_c0', '>', 'new'], ['rxn05244_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn09113_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00970_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn08661_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn00101_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn05154_c0', '>', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05301_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn02276_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05669_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00929_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01513_c0', '>', 'new'], ['rxn05306_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn39982_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00033_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00065_e0', 'EX_cpd00084_e0', 'EX_cpd00149_e0', 'EX_cpd00107_e0', 'EX_cpd00063_e0', 'EX_cpd00027_e0', 'EX_cpd00060_e0', 'EX_cpd00069_e0', 'EX_cpd00099_e0', 'EX_cpd00322_e0', 'EX_cpd00156_e0', 'EX_cpd00051_e0', 'EX_cpd00066_e0', 'EX_cpd00104_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn09177_c0', 'rxn10336_c0', 'rxn01483_c0', 'rxn00530_c0', 'rxn00710_c0', 'rxn00910_c0', 'rxn08710_c0', 'rxn08583_c0', 'rxn05514_c0', 'rxn01362_c0', 'rxn03918_c0', 'rxn05243_c0', 'rxn10030_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn01301_c0', 'rxn00392_c0', 'rxn05219_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn01505_c0', 'rxn00213_c0', 'rxn05573_c0', 'rxn05244_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn08528_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn05237_c0', 'rxn09113_c0', 'rxn08711_c0', 'rxn00137_c0', 'rxn06023_c0', 'rxn00832_c0', 'rxn00970_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn08661_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn03150_c0', 'rxn00101_c0', 'rxn03087_c0', 'rxn05663_c0', 'rxn03538_c0', 'rxn01213_c0', 'rxn08241_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn00615_c0', 'rxn01265_c0', 'rxn00834_c0', 'rxn00704_c0', 'rxn05154_c0', 'rxn01332_c0', 'rxn03084_c0', 'rxn01790_c0', 'rxn02897_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn05301_c0', 'rxn05223_c0', 'rxn08713_c0', 'rxn02276_c0', 'rxn08620_c0', 'rxn01466_c0', 'rxn02287_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05669_c0', 'rxn05255_c0', 'rxn00929_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn08619_c0', 'rxn01513_c0', 'rxn05306_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn39982_c0', 'rxn12930_c0', 'rxn12932_c0', 'rxn12940_c0', 'rxn12939_c0', 'rxn12929_c0', 'rxn12938_c0', 'rxn12927_c0', 'rxn12921_c0', 'rxn12928_c0', 'rxn12943_c0', 'rxn12942_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn19346_c0', 'rxn19728_c0', 'rxn20235_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn11285_c0', 'rxn08233_c0', 'rxn20627_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd00013_e0', '<', 'new'], ['EX_cpd00020_e0', '<', 'new'], ['rxn00359_c0', '<', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn02320_c0', '<', 'new'], ['rxn00898_c0', '>', 'new'], ['rxn02305_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn00902_c0', '<', 'new'], ['rxn05469_c0', '>', 'new'], ['rxn00789_c0', '<', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00802_c0', '>', 'new'], ['rxn02160_c0', '>', 'new'], ['rxn00957_c0', '>', 'new'], ['rxn02159_c0', '>', 'new'], ['rxn05466_c0', '>', 'new'], ['rxn05957_c0', '>', 'new'], ['rxn00272_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn03435_c0', '<', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03175_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn12868_c0', '>', 'new'], ['rxn02811_c0', '<', 'new'], ['rxn03062_c0', '>', 'new'], ['rxn00863_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn03437_c0', '>', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn02789_c0', '>', 'new'], ['rxn05035_c0', '>', 'new'], ['rxn00333_c0', '>', 'new'], ['rxn01069_c0', '>', 'new'], ['rxn00791_c0', '<', 'new'], ['rxn01302_c0', '<', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn00227_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn00693_c0', '>', 'new'], ['rxn03909_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn02473_c0', '>', 'new'], ['rxn01434_c0', '>', 'new'], ['rxn08094_c0', '<', 'new'], ['rxn02373_c0', '<', 'new'], ['rxn01304_c0', '>', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn02507_c0', '>', 'new'], ['rxn01964_c0', '>', 'new'], ['rxn02186_c0', '>', 'new'], ['rxn01019_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn03194_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn21862_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn21858_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn15395_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn44043_c0', '>', 'new'], ['rxn13339_c0', '>', 'new'], ['rxn13321_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn00907_c0', '>', 'reversed']]
2026-01-13 19:33:28,961 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,962 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00033_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,963 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,964 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,965 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,966 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00065_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,968 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00084_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,969 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00149_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,970 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00107_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,971 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,972 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00027_e0< needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:28,973 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00060_e0< needed:0.0 with min obj:0.01

2026-01-13 19:33:28,975 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00069_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,976 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,977 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00322_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,978 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00156_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,979 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00051_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,980 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00066_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,981 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,982 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,983 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,985 - INFO - PyruateMinimalAnaerobic/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,986 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,987 - INFO - PyruateMinimalAnaerobic/bio1:rxn01483_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,988 - INFO - PyruateMinimalAnaerobic/bio1:rxn00530_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,989 - INFO - PyruateMinimalAnaerobic/bio1:rxn00710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,990 - INFO - PyruateMinimalAnaerobic/bio1:rxn00910_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,992 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,993 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,994 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,995 - INFO - PyruateMinimalAnaerobic/bio1:rxn01362_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:28,996 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,997 - INFO - PyruateMinimalAnaerobic/bio1:rxn05243_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,998 - INFO - PyruateMinimalAnaerobic/bio1:rxn10030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:28,999 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,001 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,002 - INFO - PyruateMinimalAnaerobic/bio1:rxn01301_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,003 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,004 - INFO - PyruateMinimalAnaerobic/bio1:rxn05219_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,005 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,006 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,007 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,009 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,010 - INFO - PyruateMinimalAnaerobic/bio1:rxn00213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,011 - INFO - PyruateMinimalAnaerobic/bio1:rxn05573_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,012 - INFO - PyruateMinimalAnaerobic/bio1:rxn05244_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,013 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,014 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,015 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,017 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,018 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,019 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,020 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,020 - INFO - Objective with gapfill database:86.04689764726818; min objective:0.01
2026-01-13 19:33:29,021 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,022 - INFO - PyruateMinimalAnaerobic/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,024 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,025 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,026 - INFO - PyruateMinimalAnaerobic/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,027 - INFO - PyruateMinimalAnaerobic/bio1:rxn05237_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,028 - INFO - PyruateMinimalAnaerobic/bio1:rxn09113_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,029 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,030 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,031 - INFO - PyruateMinimalAnaerobic/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,033 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,034 - INFO - PyruateMinimalAnaerobic/bio1:rxn00970_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,035 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,036 - INFO - PyruateMinimalAnaerobic/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,037 - INFO - PyruateMinimalAnaerobic/bio1:rxn08661_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,038 - INFO - PyruateMinimalAnaerobic/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,039 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,040 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,042 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,043 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,044 - INFO - PyruateMinimalAnaerobic/bio1:rxn00101_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,045 - INFO - PyruateMinimalAnaerobic/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,046 - INFO - PyruateMinimalAnaerobic/bio1:rxn05663_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,047 - INFO - PyruateMinimalAnaerobic/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,048 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,049 - INFO - PyruateMinimalAnaerobic/bio1:rxn08241_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,051 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,052 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,054 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,055 - INFO - PyruateMinimalAnaerobic/bio1:rxn00615_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,056 - INFO - PyruateMinimalAnaerobic/bio1:rxn01265_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,057 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,058 - INFO - PyruateMinimalAnaerobic/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,059 - INFO - PyruateMinimalAnaerobic/bio1:rxn05154_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,061 - INFO - PyruateMinimalAnaerobic/bio1:rxn01332_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,062 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,063 - INFO - PyruateMinimalAnaerobic/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,064 - INFO - PyruateMinimalAnaerobic/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,065 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,067 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,068 - INFO - PyruateMinimalAnaerobic/bio1:rxn05301_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,069 - INFO - PyruateMinimalAnaerobic/bio1:rxn05223_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,070 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,071 - INFO - PyruateMinimalAnaerobic/bio1:rxn02276_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,073 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,074 - INFO - PyruateMinimalAnaerobic/bio1:rxn01466_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,075 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,076 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,077 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,079 - INFO - PyruateMinimalAnaerobic/bio1:rxn05669_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,080 - INFO - PyruateMinimalAnaerobic/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,081 - INFO - PyruateMinimalAnaerobic/bio1:rxn00929_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,082 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,084 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,085 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,086 - INFO - PyruateMinimalAnaerobic/bio1:rxn01513_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,088 - INFO - PyruateMinimalAnaerobic/bio1:rxn05306_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,089 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,090 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,091 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,092 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,095 - INFO - PyruateMinimalAnaerobic/bio1:rxn39982_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,097 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,098 - INFO - PyruateMinimalAnaerobic/bio1:rxn12932_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,100 - INFO - PyruateMinimalAnaerobic/bio1:rxn12940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,101 - INFO - PyruateMinimalAnaerobic/bio1:rxn12939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,102 - INFO - PyruateMinimalAnaerobic/bio1:rxn12929_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,103 - INFO - PyruateMinimalAnaerobic/bio1:rxn12938_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,104 - INFO - PyruateMinimalAnaerobic/bio1:rxn12927_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,106 - INFO - PyruateMinimalAnaerobic/bio1:rxn12921_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,107 - INFO - PyruateMinimalAnaerobic/bio1:rxn12928_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,108 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,109 - INFO - PyruateMinimalAnaerobic/bio1:rxn12942_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,111 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,112 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,113 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,114 - INFO - PyruateMinimalAnaerobic/bio1:rxn19346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,115 - INFO - PyruateMinimalAnaerobic/bio1:rxn19728_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,117 - INFO - PyruateMinimalAnaerobic/bio1:rxn20235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,118 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,119 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,120 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,121 - INFO - PyruateMinimalAnaerobic/bio1:rxn11285_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,123 - INFO - PyruateMinimalAnaerobic/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,124 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,125 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,126 - INFO - PyruateMinimalAnaerobic/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,127 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,129 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,129 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:33:29,130 - INFO -   Running ATP safety check...

c0

2026-01-13 19:33:29,301 - INFO - Objective with gapfill database:107.98937469951171; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:29,589 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn00423_c0': '>', 'rxn02504_c0': '>', 'rxn03436_c0': '>', 'rxn02160_c0': '>', 'rxn00300_c0': '>', 'rxn00336_c0': '<', 'rxn12376_c0': '<', 'rxn01303_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn00952_c0': '>', 'rxn03841_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn21863_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn21860_c0': '>', 'rxn14424_c0': '>', 'rxn25638_c0': '>', 'rxn11251_c0': '>', 'rxn04551_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn30685_c0': '>', 'rxn08233_c0': '>', 'rxn15939_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:29,592 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:29,594 - INFO - integrating rxn: rxn00423_c0
2026-01-13 19:33:29,596 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:29,597 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:29,599 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:33:29,600 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:29,602 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:33:29,604 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:29,605 - INFO - integrating rxn: rxn01303_c0
2026-01-13 19:33:29,607 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:29,608 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:29,610 - INFO - integrating rxn: rxn00952_c0
2026-01-13 19:33:29,611 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:29,612 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:29,614 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:29,615 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:29,617 - INFO - integrating rxn: rxn21863_c0
2026-01-13 19:33:29,619 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:29,621 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:29,623 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:29,624 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:29,626 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:29,628 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:29,629 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:29,631 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:33:29,632 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:29,634 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:29,635 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:33:29,637 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:33:29,639 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:33:29,640 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:33:29,642 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:29,643 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:33:29,644 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:29,646 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:33:29,647 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:33:29,648 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00084_e0', '<', 'new'], ['EX_cpd00060_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05324_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn05219_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn05744_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn05327_c0', '<', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn05237_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn05325_c0', '<', 'new'], ['rxn01508_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn01361_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00693_c0', '>', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00541_c0', '>', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00778_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05326_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn03004_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn00347_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn02914_c0', '<', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00048_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00084_e0', 'EX_cpd00060_e0', 'EX_cpd00104_e0', 'rxn08709_c0', 'rxn03086_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn09177_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn03030_c0', 'rxn01636_c0', 'rxn05235_c0', 'rxn00470_c0', 'rxn00100_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn05324_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn05229_c0', 'rxn00392_c0', 'rxn05219_c0', 'rxn09225_c0', 'rxn05744_c0', 'rxn02774_c0', 'rxn01675_c0', 'rxn03536_c0', 'rxn01256_c0', 'rxn05327_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn04704_c0', 'rxn01000_c0', 'rxn03397_c0', 'rxn01972_c0', 'rxn11703_c0', 'rxn01300_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn08528_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn10954_c0', 'rxn05645_c0', 'rxn05237_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn01539_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn05325_c0', 'rxn01508_c0', 'rxn00420_c0', 'rxn09657_c0', 'rxn03893_c0', 'rxn01537_c0', 'rxn01213_c0', 'rxn01361_c0', 'rxn03136_c0', 'rxn08088_c0', 'rxn00350_c0', 'rxn00533_c0', 'rxn00834_c0', 'rxn08130_c0', 'rxn11702_c0', 'rxn00693_c0', 'rxn05651_c0', 'rxn03638_c0', 'rxn02056_c0', 'rxn00541_c0', 'rxn00912_c0', 'rxn00122_c0', 'rxn01602_c0', 'rxn05223_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn00778_c0', 'rxn02832_c0', 'rxn05326_c0', 'rxn00256_c0', 'rxn03004_c0', 'rxn00138_c0', 'rxn00347_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn02914_c0', 'rxn00686_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn25637_c0', 'rxn18935_c0', 'rxn25743_c0', 'rxn02485_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn00423_c0', '>', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn02160_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn00336_c0', '<', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn01303_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn00952_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn21863_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:33:29,662 - INFO - EX_cpd00305_e0< not needed:5.684955202840576
2026-01-13 19:33:29,663 - INFO - EX_cpd00393_e0< not needed:5.684955202840576
2026-01-13 19:33:29,665 - INFO - EX_cpd00119_e0< not needed:5.684955202840576
2026-01-13 19:33:29,667 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00048_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,670 - INFO - EX_cpd00220_e0< not needed:5.6849552028405546
2026-01-13 19:33:29,672 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,675 - INFO - EX_cpd00084_e0< not needed:5.684955202840556
2026-01-13 19:33:29,676 - INFO - EX_cpd00060_e0< not needed:5.684955202840571
2026-01-13 19:33:29,678 - INFO - EX_cpd00104_e0< not needed:5.684955202840571
2026-01-13 19:33:29,680 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,682 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,684 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,685 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,687 - INFO - PyruateMinimalAnaerobic/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,689 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,690 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,692 - INFO - PyruateMinimalAnaerobic/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,693 - INFO - PyruateMinimalAnaerobic/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,695 - INFO - PyruateMinimalAnaerobic/bio1:rxn05235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,696 - INFO - PyruateMinimalAnaerobic/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,698 - INFO - PyruateMinimalAnaerobic/bio1:rxn00100_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,699 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,701 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,702 - INFO - PyruateMinimalAnaerobic/bio1:rxn05324_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,704 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,705 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,707 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,708 - INFO - PyruateMinimalAnaerobic/bio1:rxn05229_c0> needed:4.57047252785943e-13 with min obj:0.01
2026-01-13 19:33:29,710 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,712 - INFO - rxn05219_c0> not needed:5.684955202840548
2026-01-13 19:33:29,715 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,716 - INFO - PyruateMinimalAnaerobic/bio1:rxn05744_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,718 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,719 - INFO - PyruateMinimalAnaerobic/bio1:rxn01675_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,720 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,722 - INFO - PyruateMinimalAnaerobic/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,723 - INFO - PyruateMinimalAnaerobic/bio1:rxn05327_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,725 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,726 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,728 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,729 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,731 - INFO - PyruateMinimalAnaerobic/bio1:rxn04704_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,732 - INFO - PyruateMinimalAnaerobic/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,734 - INFO - PyruateMinimalAnaerobic/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,735 - INFO - PyruateMinimalAnaerobic/bio1:rxn01972_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,737 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,742 - INFO - PyruateMinimalAnaerobic/bio1:rxn01300_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,745 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,746 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,748 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,749 - INFO - PyruateMinimalAnaerobic/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,750 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,752 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,753 - INFO - PyruateMinimalAnaerobic/bio1:rxn10954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,756 - INFO - rxn05645_c0> not needed:5.6849552028405785
2026-01-13 19:33:29,757 - INFO - rxn05237_c0> not needed:5.684955202840564
2026-01-13 19:33:29,761 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,762 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,764 - INFO - PyruateMinimalAnaerobic/bio1:rxn01539_c0< needed:-1.0835372368891654e-12 with min obj:0.01
2026-01-13 19:33:29,766 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,769 - INFO - rxn05299_c0> not needed:5.684955202840558
2026-01-13 19:33:29,773 - INFO - PyruateMinimalAnaerobic/bio1:rxn05325_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,775 - INFO - PyruateMinimalAnaerobic/bio1:rxn01508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,778 - INFO - rxn00420_c0> not needed:5.684955202840547
2026-01-13 19:33:29,779 - INFO - rxn09657_c0> not needed:5.684955202840547
2026-01-13 19:33:29,782 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,784 - INFO - PyruateMinimalAnaerobic/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,785 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,787 - INFO - PyruateMinimalAnaerobic/bio1:rxn01361_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,789 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,790 - INFO - PyruateMinimalAnaerobic/bio1:rxn08088_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,792 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,793 - INFO - PyruateMinimalAnaerobic/bio1:rxn00533_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,795 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,797 - INFO - PyruateMinimalAnaerobic/bio1:rxn08130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,798 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,801 - INFO - PyruateMinimalAnaerobic/bio1:rxn00693_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,803 - INFO - PyruateMinimalAnaerobic/bio1:rxn05651_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,804 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,806 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,809 - INFO - PyruateMinimalAnaerobic/bio1:rxn00541_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,811 - INFO - PyruateMinimalAnaerobic/bio1:rxn00912_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,812 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,815 - INFO - rxn01602_c0< not needed:5.684955202840541
2026-01-13 19:33:29,816 - INFO - rxn05223_c0> not needed:5.684955202840651
2026-01-13 19:33:29,819 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,821 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,822 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,823 - INFO - PyruateMinimalAnaerobic/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,825 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,826 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,828 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,831 - INFO - rxn05255_c0> not needed:5.684955202840556
2026-01-13 19:33:29,835 - INFO - PyruateMinimalAnaerobic/bio1:rxn00778_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,837 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,838 - INFO - PyruateMinimalAnaerobic/bio1:rxn05326_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,840 - INFO - PyruateMinimalAnaerobic/bio1:rxn00256_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,842 - INFO - PyruateMinimalAnaerobic/bio1:rxn03004_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,843 - INFO - PyruateMinimalAnaerobic/bio1:rxn00138_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:29,845 - INFO - PyruateMinimalAnaerobic/bio1:rxn00347_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:29,847 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:33:29,946 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'DM_cpd02701_c0': '>', 'rxn02504_c0': '>', 'rxn02305_c0': '>', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn01575_c0': '<', 'rxn12376_c0': '<', 'rxn02312_c0': '>', 'rxn00048_c0': '>', 'rxn03108_c0': '>', 'rxn09310_c0': '>', 'rxn03841_c0': '>', 'rxn01257_c0': '>', 'rxn00806_c0': '<', 'rxn02277_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn21864_c0': '>', 'rxn17731_c0': '>', 'rxn21860_c0': '>', 'rxn12932_c0': '>', 'rxn12939_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12942_c0': '>', 'rxn46124_c0': '>', 'rxn11251_c0': '>', 'rxn40142_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn30685_c0': '>', 'rxn41185_c0': '>', 'rxn10095_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn37059_c0': '>', 'rxn47493_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:29,950 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:29,952 - INFO - integrating rxn: DM_cpd02701_c0
2026-01-13 19:33:29,954 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:29,956 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:33:29,957 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:29,959 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:29,961 - INFO - integrating rxn: rxn01575_c0
2026-01-13 19:33:29,962 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:29,964 - INFO - integrating rxn: rxn02312_c0
2026-01-13 19:33:29,965 - INFO - integrating rxn: rxn00048_c0
2026-01-13 19:33:29,967 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:33:29,969 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:29,970 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:29,972 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:29,973 - INFO - integrating rxn: rxn00806_c0
2026-01-13 19:33:29,975 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:29,977 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:29,978 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:29,980 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:29,982 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:29,984 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:29,986 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:29,988 - INFO - integrating rxn: rxn17731_c0
2026-01-13 19:33:29,989 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:29,990 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:29,992 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:33:29,994 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:29,995 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:33:29,996 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:29,998 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:33:29,999 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:30,001 - INFO - integrating rxn: rxn40142_c0
2026-01-13 19:33:30,002 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:33:30,004 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:33:30,005 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:33:30,006 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:30,008 - INFO - integrating rxn: rxn41185_c0
2026-01-13 19:33:30,009 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:33:30,011 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:33:30,012 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:33:30,014 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:33:30,015 - INFO - integrating rxn: rxn37059_c0
2026-01-13 19:33:30,017 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:30,017 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00034_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn01673_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn00416_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn01637_c0', '<', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn02760_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn00105_c0', '>', 'new'], ['rxn05315_c0', '<', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00502_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn00338_c0', '>', 'new'], ['rxn00119_c0', '>', 'new'], ['rxn00409_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00239_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01019_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn18575_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00034_e0', 'EX_cpd00063_e0', 'EX_cpd00099_e0', 'EX_cpd10515_e0', 'EX_cpd00104_e0', 'rxn08709_c0', 'rxn01673_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn02988_c0', 'rxn00470_c0', 'rxn00416_c0', 'rxn12512_c0', 'rxn01739_c0', 'rxn08583_c0', 'rxn09202_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn01637_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn01256_c0', 'rxn00503_c0', 'rxn00237_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn01000_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn08528_c0', 'rxn03916_c0', 'rxn05645_c0', 'rxn08711_c0', 'rxn02402_c0', 'rxn06023_c0', 'rxn00832_c0', 'rxn02760_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn03150_c0', 'rxn00105_c0', 'rxn05315_c0', 'rxn03538_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn00502_c0', 'rxn03137_c0', 'rxn01512_c0', 'rxn00834_c0', 'rxn08130_c0', 'rxn11702_c0', 'rxn03084_c0', 'rxn03638_c0', 'rxn02897_c0', 'rxn02056_c0', 'rxn00134_c0', 'rxn05223_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn00338_c0', 'rxn00119_c0', 'rxn00409_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn01538_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn00239_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn08619_c0', 'rxn01019_c0', 'rxn00117_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn15166_c0', 'rxn28338_c0', 'rxn01736_c0', 'rxn00644_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn17394_c0', 'rxn14070_c0', 'rxn18575_c0', 'rxn08233_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn46249_c0', 'rxn20472_c0', 'rxn40674_c0', 'rxn08473_c0', ['EX_cpd15378_e0', '>', 'new'], ['DM_cpd02701_c0', '>', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn02305_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn01575_c0', '<', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn02312_c0', '>', 'new'], ['rxn00048_c0', '>', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn01257_c0', '>', 'new'], ['rxn00806_c0', '<', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn17731_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn41185_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn37059_c0', '>', 'new'], ['rxn47493_c0', '>', 'new']]
2026-01-13 19:33:30,023 - INFO - cpd11640 not found in model!
2026-01-13 19:33:30,024 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:30,031 - INFO - EX_cpd00305_e0< not needed:7.46391456966599
2026-01-13 19:33:30,032 - INFO - EX_cpd00393_e0< not needed:7.46391456966599
2026-01-13 19:33:30,034 - INFO - EX_cpd00220_e0< not needed:7.46391456966599
2026-01-13 19:33:30,037 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,039 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00034_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,040 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,042 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,043 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd10515_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,047 - INFO - EX_cpd00104_e0< not needed:7.463914569665992
2026-01-13 19:33:30,050 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,051 - INFO - PyruateMinimalAnaerobic/bio1:rxn01673_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,054 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,056 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,058 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,060 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,062 - INFO - PyruateMinimalAnaerobic/bio1:rxn02988_c0< needed:3.800859603994564e-12 with min obj:0.01
2026-01-13 19:33:30,064 - INFO - PyruateMinimalAnaerobic/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,065 - INFO - PyruateMinimalAnaerobic/bio1:rxn00416_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,067 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,069 - INFO - PyruateMinimalAnaerobic/bio1:rxn01739_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,070 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,072 - INFO - PyruateMinimalAnaerobic/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,073 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,075 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,076 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,078 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,079 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,081 - INFO - PyruateMinimalAnaerobic/bio1:rxn01637_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,082 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,084 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,086 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,087 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,089 - INFO - PyruateMinimalAnaerobic/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,090 - INFO - PyruateMinimalAnaerobic/bio1:rxn00503_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,092 - INFO - PyruateMinimalAnaerobic/bio1:rxn00237_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,093 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,095 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,097 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,099 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,100 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,102 - INFO - PyruateMinimalAnaerobic/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,104 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,106 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,107 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,109 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,111 - INFO - PyruateMinimalAnaerobic/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,112 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,115 - INFO - rxn05645_c0> not needed:7.463914569665967
2026-01-13 19:33:30,117 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,119 - INFO - PyruateMinimalAnaerobic/bio1:rxn02402_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,121 - INFO - PyruateMinimalAnaerobic/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,125 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,127 - INFO - PyruateMinimalAnaerobic/bio1:rxn02760_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,129 - INFO - rxn09657_c0> not needed:7.463914569665993
2026-01-13 19:33:30,132 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,134 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,135 - INFO - PyruateMinimalAnaerobic/bio1:rxn00105_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,137 - INFO - PyruateMinimalAnaerobic/bio1:rxn05315_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,138 - INFO - PyruateMinimalAnaerobic/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,140 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,142 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:1.1201806292418254e-13 with min obj:0.01
2026-01-13 19:33:30,144 - INFO - PyruateMinimalAnaerobic/bio1:rxn00502_c0< needed:-3.765585326098976e-12 with min obj:0.01
2026-01-13 19:33:30,145 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,147 - INFO - PyruateMinimalAnaerobic/bio1:rxn01512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,149 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,151 - INFO - PyruateMinimalAnaerobic/bio1:rxn08130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,152 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,154 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,156 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,157 - INFO - PyruateMinimalAnaerobic/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,159 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,160 - INFO - PyruateMinimalAnaerobic/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,163 - INFO - rxn05223_c0> not needed:7.463914569666038
2026-01-13 19:33:30,165 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,167 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,169 - INFO - PyruateMinimalAnaerobic/bio1:rxn00338_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,170 - INFO - PyruateMinimalAnaerobic/bio1:rxn00119_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,173 - INFO - PyruateMinimalAnaerobic/bio1:rxn00409_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,175 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,177 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,179 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,181 - INFO - rxn01538_c0> not needed:7.463914569665945
2026-01-13 19:33:30,183 - INFO - rxn05255_c0> not needed:7.4639145696659845
2026-01-13 19:33:30,185 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:30,187 - INFO - PyruateMinimalAnaerobic/bio1:rxn00239_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,189 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,190 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:-1.0127623052636082e-11 with min obj:0.01
2026-01-13 19:33:30,192 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,194 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,196 - INFO - PyruateMinimalAnaerobic/bio1:rxn01019_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,198 - INFO - PyruateMinimalAnaerobic/bio1:rxn00117_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,199 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:30,201 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:33:30,693 - INFO - Objective with gapfill database:86.0468976472674; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:33:30,934 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:33:31,081 - INFO - Objective with gapfill database:114.73871061823196; min objective:0.01
2026-01-13 19:33:31,269 - INFO -   Saved gapfilled model: gapfilled_models2/DMER64.1_gf.xml
2026-01-13 19:33:31,271 - INFO -   Total reactions added: 430
2026-01-13 19:33:31,395 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:33:31,612 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'DM_cpd02701_c0': '>', 'rxn02320_c0': '<', 'rxn02504_c0': '>', 'rxn00796_c0': '>', 'rxn00789_c0': '<', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn02835_c0': '>', 'rxn03175_c0': '>', 'rxn12376_c0': '<', 'rxn01539_c0': '<', 'rxn02312_c0': '>', 'rxn00726_c0': '>', 'rxn00791_c0': '<', 'rxn01537_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn03909_c0': '>', 'rxn02277_c0': '>', 'rxn02185_c0': '<', 'rxn02473_c0': '>', 'rxn02507_c0': '>', 'rxn01603_c0': '>', 'rxn21857_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn21862_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn47768_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn21858_c0': '>', 'rxn20834_c0': '>', 'rxn21861_c0': '>', 'rxn21860_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn30633_c0': '>', 'rxn15395_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn16114_c0': '>', 'rxn30685_c0': '>', 'rxn15940_c0': '>', 'rxn47493_c0': '>', 'rxn09390_c0': '>', 'rxn14423_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:31,615 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:31,617 - INFO - integrating rxn: DM_cpd02701_c0
2026-01-13 19:33:31,620 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:33:31,621 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:31,623 - INFO - integrating rxn: rxn00796_c0
2026-01-13 19:33:31,625 - INFO - integrating rxn: rxn00789_c0
2026-01-13 19:33:31,626 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:31,629 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:31,630 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:33:31,632 - INFO - integrating rxn: rxn03175_c0
2026-01-13 19:33:31,634 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:31,635 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:31,637 - INFO - integrating rxn: rxn02312_c0
2026-01-13 19:33:31,639 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:33:31,641 - INFO - integrating rxn: rxn00791_c0
2026-01-13 19:33:31,642 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:33:31,644 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:31,646 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:31,648 - INFO - integrating rxn: rxn03909_c0
2026-01-13 19:33:31,650 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:31,651 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:31,653 - INFO - integrating rxn: rxn02473_c0
2026-01-13 19:33:31,655 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:33:31,657 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:31,658 - INFO - integrating rxn: rxn21857_c0
2026-01-13 19:33:31,660 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:31,662 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:31,664 - INFO - integrating rxn: rxn21862_c0
2026-01-13 19:33:31,666 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:31,667 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:31,669 - INFO - integrating rxn: rxn47768_c0
2026-01-13 19:33:31,670 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:31,672 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:31,674 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:31,676 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:31,677 - INFO - integrating rxn: rxn21858_c0
2026-01-13 19:33:31,679 - INFO - integrating rxn: rxn20834_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:31,681 - INFO - integrating rxn: rxn21861_c0

c0

2026-01-13 19:33:31,683 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:31,685 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:33:31,687 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:33:31,689 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:33:31,690 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:33:31,691 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:33:31,692 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:33:31,693 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:31,694 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:33:31,696 - INFO - integrating rxn: rxn30633_c0
2026-01-13 19:33:31,698 - INFO - integrating rxn: rxn15395_c0
2026-01-13 19:33:31,699 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:33:31,701 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:33:31,702 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:33:31,703 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:31,705 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:31,706 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:33:31,708 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:31,709 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:33:31,710 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:33:31,711 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00423_c0', '>', 'new'], ['rxn05457_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn05235_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn12933_c0', '<', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn00097_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn00774_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00340_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn05957_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn05345_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn05744_c0', '>', 'new'], ['rxn02175_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn08311_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn03843_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn05465_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03244_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00410_c0', '>', 'new'], ['rxn05342_c0', '<', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02937_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn03249_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00558_c0', '<', 'new'], ['rxn00077_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00991_c0', '<', 'new'], ['rxn03242_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn00114_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn00119_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn00409_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03004_c0', '>', 'new'], ['rxn06729_c0', '>', 'new'], ['rxn03031_c0', '>', 'new'], ['rxn00239_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn05232_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn03246_c0', '<', 'new'], ['rxn06075_c0', '<', 'new'], ['rxn09149_c0', '<', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn01520_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00220_e0', 'EX_cpd00065_e0', 'EX_cpd00058_e0', 'EX_cpd00063_e0', 'rxn08709_c0', 'rxn00423_c0', 'rxn05457_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn05235_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn12933_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn00097_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn00774_c0', 'rxn03918_c0', 'rxn00340_c0', 'rxn10030_c0', 'rxn05957_c0', 'rxn08708_c0', 'rxn02404_c0', 'rxn05345_c0', 'rxn00392_c0', 'rxn00830_c0', 'rxn09225_c0', 'rxn00029_c0', 'rxn05744_c0', 'rxn02175_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn01501_c0', 'rxn00237_c0', 'rxn08311_c0', 'rxn03919_c0', 'rxn09210_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03159_c0', 'rxn03397_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn03843_c0', 'rxn08711_c0', 'rxn05465_c0', 'rxn00832_c0', 'rxn10094_c0', 'rxn03244_c0', 'rxn04139_c0', 'rxn06723_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn00410_c0', 'rxn05342_c0', 'rxn03150_c0', 'rxn05663_c0', 'rxn03538_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn02937_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn01512_c0', 'rxn06865_c0', 'rxn03249_c0', 'rxn00834_c0', 'rxn11702_c0', 'rxn03439_c0', 'rxn00558_c0', 'rxn00077_c0', 'rxn03638_c0', 'rxn02897_c0', 'rxn02056_c0', 'rxn00991_c0', 'rxn03242_c0', 'rxn00134_c0', 'rxn02003_c0', 'rxn00130_c0', 'rxn00122_c0', 'rxn00114_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn00119_c0', 'rxn01466_c0', 'rxn00409_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn01538_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn03004_c0', 'rxn06729_c0', 'rxn03031_c0', 'rxn00239_c0', 'rxn03130_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn05232_c0', 'rxn08619_c0', 'rxn03246_c0', 'rxn06075_c0', 'rxn09149_c0', 'rxn00117_c0', 'rxn01520_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn16218_c0', 'rxn15949_c0', 'rxn16217_c0', 'rxn15947_c0', 'rxn25474_c0', 'rxn19728_c0', 'rxn20235_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn20627_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn43975_c0', 'rxn42732_c0', 'rxn41263_c0', 'rxn20839_c0', ['EX_cpd15378_e0', '>', 'new'], ['DM_cpd02701_c0', '>', 'new'], ['rxn02320_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn00796_c0', '>', 'new'], ['rxn00789_c0', '<', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn03175_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn02312_c0', '>', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn00791_c0', '<', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn03909_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn02473_c0', '>', 'new'], ['rxn02507_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn21857_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn21862_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn47768_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn21858_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn21861_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn15395_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:33:31,730 - INFO - EX_cpd00305_e0< not needed:4.428758339025705
2026-01-13 19:33:31,731 - INFO - EX_cpd00393_e0< not needed:4.428758339025705
2026-01-13 19:33:31,732 - INFO - EX_cpd00220_e0< not needed:4.428758339025705
2026-01-13 19:33:31,734 - INFO - EX_cpd00065_e0< not needed:4.428758339025705
2026-01-13 19:33:31,736 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,738 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,739 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,742 - INFO - rxn00423_c0> not needed:4.428758339025715
2026-01-13 19:33:31,744 - INFO - rxn05457_c0< not needed:4.428758339025705
2026-01-13 19:33:31,746 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,748 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,749 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,751 - INFO - PyruateMinimalAnaerobic/bio1:rxn05235_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,752 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,754 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,755 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,757 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,759 - INFO - PyruateMinimalAnaerobic/bio1:rxn12933_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,761 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,762 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,765 - INFO - PyruateMinimalAnaerobic/bio1:rxn00097_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,767 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,769 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,770 - INFO - PyruateMinimalAnaerobic/bio1:rxn00774_c0> needed:-3.571115782694633e-13 with min obj:0.01
2026-01-13 19:33:31,772 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,773 - INFO - PyruateMinimalAnaerobic/bio1:rxn00340_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,775 - INFO - PyruateMinimalAnaerobic/bio1:rxn10030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,776 - INFO - PyruateMinimalAnaerobic/bio1:rxn05957_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,778 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,780 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,781 - INFO - PyruateMinimalAnaerobic/bio1:rxn05345_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,783 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,784 - INFO - PyruateMinimalAnaerobic/bio1:rxn00830_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,786 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,787 - INFO - PyruateMinimalAnaerobic/bio1:rxn00029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,790 - INFO - rxn05744_c0> not needed:4.4287583390257135
2026-01-13 19:33:31,795 - INFO - PyruateMinimalAnaerobic/bio1:rxn02175_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,796 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,798 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,799 - INFO - PyruateMinimalAnaerobic/bio1:rxn01501_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,801 - INFO - PyruateMinimalAnaerobic/bio1:rxn00237_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,802 - INFO - PyruateMinimalAnaerobic/bio1:rxn08311_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,804 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,806 - INFO - PyruateMinimalAnaerobic/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,807 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,809 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,810 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,812 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,814 - INFO - PyruateMinimalAnaerobic/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,815 - INFO - PyruateMinimalAnaerobic/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,817 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,819 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,821 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,822 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,824 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,825 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,828 - INFO - rxn05645_c0> not needed:4.428758339025709
2026-01-13 19:33:31,832 - INFO - PyruateMinimalAnaerobic/bio1:rxn03843_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,834 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,836 - INFO - PyruateMinimalAnaerobic/bio1:rxn05465_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,837 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,839 - INFO - PyruateMinimalAnaerobic/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,841 - INFO - PyruateMinimalAnaerobic/bio1:rxn03244_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,843 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,844 - INFO - PyruateMinimalAnaerobic/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,848 - INFO - rxn09657_c0> not needed:4.4287583390257055
2026-01-13 19:33:31,850 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,852 - INFO - PyruateMinimalAnaerobic/bio1:rxn00410_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,854 - INFO - PyruateMinimalAnaerobic/bio1:rxn05342_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,855 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,858 - INFO - rxn05663_c0> not needed:4.428758339025708
2026-01-13 19:33:31,860 - INFO - PyruateMinimalAnaerobic/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,862 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,864 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,865 - INFO - PyruateMinimalAnaerobic/bio1:rxn02937_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,867 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,869 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,870 - INFO - PyruateMinimalAnaerobic/bio1:rxn01512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,872 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,874 - INFO - PyruateMinimalAnaerobic/bio1:rxn03249_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,875 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,877 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,878 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,880 - INFO - PyruateMinimalAnaerobic/bio1:rxn00558_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,881 - INFO - PyruateMinimalAnaerobic/bio1:rxn00077_c0> needed:-7.795519642060084e-13 with min obj:0.01
2026-01-13 19:33:31,883 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,885 - INFO - PyruateMinimalAnaerobic/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,886 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,888 - INFO - PyruateMinimalAnaerobic/bio1:rxn00991_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,889 - INFO - PyruateMinimalAnaerobic/bio1:rxn03242_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,891 - INFO - PyruateMinimalAnaerobic/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,893 - INFO - PyruateMinimalAnaerobic/bio1:rxn02003_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,894 - INFO - PyruateMinimalAnaerobic/bio1:rxn00130_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:31,896 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,897 - INFO - PyruateMinimalAnaerobic/bio1:rxn00114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,899 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,900 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,903 - INFO - PyruateMinimalAnaerobic/bio1:rxn00119_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,904 - INFO - PyruateMinimalAnaerobic/bio1:rxn01466_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,906 - INFO - PyruateMinimalAnaerobic/bio1:rxn00409_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,908 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,909 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,911 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:31,913 - INFO - rxn01538_c0> not needed:4.4287583390257
2026-01-13 19:33:31,915 - INFO - rxn05255_c0> not needed:4.428758339025697
2026-01-13 19:33:31,917 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01

c0
Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:33:32,399 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:33:32,731 - INFO -   Saved gapfilled model: gapfilled_models2/Christensenellaceae_R-7_group.57_gf.xml
2026-01-13 19:33:32,733 - INFO -   Total reactions added: 374
2026-01-13 19:33:32,857 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:33:32,927 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:32,942 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:32,951 - INFO - cpd00363 not found in model!
2026-01-13 19:33:32,952 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:32,955 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:32,966 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:32,976 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:32,986 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:32,996 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,006 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,014 - INFO - cpd00159 not found in model!
2026-01-13 19:33:33,015 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:33,018 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,028 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,038 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,048 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,058 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,066 - INFO - cpd00363 not found in model!
2026-01-13 19:33:33,066 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:33,069 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,079 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,099 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,108 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,118 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,126 - INFO - cpd00159 not found in model!
2026-01-13 19:33:33,127 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:33,130 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:33:33,139 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,146 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:33:33,149 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,159 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,167 - INFO - cpd00075 not found in model!
2026-01-13 19:33:33,168 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:33,171 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,179 - INFO - cpd00209 not found in model!
2026-01-13 19:33:33,180 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:33,183 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,191 - INFO - cpd00418 not found in model!
2026-01-13 19:33:33,192 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:33,194 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,200 - INFO - Objective with gapfill database:86.0468976472674; min objective:0.01
2026-01-13 19:33:33,203 - INFO - cpd00075 not found in model!
2026-01-13 19:33:33,203 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:33,206 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,214 - INFO - cpd00209 not found in model!
2026-01-13 19:33:33,215 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:33,218 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,226 - INFO - cpd00418 not found in model!
2026-01-13 19:33:33,227 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:33,229 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,237 - INFO - cpd00075 not found in model!
2026-01-13 19:33:33,238 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:33,241 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,249 - INFO - cpd00209 not found in model!
2026-01-13 19:33:33,249 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:33,252 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,260 - INFO - cpd00418 not found in model!
2026-01-13 19:33:33,261 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:33,263 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,271 - INFO - cpd08021 not found in model!
2026-01-13 19:33:33,272 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:33,274 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,283 - INFO - cpd00811 not found in model!
2026-01-13 19:33:33,283 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:33,286 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,295 - INFO - cpd08021 not found in model!
2026-01-13 19:33:33,296 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:33,299 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,307 - INFO - cpd00811 not found in model!
2026-01-13 19:33:33,307 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:33,310 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,319 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,329 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,337 - INFO - cpd11640 not found in model!
2026-01-13 19:33:33,338 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:33,341 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,349 - INFO - cpd11640 not found in model!
2026-01-13 19:33:33,350 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:33,352 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,361 - INFO - cpd11640 not found in model!
2026-01-13 19:33:33,362 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:33,364 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,372 - INFO - cpd00159 not found in model!
2026-01-13 19:33:33,373 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:33,374 - INFO - cpd11640 not found in model!
2026-01-13 19:33:33,374 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:33,377 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,387 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,395 - INFO - cpd00159 not found in model!
2026-01-13 19:33:33,395 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:33,398 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,406 - INFO - cpd11640 not found in model!
2026-01-13 19:33:33,406 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:33,409 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,419 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,427 - INFO - cpd11632 not found in model!
2026-01-13 19:33:33,428 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:33:33,431 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,439 - INFO - cpd08701 not found in model!
2026-01-13 19:33:33,440 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:33:33,440 - INFO - cpd01024 not found in model!
2026-01-13 19:33:33,441 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:33,443 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,451 - INFO - cpd01024 not found in model!
2026-01-13 19:33:33,452 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:33,455 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,465 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,473 - INFO - cpd11640 not found in model!
2026-01-13 19:33:33,473 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:33,476 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,484 - INFO - cpd11640 not found in model!
2026-01-13 19:33:33,485 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:33,485 - INFO - cpd00187 not found in model!
2026-01-13 19:33:33,486 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:33:33,489 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,497 - INFO - cpd11640 not found in model!
2026-01-13 19:33:33,498 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:33,498 - INFO - cpd00425 not found in model!
2026-01-13 19:33:33,499 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:33:33,502 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,510 - INFO - cpd11640 not found in model!
2026-01-13 19:33:33,511 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:33,512 - INFO - cpd00441 not found in model!
2026-01-13 19:33:33,514 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:33:33,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:33,784 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'DM_cpd02701_c0': '>', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn02835_c0': '>', 'rxn00503_c0': '<', 'rxn12376_c0': '<', 'rxn02312_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn02277_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn21860_c0': '>', 'rxn11274_c0': '>', 'rxn12932_c0': '>', 'rxn12939_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12942_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn16671_c0': '>', 'rxn30685_c0': '>', 'rxn20508_c0': '>', 'rxn15939_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn47493_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:33,787 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:33,789 - INFO - integrating rxn: DM_cpd02701_c0
2026-01-13 19:33:33,790 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:33,792 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:33,794 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:33:33,795 - INFO - integrating rxn: rxn00503_c0
2026-01-13 19:33:33,797 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:33,798 - INFO - integrating rxn: rxn02312_c0
2026-01-13 19:33:33,800 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:33,802 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:33,804 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:33,805 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:33,807 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:33,808 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:33,810 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:33:33,812 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:33,814 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:33,815 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:33,817 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:33,818 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:33,819 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:33,821 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:33,822 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:33,824 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:33,825 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:33:33,827 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:33,828 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:33:33,829 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:33:33,831 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:33:33,833 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:33:33,834 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:33:33,836 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:33,837 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:33:33,839 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:33:33,840 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:33:33,841 - INFO - integrating rxn: rxn16671_c0
2026-01-13 19:33:33,843 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:33,844 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:33:33,846 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:33,847 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:33:33,848 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:33:33,850 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:33:33,851 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:33,852 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn01967_c0', '<', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn05117_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn01541_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn03086_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn03030_c0', 'rxn01636_c0', 'rxn01117_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn02404_c0', 'rxn10204_c0', 'rxn06937_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn01256_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03159_c0', 'rxn01000_c0', 'rxn01972_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn01967_c0', 'rxn08711_c0', 'rxn04413_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn01539_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn05029_c0', 'rxn01537_c0', 'rxn02303_c0', 'rxn03907_c0', 'rxn01213_c0', 'rxn02304_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn06865_c0', 'rxn04113_c0', 'rxn05117_c0', 'rxn03439_c0', 'rxn03638_c0', 'rxn01541_c0', 'rxn02056_c0', 'rxn00134_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn03130_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn14424_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn02485_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn10095_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn14423_c0', ['EX_cpd15378_e0', '>', 'new'], ['DM_cpd02701_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn02312_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn16671_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn47493_c0', '>', 'new']]
2026-01-13 19:33:33,865 - INFO - EX_cpd00305_e0< not needed:3.0102730435197094
2026-01-13 19:33:33,866 - INFO - EX_cpd00393_e0< not needed:3.0102730435197094
2026-01-13 19:33:33,867 - INFO - EX_cpd00119_e0< not needed:3.0102730435197094
2026-01-13 19:33:33,869 - INFO - EX_cpd00220_e0< not needed:3.0102730435197094
2026-01-13 19:33:33,871 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:33,872 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:33,874 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:33,876 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:-1.730579963094182e-13 with min obj:0.01
2026-01-13 19:33:33,878 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:33:34,064 - INFO - cpd00159 not found in model!
2026-01-13 19:33:34,064 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:34,067 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,077 - INFO - cpd00221 not found in model!
2026-01-13 19:33:34,078 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:33:34,080 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,098 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,107 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,116 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,127 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,136 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,145 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,154 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,163 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,171 - INFO - cpd00159 not found in model!
2026-01-13 19:33:34,172 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:34,175 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,186 - INFO - cpd00221 not found in model!
2026-01-13 19:33:34,187 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:33:34,191 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,201 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,211 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,219 - INFO - cpd00075 not found in model!
2026-01-13 19:33:34,220 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:34,223 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,232 - INFO - cpd00209 not found in model!
2026-01-13 19:33:34,233 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:34,236 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,244 - INFO - cpd00418 not found in model!
2026-01-13 19:33:34,244 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:34,248 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,257 - INFO - cpd00075 not found in model!
2026-01-13 19:33:34,258 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:34,261 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,269 - INFO - cpd00209 not found in model!
2026-01-13 19:33:34,269 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:34,272 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,281 - INFO - cpd00418 not found in model!
2026-01-13 19:33:34,283 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:34,286 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,294 - INFO - cpd00075 not found in model!
2026-01-13 19:33:34,295 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:34,297 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,305 - INFO - cpd00209 not found in model!
2026-01-13 19:33:34,305 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:34,308 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,315 - INFO - cpd00418 not found in model!
2026-01-13 19:33:34,316 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:34,319 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,327 - INFO - cpd08021 not found in model!
2026-01-13 19:33:34,328 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:34,331 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,340 - INFO - cpd00811 not found in model!
2026-01-13 19:33:34,341 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:34,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,351 - INFO - cpd08021 not found in model!
2026-01-13 19:33:34,352 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:34,355 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,363 - INFO - cpd00811 not found in model!
2026-01-13 19:33:34,364 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:34,366 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,378 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,387 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,395 - INFO - cpd11640 not found in model!
2026-01-13 19:33:34,396 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:34,399 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,408 - INFO - cpd11640 not found in model!
2026-01-13 19:33:34,409 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:34,412 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,421 - INFO - cpd11640 not found in model!
2026-01-13 19:33:34,422 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:34,425 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,434 - INFO - cpd00159 not found in model!
2026-01-13 19:33:34,435 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:34,436 - INFO - cpd11640 not found in model!
2026-01-13 19:33:34,436 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:34,440 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,451 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,460 - INFO - cpd00159 not found in model!
2026-01-13 19:33:34,461 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:34,464 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,472 - INFO - cpd11640 not found in model!
2026-01-13 19:33:34,473 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:34,476 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,486 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,495 - INFO - cpd11632 not found in model!
2026-01-13 19:33:34,497 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:33:34,500 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,507 - INFO - cpd08701 not found in model!
2026-01-13 19:33:34,508 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:33:34,509 - INFO - cpd01024 not found in model!
2026-01-13 19:33:34,510 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:34,513 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:34,521 - INFO - cpd01024 not found in model!
2026-01-13 19:33:34,522 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:34,524 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,533 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,542 - INFO - cpd11640 not found in model!
2026-01-13 19:33:34,543 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:34,546 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,555 - INFO - cpd11640 not found in model!
2026-01-13 19:33:34,556 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:34,557 - INFO - cpd00187 not found in model!
2026-01-13 19:33:34,558 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:33:34,562 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,573 - INFO - cpd11640 not found in model!
2026-01-13 19:33:34,574 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:34,575 - INFO - cpd00425 not found in model!
2026-01-13 19:33:34,577 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:33:34,581 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:34,592 - INFO - cpd11640 not found in model!
2026-01-13 19:33:34,593 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:34,594 - INFO - cpd00441 not found in model!
2026-01-13 19:33:34,595 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:33:34,599 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:35,824 - INFO - Objective with gapfill database:86.04689764726719; min objective:0.01
2026-01-13 19:33:38,294 - INFO - Objective with gapfill database:86.04689764726719; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:39,016 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00359_c0': '<', 'rxn00796_c0': '>', 'rxn00957_c0': '>', 'rxn00300_c0': '>', 'rxn02835_c0': '>', 'rxn01539_c0': '<', 'rxn00333_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn12239_c0': '>', 'rxn00782_c0': '<', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02473_c0': '>', 'rxn00623_c0': '<', 'rxn01603_c0': '>', 'rxn00157_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12939_c0': '>', 'rxn12928_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15166_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn30685_c0': '>', 'rxn16341_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:39,020 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:33:39,022 - INFO - integrating rxn: rxn00796_c0
2026-01-13 19:33:39,024 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:33:39,025 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:39,027 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:33:39,029 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:39,031 - INFO - integrating rxn: rxn00333_c0
2026-01-13 19:33:39,033 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:39,035 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:39,037 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:39,038 - INFO - integrating rxn: rxn00782_c0
2026-01-13 19:33:39,040 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:39,042 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:39,043 - INFO - integrating rxn: rxn02473_c0
2026-01-13 19:33:39,045 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:33:39,047 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:39,048 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:33:39,050 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:39,052 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:39,053 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:39,055 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:39,057 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:39,058 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:39,060 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:39,061 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:39,063 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:39,064 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:39,066 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:33:39,068 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:33:39,070 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:33:39,071 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:33:39,073 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:33:39,075 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:33:39,076 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:33:39,078 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:33:39,080 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:33:39,081 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:33:39,083 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:39,084 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:33:39,085 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:33:39,087 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:33:39,088 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:33:39,089 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00991_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00912_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00063_e0', 'EX_cpd00099_e0', 'EX_cpd00104_e0', 'rxn08709_c0', 'rxn02000_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn01636_c0', 'rxn08710_c0', 'rxn12512_c0', 'rxn03436_c0', 'rxn08583_c0', 'rxn09202_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn01997_c0', 'rxn03918_c0', 'rxn10030_c0', 'rxn08708_c0', 'rxn00907_c0', 'rxn10213_c0', 'rxn02404_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn01675_c0', 'rxn01501_c0', 'rxn09210_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03397_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn04413_c0', 'rxn00832_c0', 'rxn10094_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn00420_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn03150_c0', 'rxn01537_c0', 'rxn03087_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn00704_c0', 'rxn11702_c0', 'rxn01790_c0', 'rxn03638_c0', 'rxn02056_c0', 'rxn00991_c0', 'rxn03075_c0', 'rxn02003_c0', 'rxn02185_c0', 'rxn00912_c0', 'rxn00122_c0', 'rxn05223_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn16218_c0', 'rxn15949_c0', 'rxn16217_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn08233_c0', 'rxn20627_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn43975_c0', 'rxn42732_c0', 'rxn41263_c0', 'rxn20839_c0', ['rxn00359_c0', '<', 'new'], ['rxn00796_c0', '>', 'new'], ['rxn00957_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn00333_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn00782_c0', '<', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02473_c0', '>', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn00157_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:33:39,110 - INFO - EX_cpd00305_e0< not needed:3.430919840100808
2026-01-13 19:33:39,112 - INFO - EX_cpd00393_e0< not needed:3.430919840100808
2026-01-13 19:33:39,113 - INFO - EX_cpd00119_e0< not needed:3.430919840100808
2026-01-13 19:33:39,115 - INFO - EX_cpd00220_e0< not needed:3.430919840100808
2026-01-13 19:33:39,117 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,119 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,121 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,123 - INFO - EX_cpd00104_e0< not needed:3.4309198401008194
2026-01-13 19:33:39,126 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,127 - INFO - PyruateMinimalAnaerobic/bio1:rxn02000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,129 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,131 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,133 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,135 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,136 - INFO - PyruateMinimalAnaerobic/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,138 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,140 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,141 - INFO - PyruateMinimalAnaerobic/bio1:rxn03436_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,143 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,144 - INFO - PyruateMinimalAnaerobic/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,146 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,148 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,149 - INFO - PyruateMinimalAnaerobic/bio1:rxn01997_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,151 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,153 - INFO - PyruateMinimalAnaerobic/bio1:rxn10030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,155 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,157 - INFO - rxn00907_c0> not needed:3.4309198401008136
2026-01-13 19:33:39,160 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,162 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,164 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,165 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,167 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,168 - INFO - PyruateMinimalAnaerobic/bio1:rxn01675_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,170 - INFO - PyruateMinimalAnaerobic/bio1:rxn01501_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,172 - INFO - PyruateMinimalAnaerobic/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,173 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,175 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,176 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,178 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,180 - INFO - PyruateMinimalAnaerobic/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,181 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,183 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,184 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,187 - INFO - rxn00966_c0< not needed:3.430919840100804
2026-01-13 19:33:39,190 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,191 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,195 - INFO - rxn05645_c0> not needed:3.4309198401008123
2026-01-13 19:33:39,197 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,200 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,201 - INFO - PyruateMinimalAnaerobic/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,203 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,205 - INFO - rxn05299_c0> not needed:3.430919840100809
2026-01-13 19:33:39,207 - INFO - rxn00420_c0> not needed:3.430919840100811
2026-01-13 19:33:39,208 - INFO - rxn09657_c0> not needed:3.430919840100811
2026-01-13 19:33:39,210 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,212 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,218 - INFO - PyruateMinimalAnaerobic/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,221 - INFO - PyruateMinimalAnaerobic/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,223 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,226 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,227 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,229 - INFO - PyruateMinimalAnaerobic/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,231 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,233 - INFO - PyruateMinimalAnaerobic/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,235 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,236 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,239 - INFO - rxn00991_c0< not needed:3.4309198401008105
2026-01-13 19:33:39,242 - INFO - PyruateMinimalAnaerobic/bio1:rxn03075_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,244 - INFO - PyruateMinimalAnaerobic/bio1:rxn02003_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,246 - INFO - PyruateMinimalAnaerobic/bio1:rxn02185_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,248 - INFO - PyruateMinimalAnaerobic/bio1:rxn00912_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,250 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,251 - INFO - rxn05223_c0> not needed:3.4309198401008203
2026-01-13 19:33:39,254 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,256 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,257 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,259 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,261 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,263 - INFO - rxn05255_c0> not needed:3.430919840100815
2026-01-13 19:33:39,266 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:39,268 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,269 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,271 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,273 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,274 - INFO - PyruateMinimalAnaerobic/bio1:rxn16218_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,276 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,278 - INFO - PyruateMinimalAnaerobic/bio1:rxn16217_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,279 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,281 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,283 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,284 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,286 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,287 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,289 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,291 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,293 - INFO - PyruateMinimalAnaerobic/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,294 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,302 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,304 - INFO - PyruateMinimalAnaerobic/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,306 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,308 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,310 - INFO - PyruateMinimalAnaerobic/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:39,312 - INFO - PyruateMinimalAnaerobic/bio1:rxn42732_c0> needed:0.0 with min obj:0.01

c0
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:42,341 - INFO - Objective with gapfill database:107.98937469951238; min objective:0.01
2026-01-13 19:33:42,680 - INFO - Objective with gapfill database:86.04689764726673; min objective:0.01
2026-01-13 19:33:43,145 - INFO - Objective with gapfill database:86.04689764726756; min objective:0.01
2026-01-13 19:33:43,239 - INFO - Objective with gapfill database:86.04689764726623; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:43,865 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,880 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,889 - INFO - cpd00363 not found in model!
2026-01-13 19:33:43,890 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:43,893 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,903 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,913 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,923 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,932 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,942 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,950 - INFO - cpd00159 not found in model!
2026-01-13 19:33:43,951 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:43,953 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,961 - INFO - cpd00221 not found in model!
2026-01-13 19:33:43,962 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:33:43,965 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,975 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:43,997 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,005 - INFO - cpd00363 not found in model!
2026-01-13 19:33:44,005 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:44,008 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,017 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,027 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,036 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,055 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,063 - INFO - cpd00159 not found in model!
2026-01-13 19:33:44,064 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:44,067 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,075 - INFO - cpd00221 not found in model!
2026-01-13 19:33:44,076 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:33:44,078 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,088 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,098 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,106 - INFO - cpd00075 not found in model!
2026-01-13 19:33:44,107 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:44,109 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,118 - INFO - cpd00209 not found in model!
2026-01-13 19:33:44,118 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:44,121 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,129 - INFO - cpd00418 not found in model!
2026-01-13 19:33:44,129 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:44,132 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,140 - INFO - cpd00075 not found in model!
2026-01-13 19:33:44,140 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:44,143 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,151 - INFO - cpd00209 not found in model!
2026-01-13 19:33:44,151 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:44,154 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,162 - INFO - cpd00418 not found in model!
2026-01-13 19:33:44,162 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:44,165 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,173 - INFO - cpd00075 not found in model!
2026-01-13 19:33:44,173 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:44,176 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,184 - INFO - cpd00209 not found in model!
2026-01-13 19:33:44,185 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:44,188 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,195 - INFO - cpd00418 not found in model!
2026-01-13 19:33:44,196 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:44,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,206 - INFO - cpd08021 not found in model!
2026-01-13 19:33:44,207 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:44,209 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,217 - INFO - cpd00811 not found in model!
2026-01-13 19:33:44,218 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:44,221 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,228 - INFO - cpd08021 not found in model!
2026-01-13 19:33:44,229 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:44,231 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,239 - INFO - cpd00811 not found in model!
2026-01-13 19:33:44,240 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:44,242 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,252 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,262 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,271 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,281 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,291 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,299 - INFO - cpd00159 not found in model!
2026-01-13 19:33:44,299 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:44,302 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,312 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,320 - INFO - cpd00159 not found in model!
2026-01-13 19:33:44,321 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:44,323 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,333 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,350 - INFO - cpd11632 not found in model!
2026-01-13 19:33:44,351 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:33:44,354 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,362 - INFO - cpd08701 not found in model!
2026-01-13 19:33:44,362 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:33:44,363 - INFO - cpd01024 not found in model!
2026-01-13 19:33:44,364 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:44,366 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,374 - INFO - cpd01024 not found in model!
2026-01-13 19:33:44,375 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:44,377 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,387 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,397 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,406 - INFO - cpd00187 not found in model!
2026-01-13 19:33:44,407 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:33:44,410 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,418 - INFO - cpd00425 not found in model!
2026-01-13 19:33:44,419 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:33:44,422 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:33:44,430 - INFO - cpd00441 not found in model!
2026-01-13 19:33:44,431 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:33:44,434 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:44,439 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:33:44,756 - INFO - Objective with gapfill database:107.98937469951238; min objective:0.01
2026-01-13 19:33:44,805 - INFO -   Saved gapfilled model: gapfilled_models2/Acholeplasma.3_gf.xml
2026-01-13 19:33:44,807 - INFO -   Total reactions added: 404
2026-01-13 19:33:44,944 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:33:45,158 - INFO - Objective with gapfill database:86.04689764726673; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:33:45,266 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:33:45,324 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00020_e0': '<', 'rxn00958_c0': '>', 'rxn05469_c0': '>', 'rxn03436_c0': '>', 'rxn00503_c0': '<', 'rxn12868_c0': '>', 'rxn01539_c0': '<', 'rxn01537_c0': '>', 'rxn09310_c0': '>', 'rxn00502_c0': '<', 'rxn03841_c0': '>', 'rxn12239_c0': '>', 'rxn01257_c0': '>', 'rxn00541_c0': '>', 'rxn00309_c0': '<', 'rxn00430_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn21860_c0': '>', 'rxn11274_c0': '>', 'rxn12932_c0': '>', 'rxn25743_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn15166_c0': '>', 'rxn16114_c0': '>', 'rxn15550_c0': '>', 'rxn15072_c0': '>', 'rxn30685_c0': '>', 'rxn41185_c0': '>', 'rxn13741_c0': '>', 'rxn08921_c0': '>', 'rxn08474_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:45,327 - INFO - integrating rxn: EX_cpd00020_e0
2026-01-13 19:33:45,329 - INFO - integrating rxn: rxn00958_c0
2026-01-13 19:33:45,331 - INFO - integrating rxn: rxn05469_c0
2026-01-13 19:33:45,333 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:45,334 - INFO - integrating rxn: rxn00503_c0
2026-01-13 19:33:45,336 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:33:45,338 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:45,339 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:33:45,341 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:45,343 - INFO - integrating rxn: rxn00502_c0
2026-01-13 19:33:45,344 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:45,346 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:45,347 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:45,348 - INFO - integrating rxn: rxn00541_c0
2026-01-13 19:33:45,350 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:45,351 - INFO - integrating rxn: rxn00430_c0
2026-01-13 19:33:45,353 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:45,354 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:45,355 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:45,357 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:45,358 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:45,360 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:45,361 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:45,362 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:45,364 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:45,365 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:45,367 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:33:45,368 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:45,369 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:33:45,371 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:45,372 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:33:45,374 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:33:45,376 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:33:45,377 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:33:45,379 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:45,380 - INFO - integrating rxn: rxn15550_c0
2026-01-13 19:33:45,381 - INFO - integrating rxn: rxn15072_c0
2026-01-13 19:33:45,383 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:45,384 - INFO - integrating rxn: rxn41185_c0
2026-01-13 19:33:45,385 - INFO - integrating rxn: rxn13741_c0
2026-01-13 19:33:45,387 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:45,388 - INFO - integrating rxn: rxn08474_c0
2026-01-13 19:33:45,389 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:33:45,390 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd10515_e0', 'EX_cpd00104_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn01636_c0', 'rxn02988_c0', 'rxn00470_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn10481_c0', 'rxn08708_c0', 'rxn00907_c0', 'rxn10213_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn01256_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn01000_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn05119_c0', 'rxn02011_c0', 'rxn05645_c0', 'rxn02402_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn10094_c0', 'rxn05299_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn03150_c0', 'rxn03538_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn00834_c0', 'rxn11702_c0', 'rxn03084_c0', 'rxn03638_c0', 'rxn02897_c0', 'rxn02056_c0', 'rxn00134_c0', 'rxn05223_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn01538_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn28338_c0', 'rxn01736_c0', 'rxn00644_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn17394_c0', 'rxn14070_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn46249_c0', 'rxn41492_c0', 'rxn44493_c0', 'rxn42332_c0', 'rxn20472_c0', 'rxn40674_c0', 'rxn08473_c0', ['EX_cpd00020_e0', '<', 'new'], ['rxn00958_c0', '>', 'new'], ['rxn05469_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn12868_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn00502_c0', '<', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn01257_c0', '>', 'new'], ['rxn00541_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn00430_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn15550_c0', '>', 'new'], ['rxn15072_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn41185_c0', '>', 'new'], ['rxn13741_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn08474_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:33:45,404 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,405 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,406 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,408 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,409 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,410 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd10515_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,411 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,412 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,413 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,415 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,416 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,417 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,418 - INFO - PyruateMinimalAnaerobic/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,419 - INFO - PyruateMinimalAnaerobic/bio1:rxn02988_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,421 - INFO - PyruateMinimalAnaerobic/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,422 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,423 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,424 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,425 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,426 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,428 - INFO - PyruateMinimalAnaerobic/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,429 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,430 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,431 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,432 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,434 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,435 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,436 - INFO - PyruateMinimalAnaerobic/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,437 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,438 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,439 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,441 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,442 - INFO - PyruateMinimalAnaerobic/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,443 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,444 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,445 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,447 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,448 - INFO - PyruateMinimalAnaerobic/bio1:rxn05119_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,449 - INFO - PyruateMinimalAnaerobic/bio1:rxn02011_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,450 - INFO - PyruateMinimalAnaerobic/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,451 - INFO - PyruateMinimalAnaerobic/bio1:rxn02402_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,452 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,454 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,456 - INFO - PyruateMinimalAnaerobic/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,457 - INFO - PyruateMinimalAnaerobic/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,458 - INFO - PyruateMinimalAnaerobic/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,459 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,460 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,462 - INFO - PyruateMinimalAnaerobic/bio1:rxn03538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,463 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,464 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,465 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,467 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,468 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,469 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,470 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,472 - INFO - PyruateMinimalAnaerobic/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,473 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,475 - INFO - PyruateMinimalAnaerobic/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,476 - INFO - PyruateMinimalAnaerobic/bio1:rxn05223_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,477 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,478 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,480 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,481 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,482 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,483 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,485 - INFO - PyruateMinimalAnaerobic/bio1:rxn01538_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,486 - INFO - PyruateMinimalAnaerobic/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,487 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,488 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,490 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,491 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,492 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,493 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,495 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,496 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,497 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,498 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,500 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,501 - INFO - PyruateMinimalAnaerobic/bio1:rxn28338_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,502 - INFO - PyruateMinimalAnaerobic/bio1:rxn01736_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,503 - INFO - PyruateMinimalAnaerobic/bio1:rxn00644_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,505 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,506 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,507 - INFO - PyruateMinimalAnaerobic/bio1:rxn17394_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,508 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,510 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,511 - INFO - PyruateMinimalAnaerobic/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,513 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,514 - INFO - PyruateMinimalAnaerobic/bio1:rxn46249_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,515 - INFO - PyruateMinimalAnaerobic/bio1:rxn41492_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,516 - INFO - PyruateMinimalAnaerobic/bio1:rxn44493_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,517 - INFO - PyruateMinimalAnaerobic/bio1:rxn42332_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,519 - INFO - PyruateMinimalAnaerobic/bio1:rxn20472_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,520 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,521 - INFO - PyruateMinimalAnaerobic/bio1:rxn08473_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,521 - INFO - Objective with gapfill database:86.04689764726741; min objective:0.01
2026-01-13 19:33:45,522 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:33:45,523 - INFO -   Running ATP safety check...

c0

2026-01-13 19:33:45,614 - INFO - Objective with gapfill database:86.04689764726623; min objective:0.01
2026-01-13 19:33:45,685 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn02320_c0': '<', 'rxn02504_c0': '>', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn00336_c0': '<', 'rxn00503_c0': '<', 'rxn12376_c0': '<', 'rxn00265_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21860_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn14178_c0': '>', 'rxn30685_c0': '>', 'rxn15939_c0': '>', 'rxn47493_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:45,689 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:45,691 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:33:45,692 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:45,694 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:45,696 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:45,697 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:33:45,699 - INFO - integrating rxn: rxn00503_c0
2026-01-13 19:33:45,700 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:45,702 - INFO - integrating rxn: rxn00265_c0
2026-01-13 19:33:45,704 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:45,705 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:33:45,707 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:45,709 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:45,711 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:45,712 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:45,714 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:45,716 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:45,717 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:45,719 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:45,721 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:33:45,722 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:33:45,724 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:33:45,725 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:33:45,726 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:33:45,728 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:33:45,729 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:33:45,731 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:33:45,732 - INFO - integrating rxn: rxn14178_c0
2026-01-13 19:33:45,734 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:45,735 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:33:45,737 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:45,738 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn02212_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn04464_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn03910_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn00420_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn00952_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn10667_c0', '>', 'new'], ['rxn01265_c0', '<', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn01602_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05177_c0', '>', 'new'], ['rxn02914_c0', '<', 'new'], ['rxn00686_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn39982_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn03086_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn09177_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn03030_c0', 'rxn01636_c0', 'rxn00470_c0', 'rxn08710_c0', 'rxn00100_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn02212_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn05229_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn04464_c0', 'rxn01256_c0', 'rxn03910_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08618_c0', 'rxn04704_c0', 'rxn01000_c0', 'rxn01972_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn05645_c0', 'rxn04413_c0', 'rxn01539_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn00420_c0', 'rxn03893_c0', 'rxn03150_c0', 'rxn01537_c0', 'rxn03907_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn00952_c0', 'rxn00533_c0', 'rxn10667_c0', 'rxn01265_c0', 'rxn00834_c0', 'rxn11702_c0', 'rxn00346_c0', 'rxn01790_c0', 'rxn03638_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn01602_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn00623_c0', 'rxn02341_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn05177_c0', 'rxn02914_c0', 'rxn00686_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn39982_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn02485_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn02320_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn00336_c0', '<', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn00265_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn14178_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn47493_c0', '>', 'new']]
2026-01-13 19:33:45,753 - INFO - EX_cpd00305_e0< not needed:4.09316774604521
2026-01-13 19:33:45,755 - INFO - EX_cpd00393_e0< not needed:4.09316774604521
2026-01-13 19:33:45,756 - INFO - EX_cpd00119_e0< not needed:4.09316774604521
2026-01-13 19:33:45,757 - INFO - EX_cpd00220_e0< not needed:4.09316774604521
2026-01-13 19:33:45,761 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,762 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,764 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,766 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,768 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,769 - INFO - PyruateMinimalAnaerobic/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,771 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,772 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,774 - INFO - PyruateMinimalAnaerobic/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,776 - INFO - PyruateMinimalAnaerobic/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,777 - INFO - PyruateMinimalAnaerobic/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,779 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,780 - INFO - PyruateMinimalAnaerobic/bio1:rxn00100_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,782 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,784 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,785 - INFO - PyruateMinimalAnaerobic/bio1:rxn02212_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,787 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,788 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,790 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,792 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,792 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,793 - INFO - PyruateMinimalAnaerobic/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,795 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,797 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,799 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,800 - INFO - PyruateMinimalAnaerobic/bio1:rxn04464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,802 - INFO - PyruateMinimalAnaerobic/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,804 - INFO - PyruateMinimalAnaerobic/bio1:rxn03910_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,806 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,807 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,807 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,809 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,811 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,813 - INFO - PyruateMinimalAnaerobic/bio1:rxn04704_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,814 - INFO - PyruateMinimalAnaerobic/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,816 - INFO - cpd00363 not found in model!
2026-01-13 19:33:45,816 - INFO - PyruateMinimalAnaerobic/bio1:rxn01972_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,817 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:45,818 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,820 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,820 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,822 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,823 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,825 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,827 - INFO - rxn05645_c0> not needed:4.09316774604521
2026-01-13 19:33:45,830 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,831 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,839 - INFO - PyruateMinimalAnaerobic/bio1:rxn01539_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,841 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,843 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,846 - INFO - rxn05299_c0> not needed:4.093167746045206
2026-01-13 19:33:45,847 - INFO - rxn00420_c0> not needed:4.0931677460452045
2026-01-13 19:33:45,849 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,850 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,851 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,858 - INFO - PyruateMinimalAnaerobic/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,859 - INFO - PyruateMinimalAnaerobic/bio1:rxn03907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,862 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,861 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,863 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,866 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,867 - INFO - PyruateMinimalAnaerobic/bio1:rxn00952_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,869 - INFO - PyruateMinimalAnaerobic/bio1:rxn00533_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,871 - INFO - PyruateMinimalAnaerobic/bio1:rxn10667_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,872 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,873 - INFO - PyruateMinimalAnaerobic/bio1:rxn01265_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,874 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,876 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,878 - INFO - PyruateMinimalAnaerobic/bio1:rxn00346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,880 - INFO - cpd00159 not found in model!
2026-01-13 19:33:45,880 - INFO - PyruateMinimalAnaerobic/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,881 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:45,882 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,884 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,884 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,886 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,888 - INFO - rxn01602_c0< not needed:4.09316774604521
2026-01-13 19:33:45,891 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,893 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,893 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,895 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,896 - INFO - PyruateMinimalAnaerobic/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,898 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,900 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,901 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,903 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,904 - INFO - rxn05255_c0> not needed:4.0931677460452045
2026-01-13 19:33:45,906 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,908 - INFO - PyruateMinimalAnaerobic/bio1:rxn00623_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,909 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,911 - INFO - PyruateMinimalAnaerobic/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,912 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,913 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,915 - INFO - rxn05177_c0> not needed:4.0931677460452045
2026-01-13 19:33:45,917 - INFO - rxn02914_c0< not needed:4.09316774604521
2026-01-13 19:33:45,919 - INFO - PyruateMinimalAnaerobic/bio1:rxn00686_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:45,921 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,922 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,923 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,924 - INFO - PyruateMinimalAnaerobic/bio1:rxn39982_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,926 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,928 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,930 - INFO - cpd00363 not found in model!
2026-01-13 19:33:45,931 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:45,933 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,935 - INFO - PyruateMinimalAnaerobic/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,938 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:45,940 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:33:45,971 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:45,988 - INFO - cpd00159 not found in model!
2026-01-13 19:33:45,989 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:45,991 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,000 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,010 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,019 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,029 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,038 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,046 - INFO - cpd00418 not found in model!
2026-01-13 19:33:46,047 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:46,050 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,059 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,069 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,077 - INFO - cpd00418 not found in model!
2026-01-13 19:33:46,077 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:46,080 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,090 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,099 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,107 - INFO - cpd00418 not found in model!
2026-01-13 19:33:46,108 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:46,108 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00796_c0': '>', 'rxn03436_c0': '>', 'rxn00957_c0': '>', 'rxn00300_c0': '>', 'rxn00907_c0': '<', 'rxn09310_c0': '>', 'rxn12239_c0': '>', 'rxn00782_c0': '<', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn00157_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn14424_c0': '>', 'rxn12932_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12942_c0': '>', 'rxn11251_c0': '>', 'rxn16114_c0': '>', 'rxn15270_c0': '>', 'rxn30685_c0': '>', 'rxn16341_c0': '>', 'rxn47493_c0': '>', 'rxn14423_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:46,111 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,112 - INFO - integrating rxn: rxn00796_c0
2026-01-13 19:33:46,114 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:46,116 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:33:46,118 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:46,119 - INFO - cpd08021 not found in model!
2026-01-13 19:33:46,119 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:33:46,119 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:46,121 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:46,123 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,123 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:33:46,124 - INFO - integrating rxn: rxn00782_c0
2026-01-13 19:33:46,126 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:46,128 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:46,129 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:46,131 - INFO - cpd00811 not found in model!
2026-01-13 19:33:46,131 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'DM_cpd02701_c0': '>', 'rxn02504_c0': '>', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn12376_c0': '<', 'rxn02312_c0': '>', 'rxn02200_c0': '>', 'rxn09310_c0': '>', 'rxn03841_c0': '>', 'rxn01257_c0': '>', 'rxn02277_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn17731_c0': '>', 'rxn11274_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn30685_c0': '>', 'rxn15940_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn47875_c0': '>', 'rxn13301_c0': '>', 'rxn47493_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:46,131 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:46,131 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:46,133 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:33:46,133 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:46,134 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,135 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:46,135 - INFO - integrating rxn: DM_cpd02701_c0
2026-01-13 19:33:46,136 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:46,137 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:33:46,138 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:46,138 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:46,140 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:46,140 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:46,141 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:46,142 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:46,142 - INFO - cpd08021 not found in model!
2026-01-13 19:33:46,143 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:46,143 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:46,143 - INFO - integrating rxn: rxn02312_c0
2026-01-13 19:33:46,144 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:46,145 - INFO - integrating rxn: rxn02200_c0
2026-01-13 19:33:46,146 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,146 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:46,147 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:46,148 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:46,149 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:46,149 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:46,150 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:46,151 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:33:46,152 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:46,153 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:33:46,154 - INFO - cpd00811 not found in model!
2026-01-13 19:33:46,154 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:46,154 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:33:46,154 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:46,155 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:46,156 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:33:46,157 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:46,157 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,158 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:33:46,159 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:46,160 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:33:46,160 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:46,161 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:46,162 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:46,163 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:46,163 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:46,164 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:33:46,165 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:46,166 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:46,167 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:46,167 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:33:46,167 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,168 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:46,169 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:46,169 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:46,170 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:33:46,171 - INFO - integrating rxn: rxn17731_c0
2026-01-13 19:33:46,171 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn02000_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn02988_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00727_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01675_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn00927_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn02402_c0', '<', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00099_e0', 'EX_cpd10515_e0', 'rxn08709_c0', 'rxn02000_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn09177_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn02988_c0', 'rxn08710_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn01997_c0', 'rxn03918_c0', 'rxn00727_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn02404_c0', 'rxn00392_c0', 'rxn00830_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn01675_c0', 'rxn03536_c0', 'rxn00927_c0', 'rxn09210_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03397_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn05119_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn08711_c0', 'rxn02402_c0', 'rxn00832_c0', 'rxn01539_c0', 'rxn10094_c0', 'rxn03917_c0', 'rxn03150_c0', 'rxn03087_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn11702_c0', 'rxn01790_c0', 'rxn03638_c0', 'rxn02056_c0', 'rxn02003_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn02485_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn10095_c0', 'rxn08233_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn08473_c0', 'rxn43975_c0', 'rxn42732_c0', 'rxn41263_c0', 'rxn20839_c0', ['rxn00796_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00957_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn00907_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn00782_c0', '<', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn00157_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:33:46,173 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:33:46,174 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:33:46,176 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:33:46,177 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,177 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:33:46,179 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:33:46,180 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:33:46,182 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:33:46,183 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:33:46,184 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:33:46,185 - INFO - cpd11640 not found in model!
2026-01-13 19:33:46,186 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:33:46,186 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:46,187 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:33:46,189 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:46,189 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:46,190 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:33:46,191 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:33:46,193 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:33:46,194 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:33:46,196 - INFO - integrating rxn: rxn47875_c0
2026-01-13 19:33:46,197 - INFO - integrating rxn: rxn13301_c0
2026-01-13 19:33:46,197 - INFO - cpd11640 not found in model!
2026-01-13 19:33:46,198 - INFO - EX_cpd00393_e0< not needed:4.652646309076764
2026-01-13 19:33:46,198 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:46,198 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:33:46,200 - INFO - EX_cpd00220_e0< not needed:4.652646309076764

c0

2026-01-13 19:33:46,414 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01

2026-01-13 19:33:46,416 - INFO - PyruateMinimalAnaerobic/bio1:rxn08473_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:46,416 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:33:46,416 - INFO - Objective with gapfill database:114.73871061823203; min objective:0.01
2026-01-13 19:33:46,417 - INFO -   Running ATP safety check...

c0
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:47,391 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,409 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,420 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,430 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,441 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,452 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,460 - INFO - cpd00036 not found in model!
2026-01-13 19:33:47,461 - INFO - Media compound: cpd00036 not found in model.
2026-01-13 19:33:47,464 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,474 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,484 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,493 - INFO - cpd00221 not found in model!
2026-01-13 19:33:47,494 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:33:47,497 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,507 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,518 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,528 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,538 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,549 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,559 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,570 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,579 - INFO - cpd00036 not found in model!
2026-01-13 19:33:47,580 - INFO - Media compound: cpd00036 not found in model.
2026-01-13 19:33:47,583 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,593 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,604 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,612 - INFO - cpd00221 not found in model!
2026-01-13 19:33:47,613 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:33:47,616 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,626 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,636 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,656 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,666 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,676 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,687 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,697 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,707 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,717 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,728 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,737 - INFO - cpd08021 not found in model!
2026-01-13 19:33:47,738 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:47,741 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,749 - INFO - cpd00811 not found in model!
2026-01-13 19:33:47,750 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:47,754 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,762 - INFO - cpd08021 not found in model!
2026-01-13 19:33:47,763 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:47,766 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,774 - INFO - cpd00811 not found in model!
2026-01-13 19:33:47,775 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:47,778 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,788 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,799 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,807 - INFO - cpd11640 not found in model!
2026-01-13 19:33:47,808 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:47,811 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,819 - INFO - cpd11640 not found in model!
2026-01-13 19:33:47,820 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:47,823 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,831 - INFO - cpd11640 not found in model!
2026-01-13 19:33:47,832 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:47,835 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,843 - INFO - cpd11640 not found in model!
2026-01-13 19:33:47,844 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:47,846 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,859 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,870 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,880 - INFO - cpd11640 not found in model!
2026-01-13 19:33:47,881 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:47,884 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,895 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,903 - INFO - cpd11632 not found in model!
2026-01-13 19:33:47,904 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:33:47,907 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,915 - INFO - cpd08701 not found in model!
2026-01-13 19:33:47,916 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:33:47,917 - INFO - cpd01024 not found in model!
2026-01-13 19:33:47,918 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:47,920 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,929 - INFO - cpd01024 not found in model!
2026-01-13 19:33:47,930 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:47,933 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,943 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,951 - INFO - cpd11640 not found in model!
2026-01-13 19:33:47,952 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:47,955 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,963 - INFO - cpd11640 not found in model!
2026-01-13 19:33:47,964 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:47,965 - INFO - cpd00187 not found in model!
2026-01-13 19:33:47,966 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:33:47,968 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,977 - INFO - cpd11640 not found in model!
2026-01-13 19:33:47,978 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:47,978 - INFO - cpd00425 not found in model!
2026-01-13 19:33:47,979 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:33:47,981 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:47,990 - INFO - cpd11640 not found in model!
2026-01-13 19:33:47,991 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:47,991 - INFO - cpd00441 not found in model!
2026-01-13 19:33:47,992 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:33:47,995 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:48,772 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,783 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,790 - INFO - cpd00363 not found in model!
2026-01-13 19:33:48,791 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:48,794 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,803 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,811 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,819 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,827 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,836 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,842 - INFO - cpd00159 not found in model!
2026-01-13 19:33:48,843 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:48,846 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,854 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,862 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,869 - INFO - Objective with gapfill database:114.73871061823203; min objective:0.01
2026-01-13 19:33:48,870 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,879 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,885 - INFO - cpd00363 not found in model!
2026-01-13 19:33:48,886 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:33:48,889 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,897 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,905 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,913 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,921 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,929 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,935 - INFO - cpd00159 not found in model!
2026-01-13 19:33:48,936 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:48,939 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,947 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,955 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,962 - INFO - cpd00130 not found in model!
2026-01-13 19:33:48,962 - INFO - Media compound: cpd00130 not found in model.
2026-01-13 19:33:48,965 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,972 - INFO - cpd00075 not found in model!
2026-01-13 19:33:48,973 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:48,975 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,982 - INFO - cpd00209 not found in model!
2026-01-13 19:33:48,983 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:48,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:48,991 - INFO - cpd00418 not found in model!
2026-01-13 19:33:48,992 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:48,994 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,001 - INFO - cpd00075 not found in model!
2026-01-13 19:33:49,002 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:49,004 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,011 - INFO - cpd00209 not found in model!
2026-01-13 19:33:49,011 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:49,014 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,020 - INFO - cpd00418 not found in model!
2026-01-13 19:33:49,021 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:49,023 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,030 - INFO - cpd00075 not found in model!
2026-01-13 19:33:49,031 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:33:49,033 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,039 - INFO - cpd00209 not found in model!
2026-01-13 19:33:49,040 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:33:49,042 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,049 - INFO - cpd00418 not found in model!
2026-01-13 19:33:49,049 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:33:49,052 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,058 - INFO - cpd08021 not found in model!
2026-01-13 19:33:49,059 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:49,061 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,067 - INFO - cpd00811 not found in model!
2026-01-13 19:33:49,068 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:49,070 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,077 - INFO - cpd08021 not found in model!
2026-01-13 19:33:49,077 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:33:49,080 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,086 - INFO - cpd00811 not found in model!
2026-01-13 19:33:49,087 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:33:49,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,097 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,105 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,112 - INFO - cpd11640 not found in model!
2026-01-13 19:33:49,113 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:49,115 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,121 - INFO - cpd11640 not found in model!
2026-01-13 19:33:49,122 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:49,125 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,131 - INFO - cpd11640 not found in model!
2026-01-13 19:33:49,132 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:49,134 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,141 - INFO - cpd00159 not found in model!
2026-01-13 19:33:49,141 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:49,142 - INFO - cpd11640 not found in model!
2026-01-13 19:33:49,143 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:49,146 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,154 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,161 - INFO - cpd00159 not found in model!
2026-01-13 19:33:49,161 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:33:49,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,170 - INFO - cpd11640 not found in model!
2026-01-13 19:33:49,171 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:49,173 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,181 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,188 - INFO - cpd11632 not found in model!
2026-01-13 19:33:49,188 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:33:49,191 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,198 - INFO - cpd08701 not found in model!
2026-01-13 19:33:49,199 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:33:49,199 - INFO - cpd01024 not found in model!
2026-01-13 19:33:49,200 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:49,202 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,210 - INFO - cpd01024 not found in model!
2026-01-13 19:33:49,210 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:33:49,213 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,221 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,228 - INFO - cpd11640 not found in model!
2026-01-13 19:33:49,229 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:49,231 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,238 - INFO - cpd11640 not found in model!
2026-01-13 19:33:49,238 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:49,239 - INFO - cpd00187 not found in model!
2026-01-13 19:33:49,240 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:33:49,242 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,248 - INFO - cpd11640 not found in model!
2026-01-13 19:33:49,249 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:49,250 - INFO - cpd00425 not found in model!
2026-01-13 19:33:49,251 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:33:49,253 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,260 - INFO - cpd11640 not found in model!
2026-01-13 19:33:49,260 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:33:49,261 - INFO - cpd00441 not found in model!
2026-01-13 19:33:49,262 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:33:49,264 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:33:49,479 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'DM_cpd02701_c0': '>', 'rxn02320_c0': '<', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn12376_c0': '<', 'rxn01539_c0': '<', 'rxn02312_c0': '>', 'rxn09310_c0': '>', 'rxn03841_c0': '>', 'rxn01257_c0': '>', 'rxn02277_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn16218_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn16217_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn11251_c0': '>', 'rxn16114_c0': '>', 'rxn30685_c0': '>', 'rxn08921_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>', 'rxn14428_c0': '>', 'rxn10121_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:49,482 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:49,485 - INFO - integrating rxn: DM_cpd02701_c0
2026-01-13 19:33:49,487 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:33:49,488 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:49,490 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:49,492 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:49,493 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:49,495 - INFO - integrating rxn: rxn02312_c0
2026-01-13 19:33:49,497 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:49,498 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:49,500 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:49,502 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:49,503 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:49,505 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:49,506 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:49,508 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:49,510 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:49,512 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:33:49,513 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:49,515 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:49,516 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:49,518 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:49,519 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:49,520 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:49,522 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:33:49,523 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:49,525 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:49,526 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:49,528 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:33:49,529 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:49,531 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:49,532 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:49,534 - INFO - integrating rxn: rxn41399_c0
2026-01-13 19:33:49,535 - INFO - integrating rxn: rxn41401_c0
2026-01-13 19:33:49,536 - INFO - integrating rxn: rxn15776_c0
2026-01-13 19:33:49,538 - INFO - integrating rxn: rxn14428_c0
2026-01-13 19:33:49,539 - INFO - integrating rxn: rxn10121_c0

c0
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:33:52,850 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:53,227 - INFO -   Saved gapfilled model: gapfilled_models2/Dethiobacter.9_gf.xml
2026-01-13 19:33:53,229 - INFO -   Total reactions added: 400
2026-01-13 19:33:53,366 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:33:53,698 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:54,847 - INFO - Objective with gapfill database:114.73871061823222; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:33:57,203 - INFO - Objective with gapfill database:114.73871061823222; min objective:0.01
2026-01-13 19:33:57,747 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn00361_c0': '>', 'rxn03436_c0': '>', 'rxn02160_c0': '>', 'rxn00300_c0': '>', 'rxn01256_c0': '>', 'rxn01000_c0': '>', 'rxn12376_c0': '<', 'rxn01539_c0': '<', 'rxn00505_c0': '>', 'rxn09310_c0': '>', 'rxn03841_c0': '>', 'rxn01257_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn00623_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn21860_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn46124_c0': '>', 'rxn04551_c0': '>', 'rxn16114_c0': '>', 'rxn16671_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:33:57,751 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:33:57,753 - INFO - integrating rxn: rxn00361_c0
2026-01-13 19:33:57,755 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:33:57,757 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:33:57,759 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:33:57,760 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:33:57,762 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:33:57,763 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:33:57,765 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:33:57,767 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:33:57,769 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:33:57,770 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:33:57,772 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:33:57,774 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:33:57,776 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:33:57,777 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:33:57,779 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:33:57,781 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:33:57,782 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:33:57,784 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:33:57,786 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:33:57,788 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:33:57,789 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:33:57,791 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:33:57,792 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:33:57,794 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:33:57,796 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:33:57,798 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:33:57,799 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:33:57,801 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:33:57,802 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:33:57,805 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:33:57,806 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:33:57,808 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:33:57,809 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:33:57,811 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:33:57,813 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:33:57,815 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:33:57,817 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:33:57,819 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:33:57,820 - INFO - integrating rxn: rxn16671_c0
2026-01-13 19:33:57,822 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:33:57,824 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:33:57,826 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:33:57,827 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:33:57,829 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:33:57,831 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn04996_c0', '<', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00213_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09429_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn03086_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn04996_c0', 'rxn01117_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn05229_c0', 'rxn02404_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn01505_c0', 'rxn00213_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03159_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09429_c0', 'rxn09106_c0', 'rxn08711_c0', 'rxn04413_c0', 'rxn00137_c0', 'rxn06023_c0', 'rxn00832_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn03150_c0', 'rxn02303_c0', 'rxn03907_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn06865_c0', 'rxn04113_c0', 'rxn00704_c0', 'rxn11702_c0', 'rxn03084_c0', 'rxn03439_c0', 'rxn00346_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn00138_c0', 'rxn03130_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn15949_c0', 'rxn14424_c0', 'rxn11274_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn20508_c0', 'rxn20627_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn14423_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn00361_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn02160_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn01257_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn16671_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn08473_c0', '>', 'new']]
2026-01-13 19:33:57,855 - INFO - EX_cpd00393_e0< not needed:7.695259964906937
2026-01-13 19:33:57,856 - INFO - EX_cpd00119_e0< not needed:7.695259964906937
2026-01-13 19:33:57,860 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,862 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,867 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,871 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,874 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,876 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,878 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,880 - INFO - PyruateMinimalAnaerobic/bio1:rxn04996_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,882 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,884 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,886 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,888 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,890 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,892 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,894 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,896 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,897 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,899 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,901 - INFO - PyruateMinimalAnaerobic/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,903 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,904 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,906 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,908 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,909 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,911 - INFO - PyruateMinimalAnaerobic/bio1:rxn00213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,913 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,914 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,916 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,918 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,919 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,921 - INFO - PyruateMinimalAnaerobic/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,923 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,924 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,926 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,928 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,929 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,931 - INFO - PyruateMinimalAnaerobic/bio1:rxn09429_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,933 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,934 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,936 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,938 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:1.0540291852186514e-13 with min obj:0.01
2026-01-13 19:33:57,939 - INFO - PyruateMinimalAnaerobic/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,941 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,943 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,949 - INFO - rxn05299_c0> not needed:7.695259964906914
2026-01-13 19:33:57,952 - INFO - PyruateMinimalAnaerobic/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,954 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,956 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,958 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,960 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,962 - INFO - PyruateMinimalAnaerobic/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,964 - INFO - PyruateMinimalAnaerobic/bio1:rxn03907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,966 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,968 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,970 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,972 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,974 - INFO - PyruateMinimalAnaerobic/bio1:rxn04113_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,976 - INFO - PyruateMinimalAnaerobic/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,978 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,981 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,983 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,985 - INFO - PyruateMinimalAnaerobic/bio1:rxn00346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,987 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:57,988 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,990 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,992 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,993 - INFO - PyruateMinimalAnaerobic/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,995 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,997 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:57,998 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,004 - INFO - rxn05255_c0> not needed:7.695259964906949
2026-01-13 19:33:58,007 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:33:58,009 - INFO - PyruateMinimalAnaerobic/bio1:rxn00138_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,010 - INFO - PyruateMinimalAnaerobic/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,012 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,014 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,016 - INFO - PyruateMinimalAnaerobic/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,018 - INFO - PyruateMinimalAnaerobic/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,019 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,021 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,023 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,025 - INFO - PyruateMinimalAnaerobic/bio1:rxn14424_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,027 - INFO - PyruateMinimalAnaerobic/bio1:rxn11274_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,029 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,031 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,033 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,035 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,037 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,039 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,040 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,042 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,044 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,046 - INFO - PyruateMinimalAnaerobic/bio1:rxn20508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,048 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:33:58,051 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:1.8093505659174265e-12 with min obj:0.01

c0

2026-01-13 19:33:58,235 - INFO - Objective with gapfill database:114.73871061823213; min objective:0.01
2026-01-13 19:33:59,517 - INFO - Objective with gapfill database:86.04689764726695; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:00,510 - INFO - Objective with gapfill database:86.0468976472673; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:00,623 - INFO - Objective with gapfill database:114.73871061823213; min objective:0.01
2026-01-13 19:34:00,718 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,728 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,735 - INFO - cpd00363 not found in model!
2026-01-13 19:34:00,736 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:00,739 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,748 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,756 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,765 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,772 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,780 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,787 - INFO - cpd00159 not found in model!
2026-01-13 19:34:00,788 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:00,791 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,797 - INFO - cpd00221 not found in model!
2026-01-13 19:34:00,798 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:00,800 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,808 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,816 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,824 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,830 - INFO - cpd00363 not found in model!
2026-01-13 19:34:00,830 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:00,833 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,841 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,848 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,856 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,864 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,871 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,878 - INFO - cpd00159 not found in model!
2026-01-13 19:34:00,878 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:00,881 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,887 - INFO - cpd00221 not found in model!
2026-01-13 19:34:00,888 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:00,890 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,898 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,904 - INFO - cpd00130 not found in model!
2026-01-13 19:34:00,905 - INFO - Media compound: cpd00130 not found in model.
2026-01-13 19:34:00,907 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,915 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,923 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,929 - INFO - cpd00418 not found in model!
2026-01-13 19:34:00,929 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:00,931 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,939 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,947 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:00,953 - INFO - cpd00418 not found in model!
2026-01-13 19:34:00,954 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:00,956 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,963 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,971 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,977 - INFO - cpd00418 not found in model!
2026-01-13 19:34:00,978 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:00,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,987 - INFO - cpd08021 not found in model!
2026-01-13 19:34:00,987 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:00,990 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:00,996 - INFO - cpd00811 not found in model!
2026-01-13 19:34:00,996 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:00,999 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,005 - INFO - cpd08021 not found in model!
2026-01-13 19:34:01,006 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:01,008 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,014 - INFO - cpd00811 not found in model!
2026-01-13 19:34:01,015 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:01,017 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,025 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,033 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,039 - INFO - cpd11640 not found in model!
2026-01-13 19:34:01,040 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:01,042 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,048 - INFO - cpd11640 not found in model!
2026-01-13 19:34:01,049 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:01,051 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,057 - INFO - cpd11640 not found in model!
2026-01-13 19:34:01,058 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:01,060 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,067 - INFO - cpd00159 not found in model!
2026-01-13 19:34:01,067 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:01,068 - INFO - cpd11640 not found in model!
2026-01-13 19:34:01,068 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:01,071 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,078 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,084 - INFO - cpd00159 not found in model!
2026-01-13 19:34:01,085 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:01,088 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,094 - INFO - cpd11640 not found in model!
2026-01-13 19:34:01,095 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:01,097 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,105 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,111 - INFO - cpd11632 not found in model!
2026-01-13 19:34:01,112 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:01,114 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,115 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,121 - INFO - cpd08701 not found in model!
2026-01-13 19:34:01,122 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:01,122 - INFO - cpd01024 not found in model!
2026-01-13 19:34:01,123 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:01,125 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,131 - INFO - cpd01024 not found in model!
2026-01-13 19:34:01,131 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,132 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:01,135 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,142 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,143 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,149 - INFO - cpd11640 not found in model!
2026-01-13 19:34:01,149 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:01,152 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,152 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn02320_c0': '<', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn02835_c0': '>', 'rxn12376_c0': '<', 'rxn01539_c0': '<', 'rxn03108_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn04954_c0': '<', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn21860_c0': '>', 'rxn12932_c0': '>', 'rxn12939_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12942_c0': '>', 'rxn46124_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn47875_c0': '>', 'rxn47493_c0': '>', 'rxn15754_c0': '>', 'rxn10120_c0': '>', 'rxn10121_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:01,154 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,156 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:01,158 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:34:01,158 - INFO - cpd11640 not found in model!
2026-01-13 19:34:01,160 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:01,159 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:01,160 - INFO - cpd00187 not found in model!
2026-01-13 19:34:01,161 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:01,162 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:34:01,163 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:34:01,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,165 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:01,167 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:34:01,168 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:34:01,170 - INFO - cpd11640 not found in model!
2026-01-13 19:34:01,170 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:01,171 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:01,172 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:34:01,172 - INFO - cpd00425 not found in model!
2026-01-13 19:34:01,173 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:01,174 - INFO - integrating rxn: rxn04954_c0
2026-01-13 19:34:01,175 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,175 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:01,175 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,177 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:01,179 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:01,181 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:01,182 - INFO - cpd11640 not found in model!
2026-01-13 19:34:01,182 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:01,183 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:01,184 - INFO - cpd00441 not found in model!
2026-01-13 19:34:01,184 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:01,185 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:01,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,186 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:34:01,187 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,187 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:01,189 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:01,190 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:34:01,192 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:34:01,194 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:34:01,195 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:34:01,196 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,197 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:34:01,199 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:01,200 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:34:01,202 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:34:01,203 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:34:01,205 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:34:01,206 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,206 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:34:01,208 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:01,210 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:34:01,211 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:34:01,213 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:34:01,214 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:34:01,216 - INFO - integrating rxn: rxn47875_c0
2026-01-13 19:34:01,216 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,217 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:01,219 - INFO - integrating rxn: rxn15754_c0
2026-01-13 19:34:01,221 - INFO - integrating rxn: rxn10120_c0
2026-01-13 19:34:01,222 - INFO - integrating rxn: rxn10121_c0
2026-01-13 19:34:01,223 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn18575_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00099_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn01117_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn02404_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03159_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn08711_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn03150_c0', 'rxn02303_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn06865_c0', 'rxn00599_c0', 'rxn11702_c0', 'rxn03439_c0', 'rxn03638_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn03130_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn19346_c0', 'rxn40142_c0', 'rxn25042_c0', 'rxn19766_c0', 'rxn19764_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn18575_c0', 'rxn08233_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn02320_c0', '<', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn04954_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn47875_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn15754_c0', '>', 'new'], ['rxn10120_c0', '>', 'new'], ['rxn10121_c0', '>', 'new']]
2026-01-13 19:34:01,227 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,237 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,247 - INFO - EX_cpd00393_e0< not needed:1.2724259542940786
2026-01-13 19:34:01,248 - INFO - EX_cpd00119_e0< not needed:1.2724259542940786
2026-01-13 19:34:01,248 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,250 - INFO - EX_cpd00220_e0< not needed:1.2724259542940786
2026-01-13 19:34:01,252 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:01,254 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:01,255 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,257 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,259 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,259 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,261 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,262 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:01,264 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,266 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,267 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:01,269 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,269 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,271 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,273 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,275 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:01,276 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:34:01,443 - INFO - cpd00209 not found in model!
2026-01-13 19:34:01,445 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:01,448 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,457 - INFO - cpd00418 not found in model!
2026-01-13 19:34:01,458 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:01,460 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,469 - INFO - cpd08021 not found in model!
2026-01-13 19:34:01,470 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:01,473 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,482 - INFO - cpd00811 not found in model!
2026-01-13 19:34:01,482 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:01,485 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,493 - INFO - cpd08021 not found in model!
2026-01-13 19:34:01,494 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:01,497 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,505 - INFO - cpd00811 not found in model!
2026-01-13 19:34:01,506 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:01,507 - INFO - Objective with gapfill database:107.98937469951274; min objective:0.01
2026-01-13 19:34:01,509 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,519 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,530 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,541 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,551 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,562 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,572 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,583 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,593 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,604 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,614 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,623 - INFO - cpd11632 not found in model!
2026-01-13 19:34:01,624 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:01,626 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,635 - INFO - cpd08701 not found in model!
2026-01-13 19:34:01,636 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:01,637 - INFO - cpd01024 not found in model!
2026-01-13 19:34:01,638 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:01,641 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,649 - INFO - cpd01024 not found in model!
2026-01-13 19:34:01,650 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:01,653 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,664 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,674 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,682 - INFO - cpd00187 not found in model!
2026-01-13 19:34:01,683 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:01,686 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,695 - INFO - cpd00425 not found in model!
2026-01-13 19:34:01,696 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:01,699 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:01,708 - INFO - cpd00441 not found in model!
2026-01-13 19:34:01,709 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:01,711 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:01,904 - INFO - Objective with gapfill database:86.04689764726695; min objective:0.01
2026-01-13 19:34:02,433 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00013_e0': '<', 'EX_cpd15378_e0': '>', 'rxn02504_c0': '>', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn02835_c0': '>', 'rxn00010_c0': '>', 'rxn10868_c0': '>', 'rxn12376_c0': '<', 'rxn02508_c0': '>', 'rxn00048_c0': '>', 'rxn00726_c0': '>', 'rxn00791_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn03841_c0': '>', 'rxn01257_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn02507_c0': '>', 'rxn01964_c0': '>', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn17731_c0': '>', 'rxn12939_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn46124_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn10095_c0': '>', 'rxn15939_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn08989_c0': '>', 'rxn47493_c0': '>', 'rxn08474_c0': '>', 'rxn08473_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:02,436 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:34:02,438 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:02,440 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:34:02,442 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:02,444 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:34:02,445 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:34:02,447 - INFO - integrating rxn: rxn00010_c0
2026-01-13 19:34:02,448 - INFO - integrating rxn: rxn10868_c0
2026-01-13 19:34:02,450 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:02,451 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:34:02,453 - INFO - integrating rxn: rxn00048_c0
2026-01-13 19:34:02,454 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:34:02,456 - INFO - integrating rxn: rxn00791_c0
2026-01-13 19:34:02,457 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:02,459 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:34:02,460 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:34:02,462 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:34:02,464 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:34:02,466 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:34:02,467 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:02,469 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:34:02,470 - INFO - integrating rxn: rxn01964_c0
2026-01-13 19:34:02,471 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:02,473 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:34:02,475 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:02,476 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:02,478 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:02,479 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:02,481 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:34:02,482 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:34:02,484 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:02,485 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:02,486 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:34:02,488 - INFO - integrating rxn: rxn17731_c0
2026-01-13 19:34:02,490 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:34:02,491 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:34:02,493 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:34:02,494 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:34:02,495 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:34:02,497 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:34:02,498 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:34:02,500 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:34:02,501 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:34:02,503 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:34:02,504 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:34:02,506 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:34:02,507 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:34:02,508 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:02,510 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:34:02,511 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:34:02,513 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:34:02,514 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:34:02,516 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:34:02,517 - INFO - integrating rxn: rxn08989_c0
2026-01-13 19:34:02,519 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:02,520 - INFO - integrating rxn: rxn08474_c0
2026-01-13 19:34:02,522 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:34:02,522 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00065_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn01739_c0', '>', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn04704_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn05663_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00065_e0', 'rxn08709_c0', 'rxn03086_c0', 'rxn00800_c0', 'rxn09177_c0', 'rxn10336_c0', 'rxn03030_c0', 'rxn08710_c0', 'rxn01739_c0', 'rxn00060_c0', 'rxn08583_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn05229_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn00029_c0', 'rxn02774_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn04704_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn08528_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn08711_c0', 'rxn04413_c0', 'rxn01539_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn09657_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn03150_c0', 'rxn01537_c0', 'rxn05663_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn00599_c0', 'rxn03084_c0', 'rxn00346_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn16218_c0', 'rxn16217_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn02485_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn19346_c0', 'rxn40142_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn11285_c0', 'rxn20508_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd00013_e0', '<', 'new'], ['EX_cpd15378_e0', '>', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn00010_c0', '>', 'new'], ['rxn10868_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn00048_c0', '>', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn00791_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn01257_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn02507_c0', '>', 'new'], ['rxn01964_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn17731_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn08989_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn08474_c0', '>', 'new'], ['rxn08473_c0', '>', 'new']]
2026-01-13 19:34:02,550 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,551 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,553 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,554 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00065_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,556 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,557 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,558 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,560 - INFO - PyruateMinimalAnaerobic/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,561 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,562 - INFO - PyruateMinimalAnaerobic/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,564 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,565 - INFO - PyruateMinimalAnaerobic/bio1:rxn01739_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,566 - INFO - PyruateMinimalAnaerobic/bio1:rxn00060_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,568 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,569 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,570 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,572 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,573 - INFO - PyruateMinimalAnaerobic/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,574 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,576 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,577 - INFO - PyruateMinimalAnaerobic/bio1:rxn00029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,578 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,580 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,581 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,582 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,584 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,585 - INFO - PyruateMinimalAnaerobic/bio1:rxn04704_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,587 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,588 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,589 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,591 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,592 - INFO - PyruateMinimalAnaerobic/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,593 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,595 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,596 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,598 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,599 - INFO - PyruateMinimalAnaerobic/bio1:rxn01539_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,600 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,602 - INFO - PyruateMinimalAnaerobic/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,603 - INFO - PyruateMinimalAnaerobic/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,604 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,606 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,607 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,608 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,610 - INFO - PyruateMinimalAnaerobic/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,611 - INFO - PyruateMinimalAnaerobic/bio1:rxn05663_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,612 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,614 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,615 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,616 - INFO - PyruateMinimalAnaerobic/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,618 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,619 - INFO - PyruateMinimalAnaerobic/bio1:rxn00346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,620 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:02,622 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,623 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,624 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,626 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,628 - INFO - PyruateMinimalAnaerobic/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,629 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,631 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,632 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,634 - INFO - PyruateMinimalAnaerobic/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,635 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,637 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,638 - INFO - PyruateMinimalAnaerobic/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,639 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,641 - INFO - PyruateMinimalAnaerobic/bio1:rxn16218_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,642 - INFO - PyruateMinimalAnaerobic/bio1:rxn16217_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,643 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,645 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,646 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,647 - INFO - PyruateMinimalAnaerobic/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,649 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,650 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,651 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,653 - INFO - PyruateMinimalAnaerobic/bio1:rxn19346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,654 - INFO - PyruateMinimalAnaerobic/bio1:rxn40142_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,655 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,657 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,658 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,659 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,661 - INFO - PyruateMinimalAnaerobic/bio1:rxn11285_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,662 - INFO - PyruateMinimalAnaerobic/bio1:rxn20508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,663 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,665 - INFO - PyruateMinimalAnaerobic/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,666 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,667 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,669 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:02,670 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:02,670 - INFO -   Running ATP safety check...

c0

2026-01-13 19:34:02,921 - INFO - Objective with gapfill database:86.0468976472673; min objective:0.01
2026-01-13 19:34:03,531 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn02320_c0': '<', 'rxn02504_c0': '>', 'rxn03436_c0': '>', 'rxn00957_c0': '>', 'rxn00300_c0': '>', 'rxn09310_c0': '>', 'rxn12239_c0': '>', 'rxn00782_c0': '<', 'rxn00551_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12942_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn28338_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn15750_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn15940_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn47875_c0': '>', 'rxn47493_c0': '>', 'rxn09390_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:03,535 - INFO - integrating rxn: rxn02320_c0
2026-01-13 19:34:03,537 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:34:03,539 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:03,541 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:34:03,543 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:34:03,545 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:03,547 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:34:03,549 - INFO - integrating rxn: rxn00782_c0
2026-01-13 19:34:03,550 - INFO - integrating rxn: rxn00551_c0
2026-01-13 19:34:03,552 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:03,553 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:03,555 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:34:03,556 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:03,558 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:03,560 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:03,561 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:03,563 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:34:03,565 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:03,566 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:03,568 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:34:03,570 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:34:03,571 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:34:03,573 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:34:03,575 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:34:03,576 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:34:03,578 - INFO - integrating rxn: rxn28338_c0
2026-01-13 19:34:03,580 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:34:03,581 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:34:03,583 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:34:03,584 - INFO - integrating rxn: rxn15750_c0
2026-01-13 19:34:03,586 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:34:03,587 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:34:03,589 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:03,590 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:34:03,591 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:34:03,593 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:34:03,595 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:34:03,596 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:34:03,598 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:34:03,600 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:34:03,601 - INFO - integrating rxn: rxn47875_c0
2026-01-13 19:34:03,603 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:03,604 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:34:03,605 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd10515_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn04784_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00393_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00063_e0', 'EX_cpd10515_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn09177_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn08710_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00907_c0', 'rxn10213_c0', 'rxn02404_c0', 'rxn00392_c0', 'rxn00830_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn01501_c0', 'rxn01505_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03397_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn08711_c0', 'rxn00832_c0', 'rxn10094_c0', 'rxn09657_c0', 'rxn03917_c0', 'rxn03150_c0', 'rxn04784_c0', 'rxn01537_c0', 'rxn03087_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn00704_c0', 'rxn11702_c0', 'rxn01790_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn20627_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn08473_c0', 'rxn43975_c0', 'rxn42732_c0', 'rxn41263_c0', 'rxn20839_c0', ['rxn02320_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00957_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn00782_c0', '<', 'new'], ['rxn00551_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn15750_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn47875_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn09390_c0', '>', 'new']]
2026-01-13 19:34:03,627 - INFO - EX_cpd00305_e0< not needed:1.2742525246665821
2026-01-13 19:34:03,629 - INFO - EX_cpd00393_e0< not needed:1.2742525246665821
2026-01-13 19:34:03,631 - INFO - EX_cpd00220_e0< not needed:1.2742525246665821
2026-01-13 19:34:03,635 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,637 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,639 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd10515_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,641 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,643 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,645 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,647 - INFO - PyruateMinimalAnaerobic/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,649 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,650 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,652 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,652 - INFO - Objective with gapfill database:114.73871061823198; min objective:0.01
2026-01-13 19:34:03,654 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,656 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,657 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,659 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,661 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,663 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,664 - INFO - PyruateMinimalAnaerobic/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,666 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,668 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,670 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,672 - INFO - PyruateMinimalAnaerobic/bio1:rxn00830_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,673 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,675 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,677 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,679 - INFO - PyruateMinimalAnaerobic/bio1:rxn01501_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,680 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,682 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,684 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,686 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,688 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,689 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,691 - INFO - PyruateMinimalAnaerobic/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,693 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,695 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,696 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,699 - INFO - rxn00966_c0< not needed:1.2742525246665801
2026-01-13 19:34:03,703 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,705 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,708 - INFO - rxn05645_c0> not needed:1.2742525246665972
2026-01-13 19:34:03,712 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,714 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,716 - INFO - PyruateMinimalAnaerobic/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,719 - INFO - rxn09657_c0> not needed:1.2742525246665686
2026-01-13 19:34:03,722 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,724 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,726 - INFO - PyruateMinimalAnaerobic/bio1:rxn04784_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,729 - INFO - rxn01537_c0> not needed:1.274252524666567
2026-01-13 19:34:03,733 - INFO - PyruateMinimalAnaerobic/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,735 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,737 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,738 - INFO - PyruateMinimalAnaerobic/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,740 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,742 - INFO - PyruateMinimalAnaerobic/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,744 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,746 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,747 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,749 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,751 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,753 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,754 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,757 - INFO - rxn05255_c0> not needed:1.2742525246665914
2026-01-13 19:34:03,761 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:03,763 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,765 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,767 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,769 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,771 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,773 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,775 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,776 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,778 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,780 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,782 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,784 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,786 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,787 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,801 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,808 - INFO - rxn15939_c0> not needed:1.274252524666582
2026-01-13 19:34:03,812 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,814 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,816 - INFO - PyruateMinimalAnaerobic/bio1:rxn08473_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,818 - INFO - PyruateMinimalAnaerobic/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,820 - INFO - PyruateMinimalAnaerobic/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,821 - INFO - PyruateMinimalAnaerobic/bio1:rxn41263_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,823 - INFO - PyruateMinimalAnaerobic/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:03,825 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:03,825 - INFO -   Running ATP safety check...

c0

2026-01-13 19:34:03,854 - INFO - Objective with gapfill database:107.98937469951274; min objective:0.01
2026-01-13 19:34:03,933 - INFO - Objective with gapfill database:86.04689764726727; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:04,199 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00423_c0': '>', 'rxn00958_c0': '>', 'rxn03436_c0': '>', 'rxn01111_c0': '>', 'rxn03175_c0': '>', 'rxn12868_c0': '>', 'rxn02508_c0': '>', 'rxn00726_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn00502_c0': '<', 'rxn00952_c0': '>', 'rxn12239_c0': '>', 'rxn00309_c0': '<', 'rxn00430_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn00157_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn25743_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn30685_c0': '>', 'rxn15940_c0': '>', 'rxn37059_c0': '>', 'rxn47493_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:04,202 - INFO - integrating rxn: rxn00423_c0
2026-01-13 19:34:04,205 - INFO - integrating rxn: rxn00958_c0
2026-01-13 19:34:04,206 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:04,208 - INFO - integrating rxn: rxn01111_c0
2026-01-13 19:34:04,210 - INFO - integrating rxn: rxn03175_c0
2026-01-13 19:34:04,212 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:34:04,213 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:34:04,215 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:34:04,217 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:04,219 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:34:04,221 - INFO - integrating rxn: rxn00502_c0
2026-01-13 19:34:04,222 - INFO - integrating rxn: rxn00952_c0
2026-01-13 19:34:04,224 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:34:04,225 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:34:04,227 - INFO - integrating rxn: rxn00430_c0
2026-01-13 19:34:04,228 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:04,230 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:04,232 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:34:04,233 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:34:04,235 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:04,237 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:04,239 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:04,240 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:34:04,242 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:04,243 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:04,245 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:04,247 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:34:04,248 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:34:04,250 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:34:04,251 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:34:04,253 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:34:04,255 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:34:04,256 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:04,258 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:34:04,260 - INFO - integrating rxn: rxn37059_c0
2026-01-13 19:34:04,262 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:04,263 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:34:04,265 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:34:04,267 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:34:04,268 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:34:04,270 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:34:04,271 - INFO - Full solution: [['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn02011_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01538_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00030_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00063_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn01117_c0', 'rxn00470_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn09202_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00907_c0', 'rxn10213_c0', 'rxn02404_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn01505_c0', 'rxn03919_c0', 'rxn09210_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03159_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn02011_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn06023_c0', 'rxn00832_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn01213_c0', 'rxn05618_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn06865_c0', 'rxn00599_c0', 'rxn03439_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn04308_c0', 'rxn01538_c0', 'rxn05255_c0', 'rxn03130_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn19346_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', ['rxn00423_c0', '>', 'new'], ['rxn00958_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn01111_c0', '>', 'new'], ['rxn03175_c0', '>', 'new'], ['rxn12868_c0', '>', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn00502_c0', '<', 'new'], ['rxn00952_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn00430_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn00157_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn37059_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:34:04,304 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,308 - INFO - EX_cpd00393_e0< not needed:2.435611573955761
2026-01-13 19:34:04,310 - INFO - EX_cpd00119_e0< not needed:2.435611573955756
2026-01-13 19:34:04,312 - INFO - EX_cpd00220_e0< not needed:2.435611573955756
2026-01-13 19:34:04,314 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,316 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,318 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,320 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,322 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,324 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,326 - INFO - PyruateMinimalAnaerobic/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,328 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,329 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,331 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,333 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,335 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,336 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,338 - INFO - PyruateMinimalAnaerobic/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,340 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,342 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,343 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,345 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,347 - INFO - PyruateMinimalAnaerobic/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,349 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,351 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,353 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,355 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,356 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,358 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,360 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,362 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,363 - INFO - PyruateMinimalAnaerobic/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,365 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,367 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,369 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,371 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,372 - INFO - PyruateMinimalAnaerobic/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,374 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,376 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,378 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,382 - INFO - rxn00966_c0< not needed:2.4356115739557516
2026-01-13 19:34:04,385 - INFO - PyruateMinimalAnaerobic/bio1:rxn02011_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,386 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,388 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,392 - INFO - rxn05645_c0> not needed:2.4356115739557516
2026-01-13 19:34:04,395 - INFO - PyruateMinimalAnaerobic/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,397 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,399 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,403 - INFO - rxn05299_c0> not needed:2.435611573955768
2026-01-13 19:34:04,406 - INFO - PyruateMinimalAnaerobic/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,408 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,410 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,411 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,413 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,415 - INFO - PyruateMinimalAnaerobic/bio1:rxn05618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,417 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:-1.5064015277446847e-13 with min obj:0.01
2026-01-13 19:34:04,419 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,421 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,422 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,424 - INFO - PyruateMinimalAnaerobic/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,426 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,428 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,429 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,431 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,433 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,435 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,437 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00958_c0': '>', 'rxn03436_c0': '>', 'rxn01111_c0': '>', 'rxn00830_c0': '>', 'rxn01256_c0': '>', 'rxn01000_c0': '>', 'rxn12868_c0': '>', 'rxn01539_c0': '<', 'rxn01537_c0': '>', 'rxn09310_c0': '>', 'rxn12239_c0': '>', 'rxn03075_c0': '>', 'rxn00309_c0': '<', 'rxn00430_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn21860_c0': '>', 'rxn25743_c0': '>', 'rxn02485_c0': '>', 'rxn28338_c0': '>', 'rxn15091_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn30685_c0': '>', 'rxn10095_c0': '>', 'rxn29120_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:04,439 - INFO - rxn01538_c0> not needed:2.43561157395578
2026-01-13 19:34:04,440 - INFO - integrating rxn: rxn00958_c0
2026-01-13 19:34:04,440 - INFO - rxn05255_c0> not needed:2.4356115739557507
2026-01-13 19:34:04,442 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:04,443 - INFO - PyruateMinimalAnaerobic/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,444 - INFO - integrating rxn: rxn01111_c0
2026-01-13 19:34:04,445 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,445 - INFO - integrating rxn: rxn00830_c0
2026-01-13 19:34:04,447 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:34:04,447 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,449 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:34:04,449 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,451 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:34:04,451 - INFO - PyruateMinimalAnaerobic/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,452 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:34:04,453 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,454 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:34:04,455 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,456 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:04,457 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,458 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:34:04,459 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,460 - INFO - integrating rxn: rxn03075_c0
2026-01-13 19:34:04,461 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,461 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:34:04,463 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,463 - INFO - integrating rxn: rxn00430_c0
2026-01-13 19:34:04,465 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,465 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:04,466 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,467 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:04,468 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,468 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:34:04,470 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:04,472 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:04,472 - INFO - rxn19346_c0> not needed:2.4356115739557507
2026-01-13 19:34:04,473 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:04,475 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:34:04,475 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,477 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:04,478 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,478 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:34:04,480 - INFO - integrating rxn: rxn28338_c0
2026-01-13 19:34:04,481 - INFO - rxn14070_c0> not needed:2.435611573955748
2026-01-13 19:34:04,481 - INFO - integrating rxn: rxn15091_c0

c0

2026-01-13 19:34:04,529 - INFO - EX_cpd00393_e0< not needed:2.9166491535687165
2026-01-13 19:34:04,531 - INFO - EX_cpd00220_e0< not needed:2.9166491535687165
2026-01-13 19:34:04,533 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,535 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,537 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,539 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,541 - INFO - PyruateMinimalAnaerobic/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,542 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,544 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,546 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,548 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,549 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,551 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,554 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,555 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,557 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,559 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,561 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,562 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,564 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,566 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,568 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,570 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,572 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,574 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,575 - INFO - PyruateMinimalAnaerobic/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,578 - INFO - rxn05645_c0> not needed:2.9166491535687347
2026-01-13 19:34:04,581 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,583 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,585 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,587 - INFO - PyruateMinimalAnaerobic/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,589 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,590 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,592 - INFO - PyruateMinimalAnaerobic/bio1:rxn00858_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,594 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,596 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,598 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,600 - INFO - PyruateMinimalAnaerobic/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,602 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,603 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,605 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,607 - INFO - PyruateMinimalAnaerobic/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,609 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,611 - INFO - PyruateMinimalAnaerobic/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,613 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,614 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,616 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,618 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,621 - INFO - rxn01538_c0> not needed:2.9166491535687435
2026-01-13 19:34:04,622 - INFO - rxn05255_c0> not needed:2.9166491535687378
2026-01-13 19:34:04,626 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:04,629 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,631 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,633 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,634 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,636 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,638 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,640 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,642 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,644 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,646 - INFO - PyruateMinimalAnaerobic/bio1:rxn01736_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,648 - INFO - PyruateMinimalAnaerobic/bio1:rxn00644_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,650 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,652 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,653 - INFO - PyruateMinimalAnaerobic/bio1:rxn17394_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,657 - INFO - rxn14070_c0> not needed:2.9166491535687067
2026-01-13 19:34:04,663 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,673 - INFO - PyruateMinimalAnaerobic/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,675 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,678 - INFO - PyruateMinimalAnaerobic/bio1:rxn46249_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,680 - INFO - PyruateMinimalAnaerobic/bio1:rxn20472_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,681 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:04,683 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:04,683 - INFO -   Running ATP safety check...

c0
Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:04,935 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:05,018 - INFO - Objective with gapfill database:114.73871061823243; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:05,341 - INFO -   Saved gapfilled model: gapfilled_models2/Clostridia.7_gf.xml
2026-01-13 19:34:05,343 - INFO -   Total reactions added: 390

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:05,493 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:34:05,572 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,583 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,590 - INFO - cpd00363 not found in model!
2026-01-13 19:34:05,591 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:05,594 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,603 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,612 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,621 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,629 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,638 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,647 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,656 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,665 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,673 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,683 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,684 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,690 - INFO - cpd00363 not found in model!
2026-01-13 19:34:05,691 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:05,694 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,702 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,703 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,712 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,714 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,721 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,726 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,729 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,738 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,738 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,747 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,749 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,756 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,761 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,765 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,772 - INFO - cpd00130 not found in model!
2026-01-13 19:34:05,772 - INFO - Media compound: cpd00130 not found in model.
2026-01-13 19:34:05,773 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,775 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,784 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,785 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,791 - INFO - cpd00209 not found in model!
2026-01-13 19:34:05,792 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:05,794 - INFO - cpd00221 not found in model!
2026-01-13 19:34:05,794 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,795 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:05,798 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,803 - INFO - cpd00418 not found in model!
2026-01-13 19:34:05,803 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:05,806 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,810 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,815 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,822 - INFO - cpd00209 not found in model!
2026-01-13 19:34:05,822 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,823 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:05,825 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,832 - INFO - cpd00418 not found in model!
2026-01-13 19:34:05,833 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:05,834 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,836 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:05,844 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,845 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,851 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:05,852 - INFO - cpd00209 not found in model!
2026-01-13 19:34:05,852 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:05,855 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,857 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,862 - INFO - cpd00418 not found in model!
2026-01-13 19:34:05,863 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:05,865 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,868 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,872 - INFO - cpd08021 not found in model!
2026-01-13 19:34:05,873 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:05,876 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,881 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,883 - INFO - cpd00811 not found in model!
2026-01-13 19:34:05,884 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:05,887 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,892 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,894 - INFO - cpd08021 not found in model!
2026-01-13 19:34:05,895 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:05,898 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,904 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,905 - INFO - cpd00811 not found in model!
2026-01-13 19:34:05,906 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:05,908 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,916 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,917 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,926 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,926 - INFO - cpd00221 not found in model!
2026-01-13 19:34:05,927 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:05,930 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,933 - INFO - cpd11640 not found in model!
2026-01-13 19:34:05,934 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:05,936 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,941 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,943 - INFO - cpd11640 not found in model!
2026-01-13 19:34:05,944 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:05,947 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,953 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,954 - INFO - cpd11640 not found in model!
2026-01-13 19:34:05,955 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:05,957 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,965 - INFO - cpd11640 not found in model!
2026-01-13 19:34:05,964 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,965 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:05,968 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,976 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,977 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,986 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,988 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:05,993 - INFO - cpd11640 not found in model!
2026-01-13 19:34:05,994 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:05,996 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,000 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,005 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,011 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,012 - INFO - cpd11632 not found in model!
2026-01-13 19:34:06,013 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:06,015 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,022 - INFO - cpd08701 not found in model!
2026-01-13 19:34:06,023 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,023 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:06,024 - INFO - cpd01024 not found in model!
2026-01-13 19:34:06,025 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:06,027 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,034 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,034 - INFO - cpd01024 not found in model!
2026-01-13 19:34:06,035 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:06,038 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,045 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,054 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,054 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,057 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,057 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,064 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,065 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,066 - INFO - cpd00187 not found in model!
2026-01-13 19:34:06,066 - INFO - cpd08021 not found in model!
2026-01-13 19:34:06,067 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:06,067 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:06,070 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,071 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,077 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,077 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,078 - INFO - cpd00425 not found in model!
2026-01-13 19:34:06,079 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:06,080 - INFO - cpd00811 not found in model!
2026-01-13 19:34:06,081 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:06,081 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,084 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,089 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,089 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,090 - INFO - cpd00441 not found in model!
2026-01-13 19:34:06,091 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:06,093 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,093 - INFO - cpd08021 not found in model!
2026-01-13 19:34:06,094 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:06,097 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,107 - INFO - cpd00811 not found in model!
2026-01-13 19:34:06,107 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:06,110 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,122 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,133 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,143 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,144 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,146 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,156 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,157 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,160 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,169 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,170 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,173 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,182 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,183 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,186 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,209 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,218 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,219 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,222 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,234 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,245 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,245 - INFO - Objective with gapfill database:86.04689764726727; min objective:0.01
2026-01-13 19:34:06,259 - INFO - cpd08701 not found in model!
2026-01-13 19:34:06,260 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:06,261 - INFO - cpd01024 not found in model!
2026-01-13 19:34:06,262 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:06,266 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,276 - INFO - cpd01024 not found in model!
2026-01-13 19:34:06,276 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:06,280 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,292 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,301 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,302 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,305 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,315 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,315 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,316 - INFO - cpd00187 not found in model!
2026-01-13 19:34:06,317 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:06,320 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,330 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,330 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,332 - INFO - cpd00425 not found in model!
2026-01-13 19:34:06,332 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:06,335 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,345 - INFO - cpd11640 not found in model!
2026-01-13 19:34:06,346 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:06,347 - INFO - cpd00441 not found in model!
2026-01-13 19:34:06,348 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:06,351 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:06,762 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn00361_c0': '>', 'rxn03436_c0': '>', 'rxn02160_c0': '>', 'rxn00300_c0': '>', 'rxn00512_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn00623_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn16218_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn22817_c0': '>', 'rxn48543_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn16217_c0': '>', 'rxn17731_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12942_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn16503_c0': '>', 'rxn16511_c0': '>', 'rxn19346_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn16141_c0': '>', 'rxn16114_c0': '>', 'rxn16671_c0': '>', 'rxn16622_c0': '>', 'rxn41185_c0': '>', 'rxn11285_c0': '>', 'rxn13741_c0': '>', 'rxn18575_c0': '>', 'rxn25161_c0': '>', 'rxn29260_c0': '>', 'rxn47493_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:06,766 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:06,768 - INFO - integrating rxn: rxn00361_c0
2026-01-13 19:34:06,769 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:06,771 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:34:06,773 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:34:06,774 - INFO - integrating rxn: rxn00512_c0
2026-01-13 19:34:06,776 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:06,778 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:06,780 - INFO - integrating rxn: rxn02277_c0
2026-01-13 19:34:06,782 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:34:06,783 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:06,785 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:34:06,787 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:06,789 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:34:06,791 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:34:06,793 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:06,795 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:06,797 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:34:06,798 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:06,800 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:06,801 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:34:06,803 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:06,804 - INFO - integrating rxn: rxn48543_c0
2026-01-13 19:34:06,806 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:06,807 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:34:06,809 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:34:06,810 - INFO - integrating rxn: rxn17731_c0
2026-01-13 19:34:06,812 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:34:06,814 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:34:06,815 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:34:06,817 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:34:06,818 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:06,819 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:34:06,821 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:34:06,822 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:34:06,824 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:34:06,826 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:34:06,827 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:34:06,829 - INFO - integrating rxn: rxn16503_c0
2026-01-13 19:34:06,831 - INFO - integrating rxn: rxn16511_c0
2026-01-13 19:34:06,832 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:34:06,834 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:34:06,836 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:34:06,837 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:34:06,838 - INFO - integrating rxn: rxn16141_c0
2026-01-13 19:34:06,840 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:34:06,841 - INFO - integrating rxn: rxn16671_c0
2026-01-13 19:34:06,843 - INFO - integrating rxn: rxn16622_c0
2026-01-13 19:34:06,844 - INFO - integrating rxn: rxn41185_c0
2026-01-13 19:34:06,846 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:34:06,847 - INFO - integrating rxn: rxn13741_c0
2026-01-13 19:34:06,849 - INFO - integrating rxn: rxn18575_c0
2026-01-13 19:34:06,850 - INFO - integrating rxn: rxn25161_c0
2026-01-13 19:34:06,852 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:34:06,853 - INFO - integrating rxn: rxn47493_c0

c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:07,420 - INFO - Objective with gapfill database:114.7387106182327; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:07,844 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:07,951 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn00359_c0': '<', 'rxn00898_c0': '>', 'rxn02305_c0': '>', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn02835_c0': '>', 'rxn03062_c0': '>', 'rxn12376_c0': '<', 'rxn03437_c0': '>', 'rxn02508_c0': '>', 'rxn03108_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn03841_c0': '>', 'rxn02185_c0': '<', 'rxn02473_c0': '>', 'rxn00623_c0': '<', 'rxn01603_c0': '>', 'rxn03194_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn21860_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn11251_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn13741_c0': '>', 'rxn20508_c0': '>', 'rxn47493_c0': '>', 'rxn14423_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:07,955 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:07,956 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:34:07,958 - INFO - integrating rxn: rxn00898_c0
2026-01-13 19:34:07,960 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:34:07,962 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:07,964 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:34:07,965 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:34:07,967 - INFO - integrating rxn: rxn03062_c0
2026-01-13 19:34:07,967 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:07,968 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:07,970 - INFO - integrating rxn: rxn03437_c0
2026-01-13 19:34:07,971 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:34:07,973 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:34:07,975 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:07,977 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:34:07,978 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:34:07,980 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:07,981 - INFO - integrating rxn: rxn02473_c0
2026-01-13 19:34:07,982 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:34:07,984 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:07,985 - INFO - integrating rxn: rxn03194_c0
2026-01-13 19:34:07,987 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:34:07,987 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:07,989 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:07,990 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:07,992 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:07,993 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:07,995 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:34:07,997 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:34:07,997 - INFO - cpd00363 not found in model!
2026-01-13 19:34:07,998 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:07,998 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:08,000 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:08,001 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,001 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:34:08,003 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:34:08,005 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:34:08,007 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:34:08,008 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:34:08,010 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:08,011 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:34:08,012 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,013 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:34:08,015 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:34:08,016 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:34:08,018 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:34:08,019 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:34:08,021 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:08,022 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:34:08,023 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,024 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:34:08,025 - INFO - integrating rxn: rxn13741_c0
2026-01-13 19:34:08,026 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:34:08,028 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:08,030 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:34:08,030 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn00060_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn00605_c0', '<', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn03086_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn08710_c0', 'rxn02331_c0', 'rxn00060_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00907_c0', 'rxn10213_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn00029_c0', 'rxn02774_c0', 'rxn01505_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn08528_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn08711_c0', 'rxn04413_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn03917_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn00834_c0', 'rxn00599_c0', 'rxn03084_c0', 'rxn03439_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn00605_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn00138_c0', 'rxn05464_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn19346_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn00359_c0', '<', 'new'], ['rxn00898_c0', '>', 'new'], ['rxn02305_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn03062_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn03437_c0', '>', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn02473_c0', '>', 'new'], ['rxn00623_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn03194_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn13741_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn14423_c0', '>', 'new']]
2026-01-13 19:34:08,033 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,034 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,045 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,053 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,055 - INFO - EX_cpd00393_e0< not needed:7.247558985474952
2026-01-13 19:34:08,057 - INFO - EX_cpd00119_e0< not needed:7.247558985474952
2026-01-13 19:34:08,057 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,060 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:08,062 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,064 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:08,065 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,065 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:-1.867921264809053e-12 with min obj:0.01
2026-01-13 19:34:08,067 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,068 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,069 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,071 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:08,072 - INFO - PyruateMinimalAnaerobic/bio1:rxn00060_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,074 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,076 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,077 - INFO - cpd00221 not found in model!
2026-01-13 19:34:08,077 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,077 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,078 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:08,079 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,081 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,082 - INFO - PyruateMinimalAnaerobic/bio1:rxn00907_c0> needed:-6.533405212822342e-13 with min obj:0.01
2026-01-13 19:34:08,083 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,085 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,087 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,089 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,090 - INFO - PyruateMinimalAnaerobic/bio1:rxn00029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,092 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,092 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,094 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,095 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,097 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,099 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,100 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,101 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,102 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,103 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,104 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,105 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:08,107 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,109 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:08,110 - INFO - PyruateMinimalAnaerobic/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,112 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,113 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,113 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,115 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,117 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,117 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,119 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,121 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:1.4160195841484586e-13 with min obj:0.01
2026-01-13 19:34:08,123 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,125 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,126 - INFO - rxn05299_c0> not needed:7.247558985475027
2026-01-13 19:34:08,126 - INFO - cpd00363 not found in model!
2026-01-13 19:34:08,127 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:08,129 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,129 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,131 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,133 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,134 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,136 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,136 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,139 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:-2.616896626095574e-13 with min obj:0.01
2026-01-13 19:34:08,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,141 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:5.555789739208696e-13 with min obj:0.01
2026-01-13 19:34:08,143 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,145 - INFO - PyruateMinimalAnaerobic/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,147 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:3.0055118830802303e-13 with min obj:0.01
2026-01-13 19:34:08,147 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,148 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,150 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:08,151 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,152 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,153 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,155 - INFO - PyruateMinimalAnaerobic/bio1:rxn00605_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:08,157 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,159 - INFO - PyruateMinimalAnaerobic/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,159 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,160 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,162 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,162 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:08,166 - INFO - rxn05255_c0> not needed:7.247558985474914
2026-01-13 19:34:08,169 - INFO - PyruateMinimalAnaerobic/bio1:rxn00138_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:34:08,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,218 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,228 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,229 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,240 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,241 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,251 - INFO - cpd00209 not found in model!
2026-01-13 19:34:08,252 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,252 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:08,255 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,261 - INFO -   Saved gapfilled model: gapfilled_models2/Blvii28_wastewater-sludge_group.3_gf.xml
2026-01-13 19:34:08,263 - INFO -   Total reactions added: 322
2026-01-13 19:34:08,263 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,267 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,275 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,278 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,286 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,288 - INFO - cpd00209 not found in model!
2026-01-13 19:34:08,289 - INFO - Media compound: cpd00209 not found in model.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:08,292 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,298 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,303 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,310 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,315 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,321 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,324 - INFO - cpd00209 not found in model!
2026-01-13 19:34:08,325 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:08,328 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,333 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,336 - INFO - Objective with gapfill database:30.5; min objective:0.01
2026-01-13 19:34:08,340 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,345 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,349 - INFO - cpd08021 not found in model!
2026-01-13 19:34:08,350 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:08,353 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,357 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,362 - INFO - cpd00811 not found in model!
2026-01-13 19:34:08,363 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:08,366 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,369 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,375 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:34:08,375 - INFO - cpd08021 not found in model!
2026-01-13 19:34:08,377 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:08,380 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,381 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,389 - INFO - cpd00811 not found in model!
2026-01-13 19:34:08,390 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:08,393 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,393 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,404 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,405 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,413 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:34:08,415 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,417 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,426 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,430 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,438 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,442 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,449 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,454 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,460 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,466 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,471 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,478 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,483 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,488 - INFO - cpd11640 not found in model!
2026-01-13 19:34:08,489 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:08,492 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,494 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,503 - INFO - cpd11640 not found in model!
2026-01-13 19:34:08,504 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:08,505 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,507 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,514 - INFO - cpd11632 not found in model!
2026-01-13 19:34:08,515 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:08,517 - INFO - cpd11640 not found in model!
2026-01-13 19:34:08,518 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:08,518 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,521 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,527 - INFO - cpd08701 not found in model!
2026-01-13 19:34:08,528 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:08,529 - INFO - cpd01024 not found in model!
2026-01-13 19:34:08,530 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:08,532 - INFO - cpd11640 not found in model!
2026-01-13 19:34:08,533 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:08,533 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,536 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,542 - INFO - cpd01024 not found in model!
2026-01-13 19:34:08,543 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:08,546 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,548 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,557 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,560 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,568 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,570 - INFO - cpd11640 not found in model!
2026-01-13 19:34:08,571 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:08,574 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,577 - INFO - cpd00187 not found in model!
2026-01-13 19:34:08,578 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:08,581 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,586 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,592 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,595 - INFO - cpd11632 not found in model!
2026-01-13 19:34:08,596 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:08,599 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,601 - INFO - cpd00441 not found in model!
2026-01-13 19:34:08,601 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:08,605 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,609 - INFO - cpd08701 not found in model!
2026-01-13 19:34:08,609 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:08,610 - INFO - cpd01024 not found in model!
2026-01-13 19:34:08,611 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:08,613 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,623 - INFO - cpd01024 not found in model!
2026-01-13 19:34:08,624 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:08,627 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,639 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,649 - INFO - cpd11640 not found in model!
2026-01-13 19:34:08,649 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:08,653 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,663 - INFO - cpd11640 not found in model!
2026-01-13 19:34:08,664 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:08,665 - INFO - cpd00187 not found in model!
2026-01-13 19:34:08,665 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:08,669 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,679 - INFO - cpd11640 not found in model!
2026-01-13 19:34:08,680 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:08,681 - INFO - cpd00425 not found in model!
2026-01-13 19:34:08,681 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:08,685 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:08,695 - INFO - cpd11640 not found in model!
2026-01-13 19:34:08,695 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:08,698 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:08,772 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:09,012 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,015 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,029 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,034 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,040 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,053 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,058 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,065 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,070 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,076 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,081 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,087 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,093 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,098 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,104 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,111 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,115 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,123 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,124 - INFO - cpd00221 not found in model!
2026-01-13 19:34:09,125 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:09,128 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,136 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,139 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,150 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,150 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,163 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,165 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,171 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,177 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,187 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,189 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,196 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,202 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,207 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,209 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,214 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,218 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,220 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,229 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,230 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,237 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,240 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,241 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,248 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,250 - INFO - cpd00221 not found in model!
2026-01-13 19:34:09,250 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:09,252 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,253 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,259 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,263 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,264 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,270 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,272 - INFO - cpd00221 not found in model!
2026-01-13 19:34:09,272 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:09,275 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,275 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,282 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,286 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,287 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,294 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,297 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,299 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,305 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,309 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,312 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,316 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,319 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,327 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,328 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,330 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,339 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,341 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,351 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,351 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,355 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,362 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,363 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,366 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,372 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,374 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,378 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,383 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,386 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,389 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,392 - INFO - cpd00221 not found in model!
2026-01-13 19:34:09,393 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:09,395 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,398 - INFO - cpd08021 not found in model!
2026-01-13 19:34:09,398 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:09,401 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,402 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,406 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,411 - INFO - cpd00811 not found in model!
2026-01-13 19:34:09,412 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:09,413 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,415 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,416 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,424 - INFO - cpd08021 not found in model!
2026-01-13 19:34:09,424 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,425 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:09,427 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,437 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,438 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,438 - INFO - cpd00811 not found in model!
2026-01-13 19:34:09,439 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:09,442 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,448 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,449 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,454 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,460 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,465 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,468 - INFO - cpd11640 not found in model!
2026-01-13 19:34:09,469 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:09,470 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,472 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,474 - INFO - cpd11640 not found in model!
2026-01-13 19:34:09,475 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:09,477 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,481 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,482 - INFO - cpd11640 not found in model!
2026-01-13 19:34:09,483 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:09,486 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,487 - INFO - cpd11640 not found in model!
2026-01-13 19:34:09,487 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:09,490 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,492 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,496 - INFO - cpd11640 not found in model!
2026-01-13 19:34:09,497 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:09,499 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,502 - INFO - cpd11640 not found in model!
2026-01-13 19:34:09,502 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:09,502 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,505 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,508 - INFO - cpd11640 not found in model!
2026-01-13 19:34:09,509 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:09,512 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,513 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,514 - INFO - cpd11640 not found in model!
2026-01-13 19:34:09,515 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:09,518 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,522 - INFO - cpd08021 not found in model!
2026-01-13 19:34:09,523 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:09,523 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,526 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,535 - INFO - cpd00811 not found in model!
2026-01-13 19:34:09,535 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:09,538 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,538 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,540 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:09,547 - INFO - cpd08021 not found in model!
2026-01-13 19:34:09,547 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:09,548 - INFO - cpd11640 not found in model!
2026-01-13 19:34:09,549 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:09,549 - INFO - cpd11640 not found in model!

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:09,819 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:34:09,859 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:10,488 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:10,892 - INFO -   Saved gapfilled model: gapfilled_models2/Comamonas.5_gf.xml
2026-01-13 19:34:10,894 - INFO -   Total reactions added: 272
2026-01-13 19:34:10,894 - INFO - Objective with gapfill database:78.3026768590133; min objective:0.01
2026-01-13 19:34:11,043 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:34:11,179 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,209 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,221 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,232 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,243 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,255 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,266 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,277 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,289 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,300 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,311 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,323 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,334 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,345 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,356 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,367 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,379 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:11,391 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,396 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:11,402 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,413 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,425 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,437 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,448 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,471 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,482 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,493 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,500 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn03436_c0': '>', 'rxn02160_c0': '>', 'rxn00957_c0': '>', 'rxn00830_c0': '>', 'rxn01256_c0': '>', 'rxn01000_c0': '>', 'rxn12868_c0': '>', 'rxn01539_c0': '<', 'rxn09310_c0': '>', 'rxn03841_c0': '>', 'rxn12239_c0': '>', 'rxn01257_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn00157_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn25638_c0': '>', 'rxn11251_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn15939_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn08921_c0': '>', 'rxn47493_c0': '>', 'rxn10120_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:11,505 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,505 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:11,507 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:34:11,510 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:34:11,512 - INFO - integrating rxn: rxn00830_c0
2026-01-13 19:34:11,514 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:34:11,516 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:34:11,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,518 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:34:11,520 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:34:11,522 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:11,524 - INFO - integrating rxn: rxn03841_c0
2026-01-13 19:34:11,527 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:34:11,528 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,528 - INFO - integrating rxn: rxn01257_c0
2026-01-13 19:34:11,531 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:34:11,533 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:11,535 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:11,537 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:34:11,538 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:34:11,539 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,541 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:11,542 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:11,545 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:11,547 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:11,549 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:11,549 - INFO - cpd08021 not found in model!
2026-01-13 19:34:11,550 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:11,551 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:11,553 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:34:11,553 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,555 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:34:11,557 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:34:11,559 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:34:11,560 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:34:11,563 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:34:11,563 - INFO - cpd00811 not found in model!
2026-01-13 19:34:11,564 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:11,565 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:34:11,566 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:34:11,567 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,568 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:34:11,570 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:11,572 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:34:11,574 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:34:11,575 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:34:11,577 - INFO - cpd08021 not found in model!
2026-01-13 19:34:11,577 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:34:11,578 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:11,579 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:34:11,581 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,581 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:11,583 - INFO - integrating rxn: rxn10120_c0
2026-01-13 19:34:11,584 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00340_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn01313_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00362_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00063_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn00470_c0', 'rxn08710_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn00340_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn05645_c0', 'rxn08711_c0', 'rxn04413_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn10094_c0', 'rxn01313_c0', 'rxn03917_c0', 'rxn05029_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn00834_c0', 'rxn00362_c0', 'rxn11702_c0', 'rxn03084_c0', 'rxn03638_c0', 'rxn02056_c0', 'rxn03075_c0', 'rxn00134_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn01736_c0', 'rxn00644_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn17394_c0', 'rxn14070_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn46249_c0', 'rxn20472_c0', 'rxn40674_c0', ['rxn03436_c0', '>', 'new'], ['rxn02160_c0', '>', 'new'], ['rxn00957_c0', '>', 'new'], ['rxn00830_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn12868_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn03841_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn01257_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn00157_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn10120_c0', '>', 'new']]
2026-01-13 19:34:11,590 - INFO - cpd00811 not found in model!
2026-01-13 19:34:11,591 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:11,594 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,606 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,611 - INFO - EX_cpd00393_e0< not needed:4.36879946146801
2026-01-13 19:34:11,613 - INFO - EX_cpd00220_e0< not needed:4.36879946146801
2026-01-13 19:34:11,617 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,618 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:11,622 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:11,624 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,626 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,627 - INFO - cpd11640 not found in model!
2026-01-13 19:34:11,628 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:11,628 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,630 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,631 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,633 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,635 - INFO - PyruateMinimalAnaerobic/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,637 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,639 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,640 - INFO - cpd11640 not found in model!
2026-01-13 19:34:11,641 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,641 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:11,643 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:11,644 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,645 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,647 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,650 - INFO - PyruateMinimalAnaerobic/bio1:rxn00340_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,652 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,654 - INFO - cpd11640 not found in model!
2026-01-13 19:34:11,654 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,655 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:11,656 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,658 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,658 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,660 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,662 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,664 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,667 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,667 - INFO - cpd11640 not found in model!
2026-01-13 19:34:11,668 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:11,669 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,671 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,671 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,673 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,675 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,677 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:11,679 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,683 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,684 - INFO - rxn00966_c0< not needed:4.368799461468021
2026-01-13 19:34:11,690 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,694 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,697 - INFO - rxn05645_c0> not needed:4.36879946146801
2026-01-13 19:34:11,702 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,704 - INFO - cpd11640 not found in model!
2026-01-13 19:34:11,705 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:11,706 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,708 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,708 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,710 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:1.5083835784533888e-13 with min obj:0.01
2026-01-13 19:34:11,712 - INFO - PyruateMinimalAnaerobic/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,717 - INFO - rxn01313_c0> not needed:4.3687994614680035
2026-01-13 19:34:11,719 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,723 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,726 - INFO - PyruateMinimalAnaerobic/bio1:rxn05029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,729 - INFO - cpd11632 not found in model!
2026-01-13 19:34:11,729 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,730 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:11,731 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,733 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,733 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,735 - INFO - PyruateMinimalAnaerobic/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,737 - INFO - PyruateMinimalAnaerobic/bio1:rxn00362_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,739 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,741 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,742 - INFO - cpd08701 not found in model!
2026-01-13 19:34:11,743 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,743 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:11,744 - INFO - cpd01024 not found in model!
2026-01-13 19:34:11,745 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:11,745 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:11,748 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:11,753 - INFO - PyruateMinimalAnaerobic/bio1:rxn03075_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,757 - INFO - cpd01024 not found in model!
2026-01-13 19:34:11,757 - INFO - PyruateMinimalAnaerobic/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:11,758 - INFO - Media compound: cpd01024 not found in model.

c0

2026-01-13 19:34:13,927 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:13,946 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:13,958 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:13,971 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:13,983 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:13,995 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,007 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,019 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,032 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,044 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,056 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,068 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,080 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,081 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,092 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,094 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,101 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,106 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,110 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,118 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,118 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,127 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,129 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,136 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,142 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,145 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,152 - INFO - cpd00159 not found in model!
2026-01-13 19:34:14,152 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:14,155 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,155 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,162 - INFO - cpd00221 not found in model!
2026-01-13 19:34:14,163 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:14,165 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,167 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,173 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,179 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,182 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,190 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,190 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,199 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,203 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,208 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,215 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,226 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,228 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,234 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,240 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,243 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,250 - INFO - cpd00159 not found in model!
2026-01-13 19:34:14,250 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:14,253 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,254 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,260 - INFO - cpd00221 not found in model!
2026-01-13 19:34:14,261 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:14,264 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,267 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,273 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,280 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,283 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,291 - INFO - cpd00075 not found in model!
2026-01-13 19:34:14,291 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:14,292 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,294 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,302 - INFO - cpd00209 not found in model!
2026-01-13 19:34:14,303 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:14,305 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,306 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,314 - INFO - cpd00418 not found in model!
2026-01-13 19:34:14,315 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:14,317 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,317 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,325 - INFO - cpd00075 not found in model!
2026-01-13 19:34:14,326 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:14,328 - INFO - cpd08021 not found in model!
2026-01-13 19:34:14,328 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:14,329 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,332 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,336 - INFO - cpd00209 not found in model!
2026-01-13 19:34:14,337 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:14,340 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,341 - INFO - cpd00811 not found in model!
2026-01-13 19:34:14,342 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:14,345 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,347 - INFO - cpd00418 not found in model!
2026-01-13 19:34:14,348 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:14,350 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,354 - INFO - cpd08021 not found in model!
2026-01-13 19:34:14,355 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:14,358 - INFO - cpd00075 not found in model!
2026-01-13 19:34:14,358 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:14,359 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,362 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,369 - INFO - cpd00811 not found in model!
2026-01-13 19:34:14,369 - INFO - cpd00209 not found in model!
2026-01-13 19:34:14,370 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:14,369 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:14,372 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,373 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,379 - INFO - cpd00418 not found in model!
2026-01-13 19:34:14,380 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:14,382 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,384 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,389 - INFO - cpd08021 not found in model!
2026-01-13 19:34:14,390 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:14,392 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,396 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,400 - INFO - cpd00811 not found in model!
2026-01-13 19:34:14,400 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:14,403 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,408 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,410 - INFO - cpd08021 not found in model!
2026-01-13 19:34:14,410 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:14,413 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,420 - INFO - cpd00811 not found in model!
2026-01-13 19:34:14,420 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,420 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:14,423 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,431 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,431 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,440 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,447 - INFO - cpd11640 not found in model!
2026-01-13 19:34:14,448 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:14,450 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,456 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,457 - INFO - cpd11640 not found in model!
2026-01-13 19:34:14,458 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:14,460 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,467 - INFO - cpd11640 not found in model!
2026-01-13 19:34:14,467 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:14,468 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,470 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,477 - INFO - cpd00159 not found in model!
2026-01-13 19:34:14,478 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:14,479 - INFO - cpd11640 not found in model!
2026-01-13 19:34:14,479 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:14,480 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,482 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,490 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,492 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,497 - INFO - cpd00159 not found in model!
2026-01-13 19:34:14,498 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:14,500 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,502 - INFO - cpd11632 not found in model!
2026-01-13 19:34:14,502 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:14,506 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,507 - INFO - cpd11640 not found in model!
2026-01-13 19:34:14,508 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:14,511 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,515 - INFO - cpd08701 not found in model!
2026-01-13 19:34:14,516 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:14,517 - INFO - cpd01024 not found in model!
2026-01-13 19:34:14,518 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:14,519 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,521 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,526 - INFO - cpd11632 not found in model!
2026-01-13 19:34:14,527 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:14,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,531 - INFO - cpd01024 not found in model!
2026-01-13 19:34:14,532 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:14,534 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,536 - INFO - cpd08701 not found in model!
2026-01-13 19:34:14,536 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:14,537 - INFO - cpd01024 not found in model!
2026-01-13 19:34:14,538 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:14,540 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,546 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,547 - INFO - cpd01024 not found in model!
2026-01-13 19:34:14,548 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:14,550 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,558 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,558 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,565 - INFO - cpd11640 not found in model!
2026-01-13 19:34:14,566 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:14,568 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,569 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,575 - INFO - cpd11640 not found in model!
2026-01-13 19:34:14,576 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:14,576 - INFO - cpd00187 not found in model!
2026-01-13 19:34:14,577 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:14,579 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,581 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:14,586 - INFO - cpd11640 not found in model!

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:22,053 - INFO - Objective with gapfill database:114.73871061823192; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:24,174 - INFO - Objective with gapfill database:86.04689764726824; min objective:0.01
2026-01-13 19:34:24,399 - INFO - Objective with gapfill database:114.73871061823192; min objective:0.01
2026-01-13 19:34:24,954 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn03436_c0': '>', 'rxn02835_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn04954_c0': '<', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn48543_c0': '>', 'rxn20834_c0': '>', 'rxn11274_c0': '>', 'rxn12939_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn16826_c0': '>', 'rxn16776_c0': '>', 'rxn16827_c0': '>', 'rxn16829_c0': '>', 'rxn46124_c0': '>', 'rxn16511_c0': '>', 'rxn30633_c0': '>', 'rxn15091_c0': '>', 'rxn16114_c0': '>', 'rxn41185_c0': '>', 'rxn10095_c0': '>', 'rxn15939_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn42332_c0': '>', 'rxn47493_c0': '>', 'rxn08473_c0': '>', 'rxn15754_c0': '>', 'rxn14050_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:24,958 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:24,960 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:24,962 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:34:24,963 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:24,965 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:24,967 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:34:24,969 - INFO - integrating rxn: rxn04954_c0
2026-01-13 19:34:24,970 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:24,972 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:24,974 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:24,975 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:24,977 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:24,978 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:24,980 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:24,981 - INFO - integrating rxn: rxn48543_c0
2026-01-13 19:34:24,983 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:24,985 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:34:24,986 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:34:24,988 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:24,989 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:34:24,992 - INFO - integrating rxn: rxn16826_c0
2026-01-13 19:34:24,994 - INFO - integrating rxn: rxn16776_c0
2026-01-13 19:34:24,995 - INFO - integrating rxn: rxn16827_c0
2026-01-13 19:34:24,997 - INFO - integrating rxn: rxn16829_c0
2026-01-13 19:34:24,998 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:34:25,000 - INFO - integrating rxn: rxn16511_c0
2026-01-13 19:34:25,001 - INFO - integrating rxn: rxn30633_c0
2026-01-13 19:34:25,003 - INFO - integrating rxn: rxn15091_c0
2026-01-13 19:34:25,004 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:34:25,006 - INFO - integrating rxn: rxn41185_c0
2026-01-13 19:34:25,007 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:34:25,009 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:34:25,010 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:34:25,012 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:34:25,013 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:34:25,015 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:25,016 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:34:25,018 - INFO - integrating rxn: rxn15754_c0
2026-01-13 19:34:25,019 - INFO - integrating rxn: rxn14050_c0
2026-01-13 19:34:25,021 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:34:25,021 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn01332_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn00179_c0', 'rxn10336_c0', 'rxn01117_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn02404_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn03536_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03159_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn08711_c0', 'rxn00137_c0', 'rxn00832_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn03917_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn03150_c0', 'rxn02303_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn06865_c0', 'rxn00599_c0', 'rxn11702_c0', 'rxn01332_c0', 'rxn03439_c0', 'rxn00122_c0', 'rxn08620_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn03130_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn15167_c0', 'rxn19346_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn04954_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn48543_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn16826_c0', '>', 'new'], ['rxn16776_c0', '>', 'new'], ['rxn16827_c0', '>', 'new'], ['rxn16829_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn16511_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn15091_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn41185_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn15754_c0', '>', 'new'], ['rxn14050_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:34:25,058 - INFO - EX_cpd00393_e0< not needed:4.948705866247766
2026-01-13 19:34:25,060 - INFO - EX_cpd00119_e0< not needed:4.948705866247766
2026-01-13 19:34:25,062 - INFO - EX_cpd00220_e0< not needed:4.948705866247766
2026-01-13 19:34:25,064 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:25,066 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,068 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:-3.9358929585291994e-13 with min obj:0.01
2026-01-13 19:34:25,070 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,072 - INFO - PyruateMinimalAnaerobic/bio1:rxn00179_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,074 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,076 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:25,078 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,080 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,081 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:25,083 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,085 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,087 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,089 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,091 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,092 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,094 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,096 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,098 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,099 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,101 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,103 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,105 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,107 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,108 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,110 - INFO - PyruateMinimalAnaerobic/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,112 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,113 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:25,115 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,117 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:25,119 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,121 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,123 - INFO - rxn05645_c0> not needed:4.9487058662478
2026-01-13 19:34:25,127 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,128 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,131 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:1.3623394629433506e-13 with min obj:0.01
2026-01-13 19:34:25,133 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,137 - INFO - rxn05299_c0> not needed:4.948705866247805
2026-01-13 19:34:25,141 - INFO - PyruateMinimalAnaerobic/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:25,143 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,144 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,146 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,148 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,150 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,152 - INFO - PyruateMinimalAnaerobic/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,153 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,156 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,158 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:-2.246479641199576e-13 with min obj:0.01
2026-01-13 19:34:25,159 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:25,161 - INFO - PyruateMinimalAnaerobic/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,163 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,165 - INFO - PyruateMinimalAnaerobic/bio1:rxn01332_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,167 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,169 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,170 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,172 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,174 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,176 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,180 - INFO - rxn05255_c0> not needed:4.948705866247847
2026-01-13 19:34:25,184 - INFO - PyruateMinimalAnaerobic/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,186 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,187 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,189 - INFO - PyruateMinimalAnaerobic/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,191 - INFO - PyruateMinimalAnaerobic/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,193 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,194 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,196 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,198 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,200 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,202 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,206 - INFO - rxn15167_c0> not needed:4.9470098634105035
2026-01-13 19:34:25,207 - INFO - rxn19346_c0> not needed:4.9470098634105035
2026-01-13 19:34:25,211 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,213 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,215 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,217 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,219 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,220 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:25,221 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:25,222 - INFO -   Running ATP safety check...

c0
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:26,229 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:26,294 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,311 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,324 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,336 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,348 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,360 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,372 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,383 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,395 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,407 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,419 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,431 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,445 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,457 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,468 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,480 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,490 - INFO - Objective with gapfill database:86.04689764726824; min objective:0.01
2026-01-13 19:34:26,492 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,504 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,528 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,540 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,552 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,564 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,573 - INFO - cpd00075 not found in model!
2026-01-13 19:34:26,574 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:26,577 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,587 - INFO - cpd00209 not found in model!
2026-01-13 19:34:26,587 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:26,591 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,600 - INFO - cpd00418 not found in model!
2026-01-13 19:34:26,601 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:26,604 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,614 - INFO - cpd00075 not found in model!
2026-01-13 19:34:26,615 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:26,618 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,628 - INFO - cpd00209 not found in model!
2026-01-13 19:34:26,629 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:26,632 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,642 - INFO - cpd00418 not found in model!
2026-01-13 19:34:26,643 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:26,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,656 - INFO - cpd00075 not found in model!
2026-01-13 19:34:26,657 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:26,660 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,670 - INFO - cpd00209 not found in model!
2026-01-13 19:34:26,671 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:26,674 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,683 - INFO - cpd00418 not found in model!
2026-01-13 19:34:26,684 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:26,687 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,697 - INFO - cpd08021 not found in model!
2026-01-13 19:34:26,698 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:26,698 - INFO -   Saved gapfilled model: gapfilled_models2/Christensenellaceae_R-7_group.76_gf.xml
2026-01-13 19:34:26,700 - INFO -   Total reactions added: 304
2026-01-13 19:34:26,701 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,711 - INFO - cpd00811 not found in model!
2026-01-13 19:34:26,712 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:26,715 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,725 - INFO - cpd08021 not found in model!
2026-01-13 19:34:26,725 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:26,728 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,738 - INFO - cpd00811 not found in model!
2026-01-13 19:34:26,739 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:26,742 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,753 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,766 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,777 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,789 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,802 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,814 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,827 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,839 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,851 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,863 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,866 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:34:26,872 - INFO - cpd11632 not found in model!
2026-01-13 19:34:26,873 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:26,876 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,886 - INFO - cpd08701 not found in model!
2026-01-13 19:34:26,887 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:26,888 - INFO - cpd01024 not found in model!
2026-01-13 19:34:26,889 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:26,892 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,902 - INFO - cpd01024 not found in model!
2026-01-13 19:34:26,903 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:26,906 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,917 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,929 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,939 - INFO - cpd00187 not found in model!
2026-01-13 19:34:26,940 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:26,943 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,953 - INFO - cpd00425 not found in model!
2026-01-13 19:34:26,954 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:26,957 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:26,967 - INFO - cpd00441 not found in model!
2026-01-13 19:34:26,968 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:26,971 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:27,051 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn03436_c0': '>', 'rxn00300_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn21860_c0': '>', 'rxn11274_c0': '>', 'rxn12932_c0': '>', 'rxn12939_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12942_c0': '>', 'rxn11251_c0': '>', 'rxn16503_c0': '>', 'rxn16511_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn17394_c0': '>', 'rxn30685_c0': '>', 'rxn41185_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn15940_c0': '>', 'rxn20472_c0': '>', 'rxn08989_c0': '>', 'rxn47493_c0': '>', 'rxn10154_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:27,054 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:27,057 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:27,059 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:34:27,061 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:27,063 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:27,065 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:27,067 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:27,069 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:27,071 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:27,073 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:27,075 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:27,076 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:27,078 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:27,080 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:34:27,081 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:34:27,083 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:34:27,085 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:34:27,086 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:27,088 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:34:27,089 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:34:27,091 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:34:27,093 - INFO - integrating rxn: rxn16503_c0
2026-01-13 19:34:27,094 - INFO - integrating rxn: rxn16511_c0
2026-01-13 19:34:27,096 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:34:27,097 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:34:27,099 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:34:27,101 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:34:27,102 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:34:27,104 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:34:27,106 - INFO - integrating rxn: rxn17394_c0
2026-01-13 19:34:27,107 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:27,109 - INFO - integrating rxn: rxn41185_c0
2026-01-13 19:34:27,110 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:34:27,112 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:34:27,113 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:34:27,115 - INFO - integrating rxn: rxn20472_c0
2026-01-13 19:34:27,117 - INFO - integrating rxn: rxn08989_c0
2026-01-13 19:34:27,118 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:27,120 - INFO - integrating rxn: rxn10154_c0
2026-01-13 19:34:27,121 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:34:27,122 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn10030_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn03907_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn08710_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn10030_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn02404_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn01505_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03397_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn05645_c0', 'rxn04413_c0', 'rxn00832_c0', 'rxn10094_c0', 'rxn03150_c0', 'rxn03907_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn11702_c0', 'rxn02056_c0', 'rxn03075_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn21635_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn16503_c0', '>', 'new'], ['rxn16511_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn41185_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn08989_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn10154_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:34:27,147 - INFO - EX_cpd00393_e0< not needed:5.198671887089262
2026-01-13 19:34:27,148 - INFO - EX_cpd00220_e0< not needed:5.198671887089262
2026-01-13 19:34:27,152 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:27,154 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,156 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:6.285288807031167e-13 with min obj:0.01
2026-01-13 19:34:27,158 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,160 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,162 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,163 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,165 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,167 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,169 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,172 - INFO - PyruateMinimalAnaerobic/bio1:rxn10030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,174 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,176 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:27,248 - INFO - rxn05255_c0> not needed:5.19867188708929

c0

2026-01-13 19:34:27,251 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:27,254 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,256 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,257 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,259 - INFO - PyruateMinimalAnaerobic/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,261 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,262 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:27,263 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,265 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,266 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,268 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,270 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,272 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,275 - INFO - rxn03396_c0> not needed:5.19867188708929
2026-01-13 19:34:27,278 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,280 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,283 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,286 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,291 - INFO - rxn15939_c0> not needed:5.198671887089202
2026-01-13 19:34:27,294 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,296 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:27,297 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:27,297 - INFO -   Running ATP safety check...

c0

2026-01-13 19:34:28,082 - INFO - Objective with gapfill database:114.73871061823212; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:28,572 - INFO - Objective with gapfill database:34.49999999999998; min objective:0.01
2026-01-13 19:34:28,609 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:34:29,173 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,192 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,205 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,229 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,240 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,252 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,264 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,275 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,285 - INFO - cpd00221 not found in model!
2026-01-13 19:34:29,286 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:29,289 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,300 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,312 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,324 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,335 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,347 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,359 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,370 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,383 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,394 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,406 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,416 - INFO - cpd00221 not found in model!
2026-01-13 19:34:29,416 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:29,419 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,431 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,442 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,454 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,464 - INFO - cpd00209 not found in model!
2026-01-13 19:34:29,465 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:29,469 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,482 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,494 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,504 - INFO - cpd00209 not found in model!
2026-01-13 19:34:29,505 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:29,508 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,522 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,534 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,545 - INFO - cpd00209 not found in model!
2026-01-13 19:34:29,545 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:29,548 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,562 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,574 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,586 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,597 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,609 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,622 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,634 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,645 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,657 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,669 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,682 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,694 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,706 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,718 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,730 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,739 - INFO - cpd11632 not found in model!
2026-01-13 19:34:29,740 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:29,743 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,753 - INFO - cpd08701 not found in model!
2026-01-13 19:34:29,754 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:29,755 - INFO - cpd01024 not found in model!
2026-01-13 19:34:29,756 - INFO - Media compound: cpd01024 not found in model.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:29,759 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

None

2026-01-13 19:34:29,769 - INFO - cpd01024 not found in model!
2026-01-13 19:34:29,770 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:29,773 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,774 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:29,784 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,796 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,804 - INFO - Objective with gapfill database:86.04689764726454; min objective:0.01
2026-01-13 19:34:29,806 - INFO - cpd00187 not found in model!
2026-01-13 19:34:29,807 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:29,810 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:29,822 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,834 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:29,857 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:34:29,873 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:34:30,235 - INFO - Objective with gapfill database:86.0468976472672; min objective:0.01
2026-01-13 19:34:30,248 - INFO -   Saved gapfilled model: gapfilled_models2/Ca_Phosphoribacter.1_gf.xml
2026-01-13 19:34:30,250 - INFO -   Total reactions added: 316
2026-01-13 19:34:30,402 - INFO - Objective with gapfill database:114.73871061823212; min objective:0.01
2026-01-13 19:34:30,414 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:30,780 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:30,794 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:30,803 - INFO - cpd00363 not found in model!
2026-01-13 19:34:30,804 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:30,808 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,810 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:30,819 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,829 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,840 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,850 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,861 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,870 - INFO - cpd00159 not found in model!
2026-01-13 19:34:30,870 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:30,873 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,884 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,894 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,904 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,914 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,922 - INFO - cpd00363 not found in model!
2026-01-13 19:34:30,923 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:30,926 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,935 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,945 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,954 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,964 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,973 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,981 - INFO - cpd00159 not found in model!
2026-01-13 19:34:30,982 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:30,983 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn00179_c0': '>', 'rxn00796_c0': '>', 'rxn03436_c0': '>', 'rxn02160_c0': '>', 'rxn02835_c0': '>', 'rxn12376_c0': '<', 'rxn01539_c0': '<', 'rxn01537_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn00430_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn16218_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn16217_c0': '>', 'rxn17445_c0': '>', 'rxn11274_c0': '>', 'rxn12939_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn02485_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn16503_c0': '>', 'rxn16511_c0': '>', 'rxn01736_c0': '>', 'rxn04551_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn16671_c0': '>', 'rxn29919_c0': '>', 'rxn30685_c0': '>', 'rxn10095_c0': '>', 'rxn15940_c0': '>', 'rxn16341_c0': '>', 'rxn27266_c0': '>', 'rxn40040_c0': '>', 'rxn13301_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:30,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,987 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:30,989 - INFO - integrating rxn: rxn00179_c0
2026-01-13 19:34:30,991 - INFO - integrating rxn: rxn00796_c0
2026-01-13 19:34:30,993 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:30,994 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:30,994 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:34:30,996 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:34:30,998 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:30,999 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:34:31,001 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:34:31,003 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:31,004 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,004 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:34:31,006 - INFO - integrating rxn: rxn00430_c0
2026-01-13 19:34:31,007 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:31,009 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:31,011 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:34:31,013 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:31,014 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,015 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:34:31,016 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:31,018 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:31,019 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:31,021 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:31,021 - INFO - cpd00075 not found in model!
2026-01-13 19:34:31,022 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:31,022 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:34:31,024 - INFO - integrating rxn: rxn17445_c0
2026-01-13 19:34:31,025 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,026 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:34:31,027 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:34:31,029 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:31,030 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:34:31,031 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:34:31,033 - INFO - cpd00209 not found in model!
2026-01-13 19:34:31,033 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:34:31,034 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:31,036 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:34:31,037 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,038 - INFO - integrating rxn: rxn16503_c0
2026-01-13 19:34:31,040 - INFO - integrating rxn: rxn16511_c0
2026-01-13 19:34:31,042 - INFO - integrating rxn: rxn01736_c0
2026-01-13 19:34:31,043 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:34:31,045 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:34:31,045 - INFO - cpd00418 not found in model!
2026-01-13 19:34:31,046 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:31,047 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:34:31,048 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:34:31,049 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,050 - INFO - integrating rxn: rxn16671_c0
2026-01-13 19:34:31,051 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:34:31,053 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:31,054 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:34:31,056 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:34:31,058 - INFO - cpd00075 not found in model!
2026-01-13 19:34:31,058 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:34:31,058 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:31,059 - INFO - integrating rxn: rxn27266_c0
2026-01-13 19:34:31,061 - INFO - integrating rxn: rxn40040_c0
2026-01-13 19:34:31,062 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,062 - INFO - integrating rxn: rxn13301_c0
2026-01-13 19:34:31,064 - INFO - integrating rxn: rxn41399_c0
2026-01-13 19:34:31,066 - INFO - integrating rxn: rxn41401_c0
2026-01-13 19:34:31,067 - INFO - integrating rxn: rxn15776_c0
2026-01-13 19:34:31,068 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn09128_c0', '<', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn03086_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn09128_c0', 'rxn03536_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08618_c0', 'rxn03537_c0', 'rxn03916_c0', 'rxn05645_c0', 'rxn00832_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn03638_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn19728_c0', 'rxn20235_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn00179_c0', '>', 'new'], ['rxn00796_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn02160_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn00430_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn17445_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn16503_c0', '>', 'new'], ['rxn16511_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn16671_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn27266_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn13301_c0', '>', 'new'], ['rxn41399_c0', '>', 'new'], ['rxn41401_c0', '>', 'new'], ['rxn15776_c0', '>', 'new']]
2026-01-13 19:34:31,070 - INFO - cpd00209 not found in model!
2026-01-13 19:34:31,071 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:31,074 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,083 - INFO - cpd00418 not found in model!
2026-01-13 19:34:31,084 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:31,087 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,096 - INFO - cpd00075 not found in model!
2026-01-13 19:34:31,096 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:31,099 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,105 - INFO - EX_cpd00393_e0< not needed:13.80065438082314
2026-01-13 19:34:31,107 - INFO - EX_cpd00220_e0< not needed:13.80065438082314
2026-01-13 19:34:31,107 - INFO - cpd00209 not found in model!
2026-01-13 19:34:31,109 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:31,111 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:31,112 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,112 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,114 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:31,117 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:1.0821245114890979e-12 with min obj:0.01
2026-01-13 19:34:31,119 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,120 - INFO - cpd00418 not found in model!
2026-01-13 19:34:31,121 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:31,121 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:1.0627462800652702e-13 with min obj:0.01
2026-01-13 19:34:31,123 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,123 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,125 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,127 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,128 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,130 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,132 - INFO - cpd08021 not found in model!
2026-01-13 19:34:31,132 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,133 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:31,134 - INFO - PyruateMinimalAnaerobic/bio1:rxn09128_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:31,136 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,136 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,137 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,139 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,141 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,143 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,145 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,145 - INFO - cpd00811 not found in model!
2026-01-13 19:34:31,146 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:31,149 - INFO - rxn05645_c0> not needed:13.800654380823088
2026-01-13 19:34:31,149 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,153 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:31,155 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,157 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,158 - INFO - cpd08021 not found in model!
2026-01-13 19:34:31,159 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:31,159 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:4.1014924343984346e-13 with min obj:0.01
2026-01-13 19:34:31,161 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,162 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,163 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:31,165 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,167 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,169 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,170 - INFO - cpd00811 not found in model!
2026-01-13 19:34:31,170 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,171 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:31,173 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,175 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,179 - INFO - rxn05255_c0> not needed:13.80065438082314
2026-01-13 19:34:31,183 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,185 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,187 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,189 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,192 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,194 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,196 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,196 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:31,198 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01

c0

2026-01-13 19:34:31,229 - INFO - Media compound: cpd11640 not found in model.

2026-01-13 19:34:31,233 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,241 - INFO - cpd00159 not found in model!
2026-01-13 19:34:31,241 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:31,242 - INFO - cpd11640 not found in model!
2026-01-13 19:34:31,243 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:31,246 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,256 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,265 - INFO - cpd00159 not found in model!
2026-01-13 19:34:31,265 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:31,268 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,276 - INFO - cpd11640 not found in model!
2026-01-13 19:34:31,277 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:31,280 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,290 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,298 - INFO - cpd11632 not found in model!
2026-01-13 19:34:31,299 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:31,302 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,310 - INFO - cpd08701 not found in model!
2026-01-13 19:34:31,311 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:31,312 - INFO - cpd01024 not found in model!
2026-01-13 19:34:31,313 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:31,315 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,324 - INFO - cpd01024 not found in model!
2026-01-13 19:34:31,324 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:31,327 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,338 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,346 - INFO - cpd11640 not found in model!
2026-01-13 19:34:31,347 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:31,351 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,359 - INFO - cpd11640 not found in model!
2026-01-13 19:34:31,361 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:31,361 - INFO - cpd00187 not found in model!
2026-01-13 19:34:31,362 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:31,366 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,375 - INFO - cpd11640 not found in model!
2026-01-13 19:34:31,376 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:31,377 - INFO - cpd00425 not found in model!
2026-01-13 19:34:31,378 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:31,382 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:31,391 - INFO - cpd11640 not found in model!
2026-01-13 19:34:31,392 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:31,392 - INFO - cpd00441 not found in model!
2026-01-13 19:34:31,393 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:31,397 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:31,543 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:34:31,559 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:34:32,095 - INFO - Objective with gapfill database:86.04689764726454; min objective:0.01
2026-01-13 19:34:32,537 - INFO - Objective with gapfill database:86.0468976472672; min objective:0.01
2026-01-13 19:34:32,617 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn00300_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02185_c0': '<', 'rxn16573_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn46124_c0': '>', 'rxn11251_c0': '>', 'rxn04551_c0': '>', 'rxn10095_c0': '>', 'rxn47493_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:32,621 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:32,623 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:34:32,624 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:32,627 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:32,629 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:32,630 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:34:32,632 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:32,634 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:32,636 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:32,638 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:34:32,639 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:34:32,641 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:34:32,643 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:34:32,644 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:34:32,646 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:34:32,648 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:32,649 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:34:32,650 - INFO - Full solution: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn03086_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn08710_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn08711_c0', 'rxn00137_c0', 'rxn04139_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02303_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn08619_c0', 'rxn01603_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn30685_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:32,677 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:32,679 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,681 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:32,684 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:-1.986295775167221e-12 with min obj:0.01
2026-01-13 19:34:32,686 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,688 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,690 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,692 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,694 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,696 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,698 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,700 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,702 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,704 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,705 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,707 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,709 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,711 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,713 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,715 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:32,717 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,719 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:32,721 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,723 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,725 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,727 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,728 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,730 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,733 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,735 - INFO - PyruateMinimalAnaerobic/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,737 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,739 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:3.828799659639731e-12 with min obj:0.01
2026-01-13 19:34:32,741 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:32,743 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:32,745 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,747 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,749 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,751 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,753 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,755 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,757 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,759 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,761 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,763 - INFO - PyruateMinimalAnaerobic/bio1:rxn01603_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,765 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,767 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,769 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,771 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,773 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,775 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,777 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,779 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,782 - INFO - PyruateMinimalAnaerobic/bio1:rxn30685_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,786 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,788 - INFO - PyruateMinimalAnaerobic/bio1:rxn15939_c0> needed:4.61320055296585e-13 with min obj:0.01
2026-01-13 19:34:32,790 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,792 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:32,793 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:32,794 - INFO -   Running ATP safety check...

c0

2026-01-13 19:34:33,083 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn02504_c0': '>', 'rxn03436_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn14424_c0': '>', 'rxn12932_c0': '>', 'rxn12939_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12942_c0': '>', 'rxn30633_c0': '>', 'rxn15091_c0': '>', 'rxn29919_c0': '>', 'rxn30685_c0': '>', 'rxn10095_c0': '>', 'rxn13321_c0': '>', 'rxn29260_c0': '>', 'rxn47493_c0': '>', 'rxn08473_c0': '>', 'rxn14423_c0': '>', 'rxn11382_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:33,087 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:33,089 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:34:33,091 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:33,093 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:33,095 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:33,097 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:34:33,099 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:33,101 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:33,103 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:33,105 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:33,107 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:33,108 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:34:33,109 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:33,111 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:33,113 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:34:33,115 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:34:33,116 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:34:33,118 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:34:33,120 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:34:33,121 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:34:33,123 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:34:33,124 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:34:33,126 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:34:33,128 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:34:33,130 - INFO - integrating rxn: rxn30633_c0
2026-01-13 19:34:33,131 - INFO - integrating rxn: rxn15091_c0
2026-01-13 19:34:33,133 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:34:33,134 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:33,136 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:34:33,138 - INFO - integrating rxn: rxn13321_c0
2026-01-13 19:34:33,139 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:34:33,141 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:33,142 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:34:33,144 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:34:33,145 - INFO - integrating rxn: rxn11382_c0
2026-01-13 19:34:33,146 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn08710_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn01505_c0', 'rxn03919_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn06848_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn05463_c0', 'rxn05645_c0', 'rxn04413_c0', 'rxn00832_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn03917_c0', 'rxn03893_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn40674_c0', 'rxn43975_c0', 'rxn42732_c0', 'rxn41263_c0', 'rxn20839_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn15091_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn13321_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn11382_c0', '>', 'new']]
2026-01-13 19:34:33,174 - INFO - EX_cpd00393_e0< not needed:16.418996989809436
2026-01-13 19:34:33,175 - INFO - EX_cpd00119_e0< not needed:16.418996989809436
2026-01-13 19:34:33,177 - INFO - EX_cpd00220_e0< not needed:16.418996989809436
2026-01-13 19:34:33,180 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:33,182 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,184 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,186 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,188 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,190 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,191 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,193 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,195 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,198 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,199 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,201 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,203 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,205 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,207 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,209 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,211 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,212 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,214 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:33,216 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:33,218 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,220 - INFO - PyruateMinimalAnaerobic/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,224 - INFO - rxn05645_c0> not needed:16.418996989809347
2026-01-13 19:34:33,227 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,231 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:6.434482462309939e-13 with min obj:0.01
2026-01-13 19:34:33,233 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,237 - INFO - rxn05299_c0> not needed:16.418996989809454
2026-01-13 19:34:33,240 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,242 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,244 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,247 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:-7.151297765980808e-13 with min obj:0.01
2026-01-13 19:34:33,249 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:-8.928130278552149e-13 with min obj:0.01
2026-01-13 19:34:33,251 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:33,253 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,255 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,256 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,258 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,260 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,264 - INFO - rxn05255_c0> not needed:16.418996989809365
2026-01-13 19:34:33,267 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,269 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,271 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,273 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,275 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,277 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,279 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,281 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,283 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,286 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,288 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,289 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,291 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,293 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,295 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,297 - INFO - PyruateMinimalAnaerobic/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,299 - INFO - PyruateMinimalAnaerobic/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,301 - INFO - PyruateMinimalAnaerobic/bio1:rxn41263_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,302 - INFO - PyruateMinimalAnaerobic/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:33,303 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:33,304 - INFO -   Running ATP safety check...

c0

2026-01-13 19:34:33,710 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,731 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,744 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,756 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,769 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,781 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,794 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,806 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,819 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,829 - INFO - cpd00221 not found in model!
2026-01-13 19:34:33,830 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:33,833 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,846 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,859 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,876 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,889 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,902 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,914 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,927 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,940 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,952 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,965 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,976 - INFO - cpd00221 not found in model!
2026-01-13 19:34:33,977 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:33,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:33,992 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,005 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,017 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,031 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,059 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,071 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,084 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,098 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,110 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,124 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,136 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,153 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,167 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,179 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,192 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,204 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,229 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,242 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,255 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,268 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:34,280 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,293 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,305 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,316 - INFO - cpd11632 not found in model!
2026-01-13 19:34:34,317 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:34,320 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,330 - INFO - cpd08701 not found in model!
2026-01-13 19:34:34,331 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:34,332 - INFO - cpd01024 not found in model!
2026-01-13 19:34:34,333 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:34,336 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,346 - INFO - cpd01024 not found in model!
2026-01-13 19:34:34,347 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:34,350 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,362 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,375 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,385 - INFO - cpd00187 not found in model!
2026-01-13 19:34:34,386 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:34,389 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,401 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,413 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:34,645 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,658 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,666 - INFO - cpd00363 not found in model!
2026-01-13 19:34:34,668 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:34,671 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,681 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,691 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,701 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,702 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,710 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,719 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,720 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,728 - INFO - cpd00159 not found in model!
2026-01-13 19:34:34,729 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:34,731 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,732 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,739 - INFO - cpd00221 not found in model!
2026-01-13 19:34:34,740 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:34,743 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,745 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,752 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,758 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,762 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,770 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,771 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,779 - INFO - cpd00363 not found in model!
2026-01-13 19:34:34,780 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:34,782 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,782 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,791 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,795 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,801 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,807 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,810 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,820 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,820 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,830 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,833 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,837 - INFO - cpd00159 not found in model!
2026-01-13 19:34:34,838 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:34,840 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,845 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,848 - INFO - cpd00221 not found in model!
2026-01-13 19:34:34,849 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:34,852 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,857 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,861 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,869 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,870 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,878 - INFO - cpd00075 not found in model!
2026-01-13 19:34:34,879 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:34,881 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,882 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,889 - INFO - cpd00209 not found in model!
2026-01-13 19:34:34,889 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:34,892 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,894 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,900 - INFO - cpd00418 not found in model!
2026-01-13 19:34:34,901 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:34,903 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,906 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,911 - INFO - cpd00075 not found in model!
2026-01-13 19:34:34,912 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:34,914 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,919 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,922 - INFO - cpd00209 not found in model!
2026-01-13 19:34:34,922 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:34,925 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,931 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,932 - INFO - cpd00418 not found in model!
2026-01-13 19:34:34,933 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:34,935 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,943 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,943 - INFO - cpd00075 not found in model!
2026-01-13 19:34:34,944 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:34:34,947 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,954 - INFO - cpd00209 not found in model!
2026-01-13 19:34:34,955 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,955 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:34,958 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,966 - INFO - cpd00418 not found in model!
2026-01-13 19:34:34,967 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:34,967 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,969 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,977 - INFO - cpd08021 not found in model!
2026-01-13 19:34:34,978 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:34,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,988 - INFO - cpd00811 not found in model!
2026-01-13 19:34:34,988 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:34,991 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,992 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:34,999 - INFO - cpd08021 not found in model!
2026-01-13 19:34:34,999 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:35,002 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,004 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,010 - INFO - cpd00811 not found in model!
2026-01-13 19:34:35,011 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:35,013 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,016 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,023 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,028 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,032 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,040 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,042 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,051 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,052 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,060 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,064 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,068 - INFO - cpd00159 not found in model!
2026-01-13 19:34:35,069 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:35,072 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,077 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,082 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,089 - INFO - cpd00159 not found in model!
2026-01-13 19:34:35,091 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:35,093 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,099 - INFO - cpd08021 not found in model!
2026-01-13 19:34:35,100 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:35,103 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,103 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,114 - INFO - cpd00811 not found in model!
2026-01-13 19:34:35,115 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:35,118 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,122 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,128 - INFO - cpd08021 not found in model!
2026-01-13 19:34:35,128 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:35,129 - INFO - cpd11632 not found in model!
2026-01-13 19:34:35,130 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:35,131 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,133 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,140 - INFO - cpd08701 not found in model!
2026-01-13 19:34:35,141 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:35,141 - INFO - cpd01024 not found in model!
2026-01-13 19:34:35,141 - INFO - cpd00811 not found in model!
2026-01-13 19:34:35,142 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:35,142 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:35,145 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,145 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,153 - INFO - cpd01024 not found in model!
2026-01-13 19:34:35,153 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:35,156 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,158 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,165 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,170 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,175 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,182 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,183 - INFO - cpd00187 not found in model!
2026-01-13 19:34:35,184 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:35,187 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,194 - INFO - cpd00425 not found in model!
2026-01-13 19:34:35,194 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,195 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:35,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,206 - INFO - cpd00441 not found in model!
2026-01-13 19:34:35,206 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:35,207 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,209 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,220 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,232 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,245 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,259 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,272 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,283 - INFO - cpd11632 not found in model!
2026-01-13 19:34:35,284 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:35,287 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,297 - INFO - cpd08701 not found in model!
2026-01-13 19:34:35,298 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:35,299 - INFO - cpd01024 not found in model!
2026-01-13 19:34:35,300 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:35,304 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,314 - INFO - cpd01024 not found in model!
2026-01-13 19:34:35,315 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:35,318 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,330 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,353 - INFO - cpd00187 not found in model!
2026-01-13 19:34:35,353 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:35,356 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:35,366 - INFO - cpd00425 not found in model!

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:37,099 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:37,123 - INFO - Objective with gapfill database:28.75; min objective:0.01
2026-01-13 19:34:37,161 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:34:37,583 - INFO -   Saved gapfilled model: gapfilled_models2/Chryseobacterium.1_gf.xml
2026-01-13 19:34:37,585 - INFO -   Total reactions added: 284

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:37,694 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:37,758 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:38,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,186 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:38,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,211 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,214 - INFO -   Saved gapfilled model: gapfilled_models2/Colidextribacter.5_gf.xml
2026-01-13 19:34:38,216 - INFO -   Total reactions added: 286
2026-01-13 19:34:38,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,238 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,251 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,265 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,278 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,291 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,304 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:38,317 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,330 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,346 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,359 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,373 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,386 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,399 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,401 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:34:38,414 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,427 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,441 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,455 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,468 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,481 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,495 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,508 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,520 - INFO - cpd00418 not found in model!
2026-01-13 19:34:38,521 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:38,524 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,538 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,551 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,562 - INFO - cpd00418 not found in model!
2026-01-13 19:34:38,563 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:38,567 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,580 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,594 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,605 - INFO - cpd00418 not found in model!
2026-01-13 19:34:38,606 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:38,609 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,621 - INFO - cpd08021 not found in model!
2026-01-13 19:34:38,621 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:38,625 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,639 - INFO - cpd00811 not found in model!
2026-01-13 19:34:38,640 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:38,644 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,655 - INFO - cpd08021 not found in model!
2026-01-13 19:34:38,655 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:38,659 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,670 - INFO - cpd00811 not found in model!
2026-01-13 19:34:38,671 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:38,674 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,687 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,700 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,714 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,729 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,742 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,756 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,778 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,792 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,805 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,819 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,830 - INFO - cpd11632 not found in model!
2026-01-13 19:34:38,831 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:38,835 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:38,846 - INFO - cpd08701 not found in model!
2026-01-13 19:34:38,846 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:38,847 - INFO - cpd01024 not found in model!
2026-01-13 19:34:38,848 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:38,851 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,857 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:38,863 - INFO - cpd01024 not found in model!
2026-01-13 19:34:38,863 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:38,867 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,880 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,893 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,905 - INFO - cpd00187 not found in model!
2026-01-13 19:34:38,905 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:38,909 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,922 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:38,935 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:39,191 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:39,365 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:39,673 - INFO -   Saved gapfilled model: gapfilled_models2/Desulfobacca.1_gf.xml
2026-01-13 19:34:39,675 - INFO -   Total reactions added: 250
2026-01-13 19:34:39,855 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:34:39,855 - INFO -   Saved gapfilled model: gapfilled_models2/Clostridium_sensu_stricto_1.2_gf.xml
2026-01-13 19:34:39,857 - INFO -   Total reactions added: 276
2026-01-13 19:34:40,034 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:40,297 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:40,457 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:45,792 - INFO - Objective with gapfill database:110.04288695302905; min objective:0.01
2026-01-13 19:34:48,096 - INFO - Objective with gapfill database:110.04288695302905; min objective:0.01
2026-01-13 19:34:48,656 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn03436_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn02185_c0': '<', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn25743_c0': '>', 'rxn16503_c0': '>', 'rxn16511_c0': '>', 'rxn04551_c0': '>', 'rxn16114_c0': '>', 'rxn16671_c0': '>', 'rxn15940_c0': '>', 'rxn16341_c0': '>', 'rxn27266_c0': '>', 'rxn41399_c0': '>', 'rxn41401_c0': '>', 'rxn15776_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:48,660 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:48,662 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:48,664 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:48,666 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:48,668 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:34:48,670 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:48,672 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:48,674 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:48,676 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:48,677 - INFO - integrating rxn: rxn16503_c0
2026-01-13 19:34:48,679 - INFO - integrating rxn: rxn16511_c0
2026-01-13 19:34:48,680 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:34:48,682 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:34:48,684 - INFO - integrating rxn: rxn16671_c0
2026-01-13 19:34:48,686 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:34:48,687 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:34:48,689 - INFO - integrating rxn: rxn27266_c0
2026-01-13 19:34:48,691 - INFO - integrating rxn: rxn41399_c0
2026-01-13 19:34:48,692 - INFO - integrating rxn: rxn41401_c0
2026-01-13 19:34:48,694 - INFO - integrating rxn: rxn15776_c0
2026-01-13 19:34:48,694 - INFO - Full solution: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn40324_c0', '>', 'new'], ['rxn20839_c0', '>', 'new'], 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn08954_c0', 'rxn08618_c0', 'rxn03397_c0', 'rxn03537_c0', 'rxn03916_c0', 'rxn05463_c0', 'rxn04413_c0', 'rxn10094_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn01603_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn19728_c0', 'rxn20235_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn30685_c0', 'rxn40674_c0', 'rxn40324_c0', 'rxn20839_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn16503_c0', '>', 'new'], ['rxn16511_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn16671_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn27266_c0', '>', 'new'], ['rxn41399_c0', '>', 'new'], ['rxn41401_c0', '>', 'new'], ['rxn15776_c0', '>', 'new']]
2026-01-13 19:34:48,738 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:48,741 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,747 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,749 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,751 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,753 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,755 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,757 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,760 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,762 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,764 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,766 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,768 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,770 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,772 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,774 - INFO - PyruateMinimalAnaerobic/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,776 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,778 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,780 - INFO - PyruateMinimalAnaerobic/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,782 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,784 - INFO - PyruateMinimalAnaerobic/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,786 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,788 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,790 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:48,792 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,794 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,795 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,797 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,799 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,801 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,803 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,805 - INFO - PyruateMinimalAnaerobic/bio1:rxn01603_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,807 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,809 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,811 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,813 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,815 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,819 - INFO - rxn19728_c0> not needed:9.72930460269082
2026-01-13 19:34:48,820 - INFO - rxn20235_c0> not needed:9.729304602690755
2026-01-13 19:34:48,823 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,824 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,826 - INFO - PyruateMinimalAnaerobic/bio1:rxn30685_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,829 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:48,832 - INFO - rxn40324_c0> not needed:9.729304602690906
2026-01-13 19:34:48,834 - INFO - rxn20839_c0> not needed:9.729304602690824
2026-01-13 19:34:48,834 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:48,835 - INFO -   Running ATP safety check...

c0

2026-01-13 19:34:49,484 - INFO - Objective with gapfill database:94.56987442287178; min objective:0.01
2026-01-13 19:34:50,835 - INFO - Objective with gapfill database:86.04689764726682; min objective:0.01
2026-01-13 19:34:51,729 - INFO - Objective with gapfill database:94.56987442287178; min objective:0.01
2026-01-13 19:34:51,921 - INFO - Objective with gapfill database:78.30267685901303; min objective:0.01
2026-01-13 19:34:52,257 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn03436_c0': '>', 'rxn02160_c0': '>', 'rxn01301_c0': '<', 'rxn01637_c0': '<', 'rxn02835_c0': '>', 'rxn01256_c0': '>', 'rxn00503_c0': '<', 'rxn01000_c0': '>', 'rxn12376_c0': '<', 'rxn02508_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn02185_c0': '<', 'rxn02473_c0': '>', 'rxn02507_c0': '>', 'rxn01603_c0': '>', 'rxn22816_c0': '>', 'rxn16218_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn16217_c0': '>', 'rxn11274_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn06090_c0': '>', 'rxn07254_c0': '>', 'rxn11251_c0': '>', 'rxn04551_c0': '>', 'rxn14178_c0': '>', 'rxn30685_c0': '>', 'rxn20627_c0': '>', 'rxn15939_c0': '>', 'rxn08921_c0': '>', 'rxn08989_c0': '>', 'rxn47493_c0': '>', 'rxn11382_c0': '>', 'rxn10120_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:52,261 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:52,262 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:52,264 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:34:52,266 - INFO - integrating rxn: rxn01301_c0
2026-01-13 19:34:52,267 - INFO - integrating rxn: rxn01637_c0
2026-01-13 19:34:52,269 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:34:52,271 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:34:52,273 - INFO - integrating rxn: rxn00503_c0
2026-01-13 19:34:52,274 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:34:52,276 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:52,278 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:34:52,280 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:52,281 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:34:52,283 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:52,284 - INFO - integrating rxn: rxn02473_c0
2026-01-13 19:34:52,286 - INFO - integrating rxn: rxn02507_c0
2026-01-13 19:34:52,288 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:52,290 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:52,291 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:34:52,293 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:52,295 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:52,296 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:52,299 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:52,301 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:34:52,302 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:34:52,304 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:34:52,306 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:34:52,307 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:34:52,309 - INFO - integrating rxn: rxn06090_c0
2026-01-13 19:34:52,311 - INFO - integrating rxn: rxn07254_c0
2026-01-13 19:34:52,313 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:34:52,314 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:34:52,316 - INFO - integrating rxn: rxn14178_c0
2026-01-13 19:34:52,317 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:52,319 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:34:52,321 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:34:52,323 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:34:52,325 - INFO - integrating rxn: rxn08989_c0
2026-01-13 19:34:52,327 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:34:52,328 - INFO - integrating rxn: rxn11382_c0
2026-01-13 19:34:52,330 - INFO - integrating rxn: rxn10120_c0
2026-01-13 19:34:52,331 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn10094_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn09149_c0', '<', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'rxn00800_c0', 'rxn10336_c0', 'rxn12512_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn00392_c0', 'rxn02774_c0', 'rxn01505_c0', 'rxn00916_c0', 'rxn08618_c0', 'rxn03397_c0', 'rxn03537_c0', 'rxn03916_c0', 'rxn05463_c0', 'rxn05645_c0', 'rxn04413_c0', 'rxn00832_c0', 'rxn10094_c0', 'rxn03087_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn03084_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02341_c0', 'rxn09149_c0', 'rxn00293_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn02160_c0', '>', 'new'], ['rxn01301_c0', '<', 'new'], ['rxn01637_c0', '<', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00503_c0', '<', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn02473_c0', '>', 'new'], ['rxn02507_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn06090_c0', '>', 'new'], ['rxn07254_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn14178_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn08989_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn11382_c0', '>', 'new'], ['rxn10120_c0', '>', 'new']]
2026-01-13 19:34:52,372 - INFO - EX_cpd00393_e0< not needed:3.5947017500864953
2026-01-13 19:34:52,374 - INFO - EX_cpd00220_e0< not needed:3.5947017500864953
2026-01-13 19:34:52,379 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:52,383 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:1.6085482307626332e-13 with min obj:0.01
2026-01-13 19:34:52,385 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,388 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,390 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,392 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,394 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,396 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,398 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,400 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,402 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,404 - INFO - PyruateMinimalAnaerobic/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,406 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,408 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,411 - INFO - PyruateMinimalAnaerobic/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,415 - INFO - rxn05645_c0> not needed:3.5947017500864837
2026-01-13 19:34:52,420 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,423 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:52,426 - INFO - PyruateMinimalAnaerobic/bio1:rxn10094_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,428 - INFO - PyruateMinimalAnaerobic/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:52,430 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,432 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,434 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,436 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,438 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:52,440 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,442 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,444 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,448 - INFO - rxn05255_c0> not needed:3.594701750086485
2026-01-13 19:34:52,452 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,454 - INFO - PyruateMinimalAnaerobic/bio1:rxn09149_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:52,456 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,458 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,459 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,462 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,464 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,466 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,468 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,470 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,472 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,474 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,476 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,480 - INFO - rxn15940_c0> not needed:3.5947017500864815
2026-01-13 19:34:52,486 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,488 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:52,489 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:52,489 - INFO -   Running ATP safety check...

c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:52,851 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:52,878 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:52,892 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:52,906 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:52,919 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:52,933 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:52,946 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:52,959 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:52,973 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:52,986 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,000 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,013 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,030 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,044 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,057 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,070 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,084 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,098 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,112 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,125 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:53,138 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,142 - INFO - Objective with gapfill database:86.04689764726682; min objective:0.01
2026-01-13 19:34:53,147 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:53,152 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,165 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,178 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,191 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,203 - INFO - cpd00418 not found in model!
2026-01-13 19:34:53,204 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:53,207 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,222 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,235 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,247 - INFO - cpd00418 not found in model!
2026-01-13 19:34:53,248 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:53,251 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,266 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,280 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,292 - INFO - cpd00418 not found in model!
2026-01-13 19:34:53,293 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:53,296 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,310 - INFO - cpd08021 not found in model!
2026-01-13 19:34:53,310 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:53,314 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,326 - INFO - cpd00811 not found in model!
2026-01-13 19:34:53,327 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:53,330 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,342 - INFO - cpd08021 not found in model!
2026-01-13 19:34:53,343 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:53,348 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,366 - INFO - cpd00811 not found in model!
2026-01-13 19:34:53,367 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:53,371 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:53,386 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,400 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,414 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,458 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,472 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,485 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,499 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,512 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,523 - INFO - cpd11632 not found in model!
2026-01-13 19:34:53,524 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:53,528 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,540 - INFO - cpd08701 not found in model!
2026-01-13 19:34:53,540 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:53,542 - INFO - cpd01024 not found in model!
2026-01-13 19:34:53,542 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:53,545 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,557 - INFO - cpd01024 not found in model!
2026-01-13 19:34:53,558 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:53,561 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,575 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,588 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,601 - INFO - cpd00187 not found in model!
2026-01-13 19:34:53,602 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:53,605 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,619 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,633 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,664 - INFO -   Saved gapfilled model: gapfilled_models2/Clostridium_sensu_stricto_13.3_gf.xml
2026-01-13 19:34:53,666 - INFO -   Total reactions added: 270
2026-01-13 19:34:53,677 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn00300_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02185_c0': '<', 'rxn16573_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn30633_c0': '>', 'rxn16114_c0': '>', 'rxn20508_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:53,681 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:53,683 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:34:53,686 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:53,688 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:53,690 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:53,692 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:34:53,694 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:34:53,696 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:53,698 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:53,700 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:34:53,702 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:34:53,703 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:34:53,705 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:34:53,707 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:34:53,709 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:34:53,710 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:34:53,712 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:34:53,714 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:34:53,716 - INFO - integrating rxn: rxn30633_c0
2026-01-13 19:34:53,717 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:34:53,719 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:34:53,720 - INFO - Full solution: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn08710_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn08711_c0', 'rxn04139_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn02303_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn03439_c0', 'rxn00122_c0', 'rxn08620_c0', 'rxn04308_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn08619_c0', 'rxn01603_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn30685_c0', 'rxn30917_c0', 'rxn15939_c0', 'rxn40674_c0', 'rxn09037_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn20508_c0', '>', 'new']]
2026-01-13 19:34:53,747 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:53,749 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,751 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:1.1052239877073486e-12 with min obj:0.01
2026-01-13 19:34:53,753 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,755 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,757 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:53,759 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,761 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,763 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,765 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,767 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,769 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,770 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,772 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,774 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,776 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,778 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,781 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,783 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,784 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,786 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:53,788 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,790 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,792 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,794 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,796 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,798 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,800 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,801 - INFO - PyruateMinimalAnaerobic/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,803 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,806 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:-1.2086020240148133e-13 with min obj:0.01
2026-01-13 19:34:53,808 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:53,810 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,812 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,813 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,816 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,818 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,820 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,822 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,823 - INFO - PyruateMinimalAnaerobic/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,826 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,827 - INFO - PyruateMinimalAnaerobic/bio1:rxn01603_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,829 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,831 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,833 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,835 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,837 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,839 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:53,841 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01

2026-01-13 19:34:53,843 - INFO - PyruateMinimalAnaerobic/bio1:rxn30685_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,847 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:9.4708608689255e-12 with min obj:0.01
2026-01-13 19:34:53,849 - INFO - PyruateMinimalAnaerobic/bio1:rxn15939_c0> needed:-5.091955290341816e-13 with min obj:0.01
2026-01-13 19:34:53,851 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,852 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:34:53,853 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:53,854 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:53,855 - INFO -   Running ATP safety check...

c0

2026-01-13 19:34:53,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:53,997 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,005 - INFO - cpd00363 not found in model!
2026-01-13 19:34:54,006 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:54,009 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,018 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,028 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,037 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,055 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,063 - INFO - cpd00159 not found in model!
2026-01-13 19:34:54,064 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:54,067 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,076 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,085 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,094 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,103 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,110 - INFO - cpd00363 not found in model!
2026-01-13 19:34:54,111 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:34:54,114 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,123 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,132 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,141 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,150 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,159 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,166 - INFO - cpd00159 not found in model!
2026-01-13 19:34:54,167 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:54,170 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,179 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,180 - INFO - Objective with gapfill database:78.30267685901303; min objective:0.01
2026-01-13 19:34:54,188 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,197 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,207 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,216 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,223 - INFO - cpd00418 not found in model!
2026-01-13 19:34:54,224 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:54,227 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,236 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,245 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,253 - INFO - cpd00418 not found in model!
2026-01-13 19:34:54,254 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:54,256 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,265 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,274 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:54,282 - INFO - cpd00418 not found in model!
2026-01-13 19:34:54,283 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:34:54,285 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,290 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:54,292 - INFO - cpd08021 not found in model!
2026-01-13 19:34:54,293 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:54,296 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,304 - INFO - cpd00811 not found in model!
2026-01-13 19:34:54,305 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:54,307 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,314 - INFO - cpd08021 not found in model!
2026-01-13 19:34:54,315 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:54,318 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,325 - INFO - cpd00811 not found in model!
2026-01-13 19:34:54,325 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:54,328 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,337 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,346 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,353 - INFO - cpd11640 not found in model!
2026-01-13 19:34:54,354 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:54,356 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,364 - INFO - cpd11640 not found in model!
2026-01-13 19:34:54,365 - INFO - Media compound: cpd11640 not found in model.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:54,367 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,374 - INFO - cpd11640 not found in model!
2026-01-13 19:34:54,375 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:54,377 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,385 - INFO - cpd00159 not found in model!
2026-01-13 19:34:54,385 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:34:54,386 - INFO - cpd11640 not found in model!
2026-01-13 19:34:54,387 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:54,389 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,398 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:54,405 - INFO - cpd00159 not found in model!
2026-01-13 19:34:54,405 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0
2026-01-13 19:34:54,406 - INFO - Media compound: cpd00159 not found in model.

Removing ungapfillable media Ac.O2

2026-01-13 19:34:54,409 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,416 - INFO - cpd11640 not found in model!
2026-01-13 19:34:54,417 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:54,419 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,422 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:34:54,428 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,436 - INFO - cpd11632 not found in model!
2026-01-13 19:34:54,436 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:54,439 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,440 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:34:54,446 - INFO - cpd08701 not found in model!
2026-01-13 19:34:54,447 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:54,447 - INFO - cpd01024 not found in model!
2026-01-13 19:34:54,448 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:54,450 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,456 - INFO - Objective with gapfill database:15.5; min objective:0.01
2026-01-13 19:34:54,457 - INFO - cpd01024 not found in model!
2026-01-13 19:34:54,458 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:54,460 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,469 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,471 - INFO - Objective with gapfill database:17.125; min objective:0.01
2026-01-13 19:34:54,476 - INFO - cpd11640 not found in model!
2026-01-13 19:34:54,477 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:54,479 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,485 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:34:54,487 - INFO - cpd11640 not found in model!
2026-01-13 19:34:54,487 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:54,488 - INFO - cpd00187 not found in model!
2026-01-13 19:34:54,489 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:54,491 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,498 - INFO - cpd11640 not found in model!
2026-01-13 19:34:54,499 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:54,499 - INFO - cpd00425 not found in model!
2026-01-13 19:34:54,500 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:54,502 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,510 - INFO - cpd11640 not found in model!
2026-01-13 19:34:54,510 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:54,511 - INFO - cpd00441 not found in model!
2026-01-13 19:34:54,512 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:54,515 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:54,688 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn03436_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn22816_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn40142_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn17394_c0': '>', 'rxn15081_c0': '>', 'rxn30685_c0': '>', 'rxn20508_c0': '>', 'rxn46249_c0': '>', 'rxn40040_c0': '>', 'rxn20472_c0': '>', 'rxn08473_c0': '>', 'rxn14050_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:34:54,692 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:34:54,694 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:34:54,696 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:34:54,698 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:34:54,700 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:34:54,702 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:34:54,704 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:34:54,706 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:34:54,708 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:34:54,709 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:34:54,711 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:34:54,713 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:34:54,715 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:34:54,716 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:34:54,718 - INFO - integrating rxn: rxn40142_c0
2026-01-13 19:34:54,720 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:34:54,722 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:34:54,723 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:34:54,725 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:34:54,726 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:34:54,728 - INFO - integrating rxn: rxn17394_c0
2026-01-13 19:34:54,730 - INFO - integrating rxn: rxn15081_c0
2026-01-13 19:34:54,731 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:34:54,733 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:34:54,734 - INFO - integrating rxn: rxn46249_c0
2026-01-13 19:34:54,736 - INFO - integrating rxn: rxn40040_c0
2026-01-13 19:34:54,738 - INFO - integrating rxn: rxn20472_c0
2026-01-13 19:34:54,739 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:34:54,741 - INFO - integrating rxn: rxn14050_c0
2026-01-13 19:34:54,743 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:34:54,744 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:34:54,746 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:34:54,748 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:34:54,749 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn10213_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08618_c0', 'rxn03537_c0', 'rxn05463_c0', 'rxn05645_c0', 'rxn00832_c0', 'rxn01537_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn03638_c0', 'rxn02056_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn40674_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn17394_c0', '>', 'new'], ['rxn15081_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn20472_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn14050_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:34:54,782 - INFO - EX_cpd00393_e0< not needed:23.235369770282716
2026-01-13 19:34:54,784 - INFO - EX_cpd00220_e0< not needed:23.235369770282716
2026-01-13 19:34:54,788 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:34:54,790 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,793 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:-2.2593716142700425e-12 with min obj:0.01
2026-01-13 19:34:54,796 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,798 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:9.363780821610684e-13 with min obj:0.01
2026-01-13 19:34:54,800 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,802 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,804 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,806 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,808 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,810 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,812 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,814 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,816 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,818 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,820 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,822 - INFO - PyruateMinimalAnaerobic/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,827 - INFO - rxn05645_c0> not needed:23.235369770282674
2026-01-13 19:34:54,832 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:54,837 - INFO - rxn01537_c0> not needed:23.23536977028259
2026-01-13 19:34:54,841 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,845 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,848 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,850 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,852 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:34:54,854 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,856 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,858 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,860 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,866 - INFO - rxn05255_c0> not needed:23.23536977028261
2026-01-13 19:34:54,870 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,872 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,874 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,876 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,878 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,881 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,883 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,885 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,887 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,889 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,896 - INFO - rxn14070_c0> not needed:23.235369770282517
2026-01-13 19:34:54,901 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:34:54,901 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:34:54,902 - INFO -   Running ATP safety check...

c0
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:56,067 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:34:56,082 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:34:56,097 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:34:56,111 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:56,585 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:56,606 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,628 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,643 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,659 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,674 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,704 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,719 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,734 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,750 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,765 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,781 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,796 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,811 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,826 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,841 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,857 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,872 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,888 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,903 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,918 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,934 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,949 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,964 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:56,977 - INFO - cpd00209 not found in model!
2026-01-13 19:34:56,978 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:56,982 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,001 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,017 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,029 - INFO - cpd00209 not found in model!
2026-01-13 19:34:57,030 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:57,034 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,049 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,064 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,076 - INFO - cpd00209 not found in model!
2026-01-13 19:34:57,077 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:34:57,081 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,088 - INFO -   Saved gapfilled model: gapfilled_models2/Ca_Competibacter.1_gf.xml
2026-01-13 19:34:57,089 - INFO -   Total reactions added: 246
2026-01-13 19:34:57,096 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:57,110 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,125 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,155 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,170 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,199 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,214 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,229 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,244 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,259 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,270 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:34:57,274 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,289 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,304 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,317 - INFO - cpd11632 not found in model!
2026-01-13 19:34:57,318 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:57,321 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,333 - INFO - cpd08701 not found in model!
2026-01-13 19:34:57,334 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:57,336 - INFO - cpd01024 not found in model!
2026-01-13 19:34:57,336 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:57,340 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,352 - INFO - cpd01024 not found in model!
2026-01-13 19:34:57,353 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:57,356 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,371 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,373 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,386 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,398 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,399 - INFO - cpd00187 not found in model!
2026-01-13 19:34:57,400 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:57,403 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,413 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,418 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,433 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,474 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,489 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,503 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,518 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,533 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,549 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,564 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,580 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,595 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,609 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,625 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,641 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,657 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,673 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:57,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,694 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:57,705 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,720 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,737 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,753 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,769 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,785 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,801 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,817 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,833 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,848 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,863 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,876 - INFO - cpd08021 not found in model!
2026-01-13 19:34:57,876 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:57,880 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,892 - INFO - cpd00811 not found in model!
2026-01-13 19:34:57,893 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:57,897 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,909 - INFO - cpd08021 not found in model!
2026-01-13 19:34:57,910 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:57,914 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,926 - INFO - cpd00811 not found in model!
2026-01-13 19:34:57,926 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:57,930 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,945 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,959 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,974 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:57,988 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,017 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:58,031 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,060 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,075 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,087 - INFO - cpd11632 not found in model!
2026-01-13 19:34:58,088 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:58,091 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,103 - INFO - cpd08701 not found in model!
2026-01-13 19:34:58,104 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:58,105 - INFO - cpd01024 not found in model!
2026-01-13 19:34:58,105 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:58,109 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,120 - INFO - cpd01024 not found in model!
2026-01-13 19:34:58,121 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:58,125 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,139 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,153 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,166 - INFO - cpd00187 not found in model!
2026-01-13 19:34:58,166 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:58,170 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,182 - INFO - cpd00425 not found in model!
2026-01-13 19:34:58,182 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:58,182 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,186 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,195 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,198 - INFO - cpd00441 not found in model!
2026-01-13 19:34:58,200 - INFO - Media compound: cpd00441 not found in model.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:58,203 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,206 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,216 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,226 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,237 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,247 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,257 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,267 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,276 - INFO - cpd00221 not found in model!
2026-01-13 19:34:58,276 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:58,279 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,290 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,300 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,310 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,319 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,329 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,340 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,350 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,361 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,371 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,382 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,390 - INFO - cpd00221 not found in model!
2026-01-13 19:34:58,391 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:34:58,394 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,405 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,415 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,425 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,435 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,445 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,455 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,466 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,475 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,485 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,495 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,505 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,513 - INFO - cpd08021 not found in model!
2026-01-13 19:34:58,514 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:58,517 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,525 - INFO - cpd00811 not found in model!
2026-01-13 19:34:58,526 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:58,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,537 - INFO - cpd08021 not found in model!
2026-01-13 19:34:58,538 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:34:58,540 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,548 - INFO - cpd00811 not found in model!
2026-01-13 19:34:58,549 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:34:58,552 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,563 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,573 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,581 - INFO - cpd11640 not found in model!
2026-01-13 19:34:58,582 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:58,585 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,593 - INFO - cpd11640 not found in model!
2026-01-13 19:34:58,594 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:58,597 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,605 - INFO - cpd11640 not found in model!
2026-01-13 19:34:58,606 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:58,609 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,617 - INFO - cpd11640 not found in model!
2026-01-13 19:34:58,618 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:58,621 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,631 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,641 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,649 - INFO - cpd11640 not found in model!
2026-01-13 19:34:58,650 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:58,653 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,663 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,671 - INFO - cpd11632 not found in model!
2026-01-13 19:34:58,672 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:34:58,675 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,684 - INFO - cpd08701 not found in model!
2026-01-13 19:34:58,684 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:34:58,685 - INFO - cpd01024 not found in model!
2026-01-13 19:34:58,686 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:58,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,697 - INFO - cpd01024 not found in model!
2026-01-13 19:34:58,698 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:34:58,700 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,710 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,718 - INFO - cpd11640 not found in model!
2026-01-13 19:34:58,719 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:58,722 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,730 - INFO - cpd11640 not found in model!
2026-01-13 19:34:58,731 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:58,732 - INFO - cpd00187 not found in model!
2026-01-13 19:34:58,732 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:34:58,735 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,743 - INFO - cpd11640 not found in model!
2026-01-13 19:34:58,744 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:58,745 - INFO - cpd00425 not found in model!
2026-01-13 19:34:58,745 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:34:58,748 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:58,756 - INFO - cpd11640 not found in model!
2026-01-13 19:34:58,757 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:34:58,758 - INFO - cpd00441 not found in model!
2026-01-13 19:34:58,758 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:34:58,761 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:34:58,806 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:34:59,334 - INFO -   Saved gapfilled model: gapfilled_models2/AAP99.1_gf.xml
2026-01-13 19:34:59,337 - INFO -   Total reactions added: 234
2026-01-13 19:34:59,527 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:59,770 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,791 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,807 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,822 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,838 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,853 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,869 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,884 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,897 - INFO - cpd00159 not found in model!
2026-01-13 19:34:59,898 - INFO - Media compound: cpd00159 not found in model.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:34:59,902 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 19:34:59,918 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,937 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,952 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:34:59,954 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:34:59,970 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,977 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:34:59,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:34:59,995 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:00,000 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,015 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,031 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,062 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,074 - INFO - cpd00159 not found in model!
2026-01-13 19:35:00,075 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:35:00,079 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,094 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,110 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,125 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,156 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,171 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,187 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,202 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,233 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,248 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,264 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,276 - INFO - cpd08021 not found in model!
2026-01-13 19:35:00,277 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:00,281 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,294 - INFO - cpd00811 not found in model!
2026-01-13 19:35:00,295 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:00,298 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,311 - INFO - cpd08021 not found in model!
2026-01-13 19:35:00,311 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:00,315 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,327 - INFO - cpd00811 not found in model!
2026-01-13 19:35:00,328 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:00,332 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,347 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,362 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,378 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,393 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,409 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,421 - INFO - cpd00159 not found in model!
2026-01-13 19:35:00,422 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:35:00,426 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,441 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,454 - INFO - cpd00159 not found in model!
2026-01-13 19:35:00,455 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:35:00,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,474 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,489 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,501 - INFO - cpd11632 not found in model!
2026-01-13 19:35:00,502 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:00,506 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,520 - INFO - cpd08701 not found in model!
2026-01-13 19:35:00,521 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:00,522 - INFO - cpd01024 not found in model!
2026-01-13 19:35:00,523 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:00,527 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,540 - INFO - cpd01024 not found in model!
2026-01-13 19:35:00,541 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:00,544 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,560 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,575 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,587 - INFO - cpd00187 not found in model!
2026-01-13 19:35:00,588 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:00,592 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,604 - INFO - cpd00425 not found in model!
2026-01-13 19:35:00,605 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:00,609 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:00,621 - INFO - cpd00441 not found in model!
2026-01-13 19:35:00,622 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:00,626 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,002 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,026 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,041 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,056 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,070 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,084 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,099 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,113 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,128 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,142 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,156 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,171 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,200 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,214 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,228 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,243 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,257 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,272 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,286 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,300 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,315 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,329 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,358 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,372 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,387 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,401 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,415 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,443 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,457 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,468 - INFO - cpd08021 not found in model!
2026-01-13 19:35:01,469 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:01,472 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,484 - INFO - cpd00811 not found in model!
2026-01-13 19:35:01,484 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:01,488 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,499 - INFO - cpd08021 not found in model!
2026-01-13 19:35:01,500 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:01,503 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,515 - INFO - cpd00811 not found in model!
2026-01-13 19:35:01,516 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:01,520 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,533 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,548 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,562 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,576 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,590 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,604 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,619 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,633 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,647 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,661 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,673 - INFO - cpd11632 not found in model!
2026-01-13 19:35:01,673 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:01,677 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,689 - INFO - cpd08701 not found in model!
2026-01-13 19:35:01,689 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:01,690 - INFO - cpd01024 not found in model!
2026-01-13 19:35:01,691 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:01,694 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,706 - INFO - cpd01024 not found in model!
2026-01-13 19:35:01,707 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:01,711 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,725 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,739 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,751 - INFO - cpd00187 not found in model!
2026-01-13 19:35:01,752 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:01,755 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,767 - INFO - cpd00425 not found in model!
2026-01-13 19:35:01,768 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:01,771 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:01,783 - INFO - cpd00441 not found in model!
2026-01-13 19:35:01,784 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:01,788 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:01,936 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:02,077 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,098 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,100 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,113 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,113 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,124 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,129 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,134 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,144 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,144 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,154 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,158 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,173 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,175 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,188 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,195 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:02,202 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,205 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,211 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:35:02,215 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,232 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,235 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,246 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,247 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,256 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,261 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,266 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,276 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,276 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,286 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,291 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,296 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,305 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,307 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,315 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,321 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,325 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,335 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,336 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,343 - INFO - cpd00209 not found in model!
2026-01-13 19:35:02,344 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:02,347 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,350 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,355 - INFO - cpd00418 not found in model!
2026-01-13 19:35:02,356 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:35:02,359 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,365 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,369 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,377 - INFO - cpd00209 not found in model!
2026-01-13 19:35:02,378 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:02,379 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,381 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,390 - INFO - cpd00418 not found in model!
2026-01-13 19:35:02,390 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:35:02,394 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,395 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,404 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,410 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,412 - INFO - cpd00209 not found in model!
2026-01-13 19:35:02,413 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:02,416 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,424 - INFO - cpd00418 not found in model!
2026-01-13 19:35:02,425 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,425 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:35:02,428 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,436 - INFO - cpd08021 not found in model!
2026-01-13 19:35:02,437 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:02,440 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,440 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,449 - INFO - cpd00811 not found in model!
2026-01-13 19:35:02,449 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:02,452 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,455 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,460 - INFO - cpd08021 not found in model!
2026-01-13 19:35:02,461 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:02,464 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,470 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,473 - INFO - cpd00811 not found in model!
2026-01-13 19:35:02,473 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:02,476 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,485 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,486 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,496 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,500 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,500 - INFO -   Saved gapfilled model: gapfilled_models2/Ca_Alysiosphaera.2_gf.xml
2026-01-13 19:35:02,503 - INFO -   Total reactions added: 284
2026-01-13 19:35:02,507 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,515 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,517 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,528 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,530 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,538 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,544 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,549 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,556 - INFO - cpd08021 not found in model!
2026-01-13 19:35:02,557 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:02,559 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,561 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,570 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,573 - INFO - cpd00811 not found in model!
2026-01-13 19:35:02,574 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:02,577 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,580 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,589 - INFO - cpd11632 not found in model!
2026-01-13 19:35:02,589 - INFO - cpd08021 not found in model!
2026-01-13 19:35:02,590 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:02,591 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:02,593 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,594 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,602 - INFO - cpd08701 not found in model!
2026-01-13 19:35:02,603 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:02,604 - INFO - cpd01024 not found in model!
2026-01-13 19:35:02,605 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:02,606 - INFO - cpd00811 not found in model!
2026-01-13 19:35:02,607 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:02,608 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,611 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,616 - INFO - cpd01024 not found in model!
2026-01-13 19:35:02,617 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:02,620 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,625 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,631 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,640 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,644 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,653 - INFO - cpd00187 not found in model!
2026-01-13 19:35:02,655 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:02,654 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,658 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,669 - INFO - cpd00425 not found in model!
2026-01-13 19:35:02,670 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:02,670 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,673 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,683 - INFO - cpd00441 not found in model!
2026-01-13 19:35:02,684 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:02,684 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,688 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,699 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,700 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:35:02,714 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:02,729 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:02,744 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,758 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,765 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:35:02,771 - INFO - cpd11632 not found in model!
2026-01-13 19:35:02,772 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:02,774 - INFO -   Saved gapfilled model: gapfilled_models2/Brevundimonas.3_gf.xml
2026-01-13 19:35:02,776 - INFO -   Total reactions added: 210
2026-01-13 19:35:02,776 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,778 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:35:02,783 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:02,790 - INFO - cpd08701 not found in model!
2026-01-13 19:35:02,791 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:02,791 - INFO - cpd01024 not found in model!
2026-01-13 19:35:02,792 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:02,794 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:02,796 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,808 - INFO - cpd01024 not found in model!
2026-01-13 19:35:02,809 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:02,812 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,827 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,842 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,854 - INFO - cpd00187 not found in model!
2026-01-13 19:35:02,855 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:02,858 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,870 - INFO - cpd00425 not found in model!
2026-01-13 19:35:02,871 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:02,875 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:02,887 - INFO - cpd00441 not found in model!
2026-01-13 19:35:02,888 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:02,891 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:02,975 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:35:03,174 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:35:03,424 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:35:03,447 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,448 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:35:03,463 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,480 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,495 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,511 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,527 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,543 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,558 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,574 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,590 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,606 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,622 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,638 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,654 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,669 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,685 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,701 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,717 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,732 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,748 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,764 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,779 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,794 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,810 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,826 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,842 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,858 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,873 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,889 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,905 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,920 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,934 - INFO - cpd08021 not found in model!
2026-01-13 19:35:03,935 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:03,938 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,951 - INFO - cpd00811 not found in model!
2026-01-13 19:35:03,952 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:03,955 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,968 - INFO - cpd08021 not found in model!
2026-01-13 19:35:03,968 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:03,972 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:03,988 - INFO - cpd00811 not found in model!
2026-01-13 19:35:03,989 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:03,994 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,011 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,027 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,043 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,058 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,074 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,090 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,105 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,121 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,136 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,151 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,169 - INFO - cpd11632 not found in model!
2026-01-13 19:35:04,170 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:04,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,187 - INFO - cpd08701 not found in model!
2026-01-13 19:35:04,188 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:04,189 - INFO - cpd01024 not found in model!
2026-01-13 19:35:04,189 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:04,193 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,206 - INFO - cpd01024 not found in model!
2026-01-13 19:35:04,206 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:04,210 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,240 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,255 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,268 - INFO - cpd00425 not found in model!
2026-01-13 19:35:04,269 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:04,273 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:04,285 - INFO - cpd00441 not found in model!
2026-01-13 19:35:04,286 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:04,290 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:04,376 - INFO - Objective with gapfill database:34.50000000000004; min objective:0.01
2026-01-13 19:35:04,416 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:04,745 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:35:05,285 - INFO -   Saved gapfilled model: gapfilled_models2/Dehalobacter.1_gf.xml
2026-01-13 19:35:05,287 - INFO -   Total reactions added: 214
2026-01-13 19:35:05,490 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:35:05,948 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:35:06,815 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,837 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,852 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,866 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,880 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,894 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,908 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,923 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,936 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,950 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,964 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,978 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:06,996 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,010 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,024 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,038 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,051 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,065 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,079 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,093 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,106 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,120 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,134 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,148 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,162 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,176 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,190 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,204 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,218 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,232 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,246 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,260 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,272 - INFO - cpd08021 not found in model!
2026-01-13 19:35:07,273 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:07,277 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,288 - INFO - cpd00811 not found in model!
2026-01-13 19:35:07,289 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:07,292 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,304 - INFO - cpd08021 not found in model!
2026-01-13 19:35:07,304 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:07,308 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,323 - INFO - cpd00811 not found in model!
2026-01-13 19:35:07,324 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:07,328 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,357 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,377 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,396 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,412 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,445 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,462 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,478 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,505 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,519 - INFO - cpd11632 not found in model!
2026-01-13 19:35:07,521 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:07,525 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,541 - INFO - cpd08701 not found in model!
2026-01-13 19:35:07,542 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:07,543 - INFO - cpd01024 not found in model!
2026-01-13 19:35:07,544 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:07,549 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,562 - INFO - cpd01024 not found in model!
2026-01-13 19:35:07,563 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:07,567 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,583 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,607 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,621 - INFO - cpd00187 not found in model!
2026-01-13 19:35:07,623 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:07,627 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,640 - INFO - cpd00425 not found in model!
2026-01-13 19:35:07,642 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:07,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:07,660 - INFO - cpd00441 not found in model!
2026-01-13 19:35:07,661 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:07,665 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:09,824 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,840 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,850 - INFO - cpd00363 not found in model!
2026-01-13 19:35:09,851 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:35:09,854 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,866 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,878 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,889 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,900 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,911 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,921 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,930 - INFO - cpd00221 not found in model!
2026-01-13 19:35:09,932 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:09,935 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,948 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,961 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,974 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:09,984 - INFO - cpd00363 not found in model!
2026-01-13 19:35:09,985 - INFO - Media compound: cpd00363 not found in model.
2026-01-13 19:35:09,989 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,001 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,015 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,028 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,040 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,053 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,066 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,076 - INFO - cpd00221 not found in model!
2026-01-13 19:35:10,077 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:10,081 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,095 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,107 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,120 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,131 - INFO - cpd00209 not found in model!
2026-01-13 19:35:10,132 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:10,136 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,149 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,162 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,172 - INFO - cpd00209 not found in model!
2026-01-13 19:35:10,173 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:10,177 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,190 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,203 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,213 - INFO - cpd00209 not found in model!
2026-01-13 19:35:10,215 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:10,218 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,230 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,239 - INFO - cpd08021 not found in model!
2026-01-13 19:35:10,240 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:10,243 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,253 - INFO - cpd00811 not found in model!
2026-01-13 19:35:10,254 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:10,257 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,267 - INFO - cpd08021 not found in model!
2026-01-13 19:35:10,268 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:10,272 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,282 - INFO - cpd00811 not found in model!
2026-01-13 19:35:10,283 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:10,286 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,299 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,311 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,322 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,333 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,345 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,357 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,370 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,382 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,394 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,406 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,416 - INFO - cpd11632 not found in model!
2026-01-13 19:35:10,417 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:10,420 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,429 - INFO - cpd08701 not found in model!
2026-01-13 19:35:10,430 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:10,432 - INFO - cpd01024 not found in model!
2026-01-13 19:35:10,433 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:10,436 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,445 - INFO - cpd01024 not found in model!
2026-01-13 19:35:10,446 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:10,449 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,460 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,470 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,480 - INFO - cpd00187 not found in model!
2026-01-13 19:35:10,480 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:10,484 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,496 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:10,506 - INFO - cpd00441 not found in model!
2026-01-13 19:35:10,507 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:10,511 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:10,773 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:35:11,365 - INFO -   Saved gapfilled model: gapfilled_models2/Desulfovibrio.3_gf.xml
2026-01-13 19:35:11,367 - INFO -   Total reactions added: 204
2026-01-13 19:35:11,574 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:35:12,082 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:18,128 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,154 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,195 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,215 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,232 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,252 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,269 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,286 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,307 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,328 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,352 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,371 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,389 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,408 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,425 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,443 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,462 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,480 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,497 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,536 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,557 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,580 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,601 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,618 - INFO - cpd00418 not found in model!
2026-01-13 19:35:18,620 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:35:18,625 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,665 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,682 - INFO - cpd00418 not found in model!
2026-01-13 19:35:18,684 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:35:18,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,706 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,727 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,744 - INFO - cpd00418 not found in model!
2026-01-13 19:35:18,745 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:35:18,750 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,769 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,792 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,811 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,829 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,846 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,864 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,881 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,900 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,917 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,934 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,950 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,970 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:18,986 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:19,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:19,017 - INFO - cpd11632 not found in model!
2026-01-13 19:35:19,018 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:19,022 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:19,039 - INFO - cpd08701 not found in model!
2026-01-13 19:35:19,040 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:19,041 - INFO - cpd01024 not found in model!
2026-01-13 19:35:19,042 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:19,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:19,064 - INFO - cpd01024 not found in model!
2026-01-13 19:35:19,065 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:19,071 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:19,092 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:19,114 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:19,135 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:19,150 - INFO - cpd00425 not found in model!
2026-01-13 19:35:19,151 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:19,155 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:19,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:23,926 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:35:23,944 - INFO - Objective with gapfill database:17.499999999999993; min objective:0.01
2026-01-13 19:35:23,959 - INFO - Objective with gapfill database:19.124999999999993; min objective:0.01
2026-01-13 19:35:23,973 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:24,704 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:35:24,719 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:26,449 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,471 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,487 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,503 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,518 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,534 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,550 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,565 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,581 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,597 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,613 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,628 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,644 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,659 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,675 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,690 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,706 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,721 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,737 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,752 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,768 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,784 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,800 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,815 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,831 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,847 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,863 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,878 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,894 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,909 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,925 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,940 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,953 - INFO - cpd08021 not found in model!
2026-01-13 19:35:26,954 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:26,957 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,970 - INFO - cpd00811 not found in model!
2026-01-13 19:35:26,971 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:26,975 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:26,988 - INFO - cpd08021 not found in model!
2026-01-13 19:35:26,989 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:26,992 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,005 - INFO - cpd00811 not found in model!
2026-01-13 19:35:27,006 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:27,009 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,025 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,040 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,055 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,071 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,086 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,102 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,117 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,133 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,149 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,177 - INFO - cpd11632 not found in model!
2026-01-13 19:35:27,178 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:27,182 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,194 - INFO - cpd08701 not found in model!
2026-01-13 19:35:27,195 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:27,196 - INFO - cpd01024 not found in model!
2026-01-13 19:35:27,197 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:27,201 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,214 - INFO - cpd01024 not found in model!
2026-01-13 19:35:27,215 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:27,218 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,234 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,249 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,262 - INFO - cpd00187 not found in model!
2026-01-13 19:35:27,263 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:27,267 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,282 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:27,298 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:28,065 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:35:28,101 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:29,614 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,635 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,651 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,667 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,683 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,699 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,715 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,731 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,747 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,771 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,787 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,803 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,820 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,836 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,852 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,868 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,884 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,900 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,915 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,931 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,947 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,963 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,978 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:29,994 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,010 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,026 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,042 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,058 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,073 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,105 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,121 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,134 - INFO - cpd08021 not found in model!
2026-01-13 19:35:30,135 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:30,139 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,152 - INFO - cpd00811 not found in model!
2026-01-13 19:35:30,152 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:30,156 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,169 - INFO - cpd08021 not found in model!
2026-01-13 19:35:30,170 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:30,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,186 - INFO - cpd00811 not found in model!
2026-01-13 19:35:30,188 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:30,192 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,208 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,224 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,240 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:30,256 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,271 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,287 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,303 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,318 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,334 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,350 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,363 - INFO - cpd11632 not found in model!
2026-01-13 19:35:30,363 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:30,367 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,380 - INFO - cpd08701 not found in model!
2026-01-13 19:35:30,381 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:30,382 - INFO - cpd01024 not found in model!
2026-01-13 19:35:30,383 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:30,386 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,399 - INFO - cpd01024 not found in model!
2026-01-13 19:35:30,400 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:30,403 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,416 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,419 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,430 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,435 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,442 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,448 - INFO - cpd00187 not found in model!
2026-01-13 19:35:30,449 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:30,453 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,453 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,465 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,469 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,476 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,485 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,488 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,499 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,510 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,519 - INFO - cpd00221 not found in model!
2026-01-13 19:35:30,520 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:30,523 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,534 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,545 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,556 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,567 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,578 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,589 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,600 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,611 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,622 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,633 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,642 - INFO - cpd00221 not found in model!
2026-01-13 19:35:30,642 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:30,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,657 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,668 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,679 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,690 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,701 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,711 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,722 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,733 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,744 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,755 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,766 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,775 - INFO - cpd08021 not found in model!
2026-01-13 19:35:30,776 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:30,779 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,788 - INFO - cpd00811 not found in model!
2026-01-13 19:35:30,789 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:30,792 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,801 - INFO - cpd08021 not found in model!
2026-01-13 19:35:30,802 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:30,805 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,814 - INFO - cpd00811 not found in model!
2026-01-13 19:35:30,815 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:30,818 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,829 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,839 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,849 - INFO - cpd11640 not found in model!
2026-01-13 19:35:30,849 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:30,852 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,861 - INFO - cpd11640 not found in model!
2026-01-13 19:35:30,862 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:30,865 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,874 - INFO - cpd11640 not found in model!
2026-01-13 19:35:30,875 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:30,878 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,887 - INFO - cpd11640 not found in model!
2026-01-13 19:35:30,888 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:30,891 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,902 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,913 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,922 - INFO - cpd11640 not found in model!
2026-01-13 19:35:30,923 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:30,926 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,938 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,949 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,958 - INFO - cpd08701 not found in model!
2026-01-13 19:35:30,959 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:30,959 - INFO - cpd01024 not found in model!
2026-01-13 19:35:30,960 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:30,963 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,973 - INFO - cpd01024 not found in model!
2026-01-13 19:35:30,974 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:30,976 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,987 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:30,997 - INFO - cpd11640 not found in model!
2026-01-13 19:35:30,997 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,001 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,010 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,010 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,011 - INFO - cpd00187 not found in model!
2026-01-13 19:35:31,012 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:31,015 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,023 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,024 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,025 - INFO - cpd00425 not found in model!
2026-01-13 19:35:31,026 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:31,029 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:31,038 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,039 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,039 - INFO - cpd00441 not found in model!
2026-01-13 19:35:31,040 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:31,043 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:31,112 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:35:31,129 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:35:31,144 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:31,190 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,204 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,215 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,227 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,238 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,249 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,260 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,271 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,282 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,291 - INFO - cpd00221 not found in model!
2026-01-13 19:35:31,292 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:31,295 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,306 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,317 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,328 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,346 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,357 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,369 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,380 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,391 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,401 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,412 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,421 - INFO - cpd00221 not found in model!
2026-01-13 19:35:31,422 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:31,425 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,435 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,446 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,457 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,468 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,479 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,490 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,501 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,512 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,523 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,533 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,545 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,554 - INFO - cpd08021 not found in model!
2026-01-13 19:35:31,554 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:31,558 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,567 - INFO - cpd00811 not found in model!
2026-01-13 19:35:31,567 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:31,570 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,579 - INFO - cpd08021 not found in model!
2026-01-13 19:35:31,580 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:31,583 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,591 - INFO - cpd00811 not found in model!
2026-01-13 19:35:31,592 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:31,595 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,606 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,617 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,626 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,626 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,629 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,638 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,639 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,642 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,651 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,652 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,655 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,663 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,664 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,667 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,678 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,697 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,698 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,701 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,712 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,721 - INFO - cpd11632 not found in model!
2026-01-13 19:35:31,721 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:31,724 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,733 - INFO - cpd08701 not found in model!
2026-01-13 19:35:31,734 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:31,734 - INFO - cpd01024 not found in model!
2026-01-13 19:35:31,735 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:31,738 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,746 - INFO - cpd01024 not found in model!
2026-01-13 19:35:31,747 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:31,750 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,761 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,769 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,770 - INFO - Media compound: cpd11640 not found in model.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:31,773 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 19:35:31,782 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,783 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,784 - INFO - cpd00187 not found in model!
2026-01-13 19:35:31,784 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:31,787 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,796 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,796 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,799 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,808 - INFO - cpd11640 not found in model!
2026-01-13 19:35:31,808 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:31,809 - INFO - cpd00441 not found in model!
2026-01-13 19:35:31,809 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:31,812 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:31,935 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,949 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,961 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,974 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,986 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:31,997 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,008 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,019 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,031 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,042 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,053 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,064 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,075 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,086 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,097 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,108 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,119 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:32,130 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,141 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,152 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,163 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,169 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:35:32,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,189 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:32,196 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,208 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,219 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,230 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,241 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,251 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,262 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,274 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,285 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,296 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,307 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,318 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,329 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,339 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,350 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,359 - INFO - cpd11640 not found in model!
2026-01-13 19:35:32,360 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:32,363 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,372 - INFO - cpd11640 not found in model!
2026-01-13 19:35:32,372 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:32,376 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,385 - INFO - cpd11640 not found in model!
2026-01-13 19:35:32,385 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:32,389 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,397 - INFO - cpd11640 not found in model!
2026-01-13 19:35:32,399 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:32,401 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,412 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,423 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,432 - INFO - cpd11640 not found in model!
2026-01-13 19:35:32,432 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:32,435 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,446 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,455 - INFO - cpd11632 not found in model!
2026-01-13 19:35:32,455 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:32,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,468 - INFO - cpd08701 not found in model!
2026-01-13 19:35:32,468 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:32,469 - INFO - cpd01024 not found in model!
2026-01-13 19:35:32,470 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:32,472 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,482 - INFO - cpd01024 not found in model!
2026-01-13 19:35:32,482 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:32,485 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,496 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,505 - INFO - cpd11640 not found in model!
2026-01-13 19:35:32,506 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:32,509 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,523 - INFO - cpd11640 not found in model!
2026-01-13 19:35:32,524 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:32,525 - INFO - cpd00187 not found in model!

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:32,525 - INFO - Media compound: cpd00187 not found in model.

2026-01-13 19:35:32,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,538 - INFO - cpd11640 not found in model!
2026-01-13 19:35:32,539 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:32,539 - INFO - cpd00425 not found in model!
2026-01-13 19:35:32,540 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:32,543 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,552 - INFO - cpd11640 not found in model!
2026-01-13 19:35:32,552 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:32,555 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,565 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:35:32,581 - INFO - Objective with gapfill database:14.625; min objective:0.01
2026-01-13 19:35:32,596 - INFO - Objective with gapfill database:15.375; min objective:0.01
2026-01-13 19:35:32,610 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:32,976 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:35:32,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:32,994 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,005 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,015 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,025 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,036 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,056 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,067 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,075 - INFO - cpd00221 not found in model!
2026-01-13 19:35:33,076 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:33,079 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,100 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,110 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,120 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,131 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,141 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,151 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,162 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,172 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,182 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:33,191 - INFO - cpd00221 not found in model!
2026-01-13 19:35:33,192 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:33,195 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,205 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,216 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,224 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:35:33,227 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,238 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,240 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:35:33,248 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,255 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:33,259 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,269 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,280 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,290 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,300 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,311 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,319 - INFO - cpd08021 not found in model!
2026-01-13 19:35:33,320 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:33,324 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,332 - INFO - cpd00811 not found in model!
2026-01-13 19:35:33,333 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:33,337 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,345 - INFO - cpd08021 not found in model!
2026-01-13 19:35:33,346 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:33,349 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:33,357 - INFO - cpd00811 not found in model!
2026-01-13 19:35:33,358 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:33,361 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,372 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,382 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,392 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,399 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:35:33,403 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,413 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,424 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,434 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,437 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:33,445 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,456 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,466 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,475 - INFO - cpd11632 not found in model!
2026-01-13 19:35:33,475 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:33,479 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,487 - INFO - cpd08701 not found in model!
2026-01-13 19:35:33,488 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:33,489 - INFO - cpd01024 not found in model!
2026-01-13 19:35:33,491 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:33,493 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,502 - INFO - cpd01024 not found in model!
2026-01-13 19:35:33,503 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:33,506 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,527 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,535 - INFO - cpd00187 not found in model!
2026-01-13 19:35:33,536 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:33,539 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,548 - INFO - cpd00425 not found in model!
2026-01-13 19:35:33,548 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:33,552 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:33,560 - INFO - cpd00441 not found in model!
2026-01-13 19:35:33,561 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:33,564 - INFO -   Saved gapfilled model: gapfilled_models2/Eoetvoesia.1_gf.xml
2026-01-13 19:35:33,565 - INFO -   Total reactions added: 192
2026-01-13 19:35:33,564 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:33,640 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:35:33,657 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:33,776 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:34,290 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:34,625 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,639 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,651 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,662 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,672 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,683 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,694 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,705 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,716 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,727 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,738 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,748 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,759 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,770 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,780 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,791 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,802 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,812 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,823 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,834 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,844 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,855 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,865 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,876 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,886 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,897 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,907 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,918 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,929 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,939 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,950 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,960 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,971 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,981 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:34,992 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,014 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,024 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,033 - INFO - cpd11640 not found in model!
2026-01-13 19:35:35,034 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:35,037 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,046 - INFO - cpd11640 not found in model!
2026-01-13 19:35:35,047 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:35,051 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,059 - INFO - cpd11640 not found in model!
2026-01-13 19:35:35,060 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:35,063 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,072 - INFO - cpd11640 not found in model!
2026-01-13 19:35:35,073 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:35,075 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,086 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,096 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,105 - INFO - cpd11640 not found in model!
2026-01-13 19:35:35,105 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:35,108 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,119 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,127 - INFO - cpd11632 not found in model!
2026-01-13 19:35:35,128 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:35,131 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,139 - INFO - cpd08701 not found in model!
2026-01-13 19:35:35,140 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:35,142 - INFO - cpd01024 not found in model!
2026-01-13 19:35:35,142 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:35,146 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,154 - INFO - cpd01024 not found in model!
2026-01-13 19:35:35,155 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:35,158 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,168 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,177 - INFO - cpd11640 not found in model!
2026-01-13 19:35:35,178 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:35,181 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,189 - INFO - cpd11640 not found in model!
2026-01-13 19:35:35,191 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:35,192 - INFO - cpd00187 not found in model!
2026-01-13 19:35:35,193 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:35,196 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,205 - INFO - cpd11640 not found in model!
2026-01-13 19:35:35,205 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:35,206 - INFO - cpd00425 not found in model!
2026-01-13 19:35:35,207 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:35,210 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,219 - INFO - cpd11640 not found in model!
2026-01-13 19:35:35,220 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:35,222 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,713 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:35,735 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,738 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:35:35,752 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,770 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,786 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,803 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,820 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,837 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,854 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,870 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,887 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,903 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,920 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,937 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,953 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,969 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:35,986 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,019 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,036 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,053 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,069 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,086 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,102 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,119 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,135 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,152 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,168 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,202 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,218 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,235 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,249 - INFO - cpd08021 not found in model!
2026-01-13 19:35:36,250 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:36,254 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,268 - INFO - cpd00811 not found in model!
2026-01-13 19:35:36,269 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:36,273 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,287 - INFO - cpd08021 not found in model!
2026-01-13 19:35:36,287 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:36,291 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,305 - INFO - cpd00811 not found in model!
2026-01-13 19:35:36,306 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:36,310 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,326 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,359 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,376 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,393 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,398 - INFO -   Saved gapfilled model: gapfilled_models2/Aquamicrobium.7_gf.xml
2026-01-13 19:35:36,400 - INFO -   Total reactions added: 186
2026-01-13 19:35:36,410 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,427 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,461 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,478 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,492 - INFO - cpd11632 not found in model!
2026-01-13 19:35:36,493 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:36,496 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,510 - INFO - cpd08701 not found in model!
2026-01-13 19:35:36,511 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:36,511 - INFO - cpd01024 not found in model!
2026-01-13 19:35:36,512 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:36,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,529 - INFO - cpd01024 not found in model!
2026-01-13 19:35:36,530 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:36,534 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,551 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,567 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,581 - INFO - cpd00187 not found in model!
2026-01-13 19:35:36,582 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:36,585 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,602 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,616 - INFO - cpd00441 not found in model!
2026-01-13 19:35:36,617 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:36,620 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:36,632 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:35:37,183 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:37,460 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:35:37,478 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:37,789 - INFO - Objective with gapfill database:34.50000000000004; min objective:0.01
2026-01-13 19:35:37,825 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:37,854 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,869 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,881 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,892 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,904 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,915 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,927 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,938 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,950 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,961 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,972 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,983 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:37,995 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,007 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,018 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,029 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,041 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,052 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,063 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,074 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,086 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,097 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,108 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,119 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,130 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,142 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,145 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,153 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,169 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,175 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,186 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,187 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,204 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,210 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,219 - INFO - cpd08021 not found in model!
2026-01-13 19:35:38,220 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:38,221 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,223 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,233 - INFO - cpd00811 not found in model!
2026-01-13 19:35:38,234 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:38,237 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,238 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,246 - INFO - cpd08021 not found in model!
2026-01-13 19:35:38,247 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:38,250 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,255 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,259 - INFO - cpd00811 not found in model!
2026-01-13 19:35:38,260 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:38,263 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,272 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,274 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,285 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,290 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,294 - INFO - cpd11640 not found in model!
2026-01-13 19:35:38,295 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:38,298 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,307 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,307 - INFO - cpd11640 not found in model!
2026-01-13 19:35:38,309 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:38,312 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,321 - INFO - cpd11640 not found in model!
2026-01-13 19:35:38,322 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:38,324 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,325 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,334 - INFO - cpd11640 not found in model!
2026-01-13 19:35:38,335 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:38,338 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,341 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,350 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,358 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,361 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,370 - INFO - cpd11640 not found in model!
2026-01-13 19:35:38,371 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:38,374 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,375 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,385 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,392 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,394 - INFO - cpd11632 not found in model!
2026-01-13 19:35:38,395 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:38,398 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,407 - INFO - cpd08701 not found in model!
2026-01-13 19:35:38,408 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:38,409 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,409 - INFO - cpd01024 not found in model!
2026-01-13 19:35:38,411 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:38,414 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,423 - INFO - cpd01024 not found in model!
2026-01-13 19:35:38,424 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:38,426 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,427 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,439 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,448 - INFO - cpd11640 not found in model!
2026-01-13 19:35:38,449 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:38,452 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,461 - INFO - cpd11640 not found in model!
2026-01-13 19:35:38,461 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,462 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:38,463 - INFO - cpd00187 not found in model!
2026-01-13 19:35:38,463 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:38,467 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,477 - INFO - cpd11640 not found in model!
2026-01-13 19:35:38,478 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:38,478 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,479 - INFO - cpd00425 not found in model!
2026-01-13 19:35:38,480 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:38,483 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,492 - INFO - cpd11640 not found in model!
2026-01-13 19:35:38,493 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:35:38,494 - INFO - cpd00441 not found in model!
2026-01-13 19:35:38,495 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:38,495 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,498 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,513 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,530 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,547 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,564 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,581 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,598 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,615 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,632 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,649 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,666 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,683 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,698 - INFO - cpd08021 not found in model!
2026-01-13 19:35:38,699 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:38,703 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,724 - INFO - cpd00811 not found in model!
2026-01-13 19:35:38,725 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:38,730 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,744 - INFO - cpd08021 not found in model!
2026-01-13 19:35:38,745 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:38,749 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,763 - INFO - cpd00811 not found in model!
2026-01-13 19:35:38,764 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:38,768 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,785 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,801 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,818 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,835 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,853 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,871 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,888 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,905 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,922 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,939 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,953 - INFO - cpd11632 not found in model!
2026-01-13 19:35:38,954 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:38,958 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,972 - INFO - cpd08701 not found in model!
2026-01-13 19:35:38,973 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:38,974 - INFO - cpd01024 not found in model!
2026-01-13 19:35:38,974 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:38,978 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:38,992 - INFO - cpd01024 not found in model!
2026-01-13 19:35:38,993 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:38,997 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:39,014 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:39,030 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:39,044 - INFO - cpd00187 not found in model!
2026-01-13 19:35:39,045 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:39,049 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:39,066 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:39,080 - INFO - cpd00441 not found in model!
2026-01-13 19:35:39,081 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:39,085 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:39,120 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:39,323 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:35:39,339 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:39,764 - INFO -   Saved gapfilled model: gapfilled_models2/Bauldia.2_gf.xml
2026-01-13 19:35:39,766 - INFO -   Total reactions added: 182
2026-01-13 19:35:39,992 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:35:40,536 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:41,027 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:35:41,045 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:41,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,155 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,167 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,179 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,191 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,204 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,216 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,228 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,240 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,252 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,264 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,276 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:41,288 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,300 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,311 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,323 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:41,335 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,346 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:35:41,347 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,359 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,371 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,383 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,394 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,406 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,418 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,430 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,442 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,454 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,465 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,477 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,489 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,501 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,513 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,522 - INFO - cpd08021 not found in model!
2026-01-13 19:35:41,523 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:41,527 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,537 - INFO - cpd00811 not found in model!
2026-01-13 19:35:41,537 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:41,540 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,550 - INFO - cpd08021 not found in model!
2026-01-13 19:35:41,551 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:41,555 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,564 - INFO - cpd00811 not found in model!
2026-01-13 19:35:41,565 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:41,568 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,580 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,591 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,603 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,615 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,626 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,638 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,650 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,662 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,673 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,685 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,695 - INFO - cpd11632 not found in model!
2026-01-13 19:35:41,696 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:41,699 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,709 - INFO - cpd08701 not found in model!
2026-01-13 19:35:41,709 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:41,711 - INFO - cpd01024 not found in model!
2026-01-13 19:35:41,711 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:41,714 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,723 - INFO - cpd01024 not found in model!
2026-01-13 19:35:41,724 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:41,727 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:41,738 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,750 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,761 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,772 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:41,784 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:42,056 - INFO -   Saved gapfilled model: gapfilled_models2/Anaerovorax.4_gf.xml
2026-01-13 19:35:42,059 - INFO -   Total reactions added: 202

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:42,307 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:42,727 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:35:42,743 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:35:42,903 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:35:42,964 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:42,979 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:42,991 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,015 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,026 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,038 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,050 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,062 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,073 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,085 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,097 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,109 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,120 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,132 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,144 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,155 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,167 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,179 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,190 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,202 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,213 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,233 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,242 - INFO - cpd00075 not found in model!
2026-01-13 19:35:43,243 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:35:43,246 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,256 - INFO - cpd00209 not found in model!
2026-01-13 19:35:43,257 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:43,260 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,269 - INFO - cpd00418 not found in model!
2026-01-13 19:35:43,270 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:35:43,273 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,282 - INFO - cpd00075 not found in model!
2026-01-13 19:35:43,284 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:35:43,287 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,297 - INFO - cpd00209 not found in model!
2026-01-13 19:35:43,297 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:43,301 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,310 - INFO - cpd00418 not found in model!
2026-01-13 19:35:43,311 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:35:43,314 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,324 - INFO - cpd00075 not found in model!
2026-01-13 19:35:43,325 - INFO - Media compound: cpd00075 not found in model.
2026-01-13 19:35:43,328 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,337 - INFO - cpd00209 not found in model!
2026-01-13 19:35:43,338 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:43,341 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,350 - INFO - cpd00418 not found in model!
2026-01-13 19:35:43,351 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:35:43,354 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,363 - INFO - cpd08021 not found in model!
2026-01-13 19:35:43,364 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:43,367 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,376 - INFO - cpd00811 not found in model!
2026-01-13 19:35:43,377 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:43,380 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,389 - INFO - cpd08021 not found in model!
2026-01-13 19:35:43,390 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:43,393 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,402 - INFO - cpd00811 not found in model!
2026-01-13 19:35:43,403 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:35:43,406 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,417 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,441 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,452 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,463 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,475 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,486 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,498 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,509 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,520 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,529 - INFO - cpd11632 not found in model!
2026-01-13 19:35:43,530 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:43,533 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,543 - INFO - cpd08701 not found in model!
2026-01-13 19:35:43,544 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:43,544 - INFO - cpd01024 not found in model!
2026-01-13 19:35:43,545 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:43,549 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,558 - INFO - cpd01024 not found in model!
2026-01-13 19:35:43,559 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:43,562 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,573 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,585 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,594 - INFO - cpd00187 not found in model!
2026-01-13 19:35:43,595 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:43,598 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,608 - INFO - cpd00425 not found in model!
2026-01-13 19:35:43,608 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:43,611 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:43,620 - INFO - cpd00441 not found in model!
2026-01-13 19:35:43,621 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:35:43,624 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:44,164 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:35:44,183 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:35:44,201 - INFO - Objective with gapfill database:18.250000000000004; min objective:0.01
2026-01-13 19:35:44,217 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:44,695 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:35:44,697 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,712 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,724 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,736 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,747 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,759 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,771 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,783 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,794 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,804 - INFO - cpd00221 not found in model!
2026-01-13 19:35:44,805 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:44,808 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,819 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,830 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,842 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,853 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,864 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,875 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,886 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,897 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,909 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,920 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,929 - INFO - cpd00221 not found in model!
2026-01-13 19:35:44,930 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:35:44,933 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,944 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,956 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,967 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,976 - INFO - cpd00209 not found in model!
2026-01-13 19:35:44,977 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:44,979 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:44,990 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,002 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,011 - INFO - cpd00209 not found in model!
2026-01-13 19:35:45,012 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:45,014 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,025 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,036 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,046 - INFO - cpd00209 not found in model!
2026-01-13 19:35:45,047 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:35:45,051 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,062 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,073 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,084 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,095 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,106 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,117 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,129 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,152 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,163 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,166 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,186 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,193 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,199 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,210 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,212 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,221 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,230 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,230 - INFO - cpd11632 not found in model!
2026-01-13 19:35:45,232 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:45,234 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,244 - INFO - cpd08701 not found in model!
2026-01-13 19:35:45,244 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:45,245 - INFO - cpd01024 not found in model!
2026-01-13 19:35:45,245 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:45,248 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,249 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,258 - INFO - cpd01024 not found in model!
2026-01-13 19:35:45,259 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:45,262 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,266 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,273 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,283 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,284 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,293 - INFO - cpd00187 not found in model!
2026-01-13 19:35:45,294 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:45,297 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,301 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,308 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,319 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,324 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,349 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,375 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,387 - INFO -   Saved gapfilled model: gapfilled_models2/Devosia.9_gf.xml
2026-01-13 19:35:45,391 - INFO -   Total reactions added: 200
2026-01-13 19:35:45,400 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,427 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,447 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,467 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,487 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,505 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,523 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,540 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,558 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,576 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,586 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,595 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,612 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,615 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,631 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,632 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:35:45,637 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,650 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,658 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,669 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,680 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,701 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,708 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,722 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,727 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,741 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:45,746 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

None

2026-01-13 19:35:45,759 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,762 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:35:45,765 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,777 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,785 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,795 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,804 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,810 - INFO - cpd08021 not found in model!
2026-01-13 19:35:45,810 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:45,814 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,824 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:45,832 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,844 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,847 - INFO - cpd08021 not found in model!
2026-01-13 19:35:45,847 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:35:45,851 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,862 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,868 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,879 - INFO - Objective with gapfill database:34.500000000000036; min objective:0.01
2026-01-13 19:35:45,881 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,886 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,900 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,904 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,919 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,922 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:35:45,925 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,937 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,946 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,956 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,968 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,976 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,991 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:45,995 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,011 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,014 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,031 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,032 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,050 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,051 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,051 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,069 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,070 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,075 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,085 - INFO - cpd11632 not found in model!
2026-01-13 19:35:46,086 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:46,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,091 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,093 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,106 - INFO - cpd01024 not found in model!
2026-01-13 19:35:46,108 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:46,108 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,110 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,112 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,126 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,128 - INFO - cpd01024 not found in model!
2026-01-13 19:35:46,128 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,129 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:46,133 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,145 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,146 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,151 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,163 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,168 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,181 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,182 - INFO - cpd00187 not found in model!
2026-01-13 19:35:46,183 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,184 - INFO - Media compound: cpd00187 not found in model.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:35:46,188 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

c0

2026-01-13 19:35:46,199 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,202 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,203 - INFO - cpd00425 not found in model!
2026-01-13 19:35:46,204 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:35:46,204 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:35:46,208 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,222 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,235 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,241 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,252 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,260 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,270 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,278 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,288 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,297 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,305 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,316 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,323 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,334 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,340 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,353 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,358 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,372 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,376 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,391 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,394 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,411 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,412 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,430 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,432 - INFO -   Saved gapfilled model: gapfilled_models2/Christensenellaceae_R-7_group.36_gf.xml
2026-01-13 19:35:46,434 - INFO -   Total reactions added: 176
2026-01-13 19:35:46,447 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,449 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,464 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,465 - INFO - cpd11632 not found in model!
2026-01-13 19:35:46,466 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:46,471 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,481 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,486 - INFO - cpd08701 not found in model!
2026-01-13 19:35:46,488 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:46,488 - INFO - cpd01024 not found in model!
2026-01-13 19:35:46,489 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:46,494 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,499 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,509 - INFO - cpd01024 not found in model!
2026-01-13 19:35:46,510 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:46,515 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,534 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,542 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,552 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,561 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,570 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,576 - INFO - cpd00187 not found in model!
2026-01-13 19:35:46,578 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:46,582 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,587 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,602 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,606 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,621 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,624 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,641 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,659 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,672 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:35:46,676 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,694 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,712 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,729 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,746 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,764 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,781 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,799 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,816 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,834 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,851 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,865 - INFO - cpd11632 not found in model!
2026-01-13 19:35:46,866 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:35:46,870 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,885 - INFO - cpd08701 not found in model!
2026-01-13 19:35:46,886 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:35:46,887 - INFO - cpd01024 not found in model!
2026-01-13 19:35:46,888 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:46,892 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,907 - INFO - cpd01024 not found in model!
2026-01-13 19:35:46,908 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:35:46,913 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,931 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,949 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,963 - INFO - cpd00187 not found in model!
2026-01-13 19:35:46,964 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:35:46,969 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:46,986 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:35:47,005 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:35:47,241 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:35:51,653 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:35:52,330 - INFO -   Saved gapfilled model: gapfilled_models2/Erysipelothrix.8_gf.xml
2026-01-13 19:35:52,332 - INFO -   Total reactions added: 162
2026-01-13 19:35:52,579 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:35:53,183 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:05,942 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:36:05,958 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:07,642 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:36:07,660 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:36:07,675 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:12,033 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:36:12,049 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:36:12,065 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:12,133 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:36:12,150 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:36:12,325 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:12,428 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:36:12,467 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:12,905 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:36:12,941 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:13,025 - INFO -   Saved gapfilled model: gapfilled_models2/Bacilli.3_gf.xml
2026-01-13 19:36:13,027 - INFO -   Total reactions added: 192
2026-01-13 19:36:13,076 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,120 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,139 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,158 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:13,177 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

None

2026-01-13 19:36:13,192 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:36:13,196 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,214 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,233 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,254 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,273 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,282 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:36:13,292 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,311 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,329 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,347 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,365 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,384 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,403 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,427 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,446 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,464 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,482 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,500 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,519 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,537 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,555 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,573 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,591 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,609 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:13,627 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,645 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,659 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:36:13,664 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,682 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,697 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:13,701 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,719 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,737 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,756 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,774 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,792 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,810 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,829 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,847 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,866 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:13,884 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,889 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:36:13,900 - INFO -   Saved gapfilled model: gapfilled_models2/Chelatococcus.1_gf.xml
2026-01-13 19:36:13,902 - INFO -   Total reactions added: 176
2026-01-13 19:36:13,904 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,922 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,941 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,957 - INFO - cpd11632 not found in model!
2026-01-13 19:36:13,957 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:13,961 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:13,998 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:14,016 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:14,035 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:14,050 - INFO - cpd00187 not found in model!
2026-01-13 19:36:14,051 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:36:14,056 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:14,071 - INFO - cpd00425 not found in model!
2026-01-13 19:36:14,072 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:36:14,076 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:14,094 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:14,160 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:36:14,390 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:14,462 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:36:14,479 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:36:14,494 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:36:14,764 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:14,964 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:36:15,000 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:15,167 - INFO -   Saved gapfilled model: gapfilled_models2/Alcaligenes.14_gf.xml
2026-01-13 19:36:15,171 - INFO -   Total reactions added: 144
2026-01-13 19:36:15,442 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:15,516 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:36:15,534 - INFO - Objective with gapfill database:17.500000000000018; min objective:0.01
2026-01-13 19:36:15,549 - INFO - Objective with gapfill database:19.125000000000018; min objective:0.01
2026-01-13 19:36:15,564 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:36:16,084 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:16,749 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:36:16,782 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:16,786 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:36:16,803 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:36:16,817 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:17,308 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:36:17,325 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:17,714 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,739 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,759 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,780 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,781 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,797 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,800 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,811 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,820 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,824 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,837 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,841 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,850 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,862 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,862 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,875 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,882 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,888 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,898 - INFO - cpd00221 not found in model!
2026-01-13 19:36:17,899 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:36:17,902 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,902 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,914 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,921 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:17,927 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 19:36:17,939 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,941 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,952 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,960 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,964 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,969 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:36:17,976 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,985 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:17,988 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:17,999 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,000 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,013 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,019 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,025 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,034 - INFO - cpd00221 not found in model!
2026-01-13 19:36:18,035 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:36:18,038 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,038 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,051 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,058 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,063 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,075 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,077 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,087 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,096 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,099 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,111 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,116 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,123 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,135 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,135 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,148 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,154 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,161 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,173 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,195 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,210 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,214 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,223 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,234 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,235 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:18,247 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,253 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,260 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,272 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,273 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,285 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,293 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,297 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,313 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,315 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,328 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,332 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,341 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,352 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,353 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,363 - INFO - cpd11632 not found in model!
2026-01-13 19:36:18,364 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:18,368 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,372 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,378 - INFO - cpd08701 not found in model!
2026-01-13 19:36:18,379 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:36:18,380 - INFO - cpd01024 not found in model!
2026-01-13 19:36:18,380 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:18,384 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,393 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,395 - INFO - cpd01024 not found in model!
2026-01-13 19:36:18,396 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:18,399 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,412 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,414 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,425 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,435 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,435 - INFO - cpd00187 not found in model!
2026-01-13 19:36:18,436 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:36:18,439 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,451 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,455 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,464 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,465 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,475 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,493 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,494 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,513 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,514 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,532 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,534 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,551 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,554 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,570 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,573 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,589 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,593 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,608 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,614 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,626 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,630 - INFO - cpd11632 not found in model!
2026-01-13 19:36:18,631 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:18,636 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,645 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,652 - INFO - cpd08701 not found in model!
2026-01-13 19:36:18,653 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:36:18,654 - INFO - cpd01024 not found in model!
2026-01-13 19:36:18,655 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:18,660 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,664 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,676 - INFO - cpd01024 not found in model!
2026-01-13 19:36:18,677 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:18,682 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,683 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,702 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,703 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,721 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,722 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,738 - INFO - cpd00187 not found in model!
2026-01-13 19:36:18,739 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:36:18,741 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,743 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,759 - INFO - cpd00425 not found in model!
2026-01-13 19:36:18,760 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,760 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:36:18,765 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,779 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,785 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,798 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,816 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,835 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,854 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,872 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:18,891 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,910 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,917 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:36:18,928 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,934 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:36:18,947 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,948 - INFO - Objective with gapfill database:18.250000000000004; min objective:0.01
2026-01-13 19:36:18,962 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:18,966 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:18,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,012 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,031 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,050 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,069 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,087 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,106 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,125 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,143 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,162 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,181 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,201 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,220 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,240 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,259 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,278 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,297 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,316 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,335 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,351 - INFO - cpd11632 not found in model!
2026-01-13 19:36:19,352 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:19,356 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,372 - INFO - cpd08701 not found in model!
2026-01-13 19:36:19,373 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:36:19,374 - INFO - cpd01024 not found in model!
2026-01-13 19:36:19,375 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:19,379 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,395 - INFO - cpd01024 not found in model!
2026-01-13 19:36:19,395 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:19,400 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,418 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,437 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,453 - INFO - cpd00187 not found in model!
2026-01-13 19:36:19,453 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:36:19,458 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,476 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,495 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:36:19,853 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:36:19,976 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:19,993 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,006 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,018 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,030 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,043 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,055 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,076 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,088 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,100 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,113 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,125 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,137 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,149 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,161 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,173 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,185 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,197 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,209 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,221 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,233 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,245 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,257 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,269 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,282 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,295 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,307 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:20,319 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,332 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,350 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:36:20,356 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,368 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,369 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:36:20,378 - INFO - cpd08021 not found in model!
2026-01-13 19:36:20,379 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:20,382 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,385 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:20,392 - INFO - cpd00811 not found in model!
2026-01-13 19:36:20,393 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:20,396 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,406 - INFO - cpd08021 not found in model!
2026-01-13 19:36:20,407 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:20,410 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,419 - INFO - cpd00811 not found in model!
2026-01-13 19:36:20,420 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:20,423 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,435 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,447 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,471 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,483 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,495 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,507 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,519 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,531 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,544 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,554 - INFO - cpd11632 not found in model!
2026-01-13 19:36:20,554 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:20,557 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,567 - INFO - cpd08701 not found in model!
2026-01-13 19:36:20,568 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:36:20,569 - INFO - cpd01024 not found in model!
2026-01-13 19:36:20,569 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:20,573 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,583 - INFO - cpd01024 not found in model!
2026-01-13 19:36:20,583 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:20,586 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,598 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,611 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,622 - INFO - cpd00187 not found in model!
2026-01-13 19:36:20,623 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:36:20,626 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,636 - INFO - cpd00425 not found in model!
2026-01-13 19:36:20,637 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:36:20,640 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,641 - INFO -   Saved gapfilled model: gapfilled_models2/Actinobacteria.1_gf.xml
2026-01-13 19:36:20,645 - INFO -   Total reactions added: 180
2026-01-13 19:36:20,650 - INFO - cpd00441 not found in model!
2026-01-13 19:36:20,650 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:36:20,653 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:20,926 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:20,997 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:36:21,031 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:21,479 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:36:21,498 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:36:21,605 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:36:22,058 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,093 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,113 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,133 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,153 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,173 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,193 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,214 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,234 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,255 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,275 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,295 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,316 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,336 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,356 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,376 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,397 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,418 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,438 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,479 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,499 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,520 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,540 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,561 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,581 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,601 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,622 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,643 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,663 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,684 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,704 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,725 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,745 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,766 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,786 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,807 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,828 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,848 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,868 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,888 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,909 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,929 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:36:22,950 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,953 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:36:22,970 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:22,990 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:23,007 - INFO - cpd11632 not found in model!
2026-01-13 19:36:23,008 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:23,013 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:23,030 - INFO - cpd08701 not found in model!
2026-01-13 19:36:23,031 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:36:23,032 - INFO - cpd01024 not found in model!
2026-01-13 19:36:23,033 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:23,038 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:23,055 - INFO - cpd01024 not found in model!
2026-01-13 19:36:23,056 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:23,060 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:23,081 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:23,101 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:23,121 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:23,141 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:23,161 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:23,732 - INFO -   Saved gapfilled model: gapfilled_models2/Fastidiosipila.1_gf.xml
2026-01-13 19:36:23,736 - INFO -   Total reactions added: 142
2026-01-13 19:36:24,011 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:24,361 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,379 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,393 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,406 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,420 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,434 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,448 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,462 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,475 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,489 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,502 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,542 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,556 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,570 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,584 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:24,597 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,611 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,625 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,634 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:36:24,638 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:36:24,652 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 19:36:24,665 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,667 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:24,670 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:36:24,679 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,692 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,703 - INFO - cpd00418 not found in model!
2026-01-13 19:36:24,704 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:36:24,707 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,720 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,733 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,744 - INFO - cpd00418 not found in model!
2026-01-13 19:36:24,745 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:36:24,748 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,761 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,775 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,785 - INFO - cpd00418 not found in model!
2026-01-13 19:36:24,786 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:36:24,790 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,801 - INFO - cpd08021 not found in model!
2026-01-13 19:36:24,801 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:24,805 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,816 - INFO - cpd00811 not found in model!
2026-01-13 19:36:24,816 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:24,820 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,831 - INFO - cpd08021 not found in model!
2026-01-13 19:36:24,832 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:24,835 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,846 - INFO - cpd00811 not found in model!
2026-01-13 19:36:24,847 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:24,850 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,863 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,877 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,890 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,904 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,917 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,930 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,943 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,957 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,970 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,983 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:24,994 - INFO - cpd11632 not found in model!
2026-01-13 19:36:24,994 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:24,998 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:25,008 - INFO - cpd08701 not found in model!
2026-01-13 19:36:25,009 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:36:25,010 - INFO - cpd01024 not found in model!
2026-01-13 19:36:25,011 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:25,014 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:25,025 - INFO - cpd01024 not found in model!
2026-01-13 19:36:25,026 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:25,030 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:25,043 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:25,056 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:25,067 - INFO - cpd00187 not found in model!
2026-01-13 19:36:25,068 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:36:25,072 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:25,085 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:25,099 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:26,347 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:36:26,366 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:26,944 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:36:26,960 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:27,411 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:28,226 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,244 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,258 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,271 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,284 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,297 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,311 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,324 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,337 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,351 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,364 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,377 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,390 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,403 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,416 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,443 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,456 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,469 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,483 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,496 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,509 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,522 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,535 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,548 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,559 - INFO - cpd00418 not found in model!
2026-01-13 19:36:28,559 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:36:28,563 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,576 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,589 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,600 - INFO - cpd00418 not found in model!
2026-01-13 19:36:28,602 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:36:28,605 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,618 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,631 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:28,641 - INFO - cpd00418 not found in model!
2026-01-13 19:36:28,642 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:36:28,645 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:28,656 - INFO - cpd08021 not found in model!
2026-01-13 19:36:28,657 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:28,660 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,671 - INFO - cpd00811 not found in model!
2026-01-13 19:36:28,672 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:28,675 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,682 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:36:28,686 - INFO - cpd08021 not found in model!
2026-01-13 19:36:28,687 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:28,691 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,698 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:36:28,701 - INFO - cpd00811 not found in model!
2026-01-13 19:36:28,702 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:28,705 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,717 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:28,718 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,721 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:28,731 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,744 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,757 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,770 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,783 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,796 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,810 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,823 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,836 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,847 - INFO - cpd11632 not found in model!
2026-01-13 19:36:28,848 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:28,851 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,862 - INFO - cpd08701 not found in model!
2026-01-13 19:36:28,863 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:36:28,864 - INFO - cpd01024 not found in model!
2026-01-13 19:36:28,865 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:28,868 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,879 - INFO - cpd01024 not found in model!
2026-01-13 19:36:28,879 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:28,883 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,896 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,908 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,919 - INFO - cpd00187 not found in model!
2026-01-13 19:36:28,920 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:36:28,923 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,936 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:28,949 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:29,506 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:36:29,526 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:36:30,646 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:31,062 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:36:31,082 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:36:31,450 - INFO -   Saved gapfilled model: gapfilled_models2/Bacillus.2_gf.xml
2026-01-13 19:36:31,453 - INFO -   Total reactions added: 162
2026-01-13 19:36:31,738 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:36:32,426 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:36:33,386 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:36:34,221 - INFO -   Saved gapfilled model: gapfilled_models2/Alphaproteobacteria.2_gf.xml
2026-01-13 19:36:34,225 - INFO -   Total reactions added: 136
2026-01-13 19:36:34,518 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:36:35,239 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:36:35,815 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:36:36,598 - INFO -   Saved gapfilled model: gapfilled_models2/Comamonadaceae.19_gf.xml
2026-01-13 19:36:36,601 - INFO -   Total reactions added: 172
2026-01-13 19:36:36,884 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:36:37,559 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:38,061 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,081 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,096 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,110 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,123 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,137 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,150 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,177 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,190 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,204 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,231 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,244 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,258 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,272 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,286 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,301 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,315 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,330 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,344 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,358 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,372 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,386 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,400 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,415 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,458 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,473 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,487 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,502 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,513 - INFO - cpd08021 not found in model!
2026-01-13 19:36:38,515 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:38,519 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,531 - INFO - cpd00811 not found in model!
2026-01-13 19:36:38,532 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:38,536 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,548 - INFO - cpd08021 not found in model!
2026-01-13 19:36:38,549 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:38,552 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,563 - INFO - cpd00811 not found in model!
2026-01-13 19:36:38,564 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:38,569 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,583 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,596 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,610 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,623 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,636 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,650 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,664 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,678 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,692 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,706 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,718 - INFO - cpd11632 not found in model!
2026-01-13 19:36:38,719 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:38,723 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,734 - INFO - cpd08701 not found in model!
2026-01-13 19:36:38,735 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:36:38,736 - INFO - cpd01024 not found in model!
2026-01-13 19:36:38,737 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:38,741 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,752 - INFO - cpd01024 not found in model!
2026-01-13 19:36:38,753 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:38,756 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,770 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,783 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,794 - INFO - cpd00187 not found in model!
2026-01-13 19:36:38,795 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:36:38,799 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,810 - INFO - cpd00425 not found in model!
2026-01-13 19:36:38,811 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:36:38,814 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:38,825 - INFO - cpd00441 not found in model!
2026-01-13 19:36:38,826 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:36:38,829 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:41,871 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:41,891 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:41,905 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:41,920 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:41,934 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:41,947 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:41,961 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:41,975 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:41,989 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,017 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,031 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,060 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,075 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,103 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,118 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,132 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,147 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,161 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,175 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,190 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,205 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,227 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,243 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,257 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,272 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,288 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,303 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,318 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,333 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,347 - INFO - cpd08021 not found in model!
2026-01-13 19:36:42,348 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:42,354 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,369 - INFO - cpd00811 not found in model!
2026-01-13 19:36:42,370 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:42,375 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,389 - INFO - cpd08021 not found in model!
2026-01-13 19:36:42,390 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:36:42,394 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,409 - INFO - cpd00811 not found in model!
2026-01-13 19:36:42,410 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:36:42,414 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,435 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,457 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,477 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,495 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,514 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,532 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,550 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,569 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,586 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,605 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,619 - INFO - cpd11632 not found in model!
2026-01-13 19:36:42,621 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:36:42,625 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,639 - INFO - cpd08701 not found in model!
2026-01-13 19:36:42,640 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:36:42,642 - INFO - cpd01024 not found in model!
2026-01-13 19:36:42,642 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:42,648 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,662 - INFO - cpd01024 not found in model!
2026-01-13 19:36:42,663 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:36:42,668 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,685 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,703 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,718 - INFO - cpd00187 not found in model!
2026-01-13 19:36:42,719 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:36:42,723 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,737 - INFO - cpd00425 not found in model!
2026-01-13 19:36:42,738 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:36:42,743 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:36:42,756 - INFO - cpd00441 not found in model!
2026-01-13 19:36:42,756 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:36:42,760 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:53,022 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:36:53,039 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:36:53,053 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:56,473 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:36:56,493 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:36:56,509 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:36:56,524 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:56,692 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:36:56,709 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:36:56,724 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:58,706 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:36:58,723 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:59,438 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:36:59,456 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:36:59,923 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:36:59,943 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:01,593 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:37:01,610 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:02,373 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,392 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,407 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,423 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,437 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,452 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,466 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,481 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,496 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,511 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,526 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,540 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,555 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,569 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,584 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,600 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,616 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,631 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,660 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,674 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,703 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,718 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,729 - INFO - cpd00209 not found in model!
2026-01-13 19:37:02,730 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:37:02,734 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,749 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:02,764 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,776 - INFO - cpd00209 not found in model!
2026-01-13 19:37:02,777 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:37:02,780 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,795 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,797 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:37:02,809 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,815 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:02,822 - INFO - cpd00209 not found in model!
2026-01-13 19:37:02,822 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:37:02,826 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,841 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,855 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,869 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,884 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,898 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,912 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,927 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,941 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,955 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,969 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,984 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:02,998 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,013 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,027 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,042 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,053 - INFO - cpd11632 not found in model!
2026-01-13 19:37:03,054 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:37:03,058 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,070 - INFO - cpd08701 not found in model!
2026-01-13 19:37:03,070 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:37:03,071 - INFO - cpd01024 not found in model!
2026-01-13 19:37:03,072 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:03,075 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,087 - INFO - cpd01024 not found in model!
2026-01-13 19:37:03,088 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:03,091 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,105 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,120 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,131 - INFO - cpd00187 not found in model!
2026-01-13 19:37:03,132 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:37:03,135 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,150 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:03,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:03,689 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:37:03,705 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:37:03,710 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:03,724 - INFO - Objective with gapfill database:17.500000000000018; min objective:0.01
2026-01-13 19:37:03,740 - INFO - Objective with gapfill database:19.125000000000018; min objective:0.01
2026-01-13 19:37:03,755 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:04,563 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:37:04,583 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:37:04,600 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:06,283 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:37:06,300 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:37:06,315 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:06,684 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:37:06,700 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:37:06,715 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:07,160 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:37:07,176 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:08,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,448 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,465 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,480 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,494 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,509 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,527 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,544 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,560 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,576 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,591 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,607 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,624 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,640 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,656 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,673 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,688 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,702 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,720 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,736 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,751 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,767 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:08,788 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,804 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,820 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,828 - INFO - Objective with gapfill database:34.500000000000036; min objective:0.01
2026-01-13 19:37:08,838 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,855 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,865 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:08,870 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,888 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,903 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,918 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,937 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,951 - INFO - cpd08021 not found in model!
2026-01-13 19:37:08,951 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:08,955 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,967 - INFO - cpd00811 not found in model!
2026-01-13 19:37:08,968 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:08,972 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:08,990 - INFO - cpd08021 not found in model!
2026-01-13 19:37:08,991 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:08,995 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,009 - INFO - cpd00811 not found in model!
2026-01-13 19:37:09,010 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:09,014 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,029 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,045 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,061 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,076 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,093 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,109 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,124 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,156 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,171 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,183 - INFO - cpd11632 not found in model!
2026-01-13 19:37:09,184 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:37:09,187 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,203 - INFO - cpd08701 not found in model!
2026-01-13 19:37:09,204 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:37:09,206 - INFO - cpd01024 not found in model!
2026-01-13 19:37:09,207 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:09,212 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,226 - INFO - cpd01024 not found in model!
2026-01-13 19:37:09,226 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:09,230 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,246 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,261 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,274 - INFO - cpd00187 not found in model!
2026-01-13 19:37:09,275 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:37:09,279 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,292 - INFO - cpd00425 not found in model!
2026-01-13 19:37:09,293 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:37:09,296 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:09,309 - INFO - cpd00441 not found in model!
2026-01-13 19:37:09,310 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:37:09,314 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:09,455 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:37:09,479 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:10,105 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:37:10,122 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:10,187 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,207 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,222 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,236 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,251 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,266 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,281 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,296 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,310 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,325 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,340 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,355 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,369 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,384 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,399 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,414 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,473 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,488 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,503 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,517 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,532 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,547 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:10,562 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,576 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,591 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,605 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,619 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,634 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,649 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,661 - INFO - cpd08021 not found in model!
2026-01-13 19:37:10,662 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:10,665 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,678 - INFO - cpd00811 not found in model!
2026-01-13 19:37:10,679 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:10,683 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,695 - INFO - cpd08021 not found in model!
2026-01-13 19:37:10,695 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:10,699 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:10,712 - INFO - cpd00811 not found in model!
2026-01-13 19:37:10,712 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:10,716 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,731 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,744 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:37:10,745 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 19:37:10,761 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,761 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,766 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:10,775 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,781 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,790 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,797 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,804 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,812 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,819 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,828 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,834 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,843 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,848 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,858 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,863 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,874 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,875 - INFO - cpd11632 not found in model!
2026-01-13 19:37:10,876 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:37:10,880 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,886 - INFO - cpd00159 not found in model!
2026-01-13 19:37:10,887 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:37:10,891 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,891 - INFO - cpd08701 not found in model!
2026-01-13 19:37:10,892 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:37:10,893 - INFO - cpd01024 not found in model!
2026-01-13 19:37:10,894 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:10,897 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,906 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,909 - INFO - cpd01024 not found in model!
2026-01-13 19:37:10,909 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:10,913 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,920 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,928 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,935 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,942 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,950 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,954 - INFO - cpd00187 not found in model!
2026-01-13 19:37:10,955 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:37:10,959 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,965 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,970 - INFO - cpd00425 not found in model!
2026-01-13 19:37:10,971 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:37:10,975 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,986 - INFO - cpd00441 not found in model!
2026-01-13 19:37:10,987 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:37:10,991 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:10,994 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,009 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,024 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,039 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,051 - INFO - cpd00159 not found in model!
2026-01-13 19:37:11,052 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:37:11,056 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,071 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,085 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,100 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,115 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,129 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,144 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,159 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,188 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,203 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,218 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,233 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,245 - INFO - cpd08021 not found in model!
2026-01-13 19:37:11,246 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:11,249 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,262 - INFO - cpd00811 not found in model!
2026-01-13 19:37:11,263 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:11,267 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,279 - INFO - cpd08021 not found in model!
2026-01-13 19:37:11,280 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:11,284 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,296 - INFO - cpd00811 not found in model!
2026-01-13 19:37:11,297 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:11,301 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,315 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,330 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,344 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,359 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,374 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,387 - INFO - cpd00159 not found in model!
2026-01-13 19:37:11,388 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:37:11,392 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,406 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,419 - INFO - cpd00159 not found in model!
2026-01-13 19:37:11,420 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:37:11,424 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,439 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,455 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,467 - INFO - cpd11632 not found in model!
2026-01-13 19:37:11,468 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:37:11,472 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,485 - INFO - cpd08701 not found in model!
2026-01-13 19:37:11,486 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:37:11,486 - INFO - cpd01024 not found in model!
2026-01-13 19:37:11,487 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:11,491 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,503 - INFO - cpd01024 not found in model!
2026-01-13 19:37:11,504 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:11,508 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,523 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,538 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,550 - INFO - cpd00187 not found in model!
2026-01-13 19:37:11,551 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:37:11,554 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,567 - INFO - cpd00425 not found in model!
2026-01-13 19:37:11,568 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:37:11,571 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:11,586 - INFO - cpd00441 not found in model!
2026-01-13 19:37:11,587 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:37:11,591 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:11,976 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:37:11,994 - INFO - Objective with gapfill database:3.5000000000000004; min objective:0.01
2026-01-13 19:37:12,018 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:12,099 - INFO - Objective with gapfill database:34.50000000000006; min objective:0.01
2026-01-13 19:37:12,133 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:12,457 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:37:12,476 - INFO - Objective with gapfill database:17.500000000000018; min objective:0.01
2026-01-13 19:37:12,493 - INFO - Objective with gapfill database:19.125000000000018; min objective:0.01
2026-01-13 19:37:12,509 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:13,199 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,219 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,235 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,250 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:37:13,265 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,273 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:37:13,281 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,296 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,312 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,327 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,358 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,374 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,389 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,405 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:13,420 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,436 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,452 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,459 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:37:13,467 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,483 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,484 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:13,498 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,514 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,545 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,560 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,576 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,591 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,606 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,621 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,643 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,658 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,674 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,701 - INFO - cpd08021 not found in model!
2026-01-13 19:37:13,702 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:13,706 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,719 - INFO - cpd00811 not found in model!
2026-01-13 19:37:13,720 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:13,723 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,736 - INFO - cpd08021 not found in model!
2026-01-13 19:37:13,736 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:13,740 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,752 - INFO - cpd00811 not found in model!
2026-01-13 19:37:13,753 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:13,757 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,773 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,789 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,804 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,819 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,835 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,850 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,866 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,881 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,897 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,912 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,925 - INFO - cpd11632 not found in model!
2026-01-13 19:37:13,926 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:37:13,930 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,942 - INFO - cpd08701 not found in model!
2026-01-13 19:37:13,943 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:37:13,944 - INFO - cpd01024 not found in model!
2026-01-13 19:37:13,945 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:13,949 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,961 - INFO - cpd01024 not found in model!
2026-01-13 19:37:13,962 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:13,965 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,981 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:13,996 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:14,011 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:14,024 - INFO - cpd00425 not found in model!
2026-01-13 19:37:14,024 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:37:14,029 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:14,041 - INFO - cpd00441 not found in model!
2026-01-13 19:37:14,042 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:37:14,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:14,143 - INFO -   Saved gapfilled model: gapfilled_models2/Anaeromyxobacteraceae.2_gf.xml
2026-01-13 19:37:14,147 - INFO -   Total reactions added: 122

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:37:14,438 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:37:14,458 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:37:15,016 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:37:15,198 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:37:15,363 - INFO -   Saved gapfilled model: gapfilled_models2/Caldicoprobacteraceae.1_gf.xml
2026-01-13 19:37:15,368 - INFO -   Total reactions added: 114

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:15,513 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:37:15,533 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:15,555 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:37:15,575 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:37:15,594 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:37:15,612 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:15,661 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:37:15,682 - INFO - Objective with gapfill database:3.5000000000000004; min objective:0.01
2026-01-13 19:37:15,694 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:37:15,697 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:15,919 - INFO -   Saved gapfilled model: gapfilled_models2/EBM-39.5_gf.xml
2026-01-13 19:37:15,923 - INFO -   Total reactions added: 104

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:16,023 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:37:16,045 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:37:16,064 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:16,081 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:16,109 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:37:16,128 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:16,239 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:37:16,468 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:16,657 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:37:16,684 - INFO - Objective with gapfill database:17.5; min objective:0.01
2026-01-13 19:37:16,702 - INFO - Objective with gapfill database:19.125000000000004; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:16,720 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:16,758 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:37:16,776 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:37:16,791 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:16,921 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:37:16,947 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:37:17,009 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:17,476 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:37:17,501 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:37:17,518 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:37:17,534 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:17,688 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:37:17,715 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:18,515 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:18,743 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:37:18,761 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:37:19,234 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:20,217 - INFO -   Saved gapfilled model: gapfilled_models2/Aminivibrio.8_gf.xml
2026-01-13 19:37:20,222 - INFO -   Total reactions added: 90
2026-01-13 19:37:20,231 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:37:20,250 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:37:20,265 - INFO - Objective with gapfill database:18.250000000000004; min objective:0.01
2026-01-13 19:37:20,281 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:37:20,358 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,381 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,400 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,417 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,436 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,454 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,471 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,489 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,511 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,547 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,562 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:37:20,564 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,582 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,600 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,620 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,638 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,655 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,673 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,691 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,711 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,727 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,745 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,765 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,782 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,799 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,816 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,834 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,851 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,876 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,893 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,913 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,931 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,945 - INFO - cpd08021 not found in model!
2026-01-13 19:37:20,946 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:20,951 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,969 - INFO - cpd00811 not found in model!
2026-01-13 19:37:20,970 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:20,975 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:20,990 - INFO - cpd08021 not found in model!
2026-01-13 19:37:20,991 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:20,995 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,009 - INFO - cpd00811 not found in model!
2026-01-13 19:37:21,010 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:21,014 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,031 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,050 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,066 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,086 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,102 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,119 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,138 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,155 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,171 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,191 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,207 - INFO - cpd11632 not found in model!
2026-01-13 19:37:21,208 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:37:21,212 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,226 - INFO - cpd08701 not found in model!
2026-01-13 19:37:21,227 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:37:21,228 - INFO - cpd01024 not found in model!
2026-01-13 19:37:21,229 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:21,233 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,248 - INFO - cpd01024 not found in model!
2026-01-13 19:37:21,248 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:21,253 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,271 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,287 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,303 - INFO - cpd00187 not found in model!
2026-01-13 19:37:21,304 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:37:21,308 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,325 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:21,341 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:37:21,377 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:21,523 - INFO - Objective with gapfill database:34.50000000000005; min objective:0.01
2026-01-13 19:37:21,557 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:23,123 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,145 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,162 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,180 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,236 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,254 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,272 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,289 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,306 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,323 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,340 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,358 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,375 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,396 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,417 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,437 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,457 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,476 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,494 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,512 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,546 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,563 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,580 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,597 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,614 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,631 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,648 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,665 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,682 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,696 - INFO - cpd08021 not found in model!
2026-01-13 19:37:23,697 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:23,701 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,716 - INFO - cpd00811 not found in model!
2026-01-13 19:37:23,717 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:23,721 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,735 - INFO - cpd08021 not found in model!
2026-01-13 19:37:23,736 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:37:23,739 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,753 - INFO - cpd00811 not found in model!
2026-01-13 19:37:23,754 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:37:23,758 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,775 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,791 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,808 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,825 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,842 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,859 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,876 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,893 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,910 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,927 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,941 - INFO - cpd11632 not found in model!
2026-01-13 19:37:23,942 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:37:23,946 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,960 - INFO - cpd08701 not found in model!
2026-01-13 19:37:23,960 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:37:23,961 - INFO - cpd01024 not found in model!
2026-01-13 19:37:23,962 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:23,966 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:23,980 - INFO - cpd01024 not found in model!
2026-01-13 19:37:23,981 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:23,986 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:24,002 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:24,020 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:24,033 - INFO - cpd00187 not found in model!
2026-01-13 19:37:24,034 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:37:24,039 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:24,056 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:24,073 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:37:24,378 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:37:25,412 - INFO -   Saved gapfilled model: gapfilled_models2/Christensenellaceae_R-7_group.11_gf.xml
2026-01-13 19:37:25,417 - INFO -   Total reactions added: 108
2026-01-13 19:37:25,768 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:37:26,620 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:28,224 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:37:28,251 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:33,596 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:37:33,632 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:36,339 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,361 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,378 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,395 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,412 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,428 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,460 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,475 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,491 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,507 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,523 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,538 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,553 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,569 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,584 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,600 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,615 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,630 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,662 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,677 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,692 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,708 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,723 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,737 - INFO - cpd00418 not found in model!
2026-01-13 19:37:36,738 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:37:36,741 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,757 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,773 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,786 - INFO - cpd00418 not found in model!
2026-01-13 19:37:36,787 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:37:36,791 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,806 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,822 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,835 - INFO - cpd00418 not found in model!
2026-01-13 19:37:36,836 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:37:36,840 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,855 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,871 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,887 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,902 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,917 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,942 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,962 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:36,983 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,002 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,018 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,034 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,050 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,065 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,080 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,093 - INFO - cpd11632 not found in model!
2026-01-13 19:37:37,093 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:37:37,097 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,110 - INFO - cpd08701 not found in model!
2026-01-13 19:37:37,111 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:37:37,112 - INFO - cpd01024 not found in model!
2026-01-13 19:37:37,113 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:37,116 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,129 - INFO - cpd01024 not found in model!
2026-01-13 19:37:37,129 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:37:37,134 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,149 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,165 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,180 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,193 - INFO - cpd00425 not found in model!
2026-01-13 19:37:37,194 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:37:37,198 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:37:37,213 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:37,287 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:53,165 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:37:53,182 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:37:55,200 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:37:55,220 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:01,136 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:38:01,155 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:01,541 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:38:01,566 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:38:01,582 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:02,817 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:38:02,834 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:38:02,887 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:03,676 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:38:03,695 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:03,873 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:38:03,889 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:03,895 - INFO -   Saved gapfilled model: gapfilled_models2/Aeromonas.1_gf.xml
2026-01-13 19:38:03,901 - INFO -   Total reactions added: 94
2026-01-13 19:38:04,267 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:04,604 - INFO - Objective with gapfill database:34.49999999999999; min objective:0.01
2026-01-13 19:38:04,643 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:38:05,109 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:05,175 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:38:05,197 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:38:05,215 - INFO - Objective with gapfill database:19.125000000000004; min objective:0.01
2026-01-13 19:38:05,231 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:05,399 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:38:05,422 - INFO - Objective with gapfill database:1.9999999999999998; min objective:0.01
2026-01-13 19:38:05,440 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:05,896 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:38:05,916 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:06,044 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:38:06,065 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:06,747 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:38:06,764 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:08,907 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:38:08,928 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:38:08,946 - INFO - Objective with gapfill database:18.249999999999993; min objective:0.01
2026-01-13 19:38:08,962 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:09,369 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:38:09,395 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:38:09,617 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:10,343 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:38:10,365 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:10,688 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:38:10,690 - INFO -   Saved gapfilled model: gapfilled_models2/Azoarcus.4_gf.xml
2026-01-13 19:38:10,695 - INFO -   Total reactions added: 88
2026-01-13 19:38:10,709 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:10,818 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:38:10,839 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:11,024 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,046 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,063 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:38:11,063 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,080 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,097 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,113 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,130 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,146 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,163 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,179 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,196 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,213 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,229 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,245 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,261 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,278 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,294 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,310 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,327 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,359 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,375 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:11,391 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,408 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,425 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,431 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:11,441 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,451 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:11,458 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,474 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,489 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:38:11,490 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,506 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,523 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,525 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:11,539 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,552 - INFO - cpd08021 not found in model!
2026-01-13 19:38:11,553 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:38:11,557 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,571 - INFO - cpd00811 not found in model!
2026-01-13 19:38:11,571 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:38:11,575 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,589 - INFO - cpd08021 not found in model!
2026-01-13 19:38:11,590 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:38:11,593 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,606 - INFO - cpd00811 not found in model!
2026-01-13 19:38:11,607 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:38:11,611 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,628 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,644 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,660 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,676 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,692 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,708 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,725 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,742 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,758 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,774 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,788 - INFO - cpd11632 not found in model!
2026-01-13 19:38:11,788 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:38:11,793 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,806 - INFO - cpd08701 not found in model!
2026-01-13 19:38:11,807 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:38:11,808 - INFO - cpd01024 not found in model!
2026-01-13 19:38:11,809 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:11,813 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,826 - INFO - cpd01024 not found in model!
2026-01-13 19:38:11,827 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:11,831 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,847 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,863 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,877 - INFO - cpd00187 not found in model!
2026-01-13 19:38:11,878 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:38:11,882 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,898 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:11,911 - INFO - cpd00441 not found in model!
2026-01-13 19:38:11,912 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:38:11,916 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:38:11,954 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:12,228 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:38:12,252 - INFO - Objective with gapfill database:3.5000000000000004; min objective:0.01
2026-01-13 19:38:12,269 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:12,666 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:38:12,682 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:12,749 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:38:12,765 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:13,152 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:38:13,173 - INFO - Objective with gapfill database:18.249999999999993; min objective:0.01
2026-01-13 19:38:13,191 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:13,263 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:38:13,301 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:13,964 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:38:13,981 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:14,039 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:38:14,057 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:38:14,063 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:38:14,073 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:14,087 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:38:14,105 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:38:14,123 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:14,369 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:38:14,389 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:14,455 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:38:14,471 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:15,489 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:38:15,530 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:16,107 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:38:16,131 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:16,973 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,021 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,038 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,055 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,072 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,089 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,106 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,122 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,157 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,174 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:17,191 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,208 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,231 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:38:17,242 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,251 - INFO - Objective with gapfill database:0.7499999999999998; min objective:0.01
2026-01-13 19:38:17,259 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,270 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:17,276 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,292 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,309 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,326 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,361 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,377 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,394 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,411 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,427 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,460 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,477 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,495 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,511 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,525 - INFO - cpd08021 not found in model!
2026-01-13 19:38:17,526 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:38:17,530 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,543 - INFO - cpd00811 not found in model!
2026-01-13 19:38:17,544 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:38:17,548 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,562 - INFO - cpd08021 not found in model!
2026-01-13 19:38:17,563 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:38:17,567 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,581 - INFO - cpd00811 not found in model!
2026-01-13 19:38:17,581 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:38:17,585 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,602 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,619 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,636 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,653 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,670 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,687 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,704 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,721 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,739 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,756 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,769 - INFO - cpd11632 not found in model!
2026-01-13 19:38:17,771 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:38:17,775 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,788 - INFO - cpd08701 not found in model!
2026-01-13 19:38:17,789 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:38:17,790 - INFO - cpd01024 not found in model!
2026-01-13 19:38:17,791 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:17,796 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,809 - INFO - cpd01024 not found in model!
2026-01-13 19:38:17,810 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:17,815 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,831 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,848 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,861 - INFO - cpd00187 not found in model!
2026-01-13 19:38:17,862 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:38:17,866 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,883 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:17,897 - INFO - cpd00441 not found in model!
2026-01-13 19:38:17,897 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:38:17,901 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:18,872 - INFO - Objective with gapfill database:34.500000000000014; min objective:0.01
2026-01-13 19:38:18,908 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:19,763 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:38:19,788 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:20,002 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:38:20,020 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:38:20,035 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:21,678 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:38:21,697 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:38:21,714 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:22,682 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:38:22,706 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:22,898 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:38:22,917 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:38:22,932 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:38:22,947 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:23,122 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:38:23,141 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:24,362 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:38:24,379 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:24,860 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:24,883 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:24,901 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:24,919 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:24,937 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:24,955 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:24,973 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:24,991 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,008 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,027 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,045 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,064 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,082 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,100 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,118 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,142 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,161 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,178 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,196 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,214 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,231 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,249 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,267 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,285 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,302 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,321 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,339 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,357 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,375 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,393 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,411 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,428 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:25,443 - INFO - cpd08021 not found in model!
2026-01-13 19:38:25,444 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:38:25,449 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,467 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,481 - INFO - cpd08021 not found in model!
2026-01-13 19:38:25,482 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:38:25,485 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:38:25,486 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 19:38:25,506 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,508 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:38:25,524 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,526 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:25,542 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,559 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,578 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,596 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,614 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,632 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,650 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,667 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,685 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,699 - INFO - cpd11632 not found in model!
2026-01-13 19:38:25,701 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:38:25,705 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,720 - INFO - cpd01024 not found in model!
2026-01-13 19:38:25,720 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:25,725 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,739 - INFO - cpd01024 not found in model!
2026-01-13 19:38:25,740 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:25,744 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,761 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,779 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,793 - INFO - cpd00187 not found in model!
2026-01-13 19:38:25,794 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:38:25,798 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,812 - INFO - cpd00425 not found in model!
2026-01-13 19:38:25,813 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:38:25,818 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:25,835 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:26,268 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:38:26,294 - INFO - Objective with gapfill database:17.500000000000018; min objective:0.01
2026-01-13 19:38:26,314 - INFO - Objective with gapfill database:19.125000000000018; min objective:0.01
2026-01-13 19:38:26,333 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:26,438 - INFO - Objective with gapfill database:34.50000000000004; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:26,475 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:26,514 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:38:26,536 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:38:26,554 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:26,883 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:38:26,904 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:27,331 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:38:27,349 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:27,880 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:27,904 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:38:27,906 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 19:38:27,925 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:27,930 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:38:27,943 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:27,947 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:27,962 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:27,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:27,999 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,017 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,035 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,054 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,073 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,092 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,110 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,128 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,146 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,165 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,183 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,201 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,219 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,237 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,255 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,273 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,291 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,309 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,327 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,346 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,364 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,382 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,401 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,420 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,438 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,456 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,474 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,493 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:28,511 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,547 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,560 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:38:28,565 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,584 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,588 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:28,602 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,620 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,639 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,657 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,676 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,697 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,718 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,735 - INFO - cpd11632 not found in model!
2026-01-13 19:38:28,736 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:38:28,741 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,758 - INFO - cpd08701 not found in model!
2026-01-13 19:38:28,759 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:38:28,760 - INFO - cpd01024 not found in model!
2026-01-13 19:38:28,761 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:28,766 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,783 - INFO - cpd01024 not found in model!
2026-01-13 19:38:28,784 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:28,789 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,810 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,830 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,848 - INFO - cpd00187 not found in model!
2026-01-13 19:38:28,849 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:38:28,854 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,873 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:28,892 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:28,956 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:38:28,975 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:29,787 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:31,113 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,138 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,157 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,175 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,193 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,210 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:31,228 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,246 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,263 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,264 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:38:31,281 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,285 - INFO - Objective with gapfill database:18.25000000000003; min objective:0.01
2026-01-13 19:38:31,299 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,302 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:38:31,316 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,334 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,352 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,370 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,388 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,406 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,424 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,441 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,458 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,476 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,494 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,511 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,547 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,565 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,583 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,609 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,628 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,665 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,683 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,702 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,720 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,738 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,756 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,775 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,793 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,811 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,830 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,848 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,867 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,885 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,904 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,922 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,941 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,956 - INFO - cpd11632 not found in model!
2026-01-13 19:38:31,957 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:38:31,962 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:31,977 - INFO - cpd08701 not found in model!
2026-01-13 19:38:31,979 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:38:31,979 - INFO - cpd01024 not found in model!
2026-01-13 19:38:31,980 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:31,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:32,001 - INFO - cpd01024 not found in model!
2026-01-13 19:38:32,001 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:38:32,005 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:32,024 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:32,042 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:32,056 - INFO - cpd00187 not found in model!
2026-01-13 19:38:32,057 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:38:32,061 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:32,079 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:38:32,097 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:32,477 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:38:32,497 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:34,129 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:38:34,153 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:34,997 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:38:35,022 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:39,325 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:38:39,357 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:38:43,421 - INFO - Objective with gapfill database:34.49999999999999; min objective:0.01
2026-01-13 19:38:43,458 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:09,287 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:39:09,306 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:39:09,322 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:39:09,336 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:10,320 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:39:10,337 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:13,829 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:39:13,850 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:39:13,868 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:14,655 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:39:14,677 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:39:14,693 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:16,307 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:39:16,330 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:39:16,347 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:17,921 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:39:17,938 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:18,719 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:39:18,740 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:39:18,755 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:18,959 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:39:18,979 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:19,067 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:39:19,087 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:19,986 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:39:20,003 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:21,755 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,780 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,800 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,818 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,836 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,855 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,874 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,892 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,911 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,929 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,948 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,966 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:21,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,021 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,039 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,057 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,077 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,096 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,115 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,133 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,151 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,170 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,188 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,206 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:22,243 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:22,261 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,267 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:39:22,280 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,287 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:22,298 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,301 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:39:22,317 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,318 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:39:22,332 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:22,335 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,353 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,376 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,401 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,423 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,442 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,461 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,480 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,498 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,535 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,559 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,578 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,598 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,616 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,632 - INFO - cpd11632 not found in model!
2026-01-13 19:39:22,633 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:39:22,637 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,656 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,674 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,692 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,711 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,728 - INFO - cpd00187 not found in model!
2026-01-13 19:39:22,730 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:39:22,735 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,752 - INFO - cpd00425 not found in model!
2026-01-13 19:39:22,753 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:39:22,757 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:22,778 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:23,672 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:39:23,692 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:26,505 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:39:26,522 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:27,209 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,236 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,237 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:27,257 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,264 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:27,277 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,284 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:39:27,297 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,303 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:27,317 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,336 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,355 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:27,381 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,401 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,409 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:39:27,420 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,425 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:27,440 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,478 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,497 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,535 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,554 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,573 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,593 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:27,612 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,631 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,648 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:39:27,650 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 19:39:27,669 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,671 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:39:27,688 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:27,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,709 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,728 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,748 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,767 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,786 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:27,806 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,825 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,838 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:39:27,844 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,862 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:27,864 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,883 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,902 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,921 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,940 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,959 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,978 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:27,997 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,017 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,036 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,055 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,074 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,094 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,110 - INFO - cpd11632 not found in model!
2026-01-13 19:39:28,111 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:39:28,116 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,132 - INFO - cpd08701 not found in model!
2026-01-13 19:39:28,133 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:39:28,134 - INFO - cpd01024 not found in model!
2026-01-13 19:39:28,135 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:39:28,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,156 - INFO - cpd01024 not found in model!
2026-01-13 19:39:28,157 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:39:28,162 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,180 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,199 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,215 - INFO - cpd00187 not found in model!
2026-01-13 19:39:28,216 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:39:28,221 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,240 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,259 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:28,576 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:39:28,611 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:28,712 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:39:28,739 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:28,793 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,819 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,840 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,860 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,881 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,902 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,922 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,942 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,962 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:28,982 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,023 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,043 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,064 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,084 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,104 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,124 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,144 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,184 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,204 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,224 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,243 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,263 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,283 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,303 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,323 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,343 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,363 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,383 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,403 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,423 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,444 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,464 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,484 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,504 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,524 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,544 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,565 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,585 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,605 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,626 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:29,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,667 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,684 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:39:29,687 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:29,707 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:29,720 - INFO - Objective with gapfill database:18.25; min objective:0.01
2026-01-13 19:39:29,723 - INFO - cpd11632 not found in model!
2026-01-13 19:39:29,724 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:39:29,729 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,736 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:39:29,745 - INFO - cpd08701 not found in model!
2026-01-13 19:39:29,746 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:39:29,747 - INFO - cpd01024 not found in model!
2026-01-13 19:39:29,748 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:39:29,750 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:29,752 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,754 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:39:29,768 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0
2026-01-13 19:39:29,768 - INFO - cpd01024 not found in model!
2026-01-13 19:39:29,769 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:39:29,769 - INFO - Objective with gapfill database:3.5; min objective:0.01

Removing ungapfillable media Ac.O2

2026-01-13 19:39:29,774 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,784 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:29,793 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:29,794 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,814 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,831 - INFO - cpd00187 not found in model!
2026-01-13 19:39:29,832 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:39:29,836 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,853 - INFO - cpd00425 not found in model!
2026-01-13 19:39:29,854 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:39:29,858 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:29,878 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:30,553 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:39:30,573 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:39:30,589 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:30,605 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:30,642 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:39:30,665 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:30,720 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:39:30,739 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:39:30,756 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:30,972 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:39:30,992 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:31,122 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:39:31,145 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:39:31,163 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:31,867 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:39:31,888 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:32,314 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:39:32,330 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:32,827 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:39:32,853 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:33,085 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:39:33,107 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:33,359 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:39:33,383 - INFO - Objective with gapfill database:17.500000000000025; min objective:0.01
2026-01-13 19:39:33,403 - INFO - Objective with gapfill database:18.25000000000002; min objective:0.01
2026-01-13 19:39:33,422 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:35,239 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:39:35,256 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:35,279 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:35,302 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:39:35,318 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:35,381 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:39:35,400 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:35,850 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:39:35,867 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:36,074 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,105 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,126 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,147 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,167 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,187 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,208 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,228 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,248 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,269 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,289 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,310 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,331 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,351 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,372 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,392 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,413 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,433 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,453 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,472 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,493 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,513 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,534 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,562 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,585 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,606 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,626 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,647 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,668 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,688 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,708 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,728 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,748 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,768 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,788 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,808 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,829 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,849 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,870 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,890 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,910 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,931 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,951 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,972 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:36,993 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:37,013 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:37,030 - INFO - cpd11632 not found in model!
2026-01-13 19:39:37,031 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:39:37,036 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:37,052 - INFO - cpd08701 not found in model!
2026-01-13 19:39:37,053 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:39:37,054 - INFO - cpd01024 not found in model!
2026-01-13 19:39:37,055 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:39:37,060 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:37,077 - INFO - cpd01024 not found in model!
2026-01-13 19:39:37,078 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:39:37,083 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:37,103 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:37,123 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:37,144 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:37,164 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:39:37,184 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:37,910 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:39:37,931 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:39:37,949 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:39,214 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:39:39,233 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:39:39,250 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:39:39,267 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:39,500 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:39:39,522 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:39,581 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:39,600 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:39,643 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:39:39,674 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:39:39,697 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:40,038 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:40,061 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:39:40,079 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:40,094 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:39:40,112 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:41,592 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:39:41,623 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:42,545 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:39:42,563 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:39:42,579 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:39:42,593 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:44,265 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:39:44,285 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:44,746 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:39:44,775 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:44,795 - INFO - Objective with gapfill database:18.249999999999993; min objective:0.01
2026-01-13 19:39:44,815 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:44,826 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:39:44,846 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:39:44,866 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:45,153 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:45,579 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:39:45,598 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:45,744 - WARNING - No gapfilling solution found before filtering for Akg activating rxn00062_c0

Removing ungapfillable media Akg

2026-01-13 19:39:45,762 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:46,077 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:39:46,112 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:46,993 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:39:47,014 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:39:47,032 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:47,307 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:39:47,332 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:39:47,354 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:48,711 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:39:48,736 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:39:48,753 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:39:48,769 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:49,843 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:39:49,863 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:50,079 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:52,685 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:39:52,715 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:39:52,736 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:52,848 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:39:52,874 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:52,895 - INFO - Objective with gapfill database:18.249999999999993; min objective:0.01
2026-01-13 19:39:52,916 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:39:52,933 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:39:52,956 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:53,155 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:39:53,178 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:39:53,197 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:53,564 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:39:53,601 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:56,225 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:39:56,252 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:39:56,274 - INFO - Objective with gapfill database:18.249999999999993; min objective:0.01
2026-01-13 19:39:56,296 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:57,059 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:39:57,084 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:57,953 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:39:57,981 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:39:59,035 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:39:59,061 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:05,414 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:40:05,443 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:24,642 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:40:24,668 - INFO - Objective with gapfill database:17.499999999999996; min objective:0.01
2026-01-13 19:40:24,689 - INFO - Objective with gapfill database:18.249999999999996; min objective:0.01
2026-01-13 19:40:24,709 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:38,962 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:40:38,978 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:41,903 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:40:41,926 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:44,386 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:40:44,404 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:45,732 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:40:45,752 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:40:45,770 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:48,687 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:40:48,703 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:49,729 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:40:49,745 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:49,933 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:40:49,953 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:50,047 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:40:50,065 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:52,243 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:40:52,263 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:40:52,279 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:52,457 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:40:52,477 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:52,809 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:40:52,826 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:52,875 - WARNING - No gapfilling solution found before filtering for Akg activating rxn00062_c0

Removing ungapfillable media Akg

2026-01-13 19:40:52,894 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:53,177 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:40:53,195 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:56,105 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:40:56,126 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:56,339 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:40:56,358 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:57,092 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:40:57,129 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:58,060 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:40:58,068 - INFO - cpd11632 not found in model!
2026-01-13 19:40:58,068 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:40:58,077 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:58,405 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:40:58,422 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:40:59,528 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:40:59,544 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:40:59,550 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:40:59,567 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:40:59,571 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:40:59,584 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:40:59,595 - INFO - Objective with gapfill database:18.250000000000004; min objective:0.01
2026-01-13 19:40:59,618 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:09,020 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:41:09,043 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:10,850 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:41:10,872 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:41:10,890 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:11,237 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:41:11,257 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:11,679 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:41:11,698 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:12,059 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:41:12,068 - INFO - cpd11632 not found in model!
2026-01-13 19:41:12,069 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:41:12,077 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:12,331 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:12,352 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:41:12,371 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:12,387 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:41:12,393 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:41:12,407 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:41:12,416 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:12,425 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:12,500 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:41:12,522 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:41:12,541 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:12,824 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:41:12,840 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:13,132 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:41:13,149 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:15,675 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:41:15,702 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:20,647 - INFO - Objective with gapfill database:34.5; min objective:0.01
2026-01-13 19:41:20,684 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:20,749 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:41:20,769 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:25,902 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:26,595 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:26,616 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:41:26,633 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:26,659 - WARNING - No gapfilling solution found before filtering for Akg activating rxn00062_c0

Removing ungapfillable media Akg

2026-01-13 19:41:26,685 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:29,572 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:41:29,600 - INFO - Objective with gapfill database:17.500000000000018; min objective:0.01
2026-01-13 19:41:29,624 - INFO - Objective with gapfill database:18.25000000000002; min objective:0.01
2026-01-13 19:41:29,648 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:30,643 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:41:30,670 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:30,711 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:41:30,720 - INFO - cpd01024 not found in model!
2026-01-13 19:41:30,721 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:41:30,730 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:30,987 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:41:31,006 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:33,104 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:41:33,125 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:34,017 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:41:34,564 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:41:34,584 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:35,438 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:41:35,463 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:36,275 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:41:36,296 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:37,375 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:41:37,406 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:38,540 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:41:38,550 - INFO - cpd01024 not found in model!
2026-01-13 19:41:38,551 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:41:38,559 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:39,937 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:41:39,954 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:39,974 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:41:39,992 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:41:40,010 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:41:40,027 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:40,253 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:41,074 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:41:41,099 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:41:41,120 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:42,475 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:41:42,501 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:41:42,504 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:42,527 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:42,528 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:42,570 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:41:42,591 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:41:42,608 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:44,474 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:41:44,503 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:44,793 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:41:44,809 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:45,740 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:41:45,758 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:46,096 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:46,114 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:46,145 - WARNING - No gapfilling solution found before filtering for Akg activating rxn00062_c0

Removing ungapfillable media Akg

2026-01-13 19:41:46,151 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:41:46,165 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:46,172 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:41:46,190 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:46,651 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:41:46,655 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:41:46,656 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:41:46,672 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:46,677 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:46,681 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:41:46,701 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:47,550 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:41:47,571 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:47,674 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:41:47,701 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:48,775 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:41:48,808 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:49,469 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:41:49,504 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:49,884 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:41:49,906 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:50,139 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:41:50,160 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:41:50,178 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:50,587 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:41:50,625 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:50,995 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:41:51,014 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:51,569 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:41:51,589 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:52,240 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:41:52,272 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:52,386 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:41:52,406 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:52,959 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:41:52,979 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:53,480 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:41:53,504 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:41:53,524 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:53,668 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:41:53,702 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:41:53,726 - INFO - Objective with gapfill database:18.249999999999993; min objective:0.01
2026-01-13 19:41:53,750 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:54,488 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:41:54,508 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:55,986 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:41:56,012 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:57,397 - WARNING - No gapfilling solution found before filtering for For.O2 activating rxn00062_c0

Removing ungapfillable media For.O2

2026-01-13 19:41:57,435 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:57,565 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:41:57,601 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:41:59,093 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:41:59,094 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:41:59,118 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:41:59,121 - INFO - Objective with gapfill database:3.5000000000000018; min objective:0.01
2026-01-13 19:41:59,138 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:41:59,143 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:42:01,759 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:42:01,776 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:42:02,174 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:42:02,211 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:42:02,233 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:42:08,715 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:42:08,746 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:01,394 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:43:01,410 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:01,800 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:43:01,819 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:02,121 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:43:02,139 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:04,997 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:43:05,006 - INFO - cpd00425 not found in model!
2026-01-13 19:43:05,007 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:43:05,015 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:09,945 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:43:09,955 - INFO - cpd00425 not found in model!
2026-01-13 19:43:09,955 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:43:09,965 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:11,614 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:43:11,622 - INFO - cpd11632 not found in model!
2026-01-13 19:43:11,623 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:43:11,632 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:11,852 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:43:11,871 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:43:11,887 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:43:11,902 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:12,205 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:43:12,240 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:13,312 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:43:13,324 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:43:13,329 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:13,345 - INFO - Objective with gapfill database:30.5; min objective:0.01
2026-01-13 19:43:13,370 - INFO - Initial solution: {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bab760>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:43:13,372 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:43:13,374 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:13,376 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:43:13,378 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:43:13,380 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:43:13,381 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:43:13,382 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed']]
2026-01-13 19:43:13,398 - INFO - Glc.O2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:5
2026-01-13 19:43:13,399 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:5
2026-01-13 19:43:13,401 - INFO - Glc.O2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:5
2026-01-13 19:43:13,402 - INFO - Glc.O2/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:5
2026-01-13 19:43:13,403 - INFO - Glc.O2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:5
2026-01-13 19:43:13,404 - INFO - Glc.O2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:5
2026-01-13 19:43:13,406 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bab760>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn00171_c0': '<'}}
2026-01-13 19:43:13,407 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bab760>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:43:13,411 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed']]
2026-01-13 19:43:13,431 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:14,528 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:43:14,556 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:15,416 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:43:15,444 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:15,677 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:43:15,698 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:16,305 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:43:16,323 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:16,780 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:16,800 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0
2026-01-13 19:43:16,801 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01

Removing ungapfillable media Succ

2026-01-13 19:43:16,819 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:16,820 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:43:16,838 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:16,845 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:43:16,869 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:17,385 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:43:17,411 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:17,565 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:43:17,589 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:17,968 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:43:17,989 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:18,591 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:18,614 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:43:18,639 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn01975_c0': '>', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c426f20>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:43:18,641 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:43:18,643 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:43:18,645 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:43:18,646 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:18,647 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:43:18,649 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:43:18,650 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:43:18,651 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:43:18,652 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:43:18,654 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:43:18,655 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:43:18,656 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:43:18,656 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0
2026-01-13 19:43:18,657 - INFO - integrating rxn: rxn00799_c0

Removing ungapfillable media Ac

2026-01-13 19:43:18,659 - INFO - integrating rxn: rxn00250_c0

2026-01-13 19:43:18,660 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:43:18,673 - INFO - Glc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:5
2026-01-13 19:43:18,675 - INFO - Glc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:5
2026-01-13 19:43:18,676 - INFO - Glc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:5
2026-01-13 19:43:18,677 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:5
2026-01-13 19:43:18,678 - INFO - Glc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:5
2026-01-13 19:43:18,679 - INFO - Glc.O2/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:5
2026-01-13 19:43:18,680 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:43:18,680 - INFO - Glc.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:5
2026-01-13 19:43:18,681 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:18,681 - INFO - Glc.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:5
2026-01-13 19:43:18,683 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:43:18,683 - INFO - Glc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:5
2026-01-13 19:43:18,684 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:43:18,685 - INFO - Glc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:5
2026-01-13 19:43:18,686 - INFO - Glc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:5
2026-01-13 19:43:18,688 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c426f20>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn01975_c0': '>', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:43:18,689 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn01975_c0': '>', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c426f20>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:43:18,693 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:43:18,713 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:19,298 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:43:19,334 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:19,479 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:43:19,499 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:20,350 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:43:20,374 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:21,317 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:21,344 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:43:21,366 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:21,379 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:43:21,387 - INFO - cpd01024 not found in model!
2026-01-13 19:43:21,388 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:43:21,397 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:21,753 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:43:21,777 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:43:21,784 - INFO - Objective with gapfill database:17.125; min objective:0.01
2026-01-13 19:43:21,797 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:21,809 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00974_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08556_c0': '>', 'rxn14425_c0': '>', 'rxn00148_c0': '<', 'rxn00248_c0': '>', 'rxn01388_c0': '<', 'rxn00250_c0': '<', 'rxn14426_c0': '>', 'rxn10122_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0babe80>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:43:21,811 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:43:21,813 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:43:21,814 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:43:21,816 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:43:21,818 - INFO - integrating rxn: rxn00974_c0
2026-01-13 19:43:21,819 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:43:21,820 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:21,821 - INFO - integrating rxn: rxn08556_c0
2026-01-13 19:43:21,823 - INFO - integrating rxn: rxn14425_c0
2026-01-13 19:43:21,824 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:43:21,825 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:43:21,827 - INFO - integrating rxn: rxn01388_c0
2026-01-13 19:43:21,828 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:21,829 - INFO - integrating rxn: rxn14426_c0
2026-01-13 19:43:21,831 - INFO - integrating rxn: rxn10122_c0
2026-01-13 19:43:21,832 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:43:21,833 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new']]
2026-01-13 19:43:21,840 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:43:21,841 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:43:21,842 - INFO - Glyc.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:43:21,843 - INFO - Glyc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:43:21,844 - INFO - Glyc.O2/rxn00062_c0:rxn00974_c0> needed:0.0 with min obj:2
2026-01-13 19:43:21,845 - INFO - Glyc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:43:21,845 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:43:21,846 - INFO - Glyc.O2/rxn00062_c0:rxn08556_c0> needed:0.0 with min obj:2
2026-01-13 19:43:21,847 - INFO - Glyc.O2/rxn00062_c0:rxn14425_c0> needed:0.0 with min obj:2
2026-01-13 19:43:21,848 - INFO - Glyc.O2/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:2
2026-01-13 19:43:21,849 - INFO - Glyc.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:2
2026-01-13 19:43:21,850 - INFO - Glyc.O2/rxn00062_c0:rxn01388_c0< needed:0.0 with min obj:2
2026-01-13 19:43:21,850 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:43:21,851 - INFO - Glyc.O2/rxn00062_c0:rxn14426_c0> needed:0.0 with min obj:2
2026-01-13 19:43:21,852 - INFO - Glyc.O2/rxn00062_c0:rxn10122_c0> needed:0.0 with min obj:2
2026-01-13 19:43:21,853 - INFO - Glyc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:43:21,858 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0babe80>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00974_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08556_c0': '>', 'rxn14425_c0': '>', 'rxn00148_c0': '<', 'rxn00248_c0': '>', 'rxn01388_c0': '<', 'rxn00250_c0': '<', 'rxn14426_c0': '>', 'rxn10122_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:43:21,858 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00974_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08556_c0': '>', 'rxn14425_c0': '>', 'rxn00148_c0': '<', 'rxn00248_c0': '>', 'rxn01388_c0': '<', 'rxn00250_c0': '<', 'rxn14426_c0': '>', 'rxn10122_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0babe80>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:43:21,862 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new']]
2026-01-13 19:43:21,880 - INFO - Objective with gapfill database:15.5; min objective:0.01
2026-01-13 19:43:21,904 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00171_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00248_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fabff4d390>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:43:21,906 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:43:21,907 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:43:21,908 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:43:21,909 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:21,910 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:43:21,911 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:43:21,911 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:21,912 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:43:21,913 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:43:21,913 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:43:21,914 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:43:21,915 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:43:21,921 - INFO - Fum.O2/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:3
2026-01-13 19:43:21,921 - INFO - Fum.O2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:3
2026-01-13 19:43:21,922 - INFO - Fum.O2/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:3
2026-01-13 19:43:21,923 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:43:21,924 - INFO - Fum.O2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:3
2026-01-13 19:43:21,925 - INFO - Fum.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:3
2026-01-13 19:43:21,926 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:43:21,927 - INFO - Fum.O2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:3
2026-01-13 19:43:21,927 - INFO - Fum.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:3
2026-01-13 19:43:21,928 - INFO - Fum.O2/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:3
2026-01-13 19:43:21,929 - INFO - Fum.O2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:3
2026-01-13 19:43:21,934 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fabff4d390>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00248_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn05319_c0': '>', 'rxn00171_c0': '<'}}
2026-01-13 19:43:21,935 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00171_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00248_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fabff4d390>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:43:21,937 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:43:21,956 - INFO - Objective with gapfill database:17.125; min objective:0.01
2026-01-13 19:43:21,979 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00036_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn14426_c0': '>', 'rxn10122_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0d47fa0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:43:21,982 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:43:21,982 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:43:21,983 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:43:21,984 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:43:21,985 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:21,986 - INFO - integrating rxn: rxn14425_c0
2026-01-13 19:43:21,987 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:43:21,988 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:43:21,989 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:21,990 - INFO - integrating rxn: rxn14426_c0
2026-01-13 19:43:21,991 - INFO - integrating rxn: rxn10122_c0
2026-01-13 19:43:21,992 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:43:21,992 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:43:21,994 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new']]
2026-01-13 19:43:22,000 - INFO - Succ.O2/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:2
2026-01-13 19:43:22,001 - INFO - Succ.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,002 - INFO - Succ.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,004 - INFO - Succ.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,004 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,005 - INFO - Succ.O2/rxn00062_c0:rxn14425_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,006 - INFO - Succ.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,007 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,008 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,009 - INFO - Succ.O2/rxn00062_c0:rxn14426_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,009 - INFO - Succ.O2/rxn00062_c0:rxn10122_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,010 - INFO - Succ.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,011 - INFO - Succ.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,016 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0d47fa0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn14426_c0': '>', 'rxn10122_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:43:22,017 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00036_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn14426_c0': '>', 'rxn10122_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0d47fa0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:43:22,020 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new']]
2026-01-13 19:43:22,039 - INFO - Objective with gapfill database:14.25; min objective:0.01
2026-01-13 19:43:22,063 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00248_c0': '>', 'rxn00499_c0': '>', 'rxn00250_c0': '<', 'rxn14426_c0': '>', 'rxn10122_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0defd30>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:43:22,065 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:43:22,066 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:43:22,068 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:43:22,069 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:43:22,070 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:43:22,071 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:22,071 - INFO - integrating rxn: rxn14425_c0
2026-01-13 19:43:22,072 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:43:22,074 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:43:22,075 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:22,075 - INFO - integrating rxn: rxn14426_c0
2026-01-13 19:43:22,076 - INFO - integrating rxn: rxn10122_c0
2026-01-13 19:43:22,077 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:43:22,078 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:43:22,079 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:43:22,083 - INFO - cpd00159 not found in model!
2026-01-13 19:43:22,083 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:43:22,086 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:43:22,087 - INFO - LLac.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,088 - INFO - LLac.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,089 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,090 - INFO - LLac.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,091 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,091 - INFO - LLac.O2/rxn00062_c0:rxn14425_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,092 - INFO - LLac.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,093 - INFO - LLac.O2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,094 - INFO - LLac.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,095 - INFO - LLac.O2/rxn00062_c0:rxn14426_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,096 - INFO - LLac.O2/rxn00062_c0:rxn10122_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,097 - INFO - LLac.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:2
2026-01-13 19:43:22,097 - INFO - LLac.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:43:22,102 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0defd30>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00248_c0': '>', 'rxn00499_c0': '>', 'rxn00250_c0': '<', 'rxn14426_c0': '>', 'rxn10122_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:43:22,103 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00248_c0': '>', 'rxn00499_c0': '>', 'rxn00250_c0': '<', 'rxn14426_c0': '>', 'rxn10122_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0defd30>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:43:22,106 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:43:22,125 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:23,511 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:43:23,532 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:43:23,550 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:23,997 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:43:24,024 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:24,527 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:43:24,545 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:24,550 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:43:24,558 - INFO - cpd11632 not found in model!
2026-01-13 19:43:24,559 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:43:24,568 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:25,521 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0
2026-01-13 19:43:25,522 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media mal-LRemoving ungapfillable media Dlac.O2

2026-01-13 19:43:25,542 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:25,550 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:43:25,564 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:43:25,572 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:25,603 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:26,247 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:43:26,269 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:43:26,284 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:43:26,299 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:27,262 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:43:27,282 - INFO - Objective with gapfill database:19.124999999999986; min objective:0.01
2026-01-13 19:43:27,306 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c427730>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:43:27,309 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:43:27,310 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:43:27,311 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:43:27,312 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:43:27,313 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:27,315 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:43:27,316 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:43:27,316 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:43:27,317 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:43:27,318 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:43:27,319 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:43:27,320 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:43:27,321 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:27,322 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:43:27,328 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:43:27,329 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,330 - INFO - Glyc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,331 - INFO - Glyc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,331 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,332 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,333 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,334 - INFO - Glyc.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,335 - INFO - Glyc.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,336 - INFO - Glyc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,336 - INFO - Glyc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,337 - INFO - Glyc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,338 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,343 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c427730>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:43:27,344 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c427730>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:43:27,346 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:43:27,373 - INFO - Objective with gapfill database:17.5; min objective:0.01
2026-01-13 19:43:27,396 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c427a60>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:43:27,398 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:43:27,399 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:43:27,400 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:43:27,401 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:43:27,402 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:27,403 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:43:27,403 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:43:27,405 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:43:27,405 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:43:27,406 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:43:27,407 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:27,408 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:43:27,414 - INFO - Fum.O2/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:3
2026-01-13 19:43:27,415 - INFO - Fum.O2/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:3
2026-01-13 19:43:27,415 - INFO - Fum.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:3
2026-01-13 19:43:27,416 - INFO - Fum.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:3
2026-01-13 19:43:27,417 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:43:27,418 - INFO - Fum.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:3
2026-01-13 19:43:27,419 - INFO - Fum.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:3
2026-01-13 19:43:27,420 - INFO - Fum.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:3
2026-01-13 19:43:27,421 - INFO - Fum.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:3
2026-01-13 19:43:27,422 - INFO - Fum.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:3
2026-01-13 19:43:27,422 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:43:27,427 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c427a60>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:43:27,428 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c427a60>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:43:27,431 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:43:27,449 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:43:27,472 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c427c40>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:43:27,474 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:43:27,475 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:43:27,476 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:43:27,477 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:27,479 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:43:27,480 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:43:27,481 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:43:27,482 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:43:27,483 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:43:27,483 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:43:27,484 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:27,485 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:43:27,491 - INFO - Succ.O2/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:2
2026-01-13 19:43:27,492 - INFO - Succ.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,492 - INFO - Succ.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,493 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,494 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,495 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,496 - INFO - Succ.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,497 - INFO - Succ.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,498 - INFO - Succ.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,499 - INFO - Succ.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,499 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,504 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c427c40>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:43:27,505 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c427c40>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:43:27,510 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:43:27,529 - INFO - Objective with gapfill database:16.250000000000018; min objective:0.01
2026-01-13 19:43:27,552 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00499_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fabca46110>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:43:27,555 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:43:27,556 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:43:27,558 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:43:27,558 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:43:27,560 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:27,561 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:43:27,563 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:43:27,564 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:43:27,565 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:43:27,566 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:43:27,567 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:43:27,568 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:27,569 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:43:27,573 - INFO - cpd00159 not found in model!
2026-01-13 19:43:27,574 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:43:27,577 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:43:27,578 - INFO - LLac.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,579 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,580 - INFO - LLac.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,581 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,582 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,583 - INFO - LLac.O2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,584 - INFO - LLac.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,585 - INFO - LLac.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,586 - INFO - LLac.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:43:27,587 - INFO - LLac.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,587 - INFO - LLac.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:43:27,592 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fabca46110>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00499_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:43:27,593 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00499_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fabca46110>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:43:27,598 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:43:27,617 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:27,724 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:43:27,754 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:29,146 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:43:29,165 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:29,923 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:43:29,951 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:30,336 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:43:30,362 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:30,450 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:43:30,470 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:43:30,495 - INFO - Initial solution: {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bf0310>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:43:30,498 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:43:30,499 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:30,500 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:43:30,501 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:43:30,502 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:43:30,503 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:43:30,504 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:43:30,510 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:43:30,511 - INFO - Glc/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:30,512 - INFO - Glc/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:30,514 - INFO - Glc/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:30,514 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:43:30,515 - INFO - Glc/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:30,521 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bf0310>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn00171_c0': '<'}}
2026-01-13 19:43:30,521 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bf0310>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:43:30,526 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:43:30,544 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:30,609 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:43:30,630 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:30,849 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:43:30,867 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:43:30,883 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:43:30,899 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:31,149 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:43:31,166 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:31,623 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:43:31,644 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:31,823 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:43:31,847 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:43:31,866 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:32,294 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 19:43:32,339 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:33,718 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:43:33,743 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:33,909 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:33,931 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:33,975 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:43:33,992 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:43:34,008 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:34,013 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:34,687 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:43:34,696 - INFO - cpd01024 not found in model!
2026-01-13 19:43:34,697 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:43:34,706 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:34,896 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:43:34,923 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:35,078 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:43:35,098 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:35,512 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:43:35,533 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:35,702 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:43:35,722 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:36,070 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:43:36,090 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:36,110 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:43:36,129 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:36,211 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:43:36,231 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:43:36,254 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c6a7ac0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:43:36,257 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:43:36,258 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:36,260 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:43:36,262 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:43:36,263 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:43:36,264 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:43:36,265 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:43:36,266 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:36,267 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:43:36,273 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:43:36,274 - INFO - Glc/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:36,275 - INFO - Glc/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:36,276 - INFO - Glc/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:36,277 - INFO - Glc/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:0.01
2026-01-13 19:43:36,278 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:43:36,279 - INFO - Glc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:36,280 - INFO - Glc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:36,285 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c6a7ac0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:43:36,285 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c6a7ac0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:43:36,289 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:43:36,308 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:36,485 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:43:36,517 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:43:36,543 - INFO - Objective with gapfill database:18.249999999999993; min objective:0.01
2026-01-13 19:43:36,580 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:37,253 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:43:37,271 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:37,765 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:43:37,794 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:38,888 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:43:38,907 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:39,327 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:43:39,344 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:39,440 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:43:39,466 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:39,550 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:43:39,577 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:39,919 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:43:39,944 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:40,755 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:43:40,774 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:40,922 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:43:40,932 - INFO - cpd00425 not found in model!
2026-01-13 19:43:40,933 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:43:40,943 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:41,078 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:43:41,107 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:41,209 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:43:41,234 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:43:41,254 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:42,316 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:43:42,335 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:42,854 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:43:42,878 - INFO - Objective with gapfill database:2.0000000000000004; min objective:0.01
2026-01-13 19:43:42,898 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:43,035 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:43:43,064 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:43:43,087 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:43,731 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:43:43,752 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:43:43,770 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:44,740 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:43:44,756 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:44,939 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:43:44,958 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:46,118 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:43:46,140 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:46,263 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:43:46,289 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:47,180 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:43:47,225 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:43:47,253 - INFO - Objective with gapfill database:18.250000000000004; min objective:0.01
2026-01-13 19:43:47,281 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:47,383 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:43:47,403 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:43:47,429 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00171_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00248_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bf0b20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:43:47,432 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:43:47,433 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:43:47,434 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:43:47,435 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:43:47,435 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:43:47,436 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:43:47,437 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:43:47,438 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:43:47,439 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:43:47,439 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:43:47,440 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:43:47,441 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:43:47,448 - INFO - Fum/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:0.01
2026-01-13 19:43:47,449 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:43:47,450 - INFO - Fum/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:0.01
2026-01-13 19:43:47,451 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:47,453 - INFO - Fum/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:47,454 - INFO - Fum/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:0.01
2026-01-13 19:43:47,455 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:47,456 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:43:47,458 - INFO - Fum/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:47,459 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:43:47,460 - INFO - Fum/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:43:47,467 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bf0b20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00248_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn05319_c0': '>', 'rxn00171_c0': '<'}}
2026-01-13 19:43:47,468 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00171_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00248_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bf0b20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:43:47,472 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:43:47,493 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:47,638 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:43:47,658 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:50,091 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:50,108 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:50,146 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:43:50,167 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:51,042 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:43:51,068 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:51,198 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:43:51,226 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:43:51,249 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:51,587 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:43:51,611 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:51,883 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:43:51,902 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:52,006 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:43:52,026 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:52,481 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:43:52,483 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:43:52,501 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:43:52,501 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:53,458 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:43:53,487 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:53,961 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:43:53,994 - INFO - Objective with gapfill database:17.5; min objective:0.01
2026-01-13 19:43:54,021 - INFO - Objective with gapfill database:18.250000000000007; min objective:0.01
2026-01-13 19:43:54,048 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:54,144 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:43:54,169 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:43:54,189 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:55,337 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:43:55,358 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:56,754 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:43:56,782 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:58,402 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:43:58,428 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:59,032 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:43:59,060 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:43:59,083 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:43:59,394 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:43:59,424 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:01,337 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:44:01,356 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:44:01,373 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:44:01,389 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:01,596 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:44:01,640 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:02,690 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:44:02,716 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:44:02,737 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:03,662 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:44:03,694 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:44:03,723 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:04,047 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:44:04,068 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:04,938 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:44:04,961 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:44:04,981 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:06,025 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:44:06,053 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:08,590 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:44:08,625 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:09,506 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 19:44:09,544 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:44:09,899 - WARNING - No gapfilling solution found before filtering for For.O2 activating rxn00062_c0

Removing ungapfillable media For.O2

2026-01-13 19:44:09,928 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:08,043 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:45:08,061 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:16,943 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:45:16,963 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:19,501 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:45:19,526 - INFO - Objective with gapfill database:34.5; min objective:0.01
2026-01-13 19:45:19,551 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn03884_c0': '>', 'rxn00172_c0': '<', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69d660>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:45:19,554 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:45:19,555 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:45:19,557 - INFO - integrating rxn: rxn00172_c0
2026-01-13 19:45:19,558 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:45:19,560 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:45:19,575 - INFO - Glc.O2/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:5
2026-01-13 19:45:19,576 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:45:19,578 - INFO - Glc.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:5
2026-01-13 19:45:19,579 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:45:19,581 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69d660>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn00083_c0': '>', 'rxn03884_c0': '>', 'rxn00172_c0': '<', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:45:19,582 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn03884_c0': '>', 'rxn00172_c0': '<', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69d660>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:45:19,586 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:45:19,606 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:20,203 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:45:20,222 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:45:20,246 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c46c460>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:45:20,248 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:45:20,249 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:45:20,250 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:45:20,252 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:20,252 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:45:20,253 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:45:20,255 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:45:20,256 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:45:20,257 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:45:20,257 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:20,258 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:45:20,259 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:45:20,259 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:45:20,266 - INFO - Fum/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:0.01
2026-01-13 19:45:20,267 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:45:20,268 - INFO - Fum/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:20,269 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:20,269 - INFO - Fum/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:20,270 - INFO - Fum/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:20,271 - INFO - Fum/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:20,272 - INFO - Fum/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:20,273 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:20,274 - INFO - Fum/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:20,275 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:20,275 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:20,280 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c46c460>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}}
2026-01-13 19:45:20,281 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c46c460>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:45:20,284 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:45:20,303 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:21,111 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:45:21,119 - INFO - cpd00425 not found in model!
2026-01-13 19:45:21,120 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:45:21,129 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:21,630 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:45:21,650 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:45:21,674 - INFO - Initial solution: {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bf13c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:45:21,677 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:45:21,678 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:45:21,679 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:45:21,680 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:21,681 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:45:21,681 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:45:21,682 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:45:21,683 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:45:21,684 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:45:21,688 - INFO - cpd00159 not found in model!
2026-01-13 19:45:21,689 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:45:21,692 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:45:21,693 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:45:21,694 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:21,695 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:21,696 - INFO - Llac/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:21,696 - INFO - Llac/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:21,697 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:21,698 - INFO - Llac/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:21,703 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bf13c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {'rxn00171_c0': '<'}}
2026-01-13 19:45:21,704 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0bf13c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:45:21,707 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:45:21,726 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:22,348 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:45:22,366 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:23,940 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:45:23,960 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:25,035 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:45:25,054 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:28,841 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:45:28,860 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:45:28,883 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49e1d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:45:28,885 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:45:28,886 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:45:28,888 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:45:28,889 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:28,890 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:45:28,891 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:45:28,892 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:45:28,893 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:45:28,894 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:45:28,899 - INFO - cpd00159 not found in model!
2026-01-13 19:45:28,899 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:45:28,902 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:45:28,903 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:45:28,905 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:28,906 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:28,906 - INFO - Llac/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:28,907 - INFO - Llac/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:28,908 - INFO - Llac/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:28,909 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:28,914 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49e1d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:45:28,915 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49e1d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:45:28,918 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:45:28,936 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:29,362 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:45:29,383 - INFO - Objective with gapfill database:19.125000000000018; min objective:0.01
2026-01-13 19:45:29,408 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69de70>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:45:29,410 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:45:29,412 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:45:29,413 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:45:29,415 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:29,416 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:45:29,418 - INFO - integrating rxn: rxn00615_c0
2026-01-13 19:45:29,419 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:45:29,421 - INFO - integrating rxn: rxn05939_c0
2026-01-13 19:45:29,423 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:45:29,424 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:45:29,426 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:45:29,427 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:45:29,428 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:29,429 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:45:29,430 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed']]
2026-01-13 19:45:29,437 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:45:29,438 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,439 - INFO - Glyc.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,440 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,441 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:45:29,441 - INFO - Glyc.O2/rxn00062_c0:rxn00615_c0> needed:0.0 with min obj:2
2026-01-13 19:45:29,442 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,443 - INFO - Glyc.O2/rxn00062_c0:rxn05939_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,444 - INFO - Glyc.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:2
2026-01-13 19:45:29,445 - INFO - Glyc.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:45:29,446 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,447 - INFO - Glyc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,448 - INFO - Glyc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,449 - INFO - Glyc.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,454 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69de70>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:45:29,455 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69de70>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:45:29,460 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed']]
2026-01-13 19:45:29,479 - INFO - Objective with gapfill database:17.5; min objective:0.01
2026-01-13 19:45:29,504 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00159_c0': '>', 'rxn00172_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69e1a0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:45:29,507 - INFO - integrating rxn: rxn00159_c0
2026-01-13 19:45:29,508 - INFO - integrating rxn: rxn00172_c0
2026-01-13 19:45:29,509 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:29,510 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new']]
2026-01-13 19:45:29,517 - INFO - Fum.O2/rxn00062_c0:rxn00159_c0> needed:0.0 with min obj:3
2026-01-13 19:45:29,519 - INFO - Fum.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:3
2026-01-13 19:45:29,520 - INFO - Fum.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:3
2026-01-13 19:45:29,525 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69e1a0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'rxn00159_c0': '>', 'rxn00172_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:45:29,526 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn00159_c0': '>', 'rxn00172_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69e1a0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:45:29,530 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new']]
2026-01-13 19:45:29,550 - INFO - Objective with gapfill database:19.125000000000004; min objective:0.01
2026-01-13 19:45:29,575 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn08527_c0': '<', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69e380>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:45:29,576 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:45:29,578 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:45:29,579 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:45:29,581 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:45:29,582 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:45:29,583 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:45:29,585 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:45:29,586 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:29,587 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:45:29,588 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new']]
2026-01-13 19:45:29,595 - INFO - Succ.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,596 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,597 - INFO - Succ.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:2
2026-01-13 19:45:29,599 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:45:29,600 - INFO - Succ.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:45:29,602 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,603 - INFO - Succ.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:2
2026-01-13 19:45:29,604 - INFO - Succ.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,605 - INFO - Succ.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,611 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69e380>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn00256_c0': '<', 'rxn08527_c0': '<', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:45:29,612 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn08527_c0': '<', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69e380>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:45:29,616 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new']]
2026-01-13 19:45:29,636 - INFO - Objective with gapfill database:16.249999999999993; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:29,661 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn00172_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69e830>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:45:29,663 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:45:29,664 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:45:29,665 - INFO - integrating rxn: rxn00172_c0
2026-01-13 19:45:29,666 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 19:45:29,673 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:45:29,674 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:45:29,675 - INFO - LLac.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:2
2026-01-13 19:45:29,680 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69e830>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn00172_c0': '<'}, 'reversed': {}}
2026-01-13 19:45:29,681 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn00172_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69e830>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:45:29,684 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 19:45:29,685 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:45:29,703 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:45:29,703 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:30,037 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:45:30,056 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:30,859 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:45:30,877 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:31,127 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:45:31,149 - INFO - Objective with gapfill database:28.75; min objective:0.01
2026-01-13 19:45:31,175 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn01106_c0': '<'}, 'new': {'rxn00324_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00604_c0': '>', 'rxn01476_c0': '>', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn08656_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85d90100>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:45:31,177 - INFO - integrating rxn: rxn00324_c0
2026-01-13 19:45:31,179 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:45:31,181 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:45:31,183 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:31,184 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:45:31,186 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:45:31,188 - INFO - integrating rxn: rxn00604_c0
2026-01-13 19:45:31,190 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:45:31,192 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:45:31,193 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:45:31,195 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:45:31,197 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:45:31,199 - INFO - integrating rxn: rxn08656_c0
2026-01-13 19:45:31,200 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:31,201 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:45:31,202 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:45:31,204 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed']]
2026-01-13 19:45:31,218 - INFO - Glc.O2/rxn00062_c0:rxn00324_c0< needed:0.0 with min obj:5
2026-01-13 19:45:31,219 - INFO - Glc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:5
2026-01-13 19:45:31,220 - INFO - Glc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:5
2026-01-13 19:45:31,222 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:5
2026-01-13 19:45:31,223 - INFO - Glc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:5
2026-01-13 19:45:31,224 - INFO - Glc.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:5
2026-01-13 19:45:31,226 - INFO - Glc.O2/rxn00062_c0:rxn00604_c0> needed:0.0 with min obj:5
2026-01-13 19:45:31,227 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:45:31,228 - INFO - rxn08901_c0> not needed:19.0
2026-01-13 19:45:31,229 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:45:31,230 - INFO - Glc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:5
2026-01-13 19:45:31,232 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:45:31,233 - INFO - Glc.O2/rxn00062_c0:rxn08656_c0> needed:0.0 with min obj:5
2026-01-13 19:45:31,234 - INFO - Glc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:5
2026-01-13 19:45:31,235 - INFO - Glc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:5
2026-01-13 19:45:31,237 - INFO - Glc.O2/rxn00062_c0:rxn01106_c0< needed:0.0 with min obj:5
2026-01-13 19:45:31,239 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85d90100>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn00324_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00604_c0': '>', 'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn08656_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<', 'rxn01106_c0': '<'}}
2026-01-13 19:45:31,241 - INFO - Unneeded: [['rxn08901_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn01106_c0': '<'}, 'new': {'rxn00324_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00604_c0': '>', 'rxn01476_c0': '>', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn08656_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85d90100>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:45:31,245 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed']]
2026-01-13 19:45:31,264 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:32,195 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:45:32,213 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:33,473 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:45:33,483 - INFO - cpd11632 not found in model!
2026-01-13 19:45:33,484 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:45:33,494 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:33,601 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:45:33,623 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:45:33,645 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:45:33,665 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:34,088 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:45:34,112 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:45:34,132 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:35,116 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:45:35,145 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:35,857 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:45:35,877 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:36,624 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:45:36,642 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:45:36,652 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:45:36,696 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:37,225 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:45:37,245 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:45:37,261 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:45:37,277 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:37,629 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:45:37,648 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:38,467 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:45:38,486 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:38,669 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:45:38,690 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:39,556 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:45:39,577 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:45:39,602 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '>', 'rxn01333_c0': '<', 'rxn05602_c0': '<', 'rxn01187_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69ee00>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:45:39,605 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:45:39,606 - INFO - integrating rxn: rxn01333_c0
2026-01-13 19:45:39,608 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:45:39,609 - INFO - integrating rxn: rxn01187_c0
2026-01-13 19:45:39,610 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new']]
2026-01-13 19:45:39,617 - INFO - Glc/rxn00062_c0:EX_cpd00159_e0> needed:0.0 with min obj:0.01
2026-01-13 19:45:39,618 - INFO - Glc/rxn00062_c0:rxn01333_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:39,619 - INFO - Glc/rxn00062_c0:rxn05602_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:39,620 - INFO - Glc/rxn00062_c0:rxn01187_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:39,626 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69ee00>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '>', 'rxn01333_c0': '<', 'rxn05602_c0': '<', 'rxn01187_c0': '>'}, 'reversed': {}}
2026-01-13 19:45:39,626 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '>', 'rxn01333_c0': '<', 'rxn05602_c0': '<', 'rxn01187_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69ee00>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:45:39,630 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new']]
2026-01-13 19:45:39,650 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:40,012 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:45:40,040 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:41,170 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:45:41,195 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:45:41,217 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:41,490 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:45:41,505 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:45:41,513 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:45:41,528 - INFO - Objective with gapfill database:16.25; min objective:0.01
2026-01-13 19:45:41,555 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00148_c0': '<', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c160>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:45:41,559 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:45:41,560 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:45:41,562 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:45:41,563 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:45:41,564 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:41,566 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:45:41,567 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:45:41,569 - INFO - integrating rxn: rxn00615_c0
2026-01-13 19:45:41,570 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:45:41,571 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:45:41,573 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:45:41,573 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:45:41,574 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:41,576 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:45:41,576 - INFO - integrating rxn: rxn00747_c0
2026-01-13 19:45:41,577 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:45:41,579 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed']]
2026-01-13 19:45:41,588 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:45:41,589 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,590 - INFO - Glyc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,591 - INFO - Glyc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,592 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,594 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,595 - INFO - Glyc.O2/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,596 - INFO - Glyc.O2/rxn00062_c0:rxn00615_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,597 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,598 - INFO - Glyc.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,599 - INFO - Glyc.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,600 - INFO - Glyc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,601 - INFO - Glyc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,603 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,604 - INFO - Glyc.O2/rxn00062_c0:rxn00747_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,605 - INFO - Glyc.O2/rxn00062_c0:rxn01106_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,609 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c160>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00148_c0': '<', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<', 'rxn00747_c0': '<', 'rxn01106_c0': '<'}}
2026-01-13 19:45:41,610 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00148_c0': '<', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c160>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:45:41,614 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed']]
2026-01-13 19:45:41,633 - INFO - Objective with gapfill database:14.625; min objective:0.01
2026-01-13 19:45:41,658 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c3d0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:45:41,661 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:45:41,662 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:45:41,663 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:45:41,664 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:45:41,666 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:41,666 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:45:41,667 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:45:41,668 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:45:41,669 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:45:41,670 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:41,670 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:45:41,671 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:45:41,677 - INFO - Fum.O2/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:3
2026-01-13 19:45:41,678 - INFO - Fum.O2/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:3
2026-01-13 19:45:41,679 - INFO - Fum.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:3
2026-01-13 19:45:41,680 - INFO - Fum.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:3
2026-01-13 19:45:41,681 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:45:41,682 - INFO - Fum.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:3
2026-01-13 19:45:41,683 - INFO - Fum.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:3
2026-01-13 19:45:41,684 - INFO - Fum.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:3
2026-01-13 19:45:41,685 - INFO - Fum.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:3
2026-01-13 19:45:41,686 - INFO - Fum.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:3
2026-01-13 19:45:41,687 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:45:41,691 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c3d0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:45:41,692 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c3d0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:45:41,696 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:45:41,714 - INFO - Objective with gapfill database:15.375; min objective:0.01
2026-01-13 19:45:41,739 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn09269_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c640>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:45:41,741 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:45:41,742 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:45:41,743 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:45:41,744 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:41,745 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:45:41,746 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:45:41,747 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:45:41,748 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:45:41,749 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:45:41,750 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:41,751 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:45:41,751 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:45:41,757 - INFO - Succ.O2/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:2
2026-01-13 19:45:41,758 - INFO - Succ.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,759 - INFO - Succ.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,760 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,761 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,762 - INFO - Succ.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,763 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,764 - INFO - Succ.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,765 - INFO - Succ.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,766 - INFO - Succ.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,766 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,771 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c640>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn09269_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:45:41,772 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn09269_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c640>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:45:41,775 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:45:41,794 - INFO - Objective with gapfill database:13.375; min objective:0.01
2026-01-13 19:45:41,818 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00499_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c9d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:45:41,820 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:45:41,821 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:45:41,822 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:45:41,823 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:45:41,824 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:41,825 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:45:41,825 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:45:41,827 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:45:41,828 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:45:41,829 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:45:41,829 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:41,830 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:45:41,831 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:45:41,835 - INFO - cpd00159 not found in model!
2026-01-13 19:45:41,835 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:45:41,838 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:45:41,839 - INFO - LLac.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,840 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,840 - INFO - LLac.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,841 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,842 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,843 - INFO - LLac.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,844 - INFO - LLac.O2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,845 - INFO - LLac.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,846 - INFO - LLac.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:45:41,847 - INFO - LLac.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,847 - INFO - LLac.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:45:41,852 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c9d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00499_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:45:41,853 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00499_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4c9d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:45:41,856 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:45:41,875 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:42,204 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:45:42,224 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:43,044 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:45:43,065 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:43,860 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:45:43,878 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:44,832 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:45:44,857 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:45:44,880 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:45,469 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:45:45,487 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:45,649 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:45:45,659 - INFO - cpd01024 not found in model!
2026-01-13 19:45:45,660 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:45:45,671 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:45,941 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:45:45,962 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:46,481 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:45:46,504 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:46,665 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:45:46,685 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:46,976 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:45:46,995 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:47,445 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:45:47,469 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:45:47,489 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:47,878 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:45:47,899 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:45:47,907 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:45:47,918 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:49,677 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:45:49,698 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:49,853 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:45:49,874 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:45:49,892 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:45:49,910 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:50,502 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:45:50,529 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:45:50,547 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:45:50,565 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:51,027 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:45:51,035 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:45:51,045 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:45:51,058 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:51,857 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:45:51,872 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:45:51,878 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:45:51,895 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:45:51,898 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:45:51,912 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:45:51,919 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:52,188 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:45:52,210 - INFO - Objective with gapfill database:3.5; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:52,236 - INFO - Initial solution: {'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00786_c0': '>', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4d030>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:45:52,239 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:45:52,240 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:45:52,242 - INFO - integrating rxn: rxn00786_c0
2026-01-13 19:45:52,243 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:45:52,244 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:45:52,246 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:45:52,247 - INFO - integrating rxn: rxn00747_c0
2026-01-13 19:45:52,248 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:45:52,249 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:45:52,256 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:45:52,257 - INFO - Glc/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:52,259 - INFO - Glc/rxn00062_c0:rxn00786_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:52,260 - INFO - Glc/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:52,261 - INFO - Glc/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:52,263 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:52,264 - INFO - Glc/rxn00062_c0:rxn00747_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:52,265 - INFO - Glc/rxn00062_c0:rxn01106_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:52,271 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4d030>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00786_c0': '>', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}}
2026-01-13 19:45:52,271 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00786_c0': '>', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4d030>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:45:52,276 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:45:52,276 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:45:52,296 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:45:52,298 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:45:52,316 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:45:52,333 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:52,732 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:45:52,752 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:52,854 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:45:52,880 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:45:52,904 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:54,425 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:45:54,468 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:54,585 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:45:54,615 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:45:54,641 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:55,269 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:45:55,284 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:45:55,289 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:45:55,327 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:55,487 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 19:45:55,509 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:56,317 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:45:56,348 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:56,792 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:45:56,801 - INFO - cpd11632 not found in model!
2026-01-13 19:45:56,802 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:45:56,811 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:57,371 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:45:57,392 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:57,697 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:45:57,720 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:57,879 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:45:57,903 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:58,742 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:45:58,758 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:59,085 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:45:59,111 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:45:59,133 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:45:59,594 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:45:59,614 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:45:59,639 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69f6d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:45:59,642 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:45:59,643 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:45:59,644 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:45:59,645 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:45:59,646 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:45:59,647 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:45:59,648 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:45:59,649 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:45:59,656 - INFO - Fum/rxn00062_c0:EX_cpd00159_e0> needed:0.0 with min obj:0.01
2026-01-13 19:45:59,657 - INFO - Fum/rxn00062_c0:rxn05602_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:59,658 - INFO - Fum/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:59,659 - INFO - Fum/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:59,661 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:59,662 - INFO - Fum/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 19:45:59,664 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:45:59,669 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69f6d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:45:59,669 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69f6d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:45:59,673 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:45:59,694 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:00,121 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:46:00,140 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:00,478 - WARNING - No gapfilling solution found before filtering for For.O2 activating rxn00062_c0

Removing ungapfillable media For.O2

2026-01-13 19:46:00,514 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:00,927 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:46:00,959 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:46:00,981 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:01,269 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:46:01,289 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:01,436 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:46:01,460 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:02,549 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:46:02,569 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:46:02,594 - INFO - Initial solution: {'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00148_c0': '<', 'rxn00615_c0': '>', 'rxn00935_c0': '<', 'rxn08173_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4d720>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:46:02,597 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:46:02,598 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:46:02,599 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:46:02,600 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:46:02,601 - INFO - integrating rxn: rxn00615_c0
2026-01-13 19:46:02,603 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:46:02,604 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:46:02,606 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:46:02,606 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:46:02,608 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:46:02,609 - INFO - integrating rxn: rxn00616_c0
2026-01-13 19:46:02,610 - INFO - integrating rxn: rxn00747_c0
2026-01-13 19:46:02,611 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:46:02,611 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new']]
2026-01-13 19:46:02,618 - INFO - Glyc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:46:02,619 - INFO - Glyc/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,620 - INFO - Glyc/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,621 - INFO - Glyc/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,622 - INFO - Glyc/rxn00062_c0:rxn00615_c0> needed:0.0 with min obj:0.01
2026-01-13 19:46:02,623 - INFO - Glyc/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,624 - INFO - Glyc/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,625 - INFO - Glyc/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,626 - INFO - Glyc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:46:02,627 - INFO - Glyc/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,628 - INFO - Glyc/rxn00062_c0:rxn00616_c0> needed:0.0 with min obj:0.01
2026-01-13 19:46:02,629 - INFO - Glyc/rxn00062_c0:rxn00747_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,630 - INFO - Glyc/rxn00062_c0:rxn01106_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,635 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4d720>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00148_c0': '<', 'rxn00615_c0': '>', 'rxn00935_c0': '<', 'rxn08173_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>'}, 'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}}
2026-01-13 19:46:02,636 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00148_c0': '<', 'rxn00615_c0': '>', 'rxn00935_c0': '<', 'rxn08173_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4d720>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:46:02,639 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new']]
2026-01-13 19:46:02,659 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:46:02,685 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4d780>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:46:02,687 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:46:02,688 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:46:02,689 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:46:02,690 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:46:02,690 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:46:02,691 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:46:02,692 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:46:02,693 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:46:02,694 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:46:02,700 - INFO - Fum/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,701 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:46:02,702 - INFO - Fum/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:0.01
2026-01-13 19:46:02,703 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,704 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:46:02,705 - INFO - Fum/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,706 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:02,707 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:46:02,711 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4d780>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}}
2026-01-13 19:46:02,712 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4d780>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:46:02,716 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:46:02,734 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:02,962 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:46:02,981 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:03,556 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:46:03,575 - INFO - Objective with gapfill database:3.5; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:03,592 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:46:03,608 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:46:03,647 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:46:03,676 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:03,984 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:46:04,005 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:04,103 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 19:46:04,123 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:04,930 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:46:04,950 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:05,820 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:46:05,847 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:46:05,868 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:06,031 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:46:06,052 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:06,478 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:46:06,524 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:07,243 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:46:07,270 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:46:07,294 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:07,388 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:46:07,409 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:08,080 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:46:08,099 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:08,473 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:46:08,494 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:08,595 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:46:08,616 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:09,295 - WARNING - No gapfilling solution found before filtering for For.O2 activating rxn00062_c0

Removing ungapfillable media For.O2

2026-01-13 19:46:09,328 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:09,444 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:46:09,485 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:09,578 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:46:09,588 - INFO - cpd00425 not found in model!
2026-01-13 19:46:09,589 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:46:09,600 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:09,678 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:46:09,688 - INFO - cpd01024 not found in model!
2026-01-13 19:46:09,689 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:46:09,700 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:10,087 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:46:10,114 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:46:10,136 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:10,311 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:46:10,336 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:10,505 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:46:10,535 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:11,700 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:46:11,721 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:12,086 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:46:12,095 - INFO - cpd11632 not found in model!
2026-01-13 19:46:12,096 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:46:12,107 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:13,051 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:46:13,071 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:46:13,098 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4dde0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:46:13,100 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:46:13,101 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:46:13,102 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:46:13,103 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:46:13,104 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:46:13,105 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:46:13,106 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:46:13,107 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:46:13,111 - INFO - cpd00159 not found in model!
2026-01-13 19:46:13,112 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:46:13,115 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:46:13,116 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:46:13,117 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:46:13,118 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:13,119 - INFO - Llac/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:46:13,120 - INFO - Llac/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:46:13,121 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:46:13,126 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4dde0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:46:13,126 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4dde0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:46:13,131 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:46:13,150 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:14,502 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 19:46:14,548 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:15,541 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:46:15,570 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:46:15,595 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:16,004 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:46:16,025 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:16,643 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:46:16,669 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:16,870 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:46:16,896 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:46:16,917 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:17,933 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:46:17,953 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:17,970 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:46:17,986 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:46:18,002 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:46:18,021 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:18,440 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:46:18,464 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:19,715 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:46:19,739 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:20,596 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:46:20,615 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:21,028 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:46:21,058 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:46:21,085 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:21,443 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:46:21,469 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:46:21,498 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'rxn01975_c0': '>', 'rxn01977_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn00083_c0': '>', 'rxn08173_c0': '>', 'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn00172_c0': '<', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb1bd60>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:46:21,500 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:46:21,502 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:46:21,503 - INFO - integrating rxn: rxn01977_c0
2026-01-13 19:46:21,505 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:46:21,506 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:46:21,508 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:46:21,509 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:46:21,511 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:46:21,512 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:46:21,513 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:46:21,515 - INFO - integrating rxn: rxn00172_c0
2026-01-13 19:46:21,516 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:46:21,517 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:46:21,534 - INFO - Glc.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:5
2026-01-13 19:46:21,535 - INFO - Glc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:5
2026-01-13 19:46:21,536 - INFO - Glc.O2/rxn00062_c0:rxn01977_c0> needed:0.0 with min obj:5
2026-01-13 19:46:21,537 - INFO - Glc.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:5
2026-01-13 19:46:21,538 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:5
2026-01-13 19:46:21,539 - INFO - Glc.O2/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:5
2026-01-13 19:46:21,540 - INFO - Glc.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:5
2026-01-13 19:46:21,541 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:46:21,542 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:46:21,543 - INFO - Glc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:5
2026-01-13 19:46:21,544 - INFO - Glc.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:5
2026-01-13 19:46:21,545 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:46:21,547 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb1bd60>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'rxn01975_c0': '>', 'rxn01977_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn00083_c0': '>', 'rxn08173_c0': '>', 'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn00172_c0': '<', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:46:21,547 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'rxn01975_c0': '>', 'rxn01977_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn00083_c0': '>', 'rxn08173_c0': '>', 'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn00172_c0': '<', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb1bd60>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:46:21,551 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:46:21,574 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:21,829 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:46:21,854 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:22,238 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:46:22,260 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:22,796 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:46:22,823 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:23,356 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:46:23,375 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:23,840 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:46:23,867 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:24,729 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:46:24,755 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:24,840 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:46:24,861 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:25,060 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:46:25,080 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:30,263 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:46:30,289 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:31,591 - WARNING - No gapfilling solution found before filtering for Etho activating rxn00062_c0

Removing ungapfillable media Etho

2026-01-13 19:46:31,621 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:32,200 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:46:32,230 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:46:32,254 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:32,946 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:46:32,970 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:39,814 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:46:39,849 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:46:39,880 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:41,930 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:46:41,960 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:46:46,077 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:46:46,103 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:47:46,798 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:47:46,821 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:01,144 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:01,164 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:48:01,188 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:48:01,190 - INFO - Initial solution: {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a10b50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:01,193 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:01,194 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:01,195 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:01,196 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:48:01,197 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:01,198 - INFO - cpd11632 not found in model!
2026-01-13 19:48:01,199 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:01,199 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:48:01,200 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:01,205 - INFO - cpd08021 not found in model!
2026-01-13 19:48:01,206 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:48:01,209 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:01,210 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:01,211 - INFO - Glc.DMSO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,213 - INFO - Glc.DMSO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,214 - INFO - Glc.DMSO/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,215 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:01,217 - INFO - Glc.DMSO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,222 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a10b50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn00171_c0': '<'}}
2026-01-13 19:48:01,223 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a10b50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:01,227 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:01,246 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:48:01,270 - INFO - Initial solution: {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a108b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:48:01,272 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:01,273 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:01,274 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:01,275 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:48:01,275 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:01,276 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:01,277 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:01,281 - INFO - cpd00811 not found in model!
2026-01-13 19:48:01,282 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:48:01,285 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:01,286 - INFO - Glc.TMAO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,287 - INFO - Glc.TMAO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,288 - INFO - Glc.TMAO/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,289 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:01,290 - INFO - Glc.TMAO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,295 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a108b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn00171_c0': '<'}}
2026-01-13 19:48:01,296 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00148_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a108b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:01,300 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:01,320 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:01,921 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:48:01,942 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:48:01,969 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69fb80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:48:01,972 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:48:01,974 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:01,975 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:48:01,977 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:48:01,978 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:01,979 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:01,981 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:01,982 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:01,983 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:48:01,990 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,991 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:01,992 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:01,993 - INFO - Llac/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,994 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,995 - INFO - Llac/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,996 - INFO - Llac/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:01,997 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:02,002 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69fb80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:48:02,002 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a69fb80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:02,007 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:48:02,027 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:02,696 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:48:02,720 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:09,647 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 19:48:09,666 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:09,837 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:48:09,857 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:11,349 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 19:48:11,367 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:48:11,391 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49c700>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:48:11,393 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:11,394 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:11,395 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:11,396 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:11,397 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:11,398 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:11,399 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:48:11,400 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:11,401 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:48:11,405 - INFO - cpd08021 not found in model!
2026-01-13 19:48:11,406 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:48:11,409 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:11,410 - INFO - Glc.DMSO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,411 - INFO - Glc.DMSO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,412 - INFO - Glc.DMSO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,413 - INFO - Glc.DMSO/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:11,414 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:11,414 - INFO - Glc.DMSO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,415 - INFO - Glc.DMSO/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,420 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49c700>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:48:11,421 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49c700>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:11,423 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:48:11,442 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:48:11,465 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49c580>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:48:11,466 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:11,467 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:11,467 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:11,468 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:11,469 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:11,470 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:11,470 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:48:11,471 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:11,472 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:48:11,476 - INFO - cpd00811 not found in model!
2026-01-13 19:48:11,476 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:48:11,479 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:11,480 - INFO - Glc.TMAO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,481 - INFO - Glc.TMAO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,482 - INFO - Glc.TMAO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,482 - INFO - Glc.TMAO/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:11,483 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:11,484 - INFO - Glc.TMAO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,485 - INFO - Glc.TMAO/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:11,490 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49c580>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:48:11,490 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49c580>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:11,493 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:48:11,510 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:11,896 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:48:11,915 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:11,991 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:48:12,012 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:48:12,028 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:48:12,045 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:12,344 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:48:12,364 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:15,455 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:48:15,464 - INFO - cpd01024 not found in model!
2026-01-13 19:48:15,465 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:48:15,475 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:16,637 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:48:16,655 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:17,995 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0
2026-01-13 19:48:18,014 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:18,086 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:48:18,119 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:18,376 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:48:18,385 - INFO - cpd01024 not found in model!
2026-01-13 19:48:18,386 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:48:18,396 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:20,128 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 19:48:20,150 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:20,290 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:48:20,331 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:48:20,354 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:20,426 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:48:20,444 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:21,718 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:48:21,737 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:22,473 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:48:22,497 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:22,682 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:48:22,701 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:23,480 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:48:23,502 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:24,369 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:48:24,403 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:25,132 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:48:25,152 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:25,261 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:48:25,295 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:25,934 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:48:25,958 - INFO - Objective with gapfill database:19.125; min objective:0.01
2026-01-13 19:48:25,986 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6ee793f0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:48:25,989 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:48:25,991 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:48:25,992 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:48:25,994 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:48:25,996 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:48:25,996 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:25,998 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:48:25,999 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:48:26,000 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:48:26,002 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:26,003 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:48:26,004 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:48:26,005 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:48:26,007 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:48:26,008 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:26,009 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:48:26,017 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:48:26,018 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,019 - INFO - Glyc.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,019 - INFO - Glyc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,020 - INFO - Glyc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,021 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,022 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,023 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,024 - INFO - Glyc.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,025 - INFO - Glyc.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,026 - INFO - Glyc.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,027 - INFO - Glyc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,027 - INFO - Glyc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,028 - INFO - Glyc.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,029 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,035 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6ee793f0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00973_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:48:26,036 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6ee793f0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:48:26,040 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:48:26,064 - INFO - Objective with gapfill database:17.5; min objective:0.01
2026-01-13 19:48:26,092 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08173_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00172_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6ee795a0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:48:26,093 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:48:26,095 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:48:26,097 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:48:26,097 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:48:26,098 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:26,099 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:48:26,100 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:26,100 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:48:26,101 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:48:26,102 - INFO - integrating rxn: rxn00172_c0
2026-01-13 19:48:26,102 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:26,103 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:48:26,110 - INFO - Fum.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:3
2026-01-13 19:48:26,112 - INFO - Fum.O2/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:3
2026-01-13 19:48:26,112 - INFO - Fum.O2/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:3
2026-01-13 19:48:26,113 - INFO - Fum.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:3
2026-01-13 19:48:26,114 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:48:26,115 - INFO - Fum.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:3
2026-01-13 19:48:26,116 - INFO - Fum.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:3
2026-01-13 19:48:26,117 - INFO - Fum.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:3
2026-01-13 19:48:26,118 - INFO - Fum.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:3
2026-01-13 19:48:26,119 - INFO - Fum.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:3
2026-01-13 19:48:26,119 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:48:26,125 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6ee795a0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08173_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00172_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:48:26,126 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08173_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00172_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6ee795a0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:48:26,129 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:48:26,152 - INFO - Objective with gapfill database:18.25; min objective:0.01
2026-01-13 19:48:26,180 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00974_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn09269_c0': '>', 'rxn01388_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb753f0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:48:26,183 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:48:26,184 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:48:26,185 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:48:26,187 - INFO - integrating rxn: rxn00974_c0
2026-01-13 19:48:26,189 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:48:26,190 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:26,191 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:48:26,192 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:48:26,194 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:48:26,196 - INFO - integrating rxn: rxn01388_c0
2026-01-13 19:48:26,197 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:26,198 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:48:26,199 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:48:26,200 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:26,201 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new']]
2026-01-13 19:48:26,215 - INFO - Succ.O2/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:2
2026-01-13 19:48:26,216 - INFO - Succ.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,217 - INFO - Succ.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,218 - INFO - Succ.O2/rxn00062_c0:rxn00974_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,219 - INFO - Succ.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,221 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,222 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,223 - INFO - Succ.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,224 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,225 - INFO - Succ.O2/rxn00062_c0:rxn01388_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,226 - INFO - Succ.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,227 - INFO - Succ.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,228 - INFO - Succ.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,229 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,236 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb753f0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00974_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn09269_c0': '>', 'rxn01388_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:48:26,237 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00974_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn09269_c0': '>', 'rxn01388_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb753f0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:48:26,241 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new']]
2026-01-13 19:48:26,265 - INFO - Objective with gapfill database:16.25; min objective:0.01
2026-01-13 19:48:26,293 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00499_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb74220>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:48:26,296 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:48:26,297 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:48:26,298 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:48:26,300 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:48:26,301 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:48:26,302 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:26,303 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:48:26,304 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:48:26,306 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:48:26,307 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:26,308 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:48:26,309 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:48:26,310 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:48:26,311 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:26,312 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:26,317 - INFO - cpd00159 not found in model!
2026-01-13 19:48:26,318 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:48:26,322 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:48:26,323 - INFO - LLac.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,324 - INFO - LLac.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,325 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,326 - INFO - LLac.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,327 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,328 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,329 - INFO - LLac.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,330 - INFO - LLac.O2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,332 - INFO - LLac.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,333 - INFO - LLac.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,334 - INFO - LLac.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,335 - INFO - LLac.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:2
2026-01-13 19:48:26,336 - INFO - LLac.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:48:26,343 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb74220>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00499_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00973_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:48:26,343 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00499_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb74220>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:48:26,348 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:26,371 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:26,389 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:26,408 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:48:26,435 - INFO - Initial solution: {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a12da0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:48:26,437 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:48:26,438 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:26,439 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:48:26,440 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:26,441 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:26,442 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:48:26,443 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:26,443 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:26,444 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:26,446 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:48:26,449 - INFO - cpd00159 not found in model!

2026-01-13 19:48:26,450 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:48:26,451 - INFO - cpd11640 not found in model!
2026-01-13 19:48:26,451 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:48:26,454 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:48:26,455 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:26,456 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:26,457 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:26,458 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:26,459 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:26,460 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:26,461 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:26,466 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a12da0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {'rxn00171_c0': '<'}}
2026-01-13 19:48:26,466 - INFO - Unneeded: []

Adding gapfilling

2026-01-13 19:48:26,467 - INFO - Objective with gapfill database:0.0; min objective:0.01

{'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a12da0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:26,470 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:26,490 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:48:26,513 - INFO - Initial solution: {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a13250>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:48:26,515 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:48:26,516 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:26,517 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:48:26,518 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:26,518 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:26,519 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:48:26,520 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:26,521 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:26,521 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:26,526 - INFO - cpd00159 not found in model!
2026-01-13 19:48:26,526 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:48:26,529 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:48:26,530 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:26,531 - INFO - LLac.SO4/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:26,532 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:26,533 - INFO - LLac.SO4/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:26,534 - INFO - LLac.SO4/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:26,535 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:26,535 - INFO - LLac.SO4/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:26,541 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a13250>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {'rxn00171_c0': '<'}}
2026-01-13 19:48:26,542 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00171_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faa0a13250>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:26,545 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00171_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:26,564 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:27,267 - WARNING - No gapfilling solution found before filtering for Etho activating rxn00062_c0

Removing ungapfillable media Etho

2026-01-13 19:48:27,309 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:28,586 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:48:28,608 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:48:28,627 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:48:28,644 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:28,859 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0
2026-01-13 19:48:28,879 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:29,480 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:48:29,489 - INFO - cpd00425 not found in model!
2026-01-13 19:48:29,490 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:48:29,500 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:29,625 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:48:29,644 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:29,992 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:48:30,013 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:30,833 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:48:30,837 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:48:30,860 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:30,865 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:30,991 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:48:31,012 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:48:31,029 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:48:31,046 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:31,515 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:48:31,532 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:31,616 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:48:31,636 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:31,937 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:48:31,941 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:48:31,960 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:31,960 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:32,234 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 19:48:32,273 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:32,781 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:48:32,802 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:33,225 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:48:33,252 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:33,443 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:48:33,470 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:34,502 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:48:34,530 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:34,917 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 19:48:34,927 - INFO - cpd08701 not found in model!
2026-01-13 19:48:34,928 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:48:34,929 - INFO - cpd01024 not found in model!
2026-01-13 19:48:34,930 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:48:34,936 - INFO - cpd08701 not found in model!
2026-01-13 19:48:34,937 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:48:34,937 - INFO - cpd01024 not found in model!
2026-01-13 19:48:34,938 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:48:34,947 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:35,397 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:48:35,421 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:37,628 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0
2026-01-13 19:48:37,648 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:48:37,673 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49f190>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:48:37,675 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:48:37,676 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:37,677 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:48:37,678 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:37,679 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:37,679 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:37,680 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:48:37,681 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:37,681 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:48:37,686 - INFO - cpd00159 not found in model!
2026-01-13 19:48:37,687 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:48:37,687 - INFO - cpd11640 not found in model!
2026-01-13 19:48:37,688 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:48:37,692 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:48:37,693 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:37,694 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:37,695 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:37,695 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:37,696 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:37,697 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:37,698 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:37,703 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49f190>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:48:37,704 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49f190>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:37,707 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:48:37,726 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:48:37,750 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49f640>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:48:37,752 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:48:37,753 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:37,754 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:48:37,755 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:37,756 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:37,757 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:37,758 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:48:37,759 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:37,760 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:48:37,764 - INFO - cpd00159 not found in model!
2026-01-13 19:48:37,765 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:48:37,768 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:48:37,769 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:37,770 - INFO - LLac.SO4/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:37,771 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:37,772 - INFO - LLac.SO4/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:37,773 - INFO - LLac.SO4/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:37,774 - INFO - LLac.SO4/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:37,775 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:37,780 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49f640>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:48:37,781 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa9c49f640>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:37,785 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:48:37,804 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:38,145 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:48:38,173 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:48:38,204 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb749a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:48:38,208 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:48:38,209 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:38,211 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:48:38,213 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:48:38,214 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:48:38,215 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:38,217 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:48:38,218 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:48:38,219 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:38,221 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:48:38,232 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:48:38,233 - INFO - Glc/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:38,235 - INFO - Glc/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:38,236 - INFO - Glc/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:38,238 - INFO - Glc/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:38,239 - INFO - rxn00102_c0> not needed:2.5
2026-01-13 19:48:38,240 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:48:38,242 - INFO - Glc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:48:38,243 - INFO - rxn00250_c0< not needed:2.5
2026-01-13 19:48:38,250 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb749a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:48:38,251 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb749a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:48:38,255 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:48:38,278 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:38,631 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:38,668 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:38,691 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:48:38,720 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:38,968 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:48:39,006 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:48:39,031 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:40,411 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:48:40,432 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:40,527 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:48:40,551 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:40,805 - WARNING - No gapfilling solution found before filtering for For.O2 activating rxn00062_c0

Removing ungapfillable media For.O2

2026-01-13 19:48:40,851 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:40,868 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:48:40,911 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:41,560 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 19:48:41,580 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:42,365 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:48:42,389 - INFO - Objective with gapfill database:34.500000000000036; min objective:0.01
2026-01-13 19:48:42,418 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01975_c0': '>', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn01115_c0': '>', 'rxn08527_c0': '<', 'rxn01476_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fac0f2e5c0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:48:42,420 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:48:42,422 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:48:42,424 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:48:42,425 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:48:42,427 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:42,429 - INFO - integrating rxn: rxn01115_c0
2026-01-13 19:48:42,431 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:48:42,432 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:48:42,434 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:48:42,435 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new']]
2026-01-13 19:48:42,449 - INFO - Glc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:5
2026-01-13 19:48:42,451 - INFO - Glc.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:5
2026-01-13 19:48:42,452 - INFO - Glc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:5
2026-01-13 19:48:42,453 - INFO - Glc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:5
2026-01-13 19:48:42,454 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:5
2026-01-13 19:48:42,455 - INFO - Glc.O2/rxn00062_c0:rxn01115_c0> needed:0.0 with min obj:5
2026-01-13 19:48:42,456 - INFO - Glc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:5
2026-01-13 19:48:42,457 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:48:42,458 - INFO - Glc.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:5
2026-01-13 19:48:42,460 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fac0f2e5c0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn01975_c0': '>', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn01115_c0': '>', 'rxn08527_c0': '<', 'rxn01476_c0': '>', 'rxn00973_c0': '>'}, 'reversed': {}}
2026-01-13 19:48:42,461 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn01975_c0': '>', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn01115_c0': '>', 'rxn08527_c0': '<', 'rxn01476_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fac0f2e5c0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:48:42,466 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new']]
2026-01-13 19:48:42,487 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:42,707 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:48:42,741 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:43,138 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:43,157 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:43,191 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:48:43,211 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:43,436 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 19:48:43,458 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:44,088 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:48:44,115 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:44,726 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:48:44,735 - INFO - cpd00425 not found in model!
2026-01-13 19:48:44,736 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:48:44,746 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:45,238 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:48:45,272 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:46,586 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 19:48:46,593 - INFO - cpd08701 not found in model!
2026-01-13 19:48:46,595 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:48:46,596 - INFO - cpd01024 not found in model!
2026-01-13 19:48:46,597 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:48:46,602 - INFO - cpd08701 not found in model!
2026-01-13 19:48:46,603 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:48:46,604 - INFO - cpd01024 not found in model!
2026-01-13 19:48:46,605 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:48:46,614 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:47,267 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:48:47,294 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:47,500 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:48:47,528 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:48,139 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:48:48,159 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:48,909 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:48:48,936 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:49,629 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:48:49,656 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:49,744 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:48:49,765 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:49,899 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:48:49,919 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:50,012 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:48:50,032 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:50,121 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:48:50,146 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:50,406 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:48:50,416 - INFO - cpd11632 not found in model!
2026-01-13 19:48:50,417 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:48:50,427 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:51,442 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:51,472 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:48:51,492 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:48:51,506 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:48:51,512 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:51,526 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:51,927 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 19:48:51,935 - INFO - cpd00187 not found in model!
2026-01-13 19:48:51,936 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:48:51,947 - INFO - cpd00187 not found in model!
2026-01-13 19:48:51,949 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:48:51,958 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:52,387 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:48:52,420 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:53,050 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:53,073 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:53,089 - WARNING - No gapfilling solution found before filtering for Glyc activating rxn00062_c0

Removing ungapfillable media Glyc

2026-01-13 19:48:53,114 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:48:53,129 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:53,143 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:53,518 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:48:53,537 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:54,537 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:48:54,565 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:55,402 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 19:48:55,422 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:48:55,424 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:48:55,445 - INFO - Objective with gapfill database:19.125000000000007; min objective:0.01
2026-01-13 19:48:55,474 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00100_e0': '<', 'rxn01975_c0': '>', 'rxn05581_c0': '<', 'rxn01115_c0': '>', 'rxn08557_c0': '>', 'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a140>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:48:55,476 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:48:55,477 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:48:55,479 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:48:55,480 - INFO - integrating rxn: rxn01115_c0
2026-01-13 19:48:55,481 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:48:55,482 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:48:55,483 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new']]
2026-01-13 19:48:55,489 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:48:55,490 - INFO - Glyc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,491 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,492 - INFO - Glyc.O2/rxn00062_c0:rxn01115_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,493 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,494 - INFO - Glyc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,499 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a140>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn01975_c0': '>', 'rxn05581_c0': '<', 'rxn01115_c0': '>', 'rxn08557_c0': '>', 'rxn01476_c0': '>'}, 'reversed': {}}
2026-01-13 19:48:55,499 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00100_e0': '<', 'rxn01975_c0': '>', 'rxn05581_c0': '<', 'rxn01115_c0': '>', 'rxn08557_c0': '>', 'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a140>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:48:55,503 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new']]
2026-01-13 19:48:55,523 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:48:55,550 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a3b0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:48:55,553 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:48:55,554 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:48:55,555 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:48:55,556 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:48:55,557 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:48:55,558 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:55,559 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:48:55,560 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:55,561 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:48:55,562 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:55,563 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:48:55,569 - INFO - Fum.O2/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:3
2026-01-13 19:48:55,570 - INFO - Fum.O2/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:3
2026-01-13 19:48:55,571 - INFO - Fum.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:3
2026-01-13 19:48:55,572 - INFO - Fum.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:3
2026-01-13 19:48:55,573 - INFO - Fum.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:3
2026-01-13 19:48:55,574 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:48:55,575 - INFO - Fum.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:3
2026-01-13 19:48:55,576 - INFO - Fum.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:3
2026-01-13 19:48:55,577 - INFO - Fum.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:3
2026-01-13 19:48:55,578 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:48:55,583 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a3b0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn00973_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:48:55,584 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a3b0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:48:55,587 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:48:55,607 - INFO - Objective with gapfill database:19.125000000000007; min objective:0.01
2026-01-13 19:48:55,634 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a560>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:48:55,636 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:48:55,637 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:48:55,638 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:48:55,639 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:48:55,640 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:55,641 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:48:55,642 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:48:55,643 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:55,643 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:48:55,644 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:55,645 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:48:55,651 - INFO - Succ.O2/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:2
2026-01-13 19:48:55,652 - INFO - Succ.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,653 - INFO - Succ.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,654 - INFO - Succ.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,655 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,656 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,657 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,658 - INFO - Succ.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,659 - INFO - Succ.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,660 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,665 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a560>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:48:55,665 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a560>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:48:55,669 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:48:55,696 - INFO - Objective with gapfill database:16.250000000000007; min objective:0.01
2026-01-13 19:48:55,723 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00499_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a890>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:48:55,725 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:48:55,726 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:48:55,727 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:48:55,729 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:48:55,730 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:48:55,730 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:48:55,731 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:48:55,733 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:48:55,733 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:48:55,734 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:48:55,735 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:55,735 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:55,740 - INFO - cpd00159 not found in model!
2026-01-13 19:48:55,740 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:48:55,743 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:48:55,744 - INFO - LLac.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,745 - INFO - LLac.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,746 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,747 - INFO - LLac.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,748 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,749 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,750 - INFO - LLac.O2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,751 - INFO - LLac.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,751 - INFO - LLac.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:2
2026-01-13 19:48:55,752 - INFO - LLac.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:48:55,757 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a890>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00499_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:48:55,759 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00256_c0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00499_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78a890>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:48:55,762 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:48:55,783 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:56,012 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:48:56,022 - INFO - cpd11632 not found in model!
2026-01-13 19:48:56,023 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:48:56,035 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:56,406 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:48:56,429 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:57,414 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:48:57,438 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:58,005 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:48:58,026 - INFO - Objective with gapfill database:34.5; min objective:0.01
2026-01-13 19:48:58,053 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01975_c0': '>', 'rxn01476_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8a470>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:48:58,056 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:48:58,057 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:48:58,059 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:48:58,060 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:48:58,062 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:48:58,063 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:48:58,064 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:48:58,065 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:48:58,080 - INFO - Glc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:5
2026-01-13 19:48:58,081 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:48:58,082 - INFO - rxn00250_c0< not needed:13.0
2026-01-13 19:48:58,083 - INFO - rxn08901_c0> not needed:13.0
2026-01-13 19:48:58,084 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:48:58,085 - INFO - Glc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:5
2026-01-13 19:48:58,086 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:48:58,090 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8a470>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn01975_c0': '>', 'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:48:58,091 - INFO - Unneeded: [['rxn00250_c0', '<', 'new', -100, None], ['rxn08901_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {}, 'new': {'rxn01975_c0': '>', 'rxn01476_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8a470>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:48:58,094 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:48:58,113 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:58,190 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:48:58,210 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:59,649 - WARNING - No gapfilling solution found before filtering for Glyc activating rxn00062_c0

Removing ungapfillable media Glyc

2026-01-13 19:48:59,681 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:59,800 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:48:59,839 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:48:59,864 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:48:59,958 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:48:59,978 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:00,335 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:00,373 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:49:00,392 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 19:49:00,411 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:01,451 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 19:49:01,475 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:49:01,501 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '>', 'rxn01333_c0': '<', 'rxn05602_c0': '<', 'rxn01187_c0': '>', 'rxn00548_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6ec550>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:49:01,503 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:49:01,504 - INFO - integrating rxn: rxn01333_c0
2026-01-13 19:49:01,505 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:49:01,506 - INFO - integrating rxn: rxn01187_c0
2026-01-13 19:49:01,508 - INFO - integrating rxn: rxn00548_c0
2026-01-13 19:49:01,509 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new']]
2026-01-13 19:49:01,515 - INFO - cpd08021 not found in model!
2026-01-13 19:49:01,516 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:49:01,521 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00159_e0> needed:0.0 with min obj:0.01
2026-01-13 19:49:01,522 - INFO - Glc.DMSO/rxn00062_c0:rxn01333_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:01,523 - INFO - Glc.DMSO/rxn00062_c0:rxn05602_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:01,524 - INFO - rxn01187_c0> not needed:2.5
2026-01-13 19:49:01,525 - INFO - Glc.DMSO/rxn00062_c0:rxn00548_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:01,530 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6ec550>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '>', 'rxn01333_c0': '<', 'rxn05602_c0': '<', 'rxn00548_c0': '>'}, 'reversed': {}}
2026-01-13 19:49:01,532 - INFO - Unneeded: [['rxn01187_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '>', 'rxn01333_c0': '<', 'rxn05602_c0': '<', 'rxn01187_c0': '>', 'rxn00548_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6ec550>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:49:01,535 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new']]
2026-01-13 19:49:01,555 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:49:01,581 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '>', 'rxn01333_c0': '<', 'rxn05602_c0': '<', 'rxn00548_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6ec3d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:49:01,583 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:49:01,584 - INFO - integrating rxn: rxn01333_c0
2026-01-13 19:49:01,584 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:49:01,585 - INFO - integrating rxn: rxn00548_c0
2026-01-13 19:49:01,586 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new']]
2026-01-13 19:49:01,591 - INFO - cpd00811 not found in model!
2026-01-13 19:49:01,591 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:49:01,595 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00159_e0> needed:0.0 with min obj:0.01
2026-01-13 19:49:01,596 - INFO - Glc.TMAO/rxn00062_c0:rxn01333_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:01,597 - INFO - Glc.TMAO/rxn00062_c0:rxn05602_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:01,598 - INFO - Glc.TMAO/rxn00062_c0:rxn00548_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:01,603 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6ec3d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '>', 'rxn01333_c0': '<', 'rxn05602_c0': '<', 'rxn00548_c0': '>'}, 'reversed': {}}
2026-01-13 19:49:01,603 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '>', 'rxn01333_c0': '<', 'rxn05602_c0': '<', 'rxn00548_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6ec3d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:49:01,607 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new']]
2026-01-13 19:49:01,626 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:02,016 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:49:02,039 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:49:02,067 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb75210>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:49:02,070 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:49:02,071 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:49:02,072 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:49:02,073 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:49:02,074 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:49:02,075 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:49:02,077 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:49:02,078 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:49:02,078 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:49:02,079 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:49:02,080 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:49:02,081 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:49:02,089 - INFO - Fum/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:0.01
2026-01-13 19:49:02,090 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:49:02,091 - INFO - Fum/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:02,092 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:02,093 - INFO - Fum/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:02,094 - INFO - Fum/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:02,095 - INFO - Fum/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:02,096 - INFO - Fum/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:02,096 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:02,097 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:02,098 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:02,105 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb75210>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}}
2026-01-13 19:49:02,105 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb75210>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:49:02,109 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:49:02,131 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:03,882 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 19:49:03,901 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:49:03,927 - INFO - Initial solution: {'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00786_c0': '>', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4f760>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:49:03,930 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:49:03,931 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:49:03,932 - INFO - integrating rxn: rxn00786_c0
2026-01-13 19:49:03,933 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:49:03,934 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:49:03,934 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:49:03,935 - INFO - integrating rxn: rxn00747_c0
2026-01-13 19:49:03,936 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:49:03,937 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:49:03,941 - INFO - cpd08021 not found in model!
2026-01-13 19:49:03,942 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:49:03,946 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:49:03,947 - INFO - Glc.DMSO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:03,948 - INFO - Glc.DMSO/rxn00062_c0:rxn00786_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:03,949 - INFO - Glc.DMSO/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:03,950 - INFO - Glc.DMSO/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:03,951 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:03,952 - INFO - Glc.DMSO/rxn00062_c0:rxn00747_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:03,953 - INFO - Glc.DMSO/rxn00062_c0:rxn01106_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:03,958 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4f760>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00786_c0': '>', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}}
2026-01-13 19:49:03,959 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00786_c0': '>', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4f760>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:49:03,962 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:49:03,982 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:49:04,007 - INFO - Initial solution: {'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn01334_c0': '>', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4fe50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:49:04,009 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:49:04,010 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:49:04,012 - INFO - integrating rxn: rxn01334_c0
2026-01-13 19:49:04,013 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:49:04,014 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:49:04,015 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:49:04,016 - INFO - integrating rxn: rxn00747_c0
2026-01-13 19:49:04,017 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:49:04,017 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01334_c0', '>', 'new']]
2026-01-13 19:49:04,021 - INFO - cpd00811 not found in model!
2026-01-13 19:49:04,022 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:49:04,025 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:49:04,026 - INFO - Glc.TMAO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:04,027 - INFO - Glc.TMAO/rxn00062_c0:rxn01334_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:04,029 - INFO - Glc.TMAO/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:04,030 - INFO - Glc.TMAO/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:04,031 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:04,032 - INFO - Glc.TMAO/rxn00062_c0:rxn00747_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:04,033 - INFO - Glc.TMAO/rxn00062_c0:rxn01106_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:04,038 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4fe50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn01334_c0': '>', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}}
2026-01-13 19:49:04,039 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00747_c0': '<', 'rxn01106_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn01334_c0': '>', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a4fe50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:49:04,042 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01334_c0', '>', 'new']]
2026-01-13 19:49:04,061 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:04,237 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 19:49:04,245 - INFO - cpd00187 not found in model!
2026-01-13 19:49:04,246 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:49:04,251 - INFO - cpd00187 not found in model!
2026-01-13 19:49:04,252 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:49:04,260 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:04,818 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:49:04,841 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:49:04,859 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:49:04,872 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:49:04,877 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:49:04,904 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:05,377 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:49:05,387 - INFO - cpd01024 not found in model!
2026-01-13 19:49:05,388 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:49:05,398 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:05,975 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:49:05,994 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:49:06,007 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:49:06,025 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:49:06,029 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:49:06,059 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:06,140 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:49:06,162 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:06,246 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:49:06,267 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:06,557 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:49:06,576 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:06,788 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:49:06,817 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:07,265 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:49:07,299 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:07,674 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 19:49:07,709 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:08,292 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:49:08,331 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:49:08,357 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:08,706 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:49:08,728 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:49:08,755 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78b010>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:49:08,758 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:49:08,759 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:49:08,761 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:49:08,763 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:49:08,764 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:49:08,765 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:49:08,767 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:49:08,768 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:49:08,769 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:49:08,776 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:49:08,777 - INFO - Glc/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:08,778 - INFO - Glc/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:08,779 - INFO - Glc/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:08,780 - INFO - rxn00102_c0> not needed:2.5
2026-01-13 19:49:08,781 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:08,782 - INFO - Glc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:08,783 - INFO - rxn00250_c0< not needed:2.5
2026-01-13 19:49:08,789 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78b010>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:49:08,789 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78b010>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:49:08,793 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:49:08,814 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:08,909 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:49:08,932 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:09,109 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:49:09,135 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:11,030 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:49:11,053 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:11,317 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:49:11,336 - INFO - Objective with gapfill database:19.125000000000007; min objective:0.01
2026-01-13 19:49:11,363 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn08557_c0': '>', 'rxn00148_c0': '<', 'rxn00250_c0': '<', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8ab90>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:49:11,366 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:49:11,368 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:49:11,370 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:49:11,371 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:49:11,373 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:49:11,374 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:49:11,375 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new']]
2026-01-13 19:49:11,381 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:49:11,382 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:49:11,383 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:49:11,384 - INFO - Glyc.O2/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:2
2026-01-13 19:49:11,385 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:49:11,386 - INFO - Glyc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:49:11,390 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8ab90>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn08557_c0': '>', 'rxn00148_c0': '<', 'rxn00250_c0': '<', 'rxn08971_c0': '>'}, 'reversed': {}}
2026-01-13 19:49:11,391 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn08557_c0': '>', 'rxn00148_c0': '<', 'rxn00250_c0': '<', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8ab90>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:49:11,394 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new']]
2026-01-13 19:49:11,413 - INFO - Objective with gapfill database:17.499999999999996; min objective:0.01
2026-01-13 19:49:11,439 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8ace0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:49:11,440 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:49:11,442 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:49:11,443 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:49:11,444 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn08901_c0', '>', 'new']]
2026-01-13 19:49:11,451 - INFO - rxn00250_c0< not needed:6.25
2026-01-13 19:49:11,452 - INFO - rxn08901_c0> not needed:6.25
2026-01-13 19:49:11,453 - INFO - Fum.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:3
2026-01-13 19:49:11,457 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8ace0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'rxn08971_c0': '>'}, 'reversed': {}}
2026-01-13 19:49:11,458 - INFO - Unneeded: [['rxn00250_c0', '<', 'new', -100, None], ['rxn08901_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {}, 'new': {'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8ace0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:49:11,461 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new']]
2026-01-13 19:49:11,480 - INFO - Objective with gapfill database:18.250000000000004; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:11,507 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8af80>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:49:11,509 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:49:11,510 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:49:11,512 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:49:11,512 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:49:11,513 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08901_c0', '>', 'new']]
2026-01-13 19:49:11,519 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:49:11,520 - INFO - rxn00250_c0< not needed:7.0
2026-01-13 19:49:11,521 - INFO - rxn08901_c0> not needed:7.0
2026-01-13 19:49:11,522 - INFO - Succ.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:49:11,526 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8af80>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn09269_c0': '>', 'rxn08971_c0': '>'}, 'reversed': {}}
2026-01-13 19:49:11,528 - INFO - Unneeded: [['rxn00250_c0', '<', 'new', -100, None], ['rxn08901_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {}, 'new': {'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8af80>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:49:11,530 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0
2026-01-13 19:49:11,531 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]

Removing ungapfillable media Light

2026-01-13 19:49:11,539 - INFO - cpd01024 not found in model!
2026-01-13 19:49:11,540 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:49:11,550 - INFO - Objective with gapfill database:16.250000000000007; min objective:0.01
2026-01-13 19:49:11,551 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:49:11,575 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn00499_c0': '>', 'rxn00250_c0': '<', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8b460>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:49:11,577 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:49:11,579 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:49:11,580 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:49:11,581 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:49:11,581 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:49:11,582 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:49:11,585 - INFO - cpd00159 not found in model!
2026-01-13 19:49:11,586 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:49:11,589 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:49:11,590 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:49:11,591 - INFO - LLac.O2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:2
2026-01-13 19:49:11,592 - INFO - LLac.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:49:11,592 - INFO - LLac.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:49:11,596 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8b460>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn00499_c0': '>', 'rxn00250_c0': '<', 'rxn08971_c0': '>'}, 'reversed': {}}
2026-01-13 19:49:11,598 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn00499_c0': '>', 'rxn00250_c0': '<', 'rxn08971_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8b460>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:49:11,601 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:49:11,619 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:12,002 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:49:12,036 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:13,568 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:49:13,612 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:49:13,639 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:13,941 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:49:13,962 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:49:13,980 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:49:14,003 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:49:14,031 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8ee90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:49:14,033 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:49:14,034 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:49:14,035 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:49:14,036 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:49:14,037 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:49:14,038 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:49:14,039 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:49:14,040 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:49:14,041 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:49:14,042 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:49:14,047 - INFO - cpd00159 not found in model!
2026-01-13 19:49:14,048 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:49:14,051 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:49:14,052 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:49:14,053 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:14,054 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:14,055 - INFO - Llac/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:14,056 - INFO - Llac/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:14,057 - INFO - Llac/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:49:14,058 - INFO - Llac/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:14,059 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:49:14,065 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8ee90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:49:14,066 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8ee90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:49:14,069 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:49:14,091 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:14,580 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:49:14,607 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:49:14,625 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:49:14,661 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:15,176 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:49:15,200 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:16,016 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:49:16,039 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:17,102 - WARNING - No gapfilling solution found before filtering for Etho activating rxn00062_c0

Removing ungapfillable media Etho

2026-01-13 19:49:17,142 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:18,271 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:49:18,297 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:20,033 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:49:20,057 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:20,387 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:49:20,405 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:22,429 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:49:22,439 - INFO - cpd11632 not found in model!
2026-01-13 19:49:22,440 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:49:22,452 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:22,905 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:49:22,924 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:23,103 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:49:23,113 - INFO - cpd11632 not found in model!
2026-01-13 19:49:23,114 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:49:23,125 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:24,236 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:49:24,266 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:49:24,295 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:24,718 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:49:24,742 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:25,398 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:49:25,421 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:28,578 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:49:28,607 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:30,115 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:49:30,126 - INFO - cpd11632 not found in model!
2026-01-13 19:49:30,127 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:49:30,138 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:30,248 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:49:30,271 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:31,082 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:49:31,108 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:32,659 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:49:32,685 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:34,059 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:49:34,088 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:35,609 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:49:35,634 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:37,316 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:49:37,345 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:38,585 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:49:38,609 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:49:42,593 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:49:42,617 - INFO - Objective with gapfill database:3.5000000000000004; min objective:0.01
2026-01-13 19:49:42,636 - INFO - Objective with gapfill database:3.5000000000000004; min objective:0.01
2026-01-13 19:49:42,660 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:50:48,171 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:50:48,184 - INFO - cpd00425 not found in model!
2026-01-13 19:50:48,185 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:50:48,197 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:02,647 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:51:02,676 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:51:02,705 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa7985f040>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:51:02,707 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:51:02,709 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:51:02,711 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:02,712 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:51:02,714 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:51:02,715 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:51:02,717 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:51:02,717 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:51:02,733 - INFO - Glc.O2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:5
2026-01-13 19:51:02,735 - INFO - Glc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:5
2026-01-13 19:51:02,736 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:5
2026-01-13 19:51:02,737 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:51:02,738 - INFO - Glc.O2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:5
2026-01-13 19:51:02,740 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:51:02,741 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:51:02,743 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa7985f040>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:02,744 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa7985f040>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:51:02,748 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:51:02,769 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:17,212 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:51:17,233 - INFO - Objective with gapfill database:19.125000000000018; min objective:0.01
2026-01-13 19:51:17,261 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08556_c0': '>', 'rxn14422_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn10122_c0': '>', 'rxn14421_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c39ae0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:51:17,263 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:51:17,265 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:51:17,266 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:51:17,268 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:51:17,270 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:17,271 - INFO - integrating rxn: rxn08556_c0
2026-01-13 19:51:17,273 - INFO - integrating rxn: rxn14422_c0
2026-01-13 19:51:17,275 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:51:17,277 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:51:17,278 - INFO - integrating rxn: rxn10122_c0
2026-01-13 19:51:17,280 - INFO - integrating rxn: rxn14421_c0
2026-01-13 19:51:17,281 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:51:17,282 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:51:17,289 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:2
2026-01-13 19:51:17,290 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:51:17,291 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,292 - INFO - Glyc.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,293 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,294 - INFO - Glyc.O2/rxn00062_c0:rxn08556_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,295 - INFO - Glyc.O2/rxn00062_c0:rxn14422_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,296 - INFO - Glyc.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,297 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,298 - INFO - Glyc.O2/rxn00062_c0:rxn10122_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,299 - INFO - Glyc.O2/rxn00062_c0:rxn14421_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,300 - INFO - Glyc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,305 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c39ae0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08556_c0': '>', 'rxn14422_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn10122_c0': '>', 'rxn14421_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:51:17,306 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08556_c0': '>', 'rxn14422_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn10122_c0': '>', 'rxn14421_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c39ae0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:51:17,309 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:51:17,330 - INFO - Objective with gapfill database:17.500000000000014; min objective:0.01
2026-01-13 19:51:17,357 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c39ba0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:51:17,359 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:51:17,361 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:51:17,362 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:51:17,363 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:17,365 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:51:17,365 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:51:17,366 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:51:17,367 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:51:17,367 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:51:17,368 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:51:17,374 - INFO - Fum.O2/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:3
2026-01-13 19:51:17,375 - INFO - Fum.O2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:3
2026-01-13 19:51:17,376 - INFO - Fum.O2/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:3
2026-01-13 19:51:17,377 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:51:17,378 - INFO - Fum.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:3
2026-01-13 19:51:17,379 - INFO - Fum.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:3
2026-01-13 19:51:17,380 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:51:17,381 - INFO - Fum.O2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:3
2026-01-13 19:51:17,382 - INFO - Fum.O2/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:3
2026-01-13 19:51:17,387 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c39ba0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:51:17,388 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c39ba0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:51:17,391 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:51:17,411 - INFO - Objective with gapfill database:19.125; min objective:0.01
2026-01-13 19:51:17,438 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00036_e0': '<', 'EX_cpd00029_e0': '>', 'rxn09272_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn10122_c0': '>', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c39e70>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:51:17,441 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:51:17,442 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:51:17,444 - INFO - integrating rxn: rxn09272_c0
2026-01-13 19:51:17,444 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:51:17,446 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:17,447 - INFO - integrating rxn: rxn14422_c0
2026-01-13 19:51:17,448 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:51:17,449 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:51:17,450 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:51:17,451 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:51:17,452 - INFO - integrating rxn: rxn10122_c0
2026-01-13 19:51:17,453 - INFO - integrating rxn: rxn14421_c0
2026-01-13 19:51:17,454 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:51:17,460 - INFO - Succ.O2/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:2
2026-01-13 19:51:17,461 - INFO - Succ.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:2
2026-01-13 19:51:17,462 - INFO - Succ.O2/rxn00062_c0:rxn09272_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,464 - INFO - Succ.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,465 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,465 - INFO - Succ.O2/rxn00062_c0:rxn14422_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,466 - INFO - Succ.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,468 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,469 - INFO - Succ.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,469 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,470 - INFO - Succ.O2/rxn00062_c0:rxn10122_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,471 - INFO - Succ.O2/rxn00062_c0:rxn14421_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,476 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c39e70>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'EX_cpd00029_e0': '>', 'rxn09272_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn10122_c0': '>', 'rxn14421_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:17,477 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00036_e0': '<', 'EX_cpd00029_e0': '>', 'rxn09272_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn10122_c0': '>', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c39e70>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:51:17,481 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:51:17,501 - INFO - Objective with gapfill database:16.249999999999993; min objective:0.01
2026-01-13 19:51:17,529 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn14426_c0': '>', 'rxn10122_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3a320>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:51:17,538 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:51:17,540 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:51:17,542 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:51:17,543 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:51:17,544 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:17,546 - INFO - integrating rxn: rxn14425_c0
2026-01-13 19:51:17,548 - INFO - integrating rxn: rxn14426_c0
2026-01-13 19:51:17,549 - INFO - integrating rxn: rxn10122_c0
2026-01-13 19:51:17,550 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:51:17,557 - INFO - LLac.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:2
2026-01-13 19:51:17,558 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:51:17,559 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,560 - INFO - LLac.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,561 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:51:17,562 - INFO - LLac.O2/rxn00062_c0:rxn14425_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,563 - INFO - LLac.O2/rxn00062_c0:rxn14426_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,564 - INFO - LLac.O2/rxn00062_c0:rxn10122_c0> needed:0.0 with min obj:2
2026-01-13 19:51:17,569 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3a320>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn14426_c0': '>', 'rxn10122_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:17,570 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn14426_c0': '>', 'rxn10122_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3a320>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:51:17,573 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:51:17,594 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:23,714 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:51:23,734 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:24,665 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:51:24,686 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:31,214 - WARNING - No gapfilling solution found for Trimethylamine.H2 activating rxn00062_c0
2026-01-13 19:51:31,776 - INFO - Loading model: Firmicutes.13

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:31,996 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:51:32,017 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:51:32,045 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3a8f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:51:32,047 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:51:32,048 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:51:32,049 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:32,051 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:51:32,051 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:51:32,053 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:51:32,054 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:51:32,055 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:51:32,062 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:51:32,063 - INFO - Glc/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:32,065 - INFO - Glc/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:32,066 - INFO - Glc/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:32,067 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:32,068 - INFO - Glc/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:32,070 - INFO - Glc/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:32,075 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3a8f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:32,076 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3a8f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:51:32,079 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:51:32,100 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:51:32,171 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:51:33,014 - INFO -   Loading template...
2026-01-13 19:51:33,492 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:33,499 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:37,729 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 19:51:37,741 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:51:37,749 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:51:37,773 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:51:37,799 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:38,357 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 19:51:38,377 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:38,551 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 19:51:38,574 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:39,243 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:51:39,262 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:51:39,288 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:51:39,309 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:41,353 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:51:41,363 - INFO - cpd01024 not found in model!
2026-01-13 19:51:41,364 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:51:41,375 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:41,494 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:51:41,513 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:43,881 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:51:43,908 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:44,411 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:51:44,421 - INFO - cpd00425 not found in model!
2026-01-13 19:51:44,422 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:51:44,433 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:46,327 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:51:46,348 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:46,427 - WARNING - No gapfilling solution found for Trimethylamine.H2 activating rxn00062_c0
2026-01-13 19:51:46,479 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:51:46,510 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:46,930 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:51:46,972 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:51:46,975 - INFO - Loading model: Firmicutes.7
2026-01-13 19:51:46,997 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:51:47,440 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:48,283 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:51:48,314 - INFO - Objective with gapfill database:3.5; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:48,334 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:51:48,354 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:51:48,351 - INFO -   Loading template...
2026-01-13 19:51:48,370 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0
2026-01-13 19:51:48,391 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:48,532 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0
2026-01-13 19:51:48,558 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:51:48,785 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:48,792 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:50,158 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:51:50,194 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:50,336 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:51:50,363 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:53,867 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:51:53,887 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:51:53,912 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8b940>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:51:53,915 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:51:53,916 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:51:53,918 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:51:53,920 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:53,921 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:51:53,930 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:51:53,930 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:51:53,932 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:51:53,933 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:51:53,933 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:51:53,934 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:51:53,940 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:51:53,941 - INFO - Glc/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:53,942 - INFO - rxn05938_c0< not needed:0.5
2026-01-13 19:51:53,943 - INFO - rxn07191_c0< not needed:0.5
2026-01-13 19:51:53,944 - INFO - Glc/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:53,945 - INFO - Glc/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:53,946 - INFO - Glc/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:53,947 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:53,948 - INFO - Glc/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:53,949 - INFO - Glc/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:53,955 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8b940>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:53,956 - INFO - Unneeded: [['rxn05938_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56c8b940>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:51:53,960 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:51:53,981 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:54,327 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:51:54,360 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:54,618 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:51:54,643 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:54,855 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:51:54,872 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0
2026-01-13 19:51:54,873 - INFO - Objective with gapfill database:0.0; min objective:0.01

Removing ungapfillable media For.SO4.H2

2026-01-13 19:51:54,896 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:55,114 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:51:55,140 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:57,944 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:51:57,964 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:58,053 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:51:58,074 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:58,203 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0
2026-01-13 19:51:58,223 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:51:58,250 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6ed840>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:51:58,253 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:51:58,254 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:51:58,255 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:51:58,256 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:51:58,257 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:58,258 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:51:58,260 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:51:58,261 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:51:58,261 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new']]
2026-01-13 19:51:58,266 - INFO - cpd11640 not found in model!
2026-01-13 19:51:58,266 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:51:58,270 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,271 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,272 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,273 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,274 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,274 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,275 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,276 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,281 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6ed840>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:58,282 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6ed840>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:51:58,286 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new']]
2026-01-13 19:51:58,305 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:51:58,330 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6edcf0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:51:58,332 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:51:58,332 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:51:58,333 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:51:58,334 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:51:58,335 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:58,336 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:51:58,337 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:51:58,337 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:51:58,338 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new']]
2026-01-13 19:51:58,345 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,346 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,347 - INFO - LLac.SO4/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,348 - INFO - LLac.SO4/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,349 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,349 - INFO - LLac.SO4/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,350 - INFO - LLac.SO4/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,351 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,356 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6edcf0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:58,357 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8a6edcf0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:51:58,361 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00159_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn01333_c0', '<', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01187_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00548_c0', '>', 'new']]
2026-01-13 19:51:58,380 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:58,743 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0
2026-01-13 19:51:58,762 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:51:58,787 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a303d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:51:58,790 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:51:58,791 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:51:58,792 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:51:58,793 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:58,794 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:51:58,795 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:51:58,796 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:51:58,797 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01334_c0', '>', 'new']]
2026-01-13 19:51:58,801 - INFO - cpd00159 not found in model!
2026-01-13 19:51:58,802 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:51:58,803 - INFO - cpd11640 not found in model!
2026-01-13 19:51:58,804 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:51:58,807 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,808 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,809 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,810 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,810 - INFO - LLac.SO4.H2/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,811 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,812 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,817 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a303d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:58,818 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a303d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:51:58,821 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01334_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01334_c0', '>', 'new']]
2026-01-13 19:51:58,840 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:51:58,865 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a30880>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:51:58,867 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:51:58,867 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:51:58,868 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:51:58,869 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:51:58,870 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:51:58,870 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:51:58,871 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:51:58,872 - INFO - Full solution: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01334_c0', '>', 'new']]
2026-01-13 19:51:58,877 - INFO - cpd00159 not found in model!
2026-01-13 19:51:58,877 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:51:58,880 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,881 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,882 - INFO - LLac.SO4/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,883 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,883 - INFO - LLac.SO4/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:51:58,884 - INFO - LLac.SO4/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,885 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:51:58,890 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a30880>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:58,891 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa85a30880>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:51:58,894 - INFO - Cumulative: [['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01334_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01334_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn00604_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01106_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00747_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00786_c0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01334_c0', '>', 'new']]
2026-01-13 19:51:58,913 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:59,097 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:51:59,106 - INFO - cpd11632 not found in model!
2026-01-13 19:51:59,107 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:51:59,118 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:51:59,365 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:51:59,389 - INFO - Objective with gapfill database:34.5; min objective:0.01
2026-01-13 19:51:59,417 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01116_c0': '>', 'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa748effd0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:51:59,419 - INFO - integrating rxn: rxn01116_c0
2026-01-13 19:51:59,421 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:51:59,422 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new']]
2026-01-13 19:51:59,437 - INFO - Glc.O2/rxn00062_c0:rxn01116_c0> needed:0.0 with min obj:5
2026-01-13 19:51:59,438 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:51:59,440 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa748effd0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn01116_c0': '>', 'rxn01476_c0': '>'}, 'reversed': {}}
2026-01-13 19:51:59,441 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn01116_c0': '>', 'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa748effd0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:51:59,445 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new']]
2026-01-13 19:51:59,466 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:00,487 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:52:00,513 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:52:00,542 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3b1c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:00,544 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:52:00,546 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:00,547 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:52:00,548 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:00,549 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:52:00,550 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:52:00,551 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:00,552 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:00,553 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:52:00,554 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:52:00,565 - INFO - Fum/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:0.01
2026-01-13 19:52:00,566 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:00,567 - INFO - Fum/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:00,569 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:00,570 - INFO - Fum/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:00,571 - INFO - Fum/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:00,572 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:00,573 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:00,574 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:00,580 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3b1c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:52:00,580 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3b1c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:00,583 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:52:00,604 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:01,098 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:52:01,134 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:52:01,162 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:01,918 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:52:01,946 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:03,223 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:52:03,245 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:52:03,274 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78b730>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:03,276 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:52:03,277 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:03,279 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:52:03,280 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:03,281 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:52:03,282 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:52:03,282 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:52:03,283 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:03,284 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:03,285 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:52:03,286 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:03,293 - INFO - Fum/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:0.01
2026-01-13 19:52:03,294 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:03,295 - INFO - Fum/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:03,296 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:03,297 - INFO - Fum/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:03,298 - INFO - Fum/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:03,299 - INFO - Fum/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:03,300 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:03,301 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:03,302 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:03,307 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78b730>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}}
2026-01-13 19:52:03,307 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78b730>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:03,312 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:03,332 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:06,485 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:52:06,508 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:07,249 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:52:07,268 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:08,048 - WARNING - No gapfilling solution found before filtering for Pyr activating rxn00062_c0

Removing ungapfillable media Pyr

2026-01-13 19:52:08,080 - INFO - Objective with gapfill database:2.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:08,108 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:08,156 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:52:08,182 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:08,242 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 19:52:08,250 - INFO - cpd08701 not found in model!
2026-01-13 19:52:08,251 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:52:08,252 - INFO - cpd01024 not found in model!
2026-01-13 19:52:08,253 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:08,259 - INFO - cpd08701 not found in model!
2026-01-13 19:52:08,260 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:52:08,261 - INFO - cpd01024 not found in model!
2026-01-13 19:52:08,262 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:08,271 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:09,063 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:52:09,074 - INFO - cpd01024 not found in model!
2026-01-13 19:52:09,075 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:09,086 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:09,117 - WARNING - No gapfilling solution found before filtering for Glyc activating rxn00062_c0

Removing ungapfillable media Glyc

2026-01-13 19:52:09,157 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:09,160 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 19:52:09,168 - INFO - cpd08701 not found in model!
2026-01-13 19:52:09,168 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:52:09,170 - INFO - cpd01024 not found in model!
2026-01-13 19:52:09,170 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:09,176 - INFO - cpd08701 not found in model!
2026-01-13 19:52:09,177 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:52:09,178 - INFO - cpd01024 not found in model!
2026-01-13 19:52:09,179 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:09,188 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:09,490 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:52:09,501 - INFO - cpd01024 not found in model!
2026-01-13 19:52:09,502 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:09,513 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:10,153 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:52:10,178 - INFO - Objective with gapfill database:34.500000000000036; min objective:0.01
2026-01-13 19:52:10,210 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faac545f30>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:52:10,212 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:10,214 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:52:10,215 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:10,217 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:52:10,218 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:52:10,220 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:10,221 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:52:10,223 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:10,224 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:52:10,225 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:52:10,241 - INFO - Glc.O2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:5
2026-01-13 19:52:10,242 - INFO - Glc.O2/rxn00062_c0:rxn05938_c0< needed:1.5 with min obj:5
2026-01-13 19:52:10,243 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:1.5 with min obj:5
2026-01-13 19:52:10,245 - INFO - Glc.O2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:5
2026-01-13 19:52:10,246 - INFO - Glc.O2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:5
2026-01-13 19:52:10,247 - INFO - Glc.O2/rxn00062_c0:rxn00250_c0< needed:2.5 with min obj:5
2026-01-13 19:52:10,248 - INFO - Glc.O2/rxn00062_c0:rxn05226_c0> needed:3.25 with min obj:5
2026-01-13 19:52:10,249 - INFO - Glc.O2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:5
2026-01-13 19:52:10,250 - INFO - Glc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:5
2026-01-13 19:52:10,252 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faac545f30>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:52:10,253 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79faac545f30>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:52:10,256 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:52:10,278 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:10,380 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:52:10,403 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:11,317 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:52:11,349 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:11,883 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:52:11,916 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:52:11,942 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:12,542 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0
2026-01-13 19:52:12,543 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media H2.SO4Removing ungapfillable media Pyr.NO2

2026-01-13 19:52:12,554 - INFO - cpd11632 not found in model!
2026-01-13 19:52:12,555 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:52:12,566 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:12,571 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:12,977 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:52:12,998 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:14,383 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:52:14,405 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:52:14,433 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn08094_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c3cfd90>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:52:14,436 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:52:14,437 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:52:14,439 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:14,440 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:52:14,442 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:52:14,443 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:52:14,445 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:52:14,445 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:14,447 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:52:14,448 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed']]
2026-01-13 19:52:14,455 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:52:14,456 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,457 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,458 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:52:14,459 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,460 - INFO - Glyc.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:2
2026-01-13 19:52:14,461 - INFO - Glyc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,462 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,463 - INFO - Glyc.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,468 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c3cfd90>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn08094_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}}
2026-01-13 19:52:14,469 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn08094_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c3cfd90>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:52:14,472 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed']]
2026-01-13 19:52:14,492 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 19:52:14,519 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn08527_c0': '<', 'rxn08094_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0070>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:52:14,522 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:52:14,523 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:52:14,524 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:52:14,525 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:52:14,526 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:14,527 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:52:14,528 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:52:14,535 - INFO - Fum.O2/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:3
2026-01-13 19:52:14,536 - INFO - Fum.O2/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:3
2026-01-13 19:52:14,537 - INFO - Fum.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:3
2026-01-13 19:52:14,538 - INFO - Fum.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:3
2026-01-13 19:52:14,539 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:52:14,540 - INFO - Fum.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:3
2026-01-13 19:52:14,545 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0070>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn08527_c0': '<', 'rxn08094_c0': '>'}, 'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}}
2026-01-13 19:52:14,546 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn08527_c0': '<', 'rxn08094_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0070>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:52:14,550 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:52:14,570 - INFO - Objective with gapfill database:19.125000000000004; min objective:0.01
2026-01-13 19:52:14,598 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn08094_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0130>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:52:14,600 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:52:14,601 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:52:14,602 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:52:14,603 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:52:14,604 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:14,605 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:52:14,606 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:52:14,612 - INFO - Succ.O2/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:2
2026-01-13 19:52:14,614 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,615 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:52:14,616 - INFO - Succ.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:2
2026-01-13 19:52:14,617 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,618 - INFO - Succ.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,623 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0130>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn08094_c0': '>'}, 'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}}
2026-01-13 19:52:14,624 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn08094_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0130>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:52:14,629 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:52:14,649 - INFO - Objective with gapfill database:16.249999999999993; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:14,676 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn08527_c0': '<', 'rxn08094_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0640>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:52:14,678 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:52:14,679 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:52:14,679 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:52:14,680 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:52:14,687 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,688 - INFO - LLac.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:2
2026-01-13 19:52:14,689 - INFO - LLac.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:52:14,694 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0640>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn08527_c0': '<', 'rxn08094_c0': '>'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:52:14,695 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn08527_c0': '<', 'rxn08094_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0640>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:52:14,699 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:52:14,719 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:14,720 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:52:14,729 - INFO - cpd00425 not found in model!
2026-01-13 19:52:14,730 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:52:14,741 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:15,438 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:52:15,454 - INFO - Objective with gapfill database:143.8231579611115; min objective:0.01
2026-01-13 19:52:15,468 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:16,209 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:52:16,230 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:52:16,270 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78bd90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:16,272 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:52:16,274 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:16,275 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:52:16,276 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:16,277 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:52:16,278 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:52:16,279 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:52:16,280 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:16,281 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:16,285 - INFO - cpd00159 not found in model!
2026-01-13 19:52:16,286 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:52:16,289 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:52:16,290 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:16,291 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:16,293 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:16,294 - INFO - Llac/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:16,294 - INFO - Llac/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:16,295 - INFO - Llac/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:16,296 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:16,302 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78bd90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:52:16,302 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c78bd90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:16,306 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:16,327 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:16,761 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:52:16,771 - INFO - cpd01024 not found in model!
2026-01-13 19:52:16,772 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:16,783 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:16,884 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:52:16,904 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:17,043 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in Removing ungapfillable media Pyr.SO4

2026-01-13 19:52:17,072 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:17,101 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:52:17,129 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:17,799 - INFO - Objective with gapfill database:143.8231579611115; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:18,208 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 19:52:18,228 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:18,322 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:52:18,347 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:18,411 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn10336_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15166_c0': '>', 'rxn19346_c0': '>', 'rxn00644_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn08154_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:18,414 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:52:18,416 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:52:18,418 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:52:18,420 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:52:18,422 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:52:18,424 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:52:18,425 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:52:18,427 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:52:18,429 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:52:18,430 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:52:18,432 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:52:18,434 - INFO - integrating rxn: rxn00392_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:18,435 - INFO - integrating rxn: rxn09225_c0

2026-01-13 19:52:18,438 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:52:18,439 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:52:18,441 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:52:18,442 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:52:18,444 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:52:18,445 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:52:18,447 - INFO - integrating rxn: rxn05463_c0
2026-01-13 19:52:18,448 - INFO - integrating rxn: rxn04413_c0
2026-01-13 19:52:18,450 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:52:18,451 - INFO - integrating rxn: rxn03087_c0
2026-01-13 19:52:18,453 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:52:18,454 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:52:18,456 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:52:18,457 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:52:18,458 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:52:18,460 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:52:18,462 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:52:18,463 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:52:18,465 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:52:18,466 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:52:18,467 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:52:18,469 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:52:18,470 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:52:18,473 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:52:18,475 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:52:18,476 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:52:18,478 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:52:18,479 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:52:18,481 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:52:18,482 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:52:18,484 - INFO - integrating rxn: rxn12938_c0
2026-01-13 19:52:18,486 - INFO - integrating rxn: rxn12927_c0
2026-01-13 19:52:18,487 - INFO - integrating rxn: rxn12921_c0
2026-01-13 19:52:18,489 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:52:18,488 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:52:18,491 - INFO - integrating rxn: rxn12934_c0

2026-01-13 19:52:18,493 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:52:18,494 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:52:18,496 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:52:18,498 - INFO - integrating rxn: rxn15166_c0
2026-01-13 19:52:18,499 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:52:18,501 - INFO - integrating rxn: rxn00644_c0
2026-01-13 19:52:18,502 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:52:18,504 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:52:18,506 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:52:18,507 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:52:18,509 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:52:18,511 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:52:18,512 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:52:18,513 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:52:18,515 - INFO - integrating rxn: rxn08154_c0
2026-01-13 19:52:18,516 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:52:18,516 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:52:18,519 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:52:18,520 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:52:18,522 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:52:18,523 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15166_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn08154_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:52:18,543 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:52:18,565 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:18,596 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:52:18,600 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:52:18,601 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,605 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,607 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,609 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,611 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,613 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,614 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,616 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,618 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,621 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,623 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,625 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,627 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,629 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,631 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,633 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,635 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,638 - INFO - AuxoMedia/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,640 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,642 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:-3.8493606467696244e-13 with min obj:0.01
2026-01-13 19:52:18,644 - INFO - AuxoMedia/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:18,646 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,648 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:4.0574341952436596e-13 with min obj:0.01
2026-01-13 19:52:18,649 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:-3.685874287254322e-13 with min obj:0.01
2026-01-13 19:52:18,651 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:18,653 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,655 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,657 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,659 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,661 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,663 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,665 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,667 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,671 - INFO - rxn21635_c0> not needed:27.3152031425991
2026-01-13 19:52:18,673 - INFO - rxn16218_c0> not needed:27.315203142599117
2026-01-13 19:52:18,674 - INFO - rxn15949_c0> not needed:27.3152031425991
2026-01-13 19:52:18,676 - INFO - rxn16217_c0> not needed:27.3152031425991
2026-01-13 19:52:18,677 - INFO - rxn15947_c0> not needed:27.3152031425991
2026-01-13 19:52:18,682 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,688 - INFO - rxn12940_c0> not needed:27.315203142599117
2026-01-13 19:52:18,690 - INFO - rxn12929_c0> not needed:27.3152031425991
2026-01-13 19:52:18,692 - INFO - rxn12938_c0> not needed:27.3152031425991
2026-01-13 19:52:18,694 - INFO - rxn12927_c0> not needed:27.315203142599117
2026-01-13 19:52:18,695 - INFO - rxn12921_c0> not needed:27.315203142599117
2026-01-13 19:52:18,699 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,701 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,703 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,705 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,709 - INFO - rxn11251_c0> not needed:27.315203142599085
2026-01-13 19:52:18,711 - INFO - rxn15166_c0> not needed:27.315203142599085
2026-01-13 19:52:18,717 - INFO - rxn19346_c0> not needed:27.315203142599117
2026-01-13 19:52:18,719 - INFO - rxn00644_c0> not needed:27.3152031425991
2026-01-13 19:52:18,721 - INFO - rxn19728_c0> not needed:27.315203142599117
2026-01-13 19:52:18,723 - INFO - rxn20235_c0> not needed:27.31520314259909
2026-01-13 19:52:18,728 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,730 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,731 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,740 - INFO - rxn15060_c0> not needed:27.315203142599117
2026-01-13 19:52:18,741 - INFO - rxn15064_c0> not needed:27.315203142599117
2026-01-13 19:52:18,743 - INFO - rxn15270_c0> not needed:27.315203142599117
2026-01-13 19:52:18,744 - INFO - rxn08154_c0> not needed:27.315203142599117
2026-01-13 19:52:18,745 - INFO - rxn20627_c0> not needed:27.315203142599117
2026-01-13 19:52:18,751 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:-2.246259907969145e-13 with min obj:0.01
2026-01-13 19:52:18,753 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:-4.339124089788146e-13 with min obj:0.01
2026-01-13 19:52:18,755 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:18,759 - INFO - Unneeded: [['rxn21635_c0', '>', 'new', 100, None], ['rxn16218_c0', '>', 'new', 100, None], ['rxn15949_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn15947_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn12938_c0', '>', 'new', 100, None], ['rxn12927_c0', '>', 'new', 100, None], ['rxn12921_c0', '>', 'new', 100, None], ['rxn11251_c0', '>', 'new', 100, None], ['rxn15166_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn00644_c0', '>', 'new', 100, None], ['rxn19728_c0', '>', 'new', 100, None], ['rxn20235_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn15270_c0', '>', 'new', 100, None], ['rxn08154_c0', '>', 'new', 100, None], ['rxn20627_c0', '>', 'new', 100, None]]
2026-01-13 19:52:18,780 - INFO - Growth: 27.315203142599117 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn10336_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn10213_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn04413_c0': '>', 'rxn00832_c0': '<', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn03137_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15166_c0': '>', 'rxn19346_c0': '>', 'rxn00644_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn08154_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:18,784 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:52:18,785 - INFO -     Added 46 reactions
2026-01-13 19:52:18,786 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:19,110 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:52:19,141 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:19,434 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 19:52:19,458 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:20,027 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:52:20,039 - INFO - cpd01024 not found in model!
2026-01-13 19:52:20,040 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:20,051 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:20,150 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:52:20,177 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:20,477 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:52:20,499 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:52:20,526 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn00499_c0': '<', 'rxn00250_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56fbfb80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:20,528 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:52:20,529 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:52:20,530 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:52:20,531 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:20,532 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:52:20,534 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:20,544 - INFO - Fum/rxn00062_c0:EX_cpd00159_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:20,545 - INFO - Fum/rxn00062_c0:rxn05602_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:20,546 - INFO - Fum/rxn00062_c0:rxn00499_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:20,548 - INFO - rxn00250_c0< not needed:0.25
2026-01-13 19:52:20,549 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:20,553 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56fbfb80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn00499_c0': '<'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:52:20,554 - INFO - Unneeded: [['rxn00250_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn00499_c0': '<', 'rxn00250_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56fbfb80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:20,557 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:20,576 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:21,008 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:52:21,039 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:21,260 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:52:21,283 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:22,874 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:52:22,906 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:52:22,933 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:25,629 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:52:25,652 - INFO - Objective with gapfill database:19.124999999999986; min objective:0.01
2026-01-13 19:52:25,682 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08556_c0': '>', 'rxn14422_c0': '>', 'rxn00250_c0': '<', 'rxn00172_c0': '<', 'rxn14421_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cf3d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:52:25,685 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:52:25,687 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:52:25,689 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:52:25,690 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:52:25,691 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:52:25,692 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:25,694 - INFO - integrating rxn: rxn08556_c0
2026-01-13 19:52:25,696 - INFO - integrating rxn: rxn14422_c0
2026-01-13 19:52:25,697 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:25,699 - INFO - integrating rxn: rxn00172_c0
2026-01-13 19:52:25,700 - INFO - integrating rxn: rxn14421_c0
2026-01-13 19:52:25,701 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:52:25,702 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new']]
2026-01-13 19:52:25,709 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:2
2026-01-13 19:52:25,710 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:52:25,711 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,712 - INFO - Glyc.O2/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,713 - INFO - Glyc.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,714 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,715 - INFO - Glyc.O2/rxn00062_c0:rxn08556_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,716 - INFO - Glyc.O2/rxn00062_c0:rxn14422_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,717 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,718 - INFO - Glyc.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,719 - INFO - Glyc.O2/rxn00062_c0:rxn14421_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,720 - INFO - Glyc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,726 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cf3d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08556_c0': '>', 'rxn14422_c0': '>', 'rxn00250_c0': '<', 'rxn00172_c0': '<', 'rxn14421_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:52:25,726 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08556_c0': '>', 'rxn14422_c0': '>', 'rxn00250_c0': '<', 'rxn00172_c0': '<', 'rxn14421_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cf3d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:52:25,729 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new']]
2026-01-13 19:52:25,751 - INFO - Objective with gapfill database:17.5; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:25,780 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn00250_c0': '<', 'rxn00172_c0': '<', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cc220>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:52:25,782 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:52:25,783 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:52:25,785 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:52:25,785 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:52:25,786 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:52:25,787 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:25,788 - INFO - integrating rxn: rxn14422_c0
2026-01-13 19:52:25,788 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:25,789 - INFO - integrating rxn: rxn00172_c0
2026-01-13 19:52:25,790 - INFO - integrating rxn: rxn14421_c0
2026-01-13 19:52:25,790 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:52:25,797 - INFO - Fum.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:3
2026-01-13 19:52:25,798 - INFO - Fum.O2/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:3
2026-01-13 19:52:25,799 - INFO - Fum.O2/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:3
2026-01-13 19:52:25,800 - INFO - Fum.O2/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:3
2026-01-13 19:52:25,801 - INFO - Fum.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:3
2026-01-13 19:52:25,802 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:52:25,803 - INFO - Fum.O2/rxn00062_c0:rxn14422_c0> needed:0.0 with min obj:3
2026-01-13 19:52:25,803 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:52:25,804 - INFO - Fum.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:3
2026-01-13 19:52:25,805 - INFO - Fum.O2/rxn00062_c0:rxn14421_c0> needed:0.0 with min obj:3
2026-01-13 19:52:25,810 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cc220>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn00250_c0': '<', 'rxn00172_c0': '<', 'rxn14421_c0': '>'}, 'reversed': {}}
2026-01-13 19:52:25,811 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn00250_c0': '<', 'rxn00172_c0': '<', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cc220>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:52:25,814 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new']]
2026-01-13 19:52:25,819 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:25,835 - INFO - Objective with gapfill database:19.125000000000004; min objective:0.01
2026-01-13 19:52:25,838 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:25,865 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00036_e0': '<', 'EX_cpd00029_e0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn00172_c0': '<', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cc4c0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:52:25,868 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:52:25,869 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:52:25,870 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:52:25,871 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:52:25,872 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:25,872 - INFO - integrating rxn: rxn14422_c0
2026-01-13 19:52:25,874 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:52:25,875 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:25,875 - INFO - integrating rxn: rxn00172_c0
2026-01-13 19:52:25,876 - INFO - integrating rxn: rxn14421_c0
2026-01-13 19:52:25,877 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:52:25,878 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:52:25,883 - INFO - Succ.O2/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:2
2026-01-13 19:52:25,884 - INFO - Succ.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:2
2026-01-13 19:52:25,886 - INFO - Succ.O2/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,887 - INFO - Succ.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,888 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,889 - INFO - Succ.O2/rxn00062_c0:rxn14422_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,890 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,891 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,892 - INFO - Succ.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,893 - INFO - Succ.O2/rxn00062_c0:rxn14421_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,898 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cc4c0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'EX_cpd00029_e0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn00172_c0': '<', 'rxn14421_c0': '>'}, 'reversed': {}}
2026-01-13 19:52:25,898 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00036_e0': '<', 'EX_cpd00029_e0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn00172_c0': '<', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cc4c0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:52:25,902 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:52:25,904 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:25,923 - INFO - Objective with gapfill database:16.249999999999986; min objective:0.01
2026-01-13 19:52:25,952 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn00499_c0': '>', 'rxn00172_c0': '<', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cc940>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:52:25,953 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:52:25,955 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:52:25,956 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:52:25,957 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:52:25,958 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:52:25,959 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:25,959 - INFO - integrating rxn: rxn14422_c0
2026-01-13 19:52:25,961 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:52:25,962 - INFO - integrating rxn: rxn00172_c0
2026-01-13 19:52:25,962 - INFO - integrating rxn: rxn14421_c0
2026-01-13 19:52:25,963 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:52:25,970 - INFO - LLac.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:2
2026-01-13 19:52:25,971 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:52:25,972 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,973 - INFO - LLac.O2/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,974 - INFO - LLac.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,974 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,975 - INFO - LLac.O2/rxn00062_c0:rxn14422_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,976 - INFO - LLac.O2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,977 - INFO - LLac.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:2
2026-01-13 19:52:25,978 - INFO - LLac.O2/rxn00062_c0:rxn14421_c0> needed:0.0 with min obj:2
2026-01-13 19:52:25,983 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cc940>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn00499_c0': '>', 'rxn00172_c0': '<', 'rxn14421_c0': '>'}, 'reversed': {}}
2026-01-13 19:52:25,984 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14422_c0': '>', 'rxn00499_c0': '>', 'rxn00172_c0': '<', 'rxn14421_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cc940>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:52:25,987 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:52:26,008 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:28,240 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 19:52:28,248 - INFO - cpd00187 not found in model!
2026-01-13 19:52:28,249 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:52:28,254 - INFO - cpd00187 not found in model!
2026-01-13 19:52:28,255 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:52:28,264 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:29,278 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:52:29,299 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:29,643 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:29,665 - INFO - Objective with gapfill database:3.5000000000000004; min objective:0.01
2026-01-13 19:52:29,693 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0b50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:29,695 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:52:29,697 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:52:29,699 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:52:29,700 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:52:29,704 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:52:29,707 - INFO - Glc/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:29,708 - INFO - Glc/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:29,710 - INFO - Glc/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:29,713 - INFO - cpd01024 not found in model!
2026-01-13 19:52:29,714 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:29,715 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0b50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:52:29,716 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f0b50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:29,719 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:52:29,725 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:29,740 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:29,819 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 19:52:29,828 - INFO - cpd00187 not found in model!
2026-01-13 19:52:29,829 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:52:29,834 - INFO - cpd00187 not found in model!
2026-01-13 19:52:29,835 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:52:29,844 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:30,191 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 19:52:30,215 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:30,660 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:52:30,688 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:31,441 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:31,452 - INFO - cpd11632 not found in model!
2026-01-13 19:52:31,453 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:52:31,466 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:31,496 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:52:31,523 - INFO - Objective with gapfill database:34.49999999999999; min objective:0.01
2026-01-13 19:52:31,553 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'rxn01975_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08173_c0': '>', 'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5ce67be0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:52:31,556 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:52:31,557 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:52:31,559 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:52:31,561 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:31,562 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:52:31,564 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:52:31,565 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:52:31,567 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:52:31,568 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:52:31,585 - INFO - Glc.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:5
2026-01-13 19:52:31,586 - INFO - Glc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:5
2026-01-13 19:52:31,587 - INFO - Glc.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:5
2026-01-13 19:52:31,588 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:5
2026-01-13 19:52:31,590 - INFO - Glc.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:5
2026-01-13 19:52:31,591 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:52:31,592 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:52:31,593 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:52:31,595 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5ce67be0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'rxn01975_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08173_c0': '>', 'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:52:31,596 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'rxn01975_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08173_c0': '>', 'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5ce67be0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:52:31,601 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:52:31,626 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:32,507 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:52:32,518 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:52:32,535 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:52:32,543 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:32,557 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:52:32,579 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:33,943 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:52:33,965 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:52:33,993 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56de2fb0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:33,995 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:52:33,996 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:33,997 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:52:33,999 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:52:34,000 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:34,002 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:52:34,003 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:52:34,004 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:52:34,004 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:34,005 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:52:34,009 - INFO - cpd00159 not found in model!
2026-01-13 19:52:34,009 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:52:34,013 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:52:34,014 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:34,015 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:34,016 - INFO - Llac/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:34,017 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:34,018 - INFO - Llac/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:34,019 - INFO - Llac/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:34,020 - INFO - Llac/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:34,021 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:34,025 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56de2fb0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:52:34,026 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56de2fb0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:34,029 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:52:34,047 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:34,159 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:52:34,188 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:34,400 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:52:34,421 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:34,507 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:52:34,528 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:34,690 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:52:34,721 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:34,892 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:52:34,928 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:35,781 - INFO - Objective with gapfill database:143.8231579611124; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:36,210 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:52:36,220 - INFO - cpd11632 not found in model!
2026-01-13 19:52:36,221 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:52:36,232 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:36,343 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:52:36,377 - INFO - Objective with gapfill database:0.7499999999999998; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:36,405 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:36,453 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:52:36,477 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:36,579 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:52:36,606 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:52:36,626 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:52:36,645 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:37,897 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:52:37,919 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:38,092 - INFO - Objective with gapfill database:143.8231579611124; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:38,251 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 19:52:38,270 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:38,421 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:52:38,450 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:38,721 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn10336_c0': '>', 'rxn08583_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn08618_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn21635_c0': '>', 'rxn22815_c0': '>', 'rxn20834_c0': '>', 'rxn17445_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15550_c0': '>', 'rxn14070_c0': '>', 'rxn15072_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn10095_c0': '>', 'rxn08154_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40203_c0': '>', 'rxn40292_c0': '>', 'rxn27266_c0': '>', 'rxn40040_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn11382_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:38,727 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:52:38,730 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:52:38,732 - INFO - integrating rxn: rxn09177_c0
2026-01-13 19:52:38,735 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:52:38,737 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:52:38,739 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:52:38,741 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:52:38,743 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:52:38,745 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:52:38,747 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:52:38,748 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:52:38,750 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:52:38,752 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:52:38,754 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:52:38,756 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:52:38,757 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:52:38,759 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:52:38,761 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:52:38,762 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:52:38,764 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:52:38,766 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:52:38,768 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:52:38,769 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:52:38,771 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:52:38,773 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:52:38,774 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:52:38,776 - INFO - integrating rxn: rxn22815_c0
2026-01-13 19:52:38,778 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:52:38,780 - INFO - integrating rxn: rxn17445_c0
2026-01-13 19:52:38,781 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:52:38,783 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:52:38,785 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:52:38,787 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:52:38,788 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:52:38,790 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:52:38,792 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:52:38,794 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:52:38,795 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:52:38,797 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:52:38,799 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:52:38,800 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:52:38,802 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:52:38,803 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:52:38,805 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:52:38,807 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:52:38,808 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:52:38,810 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:52:38,812 - INFO - integrating rxn: rxn01736_c0
2026-01-13 19:52:38,813 - INFO - integrating rxn: rxn00644_c0
2026-01-13 19:52:38,815 - INFO - integrating rxn: rxn19728_c0
2026-01-13 19:52:38,817 - INFO - integrating rxn: rxn20235_c0
2026-01-13 19:52:38,818 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:52:38,820 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:52:38,822 - INFO - integrating rxn: rxn15550_c0
2026-01-13 19:52:38,824 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:52:38,825 - INFO - integrating rxn: rxn15072_c0
2026-01-13 19:52:38,827 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:52:38,828 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:52:38,830 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:52:38,832 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:52:38,833 - INFO - integrating rxn: rxn08154_c0
2026-01-13 19:52:38,835 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:52:38,837 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:52:38,838 - INFO - integrating rxn: rxn40203_c0
2026-01-13 19:52:38,840 - INFO - integrating rxn: rxn40292_c0
2026-01-13 19:52:38,842 - INFO - integrating rxn: rxn27266_c0
2026-01-13 19:52:38,843 - INFO - integrating rxn: rxn40040_c0
2026-01-13 19:52:38,845 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:52:38,846 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:52:38,848 - INFO - integrating rxn: rxn11382_c0
2026-01-13 19:52:38,848 - INFO - Full solution: [['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn22815_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn17445_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn19728_c0', '>', 'new'], ['rxn20235_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn15550_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15072_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08154_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40203_c0', '>', 'new'], ['rxn40292_c0', '>', 'new'], ['rxn27266_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn11382_c0', '>', 'new']]
2026-01-13 19:52:38,930 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,933 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:1.8545940969726246e-11 with min obj:0.01
2026-01-13 19:52:38,936 - INFO - AuxoMedia/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,938 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,940 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,942 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,945 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,947 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,949 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,951 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,953 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,955 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,957 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,959 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,961 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,966 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:3.332783761016902e-12 with min obj:0.01
2026-01-13 19:52:38,968 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:38,970 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,972 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,974 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,976 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,979 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,982 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:-1.0644258867357755e-11 with min obj:0.01
2026-01-13 19:52:38,984 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,986 - INFO - AuxoMedia/bio1:rxn01603_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:38,993 - INFO - rxn21635_c0> not needed:27.315203142599113
2026-01-13 19:52:38,994 - INFO - rxn22815_c0> not needed:27.315203142599113
2026-01-13 19:52:38,996 - INFO - rxn20834_c0> not needed:27.315203142599113
2026-01-13 19:52:38,997 - INFO - rxn17445_c0> not needed:27.315203142599113
2026-01-13 19:52:39,001 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,004 - INFO - rxn12932_c0> not needed:27.315203142599085
2026-01-13 19:52:39,007 - INFO - rxn12940_c0> not needed:27.315203142599078
2026-01-13 19:52:39,008 - INFO - rxn12939_c0> not needed:27.315203142599106
2026-01-13 19:52:39,010 - INFO - rxn12929_c0> not needed:27.315203142599106
2026-01-13 19:52:39,011 - INFO - rxn25637_c0> not needed:27.315203142599106
2026-01-13 19:52:39,013 - INFO - rxn18935_c0> not needed:27.315203142599106
2026-01-13 19:52:39,014 - INFO - rxn25638_c0> not needed:27.315203142599106
2026-01-13 19:52:39,016 - INFO - rxn12928_c0> not needed:27.315203142599106
2026-01-13 19:52:39,017 - INFO - rxn12944_c0> not needed:27.315203142599106
2026-01-13 19:52:39,019 - INFO - rxn12994_c0> not needed:27.315203142599106
2026-01-13 19:52:39,023 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,028 - INFO - rxn12942_c0> not needed:27.31520314259912
2026-01-13 19:52:39,030 - INFO - rxn02485_c0> not needed:27.31520314259912
2026-01-13 19:52:39,035 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,037 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,039 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,043 - INFO - rxn19346_c0> not needed:27.315203142599124
2026-01-13 19:52:39,046 - INFO - rxn01736_c0> not needed:27.31520314259919
2026-01-13 19:52:39,047 - INFO - rxn00644_c0> not needed:27.315203142599096
2026-01-13 19:52:39,050 - INFO - rxn19728_c0> not needed:27.315203142599078
2026-01-13 19:52:39,051 - INFO - rxn20235_c0> not needed:27.315203142599053
2026-01-13 19:52:39,055 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,057 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,059 - INFO - rxn15550_c0> not needed:27.3152031425991
2026-01-13 19:52:39,063 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,069 - INFO - rxn15072_c0> not needed:27.31520314259911
2026-01-13 19:52:39,071 - INFO - rxn29919_c0> not needed:27.31520314259911
2026-01-13 19:52:39,073 - INFO - rxn15064_c0> not needed:27.31520314259911
2026-01-13 19:52:39,078 - INFO - AuxoMedia/bio1:rxn30685_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,084 - INFO - rxn10095_c0> not needed:27.31520314259911
2026-01-13 19:52:39,085 - INFO - rxn08154_c0> not needed:27.31520314259911
2026-01-13 19:52:39,087 - INFO - rxn15940_c0> not needed:27.31520314259911
2026-01-13 19:52:39,089 - INFO - rxn30917_c0> not needed:27.31520314259911
2026-01-13 19:52:39,091 - INFO - rxn40203_c0> not needed:27.31520314259911
2026-01-13 19:52:39,092 - INFO - rxn40292_c0> not needed:27.31520314259911
2026-01-13 19:52:39,094 - INFO - rxn27266_c0> not needed:27.31520314259911
2026-01-13 19:52:39,095 - INFO - rxn40040_c0> not needed:27.31520314259911
2026-01-13 19:52:39,100 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:39,105 - INFO - rxn08921_c0> not needed:27.315203142599117
2026-01-13 19:52:39,106 - INFO - rxn11382_c0> not needed:27.315203142599117
2026-01-13 19:52:39,111 - INFO - Unneeded: [['rxn21635_c0', '>', 'new', 100, None], ['rxn22815_c0', '>', 'new', 100, None], ['rxn20834_c0', '>', 'new', 100, None], ['rxn17445_c0', '>', 'new', 100, None], ['rxn12932_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12939_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn25637_c0', '>', 'new', 100, None], ['rxn18935_c0', '>', 'new', 100, None], ['rxn25638_c0', '>', 'new', 100, None], ['rxn12928_c0', '>', 'new', 100, None], ['rxn12944_c0', '>', 'new', 100, None], ['rxn12994_c0', '>', 'new', 100, None], ['rxn12942_c0', '>', 'new', 100, None], ['rxn02485_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn01736_c0', '>', 'new', 100, None], ['rxn00644_c0', '>', 'new', 100, None], ['rxn19728_c0', '>', 'new', 100, None], ['rxn20235_c0', '>', 'new', 100, None], ['rxn15550_c0', '>', 'new', 100, None], ['rxn15072_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn15064_c0', '>', 'new', 100, None], ['rxn10095_c0', '>', 'new', 100, None], ['rxn08154_c0', '>', 'new', 100, None], ['rxn15940_c0', '>', 'new', 100, None], ['rxn30917_c0', '>', 'new', 100, None], ['rxn40203_c0', '>', 'new', 100, None], ['rxn40292_c0', '>', 'new', 100, None], ['rxn27266_c0', '>', 'new', 100, None], ['rxn40040_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn11382_c0', '>', 'new', 100, None]]
2026-01-13 19:52:39,127 - INFO - Growth: 27.315203142599117 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn09177_c0': '>', 'rxn10336_c0': '>', 'rxn08583_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn03536_c0': '>', 'rxn08954_c0': '>', 'rxn08618_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn21635_c0': '>', 'rxn22815_c0': '>', 'rxn20834_c0': '>', 'rxn17445_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn01736_c0': '>', 'rxn00644_c0': '>', 'rxn19728_c0': '>', 'rxn20235_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15550_c0': '>', 'rxn14070_c0': '>', 'rxn15072_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn30685_c0': '>', 'rxn10095_c0': '>', 'rxn08154_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40203_c0': '>', 'rxn40292_c0': '>', 'rxn27266_c0': '>', 'rxn40040_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn11382_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:39,131 - INFO - Cumulative: [['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 19:52:39,132 - INFO -     Added 35 reactions
2026-01-13 19:52:39,132 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:40,230 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 19:52:40,249 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:40,572 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:52:40,607 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:40,716 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:52:40,739 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:41,277 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:52:41,304 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:41,443 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:52:41,466 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:52:41,496 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cd090>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:41,498 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:41,499 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:52:41,500 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:41,502 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:52:41,503 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:52:41,504 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:41,505 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:52:41,506 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:41,507 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:52:41,508 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:52:41,516 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:41,517 - INFO - rxn05938_c0< not needed:1.5
2026-01-13 19:52:41,518 - INFO - rxn07191_c0< not needed:1.5
2026-01-13 19:52:41,520 - INFO - Glc/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:41,521 - INFO - Glc/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:41,523 - INFO - rxn00250_c0< not needed:0.5
2026-01-13 19:52:41,524 - INFO - Glc/rxn00062_c0:rxn05226_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:41,525 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:41,527 - INFO - Glc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:41,532 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cd090>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:52:41,533 - INFO - Unneeded: [['rxn05938_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None], ['rxn00250_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cd090>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:41,537 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:52:41,559 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:41,991 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:52:42,013 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:42,170 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:52:42,191 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:42,251 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:52:42,277 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:42,346 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:52:42,357 - INFO - cpd00425 not found in model!
2026-01-13 19:52:42,358 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:52:42,369 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:42,499 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:52:42,510 - INFO - cpd00425 not found in model!
2026-01-13 19:52:42,511 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:52:42,520 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0
2026-01-13 19:52:42,521 - INFO - Objective with gapfill database:0.0; min objective:0.01

Removing ungapfillable media mal-L

2026-01-13 19:52:42,554 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:42,975 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:52:42,999 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:43,218 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:52:43,251 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:52:43,278 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:44,220 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:52:44,247 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:44,756 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:52:44,779 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:52:44,807 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f1210>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:44,810 - INFO - integrating rxn: EX_cpd00047_e0
2026-01-13 19:52:44,812 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:44,813 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:52:44,814 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:52:44,816 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:52:44,817 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:52:44,819 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:44,820 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:52:44,822 - INFO - integrating rxn: rxn00616_c0
2026-01-13 19:52:44,822 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:52:44,823 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:44,824 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new']]
2026-01-13 19:52:44,831 - INFO - Glyc/rxn00062_c0:EX_cpd00047_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:44,833 - INFO - Glyc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:44,834 - INFO - Glyc/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:0.01
2026-01-13 19:52:44,835 - INFO - Glyc/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:44,836 - INFO - Glyc/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:44,838 - INFO - Glyc/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:44,839 - INFO - Glyc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:44,841 - INFO - Glyc/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:44,842 - INFO - Glyc/rxn00062_c0:rxn00616_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:44,843 - INFO - Glyc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:44,844 - INFO - Glyc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:44,849 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f1210>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:52:44,850 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f1210>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:44,854 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new']]
2026-01-13 19:52:44,876 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:52:44,904 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f15a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:44,906 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:52:44,907 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:52:44,908 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:52:44,909 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:44,910 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:44,917 - INFO - Fum/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:0.01
2026-01-13 19:52:44,918 - INFO - Fum/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:44,920 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:44,921 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:44,926 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f15a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>'}, 'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}}
2026-01-13 19:52:44,927 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f15a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:44,932 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:44,952 - INFO - Objective with gapfill database:0.7499999999999993; min objective:0.01
2026-01-13 19:52:44,980 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00036_e0': '<', 'EX_cpd00363_e0': '>', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn09269_c0': '>', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f1570>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:44,982 - INFO - integrating rxn: EX_cpd00047_e0
2026-01-13 19:52:44,983 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:52:44,984 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:44,984 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:52:44,986 - INFO - integrating rxn: rxn00288_c0
2026-01-13 19:52:44,987 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:52:44,988 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:52:44,989 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:44,990 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:52:44,991 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:52:44,991 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:44,992 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:52:44,999 - INFO - Succ/rxn00062_c0:EX_cpd00047_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:45,001 - INFO - Succ/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:0.01
2026-01-13 19:52:45,002 - INFO - Succ/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:45,003 - INFO - Succ/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:45,004 - INFO - Succ/rxn00062_c0:rxn00288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:45,005 - INFO - Succ/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:45,006 - INFO - Succ/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:45,007 - INFO - Succ/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:45,008 - INFO - Succ/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:45,009 - INFO - Succ/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:45,010 - INFO - Succ/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:45,015 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f1570>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00036_e0': '<', 'EX_cpd00363_e0': '>', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn09269_c0': '>', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}}
2026-01-13 19:52:45,016 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00036_e0': '<', 'EX_cpd00363_e0': '>', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn09269_c0': '>', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f1570>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:45,020 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:52:45,041 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:52:45,069 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f18d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:45,071 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:45,072 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:45,073 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:45,074 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:52:45,081 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:45,083 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:45,084 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:45,089 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f18d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:52:45,090 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1f18d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:45,095 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:52:45,115 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:45,195 - WARNING - No gapfilling solution found before filtering for Succ activating rxn00062_c0

Removing ungapfillable media Succ

2026-01-13 19:52:45,228 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:52:45,255 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:46,014 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:52:46,042 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:52:46,066 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:52:46,090 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:46,275 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:52:46,309 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:46,802 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:52:46,822 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:47,331 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:52:47,350 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:48,063 - WARNING - No gapfilling solution found for Trimethylamine.H2 activating rxn00062_c0
2026-01-13 19:52:48,557 - INFO - Loading model: Gallicola.1
2026-01-13 19:52:48,741 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 19:52:49,069 - INFO -   Loading template...
2026-01-13 19:52:49,455 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:49,460 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:49,720 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:52:49,731 - INFO - cpd01024 not found in model!
2026-01-13 19:52:49,732 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:52:49,744 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:50,449 - WARNING - No gapfilling solution found for Trimethylamine.H2 activating rxn00062_c0
2026-01-13 19:52:50,950 - INFO - Loading model: Gordonia.1
2026-01-13 19:52:51,220 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:51,541 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:52:51,575 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:51,670 - INFO -   Loading template...
2026-01-13 19:52:52,058 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:52,064 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:52,443 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:52:52,464 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:53,031 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:52:53,041 - INFO - cpd11632 not found in model!
2026-01-13 19:52:53,042 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:52:53,053 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:53,921 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 19:52:53,944 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:52:53,972 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8d570>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:53,975 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:53,976 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:53,977 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:52:53,978 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:52:53,978 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:52:53,979 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:52:53,981 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:53,981 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:52:53,982 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:53,984 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:53,989 - INFO - cpd08021 not found in model!
2026-01-13 19:52:53,990 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:52:53,994 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:53,995 - INFO - Glc.DMSO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:53,996 - INFO - Glc.DMSO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:53,997 - INFO - Glc.DMSO/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:53,998 - INFO - Glc.DMSO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:53,999 - INFO - rxn00102_c0> not needed:2.5
2026-01-13 19:52:54,000 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:54,001 - INFO - Glc.DMSO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:54,003 - INFO - rxn00250_c0< not needed:2.5
2026-01-13 19:52:54,010 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8d570>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:52:54,010 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8d570>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:54,016 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:54,038 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:52:54,066 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8d2d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:52:54,069 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:52:54,069 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:54,070 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:52:54,071 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:52:54,072 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:52:54,073 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:52:54,074 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:52:54,075 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:52:54,075 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:54,076 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:54,082 - INFO - cpd00811 not found in model!
2026-01-13 19:52:54,082 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:52:54,085 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:52:54,087 - INFO - Glc.TMAO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:54,088 - INFO - Glc.TMAO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:54,089 - INFO - Glc.TMAO/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:54,090 - INFO - Glc.TMAO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:54,091 - INFO - rxn00102_c0> not needed:2.5
2026-01-13 19:52:54,092 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:52:54,093 - INFO - Glc.TMAO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:52:54,094 - INFO - rxn00250_c0< not needed:2.5
2026-01-13 19:52:54,100 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8d2d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:52:54,101 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8d2d0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:52:54,105 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:52:54,127 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:54,498 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:52:54,524 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:52:54,546 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:52:54,567 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:54,758 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:52:54,782 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:54,972 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:52:54,995 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:55,108 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:52:55,140 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:57,093 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:52:57,119 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:58,295 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:52:58,316 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:58,574 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:52:58,602 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:52:58,634 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn01975_c0': '>', 'rxn00324_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn01476_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn08656_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860d360>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:52:58,636 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:52:58,638 - INFO - integrating rxn: rxn00324_c0
2026-01-13 19:52:58,640 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:52:58,642 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:52:58,644 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:52:58,645 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:52:58,647 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:52:58,649 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:52:58,650 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:52:58,652 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:52:58,653 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:52:58,654 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:52:58,656 - INFO - integrating rxn: rxn08656_c0
2026-01-13 19:52:58,657 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:52:58,658 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:52:58,658 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:52:58,676 - INFO - Glc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:5
2026-01-13 19:52:58,678 - INFO - Glc.O2/rxn00062_c0:rxn00324_c0< needed:0.0 with min obj:5
2026-01-13 19:52:58,680 - INFO - Glc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:5
2026-01-13 19:52:58,681 - INFO - Glc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:5
2026-01-13 19:52:58,682 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:5
2026-01-13 19:52:58,683 - INFO - Glc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:5
2026-01-13 19:52:58,685 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:52:58,686 - INFO - rxn00102_c0> not needed:17.0
2026-01-13 19:52:58,687 - INFO - Glc.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:5
2026-01-13 19:52:58,688 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:52:58,689 - INFO - Glc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:5
2026-01-13 19:52:58,690 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:52:58,692 - INFO - Glc.O2/rxn00062_c0:rxn08656_c0> needed:0.0 with min obj:5
2026-01-13 19:52:58,693 - INFO - Glc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:5
2026-01-13 19:52:58,694 - INFO - rxn00250_c0< not needed:17.0
2026-01-13 19:52:58,697 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860d360>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn01975_c0': '>', 'rxn00324_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn01476_c0': '>', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn08656_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:52:58,697 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn01975_c0': '>', 'rxn00324_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn01476_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn08656_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860d360>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:52:58,701 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new']]
2026-01-13 19:52:58,726 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:58,922 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:52:58,954 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:52:58,984 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa29513f70>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:52:58,988 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:52:58,990 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:52:58,990 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['rxn00499_c0', '<', 'new']]
2026-01-13 19:52:59,012 - INFO - Glc.O2/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:5
2026-01-13 19:52:59,013 - INFO - rxn00499_c0< not needed:10.0
2026-01-13 19:52:59,016 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa29513f70>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn00083_c0': '>'}, 'reversed': {}}
2026-01-13 19:52:59,017 - INFO - Unneeded: [['rxn00499_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa29513f70>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:52:59,021 - INFO - Cumulative: [['rxn00083_c0', '>', 'new']]
2026-01-13 19:52:59,044 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:52:59,216 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:52:59,240 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:52:59,242 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:52:59,271 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:00,280 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:53:00,293 - INFO - cpd11632 not found in model!
2026-01-13 19:53:00,294 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:53:00,307 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:00,427 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:53:00,446 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:53:00,723 - INFO - Objective with gapfill database:116.82557499858837; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:02,159 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:53:02,188 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:53:03,028 - INFO - Objective with gapfill database:116.82557499858837; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:03,284 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:53:03,313 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:03,497 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:53:03,507 - INFO - cpd00425 not found in model!
2026-01-13 19:53:03,508 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:53:03,519 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:53:03,603 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn03436_c0': '>', 'rxn02835_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn22816_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn22817_c0': '>', 'rxn48543_c0': '>', 'rxn20834_c0': '>', 'rxn11274_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25638_c0': '>', 'rxn47267_c0': '>', 'rxn41387_c0': '>', 'rxn11162_c0': '>', 'rxn01736_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn29919_c0': '>', 'rxn41185_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn16341_c0': '>', 'rxn46249_c0': '>', 'rxn27266_c0': '>', 'rxn40040_c0': '>', 'rxn08921_c0': '>', 'rxn08989_c0': '>', 'rxn47493_c0': '>', 'rxn08473_c0': '>', 'rxn09390_c0': '>', 'rxn20567_c0': '>', 'rxn23676_c0': '>', 'rxn15776_c0': '>', 'rxn14050_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:53:03,611 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:53:03,613 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:53:03,616 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:53:03,618 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:53:03,621 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:53:03,622 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:53:03,625 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:53:03,627 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:53:03,629 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:53:03,631 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:53:03,633 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:53:03,635 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:53:03,636 - INFO - integrating rxn: rxn48543_c0
2026-01-13 19:53:03,638 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:53:03,640 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:53:03,642 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:53:03,644 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:53:03,646 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:53:03,648 - INFO - integrating rxn: rxn47267_c0
2026-01-13 19:53:03,650 - INFO - integrating rxn: rxn41387_c0
2026-01-13 19:53:03,652 - INFO - integrating rxn: rxn11162_c0
2026-01-13 19:53:03,653 - INFO - integrating rxn: rxn01736_c0
2026-01-13 19:53:03,655 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:53:03,657 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:53:03,659 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:53:03,661 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:53:03,662 - INFO - integrating rxn: rxn41185_c0
2026-01-13 19:53:03,664 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:53:03,666 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:53:03,668 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:53:03,669 - INFO - integrating rxn: rxn46249_c0
2026-01-13 19:53:03,671 - INFO - integrating rxn: rxn27266_c0
2026-01-13 19:53:03,673 - INFO - integrating rxn: rxn40040_c0
2026-01-13 19:53:03,675 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:53:03,677 - INFO - integrating rxn: rxn08989_c0
2026-01-13 19:53:03,678 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:53:03,680 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:53:03,681 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:53:03,683 - INFO - integrating rxn: rxn20567_c0
2026-01-13 19:53:03,685 - INFO - integrating rxn: rxn23676_c0
2026-01-13 19:53:03,686 - INFO - integrating rxn: rxn15776_c0
2026-01-13 19:53:03,688 - INFO - integrating rxn: rxn14050_c0
2026-01-13 19:53:03,689 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn09177_c0', 'rxn10336_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn10213_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08618_c0', 'rxn03537_c0', 'rxn03916_c0', 'rxn05463_c0', 'rxn04413_c0', 'rxn00832_c0', 'rxn03087_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn03137_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn48543_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn47267_c0', '>', 'new'], ['rxn41387_c0', '>', 'new'], ['rxn11162_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn41185_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn27266_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn08989_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn20567_c0', '>', 'new'], ['rxn23676_c0', '>', 'new'], ['rxn15776_c0', '>', 'new'], ['rxn14050_c0', '>', 'new']]
2026-01-13 19:53:03,724 - INFO - EX_cpd00393_e0< not needed:18.239261817534107
2026-01-13 19:53:03,728 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:53:03,730 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,732 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:-7.652379799020164e-13 with min obj:0.01
2026-01-13 19:53:03,735 - INFO - PyruateMinimalAnaerobic/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,737 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,739 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,741 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,743 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,745 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,747 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,750 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,752 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,754 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,756 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,759 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,761 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,763 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,765 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,767 - INFO - PyruateMinimalAnaerobic/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,769 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,773 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:2.4443767469796686e-12 with min obj:0.01
2026-01-13 19:53:03,775 - INFO - PyruateMinimalAnaerobic/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 19:53:03,777 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,779 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,781 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,783 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:53:03,785 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,787 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,789 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,791 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,793 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,800 - INFO - rxn05255_c0> not needed:18.239261817533894
2026-01-13 19:53:03,804 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,806 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,808 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,811 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,813 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,815 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,818 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,820 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,822 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,824 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,828 - INFO - PyruateMinimalAnaerobic/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,830 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,832 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:53:03,833 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:53:03,834 - INFO -   Running ATP safety check...

c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:04,606 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:53:04,635 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:53:04,657 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:53:04,679 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:04,858 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:53:04,885 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:05,590 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:53:05,613 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:05,791 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 19:53:05,814 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:07,651 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 19:53:07,676 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:53:07,692 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:53:07,713 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:08,459 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:53:08,488 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:53:08,519 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn08901_c0': '>', 'rxn08094_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2aa333d0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:53:08,522 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:53:08,524 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:08,526 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:53:08,528 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:08,529 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:53:08,531 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:53:08,533 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:53:08,535 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:53:08,537 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:53:08,538 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:53:08,540 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:53:08,541 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:08,543 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new']]
2026-01-13 19:53:08,561 - INFO - Glc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:5
2026-01-13 19:53:08,563 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:5
2026-01-13 19:53:08,564 - INFO - Glc.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:5
2026-01-13 19:53:08,565 - INFO - Glc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:5
2026-01-13 19:53:08,567 - INFO - Glc.O2/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:5
2026-01-13 19:53:08,568 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:53:08,569 - INFO - Glc.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:5
2026-01-13 19:53:08,571 - INFO - Glc.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:5
2026-01-13 19:53:08,572 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:53:08,574 - INFO - Glc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:5
2026-01-13 19:53:08,575 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:53:08,576 - INFO - Glc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:5
2026-01-13 19:53:08,579 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2aa333d0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn08901_c0': '>', 'rxn08094_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:53:08,580 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn08901_c0': '>', 'rxn08094_c0': '>', 'rxn03884_c0': '>', 'rxn08971_c0': '>', 'rxn01477_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2aa333d0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:53:08,584 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new']]
2026-01-13 19:53:08,610 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:09,412 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:53:09,442 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:11,252 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:53:11,266 - INFO - cpd01024 not found in model!
2026-01-13 19:53:11,267 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:53:11,281 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:14,824 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:53:14,850 - INFO - Objective with gapfill database:19.124999999999986; min objective:0.01
2026-01-13 19:53:14,880 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860dcf0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:53:14,882 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:53:14,883 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:53:14,884 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:14,886 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:53:14,887 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:14,889 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:53:14,890 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:53:14,891 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:53:14,893 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:53:14,893 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:14,894 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:53:14,895 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:53:14,904 - INFO - Glyc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:53:14,906 - INFO - Glyc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:53:14,907 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:53:14,908 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:53:14,909 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:53:14,910 - INFO - rxn00102_c0> not needed:9.0
2026-01-13 19:53:14,911 - INFO - Glyc.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:53:14,913 - INFO - Glyc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:53:14,914 - INFO - Glyc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:2
2026-01-13 19:53:14,915 - INFO - Glyc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:53:14,916 - INFO - rxn00250_c0< not needed:9.0
2026-01-13 19:53:14,924 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860dcf0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:53:14,924 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860dcf0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:53:14,928 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:53:14,952 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:53:14,982 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860df90>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:53:14,983 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:53:14,984 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:53:14,985 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:14,986 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:14,987 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:53:14,988 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:53:14,989 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:53:14,990 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:14,991 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:53:14,992 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:53:15,000 - INFO - Fum.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:3
2026-01-13 19:53:15,002 - INFO - Fum.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,003 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,004 - INFO - Fum.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,006 - INFO - rxn00102_c0> not needed:8.25
2026-01-13 19:53:15,007 - INFO - Fum.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:3
2026-01-13 19:53:15,008 - INFO - Fum.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:3
2026-01-13 19:53:15,009 - INFO - Fum.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,011 - INFO - rxn00250_c0< not needed:8.25
2026-01-13 19:53:15,018 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860df90>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:53:15,018 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860df90>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:53:15,022 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:53:15,045 - INFO - Objective with gapfill database:19.125000000000004; min objective:0.01
2026-01-13 19:53:15,074 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860e230>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:53:15,076 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:53:15,077 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:53:15,077 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:15,078 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:15,080 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:53:15,081 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:53:15,082 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:53:15,083 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:53:15,083 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:15,084 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:53:15,085 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:53:15,093 - INFO - Succ.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,094 - INFO - Succ.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,095 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,097 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,098 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,099 - INFO - rxn00102_c0> not needed:9.0
2026-01-13 19:53:15,100 - INFO - Succ.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,101 - INFO - Succ.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,103 - INFO - Succ.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,104 - INFO - rxn00250_c0< not needed:9.0
2026-01-13 19:53:15,111 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860e230>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:53:15,112 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860e230>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:53:15,115 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:53:15,139 - INFO - Objective with gapfill database:16.250000000000018; min objective:0.01
2026-01-13 19:53:15,169 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860e6b0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:53:15,171 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:53:15,172 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:53:15,174 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:53:15,175 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:53:15,176 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:15,178 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:15,179 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:53:15,180 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:53:15,181 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:53:15,182 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:15,184 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:53:15,185 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:53:15,193 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:53:15,194 - INFO - LLac.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,196 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,197 - INFO - LLac.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,198 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,199 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,200 - INFO - LLac.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,201 - INFO - LLac.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,202 - INFO - LLac.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,203 - INFO - LLac.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,204 - INFO - LLac.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,211 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860e6b0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:53:15,212 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00102_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860e6b0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:53:15,214 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:53:15,239 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:15,342 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:53:15,366 - INFO - Objective with gapfill database:19.124999999999986; min objective:0.01
2026-01-13 19:53:15,395 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00083_c0': '>', 'rxn00505_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f1780>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:53:15,398 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:53:15,400 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:53:15,402 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:15,403 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:53:15,405 - INFO - integrating rxn: rxn00615_c0
2026-01-13 19:53:15,407 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:15,408 - INFO - integrating rxn: rxn05939_c0
2026-01-13 19:53:15,409 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:53:15,411 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:53:15,412 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:53:15,414 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:53:15,415 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:15,416 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:53:15,417 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed']]
2026-01-13 19:53:15,424 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:53:15,425 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,426 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,427 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,428 - INFO - Glyc.O2/rxn00062_c0:rxn00615_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,429 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,430 - INFO - Glyc.O2/rxn00062_c0:rxn05939_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,431 - INFO - Glyc.O2/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,432 - INFO - Glyc.O2/rxn00062_c0:rxn00505_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,433 - INFO - Glyc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,434 - INFO - Glyc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,434 - INFO - Glyc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,435 - INFO - Glyc.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,441 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f1780>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00083_c0': '>', 'rxn00505_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:53:15,442 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00083_c0': '>', 'rxn00505_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f1780>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:53:15,446 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed']]
2026-01-13 19:53:15,469 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:53:15,498 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00324_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f0220>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:53:15,500 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:53:15,501 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:53:15,503 - INFO - integrating rxn: rxn00324_c0
2026-01-13 19:53:15,504 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:15,505 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:15,506 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:53:15,507 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:15,508 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:53:15,509 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:53:15,510 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:53:15,518 - INFO - Fum.O2/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:3
2026-01-13 19:53:15,519 - INFO - Fum.O2/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:3
2026-01-13 19:53:15,520 - INFO - Fum.O2/rxn00062_c0:rxn00324_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,521 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,522 - INFO - Fum.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,523 - INFO - Fum.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:3
2026-01-13 19:53:15,524 - INFO - Fum.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,525 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,526 - INFO - Fum.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:3
2026-01-13 19:53:15,532 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f0220>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00324_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}}
2026-01-13 19:53:15,532 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'rxn05561_c0': '>', 'rxn00324_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f0220>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:53:15,536 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:53:15,558 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:53:15,587 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00505_c0': '>', 'rxn09269_c0': '>', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f04c0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:53:15,589 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:53:15,590 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:15,591 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:15,592 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:53:15,593 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:53:15,594 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:53:15,595 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:15,596 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:53:15,597 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:53:15,598 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:53:15,612 - INFO - Succ.O2/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:2
2026-01-13 19:53:15,613 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,614 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,616 - INFO - Succ.O2/rxn00062_c0:rxn00505_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,617 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,618 - INFO - Succ.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,619 - INFO - Succ.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,620 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,621 - INFO - Succ.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,627 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f04c0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00505_c0': '>', 'rxn09269_c0': '>', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}}
2026-01-13 19:53:15,628 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn00285_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00505_c0': '>', 'rxn09269_c0': '>', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f04c0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:53:15,631 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:53:15,653 - INFO - Objective with gapfill database:16.249999999999993; min objective:0.01
2026-01-13 19:53:15,681 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00505_c0': '>', 'rxn00499_c0': '>', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f0880>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:53:15,682 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:15,683 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:15,684 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:53:15,685 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:53:15,686 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:53:15,687 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:15,688 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:53:15,688 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:53:15,696 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,697 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,698 - INFO - LLac.O2/rxn00062_c0:rxn00505_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,699 - INFO - LLac.O2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,700 - INFO - LLac.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:2
2026-01-13 19:53:15,701 - INFO - LLac.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,702 - INFO - LLac.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:53:15,708 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f0880>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00505_c0': '>', 'rxn00499_c0': '>', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:53:15,709 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00505_c0': '>', 'rxn00499_c0': '>', 'rxn08094_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f0880>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:53:15,712 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:53:15,734 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:17,797 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:53:17,828 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:17,894 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:53:17,919 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:18,388 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:53:18,410 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:21,459 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:53:21,485 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:23,992 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:53:24,017 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:24,335 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:53:24,361 - INFO - Objective with gapfill database:19.124999999999993; min objective:0.01
2026-01-13 19:53:24,391 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00505_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a625930>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:53:24,393 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:24,394 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:53:24,396 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:53:24,397 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:24,399 - INFO - integrating rxn: rxn05939_c0
2026-01-13 19:53:24,401 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:53:24,403 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:53:24,404 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:53:24,405 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:53:24,407 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:53:24,408 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:24,409 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:53:24,418 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,420 - INFO - Glyc.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,421 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,422 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,423 - INFO - Glyc.O2/rxn00062_c0:rxn05939_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,425 - INFO - Glyc.O2/rxn00062_c0:rxn00505_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,426 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,427 - INFO - Glyc.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,428 - INFO - Glyc.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,430 - INFO - Glyc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,431 - INFO - Glyc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,438 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a625930>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00505_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:53:24,439 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08557_c0': '>', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00505_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00251_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a625930>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:53:24,443 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:53:24,468 - INFO - Objective with gapfill database:17.499999999999996; min objective:0.01
2026-01-13 19:53:24,497 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn00505_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08094_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a6241c0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:53:24,499 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:24,500 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:53:24,501 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:24,502 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:53:24,503 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:53:24,504 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:53:24,506 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:53:24,506 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:53:24,507 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:24,509 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:53:24,518 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:53:24,519 - INFO - Fum.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:3
2026-01-13 19:53:24,521 - INFO - Fum.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:3
2026-01-13 19:53:24,522 - INFO - Fum.O2/rxn00062_c0:rxn00505_c0> needed:0.0 with min obj:3
2026-01-13 19:53:24,523 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:53:24,525 - INFO - Fum.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:3
2026-01-13 19:53:24,526 - INFO - Fum.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:3
2026-01-13 19:53:24,527 - INFO - Fum.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:3
2026-01-13 19:53:24,529 - INFO - Fum.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:3
2026-01-13 19:53:24,535 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a6241c0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn00505_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08094_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:53:24,536 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn00505_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08094_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a6241c0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:53:24,541 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:53:24,566 - INFO - Objective with gapfill database:19.125; min objective:0.01
2026-01-13 19:53:24,594 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00505_c0': '>', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a624280>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:53:24,596 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:24,597 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:53:24,598 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:24,600 - INFO - integrating rxn: rxn05939_c0
2026-01-13 19:53:24,601 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:53:24,603 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:53:24,604 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:53:24,605 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:53:24,605 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:53:24,607 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:24,608 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:53:24,617 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,618 - INFO - Succ.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,620 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,621 - INFO - Succ.O2/rxn00062_c0:rxn05939_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,622 - INFO - Succ.O2/rxn00062_c0:rxn00505_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,623 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,624 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,625 - INFO - Succ.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,626 - INFO - Succ.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,627 - INFO - Succ.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,634 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a624280>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00505_c0': '>', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:53:24,635 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00505_c0': '>', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a624280>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:53:24,637 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:53:24,661 - INFO - Objective with gapfill database:16.249999999999993; min objective:0.01
2026-01-13 19:53:24,689 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00505_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a6248e0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:53:24,691 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:53:24,693 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:53:24,693 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:53:24,694 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:53:24,695 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:53:24,696 - INFO - integrating rxn: rxn05939_c0
2026-01-13 19:53:24,696 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:53:24,697 - INFO - integrating rxn: rxn08901_c0
2026-01-13 19:53:24,698 - INFO - integrating rxn: rxn08971_c0
2026-01-13 19:53:24,699 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:53:24,700 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 19:53:24,708 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:53:24,709 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,710 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,711 - INFO - LLac.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,712 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,713 - INFO - LLac.O2/rxn00062_c0:rxn05939_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,714 - INFO - LLac.O2/rxn00062_c0:rxn00505_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,715 - INFO - LLac.O2/rxn00062_c0:rxn08901_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,716 - INFO - LLac.O2/rxn00062_c0:rxn08971_c0> needed:0.0 with min obj:2
2026-01-13 19:53:24,717 - INFO - LLac.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:53:24,723 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a6248e0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00505_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:53:24,724 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn05939_c0': '<', 'rxn00505_c0': '>', 'rxn08901_c0': '>', 'rxn08971_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a6248e0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:53:24,727 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 19:53:24,750 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:26,708 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:53:26,740 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:27,741 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:53:27,766 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:29,073 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:53:29,100 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:31,302 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:53:31,331 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:37,724 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:53:37,753 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:41,317 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:53:41,344 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:48,890 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:53:48,918 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:53:50,800 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:53:50,824 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:54:46,522 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:54:46,550 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:54:46,578 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3b670>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:54:46,580 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:54:46,581 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:54:46,582 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:54:46,584 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:54:46,584 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:54:46,585 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:54:46,597 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:54:46,598 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:54:46,599 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:54:46,600 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:54:46,601 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:54:46,606 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3b670>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:54:46,606 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42c3b670>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:54:46,609 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:54:46,629 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:01,107 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:55:01,129 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:15,514 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:55:15,535 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:25,734 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:55:25,759 - INFO - Objective with gapfill database:19.124999999999993; min objective:0.01
2026-01-13 19:55:25,789 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00148_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c825570>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:55:25,792 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:55:25,794 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:55:25,795 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:55:25,796 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:55:25,798 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:55:25,799 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:55:25,800 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:55:25,802 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:55:25,803 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:55:25,804 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:55:25,806 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:55:25,806 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:55:25,807 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:55:25,816 - INFO - Glyc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:55:25,817 - INFO - Glyc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:55:25,818 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:55:25,819 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:55:25,820 - INFO - Glyc.O2/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:2
2026-01-13 19:55:25,821 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:55:25,822 - INFO - Glyc.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:2
2026-01-13 19:55:25,823 - INFO - Glyc.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:2
2026-01-13 19:55:25,824 - INFO - rxn00102_c0> not needed:10.0
2026-01-13 19:55:25,825 - INFO - Glyc.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:2
2026-01-13 19:55:25,826 - INFO - Glyc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:55:25,827 - INFO - rxn00250_c0< not needed:10.0
2026-01-13 19:55:25,834 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c825570>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00148_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:55:25,835 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08557_c0': '>', 'rxn00148_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c825570>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:55:25,838 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new']]
2026-01-13 19:55:25,861 - INFO - Objective with gapfill database:17.499999999999996; min objective:0.01
2026-01-13 19:55:25,891 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c824160>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:55:25,892 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:55:25,893 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:55:25,894 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:55:25,895 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:55:25,895 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:55:25,897 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:55:25,898 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:55:25,899 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:55:25,900 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:55:25,908 - INFO - Fum.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:3
2026-01-13 19:55:25,909 - INFO - Fum.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:3
2026-01-13 19:55:25,911 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:55:25,912 - INFO - Fum.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:3
2026-01-13 19:55:25,914 - INFO - rxn00248_c0> not needed:4.25
2026-01-13 19:55:25,914 - INFO - rxn00102_c0> not needed:4.25
2026-01-13 19:55:25,916 - INFO - Fum.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:3
2026-01-13 19:55:25,917 - INFO - rxn00250_c0< not needed:4.25
2026-01-13 19:55:25,923 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c824160>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08173_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:55:25,924 - INFO - Unneeded: [['rxn00248_c0', '>', 'new', 100, None], ['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c824160>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:55:25,927 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new']]
2026-01-13 19:55:25,950 - INFO - Objective with gapfill database:19.125000000000004; min objective:0.01
2026-01-13 19:55:25,979 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c824370>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:55:25,981 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:55:25,982 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:55:25,983 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:55:25,984 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:55:25,985 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:55:25,986 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:55:25,988 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:55:25,989 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:55:25,990 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:55:25,991 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:55:25,992 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:55:25,993 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:55:26,001 - INFO - Succ.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,002 - INFO - Succ.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:55:26,003 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:55:26,010 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:55:26,012 - INFO - Succ.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,013 - INFO - Succ.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,014 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,015 - INFO - rxn00102_c0> not needed:9.0
2026-01-13 19:55:26,016 - INFO - Succ.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,018 - INFO - Succ.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:55:26,019 - INFO - rxn00250_c0< not needed:9.0
2026-01-13 19:55:26,026 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c824370>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {}}
2026-01-13 19:55:26,027 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c824370>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:55:26,031 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:55:26,055 - INFO - Objective with gapfill database:16.249999999999993; min objective:0.01
2026-01-13 19:55:26,084 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c8247c0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:55:26,087 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:55:26,088 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:55:26,089 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:55:26,090 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:55:26,091 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:55:26,092 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:55:26,092 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:55:26,093 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:55:26,095 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:55:26,095 - INFO - integrating rxn: rxn00973_c0
2026-01-13 19:55:26,096 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:55:26,097 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:55:26,098 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:55:26,106 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:55:26,107 - INFO - LLac.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,108 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,109 - INFO - LLac.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:55:26,110 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:55:26,111 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:55:26,112 - INFO - LLac.O2/rxn00062_c0:rxn08173_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,113 - INFO - LLac.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,114 - INFO - LLac.O2/rxn00062_c0:rxn00102_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,115 - INFO - LLac.O2/rxn00062_c0:rxn00973_c0> needed:0.0 with min obj:2
2026-01-13 19:55:26,116 - INFO - LLac.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:55:26,117 - INFO - LLac.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:55:26,123 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c8247c0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:55:26,124 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '<', 'rxn00336_c0': '>', 'rxn05602_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn08173_c0': '>', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn00973_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c8247c0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:55:26,128 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:55:26,151 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:28,550 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:55:28,561 - INFO - cpd00425 not found in model!
2026-01-13 19:55:28,562 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:55:28,573 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:30,003 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:55:30,025 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:33,352 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:55:33,376 - INFO - Objective with gapfill database:0.7499999999999994; min objective:0.01
2026-01-13 19:55:33,405 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00543_c0': '<', 'rxn00935_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cd870>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:55:33,408 - INFO - integrating rxn: EX_cpd00047_e0
2026-01-13 19:55:33,410 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:55:33,411 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:55:33,412 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:55:33,413 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:55:33,414 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:55:33,415 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:55:33,416 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:55:33,417 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:55:33,418 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:55:33,419 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:55:33,420 - INFO - integrating rxn: rxn00616_c0
2026-01-13 19:55:33,421 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:55:33,422 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new']]
2026-01-13 19:55:33,430 - INFO - Glyc/rxn00062_c0:EX_cpd00047_e0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,431 - INFO - Glyc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,432 - INFO - Glyc/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,433 - INFO - Glyc/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,434 - INFO - Glyc/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,435 - INFO - Glyc/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,436 - INFO - Glyc/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,437 - INFO - Glyc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,437 - INFO - Glyc/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,438 - INFO - Glyc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,439 - INFO - Glyc/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,440 - INFO - Glyc/rxn00062_c0:rxn00616_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,441 - INFO - Glyc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,447 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cd870>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00543_c0': '<', 'rxn00935_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:55:33,447 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00543_c0': '<', 'rxn00935_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cd870>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:55:33,450 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new']]
2026-01-13 19:55:33,473 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:55:33,502 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cda20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:55:33,504 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:55:33,506 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:55:33,507 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:55:33,507 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:55:33,508 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:55:33,509 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:55:33,510 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:55:33,510 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:55:33,511 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:55:33,512 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:55:33,513 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:55:33,520 - INFO - Fum/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,522 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,523 - INFO - Fum/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,524 - INFO - Fum/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,525 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,526 - INFO - Fum/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,527 - INFO - Fum/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,528 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,529 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,530 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,535 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cda20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:55:33,536 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cda20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:55:33,539 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:55:33,559 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:55:33,588 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00036_e0': '<', 'EX_cpd00363_e0': '>', 'rxn00543_c0': '<', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn00171_c0': '<', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cdc60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:55:33,590 - INFO - integrating rxn: EX_cpd00047_e0
2026-01-13 19:55:33,591 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:55:33,592 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:55:33,592 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:55:33,593 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:55:33,595 - INFO - integrating rxn: rxn00288_c0
2026-01-13 19:55:33,596 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:55:33,596 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:55:33,597 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:55:33,598 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:55:33,599 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:55:33,600 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:55:33,600 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:55:33,601 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:55:33,607 - INFO - Succ/rxn00062_c0:EX_cpd00047_e0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,609 - INFO - Succ/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,610 - INFO - Succ/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,611 - INFO - Succ/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,612 - INFO - Succ/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,613 - INFO - Succ/rxn00062_c0:rxn00288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,614 - INFO - Succ/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,615 - INFO - Succ/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,615 - INFO - Succ/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,616 - INFO - Succ/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,618 - INFO - Succ/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,619 - INFO - Succ/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,620 - INFO - Succ/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,625 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cdc60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00036_e0': '<', 'EX_cpd00363_e0': '>', 'rxn00543_c0': '<', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn00171_c0': '<', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:55:33,626 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00036_e0': '<', 'EX_cpd00363_e0': '>', 'rxn00543_c0': '<', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn00171_c0': '<', 'rxn09269_c0': '>', 'rxn00250_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324cdc60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:55:33,629 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:55:33,649 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:55:33,678 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324ce050>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:55:33,680 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:55:33,681 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:55:33,682 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:55:33,683 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:55:33,684 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:55:33,684 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:55:33,685 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:55:33,686 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:55:33,687 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:55:33,688 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:55:33,694 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,696 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,696 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,698 - INFO - Llac/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,699 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,700 - INFO - Llac/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,701 - INFO - Llac/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:33,701 - INFO - Llac/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,702 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:33,708 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324ce050>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:55:33,708 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324ce050>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:55:33,711 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:55:33,732 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:33,870 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:55:33,897 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:36,940 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:55:36,951 - INFO - cpd01024 not found in model!
2026-01-13 19:55:36,952 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:55:36,964 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:42,812 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:55:42,837 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:55:42,867 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c824e50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:55:42,870 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:55:42,871 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:55:42,872 - INFO - integrating rxn: rxn00148_c0
2026-01-13 19:55:42,874 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:55:42,875 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:55:42,876 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:55:42,884 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:55:42,886 - INFO - Glc/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:42,887 - INFO - Glc/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:42,888 - INFO - Glc/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:55:42,889 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:55:42,895 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c824e50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:55:42,896 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c824e50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:55:42,899 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:55:42,921 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:44,252 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 19:55:44,273 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:44,529 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:55:44,557 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:46,162 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:55:46,187 - INFO - Objective with gapfill database:34.5; min objective:0.01
2026-01-13 19:55:46,217 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0df9ace0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:55:46,220 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:55:46,221 - INFO - Full solution: [['rxn01476_c0', '>', 'new']]
2026-01-13 19:55:46,238 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:55:46,240 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0df9ace0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn01476_c0': '>'}, 'reversed': {}}
2026-01-13 19:55:46,241 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0df9ace0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:55:46,244 - INFO - Cumulative: [['rxn01476_c0', '>', 'new']]
2026-01-13 19:55:46,265 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:47,852 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:55:47,889 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:55:47,912 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01
2026-01-13 19:55:47,934 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:48,803 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:55:48,824 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:48,967 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:55:48,988 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:50,454 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:55:50,482 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:51,529 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:55:51,560 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:53,028 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:55:53,061 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:54,592 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:55:54,627 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:56,607 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:55:56,636 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:55:56,645 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:55:56,665 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:57,921 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:55:57,941 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:58,613 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:55:58,635 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:55:59,175 - INFO - Objective with gapfill database:137.21706849317314; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:59,603 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:55:59,628 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:55:59,697 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:55:59,711 - INFO - cpd01024 not found in model!
2026-01-13 19:55:59,712 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:55:59,726 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:00,898 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:56:00,933 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:01,671 - INFO - Objective with gapfill database:137.21706849317314; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:02,232 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn01974_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn00383_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn00178_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01454_c0': '<', 'rxn01501_c0': '<', 'rxn01505_c0': '>', 'rxn01256_c0': '>', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn10124_c0': '<', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00069_c0': '>', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03917_c0': '>', 'rxn00726_c0': '>', 'rxn00440_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn02303_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn00599_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00141_c0': '>', 'rxn00130_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03130_c0': '>', 'rxn00623_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05177_c0': '>', 'rxn00117_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn21859_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn08233_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn47875_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:02,237 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 19:56:02,238 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 19:56:02,240 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:56:02,241 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:56:02,243 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:56:02,244 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:56:02,246 - INFO - integrating rxn: EX_cpd00149_e0
2026-01-13 19:56:02,247 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:56:02,249 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 19:56:02,251 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:56:02,252 - INFO - integrating rxn: rxn03086_c0
2026-01-13 19:56:02,254 - INFO - integrating rxn: rxn08333_c0
2026-01-13 19:56:02,256 - INFO - integrating rxn: rxn02898_c0
2026-01-13 19:56:02,257 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:56:02,258 - INFO - integrating rxn: rxn03030_c0
2026-01-13 19:56:02,260 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:56:02,261 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:56:02,262 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:56:02,264 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:56:02,266 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:56:02,267 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:56:02,268 - INFO - integrating rxn: rxn01974_c0
2026-01-13 19:56:02,270 - INFO - integrating rxn: rxn00100_c0
2026-01-13 19:56:02,271 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:56:02,273 - INFO - integrating rxn: rxn00383_c0
2026-01-13 19:56:02,274 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:56:02,275 - INFO - integrating rxn: rxn09202_c0
2026-01-13 19:56:02,277 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:56:02,278 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:56:02,279 - INFO - integrating rxn: rxn01997_c0
2026-01-13 19:56:02,281 - INFO - integrating rxn: rxn00178_c0
2026-01-13 19:56:02,282 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:56:02,284 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:56:02,285 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:56:02,287 - INFO - integrating rxn: rxn10213_c0
2026-01-13 19:56:02,288 - INFO - integrating rxn: rxn05229_c0
2026-01-13 19:56:02,290 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:56:02,291 - INFO - integrating rxn: rxn10204_c0
2026-01-13 19:56:02,292 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:56:02,294 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:56:02,295 - INFO - integrating rxn: rxn00029_c0
2026-01-13 19:56:02,297 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:56:02,299 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:56:02,300 - INFO - integrating rxn: rxn01454_c0
2026-01-13 19:56:02,302 - INFO - integrating rxn: rxn01501_c0
2026-01-13 19:56:02,303 - INFO - integrating rxn: rxn01505_c0
2026-01-13 19:56:02,304 - INFO - integrating rxn: rxn01256_c0
2026-01-13 19:56:02,306 - INFO - integrating rxn: rxn00237_c0
2026-01-13 19:56:02,307 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:56:02,309 - INFO - integrating rxn: rxn10124_c0
2026-01-13 19:56:02,310 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:56:02,311 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:56:02,313 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:56:02,314 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:56:02,316 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:56:02,317 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:56:02,318 - INFO - integrating rxn: rxn01000_c0
2026-01-13 19:56:02,321 - INFO - integrating rxn: rxn03397_c0
2026-01-13 19:56:02,322 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:56:02,324 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:56:02,325 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:56:02,327 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:56:02,328 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:56:02,329 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:56:02,331 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:56:02,332 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:56:02,333 - INFO - integrating rxn: rxn00137_c0
2026-01-13 19:56:02,335 - INFO - integrating rxn: rxn06023_c0
2026-01-13 19:56:02,336 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:56:02,338 - INFO - integrating rxn: rxn00069_c0
2026-01-13 19:56:02,339 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:56:02,341 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:56:02,342 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:56:02,343 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:56:02,345 - INFO - integrating rxn: rxn00726_c0
2026-01-13 19:56:02,346 - INFO - integrating rxn: rxn00440_c0
2026-01-13 19:56:02,347 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:56:02,349 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:56:02,350 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:56:02,352 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:56:02,353 - INFO - integrating rxn: rxn05029_c0
2026-01-13 19:56:02,355 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:56:02,356 - INFO - integrating rxn: rxn03538_c0
2026-01-13 19:56:02,358 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:56:02,359 - INFO - integrating rxn: rxn05618_c0
2026-01-13 19:56:02,360 - INFO - integrating rxn: rxn08241_c0
2026-01-13 19:56:02,361 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:56:02,363 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:56:02,364 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:56:02,365 - INFO - integrating rxn: rxn01512_c0
2026-01-13 19:56:02,367 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:56:02,368 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:56:02,369 - INFO - integrating rxn: rxn00704_c0
2026-01-13 19:56:02,371 - INFO - integrating rxn: rxn08130_c0
2026-01-13 19:56:02,372 - INFO - integrating rxn: rxn11702_c0
2026-01-13 19:56:02,374 - INFO - integrating rxn: rxn03084_c0
2026-01-13 19:56:02,376 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:56:02,377 - INFO - integrating rxn: rxn00346_c0
2026-01-13 19:56:02,378 - INFO - integrating rxn: rxn02897_c0
2026-01-13 19:56:02,380 - INFO - integrating rxn: rxn02056_c0
2026-01-13 19:56:02,382 - INFO - integrating rxn: rxn00141_c0
2026-01-13 19:56:02,384 - INFO - integrating rxn: rxn00130_c0
2026-01-13 19:56:02,386 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:56:02,388 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:56:02,390 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:56:02,392 - INFO - integrating rxn: rxn02288_c0
2026-01-13 19:56:02,395 - INFO - integrating rxn: rxn02831_c0
2026-01-13 19:56:02,397 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:56:02,398 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:56:02,400 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:56:02,402 - INFO - integrating rxn: rxn02832_c0
2026-01-13 19:56:02,404 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:56:02,406 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:56:02,408 - INFO - integrating rxn: rxn05464_c0
2026-01-13 19:56:02,410 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:56:02,412 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:56:02,413 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:56:02,415 - INFO - integrating rxn: rxn00224_c0
2026-01-13 19:56:02,417 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:56:02,418 - INFO - integrating rxn: rxn05177_c0
2026-01-13 19:56:02,420 - INFO - integrating rxn: rxn00117_c0
2026-01-13 19:56:02,421 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:56:02,423 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:56:02,424 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:56:02,426 - INFO - integrating rxn: rxn21859_c0
2026-01-13 19:56:02,427 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:56:02,429 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:56:02,430 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:56:02,432 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:56:02,433 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:56:02,435 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:56:02,436 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:56:02,438 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:56:02,440 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:56:02,441 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:56:02,442 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:56:02,444 - INFO - integrating rxn: rxn12944_c0
2026-01-13 19:56:02,446 - INFO - integrating rxn: rxn12994_c0
2026-01-13 19:56:02,448 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:56:02,449 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:56:02,450 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:56:02,451 - INFO - integrating rxn: rxn46124_c0
2026-01-13 19:56:02,453 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:56:02,454 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:56:02,456 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:56:02,457 - INFO - integrating rxn: rxn15167_c0
2026-01-13 19:56:02,458 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:56:02,460 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:56:02,461 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:56:02,463 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:56:02,464 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:56:02,466 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:56:02,467 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:56:02,469 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:56:02,470 - INFO - integrating rxn: rxn29919_c0
2026-01-13 19:56:02,471 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:56:02,473 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:56:02,474 - INFO - integrating rxn: rxn20627_c0
2026-01-13 19:56:02,475 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:56:02,477 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:56:02,478 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:56:02,480 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:56:02,481 - INFO - integrating rxn: rxn47875_c0
2026-01-13 19:56:02,483 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:56:02,484 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:56:02,485 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:56:02,487 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:56:02,488 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:56:02,489 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:56:02,491 - INFO - integrating rxn: rxn43975_c0
2026-01-13 19:56:02,492 - INFO - integrating rxn: rxn42732_c0
2026-01-13 19:56:02,494 - INFO - integrating rxn: rxn41263_c0
2026-01-13 19:56:02,495 - INFO - integrating rxn: rxn20839_c0
2026-01-13 19:56:02,496 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01974_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn00383_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn00178_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01454_c0', '<', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00069_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn00440_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn00623_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05177_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn21859_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12944_c0', '>', 'new'], ['rxn12994_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn47875_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:56:02,533 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:02,535 - INFO - AuxoMedia/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:02,536 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:02,538 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00149_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn01974_c0': '>', 'rxn00100_c0': '>', 'rxn08583_c0': '>', 'rxn00383_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01997_c0': '>', 'rxn00178_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn10204_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn00029_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01454_c0': '<', 'rxn01501_c0': '<', 'rxn01505_c0': '>', 'rxn01256_c0': '>', 'rxn00237_c0': '>', 'rxn03919_c0': '>', 'rxn10124_c0': '<', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn01000_c0': '>', 'rxn03397_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05645_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn06023_c0': '>', 'rxn00832_c0': '<', 'rxn00069_c0': '>', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn03917_c0': '>', 'rxn00726_c0': '>', 'rxn00440_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn05029_c0': '>', 'rxn02303_c0': '>', 'rxn03538_c0': '>', 'rxn01213_c0': '>', 'rxn05618_c0': '>', 'rxn08241_c0': '<', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn00599_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn00346_c0': '>', 'rxn02897_c0': '>', 'rxn02056_c0': '<', 'rxn00141_c0': '>', 'rxn00130_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn03130_c0': '>', 'rxn00623_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn05177_c0': '>', 'rxn00117_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn21859_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12944_c0': '>', 'rxn12994_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn15064_c0': '>', 'rxn08233_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn47875_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:02,814 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01974_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn00383_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn00178_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01454_c0', '<', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00069_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn00440_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn00623_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05177_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn47875_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 19:56:02,815 - INFO -     Added 153 reactions
2026-01-13 19:56:02,815 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:03,716 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0
2026-01-13 19:56:03,742 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:03,944 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:03,966 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:03,995 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:56:04,018 - INFO - Objective with gapfill database:19.125000000000007; min objective:0.01
2026-01-13 19:56:04,050 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn00512_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb2ec0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:04,053 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:56:04,054 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:56:04,056 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:04,058 - INFO - integrating rxn: rxn00615_c0
2026-01-13 19:56:04,059 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:56:04,061 - INFO - integrating rxn: rxn00512_c0
2026-01-13 19:56:04,061 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:04,062 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:56:04,070 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:56:04,071 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:56:04,073 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:56:04,074 - INFO - Glyc.O2/rxn00062_c0:rxn00615_c0> needed:0.0 with min obj:2
2026-01-13 19:56:04,075 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:56:04,076 - INFO - Glyc.O2/rxn00062_c0:rxn00512_c0< needed:0.0 with min obj:2
2026-01-13 19:56:04,077 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:56:04,083 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb2ec0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn00512_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:56:04,084 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn00615_c0': '>', 'rxn08527_c0': '<', 'rxn00512_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb2ec0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:04,088 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:56:04,110 - INFO - Objective with gapfill database:17.500000000000007; min objective:0.01
2026-01-13 19:56:04,140 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb3280>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:56:04,142 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:04,143 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:56:04,151 - INFO - Fum.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:3
2026-01-13 19:56:04,157 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb3280>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'rxn01476_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:04,157 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb3280>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:56:04,161 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:56:04,183 - INFO - Objective with gapfill database:19.124999999999996; min objective:0.01
2026-01-13 19:56:04,212 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn08527_c0': '<', 'rxn01476_c0': '>', 'rxn09269_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb3520>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:04,213 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:56:04,215 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:04,216 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:56:04,217 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:56:04,225 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:56:04,226 - INFO - rxn01476_c0> not needed:5.5
2026-01-13 19:56:04,227 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:56:04,233 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb3520>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn08527_c0': '<', 'rxn09269_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:04,234 - INFO - Unneeded: [['rxn01476_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {}, 'new': {'rxn08527_c0': '<', 'rxn01476_c0': '>', 'rxn09269_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb3520>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:04,237 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:56:04,259 - INFO - Objective with gapfill database:16.250000000000007; min objective:0.01
2026-01-13 19:56:04,289 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb39d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:04,291 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:56:04,293 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:56:04,294 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:04,295 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 19:56:04,302 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:56:04,303 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:56:04,304 - INFO - LLac.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:2
2026-01-13 19:56:04,310 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb39d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn01476_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:04,311 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn01476_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb39d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:04,315 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 19:56:04,338 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:04,482 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:56:04,504 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:05,035 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:56:05,070 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:05,618 - WARNING - No gapfilling solution found before filtering for Dlac activating rxn00062_c0

Removing ungapfillable media Dlac

2026-01-13 19:56:05,651 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:05,903 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:56:05,929 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:07,340 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:56:07,365 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:08,296 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:56:08,322 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:09,663 - INFO - Objective with gapfill database:137.21706849317263; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:10,820 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 19:56:10,839 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:10,844 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:56:10,881 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:11,171 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:56:11,196 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 19:56:11,224 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5d27aaa0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:56:11,227 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:11,229 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:56:11,230 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:11,232 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:56:11,233 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:11,235 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:11,237 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:11,238 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:56:11,239 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:56:11,255 - INFO - Glc.O2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:5
2026-01-13 19:56:11,256 - INFO - Glc.O2/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:5
2026-01-13 19:56:11,257 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.5 with min obj:5
2026-01-13 19:56:11,259 - INFO - Glc.O2/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:5
2026-01-13 19:56:11,260 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:56:11,262 - INFO - Glc.O2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:5
2026-01-13 19:56:11,263 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:56:11,264 - INFO - Glc.O2/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:5
2026-01-13 19:56:11,266 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5d27aaa0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:11,267 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5d27aaa0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:56:11,270 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 19:56:11,291 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:12,089 - INFO - Objective with gapfill database:137.21706849317263; min objective:0.01
2026-01-13 19:56:12,683 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08551_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn02404_c0': '>', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn10954_c0': '>', 'rxn05645_c0': '>', 'rxn03843_c0': '>', 'rxn08711_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn02508_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn08088_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn03439_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn03075_c0': '>', 'rxn00122_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn00644_c0': '>', 'rxn04551_c0': '>', 'rxn24212_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn20567_c0': '>', 'rxn23676_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:12,687 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 19:56:12,689 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 19:56:12,691 - INFO - integrating rxn: EX_cpd00220_e0
2026-01-13 19:56:12,692 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 19:56:12,694 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 19:56:12,695 - INFO - integrating rxn: EX_cpd00104_e0
2026-01-13 19:56:12,697 - INFO - integrating rxn: rxn08709_c0
2026-01-13 19:56:12,698 - INFO - integrating rxn: rxn00800_c0
2026-01-13 19:56:12,700 - INFO - integrating rxn: rxn10336_c0
2026-01-13 19:56:12,701 - INFO - integrating rxn: rxn01636_c0
2026-01-13 19:56:12,703 - INFO - integrating rxn: rxn01117_c0
2026-01-13 19:56:12,704 - INFO - integrating rxn: rxn00470_c0
2026-01-13 19:56:12,706 - INFO - integrating rxn: rxn08710_c0
2026-01-13 19:56:12,708 - INFO - integrating rxn: rxn03181_c0
2026-01-13 19:56:12,709 - INFO - integrating rxn: rxn02331_c0
2026-01-13 19:56:12,711 - INFO - integrating rxn: rxn12512_c0
2026-01-13 19:56:12,712 - INFO - integrating rxn: rxn08583_c0
2026-01-13 19:56:12,714 - INFO - integrating rxn: rxn02264_c0
2026-01-13 19:56:12,715 - INFO - integrating rxn: rxn05514_c0
2026-01-13 19:56:12,717 - INFO - integrating rxn: rxn10481_c0
2026-01-13 19:56:12,718 - INFO - integrating rxn: rxn03918_c0
2026-01-13 19:56:12,720 - INFO - integrating rxn: rxn08551_c0
2026-01-13 19:56:12,721 - INFO - integrating rxn: rxn08708_c0
2026-01-13 19:56:12,723 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:56:12,724 - INFO - integrating rxn: rxn02404_c0
2026-01-13 19:56:12,726 - INFO - integrating rxn: rxn06937_c0
2026-01-13 19:56:12,727 - INFO - integrating rxn: rxn00392_c0
2026-01-13 19:56:12,729 - INFO - integrating rxn: rxn09225_c0
2026-01-13 19:56:12,730 - INFO - integrating rxn: rxn02774_c0
2026-01-13 19:56:12,732 - INFO - integrating rxn: rxn03536_c0
2026-01-13 19:56:12,733 - INFO - integrating rxn: rxn03919_c0
2026-01-13 19:56:12,734 - INFO - integrating rxn: rxn09210_c0
2026-01-13 19:56:12,736 - INFO - integrating rxn: rxn08954_c0
2026-01-13 19:56:12,738 - INFO - integrating rxn: rxn00916_c0
2026-01-13 19:56:12,739 - INFO - integrating rxn: rxn08712_c0
2026-01-13 19:56:12,740 - INFO - integrating rxn: rxn08618_c0
2026-01-13 19:56:12,742 - INFO - integrating rxn: rxn03159_c0
2026-01-13 19:56:12,744 - INFO - integrating rxn: rxn11703_c0
2026-01-13 19:56:12,745 - INFO - integrating rxn: rxn06848_c0
2026-01-13 19:56:12,746 - INFO - integrating rxn: rxn03537_c0
2026-01-13 19:56:12,748 - INFO - integrating rxn: rxn00966_c0
2026-01-13 19:56:12,749 - INFO - integrating rxn: rxn03916_c0
2026-01-13 19:56:12,751 - INFO - integrating rxn: rxn09106_c0
2026-01-13 19:56:12,753 - INFO - integrating rxn: rxn10954_c0
2026-01-13 19:56:12,754 - INFO - integrating rxn: rxn05645_c0
2026-01-13 19:56:12,756 - INFO - integrating rxn: rxn03843_c0
2026-01-13 19:56:12,757 - INFO - integrating rxn: rxn08711_c0
2026-01-13 19:56:12,759 - INFO - integrating rxn: rxn00832_c0
2026-01-13 19:56:12,760 - INFO - integrating rxn: rxn04139_c0
2026-01-13 19:56:12,762 - INFO - integrating rxn: rxn05299_c0
2026-01-13 19:56:12,763 - INFO - integrating rxn: rxn06723_c0
2026-01-13 19:56:12,764 - INFO - integrating rxn: rxn02508_c0
2026-01-13 19:56:12,765 - INFO - integrating rxn: rxn03917_c0
2026-01-13 19:56:12,767 - INFO - integrating rxn: rxn03146_c0
2026-01-13 19:56:12,768 - INFO - integrating rxn: rxn03893_c0
2026-01-13 19:56:12,769 - INFO - integrating rxn: rxn02405_c0
2026-01-13 19:56:12,771 - INFO - integrating rxn: rxn03150_c0
2026-01-13 19:56:12,772 - INFO - integrating rxn: rxn01537_c0
2026-01-13 19:56:12,774 - INFO - integrating rxn: rxn02303_c0
2026-01-13 19:56:12,775 - INFO - integrating rxn: rxn01213_c0
2026-01-13 19:56:12,776 - INFO - integrating rxn: rxn03136_c0
2026-01-13 19:56:12,778 - INFO - integrating rxn: rxn08088_c0
2026-01-13 19:56:12,779 - INFO - integrating rxn: rxn00350_c0
2026-01-13 19:56:12,780 - INFO - integrating rxn: rxn03137_c0
2026-01-13 19:56:12,782 - INFO - integrating rxn: rxn06865_c0
2026-01-13 19:56:12,783 - INFO - integrating rxn: rxn03439_c0
2026-01-13 19:56:12,785 - INFO - integrating rxn: rxn01790_c0
2026-01-13 19:56:12,786 - INFO - integrating rxn: rxn03638_c0
2026-01-13 19:56:12,788 - INFO - integrating rxn: rxn03075_c0
2026-01-13 19:56:12,789 - INFO - integrating rxn: rxn00122_c0
2026-01-13 19:56:12,790 - INFO - integrating rxn: rxn05223_c0
2026-01-13 19:56:12,792 - INFO - integrating rxn: rxn08713_c0
2026-01-13 19:56:12,793 - INFO - integrating rxn: rxn08620_c0
2026-01-13 19:56:12,795 - INFO - integrating rxn: rxn01466_c0
2026-01-13 19:56:12,796 - INFO - integrating rxn: rxn02287_c0
2026-01-13 19:56:12,797 - INFO - integrating rxn: rxn04308_c0
2026-01-13 19:56:12,799 - INFO - integrating rxn: rxn01258_c0
2026-01-13 19:56:12,800 - INFO - integrating rxn: rxn05255_c0
2026-01-13 19:56:12,801 - INFO - integrating rxn: rxn03130_c0
2026-01-13 19:56:12,803 - INFO - integrating rxn: rxn02341_c0
2026-01-13 19:56:12,804 - INFO - integrating rxn: rxn03511_c0
2026-01-13 19:56:12,805 - INFO - integrating rxn: rxn03182_c0
2026-01-13 19:56:12,806 - INFO - integrating rxn: rxn08619_c0
2026-01-13 19:56:12,808 - INFO - integrating rxn: rxn00293_c0
2026-01-13 19:56:12,810 - INFO - integrating rxn: rxn21635_c0
2026-01-13 19:56:12,811 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:56:12,813 - INFO - integrating rxn: rxn15949_c0
2026-01-13 19:56:12,814 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:56:12,816 - INFO - integrating rxn: rxn15947_c0
2026-01-13 19:56:12,817 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:56:12,819 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:56:12,820 - INFO - integrating rxn: rxn12930_c0
2026-01-13 19:56:12,822 - INFO - integrating rxn: rxn12932_c0
2026-01-13 19:56:12,823 - INFO - integrating rxn: rxn12940_c0
2026-01-13 19:56:12,825 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:56:12,826 - INFO - integrating rxn: rxn12929_c0
2026-01-13 19:56:12,827 - INFO - integrating rxn: rxn25637_c0
2026-01-13 19:56:12,829 - INFO - integrating rxn: rxn18935_c0
2026-01-13 19:56:12,831 - INFO - integrating rxn: rxn25743_c0
2026-01-13 19:56:12,832 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:56:12,833 - INFO - integrating rxn: rxn12943_c0
2026-01-13 19:56:12,835 - INFO - integrating rxn: rxn12942_c0
2026-01-13 19:56:12,836 - INFO - integrating rxn: rxn02485_c0
2026-01-13 19:56:12,837 - INFO - integrating rxn: rxn12934_c0
2026-01-13 19:56:12,839 - INFO - integrating rxn: rxn25474_c0
2026-01-13 19:56:12,840 - INFO - integrating rxn: rxn12941_c0
2026-01-13 19:56:12,842 - INFO - integrating rxn: rxn19346_c0
2026-01-13 19:56:12,843 - INFO - integrating rxn: rxn00644_c0
2026-01-13 19:56:12,844 - INFO - integrating rxn: rxn04551_c0
2026-01-13 19:56:12,846 - INFO - integrating rxn: rxn24212_c0
2026-01-13 19:56:12,847 - INFO - integrating rxn: rxn03396_c0
2026-01-13 19:56:12,849 - INFO - integrating rxn: rxn25479_c0
2026-01-13 19:56:12,850 - INFO - integrating rxn: rxn22114_c0
2026-01-13 19:56:12,852 - INFO - integrating rxn: rxn14070_c0
2026-01-13 19:56:12,853 - INFO - integrating rxn: rxn15060_c0
2026-01-13 19:56:12,855 - INFO - integrating rxn: rxn15064_c0
2026-01-13 19:56:12,856 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:56:12,857 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:56:12,858 - INFO - integrating rxn: rxn08233_c0
2026-01-13 19:56:12,860 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:56:12,861 - INFO - integrating rxn: rxn15940_c0
2026-01-13 19:56:12,863 - INFO - integrating rxn: rxn30917_c0
2026-01-13 19:56:12,864 - INFO - integrating rxn: rxn40674_c0
2026-01-13 19:56:12,866 - INFO - integrating rxn: rxn09037_c0
2026-01-13 19:56:12,867 - INFO - integrating rxn: rxn08921_c0
2026-01-13 19:56:12,868 - INFO - integrating rxn: rxn29260_c0
2026-01-13 19:56:12,870 - INFO - integrating rxn: rxn20567_c0
2026-01-13 19:56:12,871 - INFO - integrating rxn: rxn23676_c0
2026-01-13 19:56:12,872 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:56:12,874 - INFO - integrating rxn: rxn10042_c0
2026-01-13 19:56:12,875 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08551_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn03843_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn24212_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn20567_c0', '>', 'new'], ['rxn23676_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 19:56:12,917 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,919 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,921 - INFO - AuxoMedia/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,923 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,925 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,926 - INFO - AuxoMedia/bio1:EX_cpd00104_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,928 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,930 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,931 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,933 - INFO - AuxoMedia/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,934 - INFO - AuxoMedia/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,936 - INFO - AuxoMedia/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,938 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,939 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,941 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,943 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,944 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,946 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,948 - INFO - AuxoMedia/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,949 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,951 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,952 - INFO - AuxoMedia/bio1:rxn08551_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,954 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,956 - INFO - AuxoMedia/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,957 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,959 - INFO - AuxoMedia/bio1:rxn06937_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,961 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,962 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,964 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,965 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,967 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,970 - INFO - AuxoMedia/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,971 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,973 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,975 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,976 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,978 - INFO - AuxoMedia/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,979 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,981 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,982 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,984 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,985 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,987 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,988 - INFO - AuxoMedia/bio1:rxn10954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,990 - INFO - AuxoMedia/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,992 - INFO - AuxoMedia/bio1:rxn03843_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,993 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,995 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:12,996 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,998 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:12,999 - INFO - AuxoMedia/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:13,001 - INFO - AuxoMedia/bio1:rxn02508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:13,002 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:13,004 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:13,005 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:13,007 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:13,009 - INFO - AuxoMedia/bio1:rxn03150_c0> needed:0.0 with min obj:0.01

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00220_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00104_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn01636_c0': '>', 'rxn01117_c0': '<', 'rxn00470_c0': '>', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08551_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn02404_c0': '>', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn03919_c0': '>', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn10954_c0': '>', 'rxn05645_c0': '>', 'rxn03843_c0': '>', 'rxn08711_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn02508_c0': '>', 'rxn03917_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn03150_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn08088_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn06865_c0': '<', 'rxn03439_c0': '>', 'rxn01790_c0': '<', 'rxn03638_c0': '>', 'rxn03075_c0': '>', 'rxn00122_c0': '>', 'rxn05223_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn01466_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn00293_c0': '>', 'rxn21635_c0': '>', 'rxn16218_c0': '>', 'rxn15949_c0': '>', 'rxn16217_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn25637_c0': '>', 'rxn18935_c0': '>', 'rxn25743_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn00644_c0': '>', 'rxn04551_c0': '>', 'rxn24212_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn15060_c0': '>', 'rxn15064_c0': '>', 'rxn15270_c0': '>', 'rxn10095_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn20567_c0': '>', 'rxn23676_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:13,161 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08551_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn03843_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new']]
2026-01-13 19:56:13,162 - INFO -     Added 109 reactions
2026-01-13 19:56:13,163 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:13,821 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:56:13,844 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:14,149 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:56:14,176 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:56:14,207 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860ee60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:14,211 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:14,212 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:14,213 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:56:14,215 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:14,216 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:56:14,217 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:14,218 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:56:14,228 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:14,230 - INFO - Glc/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:14,231 - INFO - rxn00102_c0> not needed:2.5
2026-01-13 19:56:14,233 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:14,234 - INFO - Glc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:14,235 - INFO - rxn00250_c0< not needed:2.5
2026-01-13 19:56:14,242 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860ee60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:56:14,242 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860ee60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:14,246 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:56:14,270 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:14,575 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:56:14,598 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:15,156 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:56:15,183 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:15,306 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0
2026-01-13 19:56:15,330 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:56:15,359 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8fe80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:15,362 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:56:15,363 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:15,364 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:56:15,365 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:15,366 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:56:15,367 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:56:15,368 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:56:15,369 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:56:15,369 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:15,370 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:15,376 - INFO - cpd00159 not found in model!
2026-01-13 19:56:15,376 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:56:15,377 - INFO - cpd11640 not found in model!
2026-01-13 19:56:15,378 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:15,381 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,382 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:15,383 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:15,385 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,386 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,387 - INFO - LLac.SO4.H2/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,388 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,388 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:15,389 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:15,396 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8fe80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:15,396 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb8fe80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:15,400 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:15,422 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:56:15,449 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb70370>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:15,452 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:56:15,453 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:15,454 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:56:15,455 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:15,455 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:56:15,456 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:56:15,457 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:56:15,458 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:56:15,458 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:15,459 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:15,465 - INFO - cpd00159 not found in model!
2026-01-13 19:56:15,466 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:56:15,469 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,470 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:15,471 - INFO - LLac.SO4/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:15,472 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,473 - INFO - LLac.SO4/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,474 - INFO - LLac.SO4/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,475 - INFO - LLac.SO4/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:15,476 - INFO - LLac.SO4/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:15,477 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:15,483 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb70370>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:15,484 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn08173_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa6eb70370>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:15,487 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01977_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn00974_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01388_c0', '<', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:15,508 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:15,654 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:56:15,679 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:16,452 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:56:16,478 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:56:16,508 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c825ae0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:16,511 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:16,512 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:16,512 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:56:16,513 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:56:16,515 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:16,515 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:56:16,516 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:16,517 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:56:16,518 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:16,527 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:16,529 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:16,530 - INFO - rxn00248_c0> not needed:1.0000000000000004
2026-01-13 19:56:16,531 - INFO - rxn00102_c0> not needed:1.0
2026-01-13 19:56:16,532 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:16,533 - INFO - Fum/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:16,534 - INFO - rxn00250_c0< not needed:1.0000000000000004
2026-01-13 19:56:16,536 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:16,542 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c825ae0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:56:16,543 - INFO - Unneeded: [['rxn00248_c0', '>', 'new', 100, None], ['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c825ae0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:16,545 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:16,569 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:16,611 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:56:16,625 - INFO - cpd00425 not found in model!
2026-01-13 19:56:16,626 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:56:16,640 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:18,568 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 19:56:18,590 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:56:18,618 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c6095a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:18,620 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:18,622 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:18,623 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:56:18,624 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:56:18,624 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:56:18,625 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:18,627 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:56:18,627 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:18,628 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:18,633 - INFO - cpd08021 not found in model!
2026-01-13 19:56:18,633 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:56:18,637 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:18,638 - INFO - Glc.DMSO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:18,639 - INFO - Glc.DMSO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:18,640 - INFO - Glc.DMSO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:18,641 - INFO - rxn00102_c0> not needed:2.5
2026-01-13 19:56:18,642 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:18,643 - INFO - Glc.DMSO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:18,644 - INFO - rxn00250_c0< not needed:2.5
2026-01-13 19:56:18,649 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c6095a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:56:18,650 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c6095a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:18,653 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:18,673 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:56:18,700 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c6093c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:18,702 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:18,703 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:18,704 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:56:18,704 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:56:18,705 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:56:18,706 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:18,707 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:56:18,708 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:18,709 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:18,714 - INFO - cpd00811 not found in model!
2026-01-13 19:56:18,714 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:56:18,717 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:18,718 - INFO - Glc.TMAO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:18,719 - INFO - Glc.TMAO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:18,720 - INFO - Glc.TMAO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:18,721 - INFO - rxn00102_c0> not needed:2.5
2026-01-13 19:56:18,722 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:18,723 - INFO - Glc.TMAO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:18,724 - INFO - rxn00250_c0< not needed:2.5
2026-01-13 19:56:18,729 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c6093c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:56:18,730 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c6093c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:18,733 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:18,753 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:19,196 - INFO - Objective with gapfill database:86.90736662373932; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:19,278 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:19,299 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:19,332 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:56:19,356 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:19,976 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:56:19,999 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:21,426 - INFO - Objective with gapfill database:86.90736662373932; min objective:0.01
2026-01-13 19:56:21,946 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn03436_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02185_c0': '<', 'rxn16218_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn48543_c0': '>', 'rxn16217_c0': '>', 'rxn11274_c0': '>', 'rxn11251_c0': '>', 'rxn30633_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn16114_c0': '>', 'rxn15270_c0': '>', 'rxn41185_c0': '>', 'rxn16341_c0': '>', 'rxn46249_c0': '>', 'rxn41492_c0': '>', 'rxn44493_c0': '>', 'rxn47875_c0': '>', 'rxn08989_c0': '>', 'rxn08473_c0': '>', 'rxn15754_c0': '>', 'rxn15776_c0': '>', 'rxn14050_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:21,952 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:56:21,954 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:56:21,956 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:56:21,959 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:56:21,961 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:56:21,963 - INFO - integrating rxn: rxn16218_c0
2026-01-13 19:56:21,965 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:56:21,967 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:56:21,969 - INFO - integrating rxn: rxn48543_c0
2026-01-13 19:56:21,971 - INFO - integrating rxn: rxn16217_c0
2026-01-13 19:56:21,973 - INFO - integrating rxn: rxn11274_c0
2026-01-13 19:56:21,975 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:56:21,977 - INFO - integrating rxn: rxn30633_c0
2026-01-13 19:56:21,978 - INFO - integrating rxn: rxn25042_c0
2026-01-13 19:56:21,980 - INFO - integrating rxn: rxn19766_c0
2026-01-13 19:56:21,982 - INFO - integrating rxn: rxn19764_c0
2026-01-13 19:56:21,984 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:56:21,985 - INFO - integrating rxn: rxn15270_c0
2026-01-13 19:56:21,987 - INFO - integrating rxn: rxn41185_c0
2026-01-13 19:56:21,989 - INFO - integrating rxn: rxn16341_c0
2026-01-13 19:56:21,990 - INFO - integrating rxn: rxn46249_c0
2026-01-13 19:56:21,992 - INFO - integrating rxn: rxn41492_c0
2026-01-13 19:56:21,993 - INFO - integrating rxn: rxn44493_c0
2026-01-13 19:56:21,995 - INFO - integrating rxn: rxn47875_c0
2026-01-13 19:56:21,997 - INFO - integrating rxn: rxn08989_c0
2026-01-13 19:56:21,998 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:56:22,000 - INFO - integrating rxn: rxn15754_c0
2026-01-13 19:56:22,002 - INFO - integrating rxn: rxn15776_c0
2026-01-13 19:56:22,004 - INFO - integrating rxn: rxn14050_c0
2026-01-13 19:56:22,005 - INFO - Full solution: [['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn09177_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], 'rxn08709_c0', 'rxn00800_c0', 'rxn09177_c0', 'rxn10336_c0', 'rxn08583_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn03536_c0', 'rxn08954_c0', 'rxn08618_c0', 'rxn03537_c0', 'rxn03916_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn02287_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn01603_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn30685_c0', 'rxn40674_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn48543_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn30633_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn41185_c0', '>', 'new'], ['rxn16341_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn47875_c0', '>', 'new'], ['rxn08989_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn15754_c0', '>', 'new'], ['rxn15776_c0', '>', 'new'], ['rxn14050_c0', '>', 'new']]
2026-01-13 19:56:22,051 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,054 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,057 - INFO - PyruateMinimalAnaerobic/bio1:rxn09177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,059 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,062 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,064 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,066 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,068 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,070 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,072 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,074 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,076 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,078 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,080 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,082 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,087 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:9.856317387364645e-13 with min obj:0.01
2026-01-13 19:56:22,089 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:22,091 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:22,093 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01

2026-01-13 19:56:22,095 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,097 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,099 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,102 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,104 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,106 - INFO - PyruateMinimalAnaerobic/bio1:rxn01603_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,108 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,111 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,113 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,115 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,117 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,119 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,121 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,123 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,130 - INFO - rxn30685_c0> not needed:23.23811595029207
2026-01-13 19:56:22,134 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,135 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'r'
2026-01-13 19:56:22,136 - INFO -   Running ATP safety check...

c0

2026-01-13 19:56:22,140 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:56:22,164 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:56:22,194 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb3f40>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:22,197 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:22,198 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:22,199 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:22,201 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:22,202 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:22,203 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new']]
2026-01-13 19:56:22,211 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,212 - INFO - rxn07191_c0< not needed:0.5
2026-01-13 19:56:22,214 - INFO - Glc/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,215 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,216 - INFO - Glc/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:22,222 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb3f40>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:22,223 - INFO - Unneeded: [['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dbb3f40>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:22,226 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new']]
2026-01-13 19:56:22,248 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:23,802 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:56:23,820 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:25,179 - INFO - Objective with gapfill database:114.73871061823222; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:25,515 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:56:25,538 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:25,662 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:56:25,689 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:26,396 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:56:26,422 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:56:26,451 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f0f10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:26,453 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:56:26,454 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:56:26,455 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:26,456 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:56:26,457 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new']]
2026-01-13 19:56:26,467 - INFO - Glc/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:26,468 - INFO - Glc/rxn00062_c0:rxn00499_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:26,469 - INFO - Glc/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:26,471 - INFO - Glc/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:26,477 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f0f10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:26,477 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f0f10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:26,482 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new']]
2026-01-13 19:56:26,505 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:27,084 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 19:56:27,093 - INFO - cpd08701 not found in model!
2026-01-13 19:56:27,094 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:56:27,095 - INFO - cpd01024 not found in model!
2026-01-13 19:56:27,096 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:56:27,102 - INFO - cpd08701 not found in model!
2026-01-13 19:56:27,103 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:56:27,103 - INFO - cpd01024 not found in model!
2026-01-13 19:56:27,104 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:56:27,113 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:27,652 - INFO - Objective with gapfill database:114.73871061823222; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:27,929 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:27,952 - INFO - Objective with gapfill database:19.125000000000018; min objective:0.01
2026-01-13 19:56:27,981 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00935_c0': '<', 'rxn14426_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1d215660>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:27,983 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:56:27,985 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:56:27,986 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:27,988 - INFO - integrating rxn: rxn14425_c0
2026-01-13 19:56:27,989 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:56:27,991 - INFO - integrating rxn: rxn14426_c0
2026-01-13 19:56:27,992 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:56:27,993 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:27,994 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:56:28,002 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:56:28,003 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:56:28,004 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:56:28,005 - INFO - Glyc.O2/rxn00062_c0:rxn14425_c0> needed:0.0 with min obj:2
2026-01-13 19:56:28,006 - INFO - Glyc.O2/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:2
2026-01-13 19:56:28,007 - INFO - Glyc.O2/rxn00062_c0:rxn14426_c0> needed:0.0 with min obj:2
2026-01-13 19:56:28,008 - INFO - Glyc.O2/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:2
2026-01-13 19:56:28,009 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:56:28,013 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0
2026-01-13 19:56:28,014 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1d215660>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00935_c0': '<', 'rxn14426_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}

Removing ungapfillable media Pyr.NO2

2026-01-13 19:56:28,015 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00935_c0': '<', 'rxn14426_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1d215660>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:28,019 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:56:28,040 - INFO - Objective with gapfill database:17.499999999999993; min objective:0.01
2026-01-13 19:56:28,043 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:28,068 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1ce50160>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:56:28,070 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:28,071 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:28,072 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:28,073 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:28,074 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:56:28,075 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:28,082 - INFO - Fum.O2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:3
2026-01-13 19:56:28,083 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:1.0 with min obj:3
2026-01-13 19:56:28,084 - INFO - Fum.O2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:3
2026-01-13 19:56:28,085 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:56:28,086 - INFO - Fum.O2/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:3
2026-01-13 19:56:28,091 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1ce50160>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}}
2026-01-13 19:56:28,092 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1ce50160>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:56:28,095 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:28,116 - INFO - Objective with gapfill database:18.250000000000004; min objective:0.01
2026-01-13 19:56:28,144 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14424_c0': '>', 'rxn14425_c0': '>', 'rxn14423_c0': '>', 'rxn09269_c0': '>', 'rxn00173_c0': '>', 'rxn14426_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1ce50430>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:28,146 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:56:28,148 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:56:28,149 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:28,151 - INFO - integrating rxn: rxn14424_c0
2026-01-13 19:56:28,152 - INFO - integrating rxn: rxn14425_c0
2026-01-13 19:56:28,154 - INFO - integrating rxn: rxn14423_c0
2026-01-13 19:56:28,155 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:56:28,157 - INFO - integrating rxn: rxn00173_c0
2026-01-13 19:56:28,157 - INFO - integrating rxn: rxn14426_c0
2026-01-13 19:56:28,158 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:28,159 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00173_c0', '>', 'new']]
2026-01-13 19:56:28,166 - INFO - EX_cpd00029_e0> not needed:15.375
2026-01-13 19:56:28,167 - INFO - rxn05488_c0< not needed:15.375
2026-01-13 19:56:28,168 - INFO - rxn07191_c0< not needed:13.375
2026-01-13 19:56:28,169 - INFO - rxn14424_c0> not needed:13.375
2026-01-13 19:56:28,170 - INFO - Succ.O2/rxn00062_c0:rxn14425_c0> needed:0.0 with min obj:2
2026-01-13 19:56:28,171 - INFO - rxn14423_c0> not needed:13.375
2026-01-13 19:56:28,172 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:56:28,173 - INFO - rxn00173_c0> not needed:13.375
2026-01-13 19:56:28,174 - INFO - Succ.O2/rxn00062_c0:rxn14426_c0> needed:0.0 with min obj:2
2026-01-13 19:56:28,175 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:56:28,183 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1ce50430>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn14425_c0': '>', 'rxn09269_c0': '>', 'rxn14426_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:56:28,184 - INFO - Unneeded: [['EX_cpd00029_e0', '>', 'new', 100, None], ['rxn05488_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None], ['rxn14424_c0', '>', 'new', 100, None], ['rxn14423_c0', '>', 'new', 100, None], ['rxn00173_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14424_c0': '>', 'rxn14425_c0': '>', 'rxn14423_c0': '>', 'rxn09269_c0': '>', 'rxn00173_c0': '>', 'rxn14426_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1ce50430>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:28,187 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:56:28,207 - INFO - Objective with gapfill database:16.249999999999993; min objective:0.01
2026-01-13 19:56:28,228 - INFO - Initial solution: {'reversed': {'rxn00623_c0': '<'}, 'new': {'EX_cpd00013_e0': '<', 'EX_cpd00048_e0': '<', 'EX_cpd15378_e0': '>', 'rxn00359_c0': '<', 'rxn02504_c0': '>', 'rxn02305_c0': '>', 'rxn01306_c0': '<', 'rxn03436_c0': '>', 'rxn02160_c0': '>', 'rxn05466_c0': '>', 'rxn00300_c0': '>', 'rxn02835_c0': '>', 'rxn12868_c0': '>', 'rxn12376_c0': '<', 'rxn01303_c0': '>', 'rxn01539_c0': '<', 'rxn00505_c0': '>', 'rxn03108_c0': '>', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn03909_c0': '>', 'rxn05651_c0': '>', 'rxn02277_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn11279_c0': '>', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn21864_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn40439_c0': '>', 'rxn21860_c0': '>', 'rxn12939_c0': '>', 'rxn25638_c0': '>', 'rxn12928_c0': '>', 'rxn11162_c0': '>', 'rxn28338_c0': '>', 'rxn45899_c0': '>', 'rxn47659_c0': '>', 'rxn43798_c0': '>', 'rxn14178_c0': '>', 'rxn16048_c0': '>', 'rxn16114_c0': '>', 'rxn37372_c0': '>', 'rxn11285_c0': '>', 'rxn10095_c0': '>', 'rxn20508_c0': '>', 'rxn42332_c0': '>', 'rxn47493_c0': '>', 'rxn08474_c0': '>', 'rxn08473_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:28,232 - INFO - integrating rxn: EX_cpd00013_e0
2026-01-13 19:56:28,234 - INFO - integrating rxn: EX_cpd00048_e0
2026-01-13 19:56:28,235 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00173_c0': '>', 'rxn14426_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1ce50280>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:28,235 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 19:56:28,237 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 19:56:28,237 - INFO - integrating rxn: rxn00359_c0
2026-01-13 19:56:28,238 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:56:28,239 - INFO - integrating rxn: rxn02504_c0
2026-01-13 19:56:28,240 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:56:28,241 - INFO - integrating rxn: rxn02305_c0
2026-01-13 19:56:28,241 - INFO - integrating rxn: rxn05488_c0
2026-01-13 19:56:28,242 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:28,242 - INFO - integrating rxn: rxn01306_c0
2026-01-13 19:56:28,243 - INFO - integrating rxn: rxn14425_c0
2026-01-13 19:56:28,244 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:56:28,245 - INFO - integrating rxn: rxn00173_c0
2026-01-13 19:56:28,245 - INFO - integrating rxn: rxn02160_c0
2026-01-13 19:56:28,245 - INFO - integrating rxn: rxn14426_c0
2026-01-13 19:56:28,246 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new']]
2026-01-13 19:56:28,247 - INFO - integrating rxn: rxn05466_c0
2026-01-13 19:56:28,248 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:56:28,250 - INFO - integrating rxn: rxn02835_c0
2026-01-13 19:56:28,252 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:56:28,253 - INFO - LLac.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:2
2026-01-13 19:56:28,253 - INFO - integrating rxn: rxn12376_c0
2026-01-13 19:56:28,254 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:56:28,255 - INFO - integrating rxn: rxn01303_c0
2026-01-13 19:56:28,255 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:56:28,256 - INFO - LLac.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:2
2026-01-13 19:56:28,257 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:56:28,257 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:56:28,258 - INFO - LLac.O2/rxn00062_c0:rxn14425_c0> needed:0.0 with min obj:2
2026-01-13 19:56:28,258 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:56:28,259 - INFO - LLac.O2/rxn00062_c0:rxn00173_c0> needed:0.0 with min obj:2
2026-01-13 19:56:28,260 - INFO - integrating rxn: rxn03108_c0
2026-01-13 19:56:28,261 - INFO - LLac.O2/rxn00062_c0:rxn14426_c0> needed:0.0 with min obj:2
2026-01-13 19:56:28,262 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:56:28,264 - INFO - integrating rxn: rxn02834_c0
2026-01-13 19:56:28,265 - INFO - integrating rxn: rxn03909_c0
2026-01-13 19:56:28,267 - INFO - integrating rxn: rxn05651_c0
2026-01-13 19:56:28,267 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1ce50280>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00173_c0': '>', 'rxn14426_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:28,268 - INFO - Unneeded: []
2026-01-13 19:56:28,268 - INFO - integrating rxn: rxn02277_c0

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00173_c0': '>', 'rxn14426_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1ce50280>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:28,270 - INFO - integrating rxn: rxn00309_c0

2026-01-13 19:56:28,272 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new']]
2026-01-13 19:56:28,272 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:56:28,274 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:56:28,275 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:56:28,277 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:56:28,278 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:56:28,280 - INFO - integrating rxn: rxn10504_c0
2026-01-13 19:56:28,281 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:56:28,283 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:56:28,284 - INFO - integrating rxn: rxn21864_c0
2026-01-13 19:56:28,285 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:56:28,287 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:56:28,288 - INFO - integrating rxn: rxn40439_c0
2026-01-13 19:56:28,290 - INFO - integrating rxn: rxn21860_c0
2026-01-13 19:56:28,291 - INFO - integrating rxn: rxn12939_c0
2026-01-13 19:56:28,293 - INFO - integrating rxn: rxn25638_c0
2026-01-13 19:56:28,294 - INFO - integrating rxn: rxn12928_c0
2026-01-13 19:56:28,295 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:28,295 - INFO - integrating rxn: rxn11162_c0
2026-01-13 19:56:28,297 - INFO - integrating rxn: rxn28338_c0
2026-01-13 19:56:28,298 - INFO - integrating rxn: rxn45899_c0
2026-01-13 19:56:28,300 - INFO - integrating rxn: rxn47659_c0
2026-01-13 19:56:28,301 - INFO - integrating rxn: rxn43798_c0
2026-01-13 19:56:28,303 - INFO - integrating rxn: rxn14178_c0
2026-01-13 19:56:28,304 - INFO - integrating rxn: rxn16048_c0
2026-01-13 19:56:28,306 - INFO - integrating rxn: rxn16114_c0
2026-01-13 19:56:28,307 - INFO - integrating rxn: rxn37372_c0
2026-01-13 19:56:28,308 - INFO - integrating rxn: rxn11285_c0
2026-01-13 19:56:28,310 - INFO - integrating rxn: rxn10095_c0
2026-01-13 19:56:28,311 - INFO - integrating rxn: rxn20508_c0
2026-01-13 19:56:28,312 - INFO - integrating rxn: rxn42332_c0
2026-01-13 19:56:28,314 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:56:28,315 - INFO - integrating rxn: rxn08474_c0
2026-01-13 19:56:28,316 - INFO - integrating rxn: rxn08473_c0
2026-01-13 19:56:28,317 - INFO - integrating rxn: rxn00623_c0
2026-01-13 19:56:28,318 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00149_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn01974_c0', '>', 'new'], ['rxn00100_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn00383_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01997_c0', '>', 'new'], ['rxn00178_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn00029_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01454_c0', '<', 'new'], ['rxn01501_c0', '<', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn01256_c0', '>', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn01000_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn06023_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn00069_c0', '>', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn00726_c0', '>', 'new'], ['rxn00440_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn05029_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn03538_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn08241_c0', '<', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn00346_c0', '>', 'new'], ['rxn02897_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00141_c0', '>', 'new'], ['rxn00130_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn00623_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn05177_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn41492_c0', '>', 'new'], ['rxn44493_c0', '>', 'new'], ['rxn47875_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new'], 'EX_cpd00305_e0', 'EX_cpd00030_e0', 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00149_e0', 'EX_cpd00063_e0', 'EX_cpd00099_e0', 'rxn08709_c0', 'rxn03086_c0', 'rxn08333_c0', 'rxn02898_c0', 'rxn10336_c0', 'rxn03030_c0', 'rxn01117_c0', 'rxn00470_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn01974_c0', 'rxn00100_c0', 'rxn08583_c0', 'rxn00383_c0', 'rxn02264_c0', 'rxn09202_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn01997_c0', 'rxn00178_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00907_c0', 'rxn10213_c0', 'rxn05229_c0', 'rxn02404_c0', 'rxn10204_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn00029_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn01454_c0', 'rxn01501_c0', 'rxn01505_c0', 'rxn01256_c0', 'rxn00237_c0', 'rxn03919_c0', 'rxn10124_c0', 'rxn09210_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03159_c0', 'rxn01000_c0', 'rxn03397_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn05645_c0', 'rxn08711_c0', 'rxn00137_c0', 'rxn06023_c0', 'rxn00832_c0', 'rxn00069_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn03917_c0', 'rxn00726_c0', 'rxn00440_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn03150_c0', 'rxn05029_c0', 'rxn02303_c0', 'rxn03538_c0', 'rxn01213_c0', 'rxn05618_c0', 'rxn08241_c0', 'rxn03136_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn01512_c0', 'rxn06865_c0', 'rxn00599_c0', 'rxn00704_c0', 'rxn08130_c0', 'rxn11702_c0', 'rxn03084_c0', 'rxn03439_c0', 'rxn00346_c0', 'rxn02897_c0', 'rxn02056_c0', 'rxn00141_c0', 'rxn00130_c0', 'rxn00122_c0', 'rxn08713_c0', 'rxn02287_c0', 'rxn02288_c0', 'rxn02831_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn02832_c0', 'rxn03130_c0', 'rxn00623_c0', 'rxn05464_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn00224_c0', 'rxn08619_c0', 'rxn05177_c0', 'rxn00117_c0', 'rxn00293_c0', 'rxn16218_c0', 'rxn15949_c0', 'rxn16217_c0', 'rxn15947_c0', 'rxn14424_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn15167_c0', 'rxn19346_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn29919_c0', 'rxn15064_c0', 'rxn08233_c0', 'rxn20627_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn41492_c0', 'rxn44493_c0', 'rxn47875_c0', 'rxn40674_c0', 'rxn09037_c0', 'rxn14423_c0', 'rxn43975_c0', 'rxn42732_c0', 'rxn41263_c0', 'rxn20839_c0', ['EX_cpd00013_e0', '<', 'new'], ['EX_cpd00048_e0', '<', 'new'], ['EX_cpd15378_e0', '>', 'new'], ['rxn00359_c0', '<', 'new'], ['rxn02504_c0', '>', 'new'], ['rxn02305_c0', '>', 'new'], ['rxn01306_c0', '<', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn02160_c0', '>', 'new'], ['rxn05466_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn02835_c0', '>', 'new'], ['rxn12868_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn01303_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03108_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn03909_c0', '>', 'new'], ['rxn05651_c0', '>', 'new'], ['rxn02277_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn21864_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn40439_c0', '>', 'new'], ['rxn21860_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn25638_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn11162_c0', '>', 'new'], ['rxn28338_c0', '>', 'new'], ['rxn45899_c0', '>', 'new'], ['rxn47659_c0', '>', 'new'], ['rxn43798_c0', '>', 'new'], ['rxn14178_c0', '>', 'new'], ['rxn16048_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn37372_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn42332_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn08474_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn00623_c0', '<', 'reversed']]
2026-01-13 19:56:28,325 - INFO - cpd11640 not found in model!
2026-01-13 19:56:28,326 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:28,335 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,336 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,338 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,339 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,340 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00220_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,341 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,342 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00149_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,344 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,345 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,346 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,347 - INFO - PyruateMinimalAnaerobic/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,348 - INFO - PyruateMinimalAnaerobic/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,349 - INFO - PyruateMinimalAnaerobic/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,351 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,352 - INFO - PyruateMinimalAnaerobic/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,353 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,354 - INFO - PyruateMinimalAnaerobic/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,355 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,356 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,358 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,359 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,360 - INFO - PyruateMinimalAnaerobic/bio1:rxn01974_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,361 - INFO - PyruateMinimalAnaerobic/bio1:rxn00100_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,362 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,363 - INFO - PyruateMinimalAnaerobic/bio1:rxn00383_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,365 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,366 - INFO - PyruateMinimalAnaerobic/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,367 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:28,368 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01

2026-01-13 19:56:28,370 - INFO - PyruateMinimalAnaerobic/bio1:rxn01997_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,371 - INFO - PyruateMinimalAnaerobic/bio1:rxn00178_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,372 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,373 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,374 - INFO - PyruateMinimalAnaerobic/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,376 - INFO - PyruateMinimalAnaerobic/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,377 - INFO - PyruateMinimalAnaerobic/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,378 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,379 - INFO - PyruateMinimalAnaerobic/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,380 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,381 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,383 - INFO - PyruateMinimalAnaerobic/bio1:rxn00029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,384 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,385 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,386 - INFO - PyruateMinimalAnaerobic/bio1:rxn01454_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,387 - INFO - PyruateMinimalAnaerobic/bio1:rxn01501_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,388 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,390 - INFO - PyruateMinimalAnaerobic/bio1:rxn01256_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,391 - INFO - PyruateMinimalAnaerobic/bio1:rxn00237_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,392 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,393 - INFO - PyruateMinimalAnaerobic/bio1:rxn10124_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,395 - INFO - PyruateMinimalAnaerobic/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,396 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,397 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,398 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,400 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,401 - INFO - PyruateMinimalAnaerobic/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,402 - INFO - PyruateMinimalAnaerobic/bio1:rxn01000_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,403 - INFO - PyruateMinimalAnaerobic/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,404 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,405 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,407 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,408 - INFO - PyruateMinimalAnaerobic/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,409 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,410 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,411 - INFO - PyruateMinimalAnaerobic/bio1:rxn05645_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,412 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,414 - INFO - PyruateMinimalAnaerobic/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,415 - INFO - PyruateMinimalAnaerobic/bio1:rxn06023_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,416 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,417 - INFO - PyruateMinimalAnaerobic/bio1:rxn00069_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,419 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,420 - INFO - PyruateMinimalAnaerobic/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,421 - INFO - PyruateMinimalAnaerobic/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,422 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,423 - INFO - PyruateMinimalAnaerobic/bio1:rxn00726_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,424 - INFO - PyruateMinimalAnaerobic/bio1:rxn00440_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,426 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,427 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,428 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,429 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,430 - INFO - PyruateMinimalAnaerobic/bio1:rxn05029_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,431 - INFO - PyruateMinimalAnaerobic/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,431 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0
2026-01-13 19:56:28,432 - INFO - PyruateMinimalAnaerobic/bio1:rxn03538_c0> needed:0.0 with min obj:0.01

Removing ungapfillable media mal-L

2026-01-13 19:56:28,434 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01

2026-01-13 19:56:28,435 - INFO - PyruateMinimalAnaerobic/bio1:rxn05618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,437 - INFO - PyruateMinimalAnaerobic/bio1:rxn08241_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,438 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,439 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,440 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,441 - INFO - PyruateMinimalAnaerobic/bio1:rxn01512_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,442 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,443 - INFO - PyruateMinimalAnaerobic/bio1:rxn00599_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,445 - INFO - PyruateMinimalAnaerobic/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,446 - INFO - PyruateMinimalAnaerobic/bio1:rxn08130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,447 - INFO - PyruateMinimalAnaerobic/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,448 - INFO - PyruateMinimalAnaerobic/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,449 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,450 - INFO - PyruateMinimalAnaerobic/bio1:rxn00346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,451 - INFO - PyruateMinimalAnaerobic/bio1:rxn02897_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,453 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,454 - INFO - PyruateMinimalAnaerobic/bio1:rxn00141_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,455 - INFO - PyruateMinimalAnaerobic/bio1:rxn00130_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,456 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,457 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,458 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,459 - INFO - PyruateMinimalAnaerobic/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,461 - INFO - PyruateMinimalAnaerobic/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,462 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,463 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,464 - INFO - PyruateMinimalAnaerobic/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,466 - INFO - PyruateMinimalAnaerobic/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:28,466 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:28,467 - INFO - PyruateMinimalAnaerobic/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,468 - INFO - PyruateMinimalAnaerobic/bio1:rxn00623_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,469 - INFO - PyruateMinimalAnaerobic/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,470 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,472 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,473 - INFO - PyruateMinimalAnaerobic/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,474 - INFO - PyruateMinimalAnaerobic/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,475 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,476 - INFO - PyruateMinimalAnaerobic/bio1:rxn05177_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,477 - INFO - PyruateMinimalAnaerobic/bio1:rxn00117_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,479 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,480 - INFO - PyruateMinimalAnaerobic/bio1:rxn16218_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,481 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,482 - INFO - PyruateMinimalAnaerobic/bio1:rxn16217_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,483 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,484 - INFO - PyruateMinimalAnaerobic/bio1:rxn14424_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,486 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,487 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,488 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,489 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,490 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,491 - INFO - PyruateMinimalAnaerobic/bio1:rxn15167_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,493 - INFO - PyruateMinimalAnaerobic/bio1:rxn19346_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,494 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,495 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,496 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,498 - INFO - PyruateMinimalAnaerobic/bio1:rxn29919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,499 - INFO - PyruateMinimalAnaerobic/bio1:rxn15064_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,500 - INFO - PyruateMinimalAnaerobic/bio1:rxn08233_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,501 - INFO - PyruateMinimalAnaerobic/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,503 - INFO - PyruateMinimalAnaerobic/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,504 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,505 - INFO - PyruateMinimalAnaerobic/bio1:rxn41492_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,506 - INFO - PyruateMinimalAnaerobic/bio1:rxn44493_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,507 - INFO - PyruateMinimalAnaerobic/bio1:rxn47875_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,509 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,510 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,511 - INFO - PyruateMinimalAnaerobic/bio1:rxn14423_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,512 - INFO - PyruateMinimalAnaerobic/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,514 - INFO - PyruateMinimalAnaerobic/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,515 - INFO - PyruateMinimalAnaerobic/bio1:rxn41263_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,516 - INFO - PyruateMinimalAnaerobic/bio1:rxn20839_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:28,517 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:56:28,518 - INFO -   Running ATP safety check...

c0
Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:29,004 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:56:29,037 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:29,267 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:56:29,290 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:30,248 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:56:30,276 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:31,390 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 19:56:31,410 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:32,182 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:56:32,209 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:32,602 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:32,632 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,651 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,670 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,676 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:56:32,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,703 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:56:32,708 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,727 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,733 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'EX_cpd00027_e0': '<', 'rxn00256_c0': '<', 'rxn01106_c0': '<', 'rxn01476_c0': '>', 'rxn05226_c0': '>', 'rxn00157_c0': '<', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b813fd0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:56:32,735 - INFO - integrating rxn: EX_cpd00027_e0
2026-01-13 19:56:32,737 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:56:32,739 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:56:32,740 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:32,742 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:56:32,743 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:56:32,745 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:32,745 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:56:32,746 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,746 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed']]
2026-01-13 19:56:32,764 - INFO - Glc.O2/rxn00062_c0:EX_cpd00027_e0< needed:0.0 with min obj:5
2026-01-13 19:56:32,765 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,766 - INFO - Glc.O2/rxn00062_c0:rxn00256_c0< needed:1.0 with min obj:5
2026-01-13 19:56:32,767 - INFO - rxn01106_c0< not needed:12.0
2026-01-13 19:56:32,768 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 19:56:32,769 - INFO - Glc.O2/rxn00062_c0:rxn05226_c0> needed:0.0 with min obj:5
2026-01-13 19:56:32,770 - INFO - Glc.O2/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:5
2026-01-13 19:56:32,771 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 19:56:32,773 - INFO - Glc.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:5
2026-01-13 19:56:32,775 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b813fd0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'EX_cpd00027_e0': '<', 'rxn00256_c0': '<', 'rxn01476_c0': '>', 'rxn05226_c0': '>', 'rxn00157_c0': '<', 'rxn03884_c0': '>'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:56:32,776 - INFO - Unneeded: [['rxn01106_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'EX_cpd00027_e0': '<', 'rxn00256_c0': '<', 'rxn01106_c0': '<', 'rxn01476_c0': '>', 'rxn05226_c0': '>', 'rxn00157_c0': '<', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b813fd0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:56:32,779 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed']]
2026-01-13 19:56:32,784 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,802 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:32,803 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,822 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,843 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,862 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,881 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,901 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,919 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,938 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,957 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,975 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:32,994 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,012 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,030 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,049 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,068 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,086 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,105 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:33,123 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,149 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,168 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,187 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,206 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,244 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,264 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,283 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,302 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,321 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:33,340 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:33,359 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,379 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,381 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:56:33,397 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,401 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:56:33,406 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:56:33,413 - INFO - cpd11632 not found in model!
2026-01-13 19:56:33,414 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:56:33,417 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,426 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:33,436 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,438 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c9c9d20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:33,440 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:56:33,441 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:33,443 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:56:33,444 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:33,445 - INFO - integrating rxn: rxn08173_c0
2026-01-13 19:56:33,446 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:33,447 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:33,455 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,455 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:33,456 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:33,458 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:33,459 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:33,460 - INFO - Llac/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:33,461 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:33,468 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c9c9d20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:33,468 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c9c9d20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:33,472 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:33,473 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,489 - INFO - cpd11632 not found in model!
2026-01-13 19:56:33,490 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:56:33,494 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,498 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:33,509 - INFO - cpd08701 not found in model!
2026-01-13 19:56:33,510 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:56:33,511 - INFO - cpd01024 not found in model!
2026-01-13 19:56:33,512 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:56:33,516 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,532 - INFO - cpd01024 not found in model!
2026-01-13 19:56:33,532 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:56:33,537 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,555 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,574 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,590 - INFO - cpd00187 not found in model!
2026-01-13 19:56:33,591 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:56:33,596 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,612 - INFO - cpd00425 not found in model!
2026-01-13 19:56:33,613 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:56:33,617 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:33,636 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:34,430 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:56:34,452 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:35,502 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 19:56:35,524 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:36,089 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:56:36,101 - INFO - cpd11632 not found in model!
2026-01-13 19:56:36,102 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:56:36,115 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:36,356 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:56:36,388 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:36,743 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 19:56:36,764 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:56:36,791 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b060b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:36,794 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:36,795 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:56:36,796 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:56:36,797 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:36,798 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:56:36,798 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:56:36,799 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:36,800 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:36,801 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:36,801 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:56:36,802 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:56:36,808 - INFO - cpd08021 not found in model!
2026-01-13 19:56:36,809 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:56:36,814 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,815 - INFO - Glc.DMSO/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,816 - INFO - rxn05938_c0< not needed:0.5
2026-01-13 19:56:36,817 - INFO - rxn07191_c0< not needed:0.5
2026-01-13 19:56:36,818 - INFO - Glc.DMSO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:36,819 - INFO - Glc.DMSO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:36,820 - INFO - Glc.DMSO/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,821 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,822 - INFO - Glc.DMSO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,823 - INFO - Glc.DMSO/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,827 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b060b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:36,828 - INFO - Unneeded: [['rxn05938_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b060b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:36,831 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:56:36,850 - INFO - Objective with gapfill database:3.499999999999999; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:36,875 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b05e10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:36,877 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:36,878 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:56:36,878 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:56:36,879 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:36,880 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:56:36,881 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:56:36,882 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:36,882 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:36,883 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:36,884 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:56:36,885 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:56:36,889 - INFO - cpd00811 not found in model!
2026-01-13 19:56:36,889 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:56:36,892 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,894 - INFO - Glc.TMAO/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,895 - INFO - rxn05938_c0< not needed:0.5
2026-01-13 19:56:36,896 - INFO - rxn07191_c0< not needed:0.5
2026-01-13 19:56:36,897 - INFO - Glc.TMAO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:36,898 - INFO - Glc.TMAO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:36,899 - INFO - Glc.TMAO/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,900 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,901 - INFO - Glc.TMAO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,902 - INFO - Glc.TMAO/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:36,906 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b05e10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:36,907 - INFO - Unneeded: [['rxn05938_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b05e10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:36,910 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:56:36,913 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:56:36,927 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:36,941 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:37,523 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:56:37,556 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:38,195 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:56:38,221 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:56:38,256 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a624f40>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:38,259 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:38,260 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:38,261 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:38,263 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:38,264 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:56:38,265 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:56:38,274 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:38,276 - INFO - Glc/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:38,277 - INFO - Glc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:38,278 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:38,279 - INFO - Glc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:38,286 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a624f40>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:56:38,287 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a624f40>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:38,292 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 19:56:38,316 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:38,614 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 19:56:38,638 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:38,868 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:56:38,891 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:39,996 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:56:40,019 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:56:40,049 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00615_c0': '>', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dfbb640>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:40,052 - INFO - integrating rxn: EX_cpd00047_e0
2026-01-13 19:56:40,053 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:40,054 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:56:40,054 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:56:40,055 - INFO - integrating rxn: rxn00615_c0
2026-01-13 19:56:40,057 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:56:40,059 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:56:40,060 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:40,061 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:56:40,062 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:40,063 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new']]
2026-01-13 19:56:40,071 - INFO - Glyc/rxn00062_c0:EX_cpd00047_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,072 - INFO - Glyc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,073 - INFO - Glyc/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,074 - INFO - Glyc/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,075 - INFO - Glyc/rxn00062_c0:rxn00615_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,076 - INFO - Glyc/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,077 - INFO - Glyc/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,078 - INFO - Glyc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,079 - INFO - Glyc/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,080 - INFO - Glyc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,086 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dfbb640>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00615_c0': '>', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:56:40,087 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00615_c0': '>', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dfbb640>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:40,091 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new']]
2026-01-13 19:56:40,113 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:56:40,143 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0da1c130>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:40,144 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:40,145 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:40,145 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:40,146 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:56:40,147 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:40,147 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:40,155 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,156 - INFO - rxn07191_c0< not needed:1.0
2026-01-13 19:56:40,157 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,158 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,159 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,164 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0da1c130>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn05553_c0': '>'}, 'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}}
2026-01-13 19:56:40,165 - INFO - Unneeded: [['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0da1c130>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:40,169 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:40,190 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:56:40,219 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn09269_c0': '>', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0da1c310>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:40,221 - INFO - integrating rxn: EX_cpd00047_e0
2026-01-13 19:56:40,222 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:40,223 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:56:40,225 - INFO - integrating rxn: rxn00288_c0
2026-01-13 19:56:40,225 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:56:40,226 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:56:40,227 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:40,228 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:56:40,228 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:56:40,229 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:40,229 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:40,237 - INFO - Succ/rxn00062_c0:EX_cpd00047_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,238 - INFO - Succ/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,239 - INFO - Succ/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,240 - INFO - Succ/rxn00062_c0:rxn00288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,241 - INFO - Succ/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,242 - INFO - Succ/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,243 - INFO - Succ/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,244 - INFO - Succ/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,245 - INFO - Succ/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,246 - INFO - Succ/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,251 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0da1c310>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn09269_c0': '>', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}}
2026-01-13 19:56:40,252 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn09269_c0': '>', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0da1c310>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:40,257 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:40,280 - INFO - Objective with gapfill database:0.7500000000000004; min objective:0.01
2026-01-13 19:56:40,309 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dcf2140>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:40,311 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:56:40,312 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:40,312 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:56:40,314 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:40,315 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:40,316 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:40,323 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,325 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,326 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,327 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:40,328 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:40,334 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dcf2140>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:40,335 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dcf2140>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:40,339 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:40,361 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:40,751 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:56:40,777 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:40,988 - INFO - Objective with gapfill database:86.04689764726723; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:41,799 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:56:41,832 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:42,381 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:56:42,409 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:42,750 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:56:42,774 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:56:42,803 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00615_c0': '>', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f1240>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:42,806 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:42,807 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:56:42,808 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:56:42,809 - INFO - integrating rxn: rxn00615_c0
2026-01-13 19:56:42,811 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:56:42,813 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:56:42,814 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:42,816 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:56:42,817 - INFO - integrating rxn: rxn00616_c0
2026-01-13 19:56:42,819 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:56:42,820 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:42,821 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:56:42,829 - INFO - Glyc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:42,830 - INFO - Glyc/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,831 - INFO - Glyc/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,832 - INFO - Glyc/rxn00062_c0:rxn00615_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:42,833 - INFO - Glyc/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,834 - INFO - Glyc/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,835 - INFO - Glyc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:42,836 - INFO - Glyc/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,837 - INFO - Glyc/rxn00062_c0:rxn00616_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:42,838 - INFO - Glyc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,839 - INFO - Glyc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,844 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f1240>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00615_c0': '>', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:56:42,845 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00615_c0': '>', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00616_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f1240>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:42,849 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new']]
2026-01-13 19:56:42,872 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:56:42,900 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f1bd0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:42,903 - INFO - integrating rxn: EX_cpd00106_e0
2026-01-13 19:56:42,903 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:42,904 - INFO - integrating rxn: rxn05561_c0
2026-01-13 19:56:42,905 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:42,906 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:42,907 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:56:42,908 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:56:42,908 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:42,909 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:42,917 - INFO - Fum/rxn00062_c0:EX_cpd00106_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,918 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:42,919 - INFO - Fum/rxn00062_c0:rxn05561_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:42,920 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,921 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:42,922 - INFO - Fum/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,922 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:42,923 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:42,929 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f1bd0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}}
2026-01-13 19:56:42,930 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00106_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05561_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa292f1bd0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:42,933 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:42,963 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:56:42,991 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'EX_cpd00363_e0': '>', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn09269_c0': '>', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928dab0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:42,993 - INFO - integrating rxn: EX_cpd00036_e0
2026-01-13 19:56:42,994 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:42,995 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:56:42,997 - INFO - integrating rxn: rxn00288_c0
2026-01-13 19:56:42,998 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:56:42,999 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:56:42,999 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:43,000 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:56:43,001 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:56:43,001 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:56:43,002 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:43,003 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:43,010 - INFO - Succ/rxn00062_c0:EX_cpd00036_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:43,011 - INFO - Succ/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:43,012 - INFO - Succ/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:43,013 - INFO - Succ/rxn00062_c0:rxn00288_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:43,014 - INFO - Succ/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:43,015 - INFO - Succ/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:43,016 - INFO - Succ/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:43,017 - INFO - Succ/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:43,018 - INFO - Succ/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:43,019 - INFO - Succ/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:43,020 - INFO - Succ/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:43,026 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928dab0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00036_e0': '<', 'EX_cpd00363_e0': '>', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn09269_c0': '>', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}}
2026-01-13 19:56:43,026 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00036_e0': '<', 'EX_cpd00363_e0': '>', 'rxn00935_c0': '<', 'rxn00288_c0': '>', 'rxn09269_c0': '>', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928dab0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:43,030 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:43,052 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:56:43,080 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928dea0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:43,082 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:43,083 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:43,083 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:56:43,084 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:43,085 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:43,093 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:43,094 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:43,095 - INFO - Llac/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:43,097 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:43,102 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928dea0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:43,103 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928dea0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:43,107 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:43,129 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:43,420 - INFO - Objective with gapfill database:86.04689764726702; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:43,687 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:56:43,708 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:43,960 - INFO - Initial solution: {'reversed': {'rxn00907_c0': '<'}, 'new': {'rxn03436_c0': '>', 'rxn00957_c0': '>', 'rxn00300_c0': '>', 'rxn03175_c0': '>', 'rxn12868_c0': '>', 'rxn01539_c0': '<', 'rxn00505_c0': '>', 'rxn09310_c0': '>', 'rxn00952_c0': '>', 'rxn12239_c0': '>', 'rxn00599_c0': '>', 'rxn00309_c0': '<', 'rxn02185_c0': '<', 'rxn01603_c0': '>', 'rxn00157_c0': '>', 'rxn16573_c0': '>', 'rxn22816_c0': '>', 'rxn21862_c0': '>', 'rxn11279_c0': '>', 'rxn10506_c0': '>', 'rxn41452_c0': '>', 'rxn22817_c0': '>', 'rxn21858_c0': '>', 'rxn20834_c0': '>', 'rxn11251_c0': '>', 'rxn30685_c0': '>', 'rxn15939_c0': '>', 'rxn47493_c0': '>', 'rxn09390_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:43,965 - INFO - integrating rxn: rxn03436_c0
2026-01-13 19:56:43,967 - INFO - integrating rxn: rxn00957_c0
2026-01-13 19:56:43,969 - INFO - integrating rxn: rxn00300_c0
2026-01-13 19:56:43,970 - INFO - integrating rxn: rxn03175_c0
2026-01-13 19:56:43,972 - INFO - integrating rxn: rxn12868_c0
2026-01-13 19:56:43,974 - INFO - integrating rxn: rxn01539_c0
2026-01-13 19:56:43,975 - INFO - integrating rxn: rxn00505_c0
2026-01-13 19:56:43,978 - INFO - integrating rxn: rxn09310_c0
2026-01-13 19:56:43,979 - INFO - integrating rxn: rxn00952_c0
2026-01-13 19:56:43,980 - INFO - integrating rxn: rxn12239_c0
2026-01-13 19:56:43,982 - INFO - integrating rxn: rxn00599_c0
2026-01-13 19:56:43,983 - INFO - integrating rxn: rxn00309_c0
2026-01-13 19:56:43,985 - INFO - integrating rxn: rxn02185_c0
2026-01-13 19:56:43,986 - INFO - integrating rxn: rxn01603_c0
2026-01-13 19:56:43,988 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:56:43,989 - INFO - integrating rxn: rxn16573_c0
2026-01-13 19:56:43,991 - INFO - integrating rxn: rxn22816_c0
2026-01-13 19:56:43,992 - INFO - integrating rxn: rxn21862_c0
2026-01-13 19:56:43,994 - INFO - integrating rxn: rxn11279_c0
2026-01-13 19:56:43,995 - INFO - integrating rxn: rxn10506_c0
2026-01-13 19:56:43,997 - INFO - integrating rxn: rxn41452_c0
2026-01-13 19:56:43,998 - INFO - integrating rxn: rxn22817_c0
2026-01-13 19:56:43,999 - INFO - integrating rxn: rxn21858_c0
2026-01-13 19:56:44,001 - INFO - integrating rxn: rxn20834_c0
2026-01-13 19:56:44,002 - INFO - integrating rxn: rxn11251_c0
2026-01-13 19:56:44,004 - INFO - integrating rxn: rxn30685_c0
2026-01-13 19:56:44,005 - INFO - integrating rxn: rxn15939_c0
2026-01-13 19:56:44,007 - INFO - integrating rxn: rxn47493_c0
2026-01-13 19:56:44,008 - INFO - integrating rxn: rxn09390_c0
2026-01-13 19:56:44,009 - INFO - integrating rxn: rxn00907_c0
2026-01-13 19:56:44,009 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00220_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00104_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn01636_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn00470_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08551_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn10954_c0', '>', 'new'], ['rxn05645_c0', '>', 'new'], ['rxn03843_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn02508_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn03150_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn08088_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn03638_c0', '>', 'new'], ['rxn03075_c0', '>', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn05223_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn01466_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn25637_c0', '>', 'new'], ['rxn18935_c0', '>', 'new'], ['rxn25743_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], 'EX_cpd00393_e0', 'EX_cpd00119_e0', 'EX_cpd00220_e0', 'EX_cpd00058_e0', 'EX_cpd00063_e0', 'EX_cpd00104_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn01636_c0', 'rxn01117_c0', 'rxn00470_c0', 'rxn08710_c0', 'rxn03181_c0', 'rxn02331_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn02264_c0', 'rxn05514_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08551_c0', 'rxn08708_c0', 'rxn00907_c0', 'rxn02404_c0', 'rxn06937_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn03536_c0', 'rxn03919_c0', 'rxn09210_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08712_c0', 'rxn08618_c0', 'rxn03159_c0', 'rxn11703_c0', 'rxn06848_c0', 'rxn03537_c0', 'rxn00966_c0', 'rxn03916_c0', 'rxn09106_c0', 'rxn10954_c0', 'rxn05645_c0', 'rxn03843_c0', 'rxn08711_c0', 'rxn00832_c0', 'rxn04139_c0', 'rxn05299_c0', 'rxn06723_c0', 'rxn02508_c0', 'rxn03917_c0', 'rxn03146_c0', 'rxn03893_c0', 'rxn02405_c0', 'rxn03150_c0', 'rxn01537_c0', 'rxn02303_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn08088_c0', 'rxn00350_c0', 'rxn03137_c0', 'rxn06865_c0', 'rxn03439_c0', 'rxn01790_c0', 'rxn03638_c0', 'rxn03075_c0', 'rxn00122_c0', 'rxn05223_c0', 'rxn08713_c0', 'rxn08620_c0', 'rxn01466_c0', 'rxn02287_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn05255_c0', 'rxn03130_c0', 'rxn02341_c0', 'rxn03511_c0', 'rxn03182_c0', 'rxn08619_c0', 'rxn00293_c0', 'rxn15949_c0', 'rxn15947_c0', 'rxn12930_c0', 'rxn12932_c0', 'rxn12940_c0', 'rxn12939_c0', 'rxn12929_c0', 'rxn25637_c0', 'rxn18935_c0', 'rxn25743_c0', 'rxn12928_c0', 'rxn12943_c0', 'rxn12942_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn19346_c0', 'rxn03396_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', 'rxn09037_c0', ['rxn03436_c0', '>', 'new'], ['rxn00957_c0', '>', 'new'], ['rxn00300_c0', '>', 'new'], ['rxn03175_c0', '>', 'new'], ['rxn12868_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn00952_c0', '>', 'new'], ['rxn12239_c0', '>', 'new'], ['rxn00599_c0', '>', 'new'], ['rxn00309_c0', '<', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn00157_c0', '>', 'new'], ['rxn16573_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn21862_c0', '>', 'new'], ['rxn11279_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn41452_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn21858_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn00907_c0', '<', 'reversed']]
2026-01-13 19:56:44,031 - INFO - EX_cpd00393_e0< not needed:5.733240820004551
2026-01-13 19:56:44,032 - INFO - EX_cpd00119_e0< not needed:5.733240820004551
2026-01-13 19:56:44,033 - INFO - EX_cpd00220_e0< not needed:5.733240820004551
2026-01-13 19:56:44,037 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,038 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,042 - INFO - EX_cpd00104_e0< not needed:5.733240820004525
2026-01-13 19:56:44,046 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,048 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,049 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,051 - INFO - PyruateMinimalAnaerobic/bio1:rxn01636_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,053 - INFO - PyruateMinimalAnaerobic/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,055 - INFO - PyruateMinimalAnaerobic/bio1:rxn00470_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,056 - INFO - PyruateMinimalAnaerobic/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,058 - INFO - PyruateMinimalAnaerobic/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,060 - INFO - PyruateMinimalAnaerobic/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,061 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:-3.822667821625777e-13 with min obj:0.01
2026-01-13 19:56:44,063 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,065 - INFO - PyruateMinimalAnaerobic/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,067 - INFO - PyruateMinimalAnaerobic/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,069 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,070 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,072 - INFO - PyruateMinimalAnaerobic/bio1:rxn08551_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,074 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,077 - INFO - rxn00907_c0> not needed:5.733240820004487
2026-01-13 19:56:44,080 - INFO - PyruateMinimalAnaerobic/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,083 - INFO - rxn06937_c0> not needed:5.733240820004482
2026-01-13 19:56:44,086 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,087 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,089 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:44,090 - INFO - PyruateMinimalAnaerobic/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,092 - INFO - PyruateMinimalAnaerobic/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,094 - INFO - PyruateMinimalAnaerobic/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,095 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,097 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,099 - INFO - PyruateMinimalAnaerobic/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,100 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,102 - INFO - PyruateMinimalAnaerobic/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,103 - INFO - PyruateMinimalAnaerobic/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,105 - INFO - PyruateMinimalAnaerobic/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,106 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,109 - INFO - rxn00966_c0< not needed:5.7332408200045055
2026-01-13 19:56:44,111 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,113 - INFO - PyruateMinimalAnaerobic/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,115 - INFO - PyruateMinimalAnaerobic/bio1:rxn10954_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,117 - INFO - rxn05645_c0> not needed:5.733240820004507
2026-01-13 19:56:44,120 - INFO - PyruateMinimalAnaerobic/bio1:rxn03843_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,121 - INFO - PyruateMinimalAnaerobic/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,123 - INFO - PyruateMinimalAnaerobic/bio1:rxn00832_c0< needed:5.378415600851312e-13 with min obj:0.01
2026-01-13 19:56:44,125 - INFO - PyruateMinimalAnaerobic/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,128 - INFO - rxn05299_c0> not needed:5.733240820004502
2026-01-13 19:56:44,131 - INFO - PyruateMinimalAnaerobic/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,132 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0
2026-01-13 19:56:44,133 - INFO - PyruateMinimalAnaerobic/bio1:rxn02508_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,134 - INFO - PyruateMinimalAnaerobic/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,136 - INFO - PyruateMinimalAnaerobic/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,138 - INFO - PyruateMinimalAnaerobic/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,139 - INFO - PyruateMinimalAnaerobic/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,141 - INFO - PyruateMinimalAnaerobic/bio1:rxn03150_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,149 - INFO - PyruateMinimalAnaerobic/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,152 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:44,153 - INFO - PyruateMinimalAnaerobic/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,155 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,157 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,158 - INFO - PyruateMinimalAnaerobic/bio1:rxn08088_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,160 - INFO - PyruateMinimalAnaerobic/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,161 - INFO - PyruateMinimalAnaerobic/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,163 - INFO - PyruateMinimalAnaerobic/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,165 - INFO - PyruateMinimalAnaerobic/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,167 - INFO - PyruateMinimalAnaerobic/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:44,169 - INFO - PyruateMinimalAnaerobic/bio1:rxn03638_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,170 - INFO - PyruateMinimalAnaerobic/bio1:rxn03075_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,172 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,176 - INFO - rxn05223_c0> not needed:5.733240820004483
2026-01-13 19:56:44,178 - INFO - PyruateMinimalAnaerobic/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,180 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,181 - INFO - PyruateMinimalAnaerobic/bio1:rxn01466_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,183 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,185 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,187 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,190 - INFO - rxn05255_c0> not needed:5.733240820004477
2026-01-13 19:56:44,193 - INFO - PyruateMinimalAnaerobic/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,195 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,196 - INFO - PyruateMinimalAnaerobic/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,198 - INFO - PyruateMinimalAnaerobic/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,199 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,201 - INFO - PyruateMinimalAnaerobic/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,203 - INFO - PyruateMinimalAnaerobic/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,205 - INFO - PyruateMinimalAnaerobic/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,206 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,208 - INFO - PyruateMinimalAnaerobic/bio1:rxn12932_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,210 - INFO - PyruateMinimalAnaerobic/bio1:rxn12940_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,211 - INFO - PyruateMinimalAnaerobic/bio1:rxn12939_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,213 - INFO - PyruateMinimalAnaerobic/bio1:rxn12929_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,214 - INFO - PyruateMinimalAnaerobic/bio1:rxn25637_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,216 - INFO - PyruateMinimalAnaerobic/bio1:rxn18935_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,218 - INFO - PyruateMinimalAnaerobic/bio1:rxn25743_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,219 - INFO - PyruateMinimalAnaerobic/bio1:rxn12928_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,221 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,222 - INFO - PyruateMinimalAnaerobic/bio1:rxn12942_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,224 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,225 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,227 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,231 - INFO - rxn19346_c0> not needed:5.733240820004556
2026-01-13 19:56:44,233 - INFO - PyruateMinimalAnaerobic/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,235 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,237 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,239 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,242 - INFO - rxn15940_c0> not needed:5.733240820004499
2026-01-13 19:56:44,245 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,246 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,248 - INFO - PyruateMinimalAnaerobic/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:44,249 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 19:56:44,250 - INFO -   Running ATP safety check...

c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:44,942 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:56:44,965 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:56:44,994 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe8e20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:44,996 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:44,998 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:56:44,999 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:45,000 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:56:45,001 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:45,002 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:45,003 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:45,003 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:56:45,004 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new']]
2026-01-13 19:56:45,012 - INFO - Glc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:45,013 - INFO - Glc/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:45,015 - INFO - rxn07191_c0< not needed:0.5
2026-01-13 19:56:45,016 - INFO - Glc/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:45,017 - INFO - Glc/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:45,018 - INFO - Glc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:45,019 - INFO - Glc/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:45,020 - INFO - Glc/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:45,025 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe8e20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:45,026 - INFO - Unneeded: [['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn00083_c0': '>', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe8e20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:45,029 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new']]
2026-01-13 19:56:45,051 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:46,259 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:56:46,284 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:56:46,314 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860f7f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:46,317 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:46,318 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:46,320 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:56:46,321 - INFO - integrating rxn: rxn00102_c0
2026-01-13 19:56:46,322 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:46,323 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:56:46,324 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:46,325 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:56:46,326 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:46,335 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:46,336 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:46,338 - INFO - Fum/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:46,339 - INFO - rxn00102_c0> not needed:1.0
2026-01-13 19:56:46,341 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:46,342 - INFO - Fum/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:46,344 - INFO - rxn00250_c0< not needed:1.0
2026-01-13 19:56:46,345 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:46,353 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860f7f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:56:46,354 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860f7f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:46,358 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:46,384 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:47,109 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,127 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,138 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,149 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,161 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,172 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,183 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,193 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,202 - INFO - cpd00159 not found in model!
2026-01-13 19:56:47,203 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:56:47,206 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,228 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,239 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,250 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,260 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,271 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,281 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,292 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,303 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,313 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,322 - INFO - cpd00159 not found in model!
2026-01-13 19:56:47,323 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:56:47,325 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,336 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,346 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,357 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,368 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,376 - INFO - cpd00209 not found in model!
2026-01-13 19:56:47,377 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:56:47,380 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,389 - INFO - cpd00418 not found in model!
2026-01-13 19:56:47,390 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:56:47,393 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,403 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,411 - INFO - cpd00209 not found in model!
2026-01-13 19:56:47,412 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:56:47,415 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,423 - INFO - cpd00418 not found in model!
2026-01-13 19:56:47,424 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:56:47,427 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,437 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,445 - INFO - cpd00209 not found in model!
2026-01-13 19:56:47,446 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:56:47,449 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,457 - INFO - cpd00418 not found in model!
2026-01-13 19:56:47,458 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:56:47,461 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,469 - INFO - cpd08021 not found in model!
2026-01-13 19:56:47,470 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:56:47,473 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,481 - INFO - cpd00811 not found in model!
2026-01-13 19:56:47,482 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:56:47,485 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,493 - INFO - cpd08021 not found in model!
2026-01-13 19:56:47,494 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:56:47,497 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,505 - INFO - cpd00811 not found in model!
2026-01-13 19:56:47,506 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:56:47,508 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,519 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,529 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,538 - INFO - cpd11640 not found in model!
2026-01-13 19:56:47,538 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:47,541 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,549 - INFO - cpd11640 not found in model!
2026-01-13 19:56:47,550 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:47,553 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,561 - INFO - cpd11640 not found in model!
2026-01-13 19:56:47,562 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:47,565 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,573 - INFO - cpd00159 not found in model!
2026-01-13 19:56:47,574 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:56:47,575 - INFO - cpd11640 not found in model!
2026-01-13 19:56:47,575 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:47,578 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,588 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,597 - INFO - cpd00159 not found in model!
2026-01-13 19:56:47,597 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:56:47,601 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,609 - INFO - cpd11640 not found in model!
2026-01-13 19:56:47,610 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:47,613 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,624 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,632 - INFO - cpd11632 not found in model!
2026-01-13 19:56:47,634 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:56:47,637 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,645 - INFO - cpd08701 not found in model!
2026-01-13 19:56:47,646 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:56:47,647 - INFO - cpd01024 not found in model!
2026-01-13 19:56:47,648 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:56:47,651 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,659 - INFO - cpd01024 not found in model!
2026-01-13 19:56:47,660 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:56:47,663 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,674 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,682 - INFO - cpd11640 not found in model!
2026-01-13 19:56:47,683 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:47,686 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,695 - INFO - cpd11640 not found in model!
2026-01-13 19:56:47,696 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:47,696 - INFO - cpd00187 not found in model!
2026-01-13 19:56:47,697 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:56:47,700 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,709 - INFO - cpd11640 not found in model!
2026-01-13 19:56:47,710 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:47,711 - INFO - cpd00425 not found in model!
2026-01-13 19:56:47,712 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:56:47,715 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:56:47,723 - INFO - cpd11640 not found in model!
2026-01-13 19:56:47,724 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:56:47,725 - INFO - cpd00441 not found in model!
2026-01-13 19:56:47,726 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:56:47,729 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:49,530 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 19:56:49,553 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:56:49,582 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c197cd0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:49,584 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:49,585 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:49,586 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:56:49,587 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:49,592 - INFO - cpd08021 not found in model!
2026-01-13 19:56:49,593 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:56:49,597 - INFO - Glc.DMSO/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:49,598 - INFO - Glc.DMSO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:49,599 - INFO - Glc.DMSO/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:49,604 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c197cd0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:49,605 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c197cd0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:49,608 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:49,629 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:56:49,656 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c197d90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:49,658 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:49,659 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:49,660 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:56:49,661 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:49,666 - INFO - cpd00811 not found in model!
2026-01-13 19:56:49,667 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:56:49,670 - INFO - Glc.TMAO/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:49,671 - INFO - Glc.TMAO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:49,673 - INFO - Glc.TMAO/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:49,678 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c197d90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:49,679 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c197d90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:49,683 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:56:49,703 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:49,822 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 19:56:49,843 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:50,166 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:56:50,182 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 19:56:50,191 - INFO - cpd00187 not found in model!
2026-01-13 19:56:50,192 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:50,192 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:56:50,199 - INFO - cpd00187 not found in model!
2026-01-13 19:56:50,200 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:56:50,210 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:50,532 - WARNING - No gapfilling solution found before filtering for mal-L activating rxn00062_c0

Removing ungapfillable media mal-L

2026-01-13 19:56:50,539 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:56:50,563 - INFO - Objective with gapfill database:19.125000000000007; min objective:0.01
2026-01-13 19:56:50,565 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:50,594 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn01476_c0': '>', 'rxn00157_c0': '<', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5034f850>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:50,597 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:56:50,598 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:56:50,598 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:56:50,599 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:56:50,600 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:56:50,601 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:56:50,602 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new']]
2026-01-13 19:56:50,611 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:56:50,612 - INFO - Glyc.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:56:50,613 - INFO - Glyc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:2
2026-01-13 19:56:50,614 - INFO - Glyc.O2/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:2
2026-01-13 19:56:50,615 - INFO - Glyc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:2
2026-01-13 19:56:50,616 - INFO - Glyc.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:56:50,622 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5034f850>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn01476_c0': '>', 'rxn00157_c0': '<', 'rxn03884_c0': '>'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:56:50,622 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn05581_c0': '<', 'rxn00256_c0': '<', 'rxn01476_c0': '>', 'rxn00157_c0': '<', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5034f850>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:50,626 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new']]
2026-01-13 19:56:50,650 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:56:50,682 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn00157_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b965db0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:56:50,684 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:56:50,685 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:56:50,686 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:56:50,686 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new']]
2026-01-13 19:56:50,695 - INFO - Fum.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:3
2026-01-13 19:56:50,696 - INFO - Fum.O2/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:3
2026-01-13 19:56:50,697 - INFO - Fum.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:3
2026-01-13 19:56:50,703 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b965db0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'rxn00256_c0': '<', 'rxn00157_c0': '<'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:56:50,704 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn00157_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b965db0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:56:50,708 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new']]
2026-01-13 19:56:50,731 - INFO - Objective with gapfill database:18.25000000000002; min objective:0.01
2026-01-13 19:56:50,760 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn09269_c0': '>', 'rxn00157_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b965f30>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:50,762 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:56:50,763 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:56:50,764 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:56:50,765 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:56:50,765 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:56:50,773 - INFO - Succ.O2/rxn00062_c0:rxn00256_c0< needed:1.0000000000000002 with min obj:2
2026-01-13 19:56:50,775 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:56:50,776 - INFO - Succ.O2/rxn00062_c0:rxn00157_c0< needed:1.0000000000000002 with min obj:2
2026-01-13 19:56:50,777 - INFO - Succ.O2/rxn00062_c0:rxn00285_c0< needed:1.0 with min obj:2
2026-01-13 19:56:50,783 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b965f30>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn00256_c0': '<', 'rxn09269_c0': '>', 'rxn00157_c0': '<'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:56:50,784 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn09269_c0': '>', 'rxn00157_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b965f30>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:50,789 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:56:50,812 - INFO - Objective with gapfill database:16.25000000000002; min objective:0.01
2026-01-13 19:56:50,842 - INFO - Initial solution: {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn00544_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b966440>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:50,844 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:56:50,846 - INFO - integrating rxn: rxn00544_c0
2026-01-13 19:56:50,846 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:56:50,848 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new']]
2026-01-13 19:56:50,856 - INFO - LLac.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:56:50,857 - INFO - LLac.O2/rxn00062_c0:rxn00544_c0< needed:0.0 with min obj:2
2026-01-13 19:56:50,858 - INFO - LLac.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:56:50,864 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b966440>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn00256_c0': '<', 'rxn00544_c0': '<'}, 'reversed': {'rxn00285_c0': '<'}}
2026-01-13 19:56:50,864 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00285_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn00544_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b966440>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:50,869 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new']]
2026-01-13 19:56:50,892 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:50,949 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 19:56:50,971 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:51,147 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:56:51,160 - INFO - cpd11632 not found in model!
2026-01-13 19:56:51,161 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:56:51,175 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:53,715 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:56:53,725 - INFO - cpd01024 not found in model!
2026-01-13 19:56:53,726 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:56:53,738 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:54,250 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:56:54,282 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:56,101 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:56:56,128 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:56,259 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:56:56,284 - INFO - Objective with gapfill database:19.124999999999986; min objective:0.01
2026-01-13 19:56:56,318 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn08557_c0': '>', 'rxn00779_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c7340>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:56,321 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:56:56,322 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:56:56,324 - INFO - integrating rxn: rxn08557_c0
2026-01-13 19:56:56,326 - INFO - integrating rxn: rxn00779_c0
2026-01-13 19:56:56,327 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:56:56,328 - INFO - Full solution: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00779_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:56:56,345 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:56:56,346 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:56:56,348 - INFO - Glyc.O2/rxn00062_c0:rxn08557_c0> needed:0.0 with min obj:2
2026-01-13 19:56:56,349 - INFO - rxn00779_c0> not needed:6.0
2026-01-13 19:56:56,351 - INFO - rxn00250_c0< not needed:6.0
2026-01-13 19:56:56,354 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c7340>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn08557_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:56,354 - INFO - Unneeded: [['rxn00779_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn08557_c0': '>', 'rxn00779_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c7340>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:56,359 - INFO - Cumulative: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new']]
2026-01-13 19:56:56,386 - INFO - Objective with gapfill database:18.250000000000018; min objective:0.01
2026-01-13 19:56:56,423 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn09269_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c43d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:56,426 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:56:56,427 - INFO - Full solution: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:56:56,435 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:56:56,441 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c43d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn09269_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:56,442 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn09269_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c43d0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:56,447 - INFO - Cumulative: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:56:56,471 - INFO - Objective with gapfill database:16.249999999999996; min objective:0.01
2026-01-13 19:56:56,504 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c49a0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:56:56,506 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:56:56,508 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:56:56,509 - INFO - Full solution: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 19:56:56,517 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 19:56:56,518 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 19:56:56,524 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c49a0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:56,525 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c49a0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:56:56,529 - INFO - Cumulative: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 19:56:56,554 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:56,868 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0
2026-01-13 19:56:56,889 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:56:56,917 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c60ab60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:56,919 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:56:56,919 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:56,920 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:56:56,921 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:56,922 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:56:56,922 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:56:56,923 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:56:56,924 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:56,925 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:56,929 - INFO - cpd00159 not found in model!
2026-01-13 19:56:56,930 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:56:56,933 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:56,934 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:56,935 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:56,936 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:56,937 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:56,938 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:56,938 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:56,939 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:56,944 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c60ab60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:56,946 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c60ab60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:56,949 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:56,968 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:56:56,995 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c60b010>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:56:56,998 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:56:56,999 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:56:57,000 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:56:57,001 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:56:57,002 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:56:57,003 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:56:57,004 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:56:57,005 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:56:57,006 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:57,010 - INFO - cpd00159 not found in model!
2026-01-13 19:56:57,011 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:56:57,014 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:56:57,015 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:56:57,015 - INFO - LLac.SO4/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:57,016 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:57,017 - INFO - LLac.SO4/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:57,019 - INFO - LLac.SO4/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:56:57,020 - INFO - LLac.SO4/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:57,021 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:56:57,026 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c60b010>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:56:57,027 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa5c60b010>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:56:57,030 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01115_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:56:57,051 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:58,509 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:56:58,520 - INFO - cpd01024 not found in model!
2026-01-13 19:56:58,521 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:56:58,534 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:58,641 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:56:58,671 - INFO - Objective with gapfill database:34.49999999999998; min objective:0.01
2026-01-13 19:56:58,705 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00506_c0': '>', 'rxn00083_c0': '>', 'rxn00544_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8c9708b0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:56:58,708 - INFO - integrating rxn: rxn00506_c0
2026-01-13 19:56:58,710 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:56:58,711 - INFO - integrating rxn: rxn00544_c0
2026-01-13 19:56:58,712 - INFO - Full solution: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new']]
2026-01-13 19:56:58,741 - INFO - Glc.O2/rxn00062_c0:rxn00506_c0> needed:0.0 with min obj:5
2026-01-13 19:56:58,742 - INFO - Glc.O2/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:5
2026-01-13 19:56:58,744 - INFO - Glc.O2/rxn00062_c0:rxn00544_c0< needed:0.0 with min obj:5
2026-01-13 19:56:58,746 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8c9708b0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn00506_c0': '>', 'rxn00083_c0': '>', 'rxn00544_c0': '<'}, 'reversed': {}}
2026-01-13 19:56:58,747 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn00506_c0': '>', 'rxn00083_c0': '>', 'rxn00544_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa8c9708b0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:56:58,752 - INFO - Cumulative: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new']]
2026-01-13 19:56:58,779 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:59,366 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:56:59,396 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:56:59,508 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:56:59,528 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:56:59,536 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:56:59,552 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:01,827 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:57:01,849 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:57:01,879 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe9600>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:01,882 - INFO - integrating rxn: EX_cpd00047_e0
2026-01-13 19:57:01,883 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:01,885 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:57:01,885 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:57:01,887 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:57:01,888 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:57:01,889 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:01,891 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:57:01,892 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:57:01,893 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:01,894 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new']]
2026-01-13 19:57:01,901 - INFO - Glyc/rxn00062_c0:EX_cpd00047_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:01,902 - INFO - Glyc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:01,904 - INFO - Glyc/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:0.01
2026-01-13 19:57:01,905 - INFO - Glyc/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:01,906 - INFO - Glyc/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:01,907 - INFO - Glyc/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:01,908 - INFO - Glyc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:01,909 - INFO - Glyc/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:01,910 - INFO - Glyc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:01,911 - INFO - Glyc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:01,916 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe9600>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00251_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:57:01,917 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe9600>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:01,921 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new']]
2026-01-13 19:57:01,943 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:57:01,962 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 19:57:01,971 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe9720>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:01,973 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:01,974 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:01,975 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:01,976 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:01,977 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:57:01,978 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new']]
2026-01-13 19:57:01,985 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:01,985 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:01,986 - INFO - rxn07191_c0< not needed:0.9999999999999998
2026-01-13 19:57:01,988 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:01,989 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:01,990 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:01,996 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe9720>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn05553_c0': '>'}, 'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}}
2026-01-13 19:57:01,997 - INFO - Unneeded: [['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe9720>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:02,000 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new']]
2026-01-13 19:57:02,022 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:02,092 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 19:57:02,120 - INFO - Objective with gapfill database:34.499999999999986; min objective:0.01
2026-01-13 19:57:02,152 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00027_e0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn05226_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa4b3fe260>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 19:57:02,155 - INFO - integrating rxn: EX_cpd00027_e0
2026-01-13 19:57:02,157 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:57:02,159 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:57:02,160 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:02,162 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:57:02,164 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:57:02,165 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:57:02,166 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:02,167 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:57:02,184 - INFO - Glc.O2/rxn00062_c0:EX_cpd00027_e0< needed:0.0 with min obj:5
2026-01-13 19:57:02,185 - INFO - Glc.O2/rxn00062_c0:rxn00336_c0> needed:2.0 with min obj:5
2026-01-13 19:57:02,186 - INFO - Glc.O2/rxn00062_c0:rxn00330_c0< needed:2.0 with min obj:5
2026-01-13 19:57:02,187 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:2.0 with min obj:5
2026-01-13 19:57:02,188 - INFO - Glc.O2/rxn00062_c0:rxn08527_c0< needed:2.0 with min obj:5
2026-01-13 19:57:02,189 - INFO - Glc.O2/rxn00062_c0:rxn05226_c0> needed:0.0 with min obj:5
2026-01-13 19:57:02,190 - INFO - Glc.O2/rxn00062_c0:rxn00799_c0< needed:2.0 with min obj:5
2026-01-13 19:57:02,192 - INFO - Glc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:5
2026-01-13 19:57:02,194 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa4b3fe260>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'EX_cpd00027_e0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn05226_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:57:02,195 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00027_e0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn05226_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa4b3fe260>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 19:57:02,199 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:57:02,224 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:02,470 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:57:02,487 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 19:57:02,496 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:57:02,527 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860fe20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:02,530 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:57:02,531 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:02,531 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:57:02,532 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:02,533 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:02,534 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:57:02,542 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:57:02,544 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:02,545 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:02,546 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:02,547 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:02,553 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860fe20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:57:02,554 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2860fe20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:02,558 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:57:02,582 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:02,938 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:02,957 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:03,008 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:57:03,035 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:03,038 - INFO -   Saved gapfilled model: gapfilled_models2/Gallicola.1_gf.xml
2026-01-13 19:57:03,043 - INFO -   Total reactions added: 306
2026-01-13 19:57:03,228 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:03,507 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:57:03,540 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:57:03,643 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:04,058 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:57:04,092 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:04,507 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,546 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,568 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,589 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,611 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,633 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,654 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,676 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:04,698 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,719 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,741 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,742 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 19:57:04,764 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,767 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:04,793 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,814 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,836 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,857 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,878 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,900 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,921 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,942 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,964 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:04,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,010 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,033 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,056 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,077 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,098 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,124 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,146 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,167 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,189 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,211 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,232 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,254 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,275 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,296 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,318 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,339 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,361 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,383 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,404 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,429 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,453 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,475 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,498 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,519 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,537 - INFO - cpd11632 not found in model!
2026-01-13 19:57:05,539 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:57:05,544 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,562 - INFO - cpd01024 not found in model!
2026-01-13 19:57:05,563 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:05,568 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,586 - INFO - cpd01024 not found in model!
2026-01-13 19:57:05,586 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:05,591 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,612 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,634 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,651 - INFO - cpd00187 not found in model!
2026-01-13 19:57:05,652 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:57:05,657 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,679 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:05,700 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:06,074 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:57:06,100 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:06,501 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 19:57:06,523 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:57:06,559 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa32473c10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:06,562 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:06,563 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:57:06,564 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:06,565 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:57:06,566 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:57:06,567 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:06,568 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:57:06,570 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:06,571 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:57:06,571 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:57:06,576 - INFO - cpd08021 not found in model!
2026-01-13 19:57:06,577 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:57:06,581 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:06,582 - INFO - rxn05938_c0< not needed:1.5
2026-01-13 19:57:06,583 - INFO - rxn07191_c0< not needed:1.5
2026-01-13 19:57:06,584 - INFO - Glc.DMSO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:06,585 - INFO - Glc.DMSO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:06,587 - INFO - rxn00250_c0< not needed:0.5
2026-01-13 19:57:06,588 - INFO - Glc.DMSO/rxn00062_c0:rxn05226_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:06,589 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:06,590 - INFO - Glc.DMSO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:06,595 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa32473c10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:57:06,596 - INFO - Unneeded: [['rxn05938_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None], ['rxn00250_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa32473c10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:06,601 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:57:06,623 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:57:06,653 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa32473eb0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:06,655 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:06,656 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:57:06,657 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:06,658 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:57:06,658 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:57:06,659 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:06,660 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:57:06,661 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:06,662 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:57:06,663 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:57:06,667 - INFO - cpd00811 not found in model!
2026-01-13 19:57:06,668 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:57:06,672 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:06,673 - INFO - rxn05938_c0< not needed:1.5
2026-01-13 19:57:06,674 - INFO - rxn07191_c0< not needed:1.5
2026-01-13 19:57:06,675 - INFO - Glc.TMAO/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:06,676 - INFO - Glc.TMAO/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:06,677 - INFO - rxn00250_c0< not needed:0.5
2026-01-13 19:57:06,678 - INFO - Glc.TMAO/rxn00062_c0:rxn05226_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:06,679 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:06,680 - INFO - Glc.TMAO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:06,686 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa32473eb0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 19:57:06,687 - INFO - Unneeded: [['rxn05938_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None], ['rxn00250_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00250_c0': '<', 'rxn05226_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa32473eb0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:06,691 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 19:57:06,713 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:57:07,481 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:08,229 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:57:08,257 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,259 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:57:08,276 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,283 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:57:08,290 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,303 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,307 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:08,316 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,329 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,342 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,355 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,367 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,378 - INFO - cpd00221 not found in model!
2026-01-13 19:57:08,378 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:57:08,382 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,395 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,408 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,421 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,433 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,446 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,459 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,471 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,484 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,497 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,509 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,520 - INFO - cpd00221 not found in model!
2026-01-13 19:57:08,521 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 19:57:08,524 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,537 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,549 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,562 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,574 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,585 - INFO - cpd00418 not found in model!
2026-01-13 19:57:08,586 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:57:08,590 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,602 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,615 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,614 - INFO -   Saved gapfilled model: gapfilled_models2/Firmicutes.13_gf.xml
2026-01-13 19:57:08,621 - INFO -   Total reactions added: 92
2026-01-13 19:57:08,625 - INFO - cpd00418 not found in model!
2026-01-13 19:57:08,626 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:57:08,630 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,643 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,655 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:08,665 - INFO - cpd00418 not found in model!

2026-01-13 19:57:08,666 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:57:08,670 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,680 - INFO - cpd08021 not found in model!
2026-01-13 19:57:08,681 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:57:08,684 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,694 - INFO - cpd00811 not found in model!
2026-01-13 19:57:08,695 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:57:08,698 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,709 - INFO - cpd08021 not found in model!
2026-01-13 19:57:08,709 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:57:08,712 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,717 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:57:08,722 - INFO - cpd00811 not found in model!
2026-01-13 19:57:08,723 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:57:08,727 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,739 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,745 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:57:08,752 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,768 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,777 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00027_e0': '<', 'rxn01106_c0': '<', 'rxn01476_c0': '>', 'rxn05226_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b966b60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:08,778 - INFO - integrating rxn: EX_cpd00027_e0
2026-01-13 19:57:08,779 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:57:08,780 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:57:08,781 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,781 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:57:08,782 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:57:08,783 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new']]
2026-01-13 19:57:08,792 - INFO - Glc/rxn00062_c0:EX_cpd00027_e0< needed:0.0 with min obj:0.01
2026-01-13 19:57:08,793 - INFO - Glc/rxn00062_c0:rxn01106_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:08,794 - INFO - Glc/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:08,794 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,795 - INFO - Glc/rxn00062_c0:rxn05226_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:08,796 - INFO - Glc/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:08,802 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b966b60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00027_e0': '<', 'rxn01106_c0': '<', 'rxn01476_c0': '>', 'rxn05226_c0': '>', 'rxn03884_c0': '>'}, 'reversed': {}}
2026-01-13 19:57:08,802 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00027_e0': '<', 'rxn01106_c0': '<', 'rxn01476_c0': '>', 'rxn05226_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b966b60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:08,807 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,807 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new']]
2026-01-13 19:57:08,820 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,831 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:08,832 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,845 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,858 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,868 - INFO - cpd11632 not found in model!
2026-01-13 19:57:08,869 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:57:08,873 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,883 - INFO - cpd08701 not found in model!
2026-01-13 19:57:08,884 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:57:08,886 - INFO - cpd01024 not found in model!
2026-01-13 19:57:08,886 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:08,890 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,900 - INFO - cpd01024 not found in model!
2026-01-13 19:57:08,901 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:08,904 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,917 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,929 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,940 - INFO - cpd00187 not found in model!
2026-01-13 19:57:08,940 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:57:08,944 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,955 - INFO - cpd00425 not found in model!
2026-01-13 19:57:08,955 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:57:08,959 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:08,969 - INFO - cpd00441 not found in model!
2026-01-13 19:57:08,970 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:57:08,973 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:09,047 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:09,742 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 19:57:09,755 - INFO - cpd08701 not found in model!
2026-01-13 19:57:09,756 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:57:09,757 - INFO - cpd01024 not found in model!
2026-01-13 19:57:09,758 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:09,763 - INFO - cpd08701 not found in model!
2026-01-13 19:57:09,764 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:57:09,765 - INFO - cpd01024 not found in model!
2026-01-13 19:57:09,766 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:09,775 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:09,893 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:57:09,949 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:57:09,982 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:10,449 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 19:57:10,483 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 19:57:10,513 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a6256c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:10,516 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:10,517 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:10,519 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:57:10,520 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:10,521 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:10,522 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:57:10,523 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:57:10,523 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:57:10,533 - INFO - Fum/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:10,534 - INFO - Fum/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:10,535 - INFO - Fum/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:10,536 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:10,538 - INFO - Fum/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:10,539 - INFO - Fum/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:10,540 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:10,546 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a6256c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:57:10,547 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00248_c0': '>', 'rxn00250_c0': '<', 'rxn05553_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a6256c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:10,550 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:57:10,574 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:12,742 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:57:12,774 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:13,068 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:57:13,100 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:13,383 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:57:13,395 - INFO - cpd01024 not found in model!
2026-01-13 19:57:13,396 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:13,408 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:13,811 - WARNING - No gapfilling solution found for Trimethylamine.H2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:14,100 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:57:14,121 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:14,152 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:57:14,185 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:14,392 - INFO - Loading model: HN-HF0106.2
2026-01-13 19:57:14,774 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:14,846 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:57:14,871 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:15,547 - INFO -   Loading template...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:15,977 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:57:16,001 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:16,004 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:16,011 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:16,101 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0
2026-01-13 19:57:16,120 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:57:16,147 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b078e0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:16,149 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:57:16,150 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:16,151 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:57:16,152 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:57:16,153 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:16,154 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:57:16,155 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:57:16,155 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:57:16,156 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:16,157 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:57:16,160 - INFO - cpd00159 not found in model!
2026-01-13 19:57:16,161 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:57:16,162 - INFO - cpd11640 not found in model!
2026-01-13 19:57:16,162 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:16,165 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,166 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:16,167 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:16,168 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,169 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,170 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,171 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,172 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:16,173 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:16,177 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b078e0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:57:16,178 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b078e0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:16,183 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:57:16,203 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:57:16,229 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b07d90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:16,231 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:57:16,232 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:16,233 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:57:16,234 - INFO - integrating rxn: rxn05938_c0
2026-01-13 19:57:16,235 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:16,236 - INFO - integrating rxn: rxn00543_c0
2026-01-13 19:57:16,237 - INFO - integrating rxn: rxn00171_c0
2026-01-13 19:57:16,238 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:57:16,239 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:16,240 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:57:16,244 - INFO - cpd00159 not found in model!
2026-01-13 19:57:16,245 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:57:16,248 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,249 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:16,251 - INFO - LLac.SO4/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:16,252 - INFO - LLac.SO4/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,253 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,254 - INFO - LLac.SO4/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,255 - INFO - LLac.SO4/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:16,256 - INFO - LLac.SO4/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:16,257 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:16,261 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b07d90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:57:16,262 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa56b07d90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:16,267 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 19:57:16,287 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:16,605 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:57:16,636 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:17,966 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:17,994 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:18,059 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:57:18,092 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:18,288 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:57:18,316 - INFO - Objective with gapfill database:19.124999999999986; min objective:0.01
2026-01-13 19:57:18,349 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn05581_c0': '<', 'rxn00324_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c61a0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:57:18,351 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:57:18,353 - INFO - integrating rxn: rxn00324_c0
2026-01-13 19:57:18,354 - INFO - Full solution: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new']]
2026-01-13 19:57:18,365 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:57:18,366 - INFO - Glyc.O2/rxn00062_c0:rxn00324_c0< needed:0.0 with min obj:2
2026-01-13 19:57:18,374 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c61a0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn05581_c0': '<', 'rxn00324_c0': '<'}, 'reversed': {}}
2026-01-13 19:57:18,375 - INFO - Unneeded: []

Adding gapfillingNeither carbon consumption nor oxygen consumption are defined in
{'reversed': {}, 'new': {'rxn05581_c0': '<', 'rxn00324_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c61a0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:57:18,380 - INFO - Cumulative: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new']]
2026-01-13 19:57:18,407 - INFO - Objective with gapfill database:17.499999999999996; min objective:0.01
2026-01-13 19:57:18,438 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn07191_c0': '<', 'rxn00506_c0': '>', 'rxn00248_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c40a0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:57:18,441 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:18,442 - INFO - integrating rxn: rxn00506_c0
2026-01-13 19:57:18,444 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:57:18,445 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:18,446 - INFO - Full solution: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:57:18,456 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:57:18,457 - INFO - Fum.O2/rxn00062_c0:rxn00506_c0> needed:0.0 with min obj:3
2026-01-13 19:57:18,458 - INFO - Fum.O2/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:3
2026-01-13 19:57:18,459 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:57:18,467 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c40a0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'rxn07191_c0': '<', 'rxn00506_c0': '>', 'rxn00248_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:57:18,468 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn07191_c0': '<', 'rxn00506_c0': '>', 'rxn00248_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c40a0>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:57:18,471 - INFO - Cumulative: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:57:18,497 - INFO - Objective with gapfill database:19.124999999999993; min objective:0.01
2026-01-13 19:57:18,528 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn00083_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn08094_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c4460>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:57:18,531 - INFO - integrating rxn: rxn00256_c0
2026-01-13 19:57:18,532 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:18,534 - INFO - integrating rxn: rxn00285_c0
2026-01-13 19:57:18,536 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:57:18,537 - INFO - integrating rxn: rxn00083_c0
2026-01-13 19:57:18,537 - INFO - integrating rxn: rxn00248_c0
2026-01-13 19:57:18,539 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:57:18,541 - INFO - integrating rxn: rxn08094_c0
2026-01-13 19:57:18,541 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:18,541 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,543 - INFO - Full solution: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new']]
2026-01-13 19:57:18,553 - INFO - Succ.O2/rxn00062_c0:rxn00256_c0< needed:0.0 with min obj:2
2026-01-13 19:57:18,554 - INFO - Succ.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:57:18,555 - INFO - Succ.O2/rxn00062_c0:rxn00285_c0< needed:0.0 with min obj:2
2026-01-13 19:57:18,557 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:57:18,556 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,558 - INFO - Succ.O2/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:2
2026-01-13 19:57:18,559 - INFO - rxn00248_c0> not needed:8.0
2026-01-13 19:57:18,561 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:57:18,562 - INFO - Succ.O2/rxn00062_c0:rxn08094_c0> needed:0.0 with min obj:2
2026-01-13 19:57:18,563 - INFO - rxn00250_c0< not needed:8.0
2026-01-13 19:57:18,568 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,570 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c4460>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn00256_c0': '<', 'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn00083_c0': '>', 'rxn09269_c0': '>', 'rxn08094_c0': '>'}, 'reversed': {}}
2026-01-13 19:57:18,571 - INFO - Unneeded: [['rxn00248_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00256_c0': '<', 'rxn07191_c0': '<', 'rxn00285_c0': '<', 'rxn08527_c0': '<', 'rxn00083_c0': '>', 'rxn00248_c0': '>', 'rxn09269_c0': '>', 'rxn08094_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c4460>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:57:18,574 - INFO - Cumulative: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new']]
2026-01-13 19:57:18,580 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,591 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,601 - INFO - Objective with gapfill database:16.25; min objective:0.01
2026-01-13 19:57:18,601 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,612 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,623 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,631 - INFO - cpd00159 not found in model!
2026-01-13 19:57:18,632 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:57:18,632 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn07191_c0': '<', 'rxn00506_c0': '>', 'rxn00499_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c48e0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:57:18,634 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:18,635 - INFO - integrating rxn: rxn00506_c0
2026-01-13 19:57:18,636 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,637 - INFO - integrating rxn: rxn00499_c0
2026-01-13 19:57:18,638 - INFO - Full solution: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:57:18,646 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,648 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:57:18,649 - INFO - LLac.O2/rxn00062_c0:rxn00506_c0> needed:0.0 with min obj:2
2026-01-13 19:57:18,650 - INFO - LLac.O2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:2
2026-01-13 19:57:18,657 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,658 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c48e0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn07191_c0': '<', 'rxn00506_c0': '>', 'rxn00499_c0': '>'}, 'reversed': {}}
2026-01-13 19:57:18,659 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn07191_c0': '<', 'rxn00506_c0': '>', 'rxn00499_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c48e0>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:57:18,662 - INFO - Cumulative: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new']]
2026-01-13 19:57:18,668 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,678 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,688 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:18,688 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,700 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,711 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,721 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,731 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,742 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:18,750 - INFO - cpd00159 not found in model!

2026-01-13 19:57:18,751 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:57:18,756 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,769 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,780 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,790 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,798 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:57:18,801 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,810 - INFO - cpd00209 not found in model!
2026-01-13 19:57:18,811 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:57:18,813 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,822 - INFO - cpd00418 not found in model!
2026-01-13 19:57:18,823 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:57:18,824 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:18,826 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,837 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,845 - INFO - cpd00209 not found in model!
2026-01-13 19:57:18,846 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:57:18,849 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,857 - INFO - cpd00418 not found in model!
2026-01-13 19:57:18,858 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:57:18,861 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,872 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,880 - INFO - cpd00209 not found in model!
2026-01-13 19:57:18,881 - INFO - Media compound: cpd00209 not found in model.
2026-01-13 19:57:18,884 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,893 - INFO - cpd00418 not found in model!
2026-01-13 19:57:18,894 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 19:57:18,897 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:18,906 - INFO - cpd08021 not found in model!
2026-01-13 19:57:18,907 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:57:18,910 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,919 - INFO - cpd00811 not found in model!
2026-01-13 19:57:18,920 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:57:18,922 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,931 - INFO - cpd08021 not found in model!
2026-01-13 19:57:18,932 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:57:18,935 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,944 - INFO - cpd00811 not found in model!
2026-01-13 19:57:18,944 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:57:18,948 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,951 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:57:18,958 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,969 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,974 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:57:18,977 - INFO - cpd11640 not found in model!
2026-01-13 19:57:18,978 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:18,981 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:18,990 - INFO - cpd11640 not found in model!
2026-01-13 19:57:18,991 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:18,994 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,002 - INFO - cpd11640 not found in model!
2026-01-13 19:57:19,003 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe9de0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:19,003 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:19,006 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:57:19,007 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,007 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:19,008 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:57:19,009 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:19,010 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:19,010 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new']]
2026-01-13 19:57:19,015 - INFO - cpd00159 not found in model!
2026-01-13 19:57:19,016 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:57:19,017 - INFO - cpd11640 not found in model!
2026-01-13 19:57:19,018 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:19,019 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:57:19,020 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:19,021 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,021 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:19,022 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:19,023 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:19,029 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe9de0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:57:19,029 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1cfe9de0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:19,032 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 19:57:19,033 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00173_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new']]
2026-01-13 19:57:19,040 - INFO - cpd00159 not found in model!
2026-01-13 19:57:19,041 - INFO - Media compound: cpd00159 not found in model.
2026-01-13 19:57:19,044 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,052 - INFO - cpd11640 not found in model!
2026-01-13 19:57:19,053 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:19,056 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,056 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:19,066 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,075 - INFO - cpd11632 not found in model!
2026-01-13 19:57:19,076 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:57:19,079 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,088 - INFO - cpd08701 not found in model!
2026-01-13 19:57:19,089 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:57:19,089 - INFO - cpd01024 not found in model!
2026-01-13 19:57:19,090 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:19,093 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,101 - INFO - cpd01024 not found in model!
2026-01-13 19:57:19,102 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:19,105 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,115 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,124 - INFO - cpd11640 not found in model!
2026-01-13 19:57:19,125 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:19,127 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,136 - INFO - cpd11640 not found in model!
2026-01-13 19:57:19,136 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:19,137 - INFO - cpd00187 not found in model!
2026-01-13 19:57:19,138 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 19:57:19,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,149 - INFO - cpd11640 not found in model!
2026-01-13 19:57:19,150 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:19,150 - INFO - cpd00425 not found in model!
2026-01-13 19:57:19,151 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:57:19,154 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 19:57:19,163 - INFO - cpd11640 not found in model!
2026-01-13 19:57:19,164 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:57:19,165 - INFO - cpd00441 not found in model!
2026-01-13 19:57:19,166 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 19:57:19,169 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:19,418 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:57:19,445 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:21,123 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 19:57:21,150 - INFO - Objective with gapfill database:19.125000000000018; min objective:0.01
2026-01-13 19:57:21,185 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d32920>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:57:21,188 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 19:57:21,190 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:57:21,191 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:57:21,192 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:57:21,193 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:21,194 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:57:21,195 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:57:21,196 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:21,197 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new']]
2026-01-13 19:57:21,207 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 19:57:21,208 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,209 - INFO - Glyc.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:57:21,210 - INFO - Glyc.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,212 - INFO - Glyc.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,213 - INFO - Glyc.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,214 - INFO - Glyc.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,215 - INFO - Glyc.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,223 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d32920>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:57:21,223 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<', 'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d32920>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:57:21,228 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new']]
2026-01-13 19:57:21,255 - INFO - Objective with gapfill database:17.500000000000004; min objective:0.01
2026-01-13 19:57:21,289 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d30280>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 19:57:21,290 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:57:21,291 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:57:21,293 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:21,294 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:57:21,295 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:57:21,296 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:21,297 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new']]
2026-01-13 19:57:21,307 - INFO - Fum.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:3
2026-01-13 19:57:21,309 - INFO - Fum.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:3
2026-01-13 19:57:21,310 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:3
2026-01-13 19:57:21,312 - INFO - Fum.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:3
2026-01-13 19:57:21,313 - INFO - Fum.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:3
2026-01-13 19:57:21,314 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:3
2026-01-13 19:57:21,321 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d30280>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:57:21,323 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d30280>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 19:57:21,328 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new']]
2026-01-13 19:57:21,354 - INFO - Objective with gapfill database:19.125; min objective:0.01
2026-01-13 19:57:21,387 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d32680>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:57:21,389 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:57:21,391 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:57:21,392 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:21,393 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:57:21,395 - INFO - integrating rxn: rxn09269_c0
2026-01-13 19:57:21,396 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:57:21,398 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:21,399 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:57:21,408 - INFO - rxn00336_c0> not needed:2.0
2026-01-13 19:57:21,410 - INFO - rxn00330_c0< not needed:2.0
2026-01-13 19:57:21,411 - INFO - rxn07191_c0< not needed:2.0
2026-01-13 19:57:21,412 - INFO - Succ.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,414 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 19:57:21,415 - INFO - Succ.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,416 - INFO - Succ.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,423 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d32680>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:57:21,425 - INFO - Unneeded: [['rxn00336_c0', '>', 'new', 100, None], ['rxn00330_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn09269_c0': '>', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d32680>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:57:21,429 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:57:21,456 - INFO - Objective with gapfill database:16.249999999999993; min objective:0.01
2026-01-13 19:57:21,489 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d30880>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 19:57:21,491 - INFO - integrating rxn: rxn00336_c0
2026-01-13 19:57:21,492 - INFO - integrating rxn: rxn00330_c0
2026-01-13 19:57:21,493 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:21,494 - INFO - integrating rxn: rxn08527_c0
2026-01-13 19:57:21,496 - INFO - integrating rxn: rxn00799_c0
2026-01-13 19:57:21,497 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:21,498 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:57:21,508 - INFO - LLac.O2/rxn00062_c0:rxn00336_c0> needed:0.0 with min obj:2
2026-01-13 19:57:21,509 - INFO - LLac.O2/rxn00062_c0:rxn00330_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,511 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,513 - INFO - LLac.O2/rxn00062_c0:rxn08527_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,514 - INFO - LLac.O2/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,516 - INFO - LLac.O2/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:2
2026-01-13 19:57:21,523 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d30880>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:57:21,523 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'rxn00336_c0': '>', 'rxn00330_c0': '<', 'rxn07191_c0': '<', 'rxn08527_c0': '<', 'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d30880>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 19:57:21,528 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:57:21,555 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:22,516 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:57:22,540 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:22,661 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 19:57:22,682 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:25,303 - WARNING - No gapfilling solution found before filtering for For.NO3 activating rxn00062_c0

Removing ungapfillable media For.NO3

2026-01-13 19:57:25,335 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:26,630 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 19:57:26,656 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:57:26,686 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a7c1d20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:26,689 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:57:26,690 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:26,691 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:57:26,692 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:57:26,693 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:26,693 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:57:26,702 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:57:26,703 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:26,704 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:26,705 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:26,706 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:26,713 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a7c1d20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:57:26,714 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2a7c1d20>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:26,719 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:57:26,744 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:26,844 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 19:57:26,869 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 19:57:26,901 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'rxn05581_c0': '<', 'rxn01106_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b967340>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:26,904 - INFO - integrating rxn: EX_cpd00047_e0
2026-01-13 19:57:26,906 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:57:26,907 - INFO - integrating rxn: rxn05581_c0
2026-01-13 19:57:26,908 - INFO - integrating rxn: rxn01106_c0
2026-01-13 19:57:26,910 - INFO - integrating rxn: rxn00935_c0
2026-01-13 19:57:26,911 - INFO - integrating rxn: rxn00157_c0
2026-01-13 19:57:26,913 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:57:26,914 - INFO - integrating rxn: rxn05559_c0
2026-01-13 19:57:26,916 - INFO - integrating rxn: rxn00251_c0
2026-01-13 19:57:26,917 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:26,918 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:57:26,927 - INFO - Glyc/rxn00062_c0:EX_cpd00047_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:26,928 - INFO - Glyc/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:57:26,930 - INFO - Glyc/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:26,931 - INFO - Glyc/rxn00062_c0:rxn01106_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:26,933 - INFO - Glyc/rxn00062_c0:rxn00935_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:26,934 - INFO - Glyc/rxn00062_c0:rxn00157_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:26,935 - INFO - Glyc/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:26,936 - INFO - Glyc/rxn00062_c0:rxn05559_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:26,937 - INFO - Glyc/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:26,938 - INFO - Glyc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:26,944 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b967340>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'rxn05581_c0': '<', 'rxn01106_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00251_c0': '<'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:57:26,945 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00047_e0': '>', 'EX_cpd00363_e0': '>', 'rxn05581_c0': '<', 'rxn01106_c0': '<', 'rxn00935_c0': '<', 'rxn00157_c0': '<', 'rxn05553_c0': '>', 'rxn05559_c0': '<', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b967340>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:26,949 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 19:57:26,974 - INFO - Objective with gapfill database:2.0000000000000004; min objective:0.01
2026-01-13 19:57:27,005 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b9674c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:27,007 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:27,008 - INFO - integrating rxn: rxn05319_c0
2026-01-13 19:57:27,009 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:57:27,018 - INFO - rxn00250_c0< not needed:0.25
2026-01-13 19:57:27,019 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:27,025 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b9674c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 19:57:27,027 - INFO - Unneeded: [['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b9674c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:27,030 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 19:57:27,053 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 19:57:29,261 - WARNING -     ATP correction failed: 'NoneType' object is not iterable

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:29,460 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 19:57:29,468 - INFO - cpd08701 not found in model!
2026-01-13 19:57:29,469 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:57:29,470 - INFO - cpd01024 not found in model!
2026-01-13 19:57:29,472 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:29,476 - INFO - cpd08701 not found in model!
2026-01-13 19:57:29,477 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 19:57:29,479 - INFO - cpd01024 not found in model!
2026-01-13 19:57:29,480 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:57:29,489 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:29,929 - INFO -   Saved gapfilled model: gapfilled_models2/Gordonia.1_gf.xml
2026-01-13 19:57:29,933 - INFO -   Total reactions added: 218
2026-01-13 19:57:30,155 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:30,689 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3
Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 19:57:30,711 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.
2026-01-13 19:57:30,719 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:32,464 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 19:57:32,490 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:34,013 - INFO - Objective with gapfill database:34.49999999999999; min objective:0.01
2026-01-13 19:57:34,051 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:34,714 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 19:57:34,724 - INFO - cpd00425 not found in model!
2026-01-13 19:57:34,725 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 19:57:34,737 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:35,109 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 19:57:35,131 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:35,784 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:57:35,814 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:36,036 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:57:36,059 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:38,025 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:57:38,057 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:41,398 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:41,427 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 19:57:41,459 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:57:41,485 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:41,731 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 19:57:41,758 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:57:41,792 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00027_e0': '<', 'rxn05226_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d30f10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:57:41,794 - INFO - integrating rxn: EX_cpd00027_e0
2026-01-13 19:57:41,795 - INFO - integrating rxn: rxn05226_c0
2026-01-13 19:57:41,796 - INFO - integrating rxn: rxn00250_c0
2026-01-13 19:57:41,797 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:57:41,807 - INFO - Glc/rxn00062_c0:EX_cpd00027_e0< needed:0.0 with min obj:0.01
2026-01-13 19:57:41,808 - INFO - Glc/rxn00062_c0:rxn05226_c0> needed:0.0 with min obj:0.01
2026-01-13 19:57:41,809 - INFO - Glc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 19:57:41,816 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d30f10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00027_e0': '<', 'rxn05226_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 19:57:41,817 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00027_e0': '<', 'rxn05226_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d30f10>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:57:41,820 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 19:57:41,844 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:42,841 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:57:42,868 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:44,747 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 19:57:44,773 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:45,229 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:57:45,267 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:45,383 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:57:45,413 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:45,828 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 19:57:45,862 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:57:45,887 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 19:57:45,914 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:49,613 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 19:57:49,636 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:57:59,481 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 19:57:59,507 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:01,007 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 19:58:01,040 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:02,350 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:58:02,374 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:03,976 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 19:58:04,004 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:05,493 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:58:05,518 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:08,692 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:58:08,703 - INFO - cpd11632 not found in model!
2026-01-13 19:58:08,704 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:58:08,717 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:10,339 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 19:58:10,365 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:10,840 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:58:10,869 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:15,223 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 19:58:15,253 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:17,563 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 19:58:17,595 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:25,958 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:58:25,970 - INFO - cpd11632 not found in model!
2026-01-13 19:58:25,970 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:58:25,983 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:28,807 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 19:58:28,820 - INFO - cpd11632 not found in model!
2026-01-13 19:58:28,821 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 19:58:28,834 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:31,438 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 19:58:31,449 - INFO - cpd01024 not found in model!
2026-01-13 19:58:31,450 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 19:58:31,463 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:58:35,618 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 19:58:35,644 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:59:16,486 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 19:59:16,513 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:59:16,542 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd1930>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:59:16,544 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:59:16,545 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:59:16,546 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:59:16,548 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:59:16,548 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:59:16,550 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:59:16,551 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:59:16,552 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:59:16,559 - INFO - cpd08021 not found in model!
2026-01-13 19:59:16,560 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 19:59:16,565 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,566 - INFO - Glc.DMSO/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,568 - INFO - Glc.DMSO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:59:16,569 - INFO - Glc.DMSO/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,570 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,572 - INFO - Glc.DMSO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,573 - INFO - Glc.DMSO/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,579 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd1930>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:59:16,579 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd1930>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:59:16,584 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:59:16,604 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 19:59:16,631 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd17b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:59:16,634 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:59:16,635 - INFO - integrating rxn: rxn01975_c0
2026-01-13 19:59:16,636 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:59:16,637 - INFO - integrating rxn: rxn01476_c0
2026-01-13 19:59:16,638 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:59:16,640 - INFO - integrating rxn: rxn03884_c0
2026-01-13 19:59:16,641 - INFO - integrating rxn: rxn01477_c0
2026-01-13 19:59:16,641 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:59:16,646 - INFO - cpd00811 not found in model!
2026-01-13 19:59:16,647 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 19:59:16,650 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,651 - INFO - Glc.TMAO/rxn00062_c0:rxn01975_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,652 - INFO - Glc.TMAO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:59:16,653 - INFO - Glc.TMAO/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,655 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,656 - INFO - Glc.TMAO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,657 - INFO - Glc.TMAO/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:16,663 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd17b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 19:59:16,664 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn01975_c0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd17b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:59:16,668 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:59:16,688 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:59:31,006 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 19:59:31,027 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:59:45,368 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0
2026-01-13 19:59:45,389 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:59:58,814 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 19:59:58,839 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 19:59:59,533 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0
2026-01-13 19:59:59,555 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 19:59:59,583 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd3640>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:59:59,585 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:59:59,586 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:59:59,588 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:59:59,588 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:59:59,590 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:59:59,590 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:59:59,596 - INFO - cpd11640 not found in model!
2026-01-13 19:59:59,597 - INFO - Media compound: cpd11640 not found in model.
2026-01-13 19:59:59,600 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:59:59,601 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:59:59,602 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:59,604 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:59:59,605 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:59,610 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd3640>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:59:59,610 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd3640>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:59:59,614 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:59:59,634 - INFO - Objective with gapfill database:0.7499999999999999; min objective:0.01
2026-01-13 19:59:59,661 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd3af0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 19:59:59,663 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 19:59:59,664 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 19:59:59,664 - INFO - integrating rxn: rxn05602_c0
2026-01-13 19:59:59,666 - INFO - integrating rxn: rxn07191_c0
2026-01-13 19:59:59,666 - INFO - integrating rxn: rxn05553_c0
2026-01-13 19:59:59,667 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:59:59,674 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 19:59:59,675 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 19:59:59,676 - INFO - LLac.SO4/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:59,677 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 19:59:59,679 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 19:59:59,683 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd3af0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 19:59:59,684 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa42cd3af0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 19:59:59,689 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn10122_c0', '>', 'new'], ['rxn14421_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09272_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]
2026-01-13 19:59:59,709 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:07,399 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 20:00:07,422 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:13,904 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 20:00:13,913 - INFO - cpd08701 not found in model!
2026-01-13 20:00:13,914 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 20:00:13,915 - INFO - cpd01024 not found in model!
2026-01-13 20:00:13,916 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:00:13,922 - INFO - cpd08701 not found in model!
2026-01-13 20:00:13,923 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 20:00:13,924 - INFO - cpd01024 not found in model!
2026-01-13 20:00:13,925 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:00:13,934 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:15,497 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 20:00:15,525 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:20,116 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2

2026-01-13 20:00:20,143 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:25,063 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 20:00:25,086 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:26,941 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0
2026-01-13 20:00:26,962 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:28,101 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 20:00:28,122 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:29,661 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 20:00:29,675 - INFO - cpd11632 not found in model!
2026-01-13 20:00:29,676 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 20:00:29,689 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:30,295 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 20:00:30,326 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 20:00:30,358 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn01343_c0': '>', 'rxn05226_c0': '>', 'rxn00781_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c4fa0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:00:30,360 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 20:00:30,361 - INFO - integrating rxn: rxn05602_c0
2026-01-13 20:00:30,364 - INFO - integrating rxn: rxn01343_c0
2026-01-13 20:00:30,366 - INFO - integrating rxn: rxn05226_c0
2026-01-13 20:00:30,368 - INFO - integrating rxn: rxn00781_c0
2026-01-13 20:00:30,369 - INFO - integrating rxn: rxn00250_c0
2026-01-13 20:00:30,370 - INFO - Full solution: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01343_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00781_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 20:00:30,382 - INFO - Glc/rxn00062_c0:EX_cpd00159_e0> needed:0.0 with min obj:0.01
2026-01-13 20:00:30,383 - INFO - Glc/rxn00062_c0:rxn05602_c0< needed:0.0 with min obj:0.01
2026-01-13 20:00:30,384 - INFO - Glc/rxn00062_c0:rxn01343_c0> needed:0.0 with min obj:0.01
2026-01-13 20:00:30,386 - INFO - rxn05226_c0> not needed:1.75
2026-01-13 20:00:30,387 - INFO - Glc/rxn00062_c0:rxn00781_c0> needed:0.0 with min obj:0.01
2026-01-13 20:00:30,388 - INFO - Glc/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 20:00:30,394 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c4fa0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn01343_c0': '>', 'rxn00781_c0': '>'}, 'reversed': {'rxn00250_c0': '<'}}
2026-01-13 20:00:30,395 - INFO - Unneeded: [['rxn05226_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn01343_c0': '>', 'rxn05226_c0': '>', 'rxn00781_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c4fa0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:00:30,399 - INFO - Cumulative: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01343_c0', '>', 'new'], ['rxn00781_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 20:00:30,421 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:30,621 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 20:00:30,644 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:31,332 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 20:00:31,356 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:32,182 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 20:00:32,210 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:41,871 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0
2026-01-13 20:00:41,892 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 20:00:41,925 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c196b90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:00:41,927 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:00:41,928 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:00:41,929 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:00:41,930 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:00:41,938 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:00:41,939 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:00:41,941 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:00:41,946 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c196b90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 20:00:41,946 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c196b90>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:00:41,950 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:00:41,970 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 20:00:41,998 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1966b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:00:42,000 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:00:42,001 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:00:42,002 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:00:42,003 - INFO - Full solution: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:00:42,010 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:00:42,012 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:00:42,013 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:00:42,018 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1966b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 20:00:42,019 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa3c1966b0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:00:42,024 - INFO - Cumulative: [['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01116_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:00:42,044 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:42,401 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 20:00:42,409 - INFO - cpd00187 not found in model!
2026-01-13 20:00:42,410 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:00:42,416 - INFO - cpd00187 not found in model!
2026-01-13 20:00:42,416 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:00:42,426 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:42,695 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0

2026-01-13 20:00:42,719 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:00:42,748 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 20:00:42,775 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:44,401 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 20:00:44,435 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:44,884 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 20:00:44,912 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:45,954 - WARNING - No gapfilling solution found for Pyr.SO3 activating rxn00062_c0
2026-01-13 20:00:45,976 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:47,231 - WARNING - No gapfilling solution found before filtering for For.SO4.H2 activating rxn00062_c0

Removing ungapfillable media For.SO4.H2

2026-01-13 20:00:47,260 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:48,516 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 20:00:48,546 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 20:00:48,578 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c4ee0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:00:48,580 - INFO - integrating rxn: rxn00083_c0
2026-01-13 20:00:48,581 - INFO - integrating rxn: rxn00499_c0
2026-01-13 20:00:48,583 - INFO - integrating rxn: rxn03884_c0
2026-01-13 20:00:48,585 - INFO - integrating rxn: rxn01477_c0
2026-01-13 20:00:48,586 - INFO - Full solution: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 20:00:48,597 - INFO - Glc/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:0.01
2026-01-13 20:00:48,599 - INFO - Glc/rxn00062_c0:rxn00499_c0< needed:0.0 with min obj:0.01
2026-01-13 20:00:48,600 - INFO - Glc/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 20:00:48,602 - INFO - Glc/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 20:00:48,609 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c4ee0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 20:00:48,609 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c4ee0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:00:48,613 - INFO - Cumulative: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 20:00:48,639 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:48,906 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 20:00:48,938 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:49,274 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:49,311 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:00:49,337 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 20:00:49,360 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:52,522 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 20:00:52,537 - INFO - cpd11632 not found in model!
2026-01-13 20:00:52,538 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 20:00:52,551 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:52,698 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 20:00:52,731 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:53,213 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 20:00:53,251 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:53,313 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 20:00:53,326 - INFO - cpd01024 not found in model!
2026-01-13 20:00:53,327 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:00:53,340 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:53,402 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 20:00:53,426 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:53,952 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 20:00:53,962 - INFO - cpd00187 not found in model!
2026-01-13 20:00:53,963 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:00:53,968 - INFO - cpd00187 not found in model!
2026-01-13 20:00:53,969 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:00:53,979 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:55,332 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 20:00:55,352 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:56,648 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 20:00:56,669 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:00:56,973 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 20:00:56,986 - INFO - cpd08701 not found in model!
2026-01-13 20:00:56,987 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 20:00:56,988 - INFO - cpd01024 not found in model!
2026-01-13 20:00:56,989 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:00:56,995 - INFO - cpd08701 not found in model!
2026-01-13 20:00:56,995 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 20:00:56,996 - INFO - cpd01024 not found in model!
2026-01-13 20:00:56,997 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:00:57,008 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:00,386 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 20:01:00,410 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:01,251 - WARNING - No gapfilling solution found for H2.Ac activating rxn00062_c0
2026-01-13 20:01:01,273 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 20:01:01,303 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324728f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:01,305 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 20:01:01,306 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:01,308 - INFO - integrating rxn: rxn05602_c0
2026-01-13 20:01:01,308 - INFO - integrating rxn: rxn05938_c0
2026-01-13 20:01:01,309 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:01,310 - INFO - integrating rxn: rxn00543_c0
2026-01-13 20:01:01,311 - INFO - integrating rxn: rxn00171_c0
2026-01-13 20:01:01,312 - INFO - integrating rxn: rxn00499_c0
2026-01-13 20:01:01,313 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:01,313 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:01,321 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,322 - INFO - LLac.SO4.H2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:01,323 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:01,324 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,325 - INFO - LLac.SO4.H2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,325 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,326 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,327 - INFO - LLac.SO4.H2/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:01,328 - INFO - LLac.SO4.H2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:01,334 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324728f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:01,334 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa324728f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:01,338 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:01,359 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 20:01:01,389 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa32472200>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:01,391 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 20:01:01,392 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:01,392 - INFO - integrating rxn: rxn05602_c0
2026-01-13 20:01:01,393 - INFO - integrating rxn: rxn05938_c0
2026-01-13 20:01:01,394 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:01,395 - INFO - integrating rxn: rxn00543_c0
2026-01-13 20:01:01,396 - INFO - integrating rxn: rxn00171_c0
2026-01-13 20:01:01,397 - INFO - integrating rxn: rxn00499_c0
2026-01-13 20:01:01,398 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:01,399 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:01,405 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,406 - INFO - LLac.SO4/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:01,407 - INFO - LLac.SO4/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:01,408 - INFO - LLac.SO4/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,409 - INFO - LLac.SO4/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,410 - INFO - LLac.SO4/rxn00062_c0:rxn00543_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,411 - INFO - LLac.SO4/rxn00062_c0:rxn00171_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:01,412 - INFO - LLac.SO4/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:01,413 - INFO - LLac.SO4/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:01,418 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa32472200>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:01,419 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn00543_c0': '<', 'rxn00171_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa32472200>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:01,422 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00543_c0', '<', 'new'], ['rxn00171_c0', '<', 'new'], ['rxn00250_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn08556_c0', '>', 'new'], ['rxn14422_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn14421_c0', '>', 'new'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:01,449 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:04,393 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 20:01:04,420 - INFO - Objective with gapfill database:0.7500000000000001; min objective:0.01
2026-01-13 20:01:04,424 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 20:01:04,445 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:04,450 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b967a00>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:04,452 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:04,455 - INFO - integrating rxn: rxn05938_c0
2026-01-13 20:01:04,456 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:04,457 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:04,458 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 20:01:04,468 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:04,469 - INFO - Llac/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:04,470 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:04,471 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:04,477 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b967a00>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:04,478 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0b967a00>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:04,482 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00256_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn01106_c0', '<', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new']]
2026-01-13 20:01:04,505 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:05,501 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 20:01:05,526 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:05,617 - WARNING - No gapfilling solution found before filtering for Pyr.NO2 activating rxn00062_c0

Removing ungapfillable media Pyr.NO2

2026-01-13 20:01:05,650 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:05,762 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 20:01:05,787 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:06,993 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 20:01:07,015 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:07,860 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 20:01:07,872 - INFO - cpd11632 not found in model!
2026-01-13 20:01:07,873 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 20:01:07,887 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:08,196 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,217 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,231 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:08,245 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,258 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,271 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,285 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,286 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 20:01:08,307 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,314 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:08,321 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,333 - INFO - cpd00221 not found in model!
2026-01-13 20:01:08,334 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 20:01:08,338 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,352 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,366 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,380 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:08,394 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,407 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,421 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,434 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,439 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 20:01:08,447 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,460 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,464 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 20:01:08,472 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,483 - INFO - cpd00221 not found in model!
2026-01-13 20:01:08,484 - INFO - Media compound: cpd00221 not found in model.
2026-01-13 20:01:08,487 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,496 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c58a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:08,498 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 20:01:08,499 - INFO - integrating rxn: rxn05602_c0
2026-01-13 20:01:08,500 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,500 - INFO - integrating rxn: rxn05319_c0
2026-01-13 20:01:08,502 - INFO - integrating rxn: rxn00250_c0
2026-01-13 20:01:08,503 - INFO - Full solution: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01343_c0', '>', 'new'], ['rxn00781_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:01:08,511 - INFO - Fum/rxn00062_c0:EX_cpd00159_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:08,513 - INFO - Fum/rxn00062_c0:rxn05602_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:08,513 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,514 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:08,516 - INFO - rxn00250_c0< not needed:0.25
2026-01-13 20:01:08,522 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c58a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<'}, 'reversed': {'rxn05319_c0': '>'}}
2026-01-13 20:01:08,522 - INFO - Unneeded: [['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00159_e0': '>', 'rxn05602_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c58a0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:08,526 - INFO - Cumulative: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01343_c0', '>', 'new'], ['rxn00781_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01343_c0', '>', 'new'], ['rxn00781_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:01:08,526 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,539 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,549 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:08,549 - INFO - cpd00418 not found in model!
2026-01-13 20:01:08,550 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 20:01:08,554 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,566 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,579 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,589 - INFO - cpd00418 not found in model!
2026-01-13 20:01:08,590 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 20:01:08,593 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,606 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:08,618 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,629 - INFO - cpd00418 not found in model!
2026-01-13 20:01:08,630 - INFO - Media compound: cpd00418 not found in model.
2026-01-13 20:01:08,633 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,643 - INFO - cpd08021 not found in model!
2026-01-13 20:01:08,644 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 20:01:08,647 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,651 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 20:01:08,658 - INFO - cpd00811 not found in model!
2026-01-13 20:01:08,659 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 20:01:08,662 - INFO - cpd00187 not found in model!
2026-01-13 20:01:08,663 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,663 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:01:08,668 - INFO - cpd00187 not found in model!
2026-01-13 20:01:08,668 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:01:08,675 - INFO - cpd08021 not found in model!
2026-01-13 20:01:08,676 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 20:01:08,678 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:08,679 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,691 - INFO - cpd00811 not found in model!
2026-01-13 20:01:08,692 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 20:01:08,695 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,709 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,723 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,737 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,750 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,763 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,777 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,790 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,804 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,817 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:08,831 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,842 - INFO - cpd11632 not found in model!
2026-01-13 20:01:08,843 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 20:01:08,846 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,857 - INFO - cpd08701 not found in model!
2026-01-13 20:01:08,858 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 20:01:08,858 - INFO - cpd01024 not found in model!
2026-01-13 20:01:08,859 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:08,862 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,873 - INFO - cpd01024 not found in model!
2026-01-13 20:01:08,874 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:08,877 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,890 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,903 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,914 - INFO - cpd00187 not found in model!
2026-01-13 20:01:08,915 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:01:08,918 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,929 - INFO - cpd00425 not found in model!
2026-01-13 20:01:08,930 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 20:01:08,933 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:08,944 - INFO - cpd00441 not found in model!
2026-01-13 20:01:08,945 - INFO - Media compound: cpd00441 not found in model.
2026-01-13 20:01:08,948 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,079 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:09,104 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,130 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,136 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 20:01:09,149 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,162 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:09,167 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,186 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,204 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,223 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,242 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,261 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,280 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,299 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,317 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,336 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,354 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,373 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,391 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,410 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,428 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,447 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,465 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,483 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,502 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,522 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,541 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,560 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,579 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,598 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,617 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,637 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,655 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,674 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,693 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,719 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,738 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,757 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,775 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,794 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,812 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,831 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,850 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in
None

2026-01-13 20:01:09,869 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,881 - WARNING -     ATP correction failed: 'NoneType' object is not iterable
2026-01-13 20:01:09,887 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,906 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,925 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,943 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,958 - INFO - cpd11632 not found in model!
2026-01-13 20:01:09,959 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 20:01:09,963 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:09,978 - INFO - cpd08701 not found in model!
2026-01-13 20:01:09,979 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 20:01:09,980 - INFO - cpd01024 not found in model!
2026-01-13 20:01:09,981 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:09,985 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:10,000 - INFO - cpd01024 not found in model!
2026-01-13 20:01:10,001 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:10,006 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:10,024 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:10,042 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:10,057 - INFO - cpd00187 not found in model!
2026-01-13 20:01:10,058 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:01:10,062 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:10,077 - INFO - cpd00425 not found in model!
2026-01-13 20:01:10,078 - INFO - Media compound: cpd00425 not found in model.
2026-01-13 20:01:10,082 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:10,100 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:10,252 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 20:01:10,284 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:11,008 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 20:01:11,039 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:11,109 - INFO -   Saved gapfilled model: gapfilled_models2/Firmicutes.7_gf.xml
2026-01-13 20:01:11,114 - INFO -   Total reactions added: 70
2026-01-13 20:01:11,526 - ERROR - '' is not a valid SBML 'SId'.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:12,137 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 20:01:12,159 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
c0

2026-01-13 20:01:12,596 - WARNING - Ignoring reaction 'rxn00062_c0' since it already exists.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:14,409 - WARNING - No gapfilling solution found before filtering for For.SO4 activating rxn00062_c0

Removing ungapfillable media For.SO4

2026-01-13 20:01:14,437 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:15,525 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 20:01:15,557 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:16,449 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 20:01:16,472 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:16,970 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 20:01:16,974 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 20:01:16,987 - INFO - cpd01024 not found in model!
2026-01-13 20:01:16,988 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:16,996 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:17,001 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:17,275 - WARNING - No gapfilling solution found for empty activating rxn00062_c0
2026-01-13 20:01:17,283 - INFO - cpd08701 not found in model!
2026-01-13 20:01:17,284 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 20:01:17,285 - INFO - cpd01024 not found in model!
2026-01-13 20:01:17,286 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:17,292 - INFO - cpd08701 not found in model!
2026-01-13 20:01:17,292 - INFO - Media compound: cpd08701 not found in model.
2026-01-13 20:01:17,293 - INFO - cpd01024 not found in model!
2026-01-13 20:01:17,294 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:17,304 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:18,099 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 20:01:18,123 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:18,604 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 20:01:18,636 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:18,818 - INFO - Objective with gapfill database:143.82315796111249; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:19,445 - WARNING - No gapfilling solution found before filtering for Pyr.O2 activating rxn00062_c0

Removing ungapfillable media Pyr.O2

2026-01-13 20:01:19,466 - INFO - Objective with gapfill database:17.499999999999996; min objective:0.01
2026-01-13 20:01:19,484 - INFO - Objective with gapfill database:19.125000000000004; min objective:0.01
2026-01-13 20:01:19,502 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:19,950 - WARNING - No gapfilling solution found for Trimethylamine.H2 activating rxn00062_c0
2026-01-13 20:01:20,546 - INFO - Loading model: Hungateiclostridiaceae.10
2026-01-13 20:01:20,858 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 20:01:21,229 - INFO - Objective with gapfill database:143.82315796111249; min objective:0.01
2026-01-13 20:01:21,451 - INFO -   Loading template...
2026-01-13 20:01:21,874 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn04413_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn16218_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn16217_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn00644_c0': '>', 'rxn04551_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn45106_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn27266_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn08989_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:21,879 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 20:01:21,881 - INFO - integrating rxn: rxn08709_c0
2026-01-13 20:01:21,883 - INFO - integrating rxn: rxn00800_c0
2026-01-13 20:01:21,885 - INFO - integrating rxn: rxn10336_c0
2026-01-13 20:01:21,887 - INFO - integrating rxn: rxn12512_c0
2026-01-13 20:01:21,889 - INFO - integrating rxn: rxn08583_c0
2026-01-13 20:01:21,891 - INFO - integrating rxn: rxn10481_c0
2026-01-13 20:01:21,892 - INFO - integrating rxn: rxn03918_c0
2026-01-13 20:01:21,894 - INFO - integrating rxn: rxn08708_c0
2026-01-13 20:01:21,896 - INFO - integrating rxn: rxn00392_c0
2026-01-13 20:01:21,898 - INFO - integrating rxn: rxn09225_c0
2026-01-13 20:01:21,900 - INFO - integrating rxn: rxn02774_c0
2026-01-13 20:01:21,901 - INFO - integrating rxn: rxn01505_c0
2026-01-13 20:01:21,903 - INFO - integrating rxn: rxn08954_c0
2026-01-13 20:01:21,905 - INFO - integrating rxn: rxn00916_c0
2026-01-13 20:01:21,906 - INFO - integrating rxn: rxn08618_c0
2026-01-13 20:01:21,908 - INFO - integrating rxn: rxn03537_c0
2026-01-13 20:01:21,909 - INFO - integrating rxn: rxn03916_c0
2026-01-13 20:01:21,911 - INFO - integrating rxn: rxn05463_c0
2026-01-13 20:01:21,913 - INFO - integrating rxn: rxn04413_c0
2026-01-13 20:01:21,914 - INFO - integrating rxn: rxn03087_c0
2026-01-13 20:01:21,916 - INFO - integrating rxn: rxn01213_c0
2026-01-13 20:01:21,917 - INFO - integrating rxn: rxn03136_c0
2026-01-13 20:01:21,919 - INFO - integrating rxn: rxn02056_c0
2026-01-13 20:01:21,920 - INFO - integrating rxn: rxn00122_c0
2026-01-13 20:01:21,922 - INFO - integrating rxn: rxn08620_c0
2026-01-13 20:01:21,923 - INFO - integrating rxn: rxn02287_c0
2026-01-13 20:01:21,925 - INFO - integrating rxn: rxn04308_c0
2026-01-13 20:01:21,926 - INFO - integrating rxn: rxn01258_c0
2026-01-13 20:01:21,928 - INFO - integrating rxn: rxn02341_c0
2026-01-13 20:01:21,928 - INFO -   Using template: GramNegative.modeltemplate
2026-01-13 20:01:21,929 - INFO - integrating rxn: rxn08619_c0
2026-01-13 20:01:21,931 - INFO - integrating rxn: rxn01603_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:21,933 - INFO - integrating rxn: rxn21635_c0
2026-01-13 20:01:21,934 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 20:01:21,935 - INFO - integrating rxn: rxn22816_c0
2026-01-13 20:01:21,937 - INFO - integrating rxn: rxn16218_c0
2026-01-13 20:01:21,938 - INFO - integrating rxn: rxn22817_c0
2026-01-13 20:01:21,940 - INFO - integrating rxn: rxn20834_c0
2026-01-13 20:01:21,941 - INFO - integrating rxn: rxn16217_c0
2026-01-13 20:01:21,943 - INFO - integrating rxn: rxn12930_c0
2026-01-13 20:01:21,945 - INFO - integrating rxn: rxn12940_c0
2026-01-13 20:01:21,947 - INFO - integrating rxn: rxn12939_c0
2026-01-13 20:01:21,948 - INFO - integrating rxn: rxn12929_c0
2026-01-13 20:01:21,950 - INFO - integrating rxn: rxn12938_c0
2026-01-13 20:01:21,951 - INFO - integrating rxn: rxn12927_c0
2026-01-13 20:01:21,953 - INFO - integrating rxn: rxn12921_c0
2026-01-13 20:01:21,954 - INFO - integrating rxn: rxn12928_c0
2026-01-13 20:01:21,956 - INFO - integrating rxn: rxn12943_c0
2026-01-13 20:01:21,957 - INFO - integrating rxn: rxn12934_c0
2026-01-13 20:01:21,959 - INFO - integrating rxn: rxn46124_c0
2026-01-13 20:01:21,961 - INFO - integrating rxn: rxn25474_c0
2026-01-13 20:01:21,963 - INFO - integrating rxn: rxn12941_c0
2026-01-13 20:01:21,964 - INFO - integrating rxn: rxn19346_c0
2026-01-13 20:01:21,966 - INFO - integrating rxn: rxn40142_c0
2026-01-13 20:01:21,968 - INFO - integrating rxn: rxn00644_c0
2026-01-13 20:01:21,969 - INFO - integrating rxn: rxn04551_c0
2026-01-13 20:01:21,971 - INFO - integrating rxn: rxn25479_c0
2026-01-13 20:01:21,972 - INFO - integrating rxn: rxn22114_c0
2026-01-13 20:01:21,974 - INFO - integrating rxn: rxn14070_c0
2026-01-13 20:01:21,975 - INFO - integrating rxn: rxn45106_c0
2026-01-13 20:01:21,977 - INFO - integrating rxn: rxn15060_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:21,979 - INFO - integrating rxn: rxn29919_c0
2026-01-13 20:01:21,980 - INFO - integrating rxn: rxn30685_c0
2026-01-13 20:01:21,982 - INFO - integrating rxn: rxn11285_c0
2026-01-13 20:01:21,983 - INFO - integrating rxn: rxn20508_c0
2026-01-13 20:01:21,985 - INFO - integrating rxn: rxn20627_c0
2026-01-13 20:01:21,986 - INFO - integrating rxn: rxn15940_c0
2026-01-13 20:01:21,988 - INFO - integrating rxn: rxn30917_c0
2026-01-13 20:01:21,990 - INFO - integrating rxn: rxn27266_c0
2026-01-13 20:01:21,991 - INFO - integrating rxn: rxn40674_c0
2026-01-13 20:01:21,993 - INFO - integrating rxn: rxn08921_c0
2026-01-13 20:01:21,994 - INFO - integrating rxn: rxn08989_c0
2026-01-13 20:01:21,995 - INFO - Full solution: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn22816_c0', '>', 'new'], ['rxn16218_c0', '>', 'new'], ['rxn22817_c0', '>', 'new'], ['rxn20834_c0', '>', 'new'], ['rxn16217_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn46124_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn40142_c0', '>', 'new'], ['rxn00644_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn45106_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn29919_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn27266_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn08989_c0', '>', 'new']]
2026-01-13 20:01:22,022 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 20:01:22,041 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:22,064 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 20:01:22,066 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,069 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,071 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,073 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,075 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,077 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,079 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,080 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,082 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,084 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,086 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,088 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,090 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,092 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,093 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,095 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,097 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,099 - INFO - AuxoMedia/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,101 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,103 - INFO - AuxoMedia/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:22,105 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,108 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,110 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:22,112 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,114 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,116 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,118 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,120 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,122 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,123 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,125 - INFO - AuxoMedia/bio1:rxn01603_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,133 - INFO - rxn21635_c0> not needed:18.397538798382023
2026-01-13 20:01:22,135 - INFO - rxn22816_c0> not needed:18.397538798381937
2026-01-13 20:01:22,136 - INFO - rxn16218_c0> not needed:18.397538798382023
2026-01-13 20:01:22,138 - INFO - rxn22817_c0> not needed:18.397538798382023
2026-01-13 20:01:22,140 - INFO - rxn20834_c0> not needed:18.397538798382023
2026-01-13 20:01:22,141 - INFO - rxn16217_c0> not needed:18.397538798382023
2026-01-13 20:01:22,145 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,151 - INFO - rxn12940_c0> not needed:18.397538798381973
2026-01-13 20:01:22,152 - INFO - rxn12939_c0> not needed:18.397538798381756
2026-01-13 20:01:22,154 - INFO - rxn12929_c0> not needed:18.397538798381756
2026-01-13 20:01:22,155 - INFO - rxn12938_c0> not needed:18.397538798381756
2026-01-13 20:01:22,157 - INFO - rxn12927_c0> not needed:18.397538798381756
2026-01-13 20:01:22,158 - INFO - rxn12921_c0> not needed:18.397538798381756
2026-01-13 20:01:22,160 - INFO - rxn12928_c0> not needed:18.397538798381756
2026-01-13 20:01:22,165 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,167 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,171 - INFO - rxn46124_c0> not needed:18.397538798382147
2026-01-13 20:01:22,175 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,178 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,184 - INFO - rxn19346_c0> not needed:17.512058963783034
2026-01-13 20:01:22,186 - INFO - rxn40142_c0> not needed:17.512058963782664
2026-01-13 20:01:22,188 - INFO - rxn00644_c0> not needed:17.512058963782664
2026-01-13 20:01:22,190 - INFO - rxn04551_c0> not needed:17.512058963782664
2026-01-13 20:01:22,196 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,198 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,200 - INFO - AuxoMedia/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,206 - INFO - rxn45106_c0> not needed:17.40792677982036
2026-01-13 20:01:22,210 - INFO - rxn15060_c0> not needed:17.40792677982088
2026-01-13 20:01:22,212 - INFO - rxn29919_c0> not needed:17.40792677982088
2026-01-13 20:01:22,217 - INFO - AuxoMedia/bio1:rxn30685_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,222 - INFO - rxn11285_c0> not needed:17.407926779820794
2026-01-13 20:01:22,224 - INFO - rxn20508_c0> not needed:17.407926779820794
2026-01-13 20:01:22,225 - INFO - rxn20627_c0> not needed:17.407926779820794
2026-01-13 20:01:22,229 - INFO - AuxoMedia/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,231 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,235 - INFO - rxn27266_c0> not needed:17.3772903802798
2026-01-13 20:01:22,238 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,242 - INFO - rxn08921_c0> not needed:17.377290380280407
2026-01-13 20:01:22,244 - INFO - rxn08989_c0> not needed:17.377290380280694
2026-01-13 20:01:22,249 - INFO - Unneeded: [['rxn21635_c0', '>', 'new', 100, None], ['rxn22816_c0', '>', 'new', 100, None], ['rxn16218_c0', '>', 'new', 100, None], ['rxn22817_c0', '>', 'new', 100, None], ['rxn20834_c0', '>', 'new', 100, None], ['rxn16217_c0', '>', 'new', 100, None], ['rxn12940_c0', '>', 'new', 100, None], ['rxn12939_c0', '>', 'new', 100, None], ['rxn12929_c0', '>', 'new', 100, None], ['rxn12938_c0', '>', 'new', 100, None], ['rxn12927_c0', '>', 'new', 100, None], ['rxn12921_c0', '>', 'new', 100, None], ['rxn12928_c0', '>', 'new', 100, None], ['rxn46124_c0', '>', 'new', 100, None], ['rxn19346_c0', '>', 'new', 100, None], ['rxn40142_c0', '>', 'new', 100, None], ['rxn00644_c0', '>', 'new', 100, None], ['rxn04551_c0', '>', 'new', 100, None], ['rxn45106_c0', '>', 'new', 100, None], ['rxn15060_c0', '>', 'new', 100, None], ['rxn29919_c0', '>', 'new', 100, None], ['rxn11285_c0', '>', 'new', 100, None], ['rxn20508_c0', '>', 'new', 100, None], ['rxn20627_c0', '>', 'new', 100, None], ['rxn27266_c0', '>', 'new', 100, None], ['rxn08921_c0', '>', 'new', 100, None], ['rxn08989_c0', '>', 'new', 100, None]]
2026-01-13 20:01:22,265 - INFO - Growth: 18.39753879838194 AuxoMedia

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn01505_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08618_c0': '>', 'rxn03537_c0': '>', 'rxn03916_c0': '>', 'rxn05463_c0': '>', 'rxn04413_c0': '>', 'rxn03087_c0': '<', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn02341_c0': '>', 'rxn08619_c0': '>', 'rxn01603_c0': '>', 'rxn21635_c0': '>', 'rxn22816_c0': '>', 'rxn16218_c0': '>', 'rxn22817_c0': '>', 'rxn20834_c0': '>', 'rxn16217_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12934_c0': '>', 'rxn46124_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn19346_c0': '>', 'rxn40142_c0': '>', 'rxn00644_c0': '>', 'rxn04551_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn14070_c0': '>', 'rxn45106_c0': '>', 'rxn15060_c0': '>', 'rxn29919_c0': '>', 'rxn30685_c0': '>', 'rxn11285_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn15940_c0': '>', 'rxn30917_c0': '>', 'rxn27266_c0': '>', 'rxn40674_c0': '>', 'rxn08921_c0': '>', 'rxn08989_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:22,270 - INFO - Cumulative: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new']]
2026-01-13 20:01:22,271 - INFO -     Added 44 reactions
2026-01-13 20:01:22,272 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:22,448 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 20:01:22,476 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 20:01:22,508 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c9cbb80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:22,510 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:22,512 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:22,512 - INFO - integrating rxn: rxn00148_c0
2026-01-13 20:01:22,513 - INFO - integrating rxn: rxn08173_c0
2026-01-13 20:01:22,514 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:22,515 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:01:22,521 - INFO - cpd08021 not found in model!
2026-01-13 20:01:22,522 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 20:01:22,526 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,527 - INFO - Glc.DMSO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:22,529 - INFO - Glc.DMSO/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:22,530 - INFO - Glc.DMSO/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:22,531 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,537 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c9cbb80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:22,538 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c9cbb80>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:22,541 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:01:22,564 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 20:01:22,593 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c9cbeb0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:22,595 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:22,596 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:22,597 - INFO - integrating rxn: rxn00148_c0
2026-01-13 20:01:22,598 - INFO - integrating rxn: rxn08173_c0
2026-01-13 20:01:22,598 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:22,599 - INFO - Full solution: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:01:22,605 - INFO - cpd00811 not found in model!
2026-01-13 20:01:22,605 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 20:01:22,609 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,610 - INFO - Glc.TMAO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:22,611 - INFO - Glc.TMAO/rxn00062_c0:rxn00148_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:22,612 - INFO - Glc.TMAO/rxn00062_c0:rxn08173_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:22,613 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:22,619 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c9cbeb0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:22,620 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00148_c0': '<', 'rxn08173_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa1c9cbeb0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:22,624 - INFO - Cumulative: [['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08173_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00148_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00973_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn08173_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:01:22,646 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:22,782 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 20:01:22,807 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:24,581 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 20:01:24,614 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:25,474 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 20:01:25,506 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:25,563 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 20:01:25,588 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:27,112 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 20:01:27,121 - INFO - cpd00187 not found in model!
2026-01-13 20:01:27,122 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:01:27,128 - INFO - cpd00187 not found in model!
2026-01-13 20:01:27,129 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:01:27,138 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:27,349 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 20:01:27,379 - INFO - Objective with gapfill database:34.500000000000036; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:27,414 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa7a80b940>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 20:01:27,416 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:27,418 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:27,419 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:27,421 - INFO - integrating rxn: rxn03884_c0
2026-01-13 20:01:27,422 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new']]
2026-01-13 20:01:27,442 - INFO - Glc.O2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:5
2026-01-13 20:01:27,443 - INFO - Glc.O2/rxn00062_c0:rxn07191_c0< needed:0.5 with min obj:5
2026-01-13 20:01:27,444 - INFO - Glc.O2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:5
2026-01-13 20:01:27,445 - INFO - Glc.O2/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:5
2026-01-13 20:01:27,448 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa7a80b940>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:27,449 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa7a80b940>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 20:01:27,452 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new']]
2026-01-13 20:01:27,460 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 20:01:27,478 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:27,484 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 20:01:27,514 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00781_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c5f60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:27,516 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 20:01:27,519 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:27,520 - INFO - integrating rxn: rxn05602_c0
2026-01-13 20:01:27,522 - INFO - integrating rxn: rxn05938_c0
2026-01-13 20:01:27,524 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:27,525 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:27,526 - INFO - integrating rxn: rxn00781_c0
2026-01-13 20:01:27,527 - INFO - Full solution: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01343_c0', '>', 'new'], ['rxn00781_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 20:01:27,535 - INFO - Llac/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:0.01
2026-01-13 20:01:27,536 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:27,537 - INFO - Llac/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:27,538 - INFO - Llac/rxn00062_c0:rxn05938_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:27,539 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:27,540 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:27,541 - INFO - Llac/rxn00062_c0:rxn00781_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:27,547 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c5f60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00781_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:27,547 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'EX_cpd00363_e0': '>', 'rxn05602_c0': '>', 'rxn05938_c0': '<', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00781_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9fa6c5f60>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:27,551 - INFO - Cumulative: [['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01343_c0', '>', 'new'], ['rxn00781_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01343_c0', '>', 'new'], ['rxn00781_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn01343_c0', '>', 'new'], ['rxn00781_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05938_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 20:01:27,574 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:27,829 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 20:01:27,865 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 20:01:27,898 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'rxn00248_c0': '>', 'rxn00499_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c5990>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:27,900 - INFO - integrating rxn: rxn00248_c0
2026-01-13 20:01:27,901 - INFO - integrating rxn: rxn00499_c0
2026-01-13 20:01:27,902 - INFO - integrating rxn: rxn00250_c0
2026-01-13 20:01:27,903 - INFO - integrating rxn: rxn05319_c0
2026-01-13 20:01:27,904 - INFO - Full solution: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:01:27,920 - INFO - Fum/rxn00062_c0:rxn00248_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:27,921 - INFO - Fum/rxn00062_c0:rxn00499_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:27,922 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:27,924 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:27,931 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c5990>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'rxn00248_c0': '>', 'rxn00499_c0': '<'}, 'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}}
2026-01-13 20:01:27,932 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'rxn00248_c0': '>', 'rxn00499_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c5990>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:27,936 - INFO - Cumulative: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:01:27,963 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:29,568 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:29,602 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

Removing ungapfillable media Dimethylamine.H2

2026-01-13 20:01:29,638 - INFO - Objective with gapfill database:34.49999999999999; min objective:0.01
2026-01-13 20:01:29,671 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6b88fd0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}
2026-01-13 20:01:29,675 - INFO - integrating rxn: rxn01476_c0
2026-01-13 20:01:29,677 - INFO - integrating rxn: rxn03884_c0
2026-01-13 20:01:29,679 - INFO - integrating rxn: rxn01477_c0
2026-01-13 20:01:29,679 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new']]
2026-01-13 20:01:29,704 - INFO - Glc.O2/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:5
2026-01-13 20:01:29,706 - INFO - rxn03884_c0> not needed:13.0
2026-01-13 20:01:29,707 - INFO - rxn01477_c0> not needed:13.0
2026-01-13 20:01:29,711 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6b88fd0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False, 'new': {'rxn01476_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:29,712 - INFO - Unneeded: [['rxn03884_c0', '>', 'new', 100, None], ['rxn01477_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {}, 'new': {'rxn01476_c0': '>', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6b88fd0>, 'target': 'rxn00062_c0', 'minobjective': 5, 'binary_check': False}

2026-01-13 20:01:29,716 - INFO - Cumulative: [['rxn01476_c0', '>', 'new']]
2026-01-13 20:01:29,741 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:32,747 - WARNING - No gapfilling solution found for ANME activating rxn00062_c0
2026-01-13 20:01:32,769 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:32,864 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 20:01:32,877 - INFO - cpd01024 not found in model!
2026-01-13 20:01:32,878 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:32,892 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:33,281 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 20:01:33,307 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:33,493 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 20:01:33,517 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:34,403 - WARNING - No gapfilling solution found before filtering for Akg.O2 activating rxn00062_c0

Removing ungapfillable media Akg.O2

2026-01-13 20:01:34,425 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:35,292 - WARNING - No gapfilling solution found for Trimethylamine.H2 activating rxn00062_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:35,641 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 20:01:35,665 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 20:01:35,696 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dcf0400>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:35,698 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:35,700 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:35,701 - INFO - integrating rxn: rxn01476_c0
2026-01-13 20:01:35,702 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:35,702 - INFO - integrating rxn: rxn03884_c0
2026-01-13 20:01:35,703 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:35,709 - INFO - cpd08021 not found in model!
2026-01-13 20:01:35,710 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 20:01:35,714 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:35,715 - INFO - rxn07191_c0< not needed:0.5
2026-01-13 20:01:35,716 - INFO - Glc.DMSO/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:35,718 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:35,719 - INFO - Glc.DMSO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:35,724 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dcf0400>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:35,725 - INFO - Unneeded: [['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dcf0400>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:35,730 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:35,753 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 20:01:35,784 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dcf01f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:35,785 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:35,786 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:35,787 - INFO - integrating rxn: rxn01476_c0
2026-01-13 20:01:35,788 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:35,789 - INFO - integrating rxn: rxn03884_c0
2026-01-13 20:01:35,790 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:35,795 - INFO - cpd00811 not found in model!
2026-01-13 20:01:35,796 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 20:01:35,800 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:35,801 - INFO - rxn07191_c0< not needed:0.5
2026-01-13 20:01:35,802 - INFO - Glc.TMAO/rxn00062_c0:rxn01476_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:35,803 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:35,804 - INFO - Glc.TMAO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:35,809 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dcf01f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:35,810 - INFO - Unneeded: [['rxn07191_c0', '<', 'new', -100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn01476_c0': '>', 'rxn05553_c0': '>', 'rxn03884_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa0dcf01f0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:35,814 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn00512_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00047_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:35,836 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:35,878 - INFO - Loading model: Hungateiclostridiaceae.31
2026-01-13 20:01:36,102 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 20:01:36,504 - INFO -   Loading template...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:36,810 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 20:01:36,825 - INFO - cpd11632 not found in model!
2026-01-13 20:01:36,826 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 20:01:36,841 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:36,979 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:36,985 - INFO -   Gapfilling with AuxoMedia...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:37,631 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 20:01:37,661 - INFO - Objective with gapfill database:19.125000000000007; min objective:0.01
2026-01-13 20:01:37,696 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn05581_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824b610>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 20:01:37,699 - INFO - integrating rxn: rxn05581_c0
2026-01-13 20:01:37,699 - INFO - Full solution: [['rxn05581_c0', '<', 'new']]
2026-01-13 20:01:37,720 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 20:01:37,723 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824b610>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn05581_c0': '<'}, 'reversed': {}}
2026-01-13 20:01:37,724 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn05581_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824b610>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 20:01:37,729 - INFO - Cumulative: [['rxn05581_c0', '<', 'new']]
2026-01-13 20:01:37,757 - INFO - Objective with gapfill database:18.250000000000007; min objective:0.01
2026-01-13 20:01:37,791 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn09269_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824b190>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 20:01:37,793 - INFO - integrating rxn: rxn09269_c0
2026-01-13 20:01:37,794 - INFO - Full solution: [['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 20:01:37,804 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 20:01:37,812 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824b190>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn09269_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:37,812 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn09269_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824b190>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 20:01:37,816 - INFO - Cumulative: [['rxn05581_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 20:01:37,843 - INFO - Objective with gapfill database:16.250000000000004; min objective:0.01
2026-01-13 20:01:37,877 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824ac20>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 20:01:37,879 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 20:01:37,881 - INFO - integrating rxn: rxn05602_c0
2026-01-13 20:01:37,882 - INFO - Full solution: [['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 20:01:37,892 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 20:01:37,893 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 20:01:37,901 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824ac20>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:37,902 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824ac20>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 20:01:37,907 - INFO - Cumulative: [['rxn05581_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 20:01:37,934 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:39,488 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 20:01:39,520 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:40,776 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 20:01:40,785 - WARNING - No gapfilling solution found before filtering for Methanol.H2 activating rxn00062_c0

Removing ungapfillable media Methanol.H2

2026-01-13 20:01:40,800 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:40,811 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:41,196 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 20:01:41,221 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:41,392 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 20:01:41,422 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:41,426 - WARNING - No gapfilling solution found before filtering for H2.SO4 activating rxn00062_c0

Removing ungapfillable media H2.SO4

2026-01-13 20:01:41,439 - INFO - cpd11632 not found in model!
2026-01-13 20:01:41,440 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 20:01:41,456 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:41,572 - WARNING - No gapfilling solution found before filtering for Pyr.NO activating rxn00062_c0

Removing ungapfillable media Pyr.NO

2026-01-13 20:01:41,606 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:41,814 - WARNING - No gapfilling solution found for Ac.NO2 activating rxn00062_c0
2026-01-13 20:01:41,838 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:42,151 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 20:01:42,173 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:43,869 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 20:01:43,897 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:44,574 - WARNING - No gapfilling solution found for Etho activating rxn00062_c0
2026-01-13 20:01:44,602 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:44,782 - INFO - Objective with gapfill database:34.50000000000001; min objective:0.01
2026-01-13 20:01:44,826 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:46,388 - WARNING - No gapfilling solution found for For activating rxn00062_c0
2026-01-13 20:01:46,413 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:47,348 - WARNING - No gapfilling solution found for Akg activating rxn00062_c0
2026-01-13 20:01:47,376 - INFO - Objective with gapfill database:0.75; min objective:0.01
2026-01-13 20:01:47,410 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c5d50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:47,413 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:47,414 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:47,416 - INFO - integrating rxn: rxn00499_c0
2026-01-13 20:01:47,418 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:47,419 - INFO - Full solution: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 20:01:47,429 - INFO - Llac/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:01:47,431 - INFO - Llac/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:47,432 - INFO - Llac/rxn00062_c0:rxn00499_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:47,433 - INFO - Llac/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:47,441 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c5d50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:47,442 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00499_c0': '>', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9f29c5d50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:47,448 - INFO - Cumulative: [['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00506_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['rxn00544_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00256_c0', '<', 'new'], ['rxn00285_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new']]
2026-01-13 20:01:47,475 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:48,172 - WARNING - No gapfilling solution found for Methanol activating rxn00062_c0
2026-01-13 20:01:48,181 - INFO - cpd00187 not found in model!
2026-01-13 20:01:48,182 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:01:48,187 - INFO - cpd00187 not found in model!
2026-01-13 20:01:48,188 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:01:48,198 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:49,194 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 20:01:49,225 - INFO - Objective with gapfill database:19.124999999999993; min objective:0.01
2026-01-13 20:01:49,260 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05581_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00935_c0': '<', 'rxn14426_c0': '>', 'rxn00172_c0': '<', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea3ab30>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 20:01:49,263 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 20:01:49,264 - INFO - integrating rxn: rxn05581_c0
2026-01-13 20:01:49,266 - INFO - integrating rxn: rxn05488_c0
2026-01-13 20:01:49,267 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:49,269 - INFO - integrating rxn: rxn14425_c0
2026-01-13 20:01:49,271 - INFO - integrating rxn: rxn00935_c0
2026-01-13 20:01:49,273 - INFO - integrating rxn: rxn14426_c0
2026-01-13 20:01:49,275 - INFO - integrating rxn: rxn00172_c0
2026-01-13 20:01:49,276 - INFO - integrating rxn: rxn00251_c0
2026-01-13 20:01:49,277 - INFO - integrating rxn: rxn00250_c0
2026-01-13 20:01:49,278 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn00172_c0', '<', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 20:01:49,288 - INFO - EX_cpd00029_e0> not needed:16.25
2026-01-13 20:01:49,290 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 20:01:49,291 - INFO - rxn05488_c0< not needed:16.25
2026-01-13 20:01:49,292 - INFO - rxn07191_c0< not needed:14.25
2026-01-13 20:01:49,294 - INFO - Glyc.O2/rxn00062_c0:rxn14425_c0> needed:0.0 with min obj:2
2026-01-13 20:01:49,295 - INFO - rxn00935_c0< not needed:13.375
2026-01-13 20:01:49,298 - INFO - Glyc.O2/rxn00062_c0:rxn14426_c0> needed:0.0 with min obj:2
2026-01-13 20:01:49,299 - INFO - rxn00172_c0< not needed:13.375
2026-01-13 20:01:49,301 - INFO - rxn00251_c0< not needed:11.250000000000002
2026-01-13 20:01:49,302 - INFO - rxn00250_c0< not needed:11.250000000000002
2026-01-13 20:01:49,313 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea3ab30>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn05581_c0': '<', 'rxn14425_c0': '>', 'rxn14426_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:49,314 - INFO - Unneeded: [['EX_cpd00029_e0', '>', 'new', 100, None], ['rxn05488_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None], ['rxn00935_c0', '<', 'new', -100, None], ['rxn00172_c0', '<', 'new', -100, None], ['rxn00251_c0', '<', 'new', -100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05581_c0': '<', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn00935_c0': '<', 'rxn14426_c0': '>', 'rxn00172_c0': '<', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea3ab30>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 20:01:49,318 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new']]

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:49,347 - INFO - Objective with gapfill database:17.49999999999999; min objective:0.01
2026-01-13 20:01:49,369 - WARNING - No gapfilling solution found before filtering for Dlac.O2 activating rxn00062_c0

Removing ungapfillable media Dlac.O2

2026-01-13 20:01:49,380 - INFO - Initial solution: {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea38220>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}
2026-01-13 20:01:49,381 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:01:49,383 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:49,383 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:01:49,384 - INFO - integrating rxn: rxn05319_c0
2026-01-13 20:01:49,385 - INFO - integrating rxn: rxn00250_c0
2026-01-13 20:01:49,386 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 20:01:49,393 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 20:01:49,396 - INFO - Fum.O2/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:3
2026-01-13 20:01:49,397 - INFO - Fum.O2/rxn00062_c0:rxn07191_c0< needed:1.0 with min obj:3
2026-01-13 20:01:49,399 - INFO - Fum.O2/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:3
2026-01-13 20:01:49,400 - INFO - Fum.O2/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:3
2026-01-13 20:01:49,402 - INFO - Fum.O2/rxn00062_c0:rxn00250_c0< needed:1.0 with min obj:3
2026-01-13 20:01:49,409 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea38220>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}}
2026-01-13 20:01:49,410 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn05319_c0': '>', 'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea38220>, 'target': 'rxn00062_c0', 'minobjective': 3, 'binary_check': False}

2026-01-13 20:01:49,412 - INFO - Objective with gapfill database:0.0; min objective:0.01

2026-01-13 20:01:49,414 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00250_c0', '<', 'reversed']]
2026-01-13 20:01:49,441 - INFO - Objective with gapfill database:18.249999999999993; min objective:0.01
2026-01-13 20:01:49,475 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14418_c0': '>', 'rxn14420_c0': '>', 'rxn09269_c0': '>', 'rxn14419_c0': '>', 'rxn00172_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea38430>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 20:01:49,478 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 20:01:49,479 - INFO - integrating rxn: rxn05488_c0
2026-01-13 20:01:49,480 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:49,482 - INFO - integrating rxn: rxn14418_c0
2026-01-13 20:01:49,484 - INFO - integrating rxn: rxn14420_c0
2026-01-13 20:01:49,486 - INFO - integrating rxn: rxn09269_c0
2026-01-13 20:01:49,487 - INFO - integrating rxn: rxn14419_c0
2026-01-13 20:01:49,489 - INFO - integrating rxn: rxn00172_c0
2026-01-13 20:01:49,489 - INFO - integrating rxn: rxn00250_c0
2026-01-13 20:01:49,490 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00029_e0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn14418_c0', '>', 'new'], ['rxn14420_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn14419_c0', '>', 'new'], ['rxn00172_c0', '<', 'new']]
2026-01-13 20:01:49,500 - INFO - EX_cpd00029_e0> not needed:15.375
2026-01-13 20:01:49,501 - INFO - rxn05488_c0< not needed:15.375
2026-01-13 20:01:49,502 - INFO - rxn07191_c0< not needed:13.375
2026-01-13 20:01:49,504 - INFO - rxn14418_c0> not needed:9.0
2026-01-13 20:01:49,505 - INFO - Succ.O2/rxn00062_c0:rxn14420_c0> needed:0.0 with min obj:2
2026-01-13 20:01:49,506 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 20:01:49,507 - INFO - Succ.O2/rxn00062_c0:rxn14419_c0> needed:0.0 with min obj:2
2026-01-13 20:01:49,509 - INFO - rxn00172_c0< not needed:9.0
2026-01-13 20:01:49,510 - INFO - rxn00250_c0< not needed:7.000000000000001
2026-01-13 20:01:49,520 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea38430>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn14420_c0': '>', 'rxn09269_c0': '>', 'rxn14419_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:49,520 - INFO - Unneeded: [['EX_cpd00029_e0', '>', 'new', 100, None], ['rxn05488_c0', '<', 'new', -100, None], ['rxn07191_c0', '<', 'new', -100, None], ['rxn14418_c0', '>', 'new', 100, None], ['rxn00172_c0', '<', 'new', -100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00029_e0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14418_c0': '>', 'rxn14420_c0': '>', 'rxn09269_c0': '>', 'rxn14419_c0': '>', 'rxn00172_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea38430>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 20:01:49,524 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00250_c0', '<', 'reversed'], ['rxn14420_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn14419_c0', '>', 'new']]
2026-01-13 20:01:49,551 - INFO - Objective with gapfill database:16.25000000000001; min objective:0.01
2026-01-13 20:01:49,585 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn14426_c0': '>', 'rxn00172_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea38970>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 20:01:49,587 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 20:01:49,589 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 20:01:49,590 - INFO - integrating rxn: rxn05602_c0
2026-01-13 20:01:49,592 - INFO - integrating rxn: rxn05488_c0
2026-01-13 20:01:49,593 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:01:49,593 - INFO - integrating rxn: rxn14425_c0
2026-01-13 20:01:49,594 - INFO - integrating rxn: rxn14426_c0
2026-01-13 20:01:49,595 - INFO - integrating rxn: rxn00172_c0
2026-01-13 20:01:49,596 - INFO - Full solution: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00250_c0', '<', 'reversed'], ['rxn14420_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn14419_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00172_c0', '<', 'new']]
2026-01-13 20:01:49,605 - INFO - LLac.O2/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:2
2026-01-13 20:01:49,607 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 20:01:49,608 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 20:01:49,609 - INFO - LLac.O2/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:2
2026-01-13 20:01:49,610 - INFO - LLac.O2/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:2
2026-01-13 20:01:49,611 - INFO - LLac.O2/rxn00062_c0:rxn14425_c0> needed:0.0 with min obj:2
2026-01-13 20:01:49,612 - INFO - LLac.O2/rxn00062_c0:rxn14426_c0> needed:0.0 with min obj:2
2026-01-13 20:01:49,613 - INFO - LLac.O2/rxn00062_c0:rxn00172_c0< needed:0.0 with min obj:2
2026-01-13 20:01:49,620 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea38970>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn14426_c0': '>', 'rxn00172_c0': '<'}, 'reversed': {}}
2026-01-13 20:01:49,621 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '<', 'rxn05602_c0': '>', 'rxn05488_c0': '<', 'rxn07191_c0': '<', 'rxn14425_c0': '>', 'rxn14426_c0': '>', 'rxn00172_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9cea38970>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 20:01:49,625 - INFO - Cumulative: [['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00250_c0', '<', 'reversed'], ['rxn14420_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn14419_c0', '>', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn14425_c0', '>', 'new'], ['rxn14426_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00250_c0', '<', 'reversed'], ['rxn14420_c0', '>', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn14419_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00172_c0', '<', 'new']]
2026-01-13 20:01:49,652 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:50,001 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 20:01:50,027 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 20:01:50,058 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928fbe0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:50,060 - INFO - integrating rxn: rxn00083_c0
2026-01-13 20:01:50,061 - INFO - integrating rxn: rxn00499_c0
2026-01-13 20:01:50,062 - INFO - integrating rxn: rxn03884_c0
2026-01-13 20:01:50,063 - INFO - integrating rxn: rxn01477_c0
2026-01-13 20:01:50,064 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:50,069 - INFO - cpd08021 not found in model!
2026-01-13 20:01:50,070 - INFO - Media compound: cpd08021 not found in model.
2026-01-13 20:01:50,074 - INFO - Glc.DMSO/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:50,075 - INFO - Glc.DMSO/rxn00062_c0:rxn00499_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:50,076 - INFO - Glc.DMSO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:50,077 - INFO - Glc.DMSO/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:50,083 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928fbe0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:50,084 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928fbe0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:50,087 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:50,110 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 20:01:50,139 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928fe50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:01:50,142 - INFO - integrating rxn: rxn00083_c0
2026-01-13 20:01:50,143 - INFO - integrating rxn: rxn00499_c0
2026-01-13 20:01:50,144 - INFO - integrating rxn: rxn03884_c0
2026-01-13 20:01:50,144 - INFO - integrating rxn: rxn01477_c0
2026-01-13 20:01:50,145 - INFO - Full solution: [['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:50,151 - INFO - cpd00811 not found in model!
2026-01-13 20:01:50,151 - INFO - Media compound: cpd00811 not found in model.
2026-01-13 20:01:50,154 - INFO - Glc.TMAO/rxn00062_c0:rxn00083_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:50,155 - INFO - Glc.TMAO/rxn00062_c0:rxn00499_c0< needed:0.0 with min obj:0.01
2026-01-13 20:01:50,157 - INFO - Glc.TMAO/rxn00062_c0:rxn03884_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:50,158 - INFO - Glc.TMAO/rxn00062_c0:rxn01477_c0> needed:0.0 with min obj:0.01
2026-01-13 20:01:50,164 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928fe50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:50,164 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'rxn00083_c0': '>', 'rxn00499_c0': '<', 'rxn03884_c0': '>', 'rxn01477_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2928fe50>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:01:50,167 - INFO - Cumulative: [['rxn00083_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new'], ['rxn00083_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00615_c0', '>', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05939_c0', '<', 'new'], ['rxn00505_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00285_c0', '<', 'reversed'], ['EX_cpd00106_e0', '<', 'new'], ['rxn05561_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn08094_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00036_e0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn00499_c0', '>', 'new'], ['rxn00499_c0', '<', 'new'], ['EX_cpd00363_e0', '>', 'new'], ['rxn00935_c0', '<', 'new'], ['rxn00157_c0', '<', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn05559_c0', '<', 'new'], ['rxn00616_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn00288_c0', '>', 'new']]
2026-01-13 20:01:50,190 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:50,326 - WARNING - No gapfilling solution found before filtering for Ac.O2 activating rxn00062_c0

Removing ungapfillable media Ac.O2

2026-01-13 20:01:50,359 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:50,466 - WARNING - No gapfilling solution found for Etho.O2 activating rxn00062_c0
2026-01-13 20:01:50,491 - INFO - Objective with gapfill database:19.125000000000014; min objective:0.01
2026-01-13 20:01:50,523 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6676590>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 20:01:50,526 - INFO - integrating rxn: EX_cpd00100_e0
2026-01-13 20:01:50,527 - INFO - integrating rxn: rxn05581_c0
2026-01-13 20:01:50,528 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new']]
2026-01-13 20:01:50,537 - INFO - Glyc.O2/rxn00062_c0:EX_cpd00100_e0< needed:0.0 with min obj:2
2026-01-13 20:01:50,538 - INFO - Glyc.O2/rxn00062_c0:rxn05581_c0< needed:0.0 with min obj:2
2026-01-13 20:01:50,544 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6676590>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<'}, 'reversed': {}}
2026-01-13 20:01:50,545 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00100_e0': '<', 'rxn05581_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6676590>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 20:01:50,549 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new']]
2026-01-13 20:01:50,572 - INFO - Objective with gapfill database:18.25000000000003; min objective:0.01
2026-01-13 20:01:50,602 - INFO - Initial solution: {'reversed': {}, 'new': {'rxn09269_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6676b60>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 20:01:50,605 - INFO - integrating rxn: rxn09269_c0
2026-01-13 20:01:50,606 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 20:01:50,613 - INFO - Succ.O2/rxn00062_c0:rxn09269_c0> needed:0.0 with min obj:2
2026-01-13 20:01:50,619 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6676b60>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'rxn09269_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:50,620 - INFO - Unneeded: []

Adding gapfillingNeither carbon consumption nor oxygen consumption are defined in
{'reversed': {}, 'new': {'rxn09269_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6676b60>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 20:01:50,625 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new']]
2026-01-13 20:01:50,649 - INFO - Objective with gapfill database:16.249999999999996; min objective:0.01
2026-01-13 20:01:50,670 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 20:01:50,680 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6677070>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}
2026-01-13 20:01:50,682 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 20:01:50,684 - INFO - integrating rxn: rxn05602_c0
2026-01-13 20:01:50,685 - INFO - Full solution: [['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 20:01:50,692 - INFO - LLac.O2/rxn00062_c0:EX_cpd00159_e0< needed:0.0 with min obj:2
2026-01-13 20:01:50,693 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:50,694 - INFO - LLac.O2/rxn00062_c0:rxn05602_c0> needed:0.0 with min obj:2
2026-01-13 20:01:50,700 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6677070>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>'}, 'reversed': {}}
2026-01-13 20:01:50,701 - INFO - Unneeded: []

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00159_e0': '<', 'rxn05602_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9e6677070>, 'target': 'rxn00062_c0', 'minobjective': 2, 'binary_check': False}

2026-01-13 20:01:50,704 - INFO - Cumulative: [['rxn01476_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01476_c0', '>', 'new'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new']]
2026-01-13 20:01:50,727 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:52,583 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,616 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,639 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,661 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,684 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,706 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,728 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,750 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,773 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,796 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,818 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,840 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,863 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:52,888 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,910 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,933 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,946 - WARNING - No gapfilling solution found before filtering for Pyr.DMSO activating rxn00062_c0

Removing ungapfillable media Pyr.DMSO

2026-01-13 20:01:52,955 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:52,978 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:52,980 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,003 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,025 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,048 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,070 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,092 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,115 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,137 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,160 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,182 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,203 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,225 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,246 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,268 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,290 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,311 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,333 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,355 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,376 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,398 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,419 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,441 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,462 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,488 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,510 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,532 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,554 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,576 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,597 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,615 - INFO - cpd11632 not found in model!
2026-01-13 20:01:53,616 - INFO - Media compound: cpd11632 not found in model.
2026-01-13 20:01:53,621 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,638 - INFO - cpd01024 not found in model!
2026-01-13 20:01:53,639 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:53,644 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,662 - INFO - cpd01024 not found in model!
2026-01-13 20:01:53,662 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:01:53,667 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,689 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,710 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2026-01-13 20:01:53,728 - INFO - cpd00187 not found in model!
2026-01-13 20:01:53,728 - INFO - Media compound: cpd00187 not found in model.
2026-01-13 20:01:53,733 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:53,754 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

2026-01-13 20:01:53,776 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:53,884 - WARNING - No gapfilling solution found for Pyr.TMAO activating rxn00062_c0
2026-01-13 20:01:53,919 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:01:55,979 - INFO - Objective with gapfill database:143.82315796111237; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:01:58,358 - WARNING - No gapfilling solution found for Trimethylamine.H2 activating rxn00062_c0
2026-01-13 20:01:58,413 - INFO - Objective with gapfill database:143.82315796111237; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:02:03,190 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 20:02:03,197 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn08710_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn21635_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15060_c0': '>', 'rxn15270_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn47493_c0': '>', 'rxn14423_c0': '>', 'rxn11382_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:02:03,200 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 20:02:03,202 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 20:02:03,204 - INFO - integrating rxn: rxn08709_c0
2026-01-13 20:02:03,206 - INFO - integrating rxn: rxn03086_c0
2026-01-13 20:02:03,208 - INFO - integrating rxn: rxn00800_c0
2026-01-13 20:02:03,209 - INFO - integrating rxn: rxn10336_c0
2026-01-13 20:02:03,210 - INFO - integrating rxn: rxn03030_c0
2026-01-13 20:02:03,212 - INFO - integrating rxn: rxn08710_c0
2026-01-13 20:02:03,214 - INFO - integrating rxn: rxn02331_c0
2026-01-13 20:02:03,215 - INFO - integrating rxn: rxn12512_c0
2026-01-13 20:02:03,217 - INFO - integrating rxn: rxn08583_c0
2026-01-13 20:02:03,219 - INFO - integrating rxn: rxn10481_c0
2026-01-13 20:02:03,220 - INFO - integrating rxn: rxn03918_c0
2026-01-13 20:02:03,222 - INFO - integrating rxn: rxn08708_c0
2026-01-13 20:02:03,224 - INFO - integrating rxn: rxn05229_c0
2026-01-13 20:02:03,226 - INFO - integrating rxn: rxn02404_c0
2026-01-13 20:02:03,228 - INFO - integrating rxn: rxn00392_c0
2026-01-13 20:02:03,230 - INFO - integrating rxn: rxn09225_c0
2026-01-13 20:02:03,232 - INFO - integrating rxn: rxn02774_c0
2026-01-13 20:02:03,234 - INFO - integrating rxn: rxn03919_c0
2026-01-13 20:02:03,236 - INFO - integrating rxn: rxn08954_c0
2026-01-13 20:02:03,238 - INFO - integrating rxn: rxn00916_c0
2026-01-13 20:02:03,239 - INFO - integrating rxn: rxn08712_c0
2026-01-13 20:02:03,241 - INFO - integrating rxn: rxn08618_c0
2026-01-13 20:02:03,243 - INFO - integrating rxn: rxn11703_c0
2026-01-13 20:02:03,244 - INFO - integrating rxn: rxn06848_c0
2026-01-13 20:02:03,246 - INFO - integrating rxn: rxn03537_c0
2026-01-13 20:02:03,247 - INFO - integrating rxn: rxn00966_c0
2026-01-13 20:02:03,249 - INFO - integrating rxn: rxn08528_c0
2026-01-13 20:02:03,250 - INFO - integrating rxn: rxn03916_c0
2026-01-13 20:02:03,252 - INFO - integrating rxn: rxn09106_c0
2026-01-13 20:02:03,254 - INFO - integrating rxn: rxn08711_c0
2026-01-13 20:02:03,255 - INFO - integrating rxn: rxn04413_c0
2026-01-13 20:02:03,257 - INFO - integrating rxn: rxn01539_c0
2026-01-13 20:02:03,258 - INFO - integrating rxn: rxn04139_c0
2026-01-13 20:02:03,260 - INFO - integrating rxn: rxn03146_c0
2026-01-13 20:02:03,262 - INFO - integrating rxn: rxn03893_c0
2026-01-13 20:02:03,263 - INFO - integrating rxn: rxn02405_c0
2026-01-13 20:02:03,263 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:02:03,265 - INFO - integrating rxn: rxn01537_c0
2026-01-13 20:02:03,267 - INFO - integrating rxn: rxn02303_c0
2026-01-13 20:02:03,268 - INFO - integrating rxn: rxn01213_c0
2026-01-13 20:02:03,269 - INFO - integrating rxn: rxn03136_c0
2026-01-13 20:02:03,271 - INFO - integrating rxn: rxn00350_c0
2026-01-13 20:02:03,272 - INFO - integrating rxn: rxn11702_c0
2026-01-13 20:02:03,274 - INFO - integrating rxn: rxn03084_c0
2026-01-13 20:02:03,276 - INFO - integrating rxn: rxn03439_c0
2026-01-13 20:02:03,278 - INFO - integrating rxn: rxn02056_c0
2026-01-13 20:02:03,279 - INFO - integrating rxn: rxn00122_c0
2026-01-13 20:02:03,281 - INFO - integrating rxn: rxn08713_c0
2026-01-13 20:02:03,282 - INFO - integrating rxn: rxn08620_c0
2026-01-13 20:02:03,284 - INFO - integrating rxn: rxn02287_c0
2026-01-13 20:02:03,285 - INFO - integrating rxn: rxn02288_c0
2026-01-13 20:02:03,287 - INFO - integrating rxn: rxn04308_c0
2026-01-13 20:02:03,288 - INFO - integrating rxn: rxn01258_c0
2026-01-13 20:02:03,289 - INFO - integrating rxn: rxn05255_c0
2026-01-13 20:02:03,291 - INFO - integrating rxn: rxn05464_c0
2026-01-13 20:02:03,292 - INFO - integrating rxn: rxn02341_c0
2026-01-13 20:02:03,293 - INFO - integrating rxn: rxn03511_c0
2026-01-13 20:02:03,295 - INFO - integrating rxn: rxn03182_c0
2026-01-13 20:02:03,296 - INFO - integrating rxn: rxn08619_c0
2026-01-13 20:02:03,298 - INFO - integrating rxn: rxn21635_c0
2026-01-13 20:02:03,314 - INFO - integrating rxn: rxn14424_c0
2026-01-13 20:02:03,329 - INFO - integrating rxn: rxn12930_c0
2026-01-13 20:02:03,341 - INFO - integrating rxn: rxn12940_c0
2026-01-13 20:02:03,343 - INFO - integrating rxn: rxn12929_c0
2026-01-13 20:02:03,344 - INFO - integrating rxn: rxn12938_c0
2026-01-13 20:02:03,347 - INFO - integrating rxn: rxn12927_c0
2026-01-13 20:02:03,349 - INFO - integrating rxn: rxn12921_c0
2026-01-13 20:02:03,351 - INFO - integrating rxn: rxn12943_c0
2026-01-13 20:02:03,352 - INFO - integrating rxn: rxn02485_c0
2026-01-13 20:02:03,354 - INFO - integrating rxn: rxn12934_c0
2026-01-13 20:02:03,358 - INFO - integrating rxn: rxn25474_c0
2026-01-13 20:02:03,360 - INFO - integrating rxn: rxn12941_c0
2026-01-13 20:02:03,363 - INFO - integrating rxn: rxn15167_c0
2026-01-13 20:02:03,367 - INFO - integrating rxn: rxn19346_c0
2026-01-13 20:02:03,368 - INFO - integrating rxn: rxn04551_c0
2026-01-13 20:02:03,370 - INFO - integrating rxn: rxn03396_c0
2026-01-13 20:02:03,371 - INFO - integrating rxn: rxn25479_c0
2026-01-13 20:02:03,373 - INFO - integrating rxn: rxn22114_c0
2026-01-13 20:02:03,374 - INFO - integrating rxn: rxn16114_c0
2026-01-13 20:02:03,376 - INFO - integrating rxn: rxn15060_c0
2026-01-13 20:02:03,377 - INFO - integrating rxn: rxn15270_c0
2026-01-13 20:02:03,378 - INFO - integrating rxn: rxn08233_c0
2026-01-13 20:02:03,380 - INFO - integrating rxn: rxn20508_c0
2026-01-13 20:02:03,381 - INFO - integrating rxn: rxn20627_c0
2026-01-13 20:02:03,383 - INFO - integrating rxn: rxn30917_c0
2026-01-13 20:02:03,384 - INFO - integrating rxn: rxn15939_c0
2026-01-13 20:02:03,386 - INFO - integrating rxn: rxn40674_c0
2026-01-13 20:02:03,387 - INFO - integrating rxn: rxn09037_c0
2026-01-13 20:02:03,390 - INFO - integrating rxn: rxn08921_c0
2026-01-13 20:02:03,391 - INFO - integrating rxn: rxn29260_c0
2026-01-13 20:02:03,393 - INFO - integrating rxn: rxn47493_c0
2026-01-13 20:02:05,589 - INFO - integrating rxn: rxn14423_c0
2026-01-13 20:02:05,591 - INFO - integrating rxn: rxn11382_c0
2026-01-13 20:02:05,594 - INFO - integrating rxn: rxn10042_c0
2026-01-13 20:02:05,596 - INFO - integrating rxn: rxn43975_c0
2026-01-13 20:02:05,599 - INFO - integrating rxn: rxn42732_c0
2026-01-13 20:02:05,601 - INFO - integrating rxn: rxn41263_c0
2026-01-13 20:02:05,602 - INFO - integrating rxn: rxn20839_c0
2026-01-13 20:02:05,608 - INFO - Full solution: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn15060_c0', '>', 'new'], ['rxn15270_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn08921_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn47493_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn11382_c0', '>', 'new'], ['rxn10042_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 20:02:05,657 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 20:02:05,659 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 20:02:05,661 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,663 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:05,665 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,667 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,668 - INFO - AuxoMedia/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,670 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,672 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:05,673 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,675 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,677 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,698 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,700 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,701 - INFO - AuxoMedia/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,703 - INFO - AuxoMedia/bio1:rxn02404_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,705 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,707 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,708 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,710 - INFO - AuxoMedia/bio1:rxn03919_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,712 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,714 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,715 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,717 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,719 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,720 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:05,722 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,724 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:05,725 - INFO - AuxoMedia/bio1:rxn08528_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,727 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,729 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,730 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,809 - INFO - AuxoMedia/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,811 - INFO - AuxoMedia/bio1:rxn01539_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:05,845 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,847 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,848 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:05,879 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,845 - INFO - AuxoMedia/bio1:rxn01537_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,849 - INFO - AuxoMedia/bio1:rxn02303_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,865 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,867 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,869 - INFO - AuxoMedia/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:07,871 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,873 - INFO - AuxoMedia/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,875 - INFO - AuxoMedia/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,877 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:07,879 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,881 - INFO - AuxoMedia/bio1:rxn08713_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,883 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,885 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,887 - INFO - AuxoMedia/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,889 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,891 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,893 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,894 - INFO - AuxoMedia/bio1:rxn05464_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,896 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,898 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,900 - INFO - AuxoMedia/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,901 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,904 - INFO - rxn21635_c0> not needed:4.224856868341409
2026-01-13 20:02:07,906 - INFO - rxn14424_c0> not needed:4.224856868341404
2026-01-13 20:02:07,910 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,919 - INFO - rxn12940_c0> not needed:4.224856868341389
2026-01-13 20:02:07,921 - INFO - rxn12929_c0> not needed:4.224856868341389
2026-01-13 20:02:07,925 - INFO - rxn12938_c0> not needed:4.224856868341402
2026-01-13 20:02:07,926 - INFO - rxn12927_c0> not needed:4.22485686834141
2026-01-13 20:02:07,927 - INFO - rxn12921_c0> not needed:4.22485686834141
2026-01-13 20:02:07,932 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,939 - INFO - AuxoMedia/bio1:rxn02485_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,945 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,953 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,965 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,967 - INFO - AuxoMedia/bio1:rxn15167_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:07,969 - INFO - AuxoMedia/bio1:rxn19346_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:08,018 - INFO - rxn04551_c0> not needed:3.4858219731328846
2026-01-13 20:02:09,345 - INFO - AuxoMedia/bio1:rxn03396_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,348 - INFO - AuxoMedia/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,426 - INFO - AuxoMedia/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,438 - INFO - rxn16114_c0> not needed:3.485821973132879
2026-01-13 20:02:09,468 - INFO - rxn15060_c0> not needed:3.4858219731328512
2026-01-13 20:02:09,470 - INFO - rxn15270_c0> not needed:3.485821973132871
2026-01-13 20:02:09,473 - INFO - rxn08233_c0> not needed:3.485821973132871
2026-01-13 20:02:09,479 - INFO - AuxoMedia/bio1:rxn20508_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,483 - INFO - AuxoMedia/bio1:rxn20627_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,496 - INFO - AuxoMedia/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,498 - INFO - AuxoMedia/bio1:rxn15939_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,500 - INFO - AuxoMedia/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,502 - INFO - AuxoMedia/bio1:rxn09037_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,507 - INFO - rxn08921_c0> not needed:3.485821973132901
2026-01-13 20:02:09,509 - INFO - rxn29260_c0> not needed:3.4858219731328615
2026-01-13 20:02:09,511 - INFO - rxn47493_c0> not needed:3.4858219731328783
2026-01-13 20:02:09,513 - INFO - rxn14423_c0> not needed:3.4858219731328783
2026-01-13 20:02:09,514 - INFO - rxn11382_c0> not needed:3.4858219731328783
2026-01-13 20:02:09,582 - INFO - rxn10042_c0> not needed:3.4858219731328783
2026-01-13 20:02:09,915 - INFO - AuxoMedia/bio1:rxn43975_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,920 - INFO - AuxoMedia/bio1:rxn42732_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:09,922 - INFO - AuxoMedia/bio1:rxn41263_c0> needed:0.0 with min obj:0.01

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00393_e0': '<', 'EX_cpd00058_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn08710_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn10481_c0': '>', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn05229_c0': '>', 'rxn02404_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03919_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn11703_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn08528_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn08711_c0': '>', 'rxn04413_c0': '>', 'rxn01539_c0': '<', 'rxn04139_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn01537_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn02056_c0': '<', 'rxn00122_c0': '>', 'rxn08713_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn05464_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn08619_c0': '>', 'rxn21635_c0': '>', 'rxn14424_c0': '>', 'rxn12930_c0': '>', 'rxn12940_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12943_c0': '>', 'rxn02485_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn16114_c0': '>', 'rxn15060_c0': '>', 'rxn15270_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn20627_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn08921_c0': '>', 'rxn29260_c0': '>', 'rxn47493_c0': '>', 'rxn14423_c0': '>', 'rxn11382_c0': '>', 'rxn10042_c0': '>', 'rxn43975_c0': '>', 'rxn42732_c0': '>', 'rxn41263_c0': '>', 'rxn20839_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:02:10,036 - INFO - Cumulative: [['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn02404_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03919_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn08528_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn01539_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01537_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08713_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn05464_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn02485_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn20627_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn43975_c0', '>', 'new'], ['rxn42732_c0', '>', 'new'], ['rxn41263_c0', '>', 'new'], ['rxn20839_c0', '>', 'new']]
2026-01-13 20:02:10,037 - INFO -     Added 81 reactions
2026-01-13 20:02:10,039 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:02:10,405 - WARNING - No gapfilling solution found before filtering for Methane activating rxn00062_c0

Removing ungapfillable media Methane

2026-01-13 20:02:12,615 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:02:18,223 - INFO - Loading model: Hydrogenophaga.6

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:02:30,351 - ERROR - '' is not a valid SBML 'SId'.
2026-01-13 20:02:35,099 - WARNING - No gapfilling solution found for Ac.NO activating rxn00062_c0
2026-01-13 20:02:41,156 - INFO - Objective with gapfill database:143.8231579611124; min objective:0.01
2026-01-13 20:02:42,410 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 20:02:44,787 - INFO -   Loading template...
2026-01-13 20:02:47,137 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa28674f70>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:02:47,141 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:02:47,140 - INFO - Objective with gapfill database:143.8231579611124; min objective:0.01
2026-01-13 20:02:47,142 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:02:47,178 - INFO - integrating rxn: rxn00102_c0
2026-01-13 20:02:47,179 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:02:47,180 - INFO - integrating rxn: rxn00251_c0
2026-01-13 20:02:47,181 - INFO - integrating rxn: rxn00250_c0
2026-01-13 20:02:47,182 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:02:49,085 - INFO - Glc.DMSO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:02:49,087 - INFO - Glc.DMSO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:49,107 - INFO - rxn00102_c0> not needed:2.5
2026-01-13 20:02:49,114 - INFO - Glc.DMSO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:49,422 - INFO - Glc.DMSO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:49,424 - INFO - rxn00250_c0< not needed:2.5
2026-01-13 20:02:49,432 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa28674f70>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 20:02:49,504 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa28674f70>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:02:49,509 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:02:49,537 - INFO - Objective with gapfill database:3.4999999999999996; min objective:0.01
2026-01-13 20:02:49,567 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2869f4c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:02:49,618 - INFO - integrating rxn: EX_cpd00363_e0
2026-01-13 20:02:49,662 - INFO - integrating rxn: rxn07191_c0
2026-01-13 20:02:49,663 - INFO - integrating rxn: rxn00102_c0
2026-01-13 20:02:49,664 - INFO - integrating rxn: rxn05553_c0
2026-01-13 20:02:49,691 - INFO - integrating rxn: rxn00251_c0
2026-01-13 20:02:49,692 - INFO - integrating rxn: rxn00250_c0
2026-01-13 20:02:49,693 - INFO - Full solution: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:02:49,702 - INFO - Glc.TMAO/rxn00062_c0:EX_cpd00363_e0> needed:0.0 with min obj:0.01
2026-01-13 20:02:49,703 - INFO - Glc.TMAO/rxn00062_c0:rxn07191_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:49,704 - INFO - rxn00102_c0> not needed:2.5
2026-01-13 20:02:50,806 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01362_c0': '<', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn10204_c0': '>', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01505_c0': '>', 'rxn00237_c0': '>', 'rxn10124_c0': '<', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn01518_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn01300_c0': '>', 'rxn13647_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05119_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05463_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03990_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn05618_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn01790_c0': '<', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn02003_c0': '<', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn00467_c0': '<', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn01286_c0': '>', 'rxn00117_c0': '>', 'rxn00293_c0': '>', 'rxn00399_c0': '>', 'rxn21635_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15081_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn11285_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn09390_c0': '>', 'rxn14423_c0': '>', 'rxn10120_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:02:49,706 - INFO - Glc.TMAO/rxn00062_c0:rxn05553_c0> needed:0.0 with min obj:0.01
2026-01-13 20:02:50,809 - INFO - integrating rxn: EX_cpd00305_e0
2026-01-13 20:02:52,025 - INFO - integrating rxn: EX_cpd00030_e0
2026-01-13 20:02:52,027 - INFO - integrating rxn: EX_cpd00393_e0
2026-01-13 20:02:52,028 - INFO - integrating rxn: EX_cpd00119_e0
2026-01-13 20:02:52,030 - INFO - integrating rxn: EX_cpd00058_e0
2026-01-13 20:02:52,031 - INFO - integrating rxn: EX_cpd00063_e0
2026-01-13 20:02:52,045 - INFO - Glc.TMAO/rxn00062_c0:rxn00251_c0< needed:0.0 with min obj:0.01
2026-01-13 20:02:52,047 - INFO - rxn00250_c0< not needed:2.5
2026-01-13 20:02:52,033 - INFO - integrating rxn: EX_cpd00099_e0
2026-01-13 20:02:52,060 - INFO - integrating rxn: rxn08709_c0
2026-01-13 20:02:52,062 - INFO - integrating rxn: rxn03086_c0
2026-01-13 20:02:52,094 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2869f4c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'reversed': {}}
2026-01-13 20:02:52,095 - INFO - Unneeded: [['rxn00102_c0', '>', 'new', 100, None], ['rxn00250_c0', '<', 'reversed', -100, None]]

Adding gapfilling {'reversed': {'rxn00250_c0': '<'}, 'new': {'EX_cpd00363_e0': '>', 'rxn07191_c0': '<', 'rxn00102_c0': '>', 'rxn05553_c0': '>', 'rxn00251_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa2869f4c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:02:52,063 - INFO - integrating rxn: rxn00800_c0
2026-01-13 20:02:52,102 - INFO - integrating rxn: rxn08333_c0
2026-01-13 20:02:52,104 - INFO - integrating rxn: rxn02898_c0
2026-01-13 20:02:52,105 - INFO - integrating rxn: rxn10336_c0
2026-01-13 20:02:52,107 - INFO - integrating rxn: rxn03030_c0
2026-01-13 20:02:52,108 - INFO - integrating rxn: rxn01117_c0
2026-01-13 20:02:52,110 - INFO - integrating rxn: rxn08710_c0
2026-01-13 20:02:52,111 - INFO - integrating rxn: rxn03181_c0
2026-01-13 20:02:52,113 - INFO - integrating rxn: rxn02331_c0
2026-01-13 20:02:52,115 - INFO - integrating rxn: rxn12512_c0
2026-01-13 20:02:52,116 - INFO - integrating rxn: rxn08583_c0
2026-01-13 20:02:52,118 - INFO - integrating rxn: rxn02264_c0
2026-01-13 20:02:52,119 - INFO - integrating rxn: rxn09202_c0
2026-01-13 20:02:52,121 - INFO - integrating rxn: rxn05514_c0
2026-01-13 20:02:52,122 - INFO - integrating rxn: rxn10481_c0
2026-01-13 20:02:52,124 - INFO - integrating rxn: rxn01362_c0

2026-01-13 20:02:54,426 - INFO - Cumulative: [['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed'], ['rxn01975_c0', '>', 'new'], ['rxn00324_c0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn01476_c0', '>', 'new'], ['rxn08901_c0', '>', 'new'], ['rxn03884_c0', '>', 'new'], ['rxn08971_c0', '>', 'new'], ['rxn01477_c0', '>', 'new'], ['rxn08656_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn08557_c0', '>', 'new'], ['rxn00251_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn00102_c0', '>', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00363_e0', '>', 'new'], ['rxn05553_c0', '>', 'new'], ['rxn00248_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:02:52,127 - INFO - integrating rxn: rxn03918_c0
2026-01-13 20:02:54,434 - INFO - integrating rxn: rxn08708_c0
2026-01-13 20:02:54,435 - INFO - integrating rxn: rxn00907_c0
2026-01-13 20:02:54,437 - INFO - integrating rxn: rxn10213_c0
2026-01-13 20:02:54,439 - INFO - integrating rxn: rxn05229_c0
2026-01-13 20:02:54,441 - INFO - integrating rxn: rxn10204_c0
2026-01-13 20:02:54,442 - INFO - integrating rxn: rxn06937_c0
2026-01-13 20:02:54,445 - INFO - integrating rxn: rxn00392_c0
2026-01-13 20:02:54,447 - INFO - integrating rxn: rxn09225_c0
2026-01-13 20:02:54,449 - INFO - integrating rxn: rxn02774_c0
2026-01-13 20:02:54,450 - INFO - integrating rxn: rxn03536_c0
2026-01-13 20:02:54,452 - INFO - integrating rxn: rxn01505_c0
2026-01-13 20:02:54,453 - INFO - integrating rxn: rxn00237_c0
2026-01-13 20:02:54,453 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:02:54,454 - INFO - integrating rxn: rxn10124_c0
2026-01-13 20:02:54,456 - INFO - integrating rxn: rxn09210_c0
2026-01-13 20:02:54,458 - INFO - integrating rxn: rxn08954_c0
2026-01-13 20:02:54,460 - INFO - integrating rxn: rxn00916_c0
2026-01-13 20:02:54,461 - INFO - integrating rxn: rxn01518_c0
2026-01-13 20:02:54,463 - INFO - integrating rxn: rxn08712_c0
2026-01-13 20:02:54,464 - INFO - integrating rxn: rxn08618_c0
2026-01-13 20:02:54,466 - INFO - integrating rxn: rxn03159_c0
2026-01-13 20:02:54,530 - INFO - integrating rxn: rxn03397_c0
2026-01-13 20:02:54,578 - INFO - integrating rxn: rxn01972_c0
2026-01-13 20:02:54,580 - INFO - integrating rxn: rxn11703_c0
2026-01-13 20:02:54,582 - INFO - integrating rxn: rxn01300_c0
2026-01-13 20:02:54,583 - INFO - integrating rxn: rxn13647_c0
2026-01-13 20:02:57,008 - INFO - integrating rxn: rxn06848_c0
2026-01-13 20:02:57,011 - INFO - integrating rxn: rxn03537_c0
2026-01-13 20:02:59,357 - INFO - integrating rxn: rxn00966_c0

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:02:59,410 - INFO - integrating rxn: rxn05119_c0
2026-01-13 20:02:59,412 - INFO - integrating rxn: rxn03916_c0
2026-01-13 20:02:59,414 - INFO - integrating rxn: rxn09106_c0
2026-01-13 20:02:59,416 - INFO - integrating rxn: rxn05463_c0
2026-01-13 20:03:01,864 - INFO - integrating rxn: rxn08711_c0
2026-01-13 20:03:01,924 - INFO - integrating rxn: rxn00137_c0
2026-01-13 20:03:01,926 - INFO - integrating rxn: rxn00832_c0
2026-01-13 20:03:01,928 - INFO - integrating rxn: rxn04139_c0
2026-01-13 20:03:01,930 - INFO - integrating rxn: rxn05299_c0
2026-01-13 20:03:01,931 - INFO - integrating rxn: rxn06723_c0
2026-01-13 20:03:01,933 - INFO - integrating rxn: rxn09657_c0
2026-01-13 20:03:01,934 - INFO - integrating rxn: rxn03917_c0
2026-01-13 20:03:01,936 - INFO - integrating rxn: rxn03990_c0
2026-01-13 20:03:02,002 - INFO - integrating rxn: rxn03146_c0
2026-01-13 20:03:02,004 - INFO - integrating rxn: rxn03893_c0
2026-01-13 20:03:02,006 - INFO - integrating rxn: rxn02405_c0
2026-01-13 20:03:02,007 - INFO - integrating rxn: rxn02303_c0
2026-01-13 20:03:02,009 - INFO - integrating rxn: rxn01213_c0
2026-01-13 20:03:02,010 - INFO - integrating rxn: rxn02304_c0
2026-01-13 20:03:02,012 - INFO - integrating rxn: rxn05618_c0
2026-01-13 20:03:02,013 - INFO - integrating rxn: rxn03136_c0
2026-01-13 20:03:02,061 - INFO - integrating rxn: rxn00350_c0
2026-01-13 20:03:02,070 - WARNING - No gapfilling solution found for For.NO activating rxn00062_c0
2026-01-13 20:03:02,063 - INFO - integrating rxn: rxn03137_c0
2026-01-13 20:03:04,290 - INFO - integrating rxn: rxn00533_c0
2026-01-13 20:03:04,292 - INFO - integrating rxn: rxn01512_c0
2026-01-13 20:03:04,294 - INFO - integrating rxn: rxn06865_c0
2026-01-13 20:03:04,296 - INFO - integrating rxn: rxn04113_c0
2026-01-13 20:03:04,298 - INFO - integrating rxn: rxn00834_c0
2026-01-13 20:03:04,300 - INFO - integrating rxn: rxn00704_c0
2026-01-13 20:03:04,301 - INFO - integrating rxn: rxn08130_c0
2026-01-13 20:03:04,303 - INFO - integrating rxn: rxn11702_c0
2026-01-13 20:03:04,305 - INFO - integrating rxn: rxn03084_c0
2026-01-13 20:03:04,307 - INFO - integrating rxn: rxn03439_c0
2026-01-13 20:03:04,308 - INFO - integrating rxn: rxn01790_c0
2026-01-13 20:03:04,310 - INFO - integrating rxn: rxn02056_c0
2026-01-13 20:03:04,404 - INFO - integrating rxn: rxn00134_c0
2026-01-13 20:03:04,406 - INFO - integrating rxn: rxn02003_c0
2026-01-13 20:03:04,407 - INFO - integrating rxn: rxn00122_c0
2026-01-13 20:03:04,409 - INFO - integrating rxn: rxn08620_c0
2026-01-13 20:03:04,411 - INFO - integrating rxn: rxn02287_c0
2026-01-13 20:03:04,412 - INFO - integrating rxn: rxn02288_c0
2026-01-13 20:03:04,522 - INFO - integrating rxn: rxn02831_c0
2026-01-13 20:03:06,946 - INFO - integrating rxn: rxn04308_c0
2026-01-13 20:03:06,948 - INFO - integrating rxn: rxn01258_c0
2026-01-13 20:03:06,950 - INFO - integrating rxn: rxn05255_c0
2026-01-13 20:03:06,952 - INFO - integrating rxn: rxn02832_c0
2026-01-13 20:03:06,954 - INFO - integrating rxn: rxn00138_c0
2026-01-13 20:03:06,955 - INFO - integrating rxn: rxn00467_c0
2026-01-13 20:03:06,957 - INFO - integrating rxn: rxn03130_c0
2026-01-13 20:03:06,959 - INFO - integrating rxn: rxn02341_c0
2026-01-13 20:03:08,061 - INFO -   Using template: GramNegative.modeltemplate

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:03:08,067 - INFO -   Gapfilling with AuxoMedia...
2026-01-13 20:03:09,231 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:03:06,960 - INFO - integrating rxn: rxn03511_c0
2026-01-13 20:03:09,258 - INFO - integrating rxn: rxn03182_c0
2026-01-13 20:03:09,260 - INFO - integrating rxn: rxn00224_c0
2026-01-13 20:03:09,261 - INFO - integrating rxn: rxn08619_c0
2026-01-13 20:03:09,263 - INFO - integrating rxn: rxn01286_c0
2026-01-13 20:03:09,265 - INFO - integrating rxn: rxn00117_c0
2026-01-13 20:03:09,266 - INFO - integrating rxn: rxn00293_c0
2026-01-13 20:03:09,268 - INFO - integrating rxn: rxn00399_c0
2026-01-13 20:03:09,269 - INFO - integrating rxn: rxn21635_c0
2026-01-13 20:03:09,271 - INFO - integrating rxn: rxn15949_c0
2026-01-13 20:03:09,273 - INFO - integrating rxn: rxn15947_c0
2026-01-13 20:03:09,275 - INFO - integrating rxn: rxn14424_c0
2026-01-13 20:03:09,276 - INFO - integrating rxn: rxn11274_c0
2026-01-13 20:03:09,278 - INFO - integrating rxn: rxn12930_c0
2026-01-13 20:03:09,368 - INFO - integrating rxn: rxn12932_c0
2026-01-13 20:03:09,369 - INFO - integrating rxn: rxn12940_c0
2026-01-13 20:03:09,371 - INFO - integrating rxn: rxn12939_c0
2026-01-13 20:03:09,423 - INFO - integrating rxn: rxn12929_c0
2026-01-13 20:03:09,426 - INFO - integrating rxn: rxn12938_c0
2026-01-13 20:03:09,427 - INFO - integrating rxn: rxn12927_c0
2026-01-13 20:03:09,478 - INFO - integrating rxn: rxn12921_c0
2026-01-13 20:03:09,480 - INFO - integrating rxn: rxn12928_c0
2026-01-13 20:03:09,517 - INFO - integrating rxn: rxn12943_c0
2026-01-13 20:03:09,518 - INFO - integrating rxn: rxn12942_c0
2026-01-13 20:03:09,520 - INFO - integrating rxn: rxn00154_c0
2026-01-13 20:03:09,522 - INFO - integrating rxn: rxn12934_c0
2026-01-13 20:03:09,524 - INFO - integrating rxn: rxn25474_c0
2026-01-13 20:03:09,525 - INFO - integrating rxn: rxn12941_c0
2026-01-13 20:03:09,527 - INFO - integrating rxn: rxn11251_c0
2026-01-13 20:03:09,528 - INFO - integrating rxn: rxn15167_c0
2026-01-13 20:03:09,530 - INFO - integrating rxn: rxn19346_c0
2026-01-13 20:03:09,531 - INFO - integrating rxn: rxn04551_c0
2026-01-13 20:03:09,533 - INFO - integrating rxn: rxn03396_c0
2026-01-13 20:03:09,580 - INFO - integrating rxn: rxn25479_c0
2026-01-13 20:03:09,581 - INFO - integrating rxn: rxn22114_c0
2026-01-13 20:03:09,583 - INFO - integrating rxn: rxn15081_c0
2026-01-13 20:03:09,585 - INFO - integrating rxn: rxn16114_c0
2026-01-13 20:03:09,586 - INFO - integrating rxn: rxn14070_c0
2026-01-13 20:03:09,587 - INFO - integrating rxn: rxn15064_c0
2026-01-13 20:03:09,589 - INFO - integrating rxn: rxn11285_c0
2026-01-13 20:03:09,590 - INFO - integrating rxn: rxn08233_c0
2026-01-13 20:03:09,591 - INFO - integrating rxn: rxn20508_c0
2026-01-13 20:03:09,593 - INFO - integrating rxn: rxn30917_c0
2026-01-13 20:03:09,594 - INFO - integrating rxn: rxn15939_c0
2026-01-13 20:03:09,596 - INFO - integrating rxn: rxn40674_c0
2026-01-13 20:03:09,636 - INFO - integrating rxn: rxn09037_c0
2026-01-13 20:03:10,712 - INFO - integrating rxn: rxn29260_c0
2026-01-13 20:03:10,714 - INFO - integrating rxn: rxn08473_c0
2026-01-13 20:03:10,716 - INFO - integrating rxn: rxn09390_c0
2026-01-13 20:03:10,718 - INFO - integrating rxn: rxn14423_c0
2026-01-13 20:03:10,719 - INFO - integrating rxn: rxn10120_c0
2026-01-13 20:03:10,721 - INFO - Full solution: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01362_c0', '<', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn01518_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn13647_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03990_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn02303_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn00467_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01286_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn00399_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12932_c0', '>', 'new'], ['rxn12940_c0', '>', 'new'], ['rxn12939_c0', '>', 'new'], ['rxn12929_c0', '>', 'new'], ['rxn12938_c0', '>', 'new'], ['rxn12927_c0', '>', 'new'], ['rxn12921_c0', '>', 'new'], ['rxn12928_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12942_c0', '>', 'new'], ['rxn00154_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn11251_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn15081_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn08473_c0', '>', 'new'], ['rxn09390_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10120_c0', '>', 'new']]
2026-01-13 20:03:16,411 - INFO - AuxoMedia/bio1:EX_cpd00305_e0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,414 - INFO - AuxoMedia/bio1:EX_cpd00030_e0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,416 - INFO - AuxoMedia/bio1:EX_cpd00393_e0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,417 - INFO - AuxoMedia/bio1:EX_cpd00119_e0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,419 - INFO - AuxoMedia/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,421 - INFO - AuxoMedia/bio1:EX_cpd00063_e0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,422 - INFO - AuxoMedia/bio1:EX_cpd00099_e0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,423 - INFO - AuxoMedia/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,462 - INFO - AuxoMedia/bio1:rxn03086_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,464 - INFO - AuxoMedia/bio1:rxn00800_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,466 - INFO - AuxoMedia/bio1:rxn08333_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,467 - INFO - AuxoMedia/bio1:rxn02898_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,512 - INFO - AuxoMedia/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,513 - INFO - AuxoMedia/bio1:rxn03030_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,515 - INFO - AuxoMedia/bio1:rxn01117_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,516 - INFO - AuxoMedia/bio1:rxn08710_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,518 - INFO - AuxoMedia/bio1:rxn03181_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,519 - INFO - AuxoMedia/bio1:rxn02331_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,521 - INFO - AuxoMedia/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,523 - INFO - AuxoMedia/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,524 - INFO - AuxoMedia/bio1:rxn02264_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,526 - INFO - AuxoMedia/bio1:rxn09202_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,527 - INFO - AuxoMedia/bio1:rxn05514_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,529 - INFO - AuxoMedia/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,530 - INFO - AuxoMedia/bio1:rxn01362_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:16,532 - INFO - AuxoMedia/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,533 - INFO - AuxoMedia/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:16,535 - INFO - AuxoMedia/bio1:rxn00907_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,244 - INFO - AuxoMedia/bio1:rxn10213_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,247 - INFO - AuxoMedia/bio1:rxn05229_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,249 - INFO - AuxoMedia/bio1:rxn10204_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,251 - INFO - AuxoMedia/bio1:rxn06937_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,253 - INFO - AuxoMedia/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,254 - INFO - AuxoMedia/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,256 - INFO - AuxoMedia/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,258 - INFO - AuxoMedia/bio1:rxn03536_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,260 - INFO - AuxoMedia/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,262 - INFO - AuxoMedia/bio1:rxn00237_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,263 - INFO - AuxoMedia/bio1:rxn10124_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,265 - INFO - AuxoMedia/bio1:rxn09210_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,266 - INFO - AuxoMedia/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,267 - INFO - AuxoMedia/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,269 - INFO - rxn01518_c0> not needed:1.9535705179863108
2026-01-13 20:03:18,272 - INFO - AuxoMedia/bio1:rxn08712_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,275 - INFO - AuxoMedia/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,276 - INFO - AuxoMedia/bio1:rxn03159_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,277 - INFO - AuxoMedia/bio1:rxn03397_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,279 - INFO - AuxoMedia/bio1:rxn01972_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,280 - INFO - AuxoMedia/bio1:rxn11703_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,282 - INFO - AuxoMedia/bio1:rxn01300_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,283 - INFO - AuxoMedia/bio1:rxn13647_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,284 - INFO - AuxoMedia/bio1:rxn06848_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,285 - INFO - AuxoMedia/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,287 - INFO - AuxoMedia/bio1:rxn00966_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,288 - INFO - AuxoMedia/bio1:rxn05119_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,290 - INFO - AuxoMedia/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,291 - INFO - AuxoMedia/bio1:rxn09106_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,292 - INFO - AuxoMedia/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,294 - INFO - AuxoMedia/bio1:rxn08711_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,295 - INFO - AuxoMedia/bio1:rxn00137_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,297 - INFO - AuxoMedia/bio1:rxn00832_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,298 - INFO - AuxoMedia/bio1:rxn04139_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,299 - INFO - AuxoMedia/bio1:rxn05299_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,301 - INFO - AuxoMedia/bio1:rxn06723_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,302 - INFO - AuxoMedia/bio1:rxn09657_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,303 - INFO - AuxoMedia/bio1:rxn03917_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,305 - INFO - AuxoMedia/bio1:rxn03990_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,306 - INFO - AuxoMedia/bio1:rxn03146_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,308 - INFO - AuxoMedia/bio1:rxn03893_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,309 - INFO - AuxoMedia/bio1:rxn02405_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,311 - INFO - rxn02303_c0> not needed:1.9503647362764323
2026-01-13 20:03:18,313 - INFO - AuxoMedia/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,314 - INFO - AuxoMedia/bio1:rxn02304_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,316 - INFO - AuxoMedia/bio1:rxn05618_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,317 - INFO - AuxoMedia/bio1:rxn03136_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,319 - INFO - AuxoMedia/bio1:rxn00350_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,320 - INFO - AuxoMedia/bio1:rxn03137_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,322 - INFO - AuxoMedia/bio1:rxn00533_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,323 - INFO - AuxoMedia/bio1:rxn01512_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,496 - INFO - AuxoMedia/bio1:rxn06865_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,498 - INFO - AuxoMedia/bio1:rxn04113_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,500 - INFO - AuxoMedia/bio1:rxn00834_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,501 - INFO - AuxoMedia/bio1:rxn00704_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,503 - INFO - AuxoMedia/bio1:rxn08130_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,504 - INFO - AuxoMedia/bio1:rxn11702_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,506 - INFO - AuxoMedia/bio1:rxn03084_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,507 - INFO - AuxoMedia/bio1:rxn03439_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,509 - INFO - AuxoMedia/bio1:rxn01790_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,510 - INFO - AuxoMedia/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,512 - INFO - AuxoMedia/bio1:rxn00134_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,515 - INFO - AuxoMedia/bio1:rxn02003_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,516 - INFO - AuxoMedia/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,518 - INFO - AuxoMedia/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,519 - INFO - AuxoMedia/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,520 - INFO - AuxoMedia/bio1:rxn02288_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,522 - INFO - AuxoMedia/bio1:rxn02831_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,523 - INFO - AuxoMedia/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,525 - INFO - AuxoMedia/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,526 - INFO - AuxoMedia/bio1:rxn05255_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,528 - INFO - AuxoMedia/bio1:rxn02832_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,530 - INFO - AuxoMedia/bio1:rxn00138_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,531 - INFO - AuxoMedia/bio1:rxn00467_c0< needed:0.0 with min obj:0.01
2026-01-13 20:03:18,533 - INFO - AuxoMedia/bio1:rxn03130_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,534 - INFO - AuxoMedia/bio1:rxn02341_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,536 - INFO - AuxoMedia/bio1:rxn03511_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,537 - INFO - AuxoMedia/bio1:rxn03182_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,539 - INFO - AuxoMedia/bio1:rxn00224_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,540 - INFO - AuxoMedia/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,543 - INFO - AuxoMedia/bio1:rxn01286_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,545 - INFO - AuxoMedia/bio1:rxn00117_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,938 - INFO - AuxoMedia/bio1:rxn00293_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,940 - INFO - AuxoMedia/bio1:rxn00399_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,941 - INFO - AuxoMedia/bio1:rxn21635_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,943 - INFO - AuxoMedia/bio1:rxn15949_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,944 - INFO - AuxoMedia/bio1:rxn15947_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,946 - INFO - AuxoMedia/bio1:rxn14424_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,947 - INFO - AuxoMedia/bio1:rxn11274_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,950 - INFO - AuxoMedia/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:18,952 - INFO - rxn12932_c0> not needed:1.9503647362764363
2026-01-13 20:03:18,956 - INFO - rxn12940_c0> not needed:1.9503647362764363
2026-01-13 20:03:19,002 - INFO - rxn12939_c0> not needed:1.950364736276424
2026-01-13 20:03:19,003 - INFO - rxn12929_c0> not needed:1.950364736276424
2026-01-13 20:03:19,065 - INFO - rxn12938_c0> not needed:1.950364736276443
2026-01-13 20:03:19,067 - INFO - rxn12927_c0> not needed:1.950364736276443
2026-01-13 20:03:19,068 - INFO - rxn12921_c0> not needed:1.950364736276443
2026-01-13 20:03:19,069 - INFO - rxn12928_c0> not needed:1.950364736276443
2026-01-13 20:03:19,073 - INFO - AuxoMedia/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:19,076 - INFO - rxn12942_c0> not needed:1.950364736276428
2026-01-13 20:03:19,078 - INFO - AuxoMedia/bio1:rxn00154_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:19,080 - INFO - AuxoMedia/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:19,081 - INFO - AuxoMedia/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:19,083 - INFO - AuxoMedia/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:19,085 - INFO - rxn11251_c0> not needed:1.9503647362764285
2026-01-13 20:03:19,088 - INFO - AuxoMedia/bio1:rxn15167_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:19,089 - INFO - AuxoMedia/bio1:rxn19346_c0> needed:0.0 with min obj:0.01
2026-01-13 20:03:19,091 - INFO - AuxoMedia/bio1:rxn04551_c0> needed:0.0 with min obj:0.01

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00305_e0': '<', 'EX_cpd00030_e0': '<', 'EX_cpd00393_e0': '<', 'EX_cpd00119_e0': '<', 'EX_cpd00058_e0': '<', 'EX_cpd00063_e0': '<', 'EX_cpd00099_e0': '<', 'rxn08709_c0': '>', 'rxn03086_c0': '<', 'rxn00800_c0': '>', 'rxn08333_c0': '>', 'rxn02898_c0': '>', 'rxn10336_c0': '>', 'rxn03030_c0': '>', 'rxn01117_c0': '<', 'rxn08710_c0': '>', 'rxn03181_c0': '>', 'rxn02331_c0': '<', 'rxn12512_c0': '>', 'rxn08583_c0': '>', 'rxn02264_c0': '>', 'rxn09202_c0': '>', 'rxn05514_c0': '<', 'rxn10481_c0': '>', 'rxn01362_c0': '<', 'rxn03918_c0': '>', 'rxn08708_c0': '>', 'rxn00907_c0': '>', 'rxn10213_c0': '>', 'rxn05229_c0': '>', 'rxn10204_c0': '>', 'rxn06937_c0': '>', 'rxn00392_c0': '>', 'rxn09225_c0': '>', 'rxn02774_c0': '>', 'rxn03536_c0': '>', 'rxn01505_c0': '>', 'rxn00237_c0': '>', 'rxn10124_c0': '<', 'rxn09210_c0': '>', 'rxn08954_c0': '>', 'rxn00916_c0': '>', 'rxn01518_c0': '>', 'rxn08712_c0': '>', 'rxn08618_c0': '>', 'rxn03159_c0': '>', 'rxn03397_c0': '>', 'rxn01972_c0': '>', 'rxn11703_c0': '>', 'rxn01300_c0': '>', 'rxn13647_c0': '>', 'rxn06848_c0': '<', 'rxn03537_c0': '>', 'rxn00966_c0': '<', 'rxn05119_c0': '>', 'rxn03916_c0': '>', 'rxn09106_c0': '>', 'rxn05463_c0': '>', 'rxn08711_c0': '>', 'rxn00137_c0': '>', 'rxn00832_c0': '<', 'rxn04139_c0': '>', 'rxn05299_c0': '>', 'rxn06723_c0': '<', 'rxn09657_c0': '>', 'rxn03917_c0': '>', 'rxn03990_c0': '>', 'rxn03146_c0': '>', 'rxn03893_c0': '>', 'rxn02405_c0': '>', 'rxn02303_c0': '>', 'rxn01213_c0': '>', 'rxn02304_c0': '>', 'rxn05618_c0': '>', 'rxn03136_c0': '>', 'rxn00350_c0': '<', 'rxn03137_c0': '>', 'rxn00533_c0': '>', 'rxn01512_c0': '>', 'rxn06865_c0': '<', 'rxn04113_c0': '>', 'rxn00834_c0': '>', 'rxn00704_c0': '<', 'rxn08130_c0': '>', 'rxn11702_c0': '>', 'rxn03084_c0': '>', 'rxn03439_c0': '>', 'rxn01790_c0': '<', 'rxn02056_c0': '<', 'rxn00134_c0': '>', 'rxn02003_c0': '<', 'rxn00122_c0': '>', 'rxn08620_c0': '>', 'rxn02287_c0': '>', 'rxn02288_c0': '>', 'rxn02831_c0': '>', 'rxn04308_c0': '>', 'rxn01258_c0': '>', 'rxn05255_c0': '>', 'rxn02832_c0': '<', 'rxn00138_c0': '>', 'rxn00467_c0': '<', 'rxn03130_c0': '>', 'rxn02341_c0': '>', 'rxn03511_c0': '>', 'rxn03182_c0': '>', 'rxn00224_c0': '>', 'rxn08619_c0': '>', 'rxn01286_c0': '>', 'rxn00117_c0': '>', 'rxn00293_c0': '>', 'rxn00399_c0': '>', 'rxn21635_c0': '>', 'rxn15949_c0': '>', 'rxn15947_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn12930_c0': '>', 'rxn12932_c0': '>', 'rxn12940_c0': '>', 'rxn12939_c0': '>', 'rxn12929_c0': '>', 'rxn12938_c0': '>', 'rxn12927_c0': '>', 'rxn12921_c0': '>', 'rxn12928_c0': '>', 'rxn12943_c0': '>', 'rxn12942_c0': '>', 'rxn00154_c0': '>', 'rxn12934_c0': '>', 'rxn25474_c0': '>', 'rxn12941_c0': '>', 'rxn11251_c0': '>', 'rxn15167_c0': '>', 'rxn19346_c0': '>', 'rxn04551_c0': '>', 'rxn03396_c0': '>', 'rxn25479_c0': '>', 'rxn22114_c0': '>', 'rxn15081_c0': '>', 'rxn16114_c0': '>', 'rxn14070_c0': '>', 'rxn15064_c0': '>', 'rxn11285_c0': '>', 'rxn08233_c0': '>', 'rxn20508_c0': '>', 'rxn30917_c0': '>', 'rxn15939_c0': '>', 'rxn40674_c0': '>', 'rxn09037_c0': '>', 'rxn29260_c0': '>', 'rxn08473_c0': '>', 'rxn09390_c0': '>', 'rxn14423_c0': '>', 'rxn10120_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fb086382e0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:03:26,401 - INFO - Cumulative: [['EX_cpd00305_e0', '<', 'new'], ['EX_cpd00030_e0', '<', 'new'], ['EX_cpd00393_e0', '<', 'new'], ['EX_cpd00119_e0', '<', 'new'], ['EX_cpd00058_e0', '<', 'new'], ['EX_cpd00063_e0', '<', 'new'], ['EX_cpd00099_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn03086_c0', '<', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn08333_c0', '>', 'new'], ['rxn02898_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn03030_c0', '>', 'new'], ['rxn01117_c0', '<', 'new'], ['rxn08710_c0', '>', 'new'], ['rxn03181_c0', '>', 'new'], ['rxn02331_c0', '<', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn02264_c0', '>', 'new'], ['rxn09202_c0', '>', 'new'], ['rxn05514_c0', '<', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn01362_c0', '<', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00907_c0', '>', 'new'], ['rxn10213_c0', '>', 'new'], ['rxn05229_c0', '>', 'new'], ['rxn10204_c0', '>', 'new'], ['rxn06937_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn03536_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn00237_c0', '>', 'new'], ['rxn10124_c0', '<', 'new'], ['rxn09210_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08712_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03159_c0', '>', 'new'], ['rxn03397_c0', '>', 'new'], ['rxn01972_c0', '>', 'new'], ['rxn11703_c0', '>', 'new'], ['rxn01300_c0', '>', 'new'], ['rxn13647_c0', '>', 'new'], ['rxn06848_c0', '<', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn00966_c0', '<', 'new'], ['rxn05119_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn09106_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn08711_c0', '>', 'new'], ['rxn00137_c0', '>', 'new'], ['rxn00832_c0', '<', 'new'], ['rxn04139_c0', '>', 'new'], ['rxn05299_c0', '>', 'new'], ['rxn06723_c0', '<', 'new'], ['rxn09657_c0', '>', 'new'], ['rxn03917_c0', '>', 'new'], ['rxn03990_c0', '>', 'new'], ['rxn03146_c0', '>', 'new'], ['rxn03893_c0', '>', 'new'], ['rxn02405_c0', '>', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn02304_c0', '>', 'new'], ['rxn05618_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn00350_c0', '<', 'new'], ['rxn03137_c0', '>', 'new'], ['rxn00533_c0', '>', 'new'], ['rxn01512_c0', '>', 'new'], ['rxn06865_c0', '<', 'new'], ['rxn04113_c0', '>', 'new'], ['rxn00834_c0', '>', 'new'], ['rxn00704_c0', '<', 'new'], ['rxn08130_c0', '>', 'new'], ['rxn11702_c0', '>', 'new'], ['rxn03084_c0', '>', 'new'], ['rxn03439_c0', '>', 'new'], ['rxn01790_c0', '<', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00134_c0', '>', 'new'], ['rxn02003_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn02288_c0', '>', 'new'], ['rxn02831_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn05255_c0', '>', 'new'], ['rxn02832_c0', '<', 'new'], ['rxn00138_c0', '>', 'new'], ['rxn00467_c0', '<', 'new'], ['rxn03130_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn03511_c0', '>', 'new'], ['rxn03182_c0', '>', 'new'], ['rxn00224_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01286_c0', '>', 'new'], ['rxn00117_c0', '>', 'new'], ['rxn00293_c0', '>', 'new'], ['rxn00399_c0', '>', 'new'], ['rxn21635_c0', '>', 'new'], ['rxn15949_c0', '>', 'new'], ['rxn15947_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn00154_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn15167_c0', '>', 'new'], ['rxn19346_c0', '>', 'new'], ['rxn04551_c0', '>', 'new'], ['rxn03396_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn16114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn11285_c0', '>', 'new'], ['rxn08233_c0', '>', 'new'], ['rxn20508_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn15939_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], ['rxn09037_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10120_c0', '>', 'new']]
2026-01-13 20:03:28,740 - INFO -     Added 138 reactions
2026-01-13 20:03:28,850 - INFO -   Gapfilling with PyruateMinimalAnaerobic...

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:03:57,007 - WARNING - No gapfilling solution found before filtering for Pyr.SO4 activating rxn00062_c0

Removing ungapfillable media Pyr.SO4

2026-01-13 20:03:59,508 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:04:02,194 - WARNING - No gapfilling solution found before filtering for Ac.NO3 activating rxn00062_c0

Removing ungapfillable media Ac.NO3

2026-01-13 20:04:04,732 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:04:07,404 - WARNING - No gapfilling solution found for Pyr.NO3 activating rxn00062_c0
2026-01-13 20:04:09,648 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:04:11,945 - WARNING - No gapfilling solution found for For.O2 activating rxn00062_c0
2026-01-13 20:04:12,318 - INFO - Objective with gapfill database:3.5; min objective:0.01
2026-01-13 20:04:14,692 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn05488_c0': '<', 'rxn00548_c0': '>', 'rxn00781_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824a530>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:04:14,724 - INFO - integrating rxn: EX_cpd00029_e0
2026-01-13 20:04:14,725 - INFO - integrating rxn: EX_cpd00159_e0
2026-01-13 20:04:14,775 - INFO - integrating rxn: rxn05602_c0
2026-01-13 20:04:14,801 - INFO - integrating rxn: rxn05488_c0
2026-01-13 20:04:17,178 - INFO - integrating rxn: rxn00548_c0
2026-01-13 20:04:17,181 - INFO - integrating rxn: rxn00781_c0
2026-01-13 20:04:17,182 - INFO - Full solution: [['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['EX_cpd00159_e0', '>', 'new'], ['rxn05602_c0', '<', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00548_c0', '>', 'new'], ['rxn00781_c0', '>', 'new']]
2026-01-13 20:04:17,240 - INFO - Glc/rxn00062_c0:EX_cpd00029_e0> needed:0.0 with min obj:0.01
2026-01-13 20:04:17,282 - INFO - EX_cpd00159_e0> not needed:1.9999999999999993
2026-01-13 20:04:17,283 - INFO - rxn05602_c0< not needed:1.9999999999999993
2026-01-13 20:04:17,285 - INFO - Glc/rxn00062_c0:rxn05488_c0< needed:0.0 with min obj:0.01
2026-01-13 20:04:17,325 - INFO - Glc/rxn00062_c0:rxn00548_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:17,359 - INFO - rxn00781_c0> not needed:1.9999999999999993
2026-01-13 20:04:17,454 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824a530>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'EX_cpd00029_e0': '>', 'rxn05488_c0': '<', 'rxn00548_c0': '>'}, 'reversed': {}}
2026-01-13 20:04:17,456 - INFO - Unneeded: [['EX_cpd00159_e0', '>', 'new', 100, None], ['rxn05602_c0', '<', 'new', -100, None], ['rxn00781_c0', '>', 'new', 100, None]]

Adding gapfilling {'reversed': {}, 'new': {'EX_cpd00029_e0': '>', 'EX_cpd00159_e0': '>', 'rxn05602_c0': '<', 'rxn05488_c0': '<', 'rxn00548_c0': '>', 'rxn00781_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79f9c824a530>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:04:19,648 - INFO - Cumulative: [['rxn05581_c0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00159_e0', '<', 'new'], ['rxn05602_c0', '>', 'new'], ['EX_cpd00029_e0', '>', 'new'], ['rxn05488_c0', '<', 'new'], ['rxn00548_c0', '>', 'new']]
2026-01-13 20:04:19,654 - INFO - Objective with gapfill database:116.82557499858882; min objective:0.01
2026-01-13 20:04:19,678 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:04:22,093 - INFO - Objective with gapfill database:116.82557499858882; min objective:0.01
2026-01-13 20:04:27,442 - INFO - Initial solution: {'reversed': {}, 'new': {'EX_cpd15378_e0': '>', 'rxn03436_c0': '>', 'rxn12376_c0': '<', 'rxn09310_c0': '>', 'rxn02834_c0': '>', 'rxn02185_c0': '<', 'rxn10504_c0': '>', 'rxn10506_c0': '>', 'rxn48543_c0': '>', 'rxn14424_c0': '>', 'rxn11274_c0': '>', 'rxn01736_c0': '>', 'rxn25042_c0': '>', 'rxn19766_c0': '>', 'rxn19764_c0': '>', 'rxn15550_c0': '>', 'rxn15072_c0': '>', 'rxn15064_c0': '>', 'rxn41185_c0': '>', 'rxn10095_c0': '>', 'rxn46249_c0': '>', 'rxn40040_c0': '>', 'rxn29260_c0': '>', 'rxn14423_c0': '>', 'rxn10042_c0': '>'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fafb8a80d0>, 'target': 'bio1', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:04:29,356 - INFO - integrating rxn: EX_cpd15378_e0
2026-01-13 20:04:29,358 - INFO - integrating rxn: rxn03436_c0
2026-01-13 20:04:29,360 - INFO - integrating rxn: rxn12376_c0
2026-01-13 20:04:29,363 - INFO - integrating rxn: rxn09310_c0
2026-01-13 20:04:29,364 - INFO - integrating rxn: rxn02834_c0
2026-01-13 20:04:29,366 - INFO - integrating rxn: rxn02185_c0
2026-01-13 20:04:29,368 - INFO - integrating rxn: rxn10504_c0
2026-01-13 20:04:29,370 - INFO - integrating rxn: rxn10506_c0
2026-01-13 20:04:29,372 - INFO - integrating rxn: rxn48543_c0
2026-01-13 20:04:29,374 - INFO - integrating rxn: rxn14424_c0
2026-01-13 20:04:29,376 - INFO - integrating rxn: rxn11274_c0
2026-01-13 20:04:29,378 - INFO - integrating rxn: rxn01736_c0
2026-01-13 20:04:29,380 - INFO - integrating rxn: rxn25042_c0
2026-01-13 20:04:29,382 - INFO - integrating rxn: rxn19766_c0
2026-01-13 20:04:29,384 - INFO - integrating rxn: rxn19764_c0
2026-01-13 20:04:29,386 - INFO - integrating rxn: rxn15550_c0
2026-01-13 20:04:29,388 - INFO - integrating rxn: rxn15072_c0
2026-01-13 20:04:29,390 - INFO - integrating rxn: rxn15064_c0
2026-01-13 20:04:29,392 - INFO - integrating rxn: rxn41185_c0
2026-01-13 20:04:29,394 - INFO - integrating rxn: rxn10095_c0
2026-01-13 20:04:29,396 - INFO - integrating rxn: rxn46249_c0
2026-01-13 20:04:29,397 - INFO - integrating rxn: rxn40040_c0
2026-01-13 20:04:29,399 - INFO - integrating rxn: rxn29260_c0
2026-01-13 20:04:29,401 - INFO - integrating rxn: rxn14423_c0
2026-01-13 20:04:29,402 - INFO - integrating rxn: rxn10042_c0
2026-01-13 20:04:29,403 - INFO - Full solution: [['EX_cpd00058_e0', '<', 'new'], ['rxn08709_c0', '>', 'new'], ['rxn00800_c0', '>', 'new'], ['rxn10336_c0', '>', 'new'], ['rxn12512_c0', '>', 'new'], ['rxn08583_c0', '>', 'new'], ['rxn10481_c0', '>', 'new'], ['rxn03918_c0', '>', 'new'], ['rxn08708_c0', '>', 'new'], ['rxn00392_c0', '>', 'new'], ['rxn09225_c0', '>', 'new'], ['rxn02774_c0', '>', 'new'], ['rxn01505_c0', '>', 'new'], ['rxn08954_c0', '>', 'new'], ['rxn00916_c0', '>', 'new'], ['rxn08618_c0', '>', 'new'], ['rxn03537_c0', '>', 'new'], ['rxn03916_c0', '>', 'new'], ['rxn05463_c0', '>', 'new'], ['rxn04413_c0', '>', 'new'], ['rxn03087_c0', '<', 'new'], ['rxn01213_c0', '>', 'new'], ['rxn03136_c0', '>', 'new'], ['rxn02056_c0', '<', 'new'], ['rxn00122_c0', '>', 'new'], ['rxn08620_c0', '>', 'new'], ['rxn02287_c0', '>', 'new'], ['rxn04308_c0', '>', 'new'], ['rxn01258_c0', '>', 'new'], ['rxn02341_c0', '>', 'new'], ['rxn08619_c0', '>', 'new'], ['rxn01603_c0', '>', 'new'], ['rxn12930_c0', '>', 'new'], ['rxn12943_c0', '>', 'new'], ['rxn12934_c0', '>', 'new'], ['rxn25474_c0', '>', 'new'], ['rxn12941_c0', '>', 'new'], ['rxn25479_c0', '>', 'new'], ['rxn22114_c0', '>', 'new'], ['rxn14070_c0', '>', 'new'], ['rxn30685_c0', '>', 'new'], ['rxn15940_c0', '>', 'new'], ['rxn30917_c0', '>', 'new'], ['rxn40674_c0', '>', 'new'], 'EX_cpd00058_e0', 'rxn08709_c0', 'rxn00800_c0', 'rxn10336_c0', 'rxn12512_c0', 'rxn08583_c0', 'rxn10481_c0', 'rxn03918_c0', 'rxn08708_c0', 'rxn00392_c0', 'rxn09225_c0', 'rxn02774_c0', 'rxn01505_c0', 'rxn08954_c0', 'rxn00916_c0', 'rxn08618_c0', 'rxn03537_c0', 'rxn03916_c0', 'rxn05463_c0', 'rxn04413_c0', 'rxn03087_c0', 'rxn01213_c0', 'rxn03136_c0', 'rxn02056_c0', 'rxn00122_c0', 'rxn08620_c0', 'rxn02287_c0', 'rxn04308_c0', 'rxn01258_c0', 'rxn02341_c0', 'rxn08619_c0', 'rxn01603_c0', 'rxn12930_c0', 'rxn12943_c0', 'rxn12934_c0', 'rxn25474_c0', 'rxn12941_c0', 'rxn25479_c0', 'rxn22114_c0', 'rxn14070_c0', 'rxn30685_c0', 'rxn15940_c0', 'rxn30917_c0', 'rxn40674_c0', ['EX_cpd15378_e0', '>', 'new'], ['rxn03436_c0', '>', 'new'], ['rxn12376_c0', '<', 'new'], ['rxn09310_c0', '>', 'new'], ['rxn02834_c0', '>', 'new'], ['rxn02185_c0', '<', 'new'], ['rxn10504_c0', '>', 'new'], ['rxn10506_c0', '>', 'new'], ['rxn48543_c0', '>', 'new'], ['rxn14424_c0', '>', 'new'], ['rxn11274_c0', '>', 'new'], ['rxn01736_c0', '>', 'new'], ['rxn25042_c0', '>', 'new'], ['rxn19766_c0', '>', 'new'], ['rxn19764_c0', '>', 'new'], ['rxn15550_c0', '>', 'new'], ['rxn15072_c0', '>', 'new'], ['rxn15064_c0', '>', 'new'], ['rxn41185_c0', '>', 'new'], ['rxn10095_c0', '>', 'new'], ['rxn46249_c0', '>', 'new'], ['rxn40040_c0', '>', 'new'], ['rxn29260_c0', '>', 'new'], ['rxn14423_c0', '>', 'new'], ['rxn10042_c0', '>', 'new']]
2026-01-13 20:04:29,739 - INFO - PyruateMinimalAnaerobic/bio1:EX_cpd00058_e0< needed:0.0 with min obj:0.01
2026-01-13 20:04:29,742 - INFO - PyruateMinimalAnaerobic/bio1:rxn08709_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:29,746 - INFO - PyruateMinimalAnaerobic/bio1:rxn00800_c0> needed:-1.783617354742593e-13 with min obj:0.01
2026-01-13 20:04:29,748 - INFO - PyruateMinimalAnaerobic/bio1:rxn10336_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:29,807 - INFO - PyruateMinimalAnaerobic/bio1:rxn12512_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:29,865 - INFO - PyruateMinimalAnaerobic/bio1:rxn08583_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:29,868 - INFO - PyruateMinimalAnaerobic/bio1:rxn10481_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:29,870 - INFO - PyruateMinimalAnaerobic/bio1:rxn03918_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:29,872 - INFO - PyruateMinimalAnaerobic/bio1:rxn08708_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:29,874 - INFO - PyruateMinimalAnaerobic/bio1:rxn00392_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:29,876 - INFO - PyruateMinimalAnaerobic/bio1:rxn09225_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:32,160 - INFO - PyruateMinimalAnaerobic/bio1:rxn02774_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:32,162 - INFO - PyruateMinimalAnaerobic/bio1:rxn01505_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,543 - INFO - PyruateMinimalAnaerobic/bio1:rxn08954_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,547 - INFO - PyruateMinimalAnaerobic/bio1:rxn00916_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,550 - INFO - PyruateMinimalAnaerobic/bio1:rxn08618_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,552 - INFO - PyruateMinimalAnaerobic/bio1:rxn03537_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,554 - INFO - PyruateMinimalAnaerobic/bio1:rxn03916_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,557 - INFO - PyruateMinimalAnaerobic/bio1:rxn05463_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,612 - INFO - PyruateMinimalAnaerobic/bio1:rxn04413_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,615 - INFO - PyruateMinimalAnaerobic/bio1:rxn03087_c0< needed:0.0 with min obj:0.01
2026-01-13 20:04:34,617 - INFO - PyruateMinimalAnaerobic/bio1:rxn01213_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,619 - INFO - PyruateMinimalAnaerobic/bio1:rxn03136_c0> needed:1.3372010548506652e-13 with min obj:0.01
2026-01-13 20:04:34,621 - INFO - PyruateMinimalAnaerobic/bio1:rxn02056_c0< needed:0.0 with min obj:0.01
2026-01-13 20:04:34,623 - INFO - PyruateMinimalAnaerobic/bio1:rxn00122_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,625 - INFO - PyruateMinimalAnaerobic/bio1:rxn08620_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,627 - INFO - PyruateMinimalAnaerobic/bio1:rxn02287_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,629 - INFO - PyruateMinimalAnaerobic/bio1:rxn04308_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,670 - INFO - PyruateMinimalAnaerobic/bio1:rxn01258_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,672 - INFO - PyruateMinimalAnaerobic/bio1:rxn02341_c0> needed:-3.719732214462527e-13 with min obj:0.01
2026-01-13 20:04:34,675 - INFO - PyruateMinimalAnaerobic/bio1:rxn08619_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,677 - INFO - PyruateMinimalAnaerobic/bio1:rxn01603_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,680 - INFO - PyruateMinimalAnaerobic/bio1:rxn12930_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,682 - INFO - PyruateMinimalAnaerobic/bio1:rxn12943_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,684 - INFO - PyruateMinimalAnaerobic/bio1:rxn12934_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,687 - INFO - PyruateMinimalAnaerobic/bio1:rxn25474_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,689 - INFO - PyruateMinimalAnaerobic/bio1:rxn12941_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,691 - INFO - PyruateMinimalAnaerobic/bio1:rxn25479_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,694 - INFO - PyruateMinimalAnaerobic/bio1:rxn22114_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,696 - INFO - PyruateMinimalAnaerobic/bio1:rxn14070_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,701 - INFO - rxn30685_c0> not needed:10.109771934109457
2026-01-13 20:04:34,704 - INFO - PyruateMinimalAnaerobic/bio1:rxn15940_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,706 - INFO - PyruateMinimalAnaerobic/bio1:rxn30917_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,708 - INFO - PyruateMinimalAnaerobic/bio1:rxn40674_c0> needed:0.0 with min obj:0.01
2026-01-13 20:04:34,716 - WARNING -     Gapfilling with PyruateMinimalAnaerobic failed: 'E'
2026-01-13 20:04:34,717 - INFO -   Running ATP safety check...

c0
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:07:15,387 - WARNING - No gapfilling solution found before filtering for H2.CO2 activating rxn00062_c0

Removing ungapfillable media H2.CO2
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:08:00,576 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:08:03,197 - WARNING - No gapfilling solution found before filtering for Light activating rxn00062_c0

Removing ungapfillable media Light

2026-01-13 20:08:03,259 - INFO - cpd01024 not found in model!
2026-01-13 20:08:03,261 - INFO - Media compound: cpd01024 not found in model.
2026-01-13 20:08:05,174 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in
Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:09:22,537 - WARNING - No gapfilling solution found for Glyc activating rxn00062_c0
2026-01-13 20:09:23,386 - WARNING - No gapfilling solution found for Methanamine.H2 activating rxn00062_c0
2026-01-13 20:09:23,733 - INFO - Objective with gapfill database:2.0; min objective:0.01
2026-01-13 20:09:24,295 - INFO - Objective with gapfill database:0.0; min objective:0.01
2026-01-13 20:09:24,331 - INFO - Initial solution: {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d319c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}
2026-01-13 20:09:24,333 - INFO - integrating rxn: rxn00799_c0
2026-01-13 20:09:24,335 - INFO - integrating rxn: rxn00250_c0
2026-01-13 20:09:24,336 - INFO - integrating rxn: rxn05319_c0
2026-01-13 20:09:24,337 - INFO - Full solution: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:09:24,442 - INFO - Fum/rxn00062_c0:rxn00799_c0< needed:0.0 with min obj:0.01
2026-01-13 20:09:24,490 - INFO - Fum/rxn00062_c0:rxn00250_c0< needed:0.0 with min obj:0.01
2026-01-13 20:09:24,492 - INFO - Fum/rxn00062_c0:rxn05319_c0> needed:0.0 with min obj:0.01
2026-01-13 20:09:24,587 - INFO - Cumulative media target solution: {'growth': 0, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d319c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False, 'new': {'rxn00799_c0': '<'}, 'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}}
2026-01-13 20:09:25,226 - INFO - Unneeded: []

Adding gapfilling {'reversed': {'rxn00250_c0': '<', 'rxn05319_c0': '>'}, 'new': {'rxn00799_c0': '<'}, 'media': <modelseedpy.core.msmedia.MSMedia object at 0x79fa04d319c0>, 'target': 'rxn00062_c0', 'minobjective': 0.01, 'binary_check': False}

2026-01-13 20:09:25,256 - INFO - Cumulative: [['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['EX_cpd00027_e0', '<', 'new'], ['rxn00336_c0', '>', 'new'], ['rxn00330_c0', '<', 'new'], ['rxn07191_c0', '<', 'new'], ['rxn08527_c0', '<', 'new'], ['rxn05226_c0', '>', 'new'], ['rxn00799_c0', '<', 'new'], ['rxn00250_c0', '<', 'reversed'], ['EX_cpd00100_e0', '<', 'new'], ['rxn05581_c0', '<', 'new'], ['rxn09269_c0', '>', 'new'], ['rxn05319_c0', '>', 'reversed']]
2026-01-13 20:09:25,952 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:09:32,448 - WARNING - No gapfilling solution found before filtering for Ac activating rxn00062_c0

Removing ungapfillable media Ac

2026-01-13 20:09:41,460 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:10:48,035 - WARNING - No gapfilling solution found for For.NO2 activating rxn00062_c0
2026-01-13 20:10:49,088 - INFO - Objective with gapfill database:0.0; min objective:0.01

Neither carbon consumption nor oxygen consumption are defined in

2026-01-13 20:10:51,673 - WARNING - No gapfilling solution found before filtering for Dimethylamine.H2 activating rxn00062_c0

## Define the metabolite-centered phenotypes

# create community models from the member models and abundances

In [1]:
from cobra.io import read_sbml_model, write_sbml_model
from pandas import read_csv, Series
from mscommunity import build_from_species_models
from tqdm import tqdm
from json import load
import os

iterativeIDs = load(open("model_inputs/iterativeIDs.json", 'r'))
ASV_sets = load(open("modeling_files/ASV_sets.json", 'r'))
redunant_asvs = {v:k for k,vs in ASV_sets.items() for v in vs}
abundances = load(open("modeling_files/ASVset_abundances.json", 'r'))
abundances = {sample: {iterativeIDs.get(ASV): abund for ASV, abund in content.items()}
              for sample, content in abundances.items()}
abundances_new = {sample: {iterativeIDs.get(ASV): {"abundance": abund} for ASV, abund in content.items()}
              for sample, content in abundances.items()}

def create_comm(item):
    sample, abundances = item
    models = []
    for ASVset, abun in abundances.items():
        # ASVset = iterativeIDs[redunant_asvs.get(ASV, ASV)]
        # print(ASVset)
        model_path = f"gapfilled_models/{ASVset}_gf.xml"
        #TODO:  investigate why these ASVs did not have any genomeIDs
        if not os.path.exists(model_path):  # some ASVs have no genomeIDs
            continue
            
        model = read_sbml_model(model_path)
        model.id = ASVset
        models.append(model)
    modelID = f"{sample}_comm"
    modelName = f"{sample}_comm"
    print(len(models))
    comm_model = build_from_species_models(models, modelID, modelName, printing=True) #abundances_new, printing=True)
    write_sbml_model(comm_model, f"comm_models/{modelID}.xml")

# parallelize the effort
args = [item for item in abundances.items() if not os.path.exists(f"comm_models/{item[0]}_comm.xml")]
print(len(args), "will be processed")
parallelize = False
if parallelize:
    from multiprocess import Pool
    from os import cpu_count
    
    cpus = min(len(args), int(cpu_count()/8))
    print(f"{cpus} cores are being used.  The first argument is {args[0]}")
    pool = Pool(cpus)
    outputs = pool.map(create_comm, args)
    
    print(f"missing iterativeIDs", missing_iterativeIDs)
    print(f"missing IDs", missing_IDs)
else:
    for arg in args:
        # print(arg)
        create_comm(arg)
        # break

modelseedpy 0.3.3

/home/afreiburger/repos/MSCommunity/mscommunity/commhelper.py:25: SyntaxWarning: invalid escape sequence '\_'
  return re.sub("(\_\w\d)", "", ID)
/home/afreiburger/repos/MSCommunity/mscommunity/commhelper.py:111: SyntaxWarning: invalid escape sequence '\d'
  if re.search('^(bio)(\d+)$', rxn.id) or "biomass" in rxn.id:

19 will be processed
156
156 models are being processed
1058 metabolites of midas_g_4042.3 are being processed
midas_g_4042.3 biomass metabolite captured cpd11416_c1
1048 reactions of midas_g_4042.3 are being processed
bio1 from midas_g_4042.3 becomes bio2
987 metabolites of midas_g_269.4 are being processed
midas_g_269.4 biomass metabolite captured cpd11416_c2
986 reactions of midas_g_269.4 are being processed
bio1 from midas_g_269.4 becomes bio3
941 metabolites of midas_g_52.2 are being processed
midas_g_52.2 biomass metabolite captured cpd11416_c3
950 reactions of midas_g_52.2 are being processed
bio1 from midas_g_52.2 becomes bio4
796 metabolites of OPB41.1 are being processed
OPB41.1 biomass metabolite captured cpd11416_c4
812 reactions of OPB41.1 are being processed
bio1 from OPB41.1 becomes bio5
787 metabolites of midas_g_531.1 are being processed
midas_g_531.1 biomass metabolite captured cpd11416_c5
784 reactions of midas_g_531.1 are being processed
bio1 from midas_g_531.1 becomes bio6
1073 metabolites of IMCC26207.3 are being processed
IMCC26207.3 biomass metabolite captured cpd11416_c6
1100 reactions of IMCC26207.3 are being processed
bio1 from IMCC26207.3 becomes bio7
1751 metabolites of Brooklawnia.1 are being processed
Brooklawnia.1 biomass metabolite captured cpd11416_c7
2139 reactions of Brooklawnia.1 are being processed
bio1 from Brooklawnia.1 becomes bio8
1751 metabolites of Propionicicella.4 are being processed
Propionicicella.4 biomass metabolite captured cpd11416_c8
2103 reactions of Propionicicella.4 are being processed
bio1 from Propionicicella.4 becomes bio9
1452 metabolites of Mycobacterium.6 are being processed
Mycobacterium.6 biomass metabolite captured cpd11416_c9
1654 reactions of Mycobacterium.6 are being processed
bio1 from Mycobacterium.6 becomes bio10
1547 metabolites of Mycobacterium.13 are being processed
Mycobacterium.13 biomass metabolite captured cpd11416_c10
1797 reactions of Mycobacterium.13 are being processed
bio1 from Mycobacterium.13 becomes bio11
1224 metabolites of Mycobacterium.14 are being processed
Mycobacterium.14 biomass metabolite captured cpd11416_c11
1375 reactions of Mycobacterium.14 are being processed
bio1 from Mycobacterium.14 becomes bio12
1157 metabolites of Gordonia.6 are being processed
Gordonia.6 biomass metabolite captured cpd11416_c12
1235 reactions of Gordonia.6 are being processed
bio1 from Gordonia.6 becomes bio13
1075 metabolites of Leucobacter.3 are being processed
Leucobacter.3 biomass metabolite captured cpd11416_c13
1160 reactions of Leucobacter.3 are being processed
bio1 from Leucobacter.3 becomes bio14
1065 metabolites of Microbacterium.10 are being processed
Microbacterium.10 biomass metabolite captured cpd11416_c14
1178 reactions of Microbacterium.10 are being processed
bio1 from Microbacterium.10 becomes bio15
985 metabolites of midas_g_399.2 are being processed
midas_g_399.2 biomass metabolite captured cpd11416_c15
1024 reactions of midas_g_399.2 are being processed
bio1 from midas_g_399.2 becomes bio16
884 metabolites of midas_g_399.4 are being processed
midas_g_399.4 biomass metabolite captured cpd11416_c16
914 reactions of midas_g_399.4 are being processed
bio1 from midas_g_399.4 becomes bio17
896 metabolites of midas_g_399.5 are being processed
midas_g_399.5 biomass metabolite captured cpd11416_c17
935 reactions of midas_g_399.5 are being processed
bio1 from midas_g_399.5 becomes bio18
853 metabolites of midas_g_497.1 are being processed
midas_g_497.1 biomass metabolite captured cpd11416_c18
874 reactions of midas_g_497.1 are being processed
bio1 from midas_g_497.1 becomes bio19
828 metabolites of Methanobacterium.6 are being processed
Methanobacterium.6 biomass metabolite captured cpd11416_c19
792 reactions of Methanobacterium.6 are being processed
bio1 from Methanobacterium.6 becomes bio20
749 metabolites of Methanobacteriaceae.1 are being processed
Methanobacteriaceae.1 biomass metabolite captured cpd11416_c20
732 reactions of Methanobacteriaceae.1 are being processed
bio1 from Methanobacteriaceae.1 becomes bio21
819 metabolites of Methanobacterium.5 are being processed
Methanobacterium.5 biomass metabolite captured cpd11416_c21
788 reactions of Methanobacterium.5 are being processed
bio1 from Methanobacterium.5 becomes bio22
723 metabolites of Methanobacterium.90 are being processed
Methanobacterium.90 biomass metabolite captured cpd11416_c22
712 reactions of Methanobacterium.90 are being processed
bio1 from Methanobacterium.90 becomes bio23
878 metabolites of midas_g_5426.1 are being processed
midas_g_5426.1 biomass metabolite captured cpd11416_c23
874 reactions of midas_g_5426.1 are being processed
bio1 from midas_g_5426.1 becomes bio24
1218 metabolites of Syner-01.1 are being processed
Syner-01.1 biomass metabolite captured cpd11416_c24
1316 reactions of Syner-01.1 are being processed
bio1 from Syner-01.1 becomes bio25
1249 metabolites of Syner-01.2 are being processed
Syner-01.2 biomass metabolite captured cpd11416_c25
1346 reactions of Syner-01.2 are being processed
bio1 from Syner-01.2 becomes bio26
1065 metabolites of Aminivibrio.1 are being processed
Aminivibrio.1 biomass metabolite captured cpd11416_c26
1111 reactions of Aminivibrio.1 are being processed
bio1 from Aminivibrio.1 becomes bio27
818 metabolites of Ca_Cloacimonas.2 are being processed
Ca_Cloacimonas.2 biomass metabolite captured cpd11416_c27
843 reactions of Ca_Cloacimonas.2 are being processed
bio1 from Ca_Cloacimonas.2 becomes bio28
988 metabolites of LNR_A2-18.1 are being processed
LNR_A2-18.1 biomass metabolite captured cpd11416_c28
985 reactions of LNR_A2-18.1 are being processed
bio1 from LNR_A2-18.1 becomes bio29
864 metabolites of Ca_Cloacimonas.4 are being processed
Ca_Cloacimonas.4 biomass metabolite captured cpd11416_c29
900 reactions of Ca_Cloacimonas.4 are being processed
bio1 from Ca_Cloacimonas.4 becomes bio30
1387 metabolites of midas_g_25828.1 are being processed
midas_g_25828.1 biomass metabolite captured cpd11416_c30
1675 reactions of midas_g_25828.1 are being processed
bio1 from midas_g_25828.1 becomes bio31
1159 metabolites of Marinilabiliaceae.1 are being processed
Marinilabiliaceae.1 biomass metabolite captured cpd11416_c31
1215 reactions of Marinilabiliaceae.1 are being processed
bio1 from Marinilabiliaceae.1 becomes bio32
1032 metabolites of midas_g_19.2 are being processed
midas_g_19.2 biomass metabolite captured cpd11416_c32
1080 reactions of midas_g_19.2 are being processed
bio1 from midas_g_19.2 becomes bio33
1440 metabolites of midas_g_36215.1 are being processed
midas_g_36215.1 biomass metabolite captured cpd11416_c33
1736 reactions of midas_g_36215.1 are being processed
bio1 from midas_g_36215.1 becomes bio34
876 metabolites of midas_g_36215.6 are being processed
midas_g_36215.6 biomass metabolite captured cpd11416_c34
862 reactions of midas_g_36215.6 are being processed
bio1 from midas_g_36215.6 becomes bio35
854 metabolites of DMER64.3 are being processed
DMER64.3 biomass metabolite captured cpd11416_c35
888 reactions of DMER64.3 are being processed
bio1 from DMER64.3 becomes bio36
1581 metabolites of Fermentimonas.6 are being processed
Fermentimonas.6 biomass metabolite captured cpd11416_c36
1878 reactions of Fermentimonas.6 are being processed
bio1 from Fermentimonas.6 becomes bio37
1077 metabolites of Proteiniphilum.1 are being processed
Proteiniphilum.1 biomass metabolite captured cpd11416_c37
1118 reactions of Proteiniphilum.1 are being processed
bio1 from Proteiniphilum.1 becomes bio38
1080 metabolites of Fermentimonas.1 are being processed
Fermentimonas.1 biomass metabolite captured cpd11416_c38
1113 reactions of Fermentimonas.1 are being processed
bio1 from Fermentimonas.1 becomes bio39
852 metabolites of Proteiniphilum.22 are being processed
Proteiniphilum.22 biomass metabolite captured cpd11416_c39
901 reactions of Proteiniphilum.22 are being processed
bio1 from Proteiniphilum.22 becomes bio40
570 metabolites of midas_g_9269.1 are being processed
midas_g_9269.1 biomass metabolite captured cpd11416_c40
599 reactions of midas_g_9269.1 are being processed
bio1 from midas_g_9269.1 becomes bio41
1050 metabolites of midas_g_83754.1 are being processed
midas_g_83754.1 biomass metabolite captured cpd11416_c41
1073 reactions of midas_g_83754.1 are being processed
bio1 from midas_g_83754.1 becomes bio42
1485 metabolites of Thermovirga.2 are being processed
Thermovirga.2 biomass metabolite captured cpd11416_c42
1772 reactions of Thermovirga.2 are being processed
bio1 from Thermovirga.2 becomes bio43
1026 metabolites of Bacteria.21 are being processed
Bacteria.21 biomass metabolite captured cpd11416_c43
1029 reactions of Bacteria.21 are being processed
bio1 from Bacteria.21 becomes bio44
986 metabolites of Thiopseudomonas.1 are being processed
Thiopseudomonas.1 biomass metabolite captured cpd11416_c44
1023 reactions of Thiopseudomonas.1 are being processed
bio1 from Thiopseudomonas.1 becomes bio45
1116 metabolites of Pseudomonas.5 are being processed
Pseudomonas.5 biomass metabolite captured cpd11416_c45
1174 reactions of Pseudomonas.5 are being processed
bio1 from Pseudomonas.5 becomes bio46
1156 metabolites of Pseudomonas.7 are being processed
Pseudomonas.7 biomass metabolite captured cpd11416_c46
1203 reactions of Pseudomonas.7 are being processed
bio1 from Pseudomonas.7 becomes bio47
1399 metabolites of Rhodanobacter.5 are being processed
Rhodanobacter.5 biomass metabolite captured cpd11416_c47
1627 reactions of Rhodanobacter.5 are being processed
bio1 from Rhodanobacter.5 becomes bio48
1349 metabolites of Rhodanobacter.2 are being processed
Rhodanobacter.2 biomass metabolite captured cpd11416_c48
1482 reactions of Rhodanobacter.2 are being processed
bio1 from Rhodanobacter.2 becomes bio49
1101 metabolites of Rheinheimera.1 are being processed
Rheinheimera.1 biomass metabolite captured cpd11416_c49
1193 reactions of Rheinheimera.1 are being processed
bio1 from Rheinheimera.1 becomes bio50
1067 metabolites of midas_g_70.1 are being processed
midas_g_70.1 biomass metabolite captured cpd11416_c50
1086 reactions of midas_g_70.1 are being processed
bio1 from midas_g_70.1 becomes bio51
1346 metabolites of Alcaligenaceae.6 are being processed
Alcaligenaceae.6 biomass metabolite captured cpd11416_c51
1459 reactions of Alcaligenaceae.6 are being processed
bio1 from Alcaligenaceae.6 becomes bio52
1050 metabolites of Pusillimonas.2 are being processed
Pusillimonas.2 biomass metabolite captured cpd11416_c52
1078 reactions of Pusillimonas.2 are being processed
bio1 from Pusillimonas.2 becomes bio53
1295 metabolites of Comamonas.3 are being processed
Comamonas.3 biomass metabolite captured cpd11416_c53
1538 reactions of Comamonas.3 are being processed
bio1 from Comamonas.3 becomes bio54
1153 metabolites of Rhodocyclaceae.5 are being processed
Rhodocyclaceae.5 biomass metabolite captured cpd11416_c54
1209 reactions of Rhodocyclaceae.5 are being processed
bio1 from Rhodocyclaceae.5 becomes bio55
1618 metabolites of Azoarcus.4 are being processed
Azoarcus.4 biomass metabolite captured cpd11416_c55
1940 reactions of Azoarcus.4 are being processed
bio1 from Azoarcus.4 becomes bio56
1438 metabolites of Thauera.2 are being processed
Thauera.2 biomass metabolite captured cpd11416_c56
1613 reactions of Thauera.2 are being processed
bio1 from Thauera.2 becomes bio57
987 metabolites of Desulfococcaceae.1 are being processed
Desulfococcaceae.1 biomass metabolite captured cpd11416_c57
993 reactions of Desulfococcaceae.1 are being processed
bio1 from Desulfococcaceae.1 becomes bio58
1137 metabolites of Desulfovibrio.3 are being processed
Desulfovibrio.3 biomass metabolite captured cpd11416_c58
1190 reactions of Desulfovibrio.3 are being processed
bio1 from Desulfovibrio.3 becomes bio59
1040 metabolites of Desulfomicrobium.1 are being processed
Desulfomicrobium.1 biomass metabolite captured cpd11416_c59
1058 reactions of Desulfomicrobium.1 are being processed
bio1 from Desulfomicrobium.1 becomes bio60
1279 metabolites of Desulfovibrionaceae.2 are being processed
Desulfovibrionaceae.2 biomass metabolite captured cpd11416_c60
1422 reactions of Desulfovibrionaceae.2 are being processed
bio1 from Desulfovibrionaceae.2 becomes bio61
1097 metabolites of Parvibaculum.1 are being processed
Parvibaculum.1 biomass metabolite captured cpd11416_c61
1085 reactions of Parvibaculum.1 are being processed
bio1 from Parvibaculum.1 becomes bio62
1310 metabolites of Amaricoccus.1 are being processed
Amaricoccus.1 biomass metabolite captured cpd11416_c62
1388 reactions of Amaricoccus.1 are being processed
bio1 from Amaricoccus.1 becomes bio63
1386 metabolites of Amaricoccus.3 are being processed
Amaricoccus.3 biomass metabolite captured cpd11416_c63
1515 reactions of Amaricoccus.3 are being processed
bio1 from Amaricoccus.3 becomes bio64
1653 metabolites of Rhodobacter.5 are being processed
Rhodobacter.5 biomass metabolite captured cpd11416_c64
1987 reactions of Rhodobacter.5 are being processed
bio1 from Rhodobacter.5 becomes bio65
1086 metabolites of Caulobacteraceae.1 are being processed
Caulobacteraceae.1 biomass metabolite captured cpd11416_c65
1159 reactions of Caulobacteraceae.1 are being processed
bio1 from Caulobacteraceae.1 becomes bio66
1124 metabolites of Hyphomonas.1 are being processed
Hyphomonas.1 biomass metabolite captured cpd11416_c66
1157 reactions of Hyphomonas.1 are being processed
bio1 from Hyphomonas.1 becomes bio67
1137 metabolites of Rhizobiaceae.1 are being processed
Rhizobiaceae.1 biomass metabolite captured cpd11416_c67
1178 reactions of Rhizobiaceae.1 are being processed
bio1 from Rhizobiaceae.1 becomes bio68
1429 metabolites of Aquamicrobium.1 are being processed
Aquamicrobium.1 biomass metabolite captured cpd11416_c68
1556 reactions of Aquamicrobium.1 are being processed
bio1 from Aquamicrobium.1 becomes bio69
1346 metabolites of Aquamicrobium.5 are being processed
Aquamicrobium.5 biomass metabolite captured cpd11416_c69
1419 reactions of Aquamicrobium.5 are being processed
bio1 from Aquamicrobium.5 becomes bio70
1247 metabolites of Aquamicrobium.7 are being processed
Aquamicrobium.7 biomass metabolite captured cpd11416_c70
1296 reactions of Aquamicrobium.7 are being processed
bio1 from Aquamicrobium.7 becomes bio71
1306 metabolites of Devosia.1 are being processed
Devosia.1 biomass metabolite captured cpd11416_c71
1442 reactions of Devosia.1 are being processed
bio1 from Devosia.1 becomes bio72
1127 metabolites of Devosia.7 are being processed
Devosia.7 biomass metabolite captured cpd11416_c72
1221 reactions of Devosia.7 are being processed
bio1 from Devosia.7 becomes bio73
1452 metabolites of Stappia.1 are being processed
Stappia.1 biomass metabolite captured cpd11416_c73
1625 reactions of Stappia.1 are being processed
bio1 from Stappia.1 becomes bio74
1156 metabolites of Hyphomicrobium.2 are being processed
Hyphomicrobium.2 biomass metabolite captured cpd11416_c74
1189 reactions of Hyphomicrobium.2 are being processed
bio1 from Hyphomicrobium.2 becomes bio75
1324 metabolites of Hyphomicrobium.10 are being processed
Hyphomicrobium.10 biomass metabolite captured cpd11416_c75
1415 reactions of Hyphomicrobium.10 are being processed
bio1 from Hyphomicrobium.10 becomes bio76
1104 metabolites of Rhodobacteraceae.6 are being processed
Rhodobacteraceae.6 biomass metabolite captured cpd11416_c76
1118 reactions of Rhodobacteraceae.6 are being processed
bio1 from Rhodobacteraceae.6 becomes bio77
514 metabolites of midas_g_57.2 are being processed
midas_g_57.2 biomass metabolite captured cpd11416_c77
561 reactions of midas_g_57.2 are being processed
bio1 from midas_g_57.2 becomes bio78
1189 metabolites of Xanthobacteraceae.1 are being processed
Xanthobacteraceae.1 biomass metabolite captured cpd11416_c78
1244 reactions of Xanthobacteraceae.1 are being processed
bio1 from Xanthobacteraceae.1 becomes bio79
1082 metabolites of Pseudochelatococcus.1 are being processed
Pseudochelatococcus.1 biomass metabolite captured cpd11416_c79
1142 reactions of Pseudochelatococcus.1 are being processed
bio1 from Pseudochelatococcus.1 becomes bio80
1331 metabolites of Afipia.1 are being processed
Afipia.1 biomass metabolite captured cpd11416_c80
1416 reactions of Afipia.1 are being processed
bio1 from Afipia.1 becomes bio81
1204 metabolites of Alphaproteobacteria.4 are being processed
Alphaproteobacteria.4 biomass metabolite captured cpd11416_c81
1220 reactions of Alphaproteobacteria.4 are being processed
bio1 from Alphaproteobacteria.4 becomes bio82
906 metabolites of Smithella.2 are being processed
Smithella.2 biomass metabolite captured cpd11416_c82
893 reactions of Smithella.2 are being processed
bio1 from Smithella.2 becomes bio83
1214 metabolites of Syntrophobacter.1 are being processed
Syntrophobacter.1 biomass metabolite captured cpd11416_c83
1270 reactions of Syntrophobacter.1 are being processed
bio1 from Syntrophobacter.1 becomes bio84
1083 metabolites of Syntrophobacter.7 are being processed
Syntrophobacter.7 biomass metabolite captured cpd11416_c84
1093 reactions of Syntrophobacter.7 are being processed
bio1 from Syntrophobacter.7 becomes bio85
998 metabolites of Desulfuromonadaceae.1 are being processed
Desulfuromonadaceae.1 biomass metabolite captured cpd11416_c85
994 reactions of Desulfuromonadaceae.1 are being processed
bio1 from Desulfuromonadaceae.1 becomes bio86
826 metabolites of RBG-16-49-21.1 are being processed
RBG-16-49-21.1 biomass metabolite captured cpd11416_c86
808 reactions of RBG-16-49-21.1 are being processed
bio1 from RBG-16-49-21.1 becomes bio87
818 metabolites of midas_g_1408.1 are being processed
midas_g_1408.1 biomass metabolite captured cpd11416_c87
842 reactions of midas_g_1408.1 are being processed
bio1 from midas_g_1408.1 becomes bio88
1407 metabolites of Hydrogenedensaceae.1 are being processed
Hydrogenedensaceae.1 biomass metabolite captured cpd11416_c88
1567 reactions of Hydrogenedensaceae.1 are being processed
bio1 from Hydrogenedensaceae.1 becomes bio89
1059 metabolites of Pir4_lineage.7 are being processed
Pir4_lineage.7 biomass metabolite captured cpd11416_c89
1059 reactions of Pir4_lineage.7 are being processed
bio1 from Pir4_lineage.7 becomes bio90
1269 metabolites of midas_g_5834.2 are being processed
midas_g_5834.2 biomass metabolite captured cpd11416_c90
1362 reactions of midas_g_5834.2 are being processed
bio1 from midas_g_5834.2 becomes bio91
710 metabolites of Leptolinea.3 are being processed
Leptolinea.3 biomass metabolite captured cpd11416_c91
774 reactions of Leptolinea.3 are being processed
bio1 from Leptolinea.3 becomes bio92
987 metabolites of midas_g_156.1 are being processed
midas_g_156.1 biomass metabolite captured cpd11416_c92
1053 reactions of midas_g_156.1 are being processed
bio1 from midas_g_156.1 becomes bio93
1010 metabolites of Ca_Caldatribacterium.1 are being processed
Ca_Caldatribacterium.1 biomass metabolite captured cpd11416_c93
1082 reactions of Ca_Caldatribacterium.1 are being processed
bio1 from Ca_Caldatribacterium.1 becomes bio94
1253 metabolites of midas_g_3409.1 are being processed
midas_g_3409.1 biomass metabolite captured cpd11416_c94
1335 reactions of midas_g_3409.1 are being processed
bio1 from midas_g_3409.1 becomes bio95
897 metabolites of midas_g_249.4 are being processed
midas_g_249.4 biomass metabolite captured cpd11416_c95
902 reactions of midas_g_249.4 are being processed
bio1 from midas_g_249.4 becomes bio96
897 metabolites of Thermovirga.6 are being processed
Thermovirga.6 biomass metabolite captured cpd11416_c96
935 reactions of Thermovirga.6 are being processed
bio1 from Thermovirga.6 becomes bio97
1024 metabolites of midas_g_515.1 are being processed
midas_g_515.1 biomass metabolite captured cpd11416_c97
1051 reactions of midas_g_515.1 are being processed
bio1 from midas_g_515.1 becomes bio98
790 metabolites of midas_g_4306.1 are being processed
midas_g_4306.1 biomass metabolite captured cpd11416_c98
850 reactions of midas_g_4306.1 are being processed

In [15]:
from json import load
abundances = load(open("modeling_files/ASVset_abundances.json", 'r'))
list(list(abundances.values())[0].values())[0]

0.0035438998239284624

## Test that the models are operational

In [ ]:
from cobra.io import read_sbml_model
from glob import glob

# for path in glob("models/F34_comm.xml"):
# for path in glob("comm_models/G12_comm.xml"):
    # print(path.split("/")[-1])
model = read_sbml_model("comm_models/P12_comm.xml")
# break

In [ ]:
print(model.objective)
display(model.summary())

In [ ]:
model.reactions.bio1.reaction

In [ ]:
bioReactions = []
for rxn in model.reactions:
    if "bio" in rxn.id:
        bioReactions.append(rxn.id)
bioReactions = sorted(bioReactions)
print(len(bioReactions), bioReactions)

In [ ]:
bioCompounds = []
for cpd in model.metabolites:
    if "cpd11416" in cpd.id:
        bioCompounds.append(cpd.id)
bioCompounds = sorted(bioCompounds)
print(len(bioCompounds), bioCompounds)

# Community modeling

## Load the community models

In [11]:
%%time
from cobra.io import read_sbml_model
from tqdm import tqdm
from glob import glob

def load_models():
    models = {}
    num_models = 1
    modelID = "P12_comm"
    for model_path in tqdm(glob(f"comm_models/{modelID}.xml")[:num_models]):
        modelID = model_path.split("/")[-1].replace(".xml", '')
        print("loading", modelID)
        model = read_sbml_model(model_path)
        model.id = modelID
        models[modelID] = model
    return models

models = load_models()

  0%|          | 0/1 [00:00<?, ?it/s]

loading P12_comm

100%|██████████| 1/1 [01:24<00:00, 84.56s/it]

CPU times: user 1min 22s, sys: 2.28 s, total: 1min 24s
Wall time: 1min 24s

In [2]:
type(models[modelID].solver)

optlang.gurobi_interface.Model

In [3]:
%%time
display(models)
print(models[modelID].objective)
display(models[modelID].summary())

{'P12_comm': <Model P12_comm at 0x7fa5adfb8070>}

Maximize
1.0*bio1 - 1.0*bio1_reverse_b18f7

CPU times: user 1min 10s, sys: 340 ms, total: 1min 10s
Wall time: 1min 10s

## Constraints

### Process data

#### convert measurements into MSIDs

In [4]:
from collections import Counter
from pandas import read_csv, set_option
from json import dump

set_option("display.max_columns", None)

mapping = {"Media Acetate (mol/L)": "cpd00029_in", "Media Propionate (mol/L)": "cpd00141_in",
           "Media Butyrate (mol/L)": "cpd00211_in", "Waste Effluent Acetate (mol/L)": "cpd00029_out",
           "Waste Effluent Propionate (mol/L)": "cpd00141_out", "Waste Effluent Butyrate (mol/L)": "cpd00211_out",
           "Approximate Total Influent C (mol/min) based on Media recipe": "media_carbon_in",
           # "Media Total COD (mg/L) Hach": "media_cpd00007",
           "Measured Total Influent C (mol/min)": "carbon_in",
           "Gas Composition (% CH4)": "%cpd01024", "Gas Composition (% H2)": "%cpd11640", "Gas Composition (% CO2)": "%cpd00011",
           "CH4 breakthrough (mol/min)": "cpd01024_out", "H2 breakthrough (mol/min)": "cpd11640_out", "CO2 breakthrough (mol/min)": "cpd00011_out",
           "Accounted C (%) based on MT sensors": "accounted_C"}


data = read_csv("model_inputs/measurements/Summary_interpolated.csv")
data["Media Total COD (mg/L) Hach"] /= 32000
data["carbon_out"] = data["Waste Effluent Dissolved Inorganic Carbon (mol C/L)"] + data["Waste Effluent Dissolved Organic Carbon (mol C/L)"
                        ] + data["Effluent C as measured (mol/min)"]
data.rename(columns=mapping, inplace=True)
data = data[data["Biomass Sample ID"].notna()].set_index("Biomass Sample ID")
# print(Counter(data.columns))
data_df = data.T.to_dict()
dump(data_df, open("model_inputs/measurements/Summer_interpolated_MSDB.json", 'w'), indent=2)
data

,Days of Operation,Media description,Media changes,Media Influent Flow Rate (mL/min) based on scales linear projection,"pH adjustment delivery rate (mL/min) - primarily 1 M HCl, sometimes 1 M NaOH",cpd00029_in,cpd00141_in,cpd00211_in,Media Total VFA (mg COD/L),Media Total COD (mg/L) Hach,Media Ammonia (mol/L),Media Dissolved Inorganic Carbon (mol C/L),Media Dissolved Organic Carbon (mol C/L),media_carbon_in,H2 delivery rate setpoint (mL/min),CO2 delivery rate setpoint (mL/min),H2 delivery rate (mol/min),H2 delivery rate (e-eq/min),H2 delivery (g COD/min),CO2 delivery rate (mol/min),H2:CO2 ratio,carbon_in,Approximate Total Influent C (mol/min) based on Media recipe + gas,Effluent waste flow rate (mL/min) - measured based on HRT after Day 38.1,cpd00029_out,cpd00141_out,cpd00211_out,Waste Effluent Total VFA (mg COD/L),Waste Effluent Total COD (mg/L) Hach,Waste Effluent Ammonia (mol/L),Waste Effluent Dissolved Inorganic Carbon (mol C/L),Waste Effluent Dissolved Organic Carbon (mol C/L),Gas Flow Out (mL/min at STP),%cpd01024,%cpd11640,%cpd00011,CH4 Production (mol/min),cpd11640_out,cpd00011_out,Specific CH4 production Rate (m3/m3d) .155,Specific CH4 production Rate (L/m2d),Waste Effluent Dissolved Inorganic Carbon (mol/min) based on sensor,Effluent C as measured (mol/min),Effluent C as biomass (mol/min),Total Effluent C (mol/min) based on MT sensors,H2 Conversion to CH4 Efficiency (%),H2 conversion to CH4 efficiency (30-day rolling average),Accounted H2 (%),Unaccounted H2 (%),C gas only Conversion Efficiency to CH4 (%),CO2 conversion to CH4 efficiency (30-day rolling average),C Conversion to CH4 Efficiency (%),accounted_C,Unaccounted C (%) based on MT sensors,Projected Cell Yield (g/min),R-TSS,W-TSS,R-VSS,W-VSS,SRT,HRT,pH,"CO2 (mg/L, aqueous dissolved CO2)",ORP (mV),Temp ©,[H],[CO2aq],pKa1,pKa2,[HCO3-],[CO3-2],TIC,carbon_out
Biomass Sample ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10AB,0.0,DSMZ v1: Using DSMZ 120 without NaHCO3,1.0,0.059222,0.000000,0.035427,2.248985e-03,NaN,2480.559207,0.548295,NaN,NaN,NaN,2.670566e-05,1.091525,0.250,0.000049,0.000268,0.012475,0.000011,4.366099,0.000011,0.000038,0.059222,0.035564,0.035564,NaN,2446.060693,NaN,NaN,0.035417,0.468748,1.027461,0.000000,0.875885,0.124115,0.000000,4.017581e-05,5.692991e-06,0.000000,0.000000,2.444632e-07,2.776001e-05,NaN,0.000006,0.000000,NaN,0.824478,0.175522,0.000000,NaN,0.000000,0.156800,0.843200,0.000998,NaN,NaN,NaN,NaN,NaN,NaN,6.902000,41.050000,-305.292000,30.647000,1.253141e-07,0.000933,6.367442,10.323185,0.003194,1.211003e-06,0.004128,0.504193
A34,21.5,DSMZ v1.5: Using DSMZ 120 with NaHCO3,1.0,0.059222,0.000000,0.028778,2.748583e-03,NaN,2116.936358,0.548295,NaN,0.051964,0.410238,2.811553e-05,0.545762,0.250,0.000024,0.000134,0.006237,0.000011,2.183050,0.000011,0.000039,0.059222,0.026992,0.026992,NaN,1794.152069,NaN,NaN,0.000800,0.030954,0.507551,0.404956,0.587181,0.007863,0.000009,1.330465e-05,1.781714e-07,1.909494,2.039777,3.321556e-07,1.833154e-06,NaN,0.000010,1.506413,NaN,2.052482,-1.052482,0.822143,NaN,0.233620,0.246613,0.753387,0.000499,NaN,NaN,NaN,NaN,NaN,NaN,7.040000,41.036000,-519.691000,36.422000,9.120108e-08,0.000932,6.339978,10.276568,0.004674,2.710676e-06,0.005609,0.031756
B34,34.9,DSMZ v1.5: Using DSMZ 120 with NaHCO3,1.0,2.079047,0.000000,0.018355,3.433353e-03,NaN,1536.108186,0.548295,NaN,0.040055,0.352996,2.811553e-05,1.091525,0.250,0.000049,0.000268,0.012475,0.000011,4.366099,0.000011,0.000039,2.079047,0.014906,0.014906,NaN,1212.358448,NaN,NaN,0.002331,0.057877,0.552281,0.270950,0.722636,0.006414,0.000007,1.781687e-05,1.581396e-07,1.390208,1.485060,4.810820e-07,3.427590e-06,NaN,0.000007,0.548372,1.413849,0.914005,0.085995,0.598562,0.669297,0.170087,0.186362,0.813638,0.000998,NaN,NaN,NaN,NaN,NaN,NaN,7.044000,1.675000,-520.272000,36.750000,9.036495e-08,0.000038,6.338419,10.273920,0.000193,1.137981e-07,0.000231,0.060212
C3,68.5,DSMZ v2: Dropped Na-Ac out of DSMZ 120 media,1.0,0.059222,0.000000,0.016016,2.804749e-03,NaN,1319.241036,0.488125,0.025907,0.020676,0.427532,2.129103e-05,0.988000,0.344,0.000044,0.000243,0.011291,0.000015,2.872093,0.000015,0.000037,0.059222,0.000792,0.000792,NaN,778.987585,NaN,0.019082,0.016326,0.031968,0.848818,0.775053,0.003683,0.221264,0.000029,1.395771e-07,8.384514e-06,6.111912,6.528920,3.347681e-07,1.922890e-06,4.594952e-07,0.000038,2.663479,1.775951,2.666644,-1.666644,1.912440,1.510110,0.801394,1.039312,-0.039312,0.000903,382.557143,216.085714,298.014286,153.971429,5.749888,5.382530,7.045000,41.037000,-513.338000,36.225000,9.015711e-08,0.000932,6.340915,10.278158,0.004718,2.757789e-06,0.005653,0.048296
D34,82.5,DSMZ v2: Dropped Na-Ac out of DSMZ 120 media,1.0,0.059222,0.040306,0.013610,3.413268e-03,NaN,1234.989138,0.488125,0.025907,0.005913,0.477081,2.129103e-05,1.200000,0.300,0.000054,0.000295,0.013714,0.000013,4.000000,0.000042,0.000035,0.099527,0.000798,0.000798,NaN,724.186390,NaN,0.027727,0.027365,0.083942,0.817240,0.755987,0.036939,0.207075,0.000028,1.347668e-06,7.554913e-06,5.739773,6.131391,5.304874e-07,8.354559e-06,4.107741e-07,0.000036,2.059409,2.073412,2.084566,-1.084566,2.059409,1.660528,0.795222,1.028338,-0.028338,0.001097,2499.718310,175.366197,2344.070423,87.478873,21.805039,2.860747,7.023000,41.037000,-508.645000,34.388000,9.484185e-08,0.000932,6.349651,10.292986,0.004395,2.360459e-06,0.005330,0.111316
E34,90.9,DSMZ v2: Dropped Na-Ac out of DSMZ 120 media,1.0,0.059222,0.071624,0.018102,2.251129e-03,NaN,1389.354987,0.488125,0.008510,0.013771,0.475770,2.129103e-05,1.200000,0.300,0.000054,0.000295,0.013714,0.000013,4.000000,0.000013,0.000035,0.130845,0.000307,0.000307,NaN,343.357172,NaN,0.029437,0.022573,0.065969,0.934852,0.805937,0.053865,0.140199,0.000034,2.248013e-06,5.851116e-06,6.999624,7.477200,7.407089e-07,7.012263e-06,7.199523e-08,0.000040,2.511439,2.258250,2.553402,-1.553402,2.511439,1.935560,0.969769,1.159823,-0.159823,0.001097,1273.915493,95.788732,1070.521127,13.661972,10.000833,2.176022,7.047000,41.037000,-502.448000,35.962000,8.974288e-08,0.000932,6.342166,10.280281,0.004726,2.761769e-06,0.005661,0.088549
F34,104.9,"DSMZ v3: dropped yeast, casitone, and bicarb o...",1.0,0.059222,0.000000,0.000202,1.930381e-05,NaN,14.891589,0.370312,0.008139,0.000000,0.316970,1.493987e-05,1.000000,0.250,0.000045,0.000246,0.011429,0.000011,4.000000,0.000011,0.000026,0.059222,0.002661,0.002661,NaN,257.536549,4005.714286,0.016401,0.017713,0.043139,0.509447,0.908542,0.011945,0.079513,0.000021,2.716672e-07,1.808378e-06,4.300064,4.593452,2.903749e-07,2.554780e-06,2.322803e-07,0.000023,1.851416,1.945535,1.857502,-0.857502,1.851416,1.936316,0.791673,0.872083,0.127917,0.000914,1520.111111,110.888889,1310.666667,78.444444,25.534185,8.780074,6.969000,41.037000,-496.706000,36.422000,1.073989e-07,0.000932,6.339978,10.276568,0.003969,1.954736e-06,0.004903,0.060855
G12,125.9,Speece: put in Speece media + EDTA + cysteine ...,1.0,0.059222,0.018644,0.000131,2.931436e-05,NaN,11.469914,0.010905,0.009413,0.000000,0.035153,1.972551e-07,1.200000,0.300,0.000054,0.000295,0.013714,0.000013,4.000000,0.000013,0.000014,0.077866,0.000414,0.000414,NaN,33.548757,130.250000,0.008280,0.001838,0.011108,0.237228,0.953264,0.039489,0.007066,0.000010,4.182125e-07,7.483612e-08,2.100918,2.244262,2.356924e-07,8.237075e-07,3.136280e-07,0.000010,0.753802,1.368538,0.761608,0.238392,0.753802,1.368538,0.742861,0.765710,0.234290,0.001097,437.171429,121.971429,333.114286,90.642857,20.390606,3.656566,6.983000,24.635000,-498.385000,36.619000,1.039920e-07,0.000560,6.339041,10.274977,0.002466,1.258903e-06,0.003027,0.012947
H34,139.9,Wolfe v1: put in modified wolfe + EDTA,1.0,0.053483,0.032527,0.000611,2.150906e-05,NaN,40.855168,0.020750,0.018967,0.000073,0.020854,4.467830e-07,1.200000,0.300,0.000054,0.000295,0.013714,0.000013,4.000000,0.000013,0.000014,0.086011,0.000207,0.000207,NaN,15.916565,754.000000,0.009518,0.003420,0.027700,0.262430,0.982670,0.009917,0.007413,0.000012,1.161879e-07,8.684800e-08,2.395809,2.559272,0.000000e+00,2.356917e-06,1.556660e-07,0.000012,0.859607,1.013967,0.861776,0.138224,0.859607,1.013967,0.831857,0.838132,0.161868,0.001097,296.271429,47.785714,218.585714,36.600000,8.426770,3.310305,7.024455,39.428455,-503.308818,36.601091,9.453562e-08,0.000896,6.339127,10.275122,0.004330,2.424841e-06,0.005228,0.031122
I34,149.1,Wolfe v2: put in KILLER wolfe + EDTA + switch ...,1.0,0.053483,0.043154,0.001474,1.368551e-15,1.000000e-10,92.856137,0.013994,0.015972,0.000626,0.015456,3.847735e-07,0.600000,0.300,0.000027,0.000147,0.006857,0.000013,2.000000,0.000013,0.000014,0.096638,0.000230,0.000230,NaN,30.771788,258.400000,0.016025,0.000149,0.009506,0.351816,0.716158,0.240375,0.043468,0.000011,3.775343e-06,6.827066e-07,2.340752,2.500459,9.890849e-08,9.186575e-07,5.651073e-07,0.000012,1.679706,0.963561,1.820652,-0.820652,0.839853,0.913461,0.816398,0.873129,0.126871,0.000549,336.487500,150.550000,265.962500,121.062500,4.760796,2.946289,6.946000,8.914000,-519.811000,36.750000,1.132400e-07,0.000203,6.338419,10.273920,0.000821,3.856494e-07,0.001023,0.009656
J12,161.1,Wolfe v3: went back to modified wolfe + EDTA a...,1.0,0.059222,0.042525,0.001089,2.691276e-05,2.703467e+00,76.484166,0.011773,0.018837,0.000004,0.021145,4.034930e-07,1.200000,0.400,0.000054,0.000295,0.013714,0.000018,3.000000,0.000018,0.000018,0.101746,0.000128,0.000128,NaN,23.724205,279.818182,0.017458,0.006254,0.018868,0.293182,0.912006,0.051939,0.036056,0.000012,6.797972e-07,4.719132e-07,2.484076,3.202619,4.793815e-07,1.963856e-06,5.889675e-07,0.000013,0.891277,1.016219,0.903967,0.096033,0.668458,0.893051,0.653688,0.705783,0.294217,0.001097,450.521127,131.971831,357.915493,112.084507,4.775200,2.798350,6.949000,41.020000,-496.168000,36.159000,1.124605e-07,0.000932,6.341229,10.278691,0.003778,1.768213e-06,0.004712,0.025124
K12,181.9,Wolfe v3: went back to modified wolfe + EDTA a...,NaN,0.059222,0.044113,0.000943,1.368551e-15,1.000000e-10,59.380287,0.020030,0.015866,0.000000,0.019662,6.494302e-07,1.250000,0.337,0.000056,0.000307,0.014286,0.000015,3.709199,0.000015,0.000016,0.103335,0.000164,0.000164,NaN,31.171463,354.173913,0.017256,0.005630,0.023745,0.303513,0.919604,0.049340,0.031055,0.000012,6.685470e-07,4.207906e-07,2.593042,2.769962,4.963146e-07,1.771378e-06,2.698194e-07,0.000013,0.893159,0.889548,0.905139,0.094861,0.828226,0.843299,0.793953,0.852390,0.147610,0.001143,504.071429,120.857143,392.114286,83.271429,6.623430,2.755332,6.962000,41.034000,-495.116000,35.569000,1.091440e-07,0.000932,6.344035,10.283453,0.003869,1.845501e-06,0.004803,0.029377
L12,189.1,Wolfe v3: went back to modified wolfe + EDTA a...,NaN,0.059222,0.031534,0.001308,1.368551e-15,1.000000e-10,82.369556,0.013680,0.016066,0.000146,0.015957,6.494302e-07,1.331000,0.337,0.000059,0.000327,0.015211,0.000015,3.949555,0.000015,0.000016,0.090756,0.000120,0.000120,NaN,16.787406,277.937500,0.017273,0.002036,0.015809,0.303482,0.948323,0.035070,0.016607,0.000013,4.751437e-07,2.249923e-07,2.673746,2.856173,5.050680e-07,1.556972e-06,2.996437e-07,0.000014,0.864911,0.899564,0.872907,0.127093,0.854003,0.853365,0.818664,0.865182,0.134818,0.001217,242.128571,85.371429,174.585714,59.257143,6.970617,3.137229,7.035000,41.036000,-499.647000,36.619000,9.225714e-08,0.000932,6.339041,10.274977,0.004630,2.664432e-06,0.005565,0.017847
M12,209.9,Wolfe v3: went back to modified wolfe + EDTA a...,NaN,0.059222,0.023921,0.000898,4.763960e-06,1.000000e-10,57.082584,0.023345,0.016665,0.001270,0.018259,6.494302e-07,1.480000,0.379,0.000066,0.000363,0.016914,0.000017,3.905013,0.000017,0.000018,0.083142,0.000074,0.000074,NaN,6.052282,503.741935,0.015989,0.002338,0.013102,0.358940,0.946802,0.039671,0.013527,0.000015,6.356922e-07,2.167527e-07,3.157270,3.372686,4.758997e-07,8.925906e-07,2.213928e-07,0.000016,0.918500,0.886350,0.928121,0.071879,0.896689,0.868964,0.863543,0.902968,0.097032,0.001353,998.914286,88.871429,804.185714,66.042857,6.303042,3.424509,7.055000,41.031000,-505.618000,35.503000,8.810489e-08,0.000932,6.344349,10.283986,0.004789,2.826415e-06,0.005724,0.015441
N12,238.0,Wolfe v3: went back to modified wolfe + EDTA a...,NaN,0.059222,0.033133,0.001174,6.085343e-06,1.000000e-10,74.630767,0.020585,0.016195,0.000075,0.017718,6.494302e-07,1.583000,0.397,0.000071,0.000389,0.018091,0.000018,3.987406,0.000018,0.000018,0.092355,0.000051,0.000051,NaN,5.659541,552.129032,0.017044,0.002584,0.014787,0.383665,0.951829,0.043160,0.005011,0.000016,7.392346e-07,8.582793e-08,3.392673,3.432838,8.989544e-07,1.494425e-06,1.188528e-06,0.000017,0.922763,0.890604,0.933224,0.066776,0.919858,0.882735,0.887343,0.940943,0.059057,0.001447,443.246377,271.318841,360.985507,230.579710,5.061742,3.082907,7.030000,72.335000,-500.210000,36.816000,9.332543e-08,0.001644,6.338105,10.273387,0.008085,4.616525e-06,0.009734,0.017373
P12,283.1,Wolfe v3: went back to modified wolfe + EDTA a...,NaN,0.059222,0.026911,0.000034,4.910360e-06,4.740000e-01,3.546537,0.023844,0.016348,0.001611,0.013381,6.494302e-07,2.775000,0.701,0.000124,0.000681,0.031714,0.000031,3.958631,0.000031,0.000032,0.086132,0.000051,0.000051,NaN,4.727244,542.600000,0.015220,0.001592,0.012646,0.724067,0.888664,0.110011,0.001325,0.000029,3.556040e-06,4.284061e-08,5.977874,6.385737,9.771744e-07,1.133029e-06,4.673642e-07,0.000030,0.927498,0.906312,0.956203,0.043797,0.917905,0.897361,0.899244,0.931176,0.068824,0.002537,292.690141,135.197183,229.056338,102.084507,7.272311,3.305635,6.951000,98.011000,-495.217000,36.619000,1.119438e-07,0.002227,6.339041,10.274977,0.009114,4.322296e-06,0.011345,0.014239
Q,300.0,Wolfe v3: went back to modified wolfe + EDTA a...,NaN,0.059222,0.046536,0.000133,2.294375e-05,1.949500e+00,14.463519,0.027502,0.016817,NaN,0.016068,6.494302e-07,2.770000,0.701,0.000124,0.000680,0.031657,0.000031,3.951498,0.000031,0.000032,0.105758,0.000091,0.000091,NaN,12.391541,711.032258,0.015521,NaN,0.016659,0.689144,0.929637,0.038145,0.032219,0.000029,1.173534e-06,9.912387e-07,5.951875,5.738007,1.332043e-06,1.765388e-06,9.493365e-07,0.000031,0.925131,0.904294,0.934621,0.065379,0.913913,0.891389,0.895333,0.968063,0.031937,0.002533,480.928571,233.800000,389.828571,179.042857,4.651421,2.692210,6.991000,102.531000,-498.215000,34.913000,1.020939e-07,0.002330,6.347154,10.288749,0.010260,5.169049e-06,0.012595,NaN

In [5]:
data_df

{'10AB': {'Days of Operation': 0.0,
  'Media description': 'DSMZ v1: Using DSMZ 120 without NaHCO3',
  'Media changes': 1.0,
  'Media Influent Flow Rate (mL/min) based on scales linear projection': 0.0592216175,
  'pH adjustment delivery rate (mL/min) - primarily 1 M HCl, sometimes 1 M NaOH': 0.0,
  'cpd00029_in': 0.0354271680216802,
  'cpd00141_in': 0.0022489849915606,
  'cpd00211_in': nan,
  'Media Total VFA (mg COD/L)': 2480.559206666667,
  'Media Total COD (mg/L) Hach': 0.5482945644886017,
  'Media Ammonia (mol/L)': nan,
  'Media Dissolved Inorganic Carbon (mol C/L)': nan,
  'Media Dissolved Organic Carbon (mol C/L)': nan,
  'media_carbon_in': 2.6705660146199203e-05,
  'H2 delivery rate setpoint (mL/min)': 1.0915248032216731,
  'CO2 delivery rate setpoint (mL/min)': 0.25,
  'H2 delivery rate (mol/min)': 4.872878585811041e-05,
  'H2 delivery rate (e-eq/min)': 0.0002680083222196,
  'H2 delivery (g COD/min)': 0.0124745691796762,
  'CO2 delivery rate (mol/min)': 1.1160714285714286e-05,
  'H2:CO2 ratio': 4.3660992128866924,
  'carbon_in': 1.1160714285714286e-05,
  'Approximate Total Influent C (mol/min) based on Media recipe + gas': 3.786637443191349e-05,
  'Effluent waste flow rate (mL/min) - measured based on HRT after Day 38.1': 0.0592216175,
  'cpd00029_out': 0.0355636856368563,
  'cpd00141_out': 0.0355636856368563,
  'cpd00211_out': nan,
  'Waste Effluent Total VFA (mg COD/L)': 2446.060693333333,
  'Waste Effluent Total COD (mg/L) Hach': nan,
  'Waste Effluent Ammonia (mol/L)': nan,
  'Waste Effluent Dissolved Inorganic Carbon (mol C/L)': 0.0354169990878835,
  'Waste Effluent Dissolved Organic Carbon (mol C/L)': 0.4687478609344043,
  'Gas Flow Out (mL/min at STP)': 1.027461111051305,
  '%cpd01024': 0.0,
  '%cpd11640': 0.8758853333333333,
  '%cpd00011': 0.1241146666666666,
  'CH4 Production (mol/min)': 0.0,
  'cpd11640_out': 4.017580882768791e-05,
  'cpd00011_out': 5.692990772816772e-06,
  'Specific CH4 production Rate (m3/m3d) .155': 0.0,
  'Specific CH4 production Rate (L/m2d)': 0.0,
  'Waste Effluent Dissolved Inorganic Carbon (mol/min) based on sensor': 2.444631971134612e-07,
  'Effluent C as measured (mol/min)': 2.776000652420049e-05,
  'Effluent C as biomass (mol/min)': nan,
  'Total Effluent C (mol/min) based on MT sensors': 5.937453969930233e-06,
  'H2 Conversion to CH4 Efficiency (%)': 0.0,
  'H2 conversion to CH4 efficiency (30-day rolling average)': nan,
  'Accounted H2 (%)': 0.824477936812806,
  'Unaccounted H2 (%)': 0.175522063187194,
  'C gas only Conversion Efficiency to CH4 (%)': 0.0,
  'CO2 conversion to CH4 efficiency (30-day rolling average)': nan,
  'C Conversion to CH4 Efficiency (%)': 0.0,
  'accounted_C': 0.1568001705736632,
  'Unaccounted C (%) based on MT sensors': 0.8431998294263368,
  'Projected Cell Yield (g/min)': 0.0009979655343741,
  'R-TSS': nan,
  'W-TSS': nan,
  'R-VSS': nan,
  'W-VSS': nan,
  'SRT': nan,
  'HRT': nan,
  'pH': 6.902,
  'CO2 (mg/L, aqueous dissolved CO2)': 41.05,
  'ORP (mV)': -305.292,
  'Temp ©': 30.647,
  '[H]': 1.2531411749414145e-07,
  '[CO2aq]': 0.0009327637528687,
  'pKa1': 6.367441674074073,
  'pKa2': 10.323184679629628,
  '[HCO3-]': 0.003193963781083,
  '[CO3-2]': 1.2110032464186114e-06,
  'TIC': 0.0041279385371981,
  'carbon_out': 0.5041926200288119},
 'A34': {'Days of Operation': 21.5,
  'Media description': 'DSMZ v1.5: Using DSMZ 120 with NaHCO3',
  'Media changes': 1.0,
  'Media Influent Flow Rate (mL/min) based on scales linear projection': 0.0592216175,
  'pH adjustment delivery rate (mL/min) - primarily 1 M HCl, sometimes 1 M NaOH': 0.0,
  'cpd00029_in': 0.0287776266905861,
  'cpd00141_in': 0.002748583100262,
  'cpd00211_in': nan,
  'Media Total VFA (mg COD/L)': 2116.9363584037555,
  'Media Total COD (mg/L) Hach': 0.5482945644886017,
  'Media Ammonia (mol/L)': nan,
  'Media Dissolved Inorganic Carbon (mol C/L)': 0.0519639129903411,
  'Media Dissolved Organic Carbon (mol C/L)': 0.4102378796138061,
  'media_carbon_in': 2.8115530835320275e-05,
  'H2 delivery rate setpoint (mL/min)': 0.5457624016108366,
  'CO2 delivery rate setpoint (mL/min)': 0.25,
  'H2 delivery rate (mol/min)': 2.4364392929055205e-05,
  'H2 delivery rate (e-eq/min)': 0.0001340041611098,
  'H2 delivery (g COD/min)': 0.0062372845898381,
  'CO2 delivery rate (mol/min)': 1.1160714285714286e-05,
  'H2:CO2 ratio': 2.1830496064433462,
  'carbon_in': 1.1160714285714286e-05,
  'Approximate Total Influent C (mol/min) based on Media recipe + gas': 3.927624512103456e-05,
  'Effluent waste flow rate (mL/min) - measured based on HRT after Day 38.1': 0.0592216175,
  'cpd00029_out': 0.0269917907938203,
  'cpd00141_out': 0.0269917907938203,
  'cpd00211_out': nan,
  'Waste Effluent Total VFA (mg COD/L)': 1794.152069002546,
  'Waste Effluent Total COD (mg/L) Hach': nan,
  'Waste Effluent Ammonia (mol/L)': nan,
  'Waste Effluent Dissolved Inorganic Carbon (mol C/L)': 0.0007997889837332,
  'Waste Effluent Dissolved Organic Carbon (mol C/L)': 0.0309541390457628,
  'Gas Flow Out (mL/min at STP)': 0.5075506548787121,
  '%cpd01024': 0.4049563333333333,
  '%cpd11640': 0.587181,
  '%cpd00011': 0.0078633333333333,
  'CH4 Production (mol/min)': 9.175707686634614e-06,
  'cpd11640_out': 1.3304647369747188e-05,
  'cpd00011_out': 1.7817142780638124e-07,
  'Specific CH4 production Rate (m3/m3d) .155': 1.9094943686457173,
  'Specific CH4 production Rate (L/m2d)': 2.039776892764205,
  'Waste Effluent Dissolved Inorganic Carbon (mol/min) based on sensor': 3.321555679862964e-07,
  'Effluent C as measured (mol/min)': 1.8331541826099869e-06,
  'Effluent C as biomass (mol/min)': nan,
  'Total Effluent C (mol/min) based on MT sensors': 9.686034682427291e-06,
  'H2 Conversion to CH4 Efficiency (%)': 1.5064126922189522,
  'H2 conversion to CH4 efficiency (30-day rolling average)': nan,
  'Accounted H2 (%)': 2.052482007735574,
  'Unaccounted H2 (%)': -1.052482007735574,
  'C gas only Conversion Efficiency to CH4 (%)': 0.8221434087224614,
  'CO2 conversion to CH4 efficiency (30-day rolling average)': nan,
  'C Conversion to CH4 Efficiency (%)': 0.2336197785291986,
  'accounted_C': 0.2466130520516558,
  'Unaccounted C (%) based on MT sensors': 0.7533869479483442,
  'Projected Cell Yield (g/min)': 0.000498982767187,
  'R-TSS': nan,
  'W-TSS': nan,
  'R-VSS': nan,
  'W-VSS': nan,
  'SRT': nan,
  'HRT': nan,
  'pH': 7.04,
  'CO2 (mg/L, aqueous dissolved CO2)': 41.036,
  'ORP (mV)': -519.691,
  'Temp ©': 36.422,
  '[H]': 9.120108393559096e-08,
  '[CO2aq]': 0.0009324456361198,
  'pKa1': 6.33997834074074,
  'pKa2': 10.276567596296296,
  '[HCO3-]': 0.0046735315626451,
  '[CO3-2]': 2.7106758323604203e-06,
  'TIC': 0.0056086878745974,
  'carbon_out': 0.03175576118367861},
 'B34': {'Days of Operation': 34.9,
  'Media description': 'DSMZ v1.5: Using DSMZ 120 with NaHCO3',
  'Media changes': 1.0,
  'Media Influent Flow Rate (mL/min) based on scales linear projection': 2.0790472319,
  'pH adjustment delivery rate (mL/min) - primarily 1 M HCl, sometimes 1 M NaOH': 0.0,
  'cpd00029_in': 0.0183549622600098,
  'cpd00141_in': 0.0034333525444441,
  'cpd00211_in': nan,
  'Media Total VFA (mg COD/L)': 1536.1081855633802,
  'Media Total COD (mg/L) Hach': 0.5482945644886017,
  'Media Ammonia (mol/L)': nan,
  'Media Dissolved Inorganic Carbon (mol C/L)': 0.0400550617528344,
  'Media Dissolved Organic Carbon (mol C/L)': 0.3529959262580938,
  'media_carbon_in': 2.8115530835320275e-05,
  'H2 delivery rate setpoint (mL/min)': 1.0915248032216731,
  'CO2 delivery rate setpoint (mL/min)': 0.25,
  'H2 delivery rate (mol/min)': 4.872878585811041e-05,
  'H2 delivery rate (e-eq/min)': 0.0002680083222196,
  'H2 delivery (g COD/min)': 0.0124745691796762,
  'CO2 delivery rate (mol/min)': 1.1160714285714286e-05,
  'H2:CO2 ratio': 4.3660992128866924,
  'carbon_in': 1.1160714285714286e-05,
  'Approximate Total Influent C (mol/min) based on Media recipe + gas': 3.927624512103456e-05,
  'Effluent waste flow rate (mL/min) - measured based on HRT after Day 38.1': 2.0790472319,
  'cpd00029_out': 0.0149064138132256,
  'cpd00141_out': 0.0149064138132256,
  'cpd00211_out': nan,
  'Waste Effluent Total VFA (mg COD/L)': 1212.3584476642725,
  'Waste Effluent Total COD (mg/L) Hach': nan,
  'Waste Effluent Ammonia (mol/L)': nan,
  'Waste Effluent Dissolved Inorganic Carbon (mol C/L)': 0.0023308136097369,
  'Waste Effluent Dissolved Organic Carbon (mol C/L)': 0.0578773518234808,
  'Gas Flow Out (mL/min at STP)': 0.5522805951970167,
  '%cpd01024': 0.2709499999999999,
  '%cpd11640': 0.722636,
  '%cpd00011': 0.0064139999999999,
  'CH4 Production (mol/min)': 6.680376217349626e-06,
  'cpd11640_out': 1.7816867865660325e-05,
  'cpd00011_out': 1.581396311425743e-07,
  'Specific CH4 production Rate (m3/m3d) .155': 1.3902078404311586,
  'Specific CH4 production Rate (L/m2d)': 1.4850600638651246,
  'Waste Effluent Dissolved Inorganic Carbon (mol/min) based on sensor': 4.810819712499789e-07,
  'Effluent C as measured (mol/min)': 3.4275903916031133e-06,
  'Effluent C as biomass (mol/min)': nan,
  'Total Effluent C (mol/min) based on MT sensors': 7.31959781974218e-06,
  'H2 Conversion to CH4 Efficiency (%)': 0.5483720638393658,
  'H2 conversion to CH4 efficiency (30-day rolling average)': 1.4138487840094751,
  'Accounted H2 (%)': 0.9140053861540216,
  'Unaccounted H2 (%)': 0.0859946138459785,
  'C gas only Conversion Efficiency to CH4 (%)': 0.5985617090745265,
  'CO2 conversion to CH4 efficiency (30-day rolling average)': 0.6692968559840901,
  'C Conversion to CH4 Efficiency (%)': 0.170086936690695,
  'accounted_C': 0.1863619548453764,
  'Unaccounted C (%) based on MT sensors': 0.8136380451546236,
  'Projected Cell Yield (g/min)': 0.0009979655343741,
  'R-TSS': nan,
  'W-TSS': nan,
  'R-VSS': nan,
  'W-VSS': nan,
  'SRT': nan,
  'HRT': nan,
  'pH': 7.044,
  'CO2 (mg/L, aqueous dissolved CO2)': 1.675,
  'ORP (mV)': -520.272,
  'Temp ©': 36.75,
  '[H]': 9.03649473722302e-08,
  '[CO2aq]': 3.806039673703106e-05,
  'pKa1': 6.338418518518518,
  'pKa2': 10.273919907407407,
  '[HCO3-]': 0.000193221207796,
  '[CO3-2]': 1.1379806699638713e-07,
  'TIC': 0.0002313954026,
  'carbon_out': 0.0602115930236093},
 'C3': {'Days of Operation': 68.5,
  'Media description': 'DSMZ v2: Dropped Na-Ac out of DSMZ 120 media',
  'Media changes': 1.0,
  'Media Influent Flow Rate (mL/min) based on scales linear projection': 0.0592216175,
  'pH adjustment delivery rate (mL/min) - primarily 1 M HCl, sometimes 1 M NaOH': 0.0,
  'cpd00029_in': 0.0160162940379402,
  'cpd00141_in': 0.0028047488709456,
  'cpd00211_in': nan,
  'Media Total VFA (mg COD/L)': 1319.241036,
  'Media Total COD (mg/L) Hach': 0.488125,
  'Media Ammonia (mol/L)': 0.0259072225484439,
  'Media Dissolved Inorganic Carbon (mol C/L)': 0.0206764647728977,
  'Media Dissolved Organic Carbon (mol C/L)': 0.4275322017964478,
  'media_carbon_in': 2.1291029790152428e-05,
  'H2 delivery rate setpoint (mL/min)': 0.988,
  'CO2 delivery rate setpoint (mL/min)': 0.344,
  'H2 delivery rate (mol/min)': 4.410714285714286e-05,
  'H2 delivery rate (e-eq/min)': 0.0002425892857142,
  'H2 delivery (g COD/min)': 0.0112914285714285,
  'CO2 delivery rate (mol/min)': 1.5357142857142855e-05,
  'H2:CO2 ratio': 2.872093023255814,
  'carbon_in': 1.5357142857142855e-05,
  'Approximate Total Influent C (mol/min) based on Media recipe + gas': 3.664817264729528e-05,
  'Effluent waste flow rate (mL/min) - measured based on HRT after Day 38.1': 0.0592216175,
  'cpd00029_out': 0.0007915869599871,
  'cpd00141_out': 0.0007915869599871,
  'cpd00211_out': nan,
  'Waste Effluent Total VFA (mg COD/L)': 778.9875847058823,
  'Waste Effluent Total COD (mg/L) Hach': nan,
  'Waste Effluent Ammonia (mol/L)': 0.0190816206694068,
  'Waste Effluent Dissolved Inorganic Carbon (mol C/L)': 0.0163263794445784,
  'Waste Effluent Dissolved Organic Carbon (mol C/L)': 0.0319680284400371,
  'Gas Flow Out (mL/min at STP)': 0.8488182513554042,
  '%cpd01024': 0.7750533183227921,
  '%cpd11640': 0.003683388715973,
  '%cpd00011': 0.221264232960907,
  'CH4 Production (mol/min)': 2.93696161770516e-05,
  'cpd11640_out': 1.3957712361403798e-07,
  'cpd00011_out': 8.384514254882672e-06,
  'Specific CH4 production Rate (m3/m3d) .155': 6.111911867141784,
  'Specific CH4 production Rate (L/m2d)': 6.528920326719343,
  'Waste Effluent Dissolved Inorganic Carbon (mol/min) based on sensor': 3.3476809521220176e-07,
  'Effluent C as measured (mol/min)': 1.922889999154512e-06,
  'Effluent C as biomass (mol/min)': 4.594951599511141e-07,
  'Total Effluent C (mol/min) based on MT sensors': 3.808889852714648e-05,
  'H2 Conversion to CH4 Efficiency (%)': 2.6634793618054893,
  'H2 conversion to CH4 efficiency (30-day rolling average)': 1.775950748523209,
  'Accounted H2 (%)': 2.6666438633935,
  'Unaccounted H2 (%)': -1.6666438633935,
  'C gas only Conversion Efficiency to CH4 (%)': 1.9124401231568489,
  'CO2 conversion to CH4 efficiency (30-day rolling average)': 1.510110219642912,
  'C Conversion to CH4 Efficiency (%)': 0.8013937409569354,
  'accounted_C': 1.039312352452518,
  'Unaccounted C (%) based on MT sensors': -0.0393123524525178,
  'Projected Cell Yield (g/min)': 0.0009033142857142,
  'R-TSS': 382.5571428571429,
  'W-TSS': 216.0857142857143,
  'R-VSS': 298.01428571428573,
  'W-VSS': 153.97142857142856,
  'SRT': 5.7498878705738665,
  'HRT': 5.382529650437885,
  'pH': 7.045,
  'CO2 (mg/L, aqueous dissolved CO2)': 41.037,
  'ORP (mV)': -513.338,
  'Temp ©': 36.225,
  '[H]': 9.015711376059569e-08,
  '[CO2aq]': 0.0009324683587448,
  'pKa1': 6.340915185185184,
  'pKa2': 10.278157824074071,
  '[HCO3-]': 0.0047175761450964,
  '[CO3-2]': 2.757789378800108e-06,
  'TIC': 0.00565280229322,
  'carbon_out': 0.048296330774614656},
 'D34': {'Days of Operation': 82.5,
  'Media description': 'DSMZ v2: Dropped Na-Ac out of DSMZ 120 media',
  'Media changes': 1.0,
  'Media Influent Flow Rate (mL/min) based on scales linear projection': 0.0592216175,
  'pH adjustment delivery rate (mL/min) - primarily 1 M HCl, sometimes 1 M NaOH': 0.0403056158300799,
  'cpd00029_in': 0.0136102377625338,
  'cpd00141_in': 0.003413268099083,
  'cpd00211_in': nan,
  'Media Total VFA (mg COD/L)': 1234.9891378125,
  'Media Total COD (mg/L) Hach': 0.488125,
  'Media Ammonia (mol/L)': 0.0259072225484439,
  'Media Dissolved Inorganic Carbon (mol C/L)': 0.0059134822031471,
  'Media Dissolved Organic Carbon (mol C/L)': 0.4770806908133806,
  'media_carbon_in': 2.1291029790152428e-05,
  'H2 delivery rate setpoint (mL/min)': 1.2,
  'CO2 delivery rate setpoint (mL/min)': 0.3,
  'H2 delivery rate (mol/min)': 5.357142857142857e-05,
  'H2 delivery rate (e-eq/min)': 0.0002946428571428,
  'H2 delivery (g COD/min)': 0.0137142857142857,
  'CO2 delivery rate (mol/min)': 1.3392857142857142e-05,
  'H2:CO2 ratio': 4.0,
  'carbon_in': 4.164634733084293e-05,
  'Approximate Total Influent C (mol/min) based on Media recipe + gas': 3.468388693300957e-05,
  'Effluent waste flow rate (mL/min) - measured based on HRT after Day 38.1': 0.0995272333300799,
  'cpd00029_out': 0.0007984851113754,
  'cpd00141_out': 0.0007984851113754,
  'cpd00211_out': nan,
  'Waste Effluent Total VFA (mg COD/L)': 724.1863898780489,
  'Waste Effluent Total COD (mg/L) Hach': nan,
  'Waste Effluent Ammonia (mol/L)': 0.0277271481698962,
  'Waste Effluent Dissolved Inorganic Carbon (mol C/L)': 0.0273647017416292,
  'Waste Effluent Dissolved Organic Carbon (mol C/L)': 0.0839424442933829,
  'Gas Flow Out (mL/min at STP)': 0.8172403486690635,
  '%cpd01024': 0.7559866666666666,
  '%cpd11640': 0.0369386666666666,
  '%cpd00011': 0.207075,
  'CH4 Production (mol/min)': 2.75813753149924e-05,
  'cpd11640_out': 1.3476682511623654e-06,
  'cpd00011_out': 7.554912732171711e-06,
  'Specific CH4 production Rate (m3/m3d) .155': 5.739773175228352,
  'Specific CH4 production Rate (L/m2d)': 6.131391055550618,
  'Waste Effluent Dissolved Inorganic Carbon (mol/min) based on sensor': 5.304873742311574e-07,
  'Effluent C as measured (mol/min)': 8.354559239484763e-06,
  'Effluent C as biomass (mol/min)': 4.1077414684514594e-07,
  'Total Effluent C (mol/min) based on MT sensors': 3.5666775421395266e-05,
  'H2 Conversion to CH4 Efficiency (%)': 2.059409356852766,
  'H2 conversion to CH4 efficiency (30-day rolling average)': 2.07341231286011,
  'Accounted H2 (%)': 2.0845658308744635,
  'Unaccounted H2 (%)': -1.0845658308744637,
  'C gas only Conversion Efficiency to CH4 (%)': 2.059409356852766,
  'CO2 conversion to CH4 efficiency (30-day rolling average)': 1.660528492612951,
  'C Conversion to CH4 Efficiency (%)': 0.7952215784887268,
  'accounted_C': 1.028338475739011,
  'Unaccounted C (%) based on MT sensors': -0.028338475739011,
  'Projected Cell Yield (g/min)': 0.0010971428571428,
  'R-TSS': 2499.718309859155,
  'W-TSS': 175.3661971830986,
  'R-VSS': 2344.0704225352115,
  'W-VSS': 87.47887323943661,
  'SRT': 21.80503939094516,
  'HRT': 2.860746879981554,
  'pH': 7.023,
  'CO2 (mg/L, aqueous dissolved CO2)': 41.037,
  'ORP (mV)': -508.645,
  'Temp ©': 34.388,
  '[H]': 9.484184633008949e-08,
  '[CO2aq]': 0.0009324683587448,
  'pKa1': 6.3496511407407406,
  'pKa2': 10.292986496296296,
  '[HCO3-]': 0.0043952437310301,
  '[CO3-2]': 2.360459029979337e-06,
  'TIC': 0.0053300725488048,
  'carbon_out': 0.11131550059425159},
 'E34': {'Days of Operation': 90.9,
  'Media description': 'DSMZ v2: Dropped Na-Ac out of DSMZ 120 media',
  'Media changes': 1.0,
  'Media Influent Flow Rate (mL/min) based on scales linear projection': 0.0592216175,
  'pH adjustment delivery rate (mL/min) - primarily 1 M HCl, sometimes 1 M NaOH': 0.0716236617882009,
  'cpd00029_in': 0.0181015130984642,
  'cpd00141_in': 0.0022511290543314,
  'cpd00211_in': nan,
  'Media Total VFA (mg COD/L)': 1389.3549866666665,
  'Media Total COD (mg/L) Hach': 0.488125,
  'Media Ammonia (mol/L)': 0.0085096887844979,
  'Media Dissolved Inorganic Carbon (mol C/L)': 0.0137705174951625,
  'Media Dissolved Organic Carbon (mol C/L)': 0.4757696354615245,
  'media_carbon_in': 2.1291029790152428e-05,
  'H2 delivery rate setpoint (mL/min)': 1.2,
  'CO2 delivery rate setpoint (mL/min)': 0.3,
  'H2 delivery rate (mol/min)': 5.357142857142857e-05,
  'H2 delivery rate (e-eq/min)': 0.0002946428571428,
  'H2 delivery (g COD/min)': 0.0137142857142857,
  'CO2 delivery rate (mol/min)': 1.3392857142857142e-05,
  'H2:CO2 ratio': 4.0,
  'carbon_in': 1.3392857142857142e-05,
  'Approximate Total Influent C (mol/min) based on Media recipe + gas': 3.468388693300957e-05,
  'Effluent waste flow rate (mL/min) - measured based on HRT after Day 38.1': 0.1308452792882009,
  'cpd00029_out': 0.0003072210930442,
  'cpd00141_out': 0.0003072210930442,
  'cpd00211_out': nan,
  'Waste Effluent Total VFA (mg COD/L)': 343.3571716666667,
  'Waste Effluent Total COD (mg/L) Hach': nan,
  'Waste Effluent Ammonia (mol/L)': 0.0294371277577384,
  'Waste Effluent Dissolved Inorganic Carbon (mol C/L)': 0.0225733565821271,
  'Waste Effluent Dissolved Organic Carbon (mol C/L)': 0.0659685606832525,
  'Gas Flow Out (mL/min at STP)': 0.9348519628354282,
  '%cpd01024': 0.805937,
  '%cpd11640': 0.0538646666666666,
  '%cpd00011': 0.1401986666666666,
  'CH4 Production (mol/min)': 3.363534760587931e-05,
  'cpd11640_out': 2.2480129178932768e-06,
  'cpd00011_out': 5.851116014296573e-06,
  'Specific CH4 production Rate (m3/m3d) .155': 6.999624337904793,
  'Specific CH4 production Rate (L/m2d)': 7.477200360959634,
  'Waste Effluent Dissolved Inorganic Carbon (mol/min) based on sensor': 7.407089160417432e-07,
  'Effluent C as measured (mol/min)': 7.012262506106897e-06,
  'Effluent C as biomass (mol/min)': 7.199522815829334e-08,
  'Total Effluent C (mol/min) based on MT sensors': 4.0227172536217626e-05,
  'H2 Conversion to CH4 Efficiency (%)': 2.511439287905655,
  'H2 conversion to CH4 efficiency (30-day rolling average)': 2.2582499798922826,
  'Accounted H2 (%)': 2.55340219570633,
  'Unaccounted H2 (%)': -1.55340219570633,
  'C gas only Conversion Efficiency to CH4 (%)': 2.511439287905655,
  'CO2 conversion to CH4 efficiency (30-day rolling average)': 1.9355598931369409,

### loading the media

In [6]:
# import os
# # os.environ["HOME"] = "~/repos/cobrakbase"
# import cobrakbase

# with open("/home/afreiburger/.kbase/token", 'r') as token:
#     kbase_obj = cobrakbase.KBaseAPI(token.readline())

# media_ws = 207617
# media = kbase_obj.get_from_ws("Wolfe",207617)
# from modelseedpy.core.fbahelper import FBAHelper
# from json import dump
# media_js = FBAHelper.convert_kbase_media(media)

# dump(media_js, open("model_inputs/Wolfe.json", 'w'), indent=2)

from json import load
media = load(open("model_inputs/Wolfe.json", 'r'))

###

### Adding the media and element constraints

In [14]:
%%time
from mscommunity import MSCommunity
from tqdm import tqdm

models = load_models()
for ID, model in tqdm(models.items()):
    sample = ID.split("_")[0]
    models[ID] = MSCommunity(model) #, climit=data_df[sample]["carbon_in"]*1000, o2limit=0)
    display(models[ID].util.model.summary())
    models[ID].util.add_medium = media

  0%|          | 0/1 [00:00<?, ?it/s]

loading P12_comm

100%|██████████| 1/1 [01:38<00:00, 98.19s/it]
  0%|          | 0/1 [00:00<?, ?it/s]

Read LP format model from file /tmp/tmp1joddpzd.lp
Reading time = 0.25 seconds
: 38032 rows, 82598 columns, 389014 nonzeros
Neither carbon consumption nor oxygen consumption are defined in P12_comm
Species0 biomass compound: cpd11416_c22
skipping atp hydrolysis rxn00062_c22 for Species0
Making biomass drain reaction for species: Species0
Species1 biomass compound: cpd11416_c24
skipping atp hydrolysis rxn00062_c24 for Species1
Making biomass drain reaction for species: Species1
Species2 biomass compound: cpd11416_c9
skipping atp hydrolysis rxn00062_c9 for Species2
Making biomass drain reaction for species: Species2
Species3 biomass compound: cpd11416_c28
skipping atp hydrolysis rxn00062_c28 for Species3
Making biomass drain reaction for species: Species3
Species4 biomass compound: cpd11416_c7
skipping atp hydrolysis rxn00062_c7 for Species4
Making biomass drain reaction for species: Species4
Species5 biomass compound: cpd11416_c11
skipping atp hydrolysis rxn00062_c11 for Species5
Making biomass drain reaction for species: Species5
Species6 biomass compound: cpd11416_c12
skipping atp hydrolysis rxn00062_c12 for Species6
Making biomass drain reaction for species: Species6
Species7 biomass compound: cpd11416_c8
skipping atp hydrolysis rxn00062_c8 for Species7
Making biomass drain reaction for species: Species7
Species8 biomass compound: cpd11416_c32
skipping atp hydrolysis rxn00062_c32 for Species8
Making biomass drain reaction for species: Species8
Species9 biomass compound: cpd11416_c31
skipping atp hydrolysis rxn00062_c31 for Species9
Making biomass drain reaction for species: Species9
Species10 biomass compound: cpd11416_c14
skipping atp hydrolysis rxn00062_c14 for Species10
Making biomass drain reaction for species: Species10
Species11 biomass compound: cpd11416_c25
skipping atp hydrolysis rxn00062_c25 for Species11
Making biomass drain reaction for species: Species11
Species12 biomass compound: cpd11416_c18
skipping atp hydrolysis rxn00062_c18 for Species12
Making biomass drain reaction for species: Species12
Species13 biomass compound: cpd11416_c36
skipping atp hydrolysis rxn00062_c36 for Species13
Making biomass drain reaction for species: Species13
Species14 biomass compound: cpd11416_c35
skipping atp hydrolysis rxn00062_c35 for Species14
Making biomass drain reaction for species: Species14
Species15 biomass compound: cpd11416_c33
skipping atp hydrolysis rxn00062_c33 for Species15
Making biomass drain reaction for species: Species15
Species16 biomass compound: cpd11416_c1
skipping atp hydrolysis rxn00062_c1 for Species16
Making biomass drain reaction for species: Species16
Species17 biomass compound: cpd11416_c34
skipping atp hydrolysis rxn00062_c34 for Species17
Making biomass drain reaction for species: Species17
Species18 biomass compound: cpd11416_c2
skipping atp hydrolysis rxn00062_c2 for Species18
Making biomass drain reaction for species: Species18
Species19 biomass compound: cpd11416_c21
skipping atp hydrolysis rxn00062_c21 for Species19
Making biomass drain reaction for species: Species19
Species20 biomass compound: cpd11416_c17
skipping atp hydrolysis rxn00062_c17 for Species20
Making biomass drain reaction for species: Species20
Species21 biomass compound: cpd11416_c30
skipping atp hydrolysis rxn00062_c30 for Species21
Making biomass drain reaction for species: Species21
Species22 biomass compound: cpd11416_c23
skipping atp hydrolysis rxn00062_c23 for Species22
Making biomass drain reaction for species: Species22
Species23 biomass compound: cpd11416_c19
skipping atp hydrolysis rxn00062_c19 for Species23
Making biomass drain reaction for species: Species23
Species24 biomass compound: cpd11416_c13
skipping atp hydrolysis rxn00062_c13 for Species24
Making biomass drain reaction for species: Species24
Species25 biomass compound: cpd11416_c3
skipping atp hydrolysis rxn00062_c3 for Species25
Making biomass drain reaction for species: Species25
Species26 biomass compound: cpd11416_c10
skipping atp hydrolysis rxn00062_c10 for Species26
Making biomass drain reaction for species: Species26
Species27 biomass compound: cpd11416_c15
skipping atp hydrolysis rxn00062_c15 for Species27
Making biomass drain reaction for species: Species27
Species28 biomass compound: cpd11416_c6
skipping atp hydrolysis rxn00062_c6 for Species28
Making biomass drain reaction for species: Species28
Species29 biomass compound: cpd11416_c5
skipping atp hydrolysis rxn00062_c5 for Species29
Making biomass drain reaction for species: Species29
Species30 biomass compound: cpd11416_c29
skipping atp hydrolysis rxn00062_c29 for Species30
Making biomass drain reaction for species: Species30
Species31 biomass compound: cpd11416_c20
skipping atp hydrolysis rxn00062_c20 for Species31
Making biomass drain reaction for species: Species31
Species32 biomass compound: cpd11416_c27
skipping atp hydrolysis rxn00062_c27 for Species32
Making biomass drain reaction for species: Species32
Species33 biomass compound: cpd11416_c4
skipping atp hydrolysis rxn00062_c4 for Species33
Making biomass drain reaction for species: Species33
Species34 biomass compound: cpd11416_c26
skipping atp hydrolysis rxn00062_c26 for Species34
Making biomass drain reaction for species: Species34
Species35 biomass compound: cpd11416_c16
skipping atp hydrolysis rxn00062_c16 for Species35
Making biomass drain reaction for species: Species35
Neither carbon consumption nor oxygen consumption are defined in P12_comm

100%|██████████| 1/1 [05:58<00:00, 358.57s/it]

CPU times: user 7min 31s, sys: 6.82 s, total: 7min 37s
Wall time: 7min 36s

In [13]:
%%time
# Without Carbon and Oxygen constraints
display(models[ID].util.model.summary())

CPU times: user 58 s, sys: 294 ms, total: 58.3 s
Wall time: 58.2 s

In [10]:
%%time
# With Carbon and Oxygen constraints
display(models[ID].util.model.summary())

CPU times: user 1min 2s, sys: 217 ms, total: 1min 2s
Wall time: 1min 2s

## Objective

In [8]:
%%time
for ID, model in models.items():
    print(ID)
    print(model.util.model.objective.expression)
    print(model.run_fba())

P12_comm
1.0*bio1 - 1.0*bio1_reverse_b18f7
<Solution 0.000 at 0x7fa586236980>
CPU times: user 3min 16s, sys: 421 ms, total: 3min 16s
Wall time: 3min 16s